### ISSUE TITLE
Sweeping Edge False Positive [Kill Aura]

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#100]
## How you trigger the false positive?
A sword with sweeping edge will trigger up as kill aura and disable it

## Verbose Message:
Player is using combat hacks 9Kill Aura)

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version**: Latest
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: Latest

**Comment by ignPerformance** [comment]
Could you provide the exact verbose messages found in your Matrix log files?

Also, if possible, make a video.

**Comment by ignPerformance** [comment]
I can't reproduce this at all.

**Comment by ignPerformance** [comment]
This is NOT invalid. I reproduced this here: https://pastebin.com/raw/Nuqddyeg
