### ISSUE TITLE
[BYPASS] Jesus check

### ISSUE THREAD

**Issue by zera0mykerd** [jiangdashao/Matrix-Issues#1000]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**LiquidBounce1.8.9-b66**: 
**https://liquidbounce.net/**: 
**WaterWalk/Jesus**: 
**[i don't have video]**: 
**WaterWalk vertical for aac bypass the jesus chest, this module it allows you to perform skips on the water and it also bypasses the vertical control**: 

## Configuration Files
**[Default Checks]**: 
**[Default Config]**:

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/69716611-53871a00-1145-11ea-99e0-d17e2996d0a9.png)

**Comment by zera0mykerd** [comment]
https://youtu.be/RcxI4dSGoqQ
