### ISSUE TITLE
[FP] False positives mostly on one specific player

### ISSUE THREAD

**Issue by realsnowy** [jiangdashao/Matrix-Issues#1001]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.14.4 (Build 186)
**Verbose messages**: N/A
**How/when does this happen**: When the player performs actions
**Video of false positive**: *Currently none as I have no time, but I will ask if he can give his POV*, ***but I do have a log file showing all the flags he is triggering and the frustration he puts in chat when talking to another player*** - https://pastebin.com/nZmZPYq7
**Other information**: (Mostly) only happens with this specific player (**spkcz**)

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/pZ0fPDYh
**Link to config.yml file**: https://pastebin.com/zGiFq3EU

**Comment by jiangdashao** [comment]
1. You need to record a video to proof it
2. You need to provide the verbose message output when the player gets kicked(/matrix verbose)

After you provided the evidence, the issue will reopen
