### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1006]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(19:56:56) player Fly | ground spoof | tag: fake air packet | at: 11.59,15.0,46.3 t: 15.597,20.353,53.826 (+7) | vl:31 ping:38 tps:20.0 component: fly.fg.air
(19:56:58) player Fly | suspicious movement:0.0 predict:-1.139 air_t:12 tag:m4 (+10) | vl:41 ping:38 tps:20.0 component: fly.main
(19:56:58) player Fly | ground spoof | send ground packets when falling | d: 5.96204786295212 (+5) | vl:46 ping:38 tps:20.0 component: fly.fg.nofall
(19:56:58) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 1.139458865433098 val3: true (+10) | vl:56 ping:38 tps:20.0 component: nofall.packet

**How/when does this happen**: i jumped from a block and died from 5 blocks distance
**Video of false positive**: -
**Other information**: 1.14 client, it doesn't matter i think

## Configuration Files
**Link to checks.yml file**: -

**Comment by ZakShearman** [comment]
Think this is a bit different, but here's a video of something similar: https://zak.pink/Violet-Kiskadee-3923.mp4

**Comment by DanielAlves123** [comment]
What??? I just died by jumping!!! @jiangdashao 
(21:34:40) player Fly | suspicious movement:-0.121 predict:-0.445 lm:-0.374 hard_pred:-0.445 sev_pred:-0.377 air_t:11 fall_t:6 g:-- tag:gn (+5) | vl:12 ping:38 tps:19.98 component: fly.main
(21:34:40) player Fly | ground spoof | t:fgw a=0.41999998688697815 b=-0.447 (+4) | vl:16 ping:38 tps:19.98 component: fly.fg.w
(21:34:40) player Fly | t: af (+5) | vl:21 ping:38 tps:19.98 component: nofall.air

**Comment by jiangdashao** [comment]
video?

**Comment by DanielAlves123** [comment]
@jiangdashao I don't have recording environment and I don't think video is needed.

**Comment by DanielAlves123** [comment]
@jiangdashao player reported being dragged back under the map i think it's similar problem
(21:14:36) player Speed | suspicious movement:0.091 expect:0.09 t:13 fr:0.6 tag:a (+9) | vl:23 ping:52 tps:19.6 component: speed.main
(21:14:36) player Speed | suspicious movement:0.091 expect:0.09 t:12 fr:0.6 tag:a (+9) | vl:32 ping:52 tps:19.6 component: speed.main
(21:14:36) player Speed | suspicious movement:0.091 expect:0.9 0t:14 fr:0.6 tag:a (+9) | vl:41 ping:52 tps:19.6 component: speed.main
(21:14:39) player  Fly | suspicious movement:-2.433 predict:-2.372 lm:-2.341 hard_pred:-2.372 sev_pred:-2.463 air_t:12 fall_t:46 g:-- tag:gn (+5) | vl:5 ping:52 tps:20.0 component: fly.main

**Comment by DanielAlves123** [comment]
same thing:
(21:55:34) player Fly | ground spoof | send ground packets when falling | d: 4.766078245531013 (+5) | vl:12 ping:58 tps:20.0 component: fly.fg.nofall
(21:55:34) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 4.844478247056891 val3: true (+10) | vl:22 ping:58 tps:20.0 component: nofall.packet
(21:55:34) player Fly | suspicious movement:-0.231 predict:-0.231 air_t:3 tag:g8 (+6) | vl:28 ping:58 tps:20.0 component: fly.main
(21:55:34) player Fly | suspicious movement:-0.304 predict:-0.304 air_t:4 tag:g8 (+6) | vl:34 ping:58 tps:20.0 component: fly.main
(21:55:34) player Fly | suspicious movement:-0.377 predict:-0.377 air_t:5 tag:g8 (+6) | vl:40 ping:58 tps:20.0 component: fly.main
(21:55:34) player Fly | suspicious movement:-0.447 predict:-0.447 air_t:6 tag:g8 (+6) | vl:46 ping:58 tps:20.0 component: fly.main
(21:55:34) player Fly | suspicious movement:-0.517 predict:-0.517 air_t:7 tag:g8 (+6) | vl:52 ping:58 tps:20.0 component: fly.main
(21:55:34) player Fly | suspicious movement:-0.585 predict:-0.585 air_t:8 tag:g8 (+6) | vl:58 ping:58 tps:20.0 component: fly.main
(21:55:36) player Fly | suspicious movement:-2.866 predict:-2.341 lm:-2.308 hard_pred:-2.341 sev_pred:-2.887 air_t:12 fall_t:45 g:-- tag:gn (+5) | vl:63 ping:58 tps:20.0 component: fly.main
(21:55:36) player Fly | suspicious movement:-2.866 predict:-2.341 air_t:12 tag:g8 (+6) | vl:69 ping:58 tps:20.0 component: fly.main

**Comment by jiangdashao** [comment]
if still no video proof, the issue will be closed

**Comment by SkyLicks** [comment]
I know a free, simple to use video recorder. Extremely self-explanatory. It is called Bandicam. Download at https://www.bandicam.com/.

When you have a video, sign in and upload to https://youtube.com.

@DanielAlves123

**Comment by DanielAlves123** [comment]
@jiangdashao https://share.getcloudapp.com/v1umoLj7

**Comment by Rigagit** [comment]
I have such cases. players are built upward, they are teleported down for the fly and killed because of nofall

**Comment by jiangdashao** [comment]
I can't reproduce the false positive

**Comment by DanielAlves123** [comment]
@jiangdashao you have videos, when under you is the void it will teleport you to the void not to the last correct location

**Comment by jiangdashao** [comment]
No, it's correct, if you get detected by Fly check, you are standing on the void, so Matrix teleports you to the void. ^^

**Comment by DanielAlves123** [comment]
@jiangdashao you are standind on the edge, so you should be teleported to the edge not to the void... first of all you shouldn't be teleported for running.
