### ISSUE TITLE
[REQUEST] Safe Ping Amount

### ISSUE THREAD

**Issue by timmehz** [jiangdashao/Matrix-Issues#1007]
**What features/checks do you need?:**
Add a safe ping to the config.yml file in Matrix, this would help if the ping is really high for some people then matrix would be disabled for that 1 person and they will become safe from being reported in the anti-cheat.

**Comment by jiangdashao** [comment]
Already had one
![image](https://user-images.githubusercontent.com/21152113/69843917-90b5ee00-12a4-11ea-9add-d13ea798e307.png)
