### ISSUE TITLE
[FP] Vehicle Check

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#1009]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 
**Verbose messages**: 
![Screenshosefseft_1](https://user-images.githubusercontent.com/20980266/69835664-ec329e00-1208-11ea-8a20-b1bd8d13a488.png)

**How/when does this happen**: When a player tries to jump with a horse
**Video of false positive**:  https://youtu.be/l8IRm9LxLNI
**Other information**: 

This seems to be a very specific case scenario. Only a few people have managed to false flag this check, so it seems to only happen to specific players. Additionally, it only happens on a specific horse. (I'm assuming a horse that can jump really high?)

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I can't reproduce the false positive, but I improved the vehicle check, hope it will working
