### ISSUE TITLE
Forward movement on horse [Fly/Speed]

### ISSUE THREAD

**Issue by FlakMagnet** [jiangdashao/Matrix-Issues#101]
Please note:  This report may seem to be a duplicate of https://github.com/jiangdashao/Matrix-Issues/issues/76 but the issue persists in Matrix Version 1.7.5.

## How you trigger the false positive?
Using a tamed horse and a saddle.
Ride Horse, and attempt to walk forward.  (Please note: A, S, D, walking backwards or to the side with a Horse will not trigger false positives, only walking forward.)
The player is dismounted from the horse and both the player and the horse "rubber-band" back to where the forward movement started.

I conducted the test twice, first time the player was whitelisted on the server and the error did not occur.  Error also does not occur with opped or staff players.

## Verbose Message:
(15:58:03) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:4 ping:65 tps:19.67
(15:58:07) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:8 ping:65 tps:19.68
(15:58:53) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4102941276106743 (+5) | vl:5 ping:56 tps:19.76
(15:58:53) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:4 ping:56 tps:19.76
(15:59:00) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4219906506085261 (+5) | vl:10 ping:56 tps:19.74
(15:59:00) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:8 ping:56 tps:19.74
(15:59:06) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4270307480908439 (+5) | vl:15 ping:56 tps:19.94
(15:59:06) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:12 ping:56 tps:19.94
(15:59:07) JoePlayer failed Speed check | type E: a=1.9235048047570922 b=0.46499999999999997 t=a (+5) | vl:20 ping:56 tps:19.94
(15:59:07) JoePlayer failed Speed check | type E: a=1.9235048047570922 c=12 lm=0.0 t:d (+15) | vl:35 ping:56 tps:19.94
(15:59:07) JoePlayer failed Fly check | fast fall:a  (+7) | vl:19 ping:56 tps:19.94
(15:59:10) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4438254782513752 (+5) | vl:40 ping:55 tps:19.89
(15:59:10) JoePlayer failed Fly check | t:e m=0.0 tk=10 et=5 vy=-0.0784000015258789 (+4) | vl:23 ping:55 tps:19.89
(15:59:10) JoePlayer failed Speed check | type E: a=2.07477137217919 b=0.46499999999999997 t=a (+5) | vl:45 ping:55 tps:19.89
(15:59:10) JoePlayer failed Speed check | type E: a=2.07477137217919 b=0.41500000000000004 t:c (+10) | vl:55 ping:55 tps:19.89
(15:59:10) JoePlayer failed Fly check | fast fall:a  (+7) | vl:30 ping:55 tps:19.89
(15:59:13) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.42085883028471605 (+5) | vl:60 ping:55 tps:19.96
(15:59:13) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:34 ping:55 tps:19.96
(15:59:13) JoePlayer failed Speed check | type E: a=1.9577007086853644 b=0.46499999999999997 t=a (+5) | vl:65 ping:55 tps:19.96
(15:59:13) JoePlayer failed Speed check | type E: a=1.9577007086853644 c=12 lm=0.0 t:d (+15) | vl:80 ping:55 tps:19.96
(15:59:13) JoePlayer failed Fly check | fast fall:a  (+7) | vl:41 ping:55 tps:19.96
(15:59:15) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.44605094366514236 (+5) | vl:85 ping:55 tps:19.88
(15:59:15) JoePlayer failed Fly check | t:e m=0.0 tk=10 et=5 vy=-0.0784000015258789 (+4) | vl:45 ping:55 tps:19.88
(15:59:18) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4376862734466004 (+5) | vl:40 ping:55 tps:19.81
(15:59:18) JoePlayer failed Speed check | type E: a=1.67620424249525 b=0.46499999999999997 t=a (+5) | vl:45 ping:55 tps:19.81
(15:59:18) JoePlayer failed Speed check | type E: a=1.67620424249525 b=0.41500000000000004 t:c (+10) | vl:55 ping:55 tps:19.81
(15:59:18) JoePlayer failed Fly check | fast fall:a  (+7) | vl:12 ping:55 tps:19.81
(15:59:36) JoePlayer failed Speed check | entity speed | type: horse | distance: 0.4259438564003172 (+5) | vl:60 ping:55 tps:19.87
(15:59:36) JoePlayer failed Fly check | t:e m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+4) | vl:16 ping:55 tps:19.87
(15:59:36) JoePlayer failed Speed check | type E: a=1.782551168279825 b=0.46499999999999997 t=a (+5) | vl:65 ping:55 tps:19.87
(15:59:36) JoePlayer failed Speed check | type E: a=1.782551168279825 c=12 lm=0.0 t:d (+15) | vl:80 ping:55 tps:19.87
(16:59:36) JoePlayer failed Fly check | fast fall:a  (+7) | vl:23 ping:55 tps:19.87

## Videos:
No video was captured.

## Server Infomation
**Matrix Version**:  Matrix version 1.7.5
**Server Version**:  git-Paper-597 (MC: 1.13.2)
**ProtocolLib Version**: ProtocolLib version 4.4.0

**Comment by ignPerformance** [comment]
I can't reproduce this at all.

**Comment by FlakMagnet** [comment]
Are you interested in visiting the server to see it first hand?  If so please coordinate and I'll be sure to be online if/when you do.

**Comment by ignPerformance** [comment]
Add me on Discord at Performance#1955
Let's coordinate.
