### ISSUE TITLE
[FP] Cobblestone generator reports a false flag

### ISSUE THREAD

**Issue by timmehz** [jiangdashao/Matrix-Issues#1010]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.12.2 PaperSpigot
**Verbose messages**: [Matrix] <player username> tried to illegally interact with Entiity/Block
**How/when does this happen**: It happens when a person mines a block from a cobblestone generator and the person goes inside of the block just before the generator generates a new block then once the generator generates a new block it pushes the player outside of the block.
**Video of false positive**: No video sorry.
**Other information**: No other information except of the question "How/when does it happen".

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/kkHGn4BG

**Comment by jiangdashao** [comment]
Please provide the verbose messages
/matrix verbose
