### ISSUE TITLE
[FP] Fly after join

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1014]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(23:15:48) player Fly | ground spoof | t: fgw.2 a=67.16610926093821 b=-0.1552320045166016 c=0.08307781780646906 (+10) | vl:10 ping:0 tps:19.99 component: fly.fg.w2
(23:15:48) player Fly | t: af (+5) | vl:15 ping:0 tps:19.99 component: nofall.air
 (23:15:55) player Fly | ground spoof | t: fgw.2 a=67.24918707874468 b=-0.30431682745754424 c=0.003016261509046103 (+10) | vl:10 ping:0 tps:20.0 component: fly.fg.w2
(23:15:55) player Fly | t: af (+5) | vl:15 ping:0 tps:20.0 component: nofall.air

**How/when does this happen**: when you join the server and run while jumping with sprint it will drag you back and detect fly
**Video of false positive**: not needed
**Other information**: 1.14 client version, should happen on every version

## Configuration Files
**Link to checks.yml file**: -

**Comment by DanielAlves123** [comment]
@jiangdashao still exists.
(00:34:05) player Speed | suspicious movement:0.392 expect:0.3825 predict:0.08275356128795708 fr:0.6 tag:ea (+5) | vl:5 ping:0 tps:20.0 component: speed.main
(00:34:05) player Fly | suspicious movement:0.42 predict:-0.078 vel:-0.078 air_t:2 tag:vt (+5) | vl:5 ping:0 tps:20.0 component: fly.main
(00:34:06) player Speed | suspicious movement:0.397 expect:0.3825 predict:0.09297358842421535 fr:0.6 tag:ea (+5) | vl:10 ping:0 tps:20.0 component: speed.main
(00:34:06) player Fly | suspicious movement:0.42 predict:-0.078 vel:-0.078 air_t:4 tag:vt (+5) | vl:10 ping:0 tps:20.0 component: fly.main

**Comment by jiangdashao** [comment]
not ground spoof, unimportant

**Comment by DanielAlves123** [comment]
@jiangdashao but still it's dragging back after join.
