### ISSUE TITLE
[FP] Suffocation triggers phase

### ISSUE THREAD

**Issue by acyis** [jiangdashao/Matrix-Issues#1015]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: https://gyazo.com/d24c43edfe03bc7fab7fe89636e1e291
**How/when does this happen**: When player suffocates in a block.
**Video of false positive**: https://gyazo.com/9ec57504b4f987169cf21e37b4d1f11c
**Other information**: Works on default checks.yml and config.yml

## Configuration Files
**Link to checks.yml file**: Works on default checks.yml and config.yml

**Comment by jiangdashao** [comment]
Phase check is a very unstable check, please don't make it auto-ban players
