### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1018]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(10:47:22) player  Fly | ground spoof | tag: fake air packet | at: 22.143,60.0,60.59 t: 7.669,60.0,33.223 (+7) | vl:7 ping:43 tps:20.0 component: fly.fg.air
(10:47:23) player Fly | ground spoof | tag: fake air packet | at: 21.185,60.0,59.717 t: 7.669,60.0,33.223 (+7) | vl:14 ping:43 tps:20.0 component: fly.fg.air
(10:47:33) player Fly | ground spoof | send ground packets when falling | d: 13.204051351727486 (+5) | vl:19 ping:43 tps:20.0 component: fly.fg.nofall
(10:47:33) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 13.204051351727486 val3: true (+10) | vl:29 ping:43 tps:20.0 component: nofall.packet
(10:47:34) player Block | abort breaking | dig | block at: -1.0,65.0,-3.0 type: STAINED_CLAY (+0) | vl:0 ping:43 tps:20.0 component: block.abort
(10:47:36) player Fly | ground spoof | tag: fake air packet | at: -0.515,66.0,-3.689 t: 0.644,66.0,-1.5 (+7) | vl:7 ping:43 tps:19.99 component: fly.fg.air
(10:47:38) player Fly | ground spoof | tag: fake air packet | at: 0.686,66.0,-13.809 t: 0.644,66.0,-1.5 (+7) | vl:14 ping:43 tps:20.0 component: fly.fg.air

**How/when does this happen**: I jumped from above while sprinting and going forward and it dragged me back when I landed or near landing and killed.
**Video of false positive**: not needed
**Other information**: i jumped from heigh that shouldn't kill me

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
No evidence
If you still can't follow the reporting rules, you will get banned

**Comment by jiangdashao** [comment]
Please try to test it in a clean environment (Only installed plugin: Matrix+ProtocolLib), and then record a video for it (Remember to enable the verbose messages output)

**Comment by DanielAlves123** [comment]
@jiangdashao I send you obvious bugs, there's no need to record a video...
