### ISSUE TITLE
[REQUEST] Click Macro Detection

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1019]
**What features/checks do you need?:**

A click macro is well, a macro for clicking. Particularly, the Razer mouses come with a macro recorder, allowing to to record your clicks, and then allowing to to play them back in a macro. This essentially allows for organic autoclickers.

But, since usually, these click macros are usually repetitive, I think it might be possible to detect them. I am suggesting a check that analyzes a players clicking over an x amount of time searching for patterns.

Example:
Click after 0.044s
Click after 0.04s
Click after 0.053s
Click after 0.038s
Click after 0.055s
Click after 0.035s
Repeat

Then, Matrix could detect the repetition of clicks patterns. Please let me know if you want me to make anything more clear. Thanks.

**Comment by jiangdashao** [comment]
No, this has little effect. Due to the network delay fluctuations, these time intervals are not accurate, and it is difficult to find macro patterns in them. :(
