### ISSUE TITLE
[FP] False Positive KillAura

### ISSUE THREAD

**Issue by EfePro9ProOfTheLife** [jiangdashao/Matrix-Issues#1020]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Spigot 1.8.8**: 
**No verbose**: 
**When i move my head fast not really fast but fast i get kicked for "[Matrix]KillAura"**: 
**http://www.mediafire.com/file/ez6kt56y6woog4q/2019-12-04_18-23-16.mp4/file**: 
**Matrix 2.7.4 to .2.7.5**: 

## Configuration Files
**http://www.mediafire.com/file/55wwtexxrr77s8e/config.yml/file**:

**Comment by jiangdashao** [comment]
It is not a false positive, you are using Wurst client, it will trigger KillAura/Speed detection, even you didnt enable any modules
