### ISSUE TITLE
[BYPASS] WWE Utility Mod | Blink Bypass

### ISSUE THREAD

**Issue by KristsxD** [jiangdashao/Matrix-Issues#1021]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: WWE Utility Mod
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: Blink
**Video of bypass**: https://streamable.com/op6gi
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://mega.nz/#!bZZxFIjY!iw9e5REHQCHaBqfgsCjA04mAY9qUTyF-XljeiMgWFPU
**Link to config.yml file**: https://mega.nz/#!fAZjzKba!a4IXscqnnpq5WRguBuIwpv4GifFuDf-uiYfm4YHHYTo

**Comment by Olly32** [comment]
Tested on 1.14.4 with no bypass. Seems like a pre-1.13 issue

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/70240282-e8be8a00-17a7-11ea-95b0-bb1910b45706.png)

**Comment by jiangdashao** [comment]
Maybe you are not using Matrix correctly

**Comment by KristsxD** [comment]
How I can't use the Matrix correctly? if all that I did is installed the plugin in my plugin list and nothing configured? :D

**Comment by jiangdashao** [comment]
I don't know
Maybe caused by permission, maybe some plugins incompatibility

**Comment by KristsxD** [comment]
Okay, thanks.
