### ISSUE TITLE
Water False Positive [Fly]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#103]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
https://pastebin.com/raw/PMgEyqH9

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogtqMceLkgeUUsvog

## Server Infomation
**Matrix Version**: 1.8.0
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
