### ISSUE TITLE
[BYPASS] ClickAimbot Bypass

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1034]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Hacked client**: Wolfram 1.12.2
**Link to hacked client**: https://github.com/Wurst-Imperium/Wolfram-MCX2/releases/download/v9.8/Wolfram-v9.8-MC1.12.zip
**Cheat that bypassed**: ClickAimbot
**Video of bypass**: https://youtu.be/cgBE0FChgzI
**Other information**: PS. Congrats on 1k+ closed issues!

## Configuration Files
Link to checks.yml file: https://pastebin.com/b8GnLWkN
Link to config.yml file: https://pastebin.com/4NNkPqvM

**Comment by jiangdashao** [comment]
Did you enable premium user mode to test it?

**Comment by SkyLicks** [comment]
Yes. When I tested it with premium mode, I only got a few ka.pt.
