### ISSUE TITLE
[REQUEST] Aimbot Check

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1035]
**What features/checks do you need?:**
I want to request an aimbot check that checks if a person is constantly aiming at an entity. I think this check would particularly be useful for the many FPS (first person shooter) servers out there. But, I do understand if you don't add this :)

Anyways, here is an example:
https://youtu.be/25fkuhfun3U

(In this example, I am using Wolfram which lets you configure your aimbot's range to up to 30 blocks)

**Comment by jiangdashao** [comment]
impossible

**Comment by Olly32** [comment]
doesn't matrix already have this as a check? I believe its called pitch.t5 or something and is a premium check.
