### ISSUE TITLE
[REQUEST] Extensions on to matrix.bypass perm

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1037]
**What features/checks do you need?:**

I want to request adding more permissions extending the flexibility of matrix.bypass to allow players to ONLY bypass certain checks.

For example instead of just a Matrix.Bypass:

Matrix.Bypass.Fly would allow user to bypass only Fly checks.

Matrix.Bypass.Speed would allow iser to bypass only KillAura checks

Matrix.Bypass.Inventory would allow users to bypass only the inventory checks

And so on...

I think it will be useful for situations where custom plugins create false positives with only a certain check only under certain conditions. Specifically, due to custom plugins we use, Fly and speed false positives can ring in the hubs or spawn. So we could disable those checks just in the spawn worlds using some permission plugin.

**Comment by jiangdashao** [comment]
Matrix's code architecture seems to make this a bit difficult to implement, which may affect performance :(

**Comment by SkyLicks** [comment]
Ok. I understand :(
