### ISSUE TITLE
[FP] Fly? Got killed

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1045]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(18:39:33) player Fly | ground spoof | normal | val1: 49.91253016538879 (+5) | vl:5 ping:67 tps:20.0 component: fly.fg.simple
(18:39:33) playerFly | send illegal packet to anti fall damage |  val1: 0.0 val2: 0.06292580855811991 val3: true (+10) | vl:15 ping:67 tps:20.0 component: nofall.packet
 
**How/when does this happen**: i was on top of water trying to move from it and it instantly killed me
**Video of false positive**: not needed
**Other information**: what happened? 1.14 client

## Configuration Files
**Link to checks.yml file**: -

**Comment by Olly32** [comment]
send video or else author most likely cannot fix

**Comment by DanielAlves123** [comment]
@Olly32 maybe its a feature like some of the bugs that i report?

**Comment by jiangdashao** [comment]
no video

**Comment by DanielAlves123** [comment]
@jiangdashao but you have detailed description of how this happened.
