### ISSUE TITLE
[BYPASS] Fast Speed bypass

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#1046]
**Server version**: 1.8
**Hacked client**: (Custom client)
**Link to hacked client**: Discord 😄 
**Cheat that bypassed**: Speed
**Video of bypass**: https://youtu.be/j94MtWTK2fw
**Other information**: the client is made by a friend who has instructed to keep it private (will send link in discord tho).
*tested on tree.ac*

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/70770993-9504ff80-1daa-11ea-930c-582a8f4d1c88.png)
Can't bypass
