### ISSUE TITLE
Bed False Positive [Speed]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#105]
## How you trigger the false positive?
Run and hit a near frame perfect jump at this angle on a bed. Watch the video.

## Verbose Message:
https://pastebin.com/raw/k2pJzYnR

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgoguk589-xiiHTr_vQ

## Server Infomation
**Matrix Version**: 1.8.0
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Update, found a better way of reproducing this: https://1drv.ms/v/s!ApY4tKsF8vPUgogvekTbsO_ai-an1g

**Comment by jiangdashao** [comment]
Fixed
