### ISSUE TITLE
[BYPASS] Flight Bypass

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1051]
## Issue Information
**Server version**: 1.14.4
**Hacked client**: WWE
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: Flight, using hypixel module
**Video of bypass**: https://www.youtube.com/watch?v=ZofAfLOrlgg&feature=youtu.be
other info: this cheat is detected on treeac which is 1.8 i think

**Comment by jiangdashao** [comment]
video broken

**Comment by Rasputing** [comment]
My bad, here is a working link: https://youtu.be/ZofAfLOrlgg (needs to process)
