### ISSUE TITLE
[REQUEST] Checks Wiki

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1056]
**What features/checks do you need?:**

I want to request adding a wiki section on what each check means. Yes, some checks are straight forward like ka.aa (aimassist) or ka.ac.cps (cps) because it says what it means in the verbose message. But other checks like speed.spin, speed.sprint, other lesser known hacks, oh and the t1, t2 checks, what do those mean?

I also suggest including how reliable these checks are, and what does it mean if someone is triggering them. For example, if someone triggers a check for 100 cps, they are 100% hacking. But if someone triggers a few ka.post, that could be a false positives. So I just wanted to suggest adding this information to help out server moderators and admins through some sort of wiki.

Thanks.

**Comment by jiangdashao** [comment]
I am lazy :(

**Comment by SkyLicks** [comment]
xD <3

**Comment by True-cc** [comment]
You are lazy. I have proof if you want some. Stop being lazy. You're turning into Marco. Stop it.

**Comment by gogorz** [comment]
> You are lazy. I have proof if you want some. Stop being lazy. You're turning into Marco. Stop it.
true unfortunately
