### ISSUE TITLE
[FP] Kill after map change

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1058]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(13:57:42) player Fly | ground spoof | tag: fake air packet | at: -135.965,28.0,-163.091 t: -141.503,27.0,-156.464 (+7) | vl:21 ping:23 tps:19.99 component: fly.fg.air
(13:57:42) player Fly | ground spoof | tag: fake air packet | at: -136.009,28.0,-163.038 t: -141.503,27.0,-156.464 (+7) | vl:28 ping:23 tps:19.99 component: fly.fg.air
(13:57:43) player Fly | ground spoof | tag: fake air packet | at: -136.009,28.0,-163.038 t: -141.503,27.0,-156.464 (+7) | vl:35 ping:23 tps:19.99 component: fly.fg.air
(13:57:47) player Fly | suspicious movement:0.42 predict:-0.078 vel:-0.078 air_t:2 tag:vt (+5) | vl:40 ping:23 tps:20.0 component: fly.main
(13:57:47) player Fly | suspicious movement:0.333 predict:0.333 vel:0.42 air_t:3 tag:vt (+5) | vl:45 ping:23 tps:20.0 component: fly.main
(13:57:47) player Fly | ground spoof | t: fgw.2 a=127.24918707874468 b=-0.1552320045166016 c=0.003016261509046103 (+10) | vl:55 ping:23 tps:20.0 component: fly.fg.w2
(13:57:47) player Fly | t: af (+5) | vl:60 ping:23 tps:20.0 component: nofall.air

**How/when does this happen**: Player was jumping, he changed map and it killed him
**Video of false positive**: Player got killed after changing map
**Other information**:  Player was jumping, he changed map and it killed him

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
...

**Comment by DanielAlves123** [comment]
@jiangdashao what happened?

**Comment by DanielAlves123** [comment]
@jiangdashao it happened again! I teleported to another map, I tried to place block and it killed me
(18:24:52) player Fly | ground spoof | tag: fake air packet | at: -141.48,27.0,-156.968 t: -141.503,27.0,-156.464 (+7) | vl:7 ping:0 tps:20.0 component: fly.fg.air
(18:24:53) player Speed | suspicious movement:0.478 expect:0.40499999999999997 fr:0.6 tag:ea (+5) | vl:5 ping:0 tps:20.0 component: speed.main
(18:25:22) player Fly | ground spoof | t: fgw.2 a=69.24918707874468 b=-0.44749789698341763 c=0.003016261509046103 (+10) | vl:10 ping:48 tps:20.0 component: fly.fg.w2
(18:25:22) player Fly | t: af (+5) | vl:15 ping:48 tps:20.0 component: nofall.air

**Comment by DanielAlves123** [comment]
@jiangdashao still exists. Fix bugs that I report...
