### ISSUE TITLE
Door False Positive [Phase]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#106]
## How you trigger the false positive?
Spam-click a door, walk in and out of it until you flag for phase.
This is critical in my opinion. Doors should never be white-listed for Phase as they are typically the block phased into the most.

## Verbose Message:
https://pastebin.com/raw/12Me3npn

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogxu4ZmfGXxMKw3zQ

## Server Infomation
**Matrix Version**: 1.8.0
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
