### ISSUE TITLE
[FP] Got killed after jumping from 10 blocks

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1060]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(21:39:35) player Fly | ground spoof | normal | val1: 10.04262784873682 (+5) | vl:5 ping:39 tps:19.97 component: fly.fg.simple
(21:39:35) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 1.3334844818430547 val3: true (+10) | vl:15 ping:39 tps:19.97 component: nofall.packet

**How/when does this happen**: I was coming down in water when I was like 10 blocks near the floor I jumped on it and died with full hp and armor.
**Video of false positive**: I was coming down in water when I was like 10 blocks near the floor I jumped on it and died with full hp and armor.
**Other information**: I was coming down in water when I was like 10 blocks near the floor I jumped on it and died with full hp and armor. 1.14 client version

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
...no video

**Comment by DanielAlves123** [comment]
@jiangdashao you have "How/when does this happen" and verbose messages so why you need video?
