### ISSUE TITLE
[FP] Transparent blocks & teleport

### ISSUE THREAD

**Issue by nicuch** [jiangdashao/Matrix-Issues#1061]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper version git-Paper-225 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Verbose messages**: none, sorry
**How/when does this happen**: When a player join for the first time, it gets teleported to another world (where the spawn is) and because under them is a transparent block (stained glass to be exactly), until the chucks load the player get inside that block and the server is trying to correct (re-sync) it and it teleports where it should be. The thing is that the player gets kicked for flying.
**Video of false positive**: none yet, if I catch it in action, i'll do it
**Other information**: If the player connects again, it can happen again. That prevents new players from joining the server.

## Configuration Files
**Link to checks.yml file**: https://gist.github.com/nicuch/81350c3d873dd6775d0be142a4546408

**Comment by jiangdashao** [comment]
video pls

**Comment by nicuch** [comment]
I tried to repeat the false positive myself but I can't get it to work... maybe happened because of high ping.
