### ISSUE TITLE
False Positive for tridents and riptide

### ISSUE THREAD

**Issue by EchoRapidz** [jiangdashao/Matrix-Issues#1063]
I have my matrix config set to ban players at VL5000
A player was using riptide and a trident and somehow got that high.
The player has more info, and a video here:
https://rapidzsurvival.xyz/index.php?route=/forum/topic/71-false-ban-caused-by-riptide-trident/

**Comment by jiangdashao** [comment]
It was caused by "Player Weather", it's "fake" weather, the plugin sends weather packets to the player, but this weather is not on the server, so the server thinks it is not in Riptide. I can't fix it :(

**Comment by SkyLicks** [comment]
@EchoRapidz I suggest just disabling the specific check that did that.
