### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1065]
**What features/checks do you need?:**

I think I requested this before but you ran in to some errors. Recently, with Minecraft 1.15, mojang shared some of its source code making working with nms easier. So I don't know if you can do it now but,

I want to request adding a fake health packets feature (AKA Healthspoof) making health indicators hacks and mods useless.

I know its possible to do via protocol lib. Horizon has a similar feature.

Thanks.

**Comment by jiangdashao** [comment]
I tried coding this feature, but it caused strange visual bugs, so I gave up this feature, not because of the obfuscation of Minecraft
