### ISSUE TITLE
[BUG] Relog-time triggers for all kicks

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1066]
**Server version**: 1.14
**what happens**:  relog time in config.yml is applied to all kicks, whether they are from matrix or not. This means I cannot use it to 'tempban' players for a certain amount of seconds for cheating. Please make this only trigger on matrixkickevent. Thanks

**Comment by jiangdashao** [comment]
"This means I cannot use it to 'tempban' players for a certain amount of seconds for cheating."?

**Comment by Rasputing** [comment]
Yes, I set the relog time to 60 seconds so when matrix kicks players they need to wait a while before joining back again.
