### ISSUE TITLE
[BYPASS] KillAura Detection Bypass

### ISSUE THREAD

**Issue by CookieLord333** [jiangdashao/Matrix-Issues#1067]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Hacked client**: Impact (Latest Version)
**Link to hacked client**: https://impactclient.net/
**Cheat that bypassed**: If you turn on lag (or if the player lags because of poor internet), KillAura isnt detected. This also happens when you turn on the accuracy of hits to a really low number like 0.2-0.4
**Video of bypass**: https://www.youtube.com/watch?v=x1QR2MW1vSs&feature=youtu.be
**Other information**: I actually ended up leaving my computer with this going for like 15 minutes and I still wasnt kicked after 15 minutes. If the player lags or they use a ping spoofer/lag the packets, KillAura is failed to be detected.

## Configuration Files
**Link to checks.yml file**: Its the Matrix Test Server found on the spigotmc page, I dont have it but I assume its the default one.
**Link to config.yml file**: Its the Matrix Test Server found on the spigotmc page, I dont have it but I assume its the default one.

**Comment by jiangdashao** [comment]
Can be detected in premium mode
