### ISSUE TITLE
2-High Ceiling False Positive [Speed Type A]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#107]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
Player failed Speed check | type A : m=0.48 e=0.2873 (+1) | vl:1 ping:253 tps: 19.97

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgog3-2GW9lXvJOU7Cw

## Server Infomation
**Matrix Version**: 1.8.0
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
I think it's not important, it just adds 1 vl

**Comment by ignPerformance** [comment]
Re-opening: https://1drv.ms/v/s!ApY4tKsF8vPUgohIAkGg9B35ERjFWw

**Comment by ignPerformance** [comment]
Re-opening: https://1drv.ms/v/s!ApY4tKsF8vPUgohIAkGg9B35ERjFWw

**Comment by jiangdashao** [comment]
Sorry, I don't want to fix this
