### ISSUE TITLE
[FP] Got killed in mid air

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1072]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(20:54:56) player Fly | ground spoof | send ground packets when falling | d: 9.588667243050018 (+5) | vl:5 ping:53 tps:19.99 component: fly.fg.nofall
(20:54:56) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 9.667067244575897 val3: true (+10) | vl:15 ping:53 tps:19.99 component: nofall.packet
**How/when does this happen**: i jumped down and got killed in mid air
**Video of false positive**: not needed
**Other information**: 1.14 client version

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
No video.......
