### ISSUE TITLE
[FP] Elytrahop fly false positive

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1074]
## Issue Information
**Server version**: 1.14.4
**How/when does this happen**: When a player elytrahops in slight lag conditions with speed 2 and goes into a bellyflop (perhaps server desync?)
**Video of false positive**: https://youtu.be/BltOv5AK_i4
**Other information**: This happens to my players often so a fix would be great.

**Comment by jiangdashao** [comment]
I only saw false positives from Speed and Fly, indicating that you are not using elytra on the server-side. I think this is caused by desync, and I have no way to resolve
