### ISSUE TITLE
[FP] Elytra False Positive

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1075]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 Paper (Im on a 1.14.4 client using viaversion)
**Verbose messages**: In the video
**How/when does this happen**: This usually tends to happen when you go up using rockets at a low angle (~5 degree angle?).
**Video of false positive**: (DMed you)
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
Outdated version, Elytra check has been recoded in 2.8.2
