### ISSUE TITLE
[FP] Players get kicked

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1078]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
`[09:08:45] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3 [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) [09:08:45] [Netty Epoll Server IO #3/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [09:08:45] [Netty Epoll Server IO #3/WARN]: at com.comphenix.tinyprotocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:550) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [09:08:45] [Netty Epoll Server IO #3/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) [09:08:45] [Netty Epoll Server IO #3/WARN]: at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [09:08:45] [Netty Epoll Server IO #3/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [09:08:45] [Netty Epoll Server IO #3/WARN]: at java.lang.Thread.run(Thread.java:748) [09:08:45] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IllegalArgumentException: unable to fit 2142105 into 3 [09:08:45] [Netty Epoll Server IO #3/WARN]: at net.minecraft.server.v1_8_R3.PacketPrepender.a(SourceFile:19) [09:08:45] [Netty Epoll Server IO #3/WARN]: at net.minecraft.server.v1_8_R3.PacketPrepender.encode(SourceFile:9) [09:08:45] [Netty Epoll Server IO #3/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [09:08:45] [Netty Epoll Server IO #3/WARN]: ... 31 more [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException [09:08:45] [Server thread/INFO]: player lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3`
**How/when does this happen**: players get kicked? maybe something wrong with setting real entity id?
**Video of false positive**: ?
**Other information**: 1.8 client

## Configuration Files
**Link to checks.yml file**: -

**Comment by Rasputing** [comment]
update protocollib?

**Comment by DanielAlves123** [comment]
@Rasputing it's the newest plib, but I think I have to change it to older version.

Recommended Versions
v4.5.0-SNAPSHOT for MC 1.15
v4.5.0-b429 for MC 1.8 thru 1.13.x
v3.7.0 for MC 1.0 thru 1.7.10

**Comment by jiangdashao** [comment]
idk
