### ISSUE TITLE
[FP] Fly kills players ('player died') 

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1079]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(22:40:43) player Fly | suspicious movement:-1.865 predict:-2.079 air_t:12 tag:g8 (+3) | vl:130 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-1.906 predict:-1.906 air_t:12 tag:g8 (+3) | vl:133 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-1.947 predict:-1.947 air_t:12 tag:g8 (+3) | vl:136 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-1.986 predict:-1.986 air_t:12 tag:g8 (+3) | vl:139 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-2.025 predict:-2.025 air_t:12 tag:g8 (+3) | vl:142 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-2.063 predict:-2.063 air_t:12 tag:g8 (+3) | vl:145 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-2.1 predict:-2.1 air_t:12 tag:g8 (+3) | vl:148 ping:186 tps:19.97 component: fly.main
(22:40:43) player Fly | suspicious movement:-2.136 predict:-2.136 air_t:12 tag:g8 (+3) | vl:151 ping:186 tps:19.85 component: fly.main
(22:40:43) player Fly | suspicious movement:-2.172 predict:-2.172 air_t:12 tag:g8 (+3) | vl:154 ping:186 tps:19.85 component: fly.main
(22:40:44) player  Fly | suspicious movement:-1.946 predict:-2.207 lm:-2.172 hard_pred:-2.207 sev_pred:-3.258 air_t:12 fall_t:91 g:-- tag:gn (+2) | vl:156 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-1.946 predict:-2.207 air_t:12 tag:g8 (+3) | vl:159 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-1.986 predict:-1.986 air_t:12 tag:g8 (+3) | vl:162 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.024 predict:-2.024 air_t:12 tag:g8 (+3) | vl:165 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.062 predict:-2.062 air_t:12 tag:g8 (+3) | vl:168 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.099 predict:-2.099 air_t:12 tag:g8 (+3) | vl:171 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.136 predict:-2.136 air_t:12 tag:g8 (+3) | vl:174 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.172 predict:-2.172 air_t:12 tag:g8 (+3) | vl:177 ping:186 tps:19.85 component: fly.main
(22:40:44) player Fly | suspicious movement:-2.207 predict:-2.207 air_t:12 tag:g8 (+3) | vl:180 ping:186 tps:19.85 component: fly.main
 
**How/when does this happen**: kills player after fly check
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**: -

**Comment by Rasputing** [comment]
Post a video please, a video is needed
