### ISSUE TITLE
[BYPASS] Speed bypass

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1086]
## Issue Information
**Server version**: 1.14.4
**Hacked client**: wwe
**Link to hacked client**: wweclient.com 
**Cheat that bypassed**: Speed
**Video of bypass**: discord
**Other information**: only with speed effect

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/71517343-89582380-28e8-11ea-8244-5d6a4cf1a749.png)
![image](https://user-images.githubusercontent.com/21152113/71517351-9248f500-28e8-11ea-977a-d0bf9e05c39f.png)

?
