### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by meerpaluten** [jiangdashao/Matrix-Issues#1088]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Error(s) found in console** 
[latest.log](https://github.com/jiangdashao/Matrix-Issues/files/3991733/latest.log): 
**How/when does this happen**: in the round when he changed the noknockback.

## Configuration Files
**Link to checks.yml file**:default 
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Please delete all config files
