### ISSUE TITLE
[REQUEST] Accounting for Player Velocity Alterations

### ISSUE THREAD

**Issue by ridarf** [jiangdashao/Matrix-Issues#1089]
**What features/checks do you need?:**
The plugin should account for velocity changes to the server, and would probably need to be added to the config.yml, or checks.yml.
My server has the velocity vector on the Y axis multiplied by 0.945, and 0.925 on the X, and Z axis, and being able to account for that would be extremely helpful in deterring false positives for the velocity check.

**Comment by jiangdashao** [comment]
You can disable the velocity patterns which cause false positive
