### ISSUE TITLE
Falling False Positive [Fly]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#109]
## How you trigger the false positive?
Watch the video. Very weird.

## Verbose Message:
https://pastebin.com/raw/K0c5AVsv

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgog9EJELO5-WwCOKKQ

## Server Infomation
Latest for everything. 1.8.0 matrix.

**Comment by jiangdashao** [comment]
I will only fix the "t: a" false positive
