### ISSUE TITLE
[FP] Spamming jump on blue ice 

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#1094]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: (In video)
**How/when does this happen**: Spam-jump + spint on blue ice with a block ontop of the player's head
**Video of false positive**: https://youtu.be/Zi3YEqFr7t4
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by Rasputing** [comment]
this issue is also for other slippy blocks such as regular ice
