### ISSUE TITLE
Anti-Knockback Bypass

### ISSUE THREAD

**Issue by AJFire14** [jiangdashao/Matrix-Issues#110]
## Bypass Infomation
**Hack Client**: Aristois Client (1.13)
**Bypassed Hacking Type**: Anti-Knockback
**Matrix Version**: 1.8.0
**Server Version**: 1.13.2

## Videos
https://vimeo.com/328143064

**Comment by ignPerformance** [comment]
Still exists.

**Comment by jiangdashao** [comment]
I can't fix it currently, I am thinking about code a better Velocity check
