### ISSUE TITLE
[REQUEST] Don't deny permission for matrix command on commandpreprocessevent

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1100]
**What features/checks do you need?:**
![image](https://user-images.githubusercontent.com/45826848/71380422-01f87080-25c7-11ea-8ff1-f91036b8744b.png)
players can easily see whether a server is running matrix by typing /matrix verbose, even with a command blocker

**Comment by jiangdashao** [comment]
wtf? I just check the permission in the #onCommand() method....Maybe you should check your command blocker
