### ISSUE TITLE
[FP] craftbook bouncing pistons

### ISSUE THREAD

**Issue by cicatrice74** [jiangdashao/Matrix-Issues#1101]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.15.1 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

**Server version**: 1.15.1
**Verbose messages**: False positive using craftbook's bouncing blocks
**How/when does this happen**: using craftbook's bouncing blocks

**Comment by Rasputing** [comment]
Video please

**Comment by cicatrice74** [comment]
I send u a video link 'bout the false positive, please let me know if u can insert craftbook features in a whitelist for the matrix plugin.

[https://youtu.be/2Omr6mYTAk8](url)

**Comment by jiangdashao** [comment]
Please provide the verbose messages
/matrix verbose
