### ISSUE TITLE
Customizable punishment type

### ISSUE THREAD

**Issue by Minkizz** [jiangdashao/Matrix-Issues#111]
Hello, I don't like Matrix Anticheat kicking the players for cheating. Instead, I would like to ban them for a customizable amounts of days (20 days is good), and also with a customizable ban/kick message. Is that possible? I really need that feature, I don't want to kick players for "[Matrix] Speed Hacks" but instead banning players for 20 days for "[TalvorGames] You got banned for: Speed Hacks". Thanks a lot.

**Comment by jiangdashao** [comment]
You can custom the punish commands for every check in the "checks.yml"

**Comment by Minkizz** [comment]
@jiangdashao: "yes you're right, I didn't saw that"
