### ISSUE TITLE
[REQUEST] Flexible check toleramce

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1114]
**What features/checks do you need?:**

Add a configurable tolerance value in to the matrix config to allow server owners and admins to manage for strict matrix is.

Can be useful for bypassing false positives, or using more strict checks. Moreover, can also be useful with plugin-compatitibility issues by adjusting different check tolerances.

**Comment by Rasputing** [comment]
just adjust the vl weights and actions for certain vls in the config. Quite a few matrix checks i'd say are boolean, like a player moved unexpectedly or not.

**Comment by SkyLicks** [comment]
What I am requesting is the ability to configure to define what "moving unexpectedly" is and be able to adjust the various tolerances for what "moving unexpectedly" is based off one's specific server set up.

**Comment by SkyLicks** [comment]
Oops. Didnt mean to close this.

**Comment by Rasputing** [comment]
Yeah but that opens a whole new can of worms. The default speed values are whats best, if its being triggered falsely just report it here

**Comment by jiangdashao** [comment]
As @Rasputing said, most checks can't add "tolerance"
