### ISSUE TITLE
[FP] hitbox/killaura false positives

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1117]
## Issue Information
**Server version**: 1.14.4
**How/when does this happen**: when a player spam attacks another from close range
**Video of false positive**: https://www.youtube.com/watch?v=M5CCbl89Swc

**Comment by jiangdashao** [comment]
A normal player can't trigger that killaura false positive

**Comment by Rasputing** [comment]
https://youtu.be/GmBPgvzGL1w  i tried it myself and triggered hitbox, you need to strafe with speed effect on
