### ISSUE TITLE
Add /matrix ban?

### ISSUE THREAD

**Issue by Minkizz** [jiangdashao/Matrix-Issues#112]
Hi, you told me I can customize messages in checks.yml, that's true, but you can only msg or ban the player, it would be cool if you add /matrix ban <player> [expiration-date]. Thank you!

**Comment by jiangdashao** [comment]
No, I won't add ban system, please use other ban plugins

**Comment by Minkizz** [comment]
That's a bit mean?

**Comment by Justin42** [comment]
Ban system is far out of scope for anti-cheat. Use a proper ban plugin, and set Matrix to use the command from that plugin. The developers response isn't "mean", it is the proper response.
