### ISSUE TITLE
[FP] Elytra close (unequip ???)

### ISSUE THREAD

**Issue by Rigagit** [jiangdashao/Matrix-Issues#1124]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
Paper version git-Paper-1618
purplemind :: Elytra | (elytra) reserve energy: 1.361 motion: 0.566 (+2) | vl:2 ping:6 tps:19.99 component: ely.re
https://youtu.be/XBTFz7ATWi4

Player use 3lvl fireworks (3 gunpowder and 1 paper https://i.imgur.com/h2kE2Zd.jpg), when boost effect end, elytra close and player drop down.

And unequip_vl set -1 lol (https://i.imgur.com/izrtldu.jpg)

**Comment by jiangdashao** [comment]
duplicate with #1097
