### ISSUE TITLE
[REQUEST] Improve chat check

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1125]
**What features/checks do you need?:**
Have options for more vl weight if the message contains a link/defined keyword
also TPS protection shouldn't turn off chat check. Chat is asynchronous. How would server lag affect it??

**Comment by jiangdashao** [comment]
1. Chat check is very simple, if you need a good anti-spam/anti-AD, please use other professional chat control plugin
2. What? Chat check didn't be disabled when TPS dropping. It is not in the protection list
