### ISSUE TITLE
[FP] Vehicle False positive

### ISSUE THREAD

**Issue by tovaba** [jiangdashao/Matrix-Issues#1126]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version*1.14.4*: 
**Issue: When a Player starts to go into a waterstream with a boat, it gets instantly kicked and this message appears. For a very weird reason there are no verbose messages when i try to show it up. Also i have experience other weird issues...
**How/when does this happen**:  often
**Video of false positive*
[bug2.zip](https://github.com/jiangdashao/Matrix-Issues/files/4008296/bug2.zip)

*: 
**Other information*this was tested with the latest version of Matrix-Anticheat: 2.8.4*: 

## Configuration Files
**Link to checks.yml file**:

**Comment by Rasputing** [comment]
Thats not velocity, thats vehicle hacks. And there is no verbose in the video.
