### ISSUE TITLE
[FUTURE] [REQUEST] 2 Autofish types

### ISSUE THREAD

**Issue by Rasputing** [jiangdashao/Matrix-Issues#1128]
**What features/checks do you need?:**
Autofish check should have 2 different types, vanilla autofishing (by weighing down mouse and building [this](https://www.youtube.com/watch?v=hTAHK2XnpQs)) and hacked client autofishing. These should be able to be disabled or enabled, as vanilla behavior shouldn't be punished in my opinion.

**Comment by jiangdashao** [comment]
I will recode AutoFish check, use a new detection way
