### ISSUE TITLE
[REQUEST] Be able to execute more than one command per VL

### ISSUE THREAD

**Issue by YellowZaki** [jiangdashao/Matrix-Issues#1129]
**What features/checks do you need?:**

Here:
```
    50: 'matrix notify %player%: using fly'
    100: 'matrix notify %player%: using fly'
    180: 'matrix notify &4%player% kicked because using fly'
    180: 'matrix kick %player% You were detected as fly'
```
` 'matrix notify &4%player% kicked because using fly'` is not executing.

And:
```
    50: 'matrix notify %player%: using fly'
    100: 'matrix notify %player%: using fly'
    176: 'matrix notify &4%player% kicked because using fly'
    180: 'matrix kick %player% You were detected as fly'
```
Neither, but:

```
    50: 'matrix notify %player%: using fly'
    100: 'matrix notify %player%: using fly'
    175: 'matrix notify &4%player% kicked because using fly'
    180: 'matrix kick %player% You were detected as fly'
```
It works, it seems like there must be a separation of 5 VL between commands

**Comment by YellowZaki** [comment]
It seems it can be done with Conditional commands, but why the limite of 5VL between?

**Comment by jiangdashao** [comment]
Why not see the Matrix discord FAQ channel?
![Screenshot_20191230-125642](https://user-images.githubusercontent.com/21152113/71568661-06abb000-2b04-11ea-830c-c87e26c265c7.jpg)
