### ISSUE TITLE
Mid-Air False Positive [Velocity]

### ISSUE THREAD

**Issue by 0x76657261** [jiangdashao/Matrix-Issues#113]
## How you trigger the false positive?
Run and Jump -> in the Jump rotate 180 degree. There you have the FP

## Verbose Message:
![image](https://user-images.githubusercontent.com/42325826/55503983-20d96000-5650-11e9-9ad5-e5cf7bb84dd0.png)

## Server Infomation
**Matrix Version**: 1.8.1 Model 5
**Server Version**: 1.8.8
**ProtocolLib Version**: 4.3.0

**Comment by ignPerformance** [comment]
I am able to reproduce this. Added tags.
