### ISSUE TITLE
[FP] Autoclicker / Killaura

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1134]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: 
**How/when does this happen**: Just clicking
**Video of false positive**: https://youtu.be/Q5c__9yuTQA
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I guess you may be using some external click assist software because this false positive is not encountered by others

**Comment by Maxsimuss** [comment]
Nope. Maybe it is because my ping is < 10 (Connected to a selfhosted server though a local network)?

**Comment by Kuraky** [comment]
I can confirm that this happens on newest Matrix. Seems to only happen when you are not moving.
https://www.youtube.com/watch?v=er7U2LTvOXM

**Comment by jiangdashao** [comment]
I will look into it again tomorrow
