### ISSUE TITLE
[REQUEST] symbols in prefix

### ISSUE THREAD

**Issue by Trexon25** [jiangdashao/Matrix-Issues#1135]
**What features/checks do you need?:**
As in the title it would be awesome if Matrix would support symbols in the prefix.

prefix in language.yml: '&4b&fCloud &cAC &8»&f '
prefix in chat: (img)
![matrix](https://user-images.githubusercontent.com/35470572/71665394-14a83d80-2d5d-11ea-9d10-fc1ee6fe07bc.png)

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/71665944-cb2a1380-2d99-11ea-8685-0c9426f700de.png)
Maybe you should check your file encoding

**Comment by Trexon25** [comment]
file encodings.... Thanks :)
