### ISSUE TITLE
[FP] consistent with honey blocks

### ISSUE THREAD

**Issue by minecraftbugs** [jiangdashao/Matrix-Issues#1139]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [1.15] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server 
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.15
**Verbose messages**: [23:16:43] [Server thread/INFO]: [Matrix] Player tried to fly (Fly) \#number
**How/when does this happen**: Player jumping against a honey block to slow their fall
**Video of false positive**: n/a
**Other information**: easily reproducible

## Configuration Files
**Link to checks.yml file**: default

**Comment by rasputinea** [comment]
could you send a video? with verbose on please

**Comment by minecraftbugs** [comment]
[matrixHoney.txt](https://github.com/jiangdashao/Matrix-Issues/files/4022325/matrixHoney.txt)
this is the log file of when it happened, I don't have any recording software installed
