### ISSUE TITLE
Water False Positive [Fly]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#114]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
https://pastebin.com/raw/TZ2v4mrZ

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgotkH0i9Poo835-nrg

## Server Infomation
**Matrix Version**: 1.8.3
**Server Version**: PaperSpigot v600 for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Another issue: https://1drv.ms/v/s!ApY4tKsF8vPUgohNjIPG5Eu086_aFQ

**Comment by ignPerformance** [comment]
Reopened. Watch the video.

**Comment by jiangdashao** [comment]
Already reduced much false flags, it's enough
