### ISSUE TITLE
[ERROR] Crash? (not sure)

### ISSUE THREAD

**Issue by YellowZaki** [jiangdashao/Matrix-Issues#1145]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.13.2
**Error(s) found in console**: https://pastebin.com/G1PfNMWW
**How/when does this happen**: 
**Other information**: 

First of all, I don't know if the crash is related to matrix but:
1. I've never had a crash in the server for years, and since I updated to matrix 3.0.0 I have had these 2 crashes.
2. In the log,  there are some exceptions about Matrix.

**Comment by jiangdashao** [comment]
This does not seem to be related to Matrix, anyway, why is anyone still using 1.13?
