### ISSUE TITLE
[FP] Vehicle false positive

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1146]
**Server version**: 1.14.4
**How/when does this happen**: when going on steam of water down into a hole
**Video of false positive**: https://youtu.be/rJgqmMskbKc
**Other information**: maybe recode vehicle fly check to be similar to player fly check, not sure though

**Comment by jiangdashao** [comment]
wtf?

**Comment by jiangdashao** [comment]
How could Liquid flow like this in a video?other plugins, such as worldedit

**Comment by rasputinea** [comment]
https://youtu.be/sa77h3xlNug water can flow in this way, you need to make sure there is a trough for water to go into as shown in video
