### ISSUE TITLE
[BYPASS] Riptide boost not stopped

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1147]
**Server version**: 1.14.4
**Hacked client**: WWE
**Video of bypass**: https://youtu.be/4p5t8EBZIoY
**Other information**: Not cancelled

**Comment by jiangdashao** [comment]
Because there is no API called "stopRiptiding" in spigot API

**Comment by rasputinea** [comment]
@jiangdashao teleport the player to their own location after it, trust me it works: 
`  public void onRiptide(PlayerRiptideEvent e) {
        Player p = e.getPlayer();
            p.teleport(p.getLocation(), PlayerTeleportEvent.TeleportCause.UNKNOWN);
    }`
