### ISSUE TITLE
Glass Pane False Positive [Phase]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#115]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
https://pastebin.com/raw/pJKBWcLL

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgohCBqdD-l1qR1xZdg

## Server Infomation
**Matrix Version**: 1.8.1
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
This also works for fences in a similar fashion.

**Comment by jiangdashao** [comment]
It's because of Glass_Plane's bug hitbox

**Comment by jiangdashao** [comment]
Fixed
