### ISSUE TITLE
[FP] Interact with chest under fence/wall

### ISSUE THREAD

**Issue by McSwede** [jiangdashao/Matrix-Issues#1155]
## Troubleshooting Information
- [ X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper v34(1.15.1)
**How/when does this happen**:  Place a fence or a wall above a chest and Matrix prevents you from opening it.
**Video of false positive**: https://youtu.be/3Zww4IqKY-Q

**Comment by jiangdashao** [comment]
1.15/1.14 changed block hitbox, it is very accurate now. This means you can touch other things through the gap in the box
