### ISSUE TITLE
[FP] FastBreak

### ISSUE THREAD

**Issue by therealdgrew** [jiangdashao/Matrix-Issues#1159]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: https://imgur.com/a/WNhU7NV
**How/when does this happen**: While normally breaking blocks with an iron/diamond pickaxe
**Video of false positive**: https://youtu.be/xIIUVvtbHS8
**Other information**: Happens only on client version of 1.8.9 with ViaRewind installed.

## Configuration Files
**Link to checks.yml file**: I'm using the default checks.yml file with only the punishment commands changed.

**Comment by jiangdashao** [comment]
ViaRewind blocked Matrix listening to the arm animation packet, I won't fix it
