### ISSUE TITLE
[FUTURE] [REQUEST] Ability to see user's forge/fabric/liteloader mods

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1165]
**What features/checks do you need?:**
This is something I have been wanting for a while but wasn't sure if it was possible until I saw a "Reflex 
 anti-cheat" which has this feature.  You can listen for certain plugin messages sent by these mods / performing a fml handshake to get a client's mods. I know hacked clients cant be detected with this but it is still useful as you can find out if they have badlion client or certain hacky forge mods.

**Comment by Kyrobi** [comment]
HackedServer is a plugin specifically built for this

**Comment by jiangdashao** [comment]
no
