### ISSUE TITLE
[FP] killaura

### ISSUE THREAD

**Issue by DenisBais** [jiangdashao/Matrix-Issues#1166]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version*test server*: 
**Verbose messages**: 
**How/when does this happen*on move head right and left fast and hitting*: 
**Video of false positive* https://youtu.be/xG_MvNMfK-Y *: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Deliberately triggering false positives will not be fixed
