### ISSUE TITLE
ProtocolSupport Error on Join

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#117]
## Console Error
https://pastebin.com/raw/d5b1fGVP

## When the error happens?
When a player joins.

# Server Infomation
**Server Version**: Latest Spigot for 1.13.2
**Matrix Version**: 1.8.1
**Player's Version**: 1.13.2
**ProtocolLib Version**: 4.4.0
**ProtocolSupport Version**: Latest
**Are your config files freshly generated?**: Not tested yet

**Comment by ignPerformance** [comment]
Details are pending.

**Comment by jiangdashao** [comment]
It's not a compatible bug, you just need to delete your old config files
You can delete checks.yml to slove the bug
