### ISSUE TITLE
[FP] Speed/Fly 2 FPS

### ISSUE THREAD

**Issue by variationtime** [jiangdashao/Matrix-Issues#1170]
So first, when u jump in to the void, die and get respawn u get fly fp
https://streamable.com/3c8uk

Second, you need another player to throw a fishing rod at you and when you fall, they pull back the rod. The player who fall instantly teleported to the void get fp.
https://streamable.com/jj7lx

**Comment by variationtime** [comment]
1.12 server

**Comment by jiangdashao** [comment]
wtf, again
