### ISSUE TITLE
[REQUEST] protocollib

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1175]
**What features/checks do you need?:**
Matrix should strongly Warn when protocollib isn't enabled and disable most checks instead of refusing to start, protocol lib malfunctioning means all hacks function - even though some matrix modules don't use protocollib

**Comment by ZakShearman** [comment]
I generally see this as unnecessary - and I have never found ProtocolLib unstable in the years and years I've been using it. 

If this were to be done, I think it would just be better to remove it as a dependency overall, but I don't know if @jiangdashao would be willing to do this.

**Comment by jiangdashao** [comment]
No, ProtocolLib helped me greatly simplify my code, and if I remove it, I will need to write a lot of code to replace it. ProtocolLib is a very popular library that is used by almost every server, I don't think it is necessary to remove it.
