### ISSUE TITLE
[REQUEST] consider 1.9+ smaller player hitbox

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1178]
**What features/checks do you need?:**
1.9 update made player hitboxes smaller, the 1.9+ sized hitboxes should be a boolean configurable option, without this extended hitbox hacks go undetected on 1.9+ servers: https://youtu.be/A-0CPrxDtsQ

**Comment by jiangdashao** [comment]
You can change it in checks.yml, change the `hitbox.width` and `hitbox.height` option

**Comment by rasputinea** [comment]
What Values do I use for 1.9?

**Comment by rasputinea** [comment]
you don't think the fact that 70% of servers running matrix are 1.9+ justifies a config option or at least some form of notation that tells which values to use for 1.9 hitboxes?
