### ISSUE TITLE
[FP] Autobots

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1182]
**Server version**: 1.14.4
**Verbose messages**: baritone
**How/when does this happen**: Rarely when mining stone with haste and eff5
**Video of false positive**: no video sorry
**Other information**: Ok so basically sometimes when someone is mining fast and server stutters they can get tons of autobot vls in a single tick and get kicked, so what i suggest that you do is throttle the amount of vls a player can gain in a very short amount of time, ie add a couple hundred millisecond cooldown between each violation.

**Comment by jiangdashao** [comment]
I can't fix it
