### ISSUE TITLE
[REQUEST] Option for matrix kick

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1183]
**What features/checks do you need?:**
Add the option for matrix kick to kick all players on the hackers ip address, stopping them from logging in on an alt to bypass the cooldown

**Comment by jiangdashao** [comment]
it's a useless feature, hackers won't log in all alt at the same time

**Comment by rasputinea** [comment]
I have the matrix relog time at 300 seconds, so they do relog on an alt
