### ISSUE TITLE
[FP] Hitbox teleport

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1185]
**Server version**: 1.14.4
**Verbose messages**: Reach: 229 blocks (entity) hb.reach
**How/when does this happen**: teleport armorstand triggers reach
**Video of false positive**: https://youtu.be/mx-9llJqJn0
**Other information**: I think reach check should roll back player's position by their ping + ~150ms before the ray trace for accurate hit registration.

**Comment by jiangdashao** [comment]
No, the right way is to use the hit target entity's history position, not the attacker. And the non-player's history position is hard to be recorded.
