### ISSUE TITLE
[REQUEST] Changing player HitBox Size doesnt seem to work

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1186]
**What features/checks do you need?:**
I tested changing player hitbox size (decreased it) to see if I would get flagged for normal hits but the player hitbox option doesn't seem to work on 1.14.4 from what I can see. In the video i test default settings then make hitbox 0.25 x 1.5 and hitbox check seemed to respond the same. https://youtu.be/-uNFDOf-zfM

**Comment by jiangdashao** [comment]
it's a bug, it will be fixed in next update
