### ISSUE TITLE
[FP] Got killed in air

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1187]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(16:43:20) player Fly | ground spoof | t: fgw.b ax_y:66.47797265986271 v_y:-0.1552320045166016 motY:0.15686728844607956 (+10) | vl:10 ping:38 tps:20.0 component: fly.fg.w2
(16:43:20) player Fly | t: af (+5) | vl:15 ping:38 tps:20.0 component: nofall.air
 
**How/when does this happen**: i was running and jumping, go hit in air and it killed me (i was low hp, but not that low)
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**:x

**Comment by jiangdashao** [comment]
it's your plugin's issue, fix it by yourself

**Comment by DanielAlves123** [comment]
@jiangdashao what??? Matrix dragged me back and it killed me!

**Comment by DanielAlves123** [comment]
@jiangdashao when you get knocked and you are above a hole you can get killed in air
