### ISSUE TITLE
[FP] Kill after arrow hit

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1188]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(16:50:26) player Fly | ground spoof | normal | val1: 51.04639646093133 (+5) | vl:5 ping:47 tps:20.0 component: fly.fg.simple
(16:50:26) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 0.9651740430907765 val3: true (+10) | vl:15 ping:47 tps:20.0 component: nofall.packet

**How/when does this happen**: i got hit with arrow while swimming and it killed me
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**:x

**Comment by jiangdashao** [comment]
...

**Comment by DanielAlves123** [comment]
@jiangdashao stop closing my issues and fix matrix

**Comment by SkyLicks** [comment]
Turn on ghost mode.
