### ISSUE TITLE
[FP] Got killed in air

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1190]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:12:17) player Fly | ground spoof | normal | val1: 59.5729071365693 (+5) | vl:5 ping:42 tps:19.97 component: fly.fg.simple
(17:12:17) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 4.1089442493947885 val3: true (+10) | vl:15 ping:42 tps:19.97 component: nofall.packet
**How/when does this happen**: i got knocked then it killed me in the air
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**:x

**Comment by DanielAlves123** [comment]
Same situation:
(17:14:02) player Fly | ground spoof | send ground packets when falling | d: 5.741244038584185 (+2) | vl:45 ping:51 tps:19.97 component: fly.fg.nofall
(17:14:02) playerFly | ground spoof | normal | val1: 58.067295139201576 (+2) | vl:47 ping:51 tps:19.97 component: fly.fg.simple
(17:14:02) playerFly | send illegal packet to anti fall damage |  val1: 0.0 val2: 5.741244038584185 val3: true (+5) | vl:52 ping:51 tps:19.97 component: nofall.packet
(17:14:05) player Fly | ground spoof | tag: fake air packet | at: 1.188,66.0,3.561 t: 1.239,66.0,-1.5 (+3) | vl:55 ping:51 tps:20.0 component: fly.fg.air
(17:14:05) playerSpeed | suspicious movement: 0.151 predict: 0.118 friction: 0.6 ground:false motY: 0.0 increase:0.026 preMove:0.092 (+2) | vl:7 ping:51 tps:20.0 component: move.xz
(17:14:06) playerFly | ground spoof | tag: fake air packet | at: 1.192,66.0,4.201 t: 1.239,66.0,-1.5 (+3) | vl:58 ping:51 tps:20.0 component: fly.fg.air

**Comment by jiangdashao** [comment]
I said other people don't have this issue, it's your own problem

**Comment by DanielAlves123** [comment]
@jiangdashao my issue? It's your plugin that causes it. Even when I recorded you bugs you say that its compability issue. Other people can't break blocks under a player?

**Comment by rasputinea** [comment]
@DanielAlves123 Please include a video of the bug with all your reports
