### ISSUE TITLE
[FP] Web fly bug

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1191]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:48:30) player Fly | ground spoof | send illegal ground moving packets | location: 0.874,67.632,5.382 | block: AIR,AIR (+5) | vl:86 ping:35 tps:20.0 component: fly.fg.ground
(17:48:30) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 0.63112002168873 val3: true (+10) | vl:96 ping:35 tps:20.0 component: nofall.packet
(17:48:31) player Fly | ground spoof | tag: fake air packet | at: -0.624,66.0,4.98 t: -0.577,67.0,5.507 (+7) | vl:103 ping:35 tps:20.0 component: fly.fg.air

**How/when does this happen**: jump to the web that is in the air, when you get out of it it will drag you back
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**:x

**Comment by rasputinea** [comment]
Here is a video of me jumping into cobweb: https://youtu.be/s7Y6HugnnxM
