### ISSUE TITLE
[FP] Elytra check stops players mid air

### ISSUE THREAD

**Issue by acyis** [jiangdashao/Matrix-Issues#1196]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.1
**Verbose messages**: https://www.youtube.com/watch?v=V-w0FMbrlXA
**How/when does this happen**: When flying with an elytra
**Video of false positive**: https://www.youtube.com/watch?v=V-w0FMbrlXA
**Other information**: Pay attention to checks by user "Flufsi" He is the one flying.

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
Can you record first-person videos?

**Comment by jiangdashao** [comment]
I can't reproduce the false positive
