### ISSUE TITLE
[FP] Bug In Matrix Cps

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#1198]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: spigot 1.8.8
Verbose messages: no
How/when does this happen: if you do /matrix cps player then whatever time if you mine a block it will say your at like 22 cps
Video of false positive: obs stupid
Other information: no

Configuration Files
Link to checks.yml file: default

**Comment by jiangdashao** [comment]
I don't think it's a false positive

**Comment by coolpvpv1** [comment]
> I don't think it's a false positive

i dont see a option to choose bug report

**Comment by ZakShearman** [comment]
I've seen this on other servers, so certainly possible.
