### ISSUE TITLE
False positive after falldamage dead

### ISSUE THREAD

**Issue by Wolfbros** [jiangdashao/Matrix-Issues#12]
## How you trigger the false positive?
When you die on falldamage, Matrix kill you again and again (1.5.1) Version 1.1.4: after falldamge dead when you jump on a block Matrix cancel the action.

## Verbose Message:
failed fly check: t:nf a=0.0 g=false (+10) : vl:45 ping: 16 tps:20

## Server Infomation
**Matrix Version**: 1.5.1
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by Wolfbros** [comment]
Now Matrix port you back to the death point... (after fall damage dead)  use /spawn and Matrix port you back

Verbose Message: failed Fly check | glide t:fg a=66.0 (+5) | vl:20
failed Fly check | glide t:nf a=0.0 g=true (+10) | vl:25

Verbose Message (/spawn):
WolfBros failed Fly check | t:nf a=0.0 g=false (+10) | vl:20
failed Fly check | t:fg a=66.0 (+5) | vl:30
failed Fly check | t:nf a=0.0 g=true (+10) | vl:35

**Comment by jiangdashao** [comment]
Fixed
