### ISSUE TITLE
[FP] mistype when relogging in and it says wait

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#1200]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: spigot 1.8.8
Verbose messages: https://i.badlion.net/Eim5WVe8g6ktzo8zRsKMid.png
How/when does this happen: when you get kicked and try to reconnect theres a little mistype https://i.badlion.net/Eim5WVe8g6ktzo8zRsKMid.png
Video of false positive: no
Other information: btw make a bug report option then so i dont have to use the false positive option ok

Configuration Files
Link to checks.yml file: default

**Comment by coolpvpv1** [comment]
btw make a bug report option then so i dont have to use the false positive option ok

**Comment by rasputinea** [comment]
config.yml relog-time

**Comment by coolpvpv1** [comment]
> config.yml relog-time

just reporting it anyway

**Comment by jiangdashao** [comment]
what? where is the mistype?

**Comment by Jakaboii** [comment]
there isn't lmao
