### ISSUE TITLE
[FP] Fly kills in air

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1204]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:28:17) player  Fly | ground spoof | send ground packets when falling | d: 4.794065029120496 (+5) | vl:5 ping:49 tps:20.0 component: fly.fg.nofall
(17:28:17) player  Fly | ground spoof | normal | val1: 58.045429152493526 (+5) | vl:10 ping:49 tps:20.0 component: fly.fg.simple
(17:28:17) player  Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 0.7769989479275665 val3: true (+10) | vl:20 ping:49 tps:20.0 component: nofall.packet

**How/when does this happen**: when i got knocked above a hole matrix killed me in the air
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**: default

**Comment by Kuraky** [comment]
Dude, you've been already told to post videos of false positives, otherwise they won't get accepted.

**Comment by DanielAlves123** [comment]
@Kuraky check it by yourself, I recorded video and @jiangdashao says its incompability issue. With what? Other servers don't have players or pickaxes and blocks for example?

**Comment by SkyLicks** [comment]
@DanielAlves123 
What version are you using
Spigot 1.8? Paper 1.8? What build version?

If Re says its a compatibility issue, then have you tested this with JUST Matrix and viaversion on your server? Does this only happen with viaversion or also when you use protocolsupport plugin?

**Comment by DanielAlves123** [comment]
@SkyLicks why would I need testing environment without ViaVersion? I use paper for 1.8 CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by YellowZaki** [comment]
I'm having this issue. More info:
- Player dies at 10:20:04 at coords x: 978, y: -10, z: 600 (there is a parkour on that coords)

Matrix log:

```
10:20:04) SantiButterfly failed Fly check | ground spoof | send ground packets when falling | d: 57.61779129686141 (+1) | vl:133 ping:256 tps:19.84 component: fly.fg.nofall
(10:20:04) SantiButterfly failed Fly check | ground spoof | normal | val1: 113.33026679004332 (+1) | vl:134 ping:256 tps:19.84 component: fly.fg.simple
(10:20:04) SantiButterfly failed Fly check | send illegal packet to anti fall damage |  val1: 0.0 val2: 76.39074007926075 val3: true (+3) | vl:137 ping:256 tps:19.84 component: nofall.packet
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:143 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:149 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:155 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:161 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:167 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:173 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:179 ping:256 tps:20.0 component: fly.ability
(10:20:08) SantiButterfly failed Fly check | send invalid ability packets (+6) | vl:185 ping:256 tps:20.0 component: fly.ability
```
