### ISSUE TITLE
[BYPASS] Hitbox.Dir

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1207]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**:  Impact (but other clients probably work too)
**Link to hacked client**: https://impactclient.net/ImpactInstaller.exe
**Cheat that bypassed**: Hitbox
**Video of bypass**: https://youtu.be/Pgu5mKf4mUE
**Other information**: At the end of the video, I enable a random hack just to prove I dont have bypass perms.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by rasputinea** [comment]
keep in mind that NPCs don't seem to be treated like actual players to matrix, they are shown as "empty" type instead of "player". If you try with an actual player the backwards hits would be detected as reach but definately most would bypass
