### ISSUE TITLE
[FP] CPS Counter Accuracy

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1208]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: N/A
**How/when does this happen**: Video
**Video of false positive**: https://youtu.be/oy0uIevcrQs
**Other information**: 

I am using a basic autoclicker in this video: https://sourceforge.net/projects/orphamielautoclicker/
The clicker is set to a delay of 20 mili second on this particular clicker

Even though the CPS is relatively constant, it is heavily fluctuating especially in the /matrix cps sometimes off by over 10 clicks.

## Configuration Files
**Link to checks.yml file**: https://justpaste.it/4khni

**Comment by SkyLicks** [comment]
I am not sure if this is a technical limitation but it does look like that CPS data is more accurate when targeting an entity.

**Comment by jiangdashao** [comment]
Due to network fluctuations and software problems, this data cannot be completely accurate
