### ISSUE TITLE
mcMMO Serrated Strikes False Positive [Reach & NoSwing]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#121]
## How you trigger the false positive?
Use mcMMO serrated strikes ability on a mob or a player and walk away.

## Verbose Message:
<! -- Provide the verbose message here -->

## Server Infomation
**Matrix Version**: 1.8.1
**Server Version**: PaperSpigot v600 for 1.13.2
**mcMMO Version**: 2.1.28
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Video/Verbose message, please
