### ISSUE TITLE
[REQUEST] Matrix API add vl

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1211]
**What features/checks do you need?:**
Make a way to add vl (instead of just setting vl) via the matrix api.

Example:

api.addViolations()

**Comment by jiangdashao** [comment]
why? What's the difference between the two?

**Comment by SkyLicks** [comment]
The difference is that setViolation SETS the violation level. So lets say I make a custom check that I want to use with Matrix.

The player starts fly hacking and is triggering both my custom check and a matrix check. Matrix violation add +10 to his violation. And everytime my custom check is failed I want to add +5 to the violation using the api. I can only SET my violations and not add to the violations.

I hope that makes sense.

And actually now that I think about it, a matrix subtractViolation() could also be useful.

**Comment by rasputinea** [comment]
@SkyLicks api.setviolation(api.getviolation + 10)???
