### ISSUE TITLE
[REQUEST] Player specific verbose

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1212]
**What features/checks do you need?:**
Be able to view the verbose alerts for a specific player.

For example currently, /matrix verbose enables all verbose alerts for all players. I am suggesting adding a feature like /matrix verbose (player) which only shows verbose from a specific player.

**Comment by rasputinea** [comment]
it literally does that

**Comment by SkyLicks** [comment]
Woah. I guess im dumb.
