### ISSUE TITLE
[FP] Velocity false positive

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#1215]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: https://pastebin.com/vHCe0krw
**How/when does this happen**: when a player was beaten by another player
**Video of false positive**: none
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default

**Comment by rasputinea** [comment]
Video please, with verbose messages on
