### ISSUE TITLE
[REQUEST] Please add this <3

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1220]
**What features/checks do you need?:**
![image](https://user-images.githubusercontent.com/34877092/72753922-43fbde80-3b94-11ea-8296-ee732e2bc070.png)
I saw this and I want to suggest again to add support to matrix.bypass for sub checks like matrix.bypass.fly and .killaura in both permissions AND in the matrix api. Even now, Matrix does have noticeable impacts on timings when 90+ players are on for me which I why I was somewhat concerned too about the performance impact matrix 4 might have :(

Disabling certain matrix checks where they aren't needed will help us optimize performance.

Specifically, I want to disable hitbox check in the spawn world, but keep kill aura check enabled because its useful for AFK kill aura :). Someone else might want to disable interact checks because you can't breaks block at spawn but keep fly checks open. It would really help medium to larger servers save on performance by disabling matrix where not needed.

**Comment by rasputinea** [comment]
why not just turn it off in checks.yml?

**Comment by SkyLicks** [comment]
Because I don't want to completely disable the check across the server. Just certain checks in certain worlds. And through the api, I would be able to disable certain checks under certain situations.

Example: 
If player /fly enabled, disable fly checks for him.
If player is in spawn world disable combat checks.
If player is afk, disable all checks for him.

Through things like these, we can save on a lot of performance without sacrificing any checks further optimizing matrix on servers with a large player base.

**Comment by jiangdashao** [comment]
Matrix can't do this
