### ISSUE TITLE
[REQUEST] Freecam detection

### ISSUE THREAD

**Issue by McSwede** [jiangdashao/Matrix-Issues#1221]
**What features/checks do you need?:**
I want to start by saying that i have seen issue #912 so i know you have already said no to this request before but in your respone to that issue you said that teleporting the player is the only way to prevent freecam and that may be true but there are ways to detect when players are using freecam and kicking them.

By checking if the player is sending keep-alive packets but not move packets Matrix could detect if players are using freecam. Maybe you could even add an option to cancel it by teleporting them like you mentioned in the other issue.

This would help our server massively!
// McSwede

**Comment by rasputinea** [comment]
yeah this is true, you should add this re

**Comment by jiangdashao** [comment]
First, Freecam cannot be detected, and you can only block it in some way. For example, a position packet is sent to a player after he has been banned. However, this method does not prevent all Freecams, and may cause false positives.
