### ISSUE TITLE
[FP] McMMO activation abilities throw out false positive violations.

### ISSUE THREAD

**Issue by mibby** [jiangdashao/Matrix-Issues#1223]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper dev 62 (Spigot 1.15.1)
**Incompatible plugin**: McMMO
**How/when does this happen**: When using mcmmo activation abilities.

Would it be possible to add a hook for McMMO? Similar to NoCheatPlus's old CompatNoCheatPlus addon. Currently using activation abilities with McMMO throws out many false positive violations in matrix. 

## Configuration Files
**Link to checks.yml file**:
https://paste.ubuntu.com/p/j8Z2Hjk6Zg/

Paper dev 62 (Spigot 1.15.1)
McMMO 2.1.113-SNAPSHOT dev 888
ProtocolLib  4.5.1-SNAPSHOT-b445
Matrix v3.0.4

**Comment by jiangdashao** [comment]
Please provide how the false positive happens, Which skills cause false positives, and the verbose messages
