### ISSUE TITLE
[REQUEST] Suggests to Possibly improve performance

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1224]
**What features/checks do you need?:**

First of all, I am not sure how Matrix checks anticheat work, so this maybe a stupid suggest. But these suggestions are to disable certain checks when its impossible for a player to trigger them. Instead of checking if a player is hacking all the time, only activate certain checks if certain conditions are met to improve performance. Not all these suggestions might be good because they might lead to bypass and you might already have some added. So here I go.

- Disable matrix checks for a player when a player is detected AFK
- Disable jesus check on ground
- Disable fly/speed check for a gliding player
- Disable fastbow check if no bow
- disable vehicle check if player is not on a vehicle
- disable all checks in a player is dead
- disable combat checks until a arm swing (or interact) event is fired?
- disable combat checks if player is invincible? (99% of the time servers dont let invincible players pvp, maybe optional config?)
- disable velocoty check if player is invincible
- disable fastheal check if player is not hungry

**Comment by jiangdashao** [comment]
I did exactly that
