### ISSUE TITLE
Matrix.jar not working at all?

### ISSUE THREAD

**Issue by No0to** [jiangdashao/Matrix-Issues#123]
I have a minecraft server running spigot-1.13.1.jar and I have just dragged the Matrix.jar file into my plugins folder, restarted the server, and nothing. Not a file created or anything. My only possible suspicion is that I'm running a 1.13 plugin on a 1.13.1 server but I have other plugins that are made for things like 1.10 and work on 1.13. Does anybody know the issue?

**Comment by Justin42** [comment]
Working as expected on Paper 1.13.2

**Comment by jiangdashao** [comment]
Is any error in console?
