### ISSUE TITLE
Could not pass event PlayerMoveEvent to Matrix v4.0.0

### ISSUE THREAD

**Issue by hikmetozgurler** [jiangdashao/Matrix-Issues#1230]
Hi ,
Matrix having some problem.Spamming console some times i wasn't able to find why? 
I am using the latest version 4.0.0
console log: https://pastebin.pl/view/0bed1713

**Comment by hikmetozgurler** [comment]
Using Minecraft paper 1.12.2

**Comment by jiangdashao** [comment]
I will fix it soon
