### ISSUE TITLE
[FP] Groundspoof lantern

### ISSUE THREAD

**Issue by McSwede** [jiangdashao/Matrix-Issues#1231]
## Issue Information
**Server version**: Paper 70 MC 1.15.2
**Verbose messages**: See video
**How/when does this happen**: Jumping up on a block with a lantern on it
**Video of false positive**: https://youtu.be/wvlY_-rzH-c

**Comment by jiangdashao** [comment]
I can't play the video

**Comment by McSwede** [comment]
Fixed
