### ISSUE TITLE
[FP] Void teleport bug

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1234]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: not needed
**How/when does this happen**: stand near the edge of the void, violate fly/speed (in my case you can just jump on 1.14), you get teleported to the void not to the edge
**Video of false positive**: not needed
**Other information**:  not needed

## Configuration Files
**Link to checks.yml file**: -

**Comment by DanielAlves123** [comment]
@jiangdashao why close issues without fixing?

**Comment by YellowZaki** [comment]
@jiangdashao is this fixed? In order to continue using Matrix because players are complaining a lot about this issue.
