### ISSUE TITLE
[FP] Vehicle velocity 

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1235]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: (19:54:26) player Fly | step | p: 1 | m:1.312824990861202 ev:-0.231 (+8) | vl:8 ping:39 tps:19.99 component: speed.step
(19:54:26) player Fly | suspicious movement:1.313 predict:-1.569 air_t:12 tag:m1 (+15) | vl:23 ping:39 tps:19.99 component: fly.main

**How/when does this happen**: set vehicle to player, set velocity to vehicle, eject player
**Video of false positive**: not needed
**Other information**: 1.14 client

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
Video pls

**Comment by DanielAlves123** [comment]
@jiangdashao here it is: https://share.getcloudapp.com/p9u5ygyB
(18:30:15) player Fly | step | p: 1 | m:1.3418888320420308 ev:-0.155 (+8) | vl:8 ping:33 tps:20.0 component: speed.step
(18:30:15) player Fly | suspicious movement:1.342 predict:-1.569 air_t:12 tag:m1 (+15) | vl:23 ping:33 tps:20.0 component: fly.main
