### ISSUE TITLE
[REQUEST] flight is still prevented even when cancel vl is set high

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1237]
**What features/checks do you need?:**
flight is still prevented even when cancel vl is set high - i dont want to use ghost mode as some checks i must cancel

**Comment by SkyLicks** [comment]
> when cancel vl is set high
To cancel vl, you are suppose to set "cancel_vl" to "-1".

Also, some most of the "critical" checks are always canceled such as many interact and badpacket checks even in ghost mode.

**Comment by jiangdashao** [comment]
Please tell me which check(component) is broken^^

**Comment by rasputinea** [comment]
Re just set cancel-vl to -1 in flight check and then fly, you will be setback even when its not supposed to cancel.
