### ISSUE TITLE
[FP] Tower

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#1238]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.8.8
Verbose messages: https://imgur.com/I1gWRBK
How/when does this happen: if your pitch is at like 80ish and your on a long flat world and you have stone and just sprint and jump and spam left click really fast to place blocks you will false tower alot
Video of false positive: sorry obs is being stupid and won't capture my screen
Other information: uh idk

Configuration Files
Link to checks.yml file**: Default

**Comment by rasputinea** [comment]
please include a video

**Comment by coolpvpv1** [comment]
> please include a video



> please include a video

obs wont record my screen cause its being retarded and it didn't do that before

**Comment by jiangdashao** [comment]
I can't reproduce this
