### ISSUE TITLE
[FP] Killaura Post

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#1242]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.15.2
Verbose messages: 
How/when does this happen: i ran a 1.15.2 server with 400 ram just to see if it would like make matrix false or something idk but on that i hit like animals with a wooden sword and almost if not even single attack i did it falsed killaura post
Video of false positive: obs stupid
Other information:

Configuration Files
Link to checks.yml file: Default

**Comment by rasputinea** [comment]
please include a video with verbose on

**Comment by coolpvpv1** [comment]
> please include a video with verbose on

obs wont record my screen cause its being retarded and it didn't do that before
