### ISSUE TITLE
[BYPASS] ChestStealer

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#1249]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-c66f02b1 (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Hacked client**: impact 4.6
**Link to hacked client**: dunno
**Cheat that bypassed**: ChestStealer
**Video of bypass**: https://streamable.com/peh37
**Other information**: not a bypass but strange

**Comment by jiangdashao** [comment]
It's not a bypass, If the player clicks on the same item, ChestStealer will not check him
