### ISSUE TITLE
[FP] Shield/sword block

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1253]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1,8
**Verbose messages**: -
**How/when does this happen**: when shield or sword bugs that it blocks server side but not client side it will get you banned for speed
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**:-

**Comment by jiangdashao** [comment]
I can't do anything for it

**Comment by DanielAlves123** [comment]
@jiangdashao you can't unblock or unsneak server-side?
