### ISSUE TITLE
Velocity, fly bypassed

### ISSUE THREAD

**Issue by car1ot** [jiangdashao/Matrix-Issues#1256]
There are some problems. Velocity and fly bypassed.
I'm using the last version of anticheat on my server and default configs. IP: mc.skypvp.ru

1) Antiknockback detecting very bad and everyone using this
2) Fly hack sometimes not detected and people could fly

**Comment by Jakaboii** [comment]
cant you follow the format???
and no one cares what the IP is, this issue is useless
