### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by car1ot** [jiangdashao/Matrix-Issues#1259]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ 1.15.2] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**1.15.2**: 
**Any client**: 
**Any client**: 
**Velocity, fly**: 
**-**: 
**-**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:
DEFAULT FILES

**Comment by Jakaboii** [comment]
everything is required, and format it right so it's easier to read

## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 Spigot (or paper, ect)
**Hacked client**: Any
**Link to hacked client**: Any
**Cheat that bypassed**: Velocity, fly
**Video of bypass**: use streamable for this
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
？

**Comment by car1ot** [comment]
> 
> 
> ？

Velocity hack (Anti knockback) bypass by any cheat.
