### ISSUE TITLE
Piston False Positive #3 [Phase/Fly]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#126]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgohdmalxOPwRT_zlig

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Related #138 #137
