### ISSUE TITLE
[FP] Autoclicker

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#1261]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.15.2
Verbose messages: 
How/when does this happen: if you have a stack of block they added this thing where if you hold q it will spam remove blocks from the hotbar so if you hold q to remove a stack of blocks when theres 4 blocks left in your hotbar you false aura / autoclicker 30 cps
Video of false positive: not relaly needed and obs wont work anyway
Other information: idk

Configuration Files
Link to checks.yml file: Default

**Comment by rasputinea** [comment]
Better to wait for spigot/Craftbukkit to fix this.

**Comment by rasputinea** [comment]
Nevermind, spigot has decided not to fix it because of how playerinteractevent works.
