### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by car1ot** [jiangdashao/Matrix-Issues#1262]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**1.15.2**: 
**LiquidBounce b2 | 1.12.2**: 
**https://liquidbounce.net/**: 
**Velocity ak AntiKnockback**: 
**https://www.youtube.com/watch?v=Hgqq1u5dIoo**: 
**Bypassing also fly. But it happens sometimes.**: 

## Configuration Files
**Default**: 
**Default**:

**Comment by car1ot** [comment]
**_Also killaura bypassed  by this cheat. You could check out KillAura + Velocity. Matrix allows to use this together without any violations._**

**Comment by jiangdashao** [comment]
1. KillAura can be detected quickly in the premium version
2. The AntiKnockback check is not working when you standing on the half-block or standing by other solid blocks, I will try to improve it
