### ISSUE TITLE
[ERROR] BLOCK type: java.lang.NullPointerException ...

### ISSUE THREAD

**Issue by Carvane** [jiangdashao/Matrix-Issues#1263]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-71 (MC: 1.15.2) With support 1.8+ (last viaversion)
**Error(s) found in console**: https://pastebin.com/s6Q0V1nK
**How/when does this happen**: all the time
**Other information**: nothing

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/v1hwqN3D
**Link to config.yml file**: https://pastebin.com/1VX1mJ6L

**Comment by rasputinea** [comment]
Supporting 1.8 on a 1.15 server?? I don't think that is a very good idea. You would be wayy better off running a 1.8 server that supports up to 1.15 clients, or just.. yaknow.. not supporting older clients. Plugins like viaversion are so buggy.

**Comment by jiangdashao** [comment]
Error due to threads sharing objects
