### ISSUE TITLE
[FP]  FastBreak

### ISSUE THREAD

**Issue by ChrisTVH** [jiangdashao/Matrix-Issues#1266]
When a player of mine breaks a block, he is ejected. This could be the possible error

[WARNING] (Matrix) Failed to inject PlayerConnection.class: java.lang.reflect.InvocationTargetException

[WARNING] (Matrix) This may cause false positives for some checks

And this comes out when you take it out of the server

[INFO] (➵)OB_Zbatboy Salio del server!

[INFO] IILegendsOfPixelsII player OB_Zbatboy Fue pateado por hacer trampa!

[WARNING] handleDisconnection() called twice

The server is 1.12.2 I use the version of the Matrix 4.0.3 plugin when the player just tries to break the block instantly takes it out of the server

**Comment by ChrisTVH** [comment]
![image](https://user-images.githubusercontent.com/58376852/73567521-e3468e80-443c-11ea-82f8-35c69db1b020.png)

**Comment by jiangdashao** [comment]
It's a ViaBackward bug, please ProtocolSupport
