### ISSUE TITLE
[FP] Hitbox bug

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1269]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: not needed
**How/when does this happen**: when you hit player when is couple blocks above you it can detect reach
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**:-

**Comment by jordanamr** [comment]
Can confirm (1.8.8)

**Comment by DanielAlves123** [comment]
@jiangdashao what more info do you need?
