### ISSUE TITLE
[FP] move.xz Item Attribute

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1270]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: move.xz -> Video
**How/when does this happen**: Whenever you quickly switch between an item that gives slowness speed attributes, you can cause this false positive.
**Video of false positive**: https://youtu.be/avE4i_DLlug
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
I can't solve this problem
