### ISSUE TITLE
[BYPASS] Wurst Client 1.15.2

### ISSUE THREAD

**Issue by Redstoneguy129** [jiangdashao/Matrix-Issues#1278]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 Paper
**Hacked client**:  Wurst 1.15.2
**Link to hacked client**: https://www.wurstclient.net/updates/wurst-7-0pre23/
**Cheat that bypassed**: All except flight
**Video of bypass**:  x
**Other information**: x

## Configuration Files
**Link to checks.yml file**: not edited
**Link to config.yml file**: not edited

**Comment by jiangdashao** [comment]
No video proof and Wurst is shit
Please check your server environment

**Comment by jiangdashao** [comment]
KillAura:
![image](https://user-images.githubusercontent.com/21152113/73597515-b773f780-4567-11ea-8a67-0b9be6672d85.png)
Jesus:
![image](https://user-images.githubusercontent.com/21152113/73597531-dd999780-4567-11ea-95e5-c32857ea6ced.png)

Matrix works fine^^
