### ISSUE TITLE
[REQUEST] Adjustable vl weights for jesus check

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1279]
**What features/checks do you need?:**
add the modules to jesus check like this: 
...
jesus:
   Enable this check?
  enable: true

   Violations needed to cancel illegal movements (-1 = never cancel)
  cancel_vl: 50

   vl_weights:
       vertical: 5
       speed: 2
       solid: 5
       exit: 2

   Violation Thresholds
   number_of_violations: '<command>'
  ...

**Comment by jiangdashao** [comment]
No, there are 10+ modules in Jesus check, please use the custom VL setting in `config.yml`

**Comment by rasputinea** [comment]
Add a %default vl weight% module to verbose messages then, or list the modules and their vl weights because i have no idea how to find a checks base vl weight due to ping deductions lp tps etc
