### ISSUE TITLE
[INCOMPATIBILITY] Command blocker doesnt work with matrix

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1283]
**Server version**: 1.15.2
**Incompatible plugin**: any command blocking plugin
**How/when does this happen**: if you block commandpreprocessevent in a command blocker plugin matrix still tells the player "you do not have permission to execute this command" showing them that the server they are on is running matrix
**Photo of incompatibility**: https://imgur.com/a/9Fd410m
**Other information**: Instead of listening for commandpreprocessevent when checking matrix permissions simply in the matrix command check if(p.haspermission("matrix.verbose") etc.

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/73610166-83541180-460f-11ea-81b3-e0f81d5f7225.png)
I did it intentionally to prevent the use of Command Blocker

**Comment by rasputinea** [comment]
why?
