### ISSUE TITLE
[REQUEST] Fly.hover check

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1285]
**What features/checks do you need?:**
Simply have a fly check that detects hovering in the air, this will stop players flying without moving to win minigames such as tnt run

**Comment by SkyLicks** [comment]
In other words:

Players fly and hover over the abyss.
Players fly and hover over the abyss.
Players fly and hover over the abyss.
Players fly and hover over the abyss.

**Comment by jiangdashao** [comment]
Why not using server built-in anti flight
