### ISSUE TITLE
[FP] Fly Ground Spoof kill player

### ISSUE THREAD

**Issue by Rigagit** [jiangdashao/Matrix-Issues#1286]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
last paper 1.12.2
(20:39:14) nktYT :: Fly | ground spoof (expect: --, move: 0.081,-0.194,-0.002, type: air) (+5) | vl:5 ping:7 tps:19.99 lp:23 component: fly.gf
https://youtu.be/3qmljlkjOAs

**Comment by jiangdashao** [comment]
Information is not enough
