### ISSUE TITLE
[FP] Players get kicked while PvP

### ISSUE THREAD

**Issue by LukLife** [jiangdashao/Matrix-Issues#1289]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Verbose messages**: Only kick message
**How/when does this happen**: When players are playing PvP
**Video of false positive**: -
**Other information**: 
My players are complaing about getting kicked sometime but they are actually not hacking. I tested it my self and also got 2 times kicked for hacking. Some players complained about set backs while running.

## Configuration Files
**Link to checks.yml file**:
https://hastebin.com/eyogewayib.shell

**Comment by Jakaboii** [comment]
you need to provide the verbose messages (using `/matrix verbose`) and a video (you can record it and upload it to streamable.com)
