### ISSUE TITLE
Vel [FP] 

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1290]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: see video
**How/when does this happen**: moving while receiving velocity
**Video of false positive**: https://youtu.be/rSqw6ZLmo1c
**Other information**: using gadget from plugin ttps://www.spigotmc.org/resources/gadgetsmenu-1-8-1-15.10885/

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Why you install Matrix in a lobby server? You can disable the P8 by set vl weight to `-1`
