### ISSUE TITLE
[REQUEST] Auto Updater 

### ISSUE THREAD

**Issue by Nikox3003** [jiangdashao/Matrix-Issues#1291]
**What features/checks do you need?:**
Option to download recent update of the plugin on startup or using a command.
I know that someone have arleady requested it and it got rejected because files can't be auto updated, but...
It could check the spigot site / downloaded jar if any files were changed. If they were, it would cancel update / throw a warning. I don't know if it's possible or not, but it's first what I've come up with.
If it's not, it could be just an option in config to enable to use at your own risk.

**Comment by jiangdashao** [comment]
No, why is anyone too lazy to download the jar?
