### ISSUE TITLE
[FP] 1.15.2 Phase Problem

### ISSUE THREAD

**Issue by OverBrave** [jiangdashao/Matrix-Issues#1294]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server- No 1.15.2
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper 1.15.2 Patch-90
**Video**:  https://streamable.com/9bdvf

**Comment by jiangdashao** [comment]
1.14+ change player sneak height
