### ISSUE TITLE
[FP] Teleport to void

### ISSUE THREAD

**Issue by YellowZaki** [jiangdashao/Matrix-Issues#1296]
I reopen https://github.com/jiangdashao/Matrix-Issues/issues/1234 because it hasn't been fixed.

## Troubleshooting Information
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**How/when does this happen**: It is not clear, some players are just walking on the island (skyblock), and they are teleported to void. It is hard to reproduce because it is random. I have logged two.

Player 1 (he was fishing and he suddenly was teleported to void)
**Verbose messages**: 
`(22:24:36) daketlandia26 failed Fly check | suspicious movement:0.375 predict:0.289 vel:-0.304 air_t:12 tag:m4 (+4) | vl:4 ping:172 tps:20.0 lp:34 component: fly.main`
**Minecraft log**: 
`[22:24:42] [Server thread/INFO]: daketlandia26 died at x: 3043.29, y: -262.46, z: -369.46 Reason: void`

Player 2
**Verbose messages**: 
```
(18:43:51) DarkDelphim failed Speed check | t: spin (+5) | vl:5 ping:80 tps:19.9 lp:29 component: speed.spin
(18:43:51) DarkDelphim failed Speed check | t: spin (+5) | vl:10 ping:80 tps:19.9 lp:29 component: speed.spin
(18:43:57) DarkDelphim failed Speed check | suspicious movement (move: 0.659, expect:0.8235000000000001, vet: 0.62, tag: d) (+8) | vl:8 ping:80 tps:19.84 lp:4 component: speed.main
(18:43:57) DarkDelphim failed Fly check | step | p:2 | val: 0.5292000003695421 (+7) | vl:7 ping:80 tps:19.84 lp:4 component: speed.step
```
**Minecraft log**: 
`[18:44:01] [Server thread/INFO]: DarkDelphim died at x: -4370.21, y: -175.09, z: -7492.12 Reason: void
`

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
1. If the player is on the void, he will be drag into the void, I think it's correct
2. I guess the Player 2 is cheating, the normal player can't trigger "spin" flag

**Comment by YellowZaki** [comment]
The player is not on the void, they are on solid blocks and they are teleported to the void.
I is not about a false positive. It is impossible to have 0 false positive. These are some cases. 
What should be fixed is the utility that teleport the user to the ground or something.

**Comment by jiangdashao** [comment]
> The player is not on the void, they are on solid blocks and they are teleported to the void.
> I is not about a false positive. It is impossible to have 0 false positive. These are some cases.
> What should be fixed is the utility that teleport the user to the ground or something.

If he is on the void or near void, he will be teleported into the void

**Comment by YellowZaki** [comment]
But can't you do anything? If the player is going to be teleported to the void, don't do it.
On Skyblock is normal to be near the void.

**Comment by rasputinea** [comment]
@jiangdashao normal players can trigger the spin flag when server is lagging. Its rare but ive seen it before.

**Comment by jiangdashao** [comment]
I will add an option to disable the void teleport
