### ISSUE TITLE
[BYPASS] Anti-bot dont work

### ISSUE THREAD

**Issue by Dimoon12** [jiangdashao/Matrix-Issues#1298]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.13.2
**Hacked client**: impact
**Link to hacked client**: https://impactclient.net/
**Cheat that bypassed**: Baritone patchfinding
**Video of bypass**: https://mega.dp.ua/HRSVAx3e
**Other information**: Other (like anti killaura working (i show on video))

## Configuration Files
**Link to checks.yml file**: https://mega.dp.ua/s9Sz8E
**Link to config.yml file**:https://mega.dp.ua/s9Sz8E

**Comment by Dimoon12** [comment]
u know this cheat. after update anticheat dont blocking bots (sorry bad eng :c)

**Comment by jiangdashao** [comment]
This feature has been adopted as a paid feature

**Comment by Dimoon12** [comment]
:c fuc
