### ISSUE TITLE
[FP] only cancel elytra.me when vl is over a threshold

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1299]
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: flying with elytra under normal server load
**Video of false positive**: 
**Other information**: sometimes players trigger the elytra.me check because of lag etc which stops them so they fall and die. What im suggesting is that you add a config option to only setback unexpected movements when they have for example 10+ vl
## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
It did, but Matrix will FORCE setback player when this player is particularly cheating

**Comment by jiangdashao** [comment]
I will add an option to disable force setback

**Comment by rasputinea** [comment]
@jiangdashao make a force setback vl weight, not a boolean
