### ISSUE TITLE
[BYPASS] Matrix NPC

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1301]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
When `command-trigger-only` is enabled in the Matrix config, and one triggers the NPC using the command, the NPC ALWAYS stays behind the player. Given that most KillAuras can target players only in front of them, this renders the NPC, useless (for everything except testing players for tracers with this). With command trigger disabled, the NPC actually moved in front of the player. I am suggesting making it like that with command trigger as well.

**Comment by jiangdashao** [comment]
1. It uses same movement algorithm
2. NPC was used to detect some simple client
