### ISSUE TITLE
[FP] Phase No Clip

### ISSUE THREAD

**Issue by mlegok12** [jiangdashao/Matrix-Issues#1308]
Paper 1.13.2
All last version.
https://www.youtube.com/watch?v=ryJofSXxH5I&feature=youtu.be

**Comment by jiangdashao** [comment]
Did you install ViaVersion?

**Comment by mlegok12** [comment]
ProtocolSupport.

**Comment by jiangdashao** [comment]
Can you provide the verbose message?
/matrix verbose
