### ISSUE TITLE
Stuck in Block False Positives [Phase]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#131]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgohitKw6-u7F7Mkl2Q
https://1drv.ms/v/s!ApY4tKsF8vPUgokOXjv7Txqh66sU-A
https://1drv.ms/v/s!ApY4tKsF8vPUgohuRlyng6KWPhvu6A
https://1drv.ms/v/s!ApY4tKsF8vPUgohYc-8QLcd1n7zMTA
https://1drv.ms/v/s!ApY4tKsF8vPUgokPTAh4p--p29AgmA

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed

**Comment by ignPerformance** [comment]
Re-opened, some bugs still remaining.

**Comment by jiangdashao** [comment]
?

**Comment by ignPerformance** [comment]
https://1drv.ms/v/s!ApY4tKsF8vPUgotaTJ2_JlP1WJVCQA
Forgot to post.
