### ISSUE TITLE
[INCOMPATIBILITY] Command blocker doesnt work with matrix

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1312]
Server version: 1.15.2
Incompatible plugin: any command blocking plugin
How/when does this happen: if you block commandpreprocessevent in a command blocker plugin matrix still tells the player "you do not have permission to execute this command" showing them that the server they are on is running matrix
Photo of incompatibility: https://imgur.com/a/shyo2HT
Other information: Instead of listening for commandpreprocessevent when checking matrix permissions simply in the matrix command check if(p.haspermission("matrix.verbose") etc.

**Comment by jiangdashao** [comment]
You only can block it in Premium mode
