### ISSUE TITLE
[FP] Fly.gf

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1314]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: see vid
**How/when does this happen**: building a tower
**Video of false positive**: https://youtu.be/f765tOROq0w
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by rasputinea** [comment]
disable phase check, its not very stable in latest version
