### ISSUE TITLE
[FP] Gliding with Elytra into 1 block tall space fails Phase

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1322]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml // disable_bypass_permission: true (config.yml)
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Verbose messages**: (see video)
**How/when does this happen**: Glide into a 1 block tall space with elytra and move around in there to fail Phase check. Can also happen when going in from water to for example tree leaves with 1 block of space below.
**Video of false positive**:  https://streamable.com/jus8o

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/VVcBMsFC (default)

**Comment by jiangdashao** [comment]
Why you can glide on the ground?
