### ISSUE TITLE
[REQUEST] Disable all setbacks/cancels/unmounts in ghost mode.

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1327]
**What features/checks do you need?:**
Currently, the ghost mode in the config seems to disable a few cancels like for fly or jesus but it's still missing a lot of other checks.
Currently at least these setbacks/cancels/unmounts are not being disabled in ghost mode:
* Killaura
* Hitbox
* Scaffold
* Fastplace
* Fastbreak
* Inventory
* Spam
* Interact
* Phase
* Elytra
* Vehicle

Video of some cancels/unmounts while ghost mode is true: https://streamable.com/usx14

What I would like to see is for ghost mode to properly disable setbacks/cancels/unmounts for every check, as the description of the option suggests in the config file:
> If you enable Ghost Mode, Matrix will Not setback player or cancel illegal actions.

**Comment by jiangdashao** [comment]
Ghost mode only works for Speed/Fly check, I won't add it work for other checks
