### ISSUE TITLE
[BYPASS] Auto-Clicker

### ISSUE THREAD

**Issue by Pix-00** [jiangdashao/Matrix-Issues#1329]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: vanilla with extra auto-clicker
**Link to hacked client**: https://github.com/smith-j-travis/MinecraftAutoClicker
**Cheat that bypassed**: autoclick
**Video of bypass**: https://youtu.be/wQ8xsRC7dlI
**Other information**: start at 00:42

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
click block won't be detected
