### ISSUE TITLE
[FP] riptide along ground

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1332]
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: riptide along the ground whilst it is raining
**Video of false positive**: https://youtu.be/oAY0UHEGpW0
**Other information**: move.xz also triggers sometimes

## Configuration Files
**Link to checks.yml file**:

**Comment by Tomatobird8** [comment]
In air also on 1.14.4 https://streamable.com/o4yuw
