### ISSUE TITLE
[FP] Extra cancel after fastplace or fastbreak

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1335]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml // disable_bypass_permission: true 
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Verbose messages**: (see video)
**How/when does this happen**: Trigger fastplace or fastbreak violations enough to cause cancels and stop during the cancellation period, wait for any amount of time and then place or break a block (respectively depending on which cancels were triggered.)
**Video of false positive**: https://streamable.com/m83ws (fastplace only)

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/jKTPT11F (default)

**Comment by jiangdashao** [comment]
Not important
