### ISSUE TITLE
Boat Placement False Positive [Interact]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#134]
## How you trigger the false positive?
Watch the linked video.
Boats can be placed farther than normal blocks, and Matrix does not account for this.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgohltaoPlDsiX5Hdzg

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Related #145
