### ISSUE TITLE
[REQUEST] Improve elytra check

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1348]
**What features/checks do you need?:**
When force setback is on players are setback when the server is lagging and fall to their deaths (https://youtu.be/PDtjQQZDqKI) . If it is off then players using 2h2e elytra hacks can fly very far without being kicked (https://youtu.be/syy6R83Zv3s) . This could easily be fixed by adding new checks to detect 2h2e fake fireworks or changing the force setback boolean to force-setback-vl.

**Comment by jiangdashao** [comment]
I will improve firework boosting detection
