### ISSUE TITLE
[ERROR] Interact crash

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#1349]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Error(s) found in console**: https://pastebin.com/Hi66U0m4
**How/when does this happen**: once in 5-10 minutes.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
EntityInteract
