### ISSUE TITLE
Lilypad False Positive [Block/BadPackets/Speed/Interact]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#135]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgohmgoh6wGx5f9FAxQ

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Won't fix
