### ISSUE TITLE
[FP] Water false positives

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1352]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: https://pastebin.com/raw/Ry1FxGZm
**How/when does this happen**: when you use water elevator and stay in water above the ground it will cause false postiives, you just have to float on water which is not directly above the ground
**Video of false positive**: it happens with this water elevator for example: https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/6/67/Water-ladder.png/300px-Water-ladder.png?version=983a3963fe71f0d4a6977eae95abfb29
**Other information**: -

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
Your server is weird, I won't fix any movement bugs on your server

**Comment by DanielAlves123** [comment]
@jiangdashao what do you mean? Do the same water thing and check. Normal server with paperspigot and viaversion.

**Comment by SkyLicks** [comment]
@DanielAlves123 

- What jar are you using? Spigot? What build?
- What plugins do you have?
- Are you on the latest version of matrix?

**Comment by DanielAlves123** [comment]
@skylicks 
- paperspigot 1.8.8
- 0 plugins that modify players' behaviour: https://share.getcloudapp.com/bLumY4Ld
- i'm using the latest version of matrix.
(14:42:40) Matrix Enabled!
(14:42:40) Version: 4.2.2
(14:43:07) player Fly | ground spoof (expect: --, move: 0.0,0.075,0.0, at: 5.7,72.352,-22.636, type: air) (+5) | vl:5 ping:0 tps:20.0 component: fly.gf
(14:43:08) player Fly | ground spoof (expect: --, move: 0.0,-0.058,0.0, at: 5.7,72.241,-22.636, type: air) (+5) | vl:10 ping:0 tps:20.0 component: fly.gf
(14:43:10) player Fly | ground spoof (expect: --, move: -0.049,0.016,-0.025, at: 5.605,72.201,-22.713, type: air) (+5) | vl:15 ping:0 tps:20.0 component: fly.gf

**Comment by DanielAlves123** [comment]
@SkyLicks @jiangdashao

**Comment by DanielAlves123** [comment]
@jiangdashao @SkyLicks 1.12 client version it's important.

**Comment by DanielAlves123** [comment]
@jiangdashao @SkyLicks still isnt fixed

**Comment by DanielAlves123** [comment]
@jiangdashao still not fixed
