### ISSUE TITLE
[FP] Jesus/LiquidWalk false positive moving underwater

### ISSUE THREAD

**Issue by jordanamr** [jiangdashao/Matrix-Issues#1353]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: See the video
**How/when does this happen**: When a player is mining/moving under the water
**Video of false positive**: https://streamable.com/tfkgg
**Other information**: The player is running on 1.8.9, NO enchantment (depth strider) to move faster underwater

## Configuration Files
**Link to checks.yml file**: It is the premium checks.yml from the Discord

**Comment by jiangdashao** [comment]
Can't reproduce
