### ISSUE TITLE
[REQUEST] add flag to exclude interactable blocks from illegal interact check

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1354]
**What features/checks do you need?:**
https://streamable.com/t6t2t  you said that you cannot fix this so just add the option to exclude containers/crafting tables etc from illegal interact check. Or add the option not to cancel the interact, or traceback the players position a few ticks to see what they were really looking at.

**Comment by jiangdashao** [comment]
1. The client sends the interact packet before the moving packet, so I need to wait to the next tick to check the interact cheat, not traceback the position.
2. I don't think it's an important false positive, who would open the container like this?

**Comment by rasputinea** [comment]
@jiangdashao  https://youtu.be/nJJvYFAs4V4
