### ISSUE TITLE
[FP] people with massive amounts of ping flag hitbox check 

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1356]
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: when someone with 300+ ping (usually ping spike) pvps
**Video of false positive**: 
**Other information**: just dont check players with absurdly high ping for hitbox or ping compensate

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Add a "max_ping" option for hitbox check
