### ISSUE TITLE
[REQUEST] server lagspike protection doesnt work

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1358]
**What features/checks do you need?:**
https://youtu.be/LIHqYkLqQzU  players flag badpackets check, speed, killaura etc when server lags. Showing the check has not been closed. This could be addressed by having a thread check if main thread is frozen or not every few ticks.

**Comment by rasputinea** [comment]
Why was this refused if you dont mind saying?

**Comment by SkyLicks** [comment]
Already exists
![Screenshot_20200215-085628_Chrome](https://user-images.githubusercontent.com/34877092/74589188-178b8480-4fd1-11ea-887c-fdc643378ec7.jpg)

**Comment by rasputinea** [comment]
@SkyLicks @jiangdashao i know it exists, the issue i made is that it doesnt appear to work
