### ISSUE TITLE
[REQUEST] 2h2e elytraflight protection still lacking

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1359]
**What features/checks do you need?:**
https://youtu.be/pwC_ipgrzJk   why not just detect the sudden increase in energy and see if the player has actually used a rocket boost, or at the very least whether they are holding a rocket

**Comment by rasputinea** [comment]
you can utilize paper's playerelytraboostevent or listen for playerinteractevent for non-paper users (priority = monitor,ignore cancelled = true)

**Comment by jiangdashao** [comment]
I did, but you disabled setback
