### ISSUE TITLE
[INCOMPATIBILITY] Chat check incompatible with other plugins that modify chat

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1360]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Incompatible plugin**: Chat Modifying plugin
**How/when does this happen**: If a plugin modifies a player's chat then Matrix's "cancel_vl" for the Chat check would actually not cancel the chat message.
**Video of incompatibility**: Not needed
**Other Information**: 

Kindly add the `ignoreCancelled = true` flag to the Event Handler in order to allow Matrix to be better compatible with plugins modifying chat: @EventHandler(ignoreCancelled = true)

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
I did: 
![image](https://user-images.githubusercontent.com/21152113/74584538-78857d80-500e-11ea-8242-cd0f0f0016d3.png)
I guess your chat modifying plugin is working on HIGH priority too, or maybe higher priority
