### ISSUE TITLE
[FP] MCMMO Swords Bleeding Flags Kill Aura

### ISSUE THREAD

**Issue by markbuns** [jiangdashao/Matrix-Issues#1361]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: <Player> Might be using combat hacks (KillAura)
**How/when does this happen**: When attacking a large amount of mobs (a spawner farm) with the serrated strike (bleeding) swipe attack with a sword
**Video of false positive**: 
**Other information**: Serrated strikes is a MCMMO plugin addition that causes bleeding to enemies hit. Players get kicked if using this ability and using the sweeping strike against a large amount of mobs. Ideally I'd like to know how to modify config to not make this happen while still blocking actual hacking. Disabling KillAura anti cheat against npcs/mobs would also be useful.

## Configuration Files
**Link to checks.yml file**: Using default checks file

**Comment by rasputinea** [comment]
video?

**Comment by jiangdashao** [comment]
Please provide the verbose messages and video

**Comment by markbuns** [comment]
> Please provide the verbose messages and video

Not sure what you're looking for as far as 'verbose messages' but here is a clip of it happening with the chat showing admin messages:
Video hosted on imgur: https://imgur.com/a/WAUJBPU

**Comment by markbuns** [comment]
> /matrix verbose

Getting "internal error occurred" with that command and can't run it from the console, working on figuring that out
