### ISSUE TITLE
[FP] Block False positive

### ISSUE THREAD

**Issue by BackWheel** [jiangdashao/Matrix-Issues#1362]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: FastPlace/FastBreak Hacks
**How/when does this happen**: Mining with pickaxes with efficiency enchantment
**Video of false positive**: 
**Other information**: When a player uses a pickaxe with efficiency enchantment to dig a block, it will be detected as FastBreak.The same will happen when digging wood with an efficiency enchantment axe.

## Configuration Files
**Link to checks.yml file**:Using default checks file

**Comment by jiangdashao** [comment]
Please provide the verbose messages
