### ISSUE TITLE
[REQUEST] detect jesus hacks accurately

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1368]
**What features/checks do you need?:**
make jesus hacks not flag ground spoof check, so that the jesus checks will flag instead. Here is an video showing what i mean https://youtu.be/P4ya8DQzEwo

**Comment by jiangdashao** [comment]
what?

**Comment by jiangdashao** [comment]
I can't understand

**Comment by rasputinea** [comment]
when a player uses jesus hacks, the ground spoof fly check is set off, meaning they are kicked for fly instead of jesus hacks. Fly ground spoof shouldnt work for water blocks so that jesus checks will kick them instead

**Comment by jiangdashao** [comment]
No, if player is in the water, he shouldn't be "ground = true"
