### ISSUE TITLE
[BYPASS] Killaura

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1374]
**Server version**: 1.15.2
**Hacked client**: Aristois
**Cheat that bypassed**: killaura
**Video of bypass**: https://youtu.be/1OjevR-_fKM
**Other information**: Aristois killaura is quite smart, basically it extends the entity hitbox to be massive instead of snapping player head to entity. This is because when you attack a player with aristois killaura it flags hb.mis and kicks them, but there is no extended hitbox check for mobs meaning that it bypasses, this could be fixed by adding a very loose hitbox check to mobs.

**Comment by SkyLicks** [comment]
Funny story, I actually just caught a guy using Aristoles yesterday with Matrix. But yeah, maybe it can be improved.

**Comment by jiangdashao** [comment]
I can't trace back mob's history positions, because they don't have move event(they shouldn't have too, lol). If I use a task to record the mob's position, it will some performance issues. Anyway, MobAura is not important^^

**Comment by rasputinea** [comment]
@jiangdashao  why not just start tracking mob position after it is hit once by a player
