### ISSUE TITLE
[REQUEST] aristois afkbot

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1377]
**What features/checks do you need?:**
add aristois afkbot check to autobots module https://youtu.be/K4CVxhRUT2c sharp head snapping

**Comment by jiangdashao** [comment]
I guess it's undetectable, I will try tomorrow

**Comment by jiangdashao** [comment]
It can be detected, but the detect way is not safe enough, it will cause false positives if player use some mod like Optfine
