### ISSUE TITLE
[REQUEST] hb.mis check should include mobs

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1378]
**What features/checks do you need?:**
when a player hits a mob, start tracking that mobs position so that you can trace back. this would have much less of a performance impact then tracking all entities movements. aristois killaura is quite powerful against npcs and mobs and isnt detected at all: https://youtu.be/RtlpkbelHhs

**Comment by jiangdashao** [comment]
After I tried, I found it's very inaccurate, so I can't fix it...
