### ISSUE TITLE
[REQUEST] Suggested Compatibility Fix (Tested Working)

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1382]
**What features/checks do you need?:**
![image](https://user-images.githubusercontent.com/34877092/74673255-dfc14000-517c-11ea-9193-b14fa4ba3a73.png)

**Comment by jiangdashao** [comment]
1. If you have a chat plugin, why not block the spam by your self?
2. You can custom the event priority in config.yml:
`priority:
  AsyncPlayerChatEvent:LOW`
