### ISSUE TITLE
[ERROR] Could not pass event PlayerMoveEvent to Matrix v4.2.3

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#1383]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Error(s) found in console**: https://gist.github.com/e4ee3731bc5c1f45da865ac2bc0f31b4
**How/when does this happen**: Not sure. In this case, it seems like it happened after the server suspended itself at 0 players, and shortly after a player logged in, resumed the server, and joined a pvp game Matrix threw and error and eventually threw more and spammed errors, which you can see in the gist above.
**Other information**: I am unable to test this on default config because I don't know how or when it happens. 

## Configuration Files
**Link to checks.yml file**: https://gist.github.com/2b9350214501cc790ae6663dcf484b80#file-checks-yml
**Link to config.yml file**: https://gist.github.com/2b9350214501cc790ae6663dcf484b80#file-config-yml

**Comment by jiangdashao** [comment]
Try official spigot server, paper or sportpaper is not stable and useless for 1.8 server
