### ISSUE TITLE
[FP] cancel_vl doesn't work with fly, maybe with other checks too

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1386]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: (06:42:00) player Speed | suspicious movement (move: 1.031, predict: 0.19, friction: 0.6, ground:false, motY: 1.505, increase:0.026, preMove:0.164, motion: -0.42,1.505,0.942, attribute: 0.13, tag: pred) (+5) | vl:10 ping:36 tps:20.0 component: move.xz
(06:42:00) player Fly | step | p: 1 | m:1.5050198880621721 ev:-0.078 (+8) | vl:16 ping:36 tps:20.0 component: speed.step

**How/when does this happen**: it cancels movement even if cancel_vl  set to -1 or high value
**Video of false positive**: -
**Other information**: setting cancel_vl in speed works

## Configuration Files
**Link to checks.yml file**:-

**Comment by jiangdashao** [comment]
Because some checks must be cancelled

**Comment by DanielAlves123** [comment]
@jiangdashao then why you set this in config? Some checks are broken, for example when you launch a player inside a vehicle then ejects him, it will drag him back.
https://github.com/jiangdashao/Matrix-Issues/issues/1235 this is still active

**Comment by DanielAlves123** [comment]
@jiangdashao when someone sets this value then he doesn't want to cancel fly below this level, that's obvious.

**Comment by rasputinea** [comment]
@DanielAlves123 toggle "ghost_mode" on in the config
