### ISSUE TITLE
[ERROR] Number of violations check only equal values

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1387]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Error(s) found in console**:   # Violation Thresholds
  # number_of_violations: '<command>'
  commands:
    75:
**How/when does this happen**: it only executes command when number is equal in config, if it's higher by 1 or similar it doesn't show, it should check if it's higher or equal and don't send same messae when it's higher
**Other information**: /\

## Configuration Files
**Link to checks.yml file**: x
**Link to config.yml file**:x

**Comment by jiangdashao** [comment]
No, it executes when higher

**Comment by DanielAlves123** [comment]
@jiangdashao that's true my bad.
