### ISSUE TITLE
[FP] Sword blocking stays server side causing speed false positives

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1389]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: (07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:240 ping:15 tps:20.0 component: speed.main
(07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:249 ping:15 tps:20.0 component: speed.main
(07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:258 ping:15 tps:20.0 component: speed.main
(07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:267 ping:15 tps:20.0 component: speed.main
(07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:276 ping:15 tps:20.0 component: speed.main
(07:51:02) player Speed | suspicious movement (move: 0.216, expect:0.128, t:100, tag: a) (+9) | vl:285 ping:15 tps:20.0 component: speed.main

**How/when does this happen**: sword blocking bugs on server side, while on client side you don't see that you are blocking, which is causing quick false speed detections
**Video of false positive**: -
**Other information**: I would suggest to disable sword blocking for player when detecting speed.

## Configuration Files
**Link to checks.yml file**:-

**Comment by DanielAlves123** [comment]
@jiangdashao please tell me why you close this

**Comment by rasputinea** [comment]
you did not supply a video of this happening

**Comment by DanielAlves123** [comment]
@rasputinea it's hard to reproduce (maybe not that hard but I use 1.12 for example) and it's just how it works and this happens.
