### ISSUE TITLE
[ERROR] java.lang.NoSuchFieldError in 1.15.2

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1390]
**Server version**: 1.15.2
**Error(s) found in console**: https://pastebin.com/pMkeV4aL
**How/when does this happen**: i believe this is the new sneak pattern check. in 1.15.2 there is no "STOP_SNEAKING" field

**Comment by jiangdashao** [comment]
Update your ProtocolLib
