### ISSUE TITLE
[REQUEST] API Request

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1391]
**What features/checks do you need?:**

Add a "PlayerViolationDecayEvent" that fires an event every time violations delay.

Reason: Useful event to have when designing custom checks for Matrix.

**Comment by jiangdashao** [comment]
why

**Comment by jiangdashao** [comment]
you can decay the VL by yourself, why you need an event...

**Comment by SkyLicks** [comment]
I was making some custom chat checks and wanted to better control the vl decay. I found an alternative, but I still think it can be a useful feature.

**Comment by jiangdashao** [comment]
The process of changing the API is a bit cumbersome, I don’t want to change it if it is not necessary
