### ISSUE TITLE
[FP] tp by command block

### ISSUE THREAD

**Issue by Pix-00** [jiangdashao/Matrix-Issues#1394]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.15.2 (Paper-107)
**Verbose messages**: 
https://paste.ubuntu.com/p/bmVZw3T42w/
**How/when does this happen**: 
When players tp by a command block (triggered by string).
**Video of false positive**: 
https://youtu.be/FcslEYyC7Ck
**Other information**: 
![image](https://user-images.githubusercontent.com/15878537/74817819-869e0b80-5338-11ea-9d2c-4a8eef9ae9ad.png)
commands (there are four command blocks with one at each conner):
/execute as @e[x=-551,y=77,z=179,dx=0,dy=2,dz=20] at @s run tp ~18.5 ~ ~
/execute as @e[x=-551,y=77,z=179,dx=20,dy=2,dz=0] at @s run tp ~ ~ ~18.5
/execute as @e[x=-531,y=77,z=179,dx=0,dy=2,dz=20] at @s run tp ~-18.5 ~ ~
/execute as @e[x=-551,y=77,z=199,dx=20,dy=2,dz=0] at @s run tp ~ ~ ~-18.5

## Configuration Files
**Link to checks.yml file**:
_[Default]_

**Comment by jiangdashao** [comment]
It's a server bug, bukkit/spigot can't handle some teleport correctly
