### ISSUE TITLE
[FP] Speed

### ISSUE THREAD

**Issue by mlegok12** [jiangdashao/Matrix-Issues#1398]
All last version.
Paper spigot 1.13.2
I have plugin which called Mythic Items. By this plugin i can create different items with unusal properties. I created a sword and helmet which give +10% to speed you can see in video. When they start fight and run they get false positives of speed and return to the old point as you can see in the video
https://youtu.be/MnAeT7B8ft8

**Comment by rasputinea** [comment]
Link to mythic items plugin?

**Comment by mlegok12** [comment]
https://www.mythicmobs.net/index.php?resources/artifacts-mythic-items-and-enchantments-early-access-25-off.37/

**Comment by mlegok12** [comment]
Before the last updates, it worked perfectly. But after that there are a lot of FP's
