### ISSUE TITLE
[FP] Velocity

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1399]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:  
(17:25:39) player Velocity | ignore server velocity: -0.482,0.361,-0.018 pct:0.037 pattern:#3 (+7) | vl:38 ping:38 tps:20.0 component: vel.expect
(17:25:39) player Velocity | ignore server velocity: -0.482,0.361,-0.018 d:0.48225 pattern:#2 (+5) | vl:43 ping:38 tps:20.0 component: vel.expect
(17:25:40) player Velocity | ignore server velocity: 0.322375 pattern: #8 (+2) | vl:45 ping:38 tps:20.0 component: vel.expect

**How/when does this happen**: when you hit player near fake wall (sendBlockChange) it will detect velocity
**Video of false positive**: not needed
**Other information**: not needed

## Configuration Files
**Link to checks.yml file**: not needed

**Comment by rasputinea** [comment]
dont have a fake wall then, since the blocks are clientside i doubt this can be fixed

**Comment by DanielAlves123** [comment]
@rasputinea how about world border? I saw similar issue. Maybe check x/z coordinates to fix this.
