### ISSUE TITLE
Arrow Dispenser False Positive [Velocity]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#140]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgotgjXOSAojtig0w2A

## Server Infomation
**Matrix Version**: 1.8.3
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Reopened. Watch the linked video.

**Comment by jiangdashao** [comment]
It was caused by the client's unexpected movement, I can't fix it
And the knockback check is designed for MiniGame server, you'd better disable it
