### ISSUE TITLE
[BYPASS] Liquid speed

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1403]
**Server version**: 1.15.2
**Hacked client**: wwe
**Cheat that bypassed**: liquidspeed
**Video of bypass**: https://youtu.be/-0ELa5KRexU
**Other information**: seems to not have been fixed

**Comment by Tomatobird8** [comment]
Video seems to be private. Not sure if this is intended but seems like it isnt considering that your other ones are unlisted.

**Comment by jiangdashao** [comment]
video private
