### ISSUE TITLE
[FP] Server kept kicking for flight 

### ISSUE THREAD

**Issue by MCHalfAssed** [jiangdashao/Matrix-Issues#1405]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
Running on 1.15.2

- [ ] The issue happens on default config.yml and checks.yml

- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**: No video - went into creative and watched the players moving normally
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
This is my config and checks
config  - https://hasteb.in/aquhonav.yaml
checks - https://hasteb.in/ofawusal.yaml
logs - https://hasteb.in/putoqata.sql

**Comment by jiangdashao** [comment]
Are there fake blocks in your server? Other people didn't get this false positive
