### ISSUE TITLE
[FP] Jesus

### ISSUE THREAD

**Issue by Speentie8081** [jiangdashao/Matrix-Issues#1406]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: [21:45:03 INFO]: This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Verbose messages**: The /matrix verbose command says that I do not have permission even though I am opped and owner of the server, it also says I cannot execute the command from console. However this is what I was able to pull from the logs [https://pastebin.com/WScQtJUc](https://pastebin.com/WScQtJUc).
**How/when does this happen**: When maintaining water level height to break blocks along the shore
**Video of false positive**: [https://www.youtube.com/watch?v=buCs31mERYA](https://www.youtube.com/watch?v=buCs31mERYA)
**Other information**: 1.7.10 client, although it should be possible to reproduce on any version given the nature of the problem

## Configuration Files
**Link to checks.yml file**: [https://secure.devon.com.de/checks.yml](https://secure.devon.com.de/checks.yml)

**Comment by rasputinea** [comment]
please dont use protocolhack plugins such as viarewind to allow 1.7 players to join a 1.15 server, these are extremely buggy and mess with alot of anticheats.

**Comment by jiangdashao** [comment]
I can't reproduce this false positive (1.15.2 client + 1.15.2 server)

**Comment by Speentie8081** [comment]
> please dont use protocolhack plugins such as viarewind to allow 1.7 players to join a 1.15 server, these are extremely buggy and mess with alot of anticheats.
Yes I agree the Via suite is extremely buggy and refuse to use it, that's why I use ProtocolSupport which I have independently contributed to and the main developer works very hard to make it a native experience unlike the Via suite. I have not experienced any bugs with using this, not even when connecting to the server on pocket edition, but yes it does cause issues with anticheats here and there. I find it pretty biased to say that all protocolhack plugins are extremely buggy but specifically point to the Via suite as an example when it is clearly stated by the development team of ViaRewind that it has many bugs in their support channel.

> I can't reproduce this false positive (1.15.2 client + 1.15.2 server)
This is true, I just confirmed that when I connect to the same server with a 1.15 client without removing the support plugin, there is no false positive. My goal was not to encourage the anticheat support 1.7 clients despite what it seems. I would like to be able to configure the jesus checks manually if possible, to be able to increase the tolerance for these versions for my own use case, without you specifically supporting these versions. For the time being I have disabled this check because it is unplayable with it on, but with it off there are no issues whatsoever.

I will close this issue because it does not apply to the ideal use case of this plugin.
Please consider my suggestions, it would be greatly appreciated in a later release.
