### ISSUE TITLE
[FP] High step in vanilla

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1413]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml // disable_bypass_permission: true 
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-98 (MC: 1.15.2)
**Verbose messages**: (see video)
**How/when does this happen**: Fall to the side of a tall block and step up. Example setup in video. Can also happen with full blocks in certain conditions. 
**Video of false positive**: https://streamable.com/nyj65

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
Who would put this in a real server?

**Comment by Tomatobird8** [comment]
Realistically probably no one at this scale. It does happen occasionally in normal gameplay and altho its a very minor issue, in case it could be fixed easily I decided to report it.
