### ISSUE TITLE
[BYPASS] NoSlowdown while sneaking

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1420]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-98 (MC: 1.15.2)
**Hacked client**: Wurst v7.0
**Link to hacked client**: https://github.com/Wurst-Imperium/Wurst-MCX2/releases/download/v7.0/Wurst-Client-v7.0-MC1.15.2.jar
**Cheat that bypassed**: NoSlowdown
**Video of bypass**: https://streamable.com/mleqn

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Because sneak slowdown and bow/food slowdown are different. Use food/bow is faster than sneaking, so I use tolerant speed limitations
