### ISSUE TITLE
[BYPASS] Carry items in crafting slots

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1429]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-114 (MC: 1.15.2)
**Hacked client**: WWE Version 3.0.4
**Link to hacked client**: https://wweclient.com/addownloadnew.php?type=1.15.2%20fabric
**Cheat that bypassed**: XCarry + Invetory Walk
**Video of bypass**: https://streamable.com/evl65
**Other Information**: Carry check only seems to apply when player is on the ground and not jumping. You can also enter a horse and travel freely while carrying the items. Also for some reason at the end of the video the module broke completely after the vehicle cancel 🤔

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I can't fix that, sometimes "InventoryClickEvent" not trigger when player click crafting slots
