### ISSUE TITLE
Vehicle False Positive (Donkey) [Vehicle Flight/Speed]

### ISSUE THREAD

**Issue by Justin42** [jiangdashao/Matrix-Issues#143]
## How you trigger the false positive?
Walking up or down 1 block while mounted on a donkey causes the player to be dismounted.

Possibly relevant config:
speed.entity_speed: false
fly.strict_glide.enable: true
fly.strict_glide.max_diff: 0.5

## Verbose Message:
failed Speed check | t: vehicle flight a=0.35716345313029235 b=-0.0784000015258789 c=0
 d=DONKEY (+5) | vl:5 ping:55 tps:20.0

failed Speed check | t: vehicle flight a=0.0 b=-0.0784000015258789 c=150 d=DONKEY (+5)
 | vl:5 ping:35 tps:19.99

failed Speed check | t: vehicle flight a=0.0 b=-0.0784000015258789 c=50 d=DONKEY (+5)
| vl:10 ping:35 tps:20.0

## Videos:
https://www.dropbox.com/s/jb0jj89802xk36y/Peek%202019-04-06%2012-00.webm

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Paper 1.13.2 build#600
**ProtocolLib Version**: 4.4.0

Edit: Video link replaced

**Comment by ignPerformance** [comment]
I am unable to reproduce this false positive. Please provide a video @Justin42.

**Comment by Justin42** [comment]
I'll post a video soon. 

Some additional information:
In Matrix 1.8.1 this only occurred when speed.entity_speed: true was set. Disabling that resolved the issue. In 1.8.2, only disabling the speed check entirely seems to work. However, there may be other variables. 

I'll try to narrow this down further before posting a video, it's possible that this a compatibility issue but as far as I'm aware I don't have any plugins that affect vehicle movement.

**Comment by ignPerformance** [comment]
Send your plugin list?

**Comment by jiangdashao** [comment]
xD, you disabled "entity speed" check, but the "vehicle flight" flagged you, they are different checks.

**Comment by Justin42** [comment]
I think this should probably be reopened. I can followup with more details, but I see no reason to close it unless it has been fixed, or if disabling the vehicle flight check is your solution.

Disabling the check was my attempted workaround to the issue, it does not resolve the issue.

**Comment by jiangdashao** [comment]
If you provide enough evidence, I will reopen it

**Comment by Justin42** [comment]
Here is a quick round of testing on a live server.
https://drive.google.com/open?id=1ErMOp6Y85g3ILWwlPBHzAXqoh_dc4ow9

I haven't had time to narrow down the issue yet, but I will continue to provide more details and more thorough testing of my own to help resolve the issue, so long as the issue is acknowledged and remains open.

I'd prefer not to post a plugin list of my live server, I'll first narrow down the issue on my test server, but so far my suspicions are with "TownyFlight". However, I haven't yet confirmed that this is a compatibility issue either.

**Comment by Justin42** [comment]
I have now reproduced this issue using only LuckPerms 4.4.0 and ProtocolLib 4.4.0
I'm replacing the other video links, as they contain extraneous information.

Here is a new video:
https://www.dropbox.com/s/jb0jj89802xk36y/Peek%202019-04-06%2012-00.webm

I'll test with the newest version of LuckPerms soon, if it is still reproducible I will try to narrow the issue to server configuration.

**Comment by Justin42** [comment]
Issue appears to still be present using LuckPerms 4.4.2 and Paper Build#610
I'll examine server configuration and provide more details as time allows.

**Comment by Justin42** [comment]
I'm able to reproduce this even with default server configuration, with and without LuckPerms.

Horses also cause entity speed check false positives and dismount, but this is a separate (related) issue. They don't fail the fly check like donkeys do. Disabling entity speed check is a workaround for the Horse issue.

The only way I've been able to get both horses and donkeys to function properly is by disabling entity speed checks (for horses) and all fly checks (for donkeys)

Seeing as @ignPerformance was unable to reproduce these issues, I think there must be some other factors at play. Here is some additional system details:

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Linux debian 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux (Debian GNU/Linux buster/sid)
and
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux (Debian GNU/Linux 9 stretch)

I can try to reproduce this using Java 11, but probably not today.

**Comment by ignPerformance** [comment]
I am now able to reproduce this. It seems fast horses flag for entity speed.
Being bucked off a horse also flags for Fly @jiangdashao 
https://1drv.ms/v/s!ApY4tKsF8vPUgotP_ghTH4NH_8KAZg

**Comment by Justin42** [comment]
Great! Just to clarify, were you also able to reproduce the Donkey issue? I think these are related but not identical issues.

**Comment by Jaspenton** [comment]
I found the donkey false positive and came here to find a fix - I could only fix by disabling the fly check in the gui
