### ISSUE TITLE
[BYPASS] Entity Ride on horses

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1435]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-114 (MC: 1.15.2)
**Hacked client**: WWE Version 3.0.4
**Link to hacked client**: https://wweclient.com/addownloadnew.php?type=1.15.2%20fabric
**Cheat that bypassed**: Entity Ride (+ Boat Fly in water)
**Video of bypass**: https://streamable.com/5jjm1 https://streamable.com/5eok1
**Other Information**: 
* Vehicle speed check seems to be way too lenient
* There is probably no horse jump height attribute data used to check how high a horse can actually jump so now horses can all jump to extreme heights
* You can go even faster in water than on ground while in vanilla normal horses should slow down (skeleton horses speed up).
* You can move upwards in deep waters with Boat Fly.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Vehicle check can't be strict
