### ISSUE TITLE
Log Matrix Notify to console [Feature Request]

### ISSUE THREAD

**Issue by Justin42** [jiangdashao/Matrix-Issues#144]
# What features/checks do you need?
A configuration option to log matrix notify (and possibly verbose) output to console. Currently, it seems that it is only possible to have it logged to file. While that is often the preferred behavior, I believe a configuration option to log to console would be extremely useful. Especially in cases where the console is being monitored via discord or other external interfaces.

**Comment by jiangdashao** [comment]
The "notify" message will be output in console, but i won't add verbose message to console
