### ISSUE TITLE
Flight/Blink/hovering in the air [BYPASS] 

### ISSUE THREAD

**Issue by Thin-Troll** [jiangdashao/Matrix-Issues#1441]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 kernel PaperSpigot
**Hacked client**:  JigSaw, LiquidBounce & other
**Link to hacked client**: none (I use the launcher)
**Cheat that bypassed**:  Blink
**Video of bypass**:  https://sun9-16.userapi.com/c205716/v205716810/7e217/soAvSM8QZ0o.jpg, https://monosnap.com/direct/qdLHA0VG0v4nv1LMYAzQH9B8DFfaB1
**Other information**: Use cheat functions to hover in the air. at SkyPvP they manage to survive without falling.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
You should enable the server's built-in flight checks, it can prevent "Hover" flight cheat

**Comment by Thin-Troll** [comment]
> You should enable the server's built-in flight checks, it can prevent "Hover" flight cheat
the fact of the matter is that server checks kick only when the Flight function is enabled in the cheat.
but if you turn on the blink, neither the Matrix nor the server kicks.

https://monosnap.com/direct/qOMFB2fgxRJPSkQ0bktrSTwCon6hr2
https://monosnap.com/direct/nqgX0rQGaYcjnsAgFZcz4yUOF2S5nv

**Comment by jiangdashao** [comment]
I guess after the player enables the Blink feature, it stops sending any movement packets. So the server can't detect it.
