### ISSUE TITLE
[REQUEST] add killaura eating check

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1442]
**What features/checks do you need?:**
Almost every form of killaura doesn't stop attacking while the player is eating an item. Add a killaura check to detect when a player attacks but is eating at the same time.

**Comment by jiangdashao** [comment]
I worry if desync happens, this may cause false positives.
desync: eating in the server-side, but not eating in the client-side

**Comment by rasputinea** [comment]
make the check give small vl then?

**Comment by rasputinea** [comment]
speed check checks if player is eating which could also cause desync (hasnt happened to me before personally)

**Comment by jiangdashao** [comment]
I tested some clients, it can't work
