### ISSUE TITLE
[REQUEST] Make vehicle speed ignore blue ice

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#1445]
**What features/checks do you need?:** Add a setting to toggle whether vehicle speed should ignore the player if they are riding on blue ice.

Boat on blue ice still causes false positives(for example demonstrated on this video: https://cdn.discordapp.com/attachments/680647756842270731/680787782859489310/video0.mov , not sure which version is that, but I've managed to reproduce it on the latest version). I assume due to how fast you can go with a boat on blue ice it's hard to eliminate the false positive as it was already reported a few times and never got entirely fixed. Adding this setting would allow servers that rely on blue ice travel to keep the vehicle speed check enabled without annoying their players. I don't think that would cause any dangerous bypasses, as boats on blue ice are already fast enough to crash a server.

**Comment by jiangdashao** [comment]
I will try to fix the false flags, not disable it
