### ISSUE TITLE
[FP] On-ground speedboost with elytra

### ISSUE THREAD

**Issue by Tomatobird8** [jiangdashao/Matrix-Issues#1448]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml // disable_bypass_permission: true 
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-114 (MC: 1.15.2)
**Verbose messages**: (see video)
**How/when does this happen**: When boosting yourself on ground with elytra or landing from moderately or very high speeds. Currently my players are getting very high violation levels quickly due to this.
**Video of false positive**: https://streamable.com/tlmqk

## Configuration Files
**Link to checks.yml file**: default

**Comment by rasputinea** [comment]
what is your server tomatobird?

**Comment by Tomatobird8** [comment]
not willing to share publicly but i can send it privately. github doesnt seem to have a private communication feature so im available on discord, twitch or steam for that instead
