### ISSUE TITLE
[ERROR] Crash? (Maybe)

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1450]
**Server version**: 1.15.2
**Error(s) found in console**: https://pastebin.com/s9b1Fvfx
**How/when does this happen**: i do not know
**Other information**: what is causing this crash? could it have something to do with matrix? I was told that its caused by entity moving too fast but wouldnt matrix prevent this?

**Comment by jiangdashao** [comment]
I guess it was caused by I disabled the built-in anti cheat
