### ISSUE TITLE
[REQUEST] X-Ray (Please read)

### ISSUE THREAD

**Issue by NikV2** [jiangdashao/Matrix-Issues#1453]
******What features/checks do you need?:**

First of all, before saying *Use paper's built in x-ray* Understand this.

Paper's built in x-ray is very TPS Consuming + Causes issues with chunks for example if someone is breaking blocks too fast he can see random ores even visually

Now what am i exactly suggesting?
I know there used to be an old X-Ray check, and it did not work too well so it got removed.

BUT, here's how an x-ray check should be done - executed. (Please do not ignore and keep reading)

Here's an example configuration:
-----
XRay:
     #How many ores does the player need to break in order to notify the staff?
     Ores: 100
     #In how many minutes should matrix check how many ores the player broke?
     Interval: 5
    OR
     #Commands to execute
     - 100(ores): matrix notify.xray {player} Might be using x-ray
     - 150: matrix notify.xray {player} is using x-ray
     - 300 matrix kick {player} turn off ur xray or yo mama g@y
     #Blocks to count as Ores
      - iron_ore
      - coal_ore
      - e.t.c
      permission: matrix.notify.xray for example
-
OR it could work simular to this, for example IF the player broke {amount} of ores in {minutes} notify the staff. Or use {commands} 
-

Q) Why would Matrix benefit from having an x-ray check?

A) Matrix has now become a very well known anti cheat, and is becoming better and better over time. NO Anti cheat has an X-Ray check meaning if Matrix implements one. = More popular , Better overall.

The old x-ray check was a mess because it used to detect x-raying with player movements-looking and such. This is NOT needed for an x-ray check.

Q) Why don't you just use an x-ray plugin that does exactly what you said?
A) No server owner wants to use multiple plugins and it'd really be a life saver if this was implemented inside the anti cheat.

I really think matrix will benefit a lot for having an x-ray check
Thanks for reading !
Big fan of your development.
- Nik****

**Comment by True-cc** [comment]
![image](https://user-images.githubusercontent.com/38010540/75205189-f55bda00-5727-11ea-9ac4-e77d25a1d16a.png)

**Comment by NikV2** [comment]
LMAO

**Comment by rasputinea** [comment]
@NikV2  use xray mode 1, paper antixray has literally almost 0 performance inpact on engine mode 1, your check for xray is quite foolish as people who collect diamond ore with silk touch and break it with fortune would be kicked falsely.

**Comment by rasputinea** [comment]
xray engine mode 1 also fixes your random visual ore issue

**Comment by NikV2** [comment]
@rasputinea I don't think you understand my suggestion.
This request is not about Me specifically. i'm suggesting it because simply it would be great for an anti cheat such as matrix, and very useful. And no. Your wrong. Sure engine mode:1 is not laggy at all but it's also useless. Block updates do not work like engine mode 2 and All recent x-rays that also refresh the view distance of the chunks below bypass engine mode 1.

And no, again u didnt understand what i was saying. It won't detect - count how many minerals the player has gotten from mining. It would simply detect - count how many Ore Blocks the player has mined. There won't be any false positives with such a check.
Why?
If i set it to 150 Ore Blocks and the check interval at 2 minutes. Isn't it very obvious that the player is using x-ray? The fact that he broke 150 ores in 2 minutes?

And it can be configurable by the user himself. It'd give the option for users to put their own interval - block amount.

**Comment by NikV2** [comment]
And just a reminder, not many users of matrix are using paper (idk why though)

**Comment by rasputinea** [comment]
silk touch enchantment lets you collect ore, people use silk touch to collect this ore, then mine it all at once with a fortune 3 pickaxe, this means when they do that they will be false flagged. Engine mode 1 hides selected ores that dont have contact to air, you cannot bypass it be refreshing chunks. Try it yourself.

**Comment by NikV2** [comment]
Oh about that, then you're correct. But there could be an option for that, for example after the player mines - grabs that specific ore. Then if he breaks it again in the last 60 minutes (example) it won't count as block broken in x-ray check.

Or something simular. there's plenty of ways to prevent that. For example the check can only check Lower height of the world (mines e.t.c)

What are your settings for engine mode 1? I tried engine mode 1 with a couple of configurations and a few blocks could still be shown below the player, a few coal ores for example that had light on them.

**Comment by NikV2** [comment]
The thing is, not every matrix user uses paper. sure most of them might. But not all of them. I personally think such check would be very useful to those who do not use paper and EVEN to us paper users. 

And i do not disagree about the false positive that you mentioned, all im saying is that there are ways to make such problems preventable.

**Comment by rasputinea** [comment]
a few blocks will be shown with xray mode 1, as i said it only hides ore not in contact with air, 90% of ore however is hidden which is enough to nullify xraying. If they dont use paper tell them to use it, simple as that. They should be using paper anyways.

**Comment by jiangdashao** [comment]
I don't think it is useful to check the amount of ore mining, cheaters can control their mining speed to bypass anti-cheating (once they find anti-cheat)

**Comment by rasputinea** [comment]
also you *can* add metadata to mined ore but it resets when server restarts, meaning ore stored in chests etc that is then mined will false flag

**Comment by NikV2** [comment]
Then it's up to the server owner to reduce the block amount in the config, Most x-rayers do not expect a built in anti x-ray notification thingy (my guess) Most of them just expect the owners to use the built in x-ray

**Comment by rasputinea** [comment]
`    anti-xray:
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - mossy_cobblestone
      - chest
      - diamond_ore
      - redstone_ore
      - emerald_ore
      replacement-blocks:
      - stone
      - andesite
      - granite`

here is my config, makes xraying useless. The notification thing is very primitive and not reliable. Its better to just make xraying useless from the beginning.

**Comment by NikV2** [comment]
With that said, it's up to the developer to decide, I'm just throwing my suggestion in here. Thanks again @rasputinea For sharing your opinion ^^

**Comment by NikV2** [comment]
Also thanks for the config!! i'll try it out.

**Comment by NikV2** [comment]
#Note#
I simply added a suggestion on how an x-ray check *could* work.
If RE has more options to make such check. Then my suggestion doesn't matter.

At the end of the day, I think it'd be a huge benefit for matrix to have its own X-Ray check that's efficient ! (Gonna save spigot users from using plugins)

**Comment by jiangdashao** [comment]
I won't add stupid ore mining limit, it doesn't help. Unless there is a better way.

**Comment by NikV2** [comment]
Fair enough, Up to you to decide how it could work.

**Comment by jiangdashao** [comment]
I have no idea. ¯\_(ツ)_/¯
The only way is as paper does: hide or obfuscate ores

**Comment by NikV2** [comment]
@jiangdashao IF you end up adding such a feature, I'd be glad to test it out on my test server to report to you how it works  - false positives e.t.c Before releasing

Let me know!
