### ISSUE TITLE
Velocity & Strafe [BYPASS] 

### ISSUE THREAD

**Issue by Thin-Troll** [jiangdashao/Matrix-Issues#1454]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 PaperSpigot
**Hacked client**:  Flux B13
**Link to hacked client**: https://yadi.sk/d/1ikFNbrW7qj5mQ
**Cheat that bypassed**:  Velocity, Strafe
**Other information**: Velocity AAC (Amount: 0%), if you don’t stand still, but move constantly, then you won’t kick for Velocity. 
Strafe works according to the standard with it you can quickly run backwards, quickly jump in different directions, quickly maneuver in the air.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by rasputinea** [comment]
please include a video of this with verbose messages on

**Comment by jiangdashao** [comment]
Yes, I know.
The Velocity check is bad, I still don't have a good idea to detect it

**Comment by Thin-Troll** [comment]
Do you need a video?

**Comment by jiangdashao** [comment]
no

**Comment by jiangdashao** [comment]
I won't fix the strafe bypass, it's not important.
I will try to fix the anti knockback bypass when I find a way
