### ISSUE TITLE
[REQUEST] Jumping on blocks where you can't build

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1456]
**What features/checks do you need?:**
when you place block where you can't do it (event cancelled) blocks is showed for split second. if you do that near a wall you can jump on these blocks to the top of this wall. Matrix should detect it and drag player back and not let him jump on these blocks.

**Comment by rasputinea** [comment]
use adventure mode

**Comment by DanielAlves123** [comment]
@rasputinea if you have cheats you can modify them to place blocks even on adventure mode, so this will be bypass.

**Comment by DanielAlves123** [comment]
Also you can reduce fall damage with that.

**Comment by rasputinea** [comment]
which cheat allows adventure mode block placement?

**Comment by DanielAlves123** [comment]
@rasputinea if you can modify client to have cheats, you can implement this feature too. I don't know if any cheat has this option, but it's possible that it's already done in some cheat.

**Comment by Tomatobird8** [comment]
That specific modification is actually I had implemented in my own modified client years ago, as well as a "double jump/infinite jump" mod that allowed me to jump in mid air as if there was a block.
There is already a check for ground spoof in Matrix actually which can check pretty much exactly what you requested. You'll just have to set the fly cancel levels in the checks.yml very low so it sets the player back upon just one or two ground spoof attempts.

**Comment by DanielAlves123** [comment]
@tomatobird8 there's no check in Matrix that blocks this feature.

**Comment by rasputinea** [comment]
@DanielAlves123 it is detected as fly im fairly sure

**Comment by DanielAlves123** [comment]
> @DanielAlves123 it is detected as fly im fairly sure

try placing blocks near wall and jumping on them to the top of the wall, nothing detects that.

**Comment by Tomatobird8** [comment]
Oh yeah he's right. I thought I saw it work in an earlier version.... maybe one of the updates broke that?
