### ISSUE TITLE
[ERROR] java.lang.NoSuchFieldError: STOP_SNEAKING

### ISSUE THREAD

**Issue by Rigagit** [jiangdashao/Matrix-Issues#1460]
You can not close the page without even waiting for a response message?
https://github.com/jiangdashao/Matrix-Issues/issues/1459

last PLib 4.5.0 https://i.imgur.com/MpjIDW7.jpg
In error see PSupport, last ver too https://i.imgur.com/OnT3JU3.jpg

**Comment by jiangdashao** [comment]
I said, update your ProtocolLib
