### ISSUE TITLE
[FP] Scaffold triggers for planting things to fast

### ISSUE THREAD

**Issue by BijuuKrunos** [jiangdashao/Matrix-Issues#1461]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
This server is running Paper version git-Paper-112 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**How/when does this happen**: 
If the player is planting crops all sorts too fast.
**Video of false positive**: 
https://cloud.heroblade.net/index.php/s/JqedfasZiN4JW2z

**Comment by jiangdashao** [comment]
I can't reproduce the false positive, you should enable the verbose message output when you recording the video (/matrix verbose)

**Comment by BijuuKrunos** [comment]
https://cloud.heroblade.net/index.php/s/LimaNNekT3AcjZX
Here a video with /matrix verbose

And here is the part from the checks.yml:

`scaffold:
  # Enable this check
  enable: true

  # Cancel VL
  cancel_vl: 15

  # Modules
  modules:
    # It can detect player bridging faster
    scaffold:
      enable: true
      vl_weights:
        safewalk: 4
        expand: 3
        limit: 1
        head: 5
        simple: 3
        direction: 4
    # It can detect player towering up faster
    tower:
      enable: true
      vl_weight: 2

  # Violation Thresholds
  # number_of_violations: '<command>'
  commands:
    4: 'matrix notify %player% tried to bride blocks quickly (Scaffold)'
    8: 'matrix notify %player% tried to bride blocks quickly (Scaffold) #2'
    12: 'matrix kick %player% Scaffold/Tower'
`

To have this FP more often I reduces the violations counter. Same think happens less often but if the user realy wants to he will get kicked again xD.
I can't reproduce it like he does. I am to slow xD.
The same thing for planting all crops.

**Comment by jiangdashao** [comment]
set `scaffold.modules.scaffold.vl_weights.simple` to `-1`
