### ISSUE TITLE
[REQUEST] detect disablers?

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1465]
**What features/checks do you need?:**
Basically some clients have disablers which teleports the player into the void which triggers mc's anticheat which doesnt fire playermoveevent, can you listen for movement packets that have a destination into the void and check if the player is far from the void and then flag that? Or something like that.

**Comment by rasputinea** [comment]
when someone is using a disabler console spams 
`[22:36:43 WARN]: Player moved too quickly! 0.0971126014016761,-999.0,0.5204815524301125`

**Comment by jiangdashao** [comment]
PacketFly
if you find some packet fly can bypass, then report
