### ISSUE TITLE
[REQUEST] Make a "MatrixPlus" plugin, support MySQL/MongoDB Log, and AutoBan | Premium Plugin?

### ISSUE THREAD

**Issue by jiangdashao** [jiangdashao/Matrix-Issues#1471]
**What features/checks do you need?:**

**Comment by jiangdashao** [comment]
idea:
make a Ban VL system, server owners can set "matrixplus banvl %player% 1" punish commands in checks.yml
Then you can custom the Ban VL and the VL reduction speed

**Comment by Hyronymos1337** [comment]
own ban command please

**Comment by Edude42** [comment]
A way to store violation levels for an extended period of time, could have a command or system to check the total number of violations within x date.

**Comment by Hyronymos1337** [comment]
Any news about it?

**Comment by orblazer** [comment]
An way for settings max velocity (exemple: for active velocity check in same time to have an double jump)

**Comment by jordanamr** [comment]
Any news about it ? :(

**Comment by gogorz** [comment]
> A way to store violations for an extended period of time, could have a command or system to check the total number of violations within x date.

with this, you could auto-ban people after they hit a specific violation count in a specified time (days?)

**Comment by ZakShearman** [comment]
NGL wouldn't mind messing around with this and adding things like InfluxDB support for practice if possible via the API.

**Comment by jiangdashao** [comment]
already in matrix
