### ISSUE TITLE
[FP] Hitbox

### ISSUE THREAD

**Issue by Hyronymos1337** [jiangdashao/Matrix-Issues#1476]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.8.9
**Verbose messages**:  https://privatebin.net/?356ef520f9c34ab5#9i21Pd8wixkY9ZgG36pjiyRPgKBBV4TaoXY9b7zjF5Uv
**How/when does this happen**:  -
**Video of false positive**:  https://youtu.be/PyhdBoa39pU
**Other information**:  -

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
Can you try setting` hitbox.trace_back_length` lagger?
