### ISSUE TITLE
Fly false-positive

### ISSUE THREAD

**Issue by lucianxd16** [jiangdashao/Matrix-Issues#1479]
Troubleshooting Information
Change - [ ] to - [X] to check the checkboxes below.

 [X] Matrix and ProtocolLib are up-to-date
 [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
 [X] The issue happens on default config.yml and checks.yml
 [X] I've tested if the issue happens on default config

Issue Information
Server version: 1.8.8
Verbose messages: https://pastebin.com/jESpYexM
How/when does this happen: This false-positive occurs when you step in a sugar cane that has a carpet at the top
Video of false positive:
Other information:

Configuration Files
Link to checks.yml file: default

**Comment by jiangdashao** [comment]
I can't reproduce it
