### ISSUE TITLE
[INCOMPATIBILITY] UltraCosmetics Blaze Morph

### ISSUE THREAD

**Issue by minus1over12** [jiangdashao/Matrix-Issues#1481]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.15.2
**Incompatible plugin**: [UltraCosmetics](https://www.spigotmc.org/resources/1-8-to-1-15-ultra-cosmetics-opensource-free.10905/)
**Verbose messages (or) console errors**: Failed Velocity Check. Component: vel.expect
**How/when does this happen**: Blaze Morph has a fly ability that is activated by sneaking. Using the fly triggers Matrix.
**Video of incompatibility**: https://youtu.be/mDB7teTJI9Y
**Other information**: If this is unfixable, let me know so I can disable the blaze morph.

## Configuration Files
**Link to checks.yml file**: https://bin.disroot.org/?8c4f21573625da6d#BFUARRpWPULRKMqANoDBdCwyMYpM4HPV1d64x97WoSgA

**Comment by jiangdashao** [comment]
Disable `Velocity` check
