### ISSUE TITLE
[BYPASS] Step

### ISSUE THREAD

**Issue by Pix-00** [jiangdashao/Matrix-Issues#1483]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper-122 (1.15.2)
**Hacked client**: WWE 3.0.4
**Link to hacked client**: https://wweclient.com/Download.php
**Cheat that bypassed**: Step
**Video of bypass**: https://youtu.be/7sDb2m3k19M
**Other information**: 

## Configuration Files
_[default]_

**Comment by jiangdashao** [comment]
Make sure you don't have bypass permission

**Comment by Pix-00** [comment]
Is an error caused by my permission plugin, sorry for that.
