### ISSUE TITLE
[REQUEST] Make enabled checks in a new file

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1485]
**What features/checks do you need?:**
Make enabled checks in a new file (enabledchecks.yml) so if you are uploading a new config to all servers on the network or using a cloud config feature, some checks stay off on some subservers.
Also making **/matrix gui --> toggle checks** save enabled checks (enabledchecks.yml) would be very nice

**Comment by jiangdashao** [comment]
no
