### ISSUE TITLE
[FP] Phase while sneaking on 1.12 client

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1489]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(17:51:04) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:137 ping:48 tps:20.0 component: phase.main
(17:51:04) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:139 ping:48 tps:20.0 component: phase.main
(17:51:05) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:141 ping:48 tps:20.0 component: phase.main
(17:51:05) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:143 ping:48 tps:20.0 component: phase.main
(17:51:06) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:145 ping:48 tps:20.0 component: phase.main
(17:51:06) player Phase | moved into block (block: cobblestone, move: 0.0,0.35,0.0, at: -14.652,51.35,-19.423, dist: 0.0, loop: false, async) (+2) | vl:147 ping:48 tps:20.0 component: phase.main
 
**How/when does this happen**: on 1.12 client when you sneak and jump under full block it will detect phase
**Video of false positive**: not needed
**Other information**: 1.12 client version

## Configuration Files
**Link to checks.yml file**: -

**Comment by rasputinea** [comment]
server version? also viaversion is buggy and if possible you should use native 1.8/1.15.2
