### ISSUE TITLE
[ERROR] Cmd execution

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1494]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Error(s) found in console**: https://hastebin.com/kagehodeti
**How/when does this happen**: matrix executes the command from checks.yml (flag triggered by the MatrixAPI.flag)
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Call it in the main thread
