### ISSUE TITLE
[REQUEST]  How about a Player Whitelist?

### ISSUE THREAD

**Issue by ArthurFrisk** [jiangdashao/Matrix-Issues#1496]
**What features/checks do you need?:**
Thanks a lot for this splendid plugin.
In our server, wo offer prime membership to those who paid.
and the big problem is, we give them fly command but if they do so they would be kicked by Matrix.
I wondered if it's ok for you to add such a feature (Maybe it has been exist but i am blind...）
Thanks!

**Comment by Tomatobird8** [comment]
You can give players with prime membership the matrix.bypass permission.

**Comment by ArthurFrisk** [comment]
Thanks a lot!&nbsp; &nbsp;:)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tomatobird8"<notifications@github.com&gt;; 
发送时间: 2020年3月8日(星期天) 晚上6:22
收件人: "jiangdashao/Matrix-Issues"<Matrix-Issues@noreply.github.com&gt;; 
抄送: "921963209"<921963209@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jiangdashao/Matrix-Issues] [REQUEST]  How about a Player Whitelist? (#1496)




You can give players with prime membership the matrix.bypass permission.

**Comment by jiangdashao** [comment]
Fly command is compatible with Matrix
