### ISSUE TITLE
[FP] placing torches underwater

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1497]
## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: if you are underwater and place a torch where your head is to breathe
**Video of false positive**: https://youtu.be/MSIW0YoPIHs
**Other information**: probably works with sugarcane/lanterns etc (all passable blocks)

**Comment by jiangdashao** [comment]
video private

**Comment by rasputinea** [comment]
@jiangdashao  Video is un-privated: https://youtu.be/MSIW0YoPIHs
