### ISSUE TITLE
[FP] fly levitation

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1498]
**Server version**: 1.15.2
**How/when does this happen**: when a player lags with levitation causing them to trigger fly.levitation check they get teleported back, which triggers fly.levitation again, creating a feedback loop
**Video of false positive**: https://youtu.be/Mn0tc8tPapM

**Comment by rasputinea** [comment]
make fly.levitation: move unexpected check not setback the player to fix this.

**Comment by jiangdashao** [comment]
The player should keep rising when he gets this effect
I can't reproduce it
