### ISSUE TITLE
[REQUEST] make matrix lag detection based on epoch time

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1499]
**What features/checks do you need?:**
instead of having another thread detect lag use the more reliable method of comparing system time - something like this: https://pastebin.com/ujHtFhbJ . when plugman reloads a plugin it calls system.gc() (yeah really stupid) which doesn't only freeze main thread - it freezes the entire jvm, thus making matrix create huge amounts of false flags due to the lag protection not detecting the lag.

**Comment by jiangdashao** [comment]
What?

**Comment by jiangdashao** [comment]
I did
