### ISSUE TITLE
Phase glitch Speed II from beacon on corner stairs 

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1500]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: 
**How/when does this happen**: 100%
**Video of false positive**: 
https://www.youtube.com/watch?v=mVEU_IiLd94&feature=youtu.be
**Other information**: 
Phase glitch

Players had Speed II from a nearby beacon.

Happens when stairs placed on path blocks, and you have a corner stair - this doesn't seem to work when you go up a stair, it has to be corner and setup as in the vid.

All players were able to recreate, and matrix flagged for Phase.

It would not let you walk up the block and constantly shove you back into the original block, constantly flagging you

**Comment by jiangdashao** [comment]
The server returned the wrong collision box model
