### ISSUE TITLE
Packet Spammer

### ISSUE THREAD

**Issue by WaterTheMelon** [jiangdashao/Matrix-Issues#1505]
Hacked clients can spam servers with packets and lag them.
maybe Matrix could come in with some built-in packet limiter?
while this isn't the best solution it would be an easy solution without
making the plugin that much more strain on the server.

**Comment by jiangdashao** [comment]
How lag server? send what packet?

**Comment by WaterTheMelon** [comment]
I'm not sure but Impact has a hack called Franky that will spam packets and I noticed when my friend turned it on the server would lag to the point where the server would stop responding or even crash.

**Comment by GhastD** [comment]
You need to follow the format though.

**Comment by jiangdashao** [comment]
After testing, I did not find that it can crash the server or make the server lag
