### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Sybsuper** [jiangdashao/Matrix-Issues#1509]
Everyone knows that when you jump on farmland it becomes dirt. This is no problem, but it becomes one if when you jumped on it you are ofcourse for 1/16 in the dirt block, because farmland is not a full block high. This gives a false positive.

Verbose Message:
`Sybsuper failed Phase check | moved into block (block: dirt, move: -0.023,-0.121,0.0, to:-2245.296,82.938,-543186, dist: 0.023, loop: false, async) (+2) | vl:2 tps:20.0 lp:28 component: phase.main`

I hope this false positive can be fixed, thank you.

**Comment by rasputinea** [comment]
version?

**Comment by Sybsuper** [comment]
Version: 4.5.3
