### ISSUE TITLE
[FP] Recode the inventory move component -> Too unstable

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1512]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**:
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 449] [Component: inv.move] | [Ping: 117] [LP: 35] [TPS: 19.52]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 450] [Component: inv.move] | [Ping: 117] [LP: 35] [TPS: 19.52]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 451] [Component: inv.move] | [Ping: 117] [LP: 35] [TPS: 19.52]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 452] [Component: inv.move] | [Ping: 117] [LP: 33] [TPS: 20.0]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 453] [Component: inv.move] | [Ping: 117] [LP: 33] [TPS: 20.0]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 454] [Component: inv.move] | [Ping: 117] [LP: 33] [TPS: 20.0]
> (21:33:27) GOODNIGHT failed Inventory check | [inventory move | simple | d: 0.281] (+1) | [VL: 455] [Component: inv.move] | [Ping: 117] [LP: 33] [TPS: 20.0]

**How/when does this happen**: This false positive happens quite randomly, but can usually be attributed to lag.
**Video of false positive**: None.
**Other information**: I have personally checked these players, and they were not cheating. Ever since I have been using Matrix, I have had random false positives with Inventory check and I have been unable to reproduce them reliably. I think you should recode the check using improved methods because every day you become a better coder!

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/GuwbZcqE

**Comment by jiangdashao** [comment]
This is a very simple check, no need to rewrite
I will try to add more conditional judgments to it
