### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by Hyronymos1337** [jiangdashao/Matrix-Issues#1521]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Verbose messages**: https://privatebin.net/?28e736590237607a#HAN6v5J2xPqbpv3SePiuxV7tDPQPT9jFoHCtP7spJe6A
**How/when does this happen**: 
**Video of false positive**: https://youtu.be/Qi5c4DjJ8L0
**Other information**: 

## Configuration Files
**Link to checks.yml file**: premium-minigames config

**Comment by jiangdashao** [comment]
WTF?
Are you sure he didn't cheat? I think he's using NoFall
