### ISSUE TITLE
[FP] Speed false positives when lag/timeout

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1522]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:45:25) player Speed | change direction in mid-air (dist: 1.904, angle:64.835, pre:0.256) (+5) | vl:5 ping:69 tps:19.93 component: speed.strafe
(17:45:25) player Speed | suspicious movement (move: 1.904, expect: 0.3665, tag: ea) (+20) | vl:25 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.904, predict: 0.259, friction: 0.6, ground:false, motY: 0.5, increase:0.026, preMove:0.233, motion: -1.779,0.5,0.681, attribute: 0.13, tag: pred) (+5) | vl:30 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.74, expect: 0.3665, tag: ea) (+20) | vl:50 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.74, predict: 0.261, friction: 0.6, ground:false, motY: 0.412, increase:0.026, preMove:0.235, motion: -1.619,0.412,0.639, attribute: 0.13, tag: pred) (+5) | vl:55 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.592, expect: 0.3665, tag: ea) (+20) | vl:75 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.592, predict: 0.264, friction: 0.6, ground:false, motY: 0.325, increase:0.026, preMove:0.238, motion: -1.474,0.325,0.601, attribute: 0.13, tag: pred) (+5) | vl:80 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.456, expect: 0.3665, tag: ea) (+20) | vl:100 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.456, predict: 0.266, friction: 0.6, ground:false, motY: 0.24, increase:0.026, preMove:0.24, motion: -1.341,0.24,0.567, attribute: 0.13, tag: pred) (+5) | vl:105 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.333, expect: 0.3665, tag: ea) (+20) | vl:125 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.333, predict: 0.268, friction: 0.6, ground:false, motY: 0.157, increase:0.026, preMove:0.242, motion: -1.221,0.157,0.535, attribute: 0.13, tag: pred) (+5) | vl:130 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.222, expect: 0.3665, tag: ea) (+20) | vl:150 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.222, predict: 0.27, friction: 0.6, ground:false, motY: 0.075, increase:0.026, preMove:0.244, motion: -1.112,0.075,0.507, attribute: 0.13, tag: pred) (+5) | vl:155 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.12, expect: 0.3665, tag: ea) (+20) | vl:175 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.12, predict: 0.272, friction: 0.6, ground:false, motY: 0.0, increase:0.026, preMove:0.246, motion: -1.012,0.0,0.481, attribute: 0.13, tag: pred) (+5) | vl:180 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 1.028, expect: 0.3665, tag: ea) (+20) | vl:200 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 1.028, predict: 0.299, friction: 0.6, ground:false, motY: -0.078, increase:0.052, preMove:0.247, motion: -0.921,-0.078,0.457, attribute: 0.13, tag: pred) (+5) | vl:205 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.945, expect: 0.3665, tag: ea) (+5) | vl:210 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.945, predict: 0.298, friction: 0.6, ground:false, motY: -0.155, increase:0.026, preMove:0.272, motion: -0.839,-0.155,0.435, attribute: 0.13, tag: pred) (+5) | vl:215 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.869, expect: 0.3665, tag: ea) (+5) | vl:220 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.869, predict: 0.297, friction: 0.6, ground:false, motY: -0.231, increase:0.026, preMove:0.271, motion: -0.763,-0.231,0.416, attribute: 0.13, tag: pred) (+5) | vl:225 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.803, expect: 0.3665, tag: ea) (+5) | vl:230 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.803, predict: 0.297, friction: 0.6, ground:false, motY: -0.304, increase:0.026, preMove:0.271, motion: -0.695,-0.304,0.404, attribute: 0.13, tag: pred) (+5) | vl:235 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.741, expect: 0.3665, tag: ea) (+5) | vl:240 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.741, predict: 0.296, friction: 0.6, ground:false, motY: -0.377, increase:0.026, preMove:0.27, motion: -0.632,-0.377,0.387, attribute: 0.13, tag: pred) (+5) | vl:245 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.685, expect: 0.3665, tag: ea) (+5) | vl:250 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.685, predict: 0.295, friction: 0.6, ground:false, motY: -0.447, increase:0.026, preMove:0.269, motion: -0.575,-0.447,0.372, attribute: 0.13, tag: pred) (+5) | vl:255 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.634, expect: 0.3665, tag: ea) (+5) | vl:260 ping:69 tps:19.93 component: speed.main
(17:45:25) player Speed | suspicious movement (move: 0.634, predict: 0.295, friction: 0.6, ground:false, motY: -0.22, increase:0.026, preMove:0.269, motion: -0.523,-0.22,0.358, attribute: 0.13, tag: pred) (+5) | vl:265 ping:69 tps:19.93 component: move.xz
(17:45:25) player Speed | suspicious movement (move: 0.635, expect: 0.6235, tag: c) (+10) | vl:275 ping:69 tps:19.93 component: speed.main
**How/when does this happen**: player reported that he got lagged, timeout and he got kicked for speed
**Video of false positive**: not needed
**Other information**: 1.8 client

## Configuration Files
**Link to checks.yml file**:

**Comment by DanielAlves123** [comment]
Players report many false positives when getting lagged/timeout.

**Comment by rasputinea** [comment]
69 ping and getting timed out? lol

**Comment by jiangdashao** [comment]
I won't fix your server's bug, because of your server's weird plugins and the wrong issue format

**Comment by DanielAlves123** [comment]
@jiangdashao what weird plugins and what wrong format?
