### ISSUE TITLE
[ERROR] Matrix crashing server

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1523]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Error(s) found in console**: https://gist.github.com/FrozenBeard/672ea8d748f07abd09601574e1d5bb8b
**How/when does this happen**: Millions of these error messages.
**Other information**:  Crashes the server.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by Kyrobi** [comment]
I think I'll add some stuff too. Mine isn't a crash but just locks up the server for a few minutes.

Error: https://pastebin.com/hMyeiSwu

![image](https://user-images.githubusercontent.com/20980266/77127671-65a20680-6a1b-11ea-9e9c-9d9508be6fa8.png)

![image](https://user-images.githubusercontent.com/20980266/77127681-6fc40500-6a1b-11ea-9f33-39e7bc94b1db.png)
