### ISSUE TITLE
[INCOMPATIBILITY] Being kicked from server when using packet sign gui

### ISSUE THREAD

**Issue by YellowZaki** [jiangdashao/Matrix-Issues#1527]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] The incompatible plugin is up-to-date
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ X] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.13.2 and BungeeCord
**Incompatible plugin**: Sign input by using packets (https://www.spigotmc.org/threads/signmenu-1-15-2-get-player-sign-input.249381/)
**Verbose messages (or) console errors**: none
**How/when does this happen**: Only happening with Bungeecord. When a player click on Done on the sign menu
**Video of incompatibility**: https://youtu.be/JsyUrxxMDDM
**Other information**: 
Without bungeecord, it works fine. With bungeecord, it happens.
When Matrix is not installed, it doesn't happen.
I've tried disabling all checks, incluid BadPackets.
![image](https://user-images.githubusercontent.com/13599841/77117236-e4a23980-6a31-11ea-901b-aabd35faad7c.png)

## Configuration Files
**Link to checks.yml file**: default

**Comment by rasputinea** [comment]
Could you try without matrix whilst on bungeecord and see if it still happens?

**Comment by YellowZaki** [comment]
Yes, 
matrix+bungeecord = issue
matrix+ no bungeecord = no issue

**Comment by jiangdashao** [comment]
Please show me your calling code, I don't think this is caused by Matrix.
I think you wrote something here that caused the packet to be sent
`.response((player, lines) -> {`

**Comment by YellowZaki** [comment]
I was disabling plugins one by one until I found Matrix was causing the issue.
On a fresh server, with just Matrix and the sign GUI, the issue is happening. As I said, it only happens with BungeeCord.

An example:
```
        SignMenuFactory.getSignMenuFactory()
                .newMenu(player, Lists.newArrayList("", "&1&l⬆", "Enter", "the price"))
                .response((player2, strings) -> {
                    if (!Methods.isLong(strings[0])) {
                        player.sendMessage(Messages.NOT_A_NUMBER.getMessage());
                    }
                    return true;
                }).open();
```

**Comment by jiangdashao** [comment]
Please do not perform any operation in response that will send a packet, because this is incorrect.
Your code should be changed to:
` SignMenuFactory.getSignMenuFactory()
                .newMenu(player, Lists.newArrayList("", "&1&l⬆", "Enter", "the price"))
                .response((player2, strings) -> {
                    if (!Methods.isLong(strings[0])) {
                       // send the message in next tick
                       Bukkit.getSchedular().runTask(()->{
                          player.sendMessage(Messages.NOT_A_NUMBER.getMessage());
                       }
                    }
                    return true;
                }).open();`
