### ISSUE TITLE
[INCOMPATIBILITY] Being kicked from server when using packet sign gui (Reopen)

### ISSUE THREAD

**Issue by YellowZaki** [jiangdashao/Matrix-Issues#1530]
Reopen of https://github.com/jiangdashao/Matrix-Issues/issues/1527

It is still happening although if I use the task. Even if there is nothing inside response, it happens.
I've called an exception inside response, so open() doesn't execute, and it doesn't happen. So the issue comes when open() is called.

**Comment by jiangdashao** [comment]
According to your video, the error occurred when the player clicked OK to edit the wooden sign, so I think the error occurred in response ()

**Comment by jiangdashao** [comment]
If you don't mind, show your complete code

**Comment by YellowZaki** [comment]
Yes, the issue must be on response.
But it only happens when Matrix is installed. No matrix = no issue.


This code also causes the issue:

```
        SignMenuFactory.getSignMenuFactory()
                .newMenu(player, Lists.newArrayList("", "&1&l⬆", "Enter", "the price"))
                .response((player2, strings) -> {
                    return true;
                }).open();
```

**Comment by jiangdashao** [comment]
I guess I found the reason:
![image](https://user-images.githubusercontent.com/21152113/77179828-fc49f280-6b03-11ea-958c-ed23b38f7ab2.png)
He sends a block change packet when receiving the sign edit packet
It should change to:
```
    private void listen() {
        ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this.plugin, PacketType.Play.Client.UPDATE_SIGN) {
            @Override
            public void onPacketReceiving(PacketEvent event) {
                Player player = event.getPlayer();

                Menu menu = inputReceivers.remove(player);

                if (menu == null) {
                    return;
                }
                event.setCancelled(true);

                boolean success = menu.response.test(player, event.getPacket().getStringArrays().read(0));

                if (!success && menu.opensOnFail()) {
                    Bukkit.getScheduler().runTaskLater(plugin, () -> menu.open(player), 2L);
                }
Bukkit.getSchedular().runTask(your plugin instance, () ->{
                player.sendBlockChange(menu.position.toLocation(player.getWorld()), Material.AIR.createBlockData());
}
            }
        });
    }
```

**Comment by jiangdashao** [comment]
This has nothing to do with Matrix, you cannot send packets while receiving them, otherwise, it will cause errors
