### ISSUE TITLE
[Improvement] Matrix Impacting Performance at high player count

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1531]
## Issue Information
**Server version**: Paper 1.12.2

**How/when does this happen**: Matrix usually even up until 90+ players. However, over 100 players, the PlayerMoveEvents seems to start causing some noticeable performance costs. Here are a few screenshot from my timings for instance. Timings shows that in areas over 100 players, the PacketPlayInPositionLook and the PacketPlayInPosition are causing high-performance usage.
![image](https://user-images.githubusercontent.com/34877092/77180420-45685b00-6aa0-11ea-8957-ae5bec77aa2c.png)
![image](https://user-images.githubusercontent.com/34877092/77180479-5b761b80-6aa0-11ea-9bd8-8127a218ec5f.png)
I have DM-ed you the full timings & spark profiler results.

**Suggestion**: 
I am suggesting just revising the code to see where we can save performance. If thats not possible, I suggest adding a feature where above certain player counts, we can start disabling some less-important checks for less commonly used hacks/cheats to save performance that way.

**Comment by DanielAlves123** [comment]
Working async would be good too.

**Comment by jiangdashao** [comment]
As far as I know, Matrix is able to maintain 19+ TPS on some servers with 170+ people online. I do n’t think Matrix has caused performance problems.

**Comment by DanielAlves123** [comment]
@jiangdashao how about cpu usage?
