### ISSUE TITLE
[FP] Legit-Kick Block Break

### ISSUE THREAD

**Issue by Web-44** [jiangdashao/Matrix-Issues#1533]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config
-> Some checks are disabled and i changed punishment commands

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: failed Block check | break block too fast (digs: 0/11, hardness: 1.5, block: stone) (+4) | vl:20 ping: 26 tps:20.0 lp:37 component: block.fastbreak.expect
**How/when does this happen**: Player breaking stone block with wooden pickaxe
**Video of false positive**: 
**Other information**: client version 1.8.9 labymod-3

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Don't use ViaBackward/ViaRewind, please use ProtocolSupport
