### ISSUE TITLE
[REQUEST] Freeze/alting

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1540]
**What features/checks do you need?:** When you freeze in air, for example when you are in windowed mode, and you hold your window with mouse like you would want to move whole window with minecraft, your game will freeze. When you are in the air and you freeze it will give you unfair advantage. For example when you fall to and freeze till antilogout end it will cause suicide not kill by player. AntiFreeze would be good idea. Keep up the good work. :)

**Comment by jiangdashao** [comment]
Matrix doesn't actually do anything while listening to this event（set allow-flight to false in server.properties）

**Comment by DanielAlves123** [comment]
@jiangdashao oh sorry I fogot to add this. On 1.8 this built-in anti-cheat doesn't kick players. They send packets even when freezing.

**Comment by DanielAlves123** [comment]
@jiangdashao
