### ISSUE TITLE
[ERROR] Console exception spam

### ISSUE THREAD

**Issue by XXHunter796** [jiangdashao/Matrix-Issues#1541]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Error(s) found in console**: https://pastebin.com/Pk3azXD8
**How/when does this happen**: Randomly on player move
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/ZizZUz32
**Link to config.yml file**: https://pastebin.com/3dKzjYvR

**Comment by jiangdashao** [comment]
delete your checks.yml
