### ISSUE TITLE
[REQUEST] more qol features to matrix notify

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#1543]
**What features/checks do you need?:**
1) Pls make it possilbe to turn off notifications ex. /matrix togglenotify
2) Make it possible to add executable command to notify in chat (json-chat mc feature)
ex. 
executable_notify: 'tp %player%' in config.yml
then hover click notify in chat and command from config will be executed (admin teleported to player who failed some checks)

**Comment by jiangdashao** [comment]
2, no
