### ISSUE TITLE
[BYPASS] WWE Killaura

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#1544]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server

## Issue Information
**Server version**: 1.12.2
**Hacked client**: WWE latest
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: Killaura, settings on vid
**Video of bypass**: https://streamable.com/gfsab
**Other information**: no

## Configuration Files
**Link to checks.yml file**: no
**Link to config.yml file**: no

**Comment by jiangdashao** [comment]
Can't be detected, too few features
