### ISSUE TITLE
[FP] fly

### ISSUE THREAD

**Issue by sergservis** [jiangdashao/Matrix-Issues#1551]
I jump on the half block and it brings me back
https://streamable.com/hy076
Test spigot 1.8.8
The problem occurred in the last update matrix 4.6.2
Configurations I use standard

**Comment by rasputinea** [comment]
make sure you are on the latest version and turn on verbose messages in the video please

**Comment by sergservis** [comment]
I edited the first post. That's all I know

**Comment by Manicraft1001** [comment]
There's no way that anybody can help you fixing this issue, unless you provide some data.
Please provide the developers some data, for example by turning notification on (Command: /matrix verbose).
If you dont have the neccesairy permission, ask an administration for fixing it.

**Comment by jiangdashao** [comment]
You didn't provide the verbose messages

**Comment by sergservis** [comment]
(13:57:58) Dim4ik ошибка Fly проверка | ground spoof (expect: +-, move: 0.0,-0.078,-0.069, at: 39.478,27.922,107.646, type: air) (+5) | vl:15 ping:0 tps:20.0 компонент: fly.gf
