### ISSUE TITLE
[FP] ka.pt

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1552]
## Issue Information
**Server version**: matrix test server
**Verbose messages**: suspicious pitch movement T4
**How/when does this happen**: attack someone with optifine zoom
**Video of false positive**: https://youtu.be/4VLgYYSPfe4

**Comment by jiangdashao** [comment]
1. There is no way to fix it I guess
2. Who will attack others with optfine zoom?

**Comment by rasputinea** [comment]
@jiangdashao  https://github.com/funkemunky/Fiona-Anticheat/blob/master/Fiona/src/cc/funkemunky/fiona/data/MovementParser.java#L99  most anticheats with aim assist checks take optifine zoom into consideration. https://youtu.be/mxMYfLLIlOk?t=87
