### ISSUE TITLE
[FP] KillAura false positive when lags

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1553]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(19:07:46) player Speed | suspicious movement (move: 0.668, expect: 0.6235, tag: c) (+10) | vl:10 ping:37 tps:20.0 component: speed.main
(19:07:46) player Speed | suspicious movement (move: 0.385, expect: 0.3665, tag: ea) (+5) | vl:15 ping:37 tps:20.0 component: speed.main
(19:07:46) player Speed | suspicious movement (move: 0.376, expect: 0.3665, tag: ea) (+5) | vl:20 ping:37 tps:20.0 component: speed.main
(19:07:46) player Speed | suspicious movement (move: 0.367, expect: 0.3665, tag: ea) (+5) | vl:25 ping:37 tps:20.0 component: speed.main
(19:07:46) player KillAura | post attack: 0 (+1) | vl:11 ping:37 tps:20.0 component: ka.post
(19:07:47) player BadPackets | (timer) send 45 moving packets in 1438ms | tag: limit (+10) | vl:10 ping:37 tps:20.0 component: net.timer
(19:07:47) player KillAura | post attack: 1 (+1) | vl:12 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | post attack: 0 (+1) | vl:13 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | post attack: 0 (+1) | vl:14 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | post attack: 1 (+1) | vl:15 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:35 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | post attack: 0 (+1) | vl:36 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:56 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | post attack: 0 (+1) | vl:57 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | post attack: 0 (+1) | vl:58 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:78 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | post attack: 0 (+1) | vl:79 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:99 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | post attack: 0 (+1) | vl:100 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:120 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | post attack: 0 (+1) | vl:121 ping:37 tps:20.0 component: ka.post
(19:07:47) player KillAura | super knock back | action (+20) | vl:141 ping:37 tps:20.0 component: ka.action
(19:07:47) player KillAura | super knock back | action (+20) | vl:161 ping:37 tps:20.0 component: ka.action
(19:07:47) player Speed | suspicious movement (move: 2.19, expect: 0.3665, tag: ea) (+20) | vl:20 ping:37 tps:20.0 component: speed.main
(19:07:47) player Speed | suspicious movement (move: 2.19, predict: 0.265, friction: 0.6, ground:false, motY: -1.145, increase:0.026, preMove:0.239, motion: -1.791,-1.145,-1.26, attribute: 0.13, tag: pred) (+5) | vl:25 ping:37 tps:20.0 component: move.xz
(19:07:47) player Fly | suspicious movement:-1.145 predict:-0.078 lm:0.083 hard_pred:0.003 sev_pred:0.083 air_t:5 fall_t:1 g:-- tag:gn (+5) | vl:5 ping:37 tps:20.0 component: fly.main
 
**How/when does this happen**: player got lagged and got mass false positives from killaura.
**Video of false positive**: https://www.youtube.com/watch?v=-yGZwITEWhc
**Other information**: 1.8 client, maybe add a little delay between adding points?

## Configuration Files
**Link to checks.yml file**:-

**Comment by jiangdashao** [comment]
disable it

**Comment by DanielAlves123** [comment]
@jiangdashao why?

**Comment by rasputinea** [comment]
@DanielAlves123 please... stop posting random vls with no video or consistent way to replicate something.
