### ISSUE TITLE
[REQUEST] Web Interface Compatability

### ISSUE THREAD

**Issue by 09Turry** [jiangdashao/Matrix-Issues#1555]
**What features/checks do you need?:**
Allow Matrix to store the people that got banned,kicked,warned and muted on my MC server and the staff member who punished him, the date of punishment and the expiry of the punishment. LitBans has done this and also a website called Desteria(https://desteria.com/community/bans/) has done this. Please add this. If possible, you could make it work along side with PunishmentGUI.

**Comment by jiangdashao** [comment]
what? Matrix is an anti-cheat, not a punishment plugin

**Comment by 09Turry** [comment]
I know that, I want it to log its kicks, bans, mutes and warns on a website by also adding itself under the staff section. check desteria, where it says console, i would love to let it show Matrix.
