### ISSUE TITLE
[FP] Fly&Speed Kick (Sometimes)

### ISSUE THREAD

**Issue by Web-44** [jiangdashao/Matrix-Issues#1557]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [  ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Spigot
**Verbose messages**: failed Speed check | suspicious movement (move: 51.696, predict: 0.026, friction: 0.6, ground:false, motY: -101.0, increase:0.026, preMove:0.0, motion: -51.5,-101.0,-4.5, attribute: 0.13, tag: pred) (+5) | vl:250 ping:35 tps:20.0 lp:6 component: move.xz
**How/when does this happen**: Jumping slime jumps: https://cdn.anticraft.de/data/webbiii/kqlijpy2xDEBiZDB.png
Sometimes Speed flags (up to kicks) when jumping on soulsand with momentum
**Video of false positive**: If flagging it happens right above the last slime: https://youtu.be/cCUzY_KPVDg
**Other information**:
Client: LabyMod-3 1.8.9
Server does **not** use ViaVersion or any similar plugin
We were'nt able to fully reproduce this (only happens at a 5-10% rate)

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I noticed the data of "move: 51", which means that your certain movement speed is 51blocks / s, which is very abnormal.
And the video you recorded does not have verbose message enabled, which is an invalid video.
Please record a video to reproduce the false positives and turn on verbose message
