### ISSUE TITLE
[FP] Fly false possitive

### ISSUE THREAD

**Issue by FallenEmo** [jiangdashao/Matrix-Issues#1559]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: Every time, I had to disable
**Video of false positive**: https://imgur.com/a/xWuQlKF
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default Checks

**Comment by jiangdashao** [comment]
Please provide enough information or I cannot fix
