### ISSUE TITLE
RFChairs Incompatibility

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#156]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgokbLwA9qoUOGw6rwQ

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**RFChairs Version**: Latest
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
I will try to reduce the false flags
