### ISSUE TITLE
[FP] Scaffold

### ISSUE THREAD

**Issue by FallenEmo** [jiangdashao/Matrix-Issues#1561]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: Some of my players do experience this when they jump especially on blocks with snow on them 
**How/when does this happen**: Usually when someone have auto jump
**Video of false positive**:  https://imgur.com/a/80gfm92
**Other information**: none

## Configuration Files
**Link to checks.yml file**: Default Checks.yml

**Comment by jiangdashao** [comment]
please provide verbose messages

**Comment by FallenEmo** [comment]
I have no clue how to do that

**Comment by FallenEmo** [comment]
https://imgur.com/a/oQRnzFW

**Comment by FallenEmo** [comment]
https://imgur.com/a/oQRnzFW

**Comment by FallenEmo** [comment]
https://imgur.com/a/oQRnzFW Sorry for spamming but I got 3 of them

**Comment by jiangdashao** [comment]
You can disable scaffold simple module in checks.yml, it is a packet order check, so it might cause false flag when the player is lag

**Comment by FallenEmo** [comment]
So I guess is gonna be fine with fly and those kind of things
