### ISSUE TITLE
[FP] Fly fp and dealing damage

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1563]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(18:37:21) player Fly | ground spoof (expect: --, move: 0.202,-0.152,0.155, at: -6.274,53.024,-27.102, type: air) (+5) | vl:5 ping:0 tps:20.0 component: fly.gf
(18:37:21) player Fly | suspicious movement:-0.302 predict:-0.228 lm:-0.152 hard_pred:-0.228 sev_pred:-0.377 air_t:1 fall_t:3 g:-- tag:gn (+5) | vl:10 ping:0 tps:20.0 component: fly.main 
**How/when does this happen**: jump off or something while sprinting
**Video of false positive**: -
**Other information**: nofall damage is off, it still deals damage

## Configuration Files
**Link to checks.yml file**:-
  # NoFall check
  nofall:
    # Force deal damage after setback?
    damage: false

**Comment by jiangdashao** [comment]
If you do it again, I will ban u

**Comment by DanielAlves123** [comment]
@jiangdashao what are you talking about?
