### ISSUE TITLE
[FP] Speed on Beds

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#1564]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**:  In Video
**How/when does this happen**: Jumping and running on beds that are on ice.
**Video of false positive**:  http://matrix.zakshearman.com/vids/4.7.0-false-flag-speed-beds.mp4
**Other information**: Using the premium config on the test server.

## Configuration Files
**Link to checks.yml file**: Freshly reset after 4.7.0, default.

**Comment by jiangdashao** [comment]
not important
