### ISSUE TITLE
[REQUEST] api expansion

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1566]
**What features/checks do you need?:**
Could you add *API.exempt(Player player,Hacktype hacktype,int timeinmilliseconds)* to the matrix api? I was surprised something like this doesn't already exist for plugins that may be setting off false matrix flags by launching the player etc. I am making super jump boots that set off velocity flags in matrix if I go straight up so if I could do *API.exempt(Player,Hacktype.VELOCITY,300)* that would be very useful.

**Comment by jiangdashao** [comment]
I will add it, both API and commands
