### ISSUE TITLE
False flag when a other plugin teleport a player back to old location

### ISSUE THREAD

**Issue by Marv15** [jiangdashao/Matrix-Issues#1567]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: matrix notify Denn12 tried to move faster than usual (Speed) #2
**How/when does this happen**: In this countdown, the player should wait until the round finally starts. For this he is teleported to his spawn point and should stand here until it starts. For this reason, I leave the player there to teleport to their original position when they move. But if the player runs forward as shown in the video, he is flagged by the AC
**Video of false positive**: https://www.youtube.com/watch?v=V_bwRiKkoE4&feature=youtu.be
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://hastebin.com/ulehimuhag.bash

**Comment by jiangdashao** [comment]
How you block the player's movement?

**Comment by Marv15** [comment]
PlayerMoveEvent

player.teleport(event.getFrom);

**Comment by jiangdashao** [comment]
Use event.setTo(event.getFrom());
Don't use teleport in PlayerMoveEvent

**Comment by Marv15** [comment]
Thank you
