### ISSUE TITLE
[REQUEST] API New features

### ISSUE THREAD

**Issue by DamsDev1** [jiangdashao/Matrix-Issues#1573]
**What features/checks do you need?:**
I propose to add some features to the API if possible. 
The first would be an EventHandler, this EventHandler would be triggered when there is a player violation.
The second would be a function that gets the hack type.
The last would be a function that cancels the violation (and could be put in the EventHandler).

**Comment by Manicraft1001** [comment]
Before posting a request, consider reading the docs first. There is already a Feature like this implemented. What you need, is the  "PlayerViolationEvent". Import it and now you can access Hacktype, Player and even some details over the event. You can also cancel it or do some other actions over the api. Have a look at "Developer API" here: https://www.mc-market.org/resources/13999/

**Comment by DamsDev1** [comment]
> Before posting a request, consider reading the docs first. There is already a Feature like this implemented. What you need, is the "PlayerViolationEvent". Import it and now you can access Hacktype, Player and even some details over the event. You can also cancel it or do some other actions over the api. Have a look at "Developer API" here: https://www.mc-market.org/resources/13999/

Sorry, I only looked at the "MatrixAPI" part, sorry for this useless request. Thank you very much and have a nice evening or a nice day ^^
