### ISSUE TITLE
[FP] Vape KillAura

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1578]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Hacked client**: Vape
**Link to hacked client**: https://www.vape.gg/
**Cheat that bypassed**: Kill Aura
**Video of bypass**: Don't exactly have it. The player was SUPER fishy and we strongly suspected he was cheating. Matrix was being set off by him regularly, but the VL level never went too high. But how we ultimately caught the cheater was that they exposed themselves in a stream. I linked you the video in DMs.
**Other information**: Matrix was only barely detecting the KillAura. Here is the verbose logs:
https://pastebin.com/KYCzG88n
## Configuration Files
**Link to checks.yml file**: (Not important)
**Link to config.yml file**: (Premium Checks enabled)

**Comment by jiangdashao** [comment]
I don't have idea to detect it
