### ISSUE TITLE
[FP] Mounting Llamas in 1.12.2 Paper "You canmt enter this vehicle!"

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1579]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
1.12.2 Paper
**How/when does this happen**:  Every time someone trys to mount a Llama.

![2020-04-04_20 36 29](https://user-images.githubusercontent.com/144046/78458803-16f79c00-76ac-11ea-93c2-62b0033572d5.png)

**Comment by jiangdashao** [comment]
you can remove it in checks.yml

**Comment by FrozenBeard** [comment]
Why the hell is that a default...
