### ISSUE TITLE
[REQUEST] Selective Ghostmode

### ISSUE THREAD

**Issue by Nextopi** [jiangdashao/Matrix-Issues#1580]
**What features/checks do you need?:**

I would like to have a way to set ghostmode to certain checks

I have tried to disable some movement setback and cancel_vl with -1 but it doesnt work, it seems to always setback or cancel the violation no matter what is set in the config,  I want matrix to always alert me when someone is violating certain checks, but never setback or cancel and i also never get the notifications.

Ghost mode works great for that, but since it disables everything, it lets players and hackers bypass other checks and I wish i could just set this per check.

**Comment by jiangdashao** [comment]
No

**Comment by Nextopi** [comment]
So is there a way to properly disable setbacks and cancel for flight/movement checks? because is not disabling them at all when setting to -1
