### ISSUE TITLE
[FP] net.crash

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1583]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: see vid
**How/when does this happen**: flying up with elytra
**Video of false positive**: https://youtu.be/puwY03g1UZo
**Other information**: Happens on vanilla client too, it's not LB's fault

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
😁what is your location? (x,y,z)
I dont think it is a false positive

**Comment by Maxsimuss** [comment]
around 0 4 0

**Comment by jiangdashao** [comment]
what plugins do you installed? and did you tried to reinstall optfine?

**Comment by Maxsimuss** [comment]
yep, this is caused by optifine (wtf). Can it still be fixed? I will try reinstalling optifine.

**Comment by jiangdashao** [comment]
It can't pass this check:
![image](https://user-images.githubusercontent.com/21152113/78651063-60d1c380-78f2-11ea-9ac4-7aa9d03b3244.png)
Normal clients should not fail this check, please reinstall the latest version of Optfine

**Comment by Maxsimuss** [comment]
was fixed in optifine 1.14.4, thanks for help!
