### ISSUE TITLE
[ERROR] Console spam

### ISSUE THREAD

**Issue by twincake** [jiangdashao/Matrix-Issues#1588]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper-155 (1.15.2-R0.1)
**Error(s) found in console**: https://pastebin.com/Zbv6MJUa
**How/when does this happen**: I'm not sure what caused it but my console was spammed with error messages.
**Other information**:

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Update your Matrix to hotfix version
