### ISSUE TITLE
[FP] Onehit and timer

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1589]
Issue Information
**Server version**: 1.15.2
**Verbose messages**:
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:4 - ka.one.10
(11:17:42) Player: BadPackets - (timer) timer modify: 32.258 var:31 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:10 - net.timer
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:8 - ka.one.10
(11:17:42) Player: BadPackets - (timer) timer modify: 166.667 var:6 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:20 - net.timer
(11:17:42) Player: BadPackets - (timer) timer modify: 9.223372036854776E15 var:0 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:30 - net.timer
(11:17:42) Player: BadPackets - (timer) timer modify: 9.223372036854776E15 var:0 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:40 - net.timer
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 3) (+4) - p:43 t:19.9 lp:49 vl:12 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:16 - ka.one.10
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 4) (+4) - p:43 t:19.9 lp:49 vl:20 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:24 - ka.one.10
(11:17:42) Player: BadPackets - (timer) timer modify: 1000.0 var:1 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:50 - net.timer
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 5) (+4) - p:43 t:19.9 lp:49 vl:28 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:32 - ka.one.10
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 6) (+4) - p:43 t:19.9 lp:49 vl:36 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:40 - ka.one.10
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 7) (+4) - p:43 t:19.9 lp:49 vl:44 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:48 - ka.one.10
(11:17:42) Execute command: coc Player if -ping-<170&-tps->19.0 do kick Player Cheating
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 8) (+4) - p:43 t:19.9 lp:49 vl:52 - ka.one.1
(11:17:42) Player: KillAura - (onehit) attack in an abnormal state (pattern: #10) (+4) - p:43 t:19.9 lp:49 vl:56 - ka.one.10
(11:17:42) Player: BadPackets - (timer) timer modify: 9.223372036854776E15 var:0 buffer:20 | tag: timer (+10) - p:43 t:19.9 lp:49 vl:60 - net.timer
(11:17:42) Player: KillAura - (clickaimbot) click aim bot (d: 0.0, 103.47) (+5) - p:43 t:19.9 lp:49 vl:61 - ka.ckm 
**How/when does this happen**: when a player has an internet spike
**Other information**: timer check also kicks players who have internet hicups and then send all movement packets etc at once.

**Comment by jiangdashao** [comment]
onehit#10 is a super knockback check, it should only work for 1.8, I will disable it for other version

**Comment by jiangdashao** [comment]
And you can disable the packet order check in the checks.yml
