### ISSUE TITLE
Turning off NPC Visibility is not working

### ISSUE THREAD

**Issue by Waterman1001** [jiangdashao/Matrix-Issues#1590]
I try to set "NPC Visibility: false" in "checks.yml" but these strange NPC's when hitting players are still visible from time to time.
This did not happen to me before, but now suddenly it is the case. It started since the latest update of Matrix.
Server information:

Matrix version: 4.7.2-hotfix_release
Server version: Paper Spigot-1.14
Checks.yml looks like this:
...
    npc:
      async: true
      real_entity_id: true
      only_command_trigger: true
      visible: false
...

So it should be fine.
I did restart the server multiple times.

Thank you in advance for a fix!
I really appreciate it :)

**Comment by jiangdashao** [comment]
your checks.yml is oudated
