### ISSUE TITLE
[REQUEST] make aimassist check work on mobs

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1592]
**What features/checks do you need?:**
Hello there is a mobarena on my server which creates a heavy urge for some players to use aimassist on mobs, killaura is detected pretty well but aim assist checks only work on players. It would be cool if they worked on living entities thanks.

**Comment by jiangdashao** [comment]
what? AimAssist is working for all living entities, if not working, I don't have any idea. most aim assist can't be detected

**Comment by rasputinea** [comment]
@jiangdashao https://youtu.be/w3tTnnjeHIA

**Comment by jiangdashao** [comment]
ok, I will make ka.aim check work for mobs

**Comment by rasputinea** [comment]
Thank you
