### ISSUE TITLE
[REQUEST] add matrix notify event

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1594]
**What features/checks do you need?:**
matrix notify event. Would be a useful addition to developer api.
Methods:
setcancelled()
iscancelled()
getmessage() String
gethacktype() enum hacktype
getplayer() player
getviewers() set<Player>
setmessage() void
setviewers() void

**Comment by jiangdashao** [comment]
notify is a message, how can you get hack type?

**Comment by rasputinea** [comment]
True

**Comment by SkyLicks** [comment]
How is this different from PlayerViolationEvent?
