### ISSUE TITLE
Enchant Riptide

### ISSUE THREAD

**Issue by Ymies** [jiangdashao/Matrix-Issues#16]
## How you trigger the false positive?
When using enchant, Riptide goes back in place.

## Verbose Message:
<! -- Provide the verbose message here -->

## Videos:
https://youtu.be/5C9U81eGHPs?t=170 (from minute 2:50) 

## Server Infomation
**Matrix Version**: 1.1.6
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Provide verbose message, pls

**Comment by Ymies** [comment]
Ymies failed BadPackets check ; send 27 moving packets per second [23] (+0) ; vl:0 ping 56 tps: 19:98

**Comment by jiangdashao** [comment]
what enchant it is?
