### ISSUE TITLE
[FP] Speed after eating

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#1605]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In Video
**How/when does this happen**: After you eat, if you run it flags nearly 100% of the time.
**Video of false positive**: https://youtu.be/sVSfZg-04nU
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/C4GGLctd

**Comment by jiangdashao** [comment]
It's a client desync bug, I don't have any idea how to fix it
