### ISSUE TITLE
[FP] Killaura & hitbox false positives 

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#1606]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In Video
**How/when does this happen**: Running at and through a player (I believe only when you can't actually hit them and they, therefore, aren't knocked back. Not completely sure on this though). You only have to hit twice to start it triggering, more to keep on flagging.
**Video of false positive**: https://youtu.be/S3xAeaL8KVU / https://youtu.be/432H00B2Zrg
**Other information**: As a note, yes, I have seen this whilst not trying to purposefully trigger it during pvp at our warzone.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/QWG7bS8Y

**Comment by jiangdashao** [comment]
I can't reproduce the false positive, what's your client version?

**Comment by ZakShearman** [comment]
Client was 1.8.9 Forge, server is 1.12.2 Paper

**Comment by jiangdashao** [comment]
What mod did you install？

**Comment by ZakShearman** [comment]
ToggleSneak (I only use ToggleSpring tho), everything else client side. Orange's 1.7 animations, reach display mod, cps mod, sidebar mod (removes numbers on the scoreboard), Optifine.

Screenshot of folder: https://zak.pink/2020/04/Timely-Monarch-6409.png

**Comment by jiangdashao** [comment]
creative mode?

**Comment by ZakShearman** [comment]
Yes.

**Comment by ZakShearman** [comment]
Just tested, also happens in survival

**Comment by jiangdashao** [comment]
I still can't reproduce

**Comment by ZakShearman** [comment]
I can send another video that I just recorded https://zak.pink/2020/04/2020-04-13_11-30-02.mp4

**Comment by jiangdashao** [comment]
Why you move so fast?

**Comment by ZakShearman** [comment]
Speed effect
