### ISSUE TITLE
[FP] fly.levitation

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1607]
## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: when a player moves invalidly once due to lag/elytra with levitation effect they get teleported back by matrix when they flag fly.levitation, this teleport causes another fly.leviation flag and it loops until player is kicked
**Video of false positive**: https://youtu.be/Mn0tc8tPapM
**Other information**: Disable setback for fly.levitation (move unexpected)

**Comment by jiangdashao** [comment]
private video

**Comment by rasputinea** [comment]
unprivated

**Comment by jiangdashao** [comment]
I can't reproduce
