### ISSUE TITLE
[FP] Fast break when breaking glass.

### ISSUE THREAD

**Issue by Elguerrero11** [jiangdashao/Matrix-Issues#1613]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.15.2
**Verbose messages**: 
**How/when does this happen**: When the player break glass are a false positive of fast break.
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/pxT7s1jR

**Comment by jiangdashao** [comment]
Please record a video and show me the verbose messages (/matrix verbose)

**Comment by Elguerrero11** [comment]
[matrix_log_2020-04-14.txt](https://github.com/jiangdashao/Matrix-Issues/files/4476722/matrix_log_2020-04-14.txt)
Here is one log, maybe can help, i cant record a video with my pc.

**Comment by jiangdashao** [comment]
Because you break the glass without digging, maybe you installed some incompatible plugin

**Comment by Elguerrero11** [comment]
Is a gamemode of tnt, maybe is by that?

**Comment by jiangdashao** [comment]
maybe

**Comment by Elguerrero11** [comment]
Then what can i do?
Maybe change the checker in the checks or?

**Comment by jiangdashao** [comment]
Make your plugin compatible with Matrix or disable fastbreak check in the checks.yml

**Comment by Elguerrero11** [comment]
Ok, thanks.
