### ISSUE TITLE
[REQUEST] Freecam block place/break check

### ISSUE THREAD

**Issue by gogorz** [jiangdashao/Matrix-Issues#1614]
**What features/checks do you need?:**
Using LiquidBounce or other clients, you can place blocks behind walls with freecam. This gives a really unfair advantage over other players.

I would want to have Matrix check if a player can actually place blocks where they are.

**Comment by jiangdashao** [comment]
No

**Comment by gogorz** [comment]
why tf do you say "No" to everything? I know that making an anticheat is hard and can be sometimes overwhelming, but seriously, please provide a reason why to not add features.
