### ISSUE TITLE
[FP] hb.mis

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1615]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**Verbose messages**: see vid
**How/when does this happen**: see vid
**Video of false positive**: https://youtu.be/5DAZVrOXinA
**Other information**: Ignore ka.aim flags

## Configuration Files
**Link to checks.yml file**:

**Comment by rasputinea** [comment]
this cant really be fixed unless re tracks previous entity positions or looks if player has moved head alot recently

**Comment by rasputinea** [comment]
to be honest tracing back entities would be alot better

**Comment by jiangdashao** [comment]
not tracing back
it needs to wait for a tick to check because the client sends the attack packet before the moving(aiming) packet

**Comment by jiangdashao** [comment]
It need not be fixed
