### ISSUE TITLE
[FP] Velocity Expect

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#1621]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 paper-183
**Verbose messages**: In the video
**How/when does this happen**: general combat
**Video of false positive**: https://www.youtube.com/watch?v=je8mWh2rW-s
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default, except kick commands removed

**Comment by Maxsimuss** [comment]
when i tested it falsed only when jumping

**Comment by Kuraky** [comment]
That seems likely, I haven't noticed it happening when neither of the players were jumping.

**Comment by jiangdashao** [comment]
Disable #3 pattern, I have no idea how to fix it right now
