### ISSUE TITLE
[BYPASS] Velocity

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1629]
Issue Information
**Server version**: 1.15.2
**Hacked client**: sigma
**Cheat that bypassed**: velocity
**Video of bypass**: https://youtu.be/ULn579NPFcE
**Other information**: Right now matrix has really good combat checks but velocity sticks out as being not as good compared to the others. If velocity was improved that would be great

**Comment by jiangdashao** [comment]
Some Velocity modes are difficult to check because they reduce the speed of movement in the air, which requires predicting movement to check them. As far as I know, other anti-cheat anti-knockback checks are also bad(Except AAC4)

**Comment by jiangdashao** [comment]
No idea to patch it, maybe future™
