### ISSUE TITLE
Dolphin Grace False Positive [Jesus]

### ISSUE THREAD

**Issue by Minkizz** [jiangdashao/Matrix-Issues#163]
I was swimming in the ocean, swum next to a dolphin, got dolphins grace and got banned for Jesus/WaterSpeed/WaterFly hacks...

**Comment by jiangdashao** [comment]
1. Please use our issue template
2. Please provide video evidence

**Comment by ignPerformance** [comment]
I can reproduce this, but not consistently @jiangdashao https://1drv.ms/v/s!ApY4tKsF8vPUgotQq_G_yskqNyZ93w
