### ISSUE TITLE
[INCOMPATIBILITY] False positives at setFlightSpeed() edits

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#1632]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] The incompatible plugin is up-to-date <N/A>
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2

**Incompatible plugin**: Any plugin that modifies flight speed using Player#setFlightSpeed() while the player is flying.

**Verbose messages (or) console errors**: Verbose shows fly.cre HOWEVER even if fly.cre is disabled in the Matrix config you still get warped back (EVEN WITH GHOST MODE)

**How/when does this happen**: Whenever you are flying and a plugin modifies your flight speed using Player#setFlightSpeed you are warped back + fly.cre false positives.

**Video of incompatibility**: (No verbose shows up because fly.cre is disabled but I am still warped back)
https://youtu.be/sSgjm9j4Xug

**Comment by jiangdashao** [comment]
Please provide the verbose messages, EssentialsX's "/speed" command use `setFlySpeed()` too, but it works well
