### ISSUE TITLE
[FP] packet.skin

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1634]
## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: spam changing a skin customization option (if you have a layered skin)
**Video of false positive**: https://youtu.be/yNk84w9Cl2U
**Other information**: Change this check to instead see if a player has sprinted sneaked or sent interact/dig packets right after changing a skin option (look packet might not work because player sends this when they get teleported)

**Comment by jiangdashao** [comment]
I don't think it's important

**Comment by rasputinea** [comment]
@jiangdashao the only reason i know about this is because players of my server found it and told lots of people to do it and they were all getting kicked over and over lol
