### ISSUE TITLE
[BYPASS] Instant FastUse

### ISSUE THREAD

**Issue by nimm2User** [jiangdashao/Matrix-Issues#1637]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce (but it does bypass in every client)
**Link to hacked client**: https://liquidbounce.net/download
**Cheat that bypassed**: InstantUse/Instant FastUse
**Video of bypass**: it is self-explanatory
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
It can be detected, just can not be canceled, you can set cancel_vl to 1 or 2

**Comment by nimm2User** [comment]
Its already on 1.
