### ISSUE TITLE
[FP] Speed detection error when passing through the end gate

### ISSUE THREAD

**Issue by s-yh-china** [jiangdashao/Matrix-Issues#1638]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-paper-165(MC: 1.15.2)
**Verbose messages**: Spend
**How/when does this happen**: 在通过末地传送门后玩家被认为速度过快,并被拉回原位置导致掉落虚空死亡 
**Video of false positive**:  false
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default config.yml and checks.yml

**Comment by jiangdashao** [comment]
请不要从侧面进入末地门，需要从末地门方块上面跳下去
