### ISSUE TITLE
[FP] Fly False Flag

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#1639]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 paper-211
**Verbose messages**: In the video
**How/when does this happen**: Turning off essentials /fly or switching from creative to survival while in the air
**Video of false positive**: https://www.youtube.com/watch?v=l7XXMeMoYJs
**Other information**: Seems to be a bit inconsistent, although from my testing it mostly happens while you don't move your head at all for a while after turning off flight

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
Not important actually, but I will try to reduce the false flags
