### ISSUE TITLE
[ERROR] PlayerTeleportEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by x1p** [jiangdashao/Matrix-Issues#1643]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Purpur version git-Purpur-569 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (=Fork of Paper) 
**Error(s) found in console**: https://pastebin.com/yeXRfm9Y
**How/when does this happen**: When player hits badpackets check
**Other information**: Repetitive error

## Configuration Files
**Link to checks.yml file**: Can't due to the terms of premium
**Link to config.yml file**: https://pastebin.com/g3Jn3wJ1

**Comment by mlegok12** [comment]
I Also have this problem at Tuinity 1.15.2 (fork of paper)
27.04 15:31:10 [Server] ERROR [Matrix] Unhandled exception occured in onPacketReceiving(PacketEvent) for Matrix
27.04 15:31:10 [Server] INFO java.lang.IllegalStateException: PlayerTeleportEvent may only be triggered synchronously.
27.04 15:31:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:769) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:503) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at me.rerere.matrix.iIiIiIIiii.a(Unknown Source) ~[?:?]
27.04 15:31:10 [Server] INFO at me.rerere.matrix.iIiIiIIiii.iIiiiiiIII(Unknown Source) ~[?:?]
27.04 15:31:10 [Server] INFO at me.rerere.matrix.IIIIiiiiII.onPacketReceiving(Unknown Source) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) ~[?:?]
27.04 15:31:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Tuinity-"037f5ca"]
27.04 15:31:10 [Server] INFO at protocolsupport.protocol.packet.PacketDataCodec.read0(PacketDataCodec.java:129) ~[?:?]
27.04 15:31:10 [Server] INFO at protocolsupport.protocol.packet.PacketDataCodec$ServerBoundPacketDataProcessor.read(PacketDataCodec.java:206) ~[?:?]
27.04 15:31:10 [Server] INFO at protocolsupport.protocol.packet.PacketDataCodec$ServerBoundPacketDataProcessor.process(PacketDataCodec.java:215) ~[?:?]
27.04 15:31:10 [Server] INFO at protocolsupport.protocol.packet.PacketDataCodec.read(PacketDataCodec.java:83) ~[?:?]
