### ISSUE TITLE
Add permission for base /matrix command [Feature Request]

### ISSUE THREAD

**Issue by Justin42** [jiangdashao/Matrix-Issues#165]
# What features/checks do you need?

Add a permission for the base '/matrix' command to prevent users from retrieving version information or determining which anti-cheat is being used. 

Preventing exposure of this information to cheaters further decreases their ability to enable or develop a bypass. This increases overall security and adds extra flexibility to the command permissions.

**Comment by jiangdashao** [comment]
Added
