### ISSUE TITLE
[FP] Velocity False Positive

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1650]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Verbose messages**: visible in the video
**How/when does this happen**: when you jump in the moment you would get velocity you get a push velocity (without cheats)
**Video of false positive**: https://www.youtube.com/watch?v=dQcZ8VIQepI
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
1. Can you test it in a real server? This false positive is not important
2. Velocity check is bad currently, I am planning to recode it, but not now
