### ISSUE TITLE
[BYPASS] Reverse Velocity

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1651]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Hacked client**: LiquidBounce
**Link to hacked client**: http://liquidbounce.net
**Cheat that bypassed**: SmoothReverse Velocity
**Video of bypass**: https://www.youtube.com/watch?v=OuXDUfTkQI0
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Can't detect

**Comment by WentilatorWentox** [comment]
What??? Why don't you get speed flags for that?
