### ISSUE TITLE
[BYPASS] Sprint without enough food

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1652]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Hacked client**: LiquidBounce b72
**Link to hacked client**: http://liquidbounce.net
**Cheat that bypassed**: Sprint without enough food
**Video of bypass**: https://www.youtube.com/watch?v=Q1UwQTsHGyU
**Other information**: you can sprint without food (normally you cant sprint anymore when you are under 3,5 food bars)

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
I won't add this check
