### ISSUE TITLE
[FP] Tower False Positive

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1653]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Verbose messages**: visible in the video
**How/when does this happen**: when you run and build yourself up in the same time
**Video of false positive**: https://www.youtube.com/watch?v=qLuSJm0zm-4
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default

**Comment by NathanKassab** [comment]
fastplace and sprint are hacks and not false positives

**Comment by WentilatorWentox** [comment]
Yes, but Sprint is legit possible and FastPlace is for assuming much cps :) So in BedWars when legits build this on a bridge they are flagged
