### ISSUE TITLE
[FP] Scaffold False Positive

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1654]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Verbose messages**: visible in the video
**How/when does this happen**: when you're breezily bridging
**Video of false positive**: https://www.youtube.com/watch?v=nRbAYYeQhRI
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default

**Comment by NathanKassab** [comment]
your using liquidbounce with sprint and fastplace on, this is not a false positive

**Comment by WentilatorWentox** [comment]
> your using liquidbounce with sprint and fastplace on, this is not a false positive and looking at is again your cursor is not even reaching the side of the block. your place a block before your even looking at the side of it

Im not using Backwards Sprint and FastPlace is just for assuming much cps. It is a false positive because breezily bridging is legit possible. and idk what you mean with "your place a block before your even looking at the side of it" its without build hacks (except FastPlace for assuming much cps)

**Comment by WentilatorWentox** [comment]
the same problem is described in #1649
