### ISSUE TITLE
[FP] Scaffold setback

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#1655]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 Latest Paper Build (227)

If you are not directly in the center of a scaffold and hold space, you will be setback.

**Comment by jiangdashao** [comment]
You didn't provide enough information (video and verbose message)
