### ISSUE TITLE
[FP] interact.trough

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1656]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: see vid
**How/when does this happen**: see vid
**Video of false positive**: https://youtu.be/2dhyRgZPRRU
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I can't fix it currently, Minecraft send interact packet before the moving packet(aiming)

**Comment by Maxsimuss** [comment]
Set some temp variable when interact packet arrives, and check for that variable when moving packets arrive, if the variable is set, then execute the check. This works fine for me
