### ISSUE TITLE
[FP] Elytra

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1659]
**Server version**: 1.15.2
**Verbose messages**: 
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.137 t: 986 (+2) - p:85 t:20.0 lp:7 vl:2 - ely.re
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.137 t: 987 (+2) - p:85 t:20.0 lp:7 vl:4 - ely.re
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.132 t: 988 (+2) - p:85 t:20.0 lp:7 vl:6 - ely.re
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.128 t: 989 (+2) - p:85 t:20.0 lp:7 vl:8 - ely.re
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.127 t: 990 (+2) - p:85 t:20.0 lp:7 vl:10 - ely.re
(16:53:21) player1: Elytra - (elytra) reserve energy: 1.402 dif: 0.0 motion: 0.127 t: 991 (+2) - p:85 t:20.0 lp:7 vl:12 - ely.re
(16:53:27) player1: Elytra - (elytra) reserve energy: 0.639 dif: 0.461 motion: 0.098 t: 1093 (+2) - p:85 t:19.73 lp:6 vl:2 - ely.re
(16:53:27) player1: Elytra - (elytra) reserve energy: 0.964 dif: 0.325 motion: 0.021 t: 1094 (+2) - p:85 t:19.73 lp:6 vl:4 - ely.re
(16:53:27) player1: Elytra - (elytra) more energy: 1.127 dif: 0.163 motion: -0.217 ratio: 0.75 (+1) - p:85 t:19.73 lp:6 vl:5 - ely.me
(16:53:48) player1: Elytra - (elytra) reserve energy: 1.179 dif: 0.126 motion: 0.396 t: 173 (+2) - p:101 t:18.87 lp:7 vl:7 - ely.re
(16:53:48) player1: Elytra - (elytra) reserve energy: 1.266 dif: 0.086 motion: 0.293 t: 174 (+2) - p:101 t:18.87 lp:7 vl:9 - ely.re
(16:53:48) player1: Elytra - (elytra) reserve energy: 1.315 dif: 0.049 motion: 0.244 t: 175 (+2) - p:101 t:18.87 lp:7 vl:11 - ely.re
(16:54:00) player2: Elytra - (elytra) reserve energy: 0.819 dif: 0.139 motion: 0.066 t: 293 (+2) - p:86 t:20.0 lp:3 vl:2 - ely.re
(16:54:00) player2: Elytra - (elytra) more energy: 0.994 dif: 0.175 motion: 0.0 ratio: 421.374 (+3) - p:86 t:20.0 lp:3 vl:5 - ely.me
(16:54:00) player2: Elytra - (elytra) more energy: 1.085 dif: 0.09 motion: -0.08 ratio: 1.124 (+3) - p:86 t:20.0 lp:3 vl:8 - ely.me
(16:54:00) player2: Elytra - (elytra) more energy: 1.142 dif: 0.057 motion: -0.188 ratio: 0.305 (+1) - p:86 t:20.0 lp:3 vl:9 - ely.me
(16:54:00) player2: Elytra - (elytra) more energy: 1.205 dif: 0.063 motion: -0.295 ratio: 0.213 (+1) - p:86 t:20.0 lp:3 vl:10 - ely.me
(16:54:00) player2: Elytra - (elytra) more energy: 1.277 dif: 0.071 motion: -0.39 ratio: 0.183 (+1) - p:86 t:20.0 lp:3 vl:11 - ely.me
(16:54:00) player2: Elytra - (elytra) more energy: 1.351 dif: 0.074 motion: -0.458 ratio: 0.162 (+1) - p:86 t:20.0 lp:3 vl:12 - ely.me
(16:54:01) player2: Elytra - (elytra) reserve energy: 1.36 dif: 0.001 motion: 0.319 t: 315 (+2) - p:86 t:20.0 lp:3 vl:14 - ely.re
(16:54:01) player2: Elytra - (elytra) reserve energy: 1.361 dif: 0.0 motion: 0.336 t: 316 (+2) - p:86 t:20.0 lp:3 vl:16 - ely.re
(16:54:01) player2: Elytra - (elytra) reserve energy: 1.284 dif: 0.027 motion: 0.366 t: 320 (+2) - p:86 t:20.0 lp:3 vl:18 - ely.re
(16:54:01) player2: Elytra - (elytra) reserve energy: 0.766 dif: 0.422 motion: 0.311 t: 322 (+2) - p:86 t:19.85 lp:3 vl:20 - ely.re
**How/when does this happen**:  When a player is lagging/server is lagging using an elytra
**Other information**: elytra check at the moment seems too unstable for players with shakey connections. Having to change elytra kick vl to 100 just so that people arent false kicked is quite annoying.

**Comment by jiangdashao** [comment]
It accelerates when gliding upwards, how is this done?
