### ISSUE TITLE
[REQUEST] FastUse Check is not working with every food

### ISSUE THREAD

**Issue by WentilatorWentox** [jiangdashao/Matrix-Issues#1660]
**What features/checks do you need?:**
FastUse Check is not working with:
Baked Potato, Potato, Carrot, Melon, Raw Rabbit, Cooked Rabbit, Rabbit Stew, Rotten Flesh, Pumpkin Pie and Poisonous Potato

Tested with Matrix 4.7.9 on a Spigot 1.8.9 Server
(Default checks and config)

**Comment by jiangdashao** [comment]
I guess BadPackets can detect it

**Comment by WentilatorWentox** [comment]
Yeah but only one timer flag and not always

**Comment by jiangdashao** [comment]
I will recode it

**Comment by WentilatorWentox** [comment]
ok thanks
