### ISSUE TITLE
[FP] reach

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1662]
**Server version**: 1.15.2
**Verbose messages**: attack player too far away 3/11 positions lag: 8 distance: 5.418 blocks +13
**How/when does this happen**: When a player attacks another player as/right after they are being hit with a high kb weapon
**Video of false positive**: https://youtu.be/mnHu6hFIEFQ

**Comment by gogorz** [comment]
Not sure but I'd say this is related to lag; the player hits another player 2 times when the knockback didn't "register" yet.

**Comment by jiangdashao** [comment]
try increasing trace_back_length?
