### ISSUE TITLE
[FP] badpackets

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1667]
**Server version**: 1.15.2
**How/when does this happen**: when a player toggles on and off their skins features
**Video of false positive**: https://youtu.be/DfD2viVLbBY
**Other information**: Player discovered that this gets you kicked so told everyone to do it and they all got kicked

**Comment by jiangdashao** [comment]
The purpose of designing this check is to prevent frequent skin switching, if you do n’t like it, you can disable it
