### ISSUE TITLE
Lilypad on Ice False Positive [Fly]

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#167]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgotsI76cffzfl6zL8w

## Server Infomation
**Matrix Version**: 1.8.4
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
If the stuck player doesn't jump, BadPackets gets a lot of violations very fast. ~200 VL in 15 seconds.

**Comment by jiangdashao** [comment]
1. FastFall false positives when fixed in the next update
2. bad packets check need to be recode
