### ISSUE TITLE
[FP] Fastbreak Issue

### ISSUE THREAD

**Issue by masterhacka** [jiangdashao/Matrix-Issues#1674]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 (Paper)
**Verbose messages**: https://i.imgur.com/AgemnIR.png
**How/when does this happen**: Breaking blocks with Client version 1.7.X-1.8.X
**Video of false positive**: https://youtu.be/DSGPO121w48
**Other information**: Plugins on server: Essentials, LuckPerms, Matrix, ProtocolLib, ViaBackwards, ViaRewind, ViaVersion - all of them newest version

## Configuration Files
**Link to checks.yml file**: I just generated complete clean Matrix folder

**Comment by jiangdashao** [comment]
Matrix does not support ViaBackwards/ViaRewind, because it delays the arm animation packet
