### ISSUE TITLE
[INCOMPATIBILITY] GeyserMC

### ISSUE THREAD

**Issue by DontStarve72** [jiangdashao/Matrix-Issues#1675]
## Troubleshooting Information
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:
git-Tuinity-"e00a4e3" (PaperMC: 248) (MC: 1.15.2)
**Incompatible plugin**: 
GeyserMC with Floodgate
**Verbose messages (or) console errors**: 
`[Matrix] *DontStarve72 failed Block check | break block with timer (block: grass_block, point: 619) (+4) | vl:20 ping:0 tps:20.0 lp:0 component: block.fb.timer`
No errors are thrown.
**How/when does this happen**:
Bedrock players are never ignored by Matrix.
**Video of incompatibility**: 
[Youtube Link](https://youtu.be/HwTxSIlNWLA)
**Other information**: 

## Configuration Files
Happens on default configuration.

**Comment by jiangdashao** [comment]
You should install GeyserMC on bukkit side

**Comment by DontStarve72** [comment]
It is installed on the bukkit side
