### ISSUE TITLE
[FP] Scaffold (breezily, sideways bridging)

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#1676]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://gist.github.com/4a292f2ae47976fe8e4fcfe8d6329d80
**How/when does this happen**: 
1. When walking backwords and moving side to side while placing blocks under you, scaffold moon walk gets triggered. I suck at doing it, so I just spam left and right movement keys while holding backwards and it triggers.
2. When walking sideways on the edge of a bridge placing blocks on the edge, scaffold moon walk triggers.

**Video of false positive**: 

1. https://streamable.com/frn802
2. https://streamable.com/yowig6

**Other information**: ~~Related issue: https://github.com/jiangdashao/Matrix-Issues/issues/1654~~

## Configuration Files
**Link to checks.yml file**: default minigames

**Comment by rasputinea** [comment]
issue #1654 isn't really related since the person in the video is using auto clicker and sprint but false number 2 is definitely important

**Comment by WentilatorWentox** [comment]
Sprint does not change this as it is not a backwards sprint. FastPlace is legit just as possible, only I cannot mouseabuse.
