### ISSUE TITLE
[BYPASS] Fly / Glide

### ISSUE THREAD

**Issue by nimm2User** [jiangdashao/Matrix-Issues#1681]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8
**Hacked client**: LiquidBounce
**Link to hacked client**: http://liquidbounce.net
**Cheat that bypassed**: Vanilla Fly / MineSecure Glide
**Video of bypass**: https://youtu.be/DE6C6-wKBo4
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
it's a bug, jump on slime block will cause that
