### ISSUE TITLE
[FP] Swimming up in water while outside of border

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#1682]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(15:50:14) player Fly | suspicious movement:0.005 predict:-0.097 air:12 tag:dmf (+10) | vl:20 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.024 predict:-0.074 air:12 tag:dmf (+10) | vl:30 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.04 predict:-0.055 air:12 tag:dmf (+10) | vl:40 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.052 predict:-0.039 air:12 tag:dmf (+10) | vl:50 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.002 predict:-0.1 air:12 tag:dmf (+10) | vl:60 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.022 predict:-0.076 air:12 tag:dmf (+10) | vl:70 ping:14 tps:19.97 component: fly.main
(15:50:14) player Fly | suspicious movement:0.04 predict:-0.057 air:12 tag:dmf (+10) | vl:80 ping:14 tps:19.97 component: fly.main
(15:50:16) player Fly | suspicious movement:0.012 predict:-0.088 air:12 tag:dmf (+10) | vl:90 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.03 predict:-0.067 air:12 tag:dmf (+10) | vl:100 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.04 predict:-0.049 air:12 tag:dmf (+10) | vl:110 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.052 predict:-0.039 air:12 tag:dmf (+10) | vl:120 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.013 predict:-0.087 air:12 tag:dmf (+10) | vl:130 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.03 predict:-0.066 air:12 tag:dmf (+10) | vl:140 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.04 predict:-0.049 air:12 tag:dmf (+10) | vl:150 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.052 predict:-0.039 air:12 tag:dmf (+10) | vl:160 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.062 predict:-0.027 air:12 tag:dmf (+10) | vl:170 ping:14 tps:20.0 component: fly.main
(15:50:16) player Fly | suspicious movement:0.069 predict:-0.018 air:12 tag:dmf (+10) | vl:180 ping:14 tps:20.0 component: fly.main
(15:50:17) player Fly | suspicious movement:0.047 predict:-0.045 air:12 tag:dmf (+10) | vl:190 ping:14 tps:20.0 component: fly.main
(15:50:17) player Fly | suspicious movement:0.058 predict:-0.032 air:12 tag:dmf (+10) | vl:200 ping:14 tps:20.0 component: fly.main
**How/when does this happen**: when you are outside of world border and it hits you and you have water on the wall, when you swim up in the water and have half moder in water and half outside to breathe it will kick you for fly
**Video of false positive**: not needed
**Other information**: 1.8 version

## Configuration Files
**Link to checks.yml file**: default

**Comment by rasputinea** [comment]
@DanielAlves123 please post a video or your issue will not be accepted
