### ISSUE TITLE
Option to skip Block#getType in speed check if chunk is not loaded

### ISSUE THREAD

**Issue by AbstractCoderX** [jiangdashao/Matrix-Issues#1688]
![изображение](https://user-images.githubusercontent.com/38766980/81500011-f7214c80-92d7-11ea-8ae6-65e6bec4a7de.png)
Please add the option to disable this check in not loaded chunks. Badly needed for 1.15 servers.

**Comment by MatrixTunnel** [comment]
With Paper you can prevent players from moving into chunks that aren't loaded

**Comment by AbstractCoderX** [comment]
> 
> 
> With Paper you can prevent players from moving into chunks that aren't loaded
That option is already enabled.
