### ISSUE TITLE
[FP] Block NoSwing

### ISSUE THREAD

**Issue by gogorz** [jiangdashao/Matrix-Issues#1689]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8 with ViaVersion, client 1.15.2
**Verbose messages**: see video
**How/when does this happen**: usually when bridging.
**Video of false positive**: https://dogotz.s-ul.eu/jHjJXZk7 (https://streamable.com/u919fc if doesn't work)
**Other information**: happens on a 1.8 server with viaversion, usually when a player with a newer version joins.

## Configuration Files
**Link to checks.yml file**: default

**Comment by NikV2** [comment]
Matrix doesn't support ViaVersion due to ViaVersion changing the Arm Animation Timer.

Use ProtocolSupport
