### ISSUE TITLE
[FP] Phase - Fences & Walls

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#169]
## How you trigger the false positive?
Watch the linked video.

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgotwZ49LtQNY5FlTRQ

## Server Infomation
**Matrix Version**: 1.8.4
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Can't reproduce it, I already add fence types into white list

**Comment by ignPerformance** [comment]
Reproduced on tree.ac: https://1drv.ms/v/s!ApY4tKsF8vPUgox-J0oh1V0skvkLCQ
