### ISSUE TITLE
[FP] Jesus/WaterSpeed/Waterfly Hacks on 1.12.2 depth strider 3, speed 2 potion, 44 ping

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1694]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 Paper
**Verbose messages**: 
**How/when does this happen**: 100% when using depth strider 3, speed 2 potion in water
**Video of false positive**: POV https://www.youtube.com/watch?v=dpJBzaOZOGA&feature=youtu.be

And from another angle:
https://www.youtube.com/watch?v=3bLwh3JTd1o&feature=youtu.be

**Comment by jiangdashao** [comment]
verbose messages?

**Comment by Wentoxic** [comment]
https://ghostbin.co/paste/tjwm2
