### ISSUE TITLE
[PERFORMANCE] matrix chunk packet sending lag

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1695]
## Issue Information
**Server version**: 1.15.2
**Spark report**: https://imgur.com/a/M1b0dxc
**How/when does this happen**: When a chunk packet is sent?
**Other information**: this is one of the most demanding processes running on my server

**Comment by jiangdashao** [comment]
Because the data in this packet is too large, are you using WorldEdit?
