### ISSUE TITLE
PvP

### ISSUE THREAD

**Issue by Ymies** [jiangdashao/Matrix-Issues#17]
## How you trigger the false positive?
You have to run to jump and punch your hand in the air or in the player, then move back into place and sometimes crashes for Fly.

## Verbose Message:
<! -- Provide the verbose message here -->

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version**: 1.1.6
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
You should provide verbose message

**Comment by Ymies** [comment]
While running, jumping and hitting animals or destroying grass, it moves back and is spam:

Ymies is sending unusual packets to server (BadPackets) #1

Ymies failed Speed check | type E: a=3.1505660782911313 b=0.365 t=a (+5) | vl:47 ping:50 tps:20.0

Ymies failed BadPackets check | send too much moving packets (1.037) [653/30] (+10) | vl:124 ping:50 tps:20.0

Ymies failed Speed check | type E: a=2.692637777931622 b=0.365 t=a (+5) | vl:52 ping:50 tps:19.96

Ymies failed Fly check | t:e m=0.2247629905309907 tk=8 et=5 vy=-1.8244679497883562 (+4) | vl:8 ping:50 tps:19.96

**Comment by jiangdashao** [comment]
This issue was caused by **entity collision** (1.9+)

**Comment by Ymies** [comment]
will you fix it?

**Comment by jiangdashao** [comment]
maybe

**Comment by Ymies** [comment]
haha fine
