### ISSUE TITLE
[INCOMPATIBILITY] GadgetsMenu v4.3.38

### ISSUE THREAD

**Issue by twincake** [jiangdashao/Matrix-Issues#1701]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] The incompatible plugin is up-to-date
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Incompatible plugin**: GadgetsMenu v4.3.38 by yapzhenyie
**Verbose messages (or) console errors**:
**How/when does this happen**: Upon players using the "Discord Ball Gadget" in hub, the gadget makes any player inside the radius of the gadget jump repeatedly. Now if another player starts hitting them or they start hitting others (even if pvp is disabled), they begin to notify velocity checks and eventually get kicked. I'm sure there's other gadgets in the plugin too which causes velocity false positives.

**Comment by rasputinea** [comment]
Please include video.

**Comment by jiangdashao** [comment]
why you use Matrix in a hub server
