### ISSUE TITLE
[FP] ka.one.1

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1705]
**Server version**: 1.15.2
**Verbose messages**: 
(18:05:45) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 3) (+4) - p:53 t:19.58 lp:41 vl:4 - ka.one.1
(18:05:45) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 4) (+4) - p:53 t:19.58 lp:41 vl:8 - ka.one.1
(18:05:45) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 5) (+4) - p:53 t:19.58 lp:41 vl:12 - ka.one.1
(18:05:45) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 6) (+4) - p:53 t:19.58 lp:41 vl:16 - ka.one.1
(18:05:46) Player: HitBox - missed player hitbox (raytrace: 1/11 positions, lag: 8, prep: false) (+1) - p:53 t:20.0 lp:41 vl:1 - hb.mis
(18:05:46) Player: HitBox - missed player hitbox (raytrace: 1/11 positions, lag: 8, prep: false) (+1) - p:63 t:20.0 lp:41 vl:2 - hb.mis
(18:05:46) Player: BadPackets - (timer) send 43 moving packets in 1057ms | tag: limit (+5) - p:63 t:20.0 lp:41 vl:5 - net.timer
(18:05:46) Player: Speed - suspicious movement (move: 1.716, expect:1.1573, t:0, sprint: false, attr: 0.14, tag: a) (+4) - p:63 t:20.0 lp:41 vl:4 - speed.main
(18:05:49) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 7) (+2) - p:63 t:20.0 lp:41 vl:18 - ka.one.1
(18:05:49) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 8) (+2) - p:63 t:20.0 lp:41 vl:20 - ka.one.1
(18:05:49) Player: HitBox - missed player hitbox (raytrace: 10/11 positions, lag: 8, prep: true) (+1) - p:63 t:20.0 lp:41 vl:3 - hb.mis
(18:05:59) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 3) (+4) - p:48 t:20.0 lp:11 vl:24 - ka.one.1
(18:05:59) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 4) (+4) - p:48 t:20.0 lp:11 vl:28 - ka.one.1

**last 10 pings before kick (1 second between them) [49, 53, 152, 49, 55, 177, 53, 52, 52, 48, 227] matrix ping: 48**

(16:52:45) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 3) (+2) - p:65 t:20.0 lp:26 vl:2 - ka.one.1
(16:52:52) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 4) (+4) - p:54 t:20.0 lp:23 vl:6 - ka.one.1
(16:52:53) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 5) (+4) - p:54 t:20.0 lp:23 vl:10 - ka.one.1
(16:52:59) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 3) (+4) - p:61 t:20.0 lp:18 vl:14 - ka.one.1
(16:52:59) Player: HitBox - missed player hitbox (raytrace: 8/11 positions, lag: 7, prep: true) (+2) - p:61 t:20.0 lp:18 vl:2 - hb.mis
(16:53:01) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 4) (+4) - p:61 t:20.0 lp:22 vl:18 - ka.one.1
(16:53:01) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 5) (+4) - p:61 t:20.0 lp:22 vl:22 - ka.one.1
(16:53:02) Player: KillAura - (onehit) attack in an abnormal state (pattern: #01, val: 6) (+4) - p:61 t:20.0 lp:22 vl:26 - ka.one.1

***last 10 pings before kick (1 second between them) [90, 73, 50, 50, 46, 51, 49, 49, 355, 555, 45] matrix ping: 61**

**How/when does this happen**: When a player is lagging, matrix ping doesnt refresh enough to realize this. Listed above are the last 10 pings for each of the kicks (measured by my plugin every second)
**Video of false positive**: 
**Other information**: A: make matrix check latency more often (have an isLagging() flag like this? https://pastebin.com/PZya9DHe) B: make matrix check players latency when they flag this check (idk)

**Comment by Hyronymos1337** [comment]
I can confirm that ka.one.1 is falsing, same thing with ka.one.8

**Comment by jiangdashao** [comment]
it's packet order check, you can disable it
