### ISSUE TITLE
[BYPASS] NoWeb

### ISSUE THREAD

**Issue by Wentoxic** [jiangdashao/Matrix-Issues#1707]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8
**Hacked client**: LiquidBounce
**Link to hacked client**: 
**Cheat that bypassed**: NoWeb when the cobweb is only in the upper part of the player
**Video of bypass**: https://gyazo.com/f70ca2223d77f7a289ab38864cf5667d
**Other information**: -

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Yes, NoWeb check is not strict, but I think it is not important

**Comment by Wentoxic** [comment]
well ok
