### ISSUE TITLE
[FP] Velocity

### ISSUE THREAD

**Issue by Wentoxic** [jiangdashao/Matrix-Issues#1708]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.9
**Verbose messages**: visible in the video
**How/when does this happen**: when a player is hit in the cobweb and then knocked out
**Video of false positive**: https://www.youtube.com/watch?v=cAHYyN1gmk0
**Other information**: -

## Configuration Files
**Link to checks.yml file**: https://ghostbin.co/paste/bjwsf

**Comment by jiangdashao** [comment]
Please report useful bugs, instead of reporting any false positives.

**Comment by Wentoxic** [comment]
In SkyWars you have cobwebs to save yourself from falling down. If you fight and get knocked out and get velocity flags, I don't think it's that nice. But if you think it's completely unnecessary, it's your decision.
