### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CrazyWords1** [jiangdashao/Matrix-Issues#171]
## Console Error
https://pastebin.com/BbXvCn10

## When the error happens?
Sorry, but I don't know

# Server Infomation
**Server Version**: 1.12.2
**Matrix Version**: 1.8.4
**ProtocolLib Version**: 4.3.0
**Is you config files newest?**: yes

**Comment by jiangdashao** [comment]
Please use ProtocolLib 4.4.0
