### ISSUE TITLE
[ERROR + BUG] Players can take damages + Hit others

### ISSUE THREAD

**Issue by AymerickA** [jiangdashao/Matrix-Issues#1717]
## Troubleshooting Information
- [ ] Matrix and ProtocolLib are 4.8.4
- [ ] Matrix is running on a 1.8 server

## Issue Information
**Server version 1.8
**Error(s) found in console**: https://framabin.org/p/?673fb18a5ac918bc#YJ369Y9LFNI9BCqvr0QafYzR2Vvsewc61MS5REQDbhk=
**How/when does this happen**: When start the server
**Other information**: Players can hit others players and take damages

## Configuration Files
**Link to checks.yml file**: https://framabin.org/p/?eda5d5b257464150#hkcoVx0GGvXe8sJ+p1zRAG3QKMoAaeGQ4nzNJasJzCw=
**Link to config.yml file**: https://framabin.org/p/?416a4168a8b8db3d#yf8b4I4g9a8GUvpf1MNKrjWBLODI9bX7Ryd2x4ORThM=

**Comment by jiangdashao** [comment]
You gave almost useless information
