### ISSUE TITLE
[FP] vehicle flight

### ISSUE THREAD

**Issue by shionuma** [jiangdashao/Matrix-Issues#1718]
## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: boat on slime blocks powered by pistons. same thing happens with horses and pigs
**Video of false positive**: https://youtu.be/Xy6gVnwupaI

**Comment by jiangdashao** [comment]
Do you think someone will play like this on a real server?

**Comment by shionuma** [comment]
yes, thats why i reported it.

**Comment by Hyronymos1337** [comment]
It isn’t possible to get slime blocks in survival mode
