### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1719]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
TestServer
**lb*: 
**Link to hacked client**: 
**LongJumpo Speed**: 
**https://www.youtube.com/watch?v=MVabjwKT-IA&feature=youtu.be**: 
**Test Server**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Speed check is weaker on slime block/ice block, I don't think it's important
