### ISSUE TITLE
[FP] Velocity

### ISSUE THREAD

**Issue by variationtime** [jiangdashao/Matrix-Issues#1722]
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12 paper
**Verbose messages**: https://prnt.sc/spdzhg
**How/when does this happen**: move to 50 second of the video
**Video of false positive**: https://youtu.be/j3fPd9Po1ZU

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
I have no idea how it happens

**Comment by variationtime** [comment]
F
