### ISSUE TITLE
[BYPASS] NoSlow in water

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#1724]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Impact
**Cheat that bypassed**: NoSlow
**Video of bypass**: https://youtu.be/8lqlqEcHU_o

**Comment by jiangdashao** [comment]
This is not important, I won't patch it
