### ISSUE TITLE
[BYPASS] No Slow

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#1725]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Impact
**Cheat that bypassed**: NoSlow
**Video of bypass**: https://youtu.be/qqbTveuCWDM

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/83734167-35185300-a681-11ea-91aa-63491e4c31bc.png)
