### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1728]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**tree.ac**: 
**liquidbounce**: 
**Link to hacked client**: 
**step**: 
**https://www.youtube.com/watch?v=phMOTJzH7Rk**: 
**hi**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by dudeman123** [comment]
wow you bypassed step on ladders and enchant tables at 10% timer speed!!!

**Comment by jiangdashao** [comment]
In this case, there is almost no real server, and you use this extremely slow timer does not have any "step" meaning
