### ISSUE TITLE
[1.8.4] [Jesus / Bad Packets ]False Positives for Swimming 

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#173]
## How you trigger the false positive?
Requires poor connection, bad ping
1. Use 1.13.2 Client
2. Swim in water near a dolphin
3. The Bad Packets check will start, but the player will get flagged for Jesus as well, likely because the Anti Cheat is holding them still?

## Verbose Message:
Watch video , see verbose logs for "AnimalTheGamer"

## Videos:
https://clips.twitch.tv/SuaveCarelessMageCmonBruh

## Server Information
**Matrix Version**:  1.8.4
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Same as #174
