### ISSUE TITLE
[INCOMPATIBILITY] False kick with quality armoury vehicles

### ISSUE THREAD

**Issue by JoseLu1200** [jiangdashao/Matrix-Issues#1732]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 Paper
**Incompatible plugin**: Quality Armoury Vehicles
**Verbose messages (or) console errors**: Fly kick
**How/when does this happen**: When one person is gonna enter in one vehicle and vehicles hitboxes bugs and the player keep bugged in the air

**Video of incompatibility**:  https://mega.nz/file/hzABxCoS#Vkm3cqHLIHO92iHa5SagmajX0D-zon4yGdRUiFbbTMk

**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://mega.nz/file/43o1TKrQ#3T_P4xvz6w9NxIm6Q1fne0SZTtfk2bKJMRFt71knf-s

**Comment by jiangdashao** [comment]
what's your discord name?

**Comment by JoseLu1200** [comment]
> what's your discord name?

CODE JoseLu121#9347

**Comment by jiangdashao** [comment]
Are you premium user?

**Comment by JoseLu1200** [comment]
> Are you a premium user?

Yes

**Comment by jiangdashao** [comment]
You should join my discord server and get your username/password

**Comment by jiangdashao** [comment]
it's a paid plugin
