### ISSUE TITLE
[BYPASS] FastBreak

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#1733]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2 paper-317
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/download/
**Cheat that bypassed**: FastBreak
**Video of bypass**: https://www.youtube.com/watch?v=D0BdJXunbJA
**Other information**: Seems to only bypass when block breaking is instant. As shown on the video, when fastbreak caused block breaking to happen instantly, the cheat wouldn't be detected.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
It is because the expected number of digs is similar to the actual number of digs, It doesn't really matter
