### ISSUE TITLE
Fly WorldGuard - water bucket & entry deny

### ISSUE THREAD

**Issue by OlekMK342** [jiangdashao/Matrix-Issues#1737]
**Server version:** 1.15.2
**How/when does this happen:** 
- Using water bucket on World Guard region.
- Going to the region when on the region is entry deny.
**Video of false positive:** 
https://youtu.be/Tti7n1psAW0 - bucket
https://youtu.be/c3_OwPnLHdE - entry region
**Other information:** 
Rather everything was presented in the video and I don't have to add anything (for now)
but overall I'm happy with the plugin :)

**Comment by jiangdashao** [comment]
the bucket stuff is not a false positive, Matrix should prevent it

**Comment by jiangdashao** [comment]
2. Matrix will setback players if they try to enter the arena. If the player persists in and causes a false positive, I can’t do anything about it.
