### ISSUE TITLE
[FP] bridging activates scaffold check

### ISSUE THREAD

**Issue by Keyboardsheep** [jiangdashao/Matrix-Issues#1738]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 (Viaversion, Viarewind, Viabackwards)
**Verbose messages**: *Me* failed Scaffold check | scaffold | type: switch (+25) | vl:1295 ping:45 tps:19.91 lp:0 component: sfd.simple
**How/when does this happen**: Any time someone bridges
**Video of false positive**:  https://youtu.be/ztqdTqIWQfA
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/JH5UuCf8

**Comment by jiangdashao** [comment]
Don't use ViaRewind/ViaBackwards, matrix does NOT support it
