### ISSUE TITLE
[1.8.4] [BadPackets/Fly/Jesus/KillAura]  False Positives when rowing a boat and breaking boat and swimming in laggy conditions

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#174]
## How you trigger the false positive?
Requires poor connection, bad ping
1. Use 1.13.2 Client
2. Use a boat and row forward
4.  Break boat
5. Swim forward

Bad Packets Check seems to prevent users from entering a boat properly and Kill Aura flags when breaking boat

## Verbose Message:
Watch video , see verbose logs for "AnimalTheGamer"

## Videos:
https://clips.twitch.tv/AnimatedBombasticCheddarBleedPurple

## Server Information
**Matrix Version**:  1.8.4
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Why you are so lag?

**Comment by Kruize1** [comment]
The user has a bad computer or a bad connection to the server. This doesn't happen to everyone, but only him and maybe one other user.

**Comment by jiangdashao** [comment]
Check the next version
