### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by NathanKassab** [jiangdashao/Matrix-Issues#1741]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: fasteat
**Video of bypass**: https://www.youtube.com/watch?v=EO2lN2fAjOo&feature=youtu.be
**Other information**: the anticheat catches it if constantly eat gapples, but in a pvp scenario a player would only eat a gapple or 2 before going back to fight

## Configuration Files
**Link to checks.yml file**: https://www.mediafire.com/file/wwaqsqhbbsoc5rz/checks.yml/file
**Link to config.yml file**: https://www.mediafire.com/file/ccrwitkdt5v2c75/config.yml/file

**Comment by jiangdashao** [comment]
because the cancel_vl is low in default config, you can set it to `1`
![image](https://user-images.githubusercontent.com/21152113/84228763-6fb73b00-ab1a-11ea-8dd2-7ab646d699bd.png)
