### ISSUE TITLE
[REQUEST] levitation control

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#1745]
**What features/checks do you need?:**
cheat: impact 4.8.3
video (sorry for sound) - https://youtu.be/MA633AGlGYE

**Comment by respiter** [comment]
if they move when they have levitation they will be flagged, if they are standing still they could be lagging

**Comment by jiangdashao** [comment]
I don't think it's useful, I guess you will get more flag when you moving
