### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1746]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [4.8.4 Matrix] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(02:43:04) assasin541 Fly | ground spoof (expect: --, move: -0.02,-1.407,0.006, at: -151.843,72.684,89.506, type: air, pkt: false) (+5) | vl:5 ping:62 tps:19.99 component: fly.gf
-> i think this one dealt damage in the air (before hitting the ground!) (02:43:06) assasin541 Speed | suspicious movement (move: 0.152, predict: 0.115, friction: 0.6, ground:false, motY: 0.0, increase:0.026, preMove:0.089, motion: -0.145,0.0,0.043, attribute: 0.13, tag: pred) (+2) | vl:2 ping:62 tps:19.99 component: move.xz
(02:43:21) assasin541 Fly | ground spoof (expect: --, move: -0.048,-0.966,-0.016, at: -151.795,82.44,90.353, type: air, pkt: false) (+5) | vl:10 ping:47 tps:19.99 component: fly.gf
(02:43:22) assasin541 Fly | ground spoof (expect: --, move: -0.015,-1.407,0.023, at: -151.977,72.685,90.556, type: air, pkt: false) (+5) | vl:15 ping:47 tps:19.99 component: fly.gf
(02:43:31) assasin541 Fly | ground spoof (expect: --, move: -0.021,-1.407,0.0, at: -151.983,72.684,91.288, type: air, pkt: false) (+5) | vl:20 ping:47 tps:19.99 component: fly.gf
(02:47:04) assasin541 Fly | ground spoof (expect: --, move: -0.189,-0.966,-0.027, at: -152.818,82.44,89.604, type: air, pkt: false) (+5) | vl:5 ping:47 tps:19.99 component: fly.gf
(02:47:04) assasin541 Fly | suspicious movement:-1.083 predict:-1.025 lm:-0.966 hard_pred:-1.025 sev_pred:-1.139 air_t:1 fall_t:14 g:-- tag:gn (+5) | vl:10 ping:47 tps:19.99 component: fly.main

**How/when does this happen**: jump down and try to place water when you are near the ground
**Video of false positive**: 
1. damage before landing - https://share.getcloudapp.com/ApuA14ON
2. damage after placing water - https://share.getcloudapp.com/5zuXpxJK
**Other information**: 1.8/1.12/1.15 client version, changing nofall damage to false and skip rate to 0 doesn't help

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
can't reproduce

**Comment by assasin541** [comment]
@jiangdashao i will test this on 4.8.8.

**Comment by assasin541** [comment]
@jiangdashao still exists in 4.8.8. You get damaged above the ground.
