### ISSUE TITLE
[FP] fly.main

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1747]
**Server version**: 1.15.2
**Verbose messages**: 
Fly - suspicious movement:0.37 predict:-0.318 air:9 tag:dmf (+5) - p:237 t:20.0 lp:1 vl:5 - fly.main
Fly - suspicious movement:0.598 predict:-0.517 air:12 tag:dmf (+10) - p:87 t:20.0 lp:3 vl:10 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+10) - p:18 t:20.0 lp:3 vl:10 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+3) - p:399 t:20.0 lp:2 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+3) - p:670 t:20.0 lp:2 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+3) - p:554 t:20.0 lp:6 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+3) - p:524 t:20.0 lp:7 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:11 tag:dmf (+3) - p:360 t:20.0 lp:2 vl:3 - fly.main
Fly - suspicious movement:0.23 predict:-0.374 air:12 tag:dmf (+5) - p:112 t:20.0 lp:26 vl:5 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:11 tag:dmf (+3) - p:533 t:20.0 lp:3 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:6 tag:dmf (+3) - p:654 t:20.0 lp:2 vl:3 - fly.main
Fly - suspicious movement:0.039 predict:-0.53 air:12 tag:dmf (+10) - p:108 t:20.0 lp:1 vl:10 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+3) - p:537 t:20.0 lp:3 vl:3 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+10) - p:89 t:20.0 lp:3 vl:10 - fly.main
Fly - suspicious movement:0.389 predict:-0.377 air:12 tag:dmf (+5) - p:237 t:20.0 lp:1 vl:5 - fly.main
Fly - suspicious movement:0.078 predict:-0.155 air:12 tag:dmf (+10) - p:76 t:20.0 lp:11 vl:10 - fly.main
Fly - suspicious movement:0.264 predict:-0.638 air:12 tag:dmf (+10) - p:117 t:20.0 lp:4 vl:10 - fly.main
Fly - suspicious movement:0.435 predict:-0.287 air:12 tag:dmf (+9) - p:120 t:20.0 lp:1 vl:19 - fly.main
Fly - suspicious movement:0.371 predict:-0.209 air:12 tag:dmf (+10) - p:117 t:20.0 lp:2 vl:10 - fly.main
Fly - suspicious movement:0.264 predict:-0.638 air:12 tag:dmf (+5) - p:115 t:20.0 lp:27 vl:5 - fly.main
Fly - suspicious movement:0.588 predict:-0.562 air:12 tag:dmf (+10) - p:49 t:20.0 lp:8 vl:10 - fly.main
Fly - suspicious movement:0.418 predict:-0.278 air:8 tag:dmf (+10) - p:49 t:20.0 lp:13 vl:10 - fly.main
Fly - suspicious movement:0.196 predict:-0.351 air:9 tag:dmf (+10) - p:109 t:20.0 lp:2 vl:10 - fly.main
Fly - suspicious movement:0.418 predict:-0.278 air:8 tag:dmf (+10) - p:27 t:20.0 lp:7 vl:10 - fly.main
Fly - suspicious movement:0.196 predict:-0.351 air:9 tag:dmf (+10) - p:45 t:20.0 lp:13 vl:10 - fly.main
Fly - suspicious movement:0.025 predict:-0.639 air:12 tag:dmf (+10) - p:65 t:20.0 lp:2 vl:10 - fly.main
Fly - suspicious movement:0.267 predict:-0.436 air:12 tag:dmf (+10) - p:65 t:20.0 lp:2 vl:10 - fly.main
**How/when does this happen**: taking knockback sometimes
**Other information**: not that big of an issue but wouldnt cause much harm to fix

**Comment by jiangdashao** [comment]
tag:dmf is used to detect damage fly
