### ISSUE TITLE
[1.8.4] [Fly/Speed/Velocity] Horses are impossible to ride

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#175]
## How you trigger the false positive?
1. Use 1.13.2 Client
2. Disable Entity_Speed check
3. Attempt to ride any horse in the wild with a saddle (not spawn egg)
4. Attempt to move forward

## Verbose Message:
See video, impossible to ride horses. Verbose logs "kold_gaming_yt"

## Videos:
https://clips.twitch.tv/ShinyModernWaffleDuDudu

## Server Information
**Matrix Version**:  1.8.4
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by Jaspenton** [comment]
it happens to me aswell. I have noticed that it only happens on some horses when they gain or loose altitude (go up or down 1)
