### ISSUE TITLE
[FP] Fly & Speed

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1751]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**https://pastebin.com/hTQvuAJF**: 
**At the beggining of the round. It is just for some users**: 
**https://youtu.be/-g8IAYEKktA**: 
****: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Please provide the verbose messages
