### ISSUE TITLE
[FP] vehicle fly

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1752]
**Server version**: 1.15.2
**Verbose messages**: 
(23:21:46) Player: Vehicle - vehicle flight (mot: 0.115, entity:zombie_horse, t:20, js:0.786) (+2) - p:42 t:20.0 lp:3 vl:2 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.752, entity:zombie_horse, t:28, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:4 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.678, entity:zombie_horse, t:28, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:6 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.575, entity:zombie_horse, t:29, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:8 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.475, entity:zombie_horse, t:30, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:10 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.379, entity:zombie_horse, t:31, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:12 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.288, entity:zombie_horse, t:32, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:14 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.199, entity:zombie_horse, t:33, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:16 - veh.fly
(23:21:48) Player: Vehicle - vehicle flight (mot: 0.115, entity:zombie_horse, t:34, js:0.786) (+2) - p:38 t:20.0 lp:3 vl:18 - veh.fly
(23:21:49) Player: Vehicle - vehicle flight (mot: 0.752, entity:zombie_horse, t:42, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:20 - veh.fly
(23:21:49) Player: Vehicle - vehicle flight (mot: 0.678, entity:zombie_horse, t:42, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:22 - veh.fly
(23:21:49) Player: Vehicle - vehicle flight (mot: 0.575, entity:zombie_horse, t:43, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:24 - veh.fly
(23:21:49) Player: Vehicle - vehicle flight (mot: 0.475, entity:zombie_horse, t:44, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:26 - veh.fly
(23:21:50) Player: Vehicle - vehicle flight (mot: 0.379, entity:zombie_horse, t:45, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:28 - veh.fly
(23:21:50) Player: Vehicle - vehicle flight (mot: 0.288, entity:zombie_horse, t:46, js:0.786) (+2) - p:41 t:20.0 lp:3 vl:30 - veh.fly
**How/when does this happen**: zombie horse with jump attribute
**Other information**: same as #1734

**Comment by jiangdashao** [comment]
A horse with a jump strength of 0.786 can only jump up to 14 ticks, but you jumped 40+ ticks
