### ISSUE TITLE
[FP] Fly in water/lava

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1754]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.058,0.0, at: 65.242,59.279,66.263, type: air, pkt: false) (+5) | vl:5 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.055,0.0, at: 65.242,59.223,66.263, type: air, pkt: false) (+5) | vl:10 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.053,0.0, at: 65.242,59.17,66.263, type: air, pkt: false) (+5) | vl:15 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.052,0.0, at: 65.242,59.118,66.263, type: air, pkt: false) (+5) | vl:20 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.051,0.0, at: 65.242,59.066,66.263, type: air, pkt: false) (+5) | vl:25 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.051,0.0, at: 65.242,59.015,66.263, type: air, pkt: false) (+5) | vl:30 ping:36 tps:20.0 component: fly.gf
(01:23:52) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.051,0.0, at: 65.242,58.965,66.263, type: air, pkt: false) (+5) | vl:35 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.914,66.263, type: air, pkt: false) (+5) | vl:40 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.864,66.263, type: air, pkt: false) (+5) | vl:45 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.814,66.263, type: air, pkt: false) (+5) | vl:50 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.764,66.263, type: air, pkt: false) (+5) | vl:55 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.714,66.263, type: air, pkt: false) (+5) | vl:60 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.664,66.263, type: air, pkt: false) (+5) | vl:65 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.614,66.263, type: air, pkt: false) (+5) | vl:70 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.564,66.263, type: air, pkt: false) (+5) | vl:75 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.514,66.263, type: air, pkt: false) (+5) | vl:80 ping:36 tps:20.0 component: fly.gf
(01:23:53) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.464,66.263, type: air, pkt: false) (+5) | vl:85 ping:36 tps:20.0 component: fly.gf
(01:23:54) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.414,66.263, type: air, pkt: false) (+5) | vl:90 ping:36 tps:20.0 component: fly.gf
(01:23:54) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.364,66.263, type: air, pkt: false) (+5) | vl:95 ping:36 tps:20.0 component: fly.gf
(01:23:54) assasin541 Fly | ground spoof (expect: --, move: 0.0,-0.05,0.0, at: 65.242,58.314,66.263, type: air, pkt: false) (+5) | vl:100 ping:36 tps:20.0 component: fly.gf
**How/when does this happen**: login on 1.15, go in the water, it can be normal water, lava or water elevator, probably on 1.15 there is different swimming down speed
**Video of false positive**: https://share.getcloudapp.com/ApuAyBG5
**Other information**: 1.15 client, viaversion

## Configuration Files
**Link to checks.yml file**: default, matrix 4.8.8

**Comment by jiangdashao** [comment]
can't reproduce

**Comment by assasin541** [comment]
@jiangdashao what? You literally have video, verbose messages and step by step how to do that. On 1.8 server with viaversion you login with 1.15 (1.13+ is enough i think) and go in the water/lava.

**Comment by jiangdashao** [comment]
I tried it, can't reproduce

**Comment by assasin541** [comment]
@jiangdashao ghost mode enabled? It happens on clear server

**Comment by respiter** [comment]
tested 1.15.2 client on matrix test server (1.8) in same thing didnt work

**Comment by assasin541** [comment]
Tested again. With option 'nms-player-ticking: false' in ViaVersion this happens. Disabling this option creates more false posivites in water.

**Comment by respiter** [comment]
why would you have  'nms-player-ticking: false' in the first place? @assasin541
