### ISSUE TITLE
[FP] Scaffold ban using badlion 

### ISSUE THREAD

**Issue by Satioss** [jiangdashao/Matrix-Issues#1755]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8 
**Verbose messages**: In the video
**How/when does this happen**: Player started bridging and got banned
**Video of false positive**: https://www.youtube.com/watch?v=Zt1OSw7DIMU
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Check_minigames from config-example

**Comment by jiangdashao** [comment]
Please provide the verbose messages

**Comment by Satioss** [comment]
![false](https://user-images.githubusercontent.com/66736892/84401495-a0bf6a80-ac03-11ea-928f-79bc82b75cf2.jpg)

**Comment by respiter** [comment]
scaffold ez check is not reliable, should be 1-3vl or removed

**Comment by Satioss** [comment]
New video with correct verbose message https://youtu.be/lm6UnntaH6Y
![image](https://user-images.githubusercontent.com/66736892/84520000-2e1dc000-acd3-11ea-9d24-9cc691bb59ad.png)
