### ISSUE TITLE
[FP] flight

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1757]
**Server version**: 1.15.2
**Verbose messages**: 
failed Fly check | suspicious movement:-0.121 predict:-0.445 lm:-0.374 hard_pred:-0.445 sev_pred:-1.025 air_t:11 fall_t:6 g:-- tag:gn (+5) | vl:10 ping:107 tps:20.0 lp:5 component: fly.main
Hey! Sorry, but you can't place that block here.
failed Fly check | suspicious movement:-0.121 predict:-0.445 lm:-0.374 hard_pred:-0.445 sev_pred:-0.377 air_t:11 fall_t:6 g:-- tag:gn (+5) | vl:15 ping:107 tps:20.0 lp:5 component: fly.main
**How/when does this happen**: jumping with blocks on worldguard region
**Other information**: https://imgur.com/a/QCh8kpP on matrix test server, matrix should set them back instead of giving them vl, kinda like how hypixel does

**Comment by jiangdashao** [comment]
They should get vl
