### ISSUE TITLE
[FP]  Scaffold ban using badlion

### ISSUE THREAD

**Issue by Satioss** [jiangdashao/Matrix-Issues#1758]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8, matrix 4.8.7
**Verbose messages**: https://user-images.githubusercontent.com/66736892/84520000-2e1dc000-acd3-11ea-9d24-9cc691bb59ad.png 
**How/when does this happen**: Player started bridging and got banned
**Video of false positive**: https://www.youtube.com/watch?v=lm6UnntaH6Y&feature=youtu.be
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Check_minigames from config-example

**Comment by jiangdashao** [comment]
Why does this player have a pitch of 81 degrees? And it’s an integer, it’s almost impossible, only cheating

**Comment by respiter** [comment]
@jiangdashao if you have a server with 10+ people you are gonna have a few integer pitch/yaw flags per day even though its unlikely. A large sample size makes unlikely things likely.

**Comment by jiangdashao** [comment]
I will remove this check in the next update
