### ISSUE TITLE
[BYPASS] Reach and fastplace on Raven v2

### ISSUE THREAD

**Issue by dgo2001** [jiangdashao/Matrix-Issues#1759]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Sportpaper 1.8, PGM server. Just downloaded Matrix and ProtocolLib
**Hacked client**: Raven V2
**Link to hacked client**: https://www.youtube.com/watch?v=RugFiD_U1I4
**Cheat that bypassed**: Reach up to 4.5 blocks, fastplace
**Video of bypass**: Dont have any
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by respiter** [comment]
post video of you bypassing please, along with verbose messages

**Comment by jiangdashao** [comment]
dumb?
