### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by Helios19932** [jiangdashao/Matrix-Issues#1761]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: RANGGYU-Cheats
**Link to hacked client**: 
**Cheat that bypassed**: Fly
**Video of bypass**: https://youtu.be/SpZ2FsEfwP4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
...
