### ISSUE TITLE
[FP]  Anticheat thinks speed hacks on snow whilst using badlion client

### ISSUE THREAD

**Issue by obsessivecoder1** [jiangdashao/Matrix-Issues#1762]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15
**Verbose messages**:  
![image](https://user-images.githubusercontent.com/40735254/84650689-a9b08480-af00-11ea-9532-5ea2b927eaf5.png)
**How/when does this happen**:  This had happened on the test server. when I was going up the snow stair, the anticheat detected i was doing speed, this is only happening on BAC
**Video of false positive**: 
https://streamable.com/dkfp6q
**Other information**: 
None
## Configuration Files
**Link to checks.yml file**:
Default config as this happened on the test server

**Comment by jiangdashao** [comment]
if it's a client issue, then I won't fix it

**Comment by obsessivecoder1** [comment]
This still happens in vanilla. 

Video: https://streamable.com/92yndx
