### ISSUE TITLE
[FP] Printer?

### ISSUE THREAD

**Issue by DeveloperJackYT** [jiangdashao/Matrix-Issues#1763]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.8.8 TacoSpigot
**Verbose messages**:  Lots of differnet ones
**How/when does this happen**:  When someones uses printer
**Video of false positive**:  None
**Other information**: Is there any way to stop printer flagging for speed, scaffold, badpackets, etc? Is there an extra plugin I can use or anything? Thank you so much to whoever can help, all I need is to be able to modify the AC so that printer will work :D

## Configuration Files
**Link to checks.yml file**: https://sourceb.in/c208efae05

**Comment by respiter** [comment]
schematica printer is a hack, tell your player to build it legit

**Comment by jiangdashao** [comment]
printer mod is a hack
