### ISSUE TITLE
[REQUEST] timer

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1764]
**What features/checks do you need?:**
net.timer tag:timer doesnt false much from network lag, so you can freeze player when they set this off but players with network lag sometimes false tag:limit and get frozen for time which is annoying. How about you make tag:limit not freeze the player and make tag:timer freeze then like it does now (maybe add config option)

**Comment by jiangdashao** [comment]
limit usually means blink or teleport, so it must be frozen
