### ISSUE TITLE
[BYPASS] liquid speed

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1765]
**Server version**: 1.8.8
**Hacked client**: wwe
**Video of bypass**: discord
**Other information**: super speed in lava

**Comment by jiangdashao** [comment]
Because it's 1.13+ client, it can swim, Matrix will make 1.13+ client more tolerant in the water

**Comment by respiter** [comment]
@jiangdashao you cannot swim in lava, even on 1.13, max speed in lava in 1.8 and 1.13 is the same
