### ISSUE TITLE
[FP] Fly Speed

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1768]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**https://youtu.be/HSJSrptEhSk**: 
**https://youtu.be/HSJSrptEhSk**: 
**https://youtu.be/HSJSrptEhSk**: 
**Random happens, doenst have any modifikation**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by respiter** [comment]
they are using nofall im pretty sure

**Comment by respiter** [comment]
here is what is set off sprinting with nofall on
`failed Fly check | ground spoof (expect: --, move: 0.007,0.248,-0.333, at: 273.3,55.001,1396.814, type: air, pkt: false) (+2) | vl:14 ping:103 tps:20.0 lp:610 component: fly.gf
failed Fly check | ground spoof (expect: --, move: 0.01,0.165,-0.328, at: 273.311,55.166,1396.486, type: air, pkt: false) (+2) | vl:16 ping:103 tps:20.0 lp:610 component: fly.gf
failed Speed check | suspicious movement (move: 0.319, predict: 0.307, friction: 0.6, ground:true, motY: 0.003, increase:0.13, preMove:0.177, motion: 0.02,0.003,-0.319, attribute: 0.13, tag: pred) (+2) | vl:4 ping:103 tps:20.0 lp:610 component: move.xz
failed Speed check | suspicious movement (move: 0.834, predict: 0.266, friction: 0.6, ground:true, motY: -0.753, increase:0.13, preMove:0.136, motion: -0.087,-0.753,0.83, attribute: 0.13, tag: pred) (+2) | vl:2 ping:120 tps:20.0 lp:610 component: move.xz
failed Fly check | ground spoof (expect: --, move: 0.031,0.248,-0.28, at: 275.176,55.001,1394.487, type: air, pkt: false) (+2) | vl:22 ping:120 tps:20.0 lp:610 component: fly.gf`
it also kills me like in the video

**Comment by Crowraw** [comment]
Nope he doesnt use NoFall.

**Comment by respiter** [comment]
are you sure?

**Comment by Crowraw** [comment]
Yes

**Comment by respiter** [comment]
did you screenshare him

**Comment by Crowraw** [comment]
Yes

**Comment by respiter** [comment]
whats their client version

**Comment by jiangdashao** [comment]
He is cheating
