### ISSUE TITLE
[REQUEST] Better NoSlow check

### ISSUE THREAD

**Issue by ghost** [jiangdashao/Matrix-Issues#1769]
change "should matrix check for noslowdown" config option to "should matrix give violations for noslowdown" and make it when a player flags noslowdown   ((CraftPlayer)p).getHandle().clearActiveItem(); is called, this means that their bow/food gets reset so they cannot eat. This will remove false kicks and also make it very difficult to use noslow

**Comment by respiter** [comment]
you can do the same if a player sends attack packet while their hand is raised just do event.setcancelled(true)

**Comment by AMDBartek** [comment]
+1 for resetting the player's bow/food when they use noslowdown

**Comment by DontNeedAName** [comment]
Isn't this already added in matrix 6?
