### ISSUE TITLE
[FP] Scaffold + macro/fastclicking

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1770]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(02:56:41) assasin541 Scaffold | (tower) quickly build blocks up (t: 200, d_n: 0.879, d_h: 0.46, avg: 300.0, block: true) (+2) | vl:2 ping:39 tps:19.98 component: sfd.twr
(02:56:42) assasin541 Scaffold | (tower) quickly build blocks up (t: 400, d_n: 0.542, d_h: 0.207, avg: 280.0, block: true) (+2) | vl:4 ping:39 tps:19.98 component: sfd.twr
(02:56:42) assasin541 Scaffold | (tower) quickly build blocks up (t: 298, d_n: 0.566, d_h: 0.234, avg: 280.0, block: true) (+2) | vl:6 ping:39 tps:19.98 component: sfd.twr
(02:56:42) assasin541 Scaffold | (tower) quickly build blocks up (t: 301, d_n: 0.695, d_h: 0.2, avg: 300.0, block: true) (+2) | vl:8 ping:39 tps:19.98 component: sfd.twr
(02:56:43) assasin541 Scaffold | (tower) quickly build blocks up (t: 201, d_n: 0.561, d_h: 0.255, avg: 280.0, block: true) (+2) | vl:10 ping:39 tps:19.98 component: sfd.twr
(02:56:43) assasin541 Scaffold | (tower) quickly build blocks up (t: 199, d_n: 0.657, d_h: 0.425, avg: 279.0, block: true) (+2) | vl:12 ping:39 tps:19.98 component: sfd.twr
(02:56:43) assasin541 Scaffold | (tower) quickly build blocks up (t: 399, d_n: 0.552, d_h: 0.233, avg: 279.0, block: true) (+2) | vl:14 ping:39 tps:20.0 component: sfd.twr
(02:56:43) assasin541 Scaffold | (tower) quickly build blocks up (t: 200, d_n: 0.819, d_h: 0.476, avg: 260.0, block: true) (+2) | vl:16 ping:39 tps:20.0 component: sfd.twr
(02:56:44) assasin541 Scaffold | (tower) quickly build blocks up (t: 501, d_n: 1.056, d_h: 0.744, avg: 300.0, block: true) (+2) | vl:18 ping:39 tps:20.0 component: sfd.twr
(02:56:46) assasin541 Scaffold | (tower) quickly build blocks up (t: 199, d_n: 0.696, d_h: 0.185, avg: 320.0, block: true) (+2) | vl:20 ping:46 tps:20.0 component: sfd.twr
(02:56:47) assasin541 Scaffold | (tower) quickly build blocks up (t: 500, d_n: 0.787, d_h: 0.242, avg: 300.0, block: true) (+2) | vl:22 ping:46 tps:20.0 component: sfd.twr
(02:56:47) assasin541 Scaffold | (tower) quickly build blocks up (t: 200, d_n: 0.526, d_h: 0.162, avg: 300.0, block: true) (+2) | vl:24 ping:46 tps:20.0 component: sfd.twr

**How/when does this happen**: when you click ~15 clicks per second on right click and place blocks near wall and try building up your blocks are not placing and cancel_vl: 30 doesn't work with this check
**Other information**: easy to check with 15 cps autoclicker/macro near wall and jumping up and sprinting

## Configuration Files
**Link to checks.yml file**: default files

**Comment by respiter** [comment]
please include a video

**Comment by respiter** [comment]
and is autoclicker when scaffolding even legit ?

**Comment by jiangdashao** [comment]
Please include a video to show do it (legit, no autoclicker, no hack)

**Comment by assasin541** [comment]
@jiangdashao there should be option to allow it or not and cancel_vl should work with it.

**Comment by eggnog3** [comment]
you can easily false positive the anticheat... if you punch someone enough that the kill aura checker ghost spawns behind you, you can spin your mouse really fast and hit the ghost and cause the anti cheat to think youre using kill aura.

**Comment by jiangdashao** [comment]
> you can easily false positive the anticheat... if you punch someone enough that the kill aura checker ghost spawns behind you, you can spin your mouse really fast and hit the ghost and cause the anti cheat to think youre using kill aura.
Are you DUMB? Deliberately trigger an attack NPC = false positive?

**Comment by assasin541** [comment]
@jiangdashao cancel_vl should work with this scafffold check.

**Comment by assasin541** [comment]
@jiangdashao any news?

**Comment by assasin541** [comment]
@jiangdashao it is not fixed 
(14:21:51) player1 Scaffold | (tower) quickly build blocks up (t: 94, d_n: 0.538, d_h: 0.196, avg: 300.0, block: true) (+2) | vl:19 ping:17 tps:20.0 component: sfd.twr
(14:21:51) player1 Scaffold | (tower) quickly build blocks up (t: 312, d_n: 0.969, d_h: 0.304, avg: 339.0, block: true) (+2) | vl:21 ping:17 tps:20.0 component: sfd.twr
(14:21:51) player1 Scaffold | (tower) quickly build blocks up (t: 185, d_n: 0.698, d_h: 0.21, avg: 279.0, block: true) (+2) | vl:23 ping:17 tps:20.0 component: sfd.twr
(14:21:51) player2 Scaffold | (tower) quickly build blocks up (t: 194, d_n: 1.266, d_h: 0.179, avg: 316.0, block: true) (+2) | vl:2 ping:49 tps:20.0 component: sfd.twr
(14:21:52) player2 Scaffold | (tower) quickly build blocks up (t: 184, d_n: 0.957, d_h: 0.262, avg: 337.0, block: true) (+2) | vl:4 ping:49 tps:20.0 component: sfd.twr

Cancel vl should work with this option and it should be editable.

**Comment by assasin541** [comment]
@jiangdashao did you have a look into that? Disabling this option is just temporary fix

**Comment by jiangdashao** [comment]
> @jiangdashao did you have a look into that? Disabling this option is just temporary fix

what do you mean? false positive?

**Comment by assasin541** [comment]
@assasin541 yes with sfd.twr. Jump and run near wall and place blocks fast. You don't need autoclicker to trigger that and cancel_vl doesn't check that.

**Comment by assasin541** [comment]
@jiangdashao
