### ISSUE TITLE
[FP] Speed BadPackets

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1772]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**https://youtu.be/dChqaWQV8d8**: 
**https://youtu.be/dChqaWQV8d8**: 
**https://youtu.be/dChqaWQV8d8**: 
**https://youtu.be/dChqaWQV8d8**: 
**https://youtu.be/dChqaWQV8d8**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
wtf, I can't get your point, your video is confusing

**Comment by jiangdashao** [comment]
if it was caused by teleport, you can set `max_extra_packets` to `21`
