### ISSUE TITLE
[BYPASS] Flight

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1773]
**Server version**: 1.15.2
**Hacked client**: sigma
**Cheat that bypassed**: Flight
**Video of bypass**: https://youtu.be/fjefevCmq_s
**Other information**: default configuration

**Comment by jiangdashao** [comment]
did you enable fly setback?

**Comment by respiter** [comment]
yes, this is default matrix configuration

**Comment by respiter** [comment]
I tested this on matrix test server and it didn't work so perhaps its a 1.15.2 issue

**Comment by jiangdashao** [comment]
it's a setback system bug
