### ISSUE TITLE
[FP] speed fly movement

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1774]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**https://www.youtube.com/watch?v=vFyRY2Pysds&feature=youtu.be**: 
**https://www.youtube.com/watch?v=vFyRY2Pysds&feature=youtu.be**: 
**https://www.youtube.com/watch?v=vFyRY2Pysds&feature=youtu.be**: 
**https://www.youtube.com/watch?v=vFyRY2Pysds&feature=youtu.be**: 
Just random happens when starting the round
## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
if only this guy can get the false positive, why not let him check his client?
