### ISSUE TITLE
[REQUEST] Make all calls to player.teleport have the teleportreason.UNKNOWN

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1775]
**What features/checks do you need?:**
Make all calls to player.teleport have the teleportreason.UNKNOWN, when a player is setback plugin teleport reason is used. This messes with plugins listening for teleportation.

**Comment by jiangdashao** [comment]
I hardly use teleport(), I usually use event.setTo()

**Comment by respiter** [comment]
This calls player.teleport(location,Teleportreason.PLUGIN) so why not use this but with teleportreason.UNKNOWN
