### ISSUE TITLE
[BYPASS] SPEED

### ISSUE THREAD

**Issue by Incluuu** [jiangdashao/Matrix-Issues#1780]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.12.2
**Hacked client**:  Flux (but works on everyone)
**Link to hacked client**: 
**Cheat that bypassed**: SPEED
**Video of bypass**: https://www.youtube.com/watch?v=uCo2b6pygDU&feature=youtu.be
**Other information**: I turned off the kick

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Not bypassed, Receiving knockback will cause faster movement
