### ISSUE TITLE
[FP] Fastbreak/Place

### ISSUE THREAD

**Issue by swerck** [jiangdashao/Matrix-Issues#1785]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.14.4
**Verbose messages**: "Player" tried to place/break a block too quickly (FastPlace/FastBreak)
**How/when does this happen**: 
I have ViaVersion on my network and if a player with version 1.8.8 joins and tries to break dirt with a shovel (with all of them) or Hand then he gets kicked for fastbreak
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/kFwsN2DZ

**Comment by respiter** [comment]
post verbose messages and/or video of this. Also via-rewind is buggy and not supported. Please use protocolsupport.

**Comment by Hyronymos1337** [comment]
People can place blocks faster in 1.15 maybe that’s the issue here

**Comment by jiangdashao** [comment]
DO NOT USE ViaRewind, Please use protocolsupport.
