### ISSUE TITLE
[REQUEST] improve interact checks

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1786]
**What features/checks do you need?:**
Since mc sends interact packet before movement this causes many false flags for opening chests whilst moving, how about you wait until the move is sent before flagging, like hitbox check. you can cancel it if its not valid when interact packet is sent but wait until move is send before flagging

**Comment by jiangdashao** [comment]
Then Interact check loses its meaning, Interact check should try to prevent cheating, you can even set 0VL weight
