### ISSUE TITLE
[FP] Scaffold False Positive

### ISSUE THREAD

**Issue by Tecnio** [jiangdashao/Matrix-Issues#1788]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: Player failed Scaffold check : (scaffold) safe walk (vx: 0.371, vz = 0.795, d: 300)
**How/when does this happen**: When i breeizly bridge
**Video of false positive**: https://gyazo.com/718d081ce9e3c10d4cc20c711233282f
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
Default

**Comment by respiter** [comment]
only 6vl, try and get kicked by doing that. I think it will be near impossible to breezy that long

**Comment by Tecnio** [comment]
> only 6vl, try and get kicked by doing that. I think it will be near impossible to breezy that long

Oh thats bc i couldnt breeizly good if i breeizly good it sky rockets.
