### ISSUE TITLE
[REQUEST] Add slow timer check

### ISSUE THREAD

**Issue by respiter** [jiangdashao/Matrix-Issues#1792]
**What features/checks do you need?:**
Players can use slow timer 0.1 speed to have more air time which can give them an unfair advantage in minigames. If the player is consistently sending less than normals packets then flag them for timer tag: slow, shouldn't false from laggy players since they don't have a consistently slower game speed.

**Comment by jiangdashao** [comment]
No, Matrix had slow timer check before, But Minecraft will slow the flying packet in some cases, so I removed this check
