### ISSUE TITLE
[REQUEST] 1.16 Support

### ISSUE THREAD

**Issue by jiangdashao** [jiangdashao/Matrix-Issues#1795]
**What features/checks do you need?:**
1. Soul speed enchant, when a player has this on their boots depending on the level they can go faster on soul soil and soul sand blocks (https://youtu.be/zqMw2ZmTOIc?t=1533) . 2. twisting vines and weeping vines, let you climb them, unlike ladders they aren't against the wall (https://youtu.be/zqMw2ZmTOIc?t=766). Striders are a new ridable mob on lava, you will need to add them to entity speed check (https://youtu.be/zqMw2ZmTOIc?t=390)

**Comment by Hyronymos1337** [comment]
1.16.1
