### ISSUE TITLE
[REQUEST] add miniscule yaw difference check to ka.aim

### ISSUE THREAD

**Issue by ghost** [jiangdashao/Matrix-Issues#1796]
**What features/checks do you need?:**
Some kill aura aim modes such as Test and AAC mode on sigma send yaw packets with a yaw difference from last yaw of <0.001, legit client can only send this consistently if they are in a boat (boat sways side to side in tiny amounts) so if player isnt in a vehicle this flags kill aura aim and from my weeks of testing hasnt false flagged.

example:
long time = (System.currentTimeMillis() - op.lastlook);
 op.lastlook = System.currentTimeMillis();
        if (yawdif != 0 && Math.abs(time - 50) < 15) {
            if ((System.currentTimeMillis() - op.lastattackpacket) < 3000) {
                if (yawdif < 0.001) {
                    if (p.getVehicle() == null) {
                        if ((op.yawvl += 20) >= 200) { //some sort of slight verbose
                          *flag*
                        }
                    }

**Comment by jiangdashao** [comment]
it only detects Test mode, Matrix's other checks are enough to check it
