### ISSUE TITLE
[BYPASS] criticals

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1798]
**Server version**: 1.15.2
**Hacked client**: aristois
**Cheat that bypassed**: criticals
**Other information**: criticals dont flag when you attack blazes, you only flag timer

**Comment by jiangdashao** [comment]
Matrix can't detect it when you "inside" some blocks (e.g. grass)
