### ISSUE TITLE
[FP] FastPlace

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#1803]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.8.8
**Verbose messages**: https://i.imgur.com/9ZomW7M.png
**How/when does this happen**: From the 13th second in the video.
**Video of false positive**: https://www.youtube.com/watch?v=b2KL9ewijY0&feature=youtu.be

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/raw/VrikCEHE

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
client version? using any protocol hacks?

**Comment by Hyronymos1337** [comment]
As far as I know you can place blocks with 1.15 faster as in 1.8, maybe that’s the bugg

**Comment by PhoenixDiscord** [comment]
Are you sure that Matrix is up-to-date? The noswing false positives have been fixed in Matrix 4.8.1 (see https://github.com/jiangdashao/Matrix-Issues/issues/1689)

**Comment by DrakMC** [comment]
Client: Minecraft 1.12
Server: Paper Spigot 1.8.8 with ViaVersion

I'm using latest version of the plugin.
