### ISSUE TITLE
[BYPASS] MatrixBots

### ISSUE THREAD

**Issue by variationtime** [jiangdashao/Matrix-Issues#1805]
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

https://www.youtube.com/watch?v=a9TRJe7XMWk&feature=emb_logo
Almost all clients are currently bypasing matrix bots, lb just remove it from your client as u can see

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: defaut

**Comment by jiangdashao** [comment]
LiquidBounce B2? It should be detected quickly

**Comment by Wentoxic** [comment]
i think its the 1.12.2 version from LiquidBounce

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
basically no anticheats can detect 1.8 lb killaura?

**Comment by AoElite** [comment]
I don't think the bot needs to be removed but it definitely needs some small adjustments. A lot of clients do hit it if their fov is high enough. (Including Vape!) If the bot showed it's self infront of the player more then most clients would hit it.
