### ISSUE TITLE
[FP] Throwing EnderPearl

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#1806]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  PaperSpigot 1.8.8
**How/when does this happen**:  When I right-click with ender pearl on the block, I don't get teleported, it just removes the item from the inventory. This problem doesn't persist without AntiCheat.

**Comment by jiangdashao** [comment]
Because the matrix blocks the delivery of pearls at close range, you can use the checks.yml Disable this function (phase check) in
