### ISSUE TITLE
[FP] Kicked for fastplacing when using bonemeal farm 

### ISSUE THREAD

**Issue by Markiie** [jiangdashao/Matrix-Issues#1807]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server - RUNNING ON 1.16.1
- [x ] The issue happens on default config.yml and checks.yml - Premium Config
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.1 
**Verbose messages**: (I dont know what this means, im sorry)
**How/when does this happen**: Everytime
**Video of false positive**:  https://www.youtube.com/watch?v=qpUy3yKK5ec&feature=youtu.be
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/yFAghz6v

**Comment by jiangdashao** [comment]
Please provide the verbose message: /matrix verbose

**Comment by Markiie** [comment]
AsousNova failed Block check | no swing after place block | POTATOES (+1) vl:11 ping: 29 tps:20.0 lp:0 component: block.noswing
