### ISSUE TITLE
[1.8.5] Matrix Verbose logging doesn't work for a single player

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#181]
## How you trigger the false positive?
1. Use /matrix verbose playername
2. Observe logs in-game
3. Nothing appears in chat for that targeted player

## Server Information
**Matrix Version**: 1.8.5
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Please input the target player's name
/matrix verbose <player name>

**Comment by Kruize1** [comment]
I do, for example I use /matrix verbose AnimalGamer 

Their logs don't show up

**Comment by jiangdashao** [comment]
Are you sure they get flagged?

**Comment by Kruize1** [comment]
Yes, the normal verbose logging works and shows their violations

**Comment by Kruize1** [comment]
nevermind it's working now...
