### ISSUE TITLE
[FP] twisting_vines fly

### ISSUE THREAD

**Issue by lJt-iS43BSqrVdhq** [jiangdashao/Matrix-Issues#1813]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16Paper #47
**Verbose messages**: fly
**How/when does this happen**: 爬到缠怨藤minecraft:twisting_vines顶部
**Video of false positive**:
**Other information**:

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
This false-positive already fixed in 5.0.1, I will release it soon
