### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by EchoRapidz** [jiangdashao/Matrix-Issues#1815]
Feature requests:

- Add ban animations for premium users
- Add a pingspoof check
- Add a feature that generates a file every time someone gets kicked/banned that has all the violations they did leading up to the punishment including time, ping, and server tps.

**Comment by jiangdashao** [comment]
1. No, it's useless
2. No, Matrix does not use the server's ping data, most ping spoof hack is useless. And I will continue to improve Matrix's own latency computing system
3. Still No. You can do this through the API, I don’t think this function is useful, it will only create many files
