### ISSUE TITLE
[FP] water speed

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1823]
**Server version**: 1.16.1
**Verbose messages**: 
 Jesus - liquid speed (speed: 0.191, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:84 - jesus.speed.in
 Jesus - liquid speed (speed: 0.191, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:87 - jesus.speed.in
 Jesus - liquid speed (speed: 0.191, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:90 - jesus.speed.in
 Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:93 - jesus.speed.in
 Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:96 - jesus.speed.in
 Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:99 - jesus.speed.in
Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:102 - jesus.speed.in
 Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:105 - jesus.speed.in
 Jesus - liquid speed (speed: 0.192, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:108 - jesus.speed.in
Jesus - liquid speed (speed: 0.193, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:111 - jesus.speed.in
 Jesus - liquid speed (speed: 0.193, expect:0.12, dmg: false, flw:false, module: in) (+3) - p:98 t:15.62 lp:11 vl:114 - jesus.speed.in
**How/when does this happen**: swimming in water 
**Other information**: dont use whether player is in swimming pose in 1.13+ for detection, this is very susceptible to desyncs and keeps falsely kicking players due to this, atleast add a config option

**Comment by jiangdashao** [comment]
I will try to make the player stop swimming after get flagged
