### ISSUE TITLE
[BYPASS] Sigma5 nuker bypass  

### ISSUE THREAD

**Issue by iAvearges** [jiangdashao/Matrix-Issues#1826]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Hacked client**: Sigma5 (5.0.0)
**Link to hacked client**: https://sigmaclient.info/#download
**Cheat that bypassed**: Nuker 
**Video of bypass**: https://i.dannn.net/CJq42.mp4
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: https://paste.danielraybone.com/idukuwulac.hs
**Link to config.yml file**: https://paste.danielraybone.com/amefemikis.hs

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
cant really detect it without falses ig seems pretty legit serverside

**Comment by jiangdashao** [comment]
it's pretty legit for server
