### ISSUE TITLE
[BYPASS] Sigma5 No Fall 

### ISSUE THREAD

**Issue by iAvearges** [jiangdashao/Matrix-Issues#1827]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Hacked client**: Sigma5 (5.0.0)
**Link to hacked client**: https://sigmaclient.info/#download
**Cheat that bypassed**: No Fall - Vanilla setting
**Video of bypass**: https://i.dannn.net/eSUtj.mp4
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Not important
