### ISSUE TITLE
[FP] velocity

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1828]
## Issue Information
**Server version**: 1.16.1
**How/when does this happen**: Being attacked by magma cube
**Video of false positive**: discord

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
This might actually be from netherite knockback resistance

**Comment by jiangdashao** [comment]
if some patterns works not good, disable it, I can't fix it
