### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by iAvearges** [jiangdashao/Matrix-Issues#1829]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Hacked client**: Sigma5 (5.0.0)
**Link to hacked client**: https://sigmaclient.info/#download
**Cheat that bypassed**: Entity speed 
**Video of bypass**: https://i.dannn.net/1ICtM.mp4
**Other information**: Works on ice/packet ice. Detected on normal blocks.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
What? In this video, you are showing nofall, not entity speed

**Comment by iAvearges** [comment]
Whoops my bad. Posted the wrong link. Edited the post.

**Comment by jiangdashao** [comment]
Because you can eventually move very fast on the ice block, about 2.8~3.2 blocks/tick.
