### ISSUE TITLE
[INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by JoseLu1200** [jiangdashao/Matrix-Issues#1830]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Incompatible plugin**: Golden Enchants (https://www.spigotmc.org/resources/goldenenchants-1-14-1-16.61693/)
**Verbose messages (or) console errors**: 
- JoseLu1200 tried to illegally interact with an entity or block | Interact | 1/2
- JoseLu1200 has disconnected, reason: ?AntiCheat?>> Illegally Interacting with Block/Entity 
**How/when does this happen**: When you use the "Tunnel" custom enchant of the Golden Enchants plugin
**Video of incompatibility**: https://imgur.com/a/2bHqfre
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/iVXKK2kh

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
@jiangdashao Why not use dig packets instead of blockbreakevent?
