### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1831]
**Server version**: 1.16.1
**Hacked client**: bleachhack
**Link to hacked client**: https://github.com/BleachDrinker420/bleachhack-1.14/blob/master/BleachHack-Fabric-1.16/src/main/java/bleach/hack/module/mods/Speed.java
**Cheat that bypassed**: speed
**Video of bypass**: discord

**Comment by MrEDok** [comment]
Just tested real quick and none of the Speed module in that client was able to bypass matrix 
Server version 1.16.1 client 1.16.1

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
@MrEDok mode: onground speed: 1.1

**Comment by MrEDok** [comment]
ah got it 1.1 seem to work 1.2 it detect
1.1 walking/running work but when jump it detect

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
mode: minihop speed: 3.0 works on/around slabs
