### ISSUE TITLE
[FP] Fly FP when swimming up in water with kelp

### ISSUE THREAD

**Issue by JasonHorkles** [jiangdashao/Matrix-Issues#1834]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-68 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Verbose messages**: Shown in video
**How/when does this happen**: Swimming up in a column of water and kelp will trigger a fly false positive when you reach the top
**Video of false positive**: [Video](https://1drv.ms/v/s!ArOS099NaR9LiIAUqwPwK9r4w1ueDw?e=ESlX9t)
**Other information**: Haven't thoroughly tested in an area larger than a 1x1 area but it seems to only happen in a 1x1 space from what I've seen

## Configuration Files
**Link to checks.yml file**:
https://hasteb.in/ixigiboj.yaml

**Comment by jiangdashao** [comment]
It seems that kelp is not judged as water
