### ISSUE TITLE
[FP] KillAura (ka.critical.ground/ka.critical.modify)

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1839]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:26:12) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:45 ping:13 tps:20.0 component: ka.critical.ground
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:50 ping:13 tps:20.0 component: ka.critical.modify
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:55 ping:13 tps:20.0 component: ka.critical.ground
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:60 ping:13 tps:20.0 component: ka.critical.modify
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:65 ping:13 tps:20.0 component: ka.critical.ground
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:70 ping:13 tps:20.0 component: ka.critical.modify
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:75 ping:13 tps:20.0 component: ka.critical.ground
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:80 ping:13 tps:20.0 component: ka.critical.modify
(17:26:13) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:85 ping:13 tps:20.0 component: ka.critical.ground
(17:26:14) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:90 ping:13 tps:20.0 component: ka.critical.modify
(17:26:14) testre13 KillAura | critical hit without correct jumping | tag: ground spoof (+5) | vl:95 ping:13 tps:20.0 component: ka.critical.ground
(17:26:14) testre13 KillAura | critical hit without correct jumping | tag: modify | ver: 8 d: 0.0 (+5) | vl:100 ping:13 tps:20.0 component: ka.critical.modify

**How/when does this happen**: player reported that when he was spectator, and tried to damage his old enemy/teammate he got kicked
**Other information**: 1.8.8 client's version

## Configuration Files
**Link to checks.yml file**: -

**Comment by dudeman123** [comment]
Probably cheating

**Comment by jiangdashao** [comment]
Please include a video
