### ISSUE TITLE
[ERROR] RuntimeException

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#1841]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.8.8
**Error(s) found in console**: https://pastebin.com/raw/RXPWFRnM
**How/when does this happen**: Randomly

**Comment by jiangdashao** [comment]
can't reproduce
