### ISSUE TITLE
[BYPASS] Vanilla WallClimb with cancelled BreakBlock event.

### ISSUE THREAD

**Issue by LEx66** [jiangdashao/Matrix-Issues#1842]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 PaperMC
**Hacked client**: N/A
**Link to hacked client**: N/A
**Cheat that bypassed**: WallClimb/Spider (Fly/Phase)
**Video of bypass**: https://streamable.com/1u5j2r
**Other information**: A plugins cancels the BreakBlock event. While the player is bugged inside the block he does not take knockback and is flagged as fly

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
can't fix
