### ISSUE TITLE
[FP] Phase on carpet with 1.7 client

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1843]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(22:28:14) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.027,44.853, dist: 0.0, loop: false) (+2) | vl:467 ping:12 tps:20.0 component: phase.main
(22:28:14) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.028,44.853, dist: 0.0, loop: false) (+2) | vl:469 ping:12 tps:20.0 component: phase.main
(22:28:14) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.029,44.853, dist: 0.0, loop: false) (+2) | vl:471 ping:12 tps:20.0 component: phase.main
(22:28:14) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.03,44.853, dist: 0.0, loop: false) (+2) | vl:473 ping:12 tps:20.0 component: phase.main
(22:28:15) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.031,44.853, dist: 0.0, loop: false) (+2) | vl:475 ping:12 tps:19.99 component: phase.main
(22:28:15) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.032,44.853, dist: 0.0, loop: false) (+2) | vl:477 ping:12 tps:19.99 component: phase.main
(22:28:15) soimer Phase | moved into block (block: carpet, move: 0.0,-0.078,0.0, at: 5.036,60.033,44.853, dist: 0.0, loop: false) (+2) | vl:479 ping:12 tps:19.99 component: phase.main
(22:28:36) soimer Speed | suspicious movement (move: 0.426, expect:0.2873, t:0, sprint: false, attr: 0.1, tag: a) (+9) | vl:9 ping:13 tps:19.97 component: speed.main
(22:28:36) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.001,43.759, dist: 0.098, loop: false) (+2) | vl:496 ping:13 tps:19.97 component: phase.main
(22:28:36) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.002,43.759, dist: 0.098, loop: false) (+2) | vl:498 ping:13 tps:19.97 component: phase.main
(22:28:36) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.003,43.759, dist: 0.098, loop: false) (+2) | vl:500 ping:13 tps:19.97 component: phase.main
(22:28:36) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.004,43.759, dist: 0.098, loop: false) (+2) | vl:502 ping:13 tps:19.97 component: phase.main
(22:28:37) soimer Phase | moved into block (block: carpet, move: -0.124,0.0,0.118, at: 7.067,60.004,43.809, dist: 0.171, loop: false) (+2) | vl:504 ping:13 tps:20.0 component: phase.main
(22:28:37) soimer Fly | suspicious movement:0.001 predict:-0.078 pmv:0.001 tag:ground (+5) | vl:5 ping:13 tps:20.0 component: fly.main
(22:28:37) soimer Fly | suspicious movement:0.001 predict:0.42 air_t:0 tag:sam (+5) | vl:10 ping:13 tps:20.0 component: fly.main
(22:28:37) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.005,43.759, dist: 0.098, loop: false) (+2) | vl:506 ping:13 tps:20.0 component: phase.main
(22:28:37) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.006,43.759, dist: 0.098, loop: false) (+2) | vl:508 ping:13 tps:20.0 component: phase.main
(22:28:37) soimer Phase | moved into block (block: carpet, move: -0.071,0.0,0.068, at: 7.12,60.007,43.759, dist: 0.098, loop: false) (+2) | vl:510 ping:13 tps:20.0 component: phase.main

**How/when does this happen**: when you step on carpet which is on the ground and you are on 1.7
**Other information**: 1.7 client's version

## Configuration Files
**Link to checks.yml file**: -

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
Matrix only supports 1.8 - 1.16.1

**Comment by assasin541** [comment]
@YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE it's on 1.8 server and this bug is simple and there is no option to disable phase per blocks anymore.

**Comment by Wentoxic** [comment]
That doesn't change the fact that Matrix doesn't support Minecraft version 1.7.

**Comment by jiangdashao** [comment]
I will add custom exlcude types
