### ISSUE TITLE
[REQUEST] add tick or ms to matrix log format

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1844]
**What features/checks do you need?:**
right now the timestamp is `(HH:MM:SS)` if it was `(HH:MM:SS:TT)` (1-20 ticks?) or `(HH:MM:SS:mmmm)` milliseconds. This makes debugging logs easier, say a player flags multiple of the same check within the same second, was it because of a lagspike? This would make it easier to tell.

**Comment by jiangdashao** [comment]
no
