### ISSUE TITLE
[FP] net.crash

### ISSUE THREAD

**Issue by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [jiangdashao/Matrix-Issues#1847]
**Server version**: 1.16.1
**Verbose messages**: 
BadPackets - (valid) illegal position packet | 2.9999986889802612E7,87.81614210874442,3.0E7 (+1000) - p:31 t:20.0 lp:11 vl:1000 - net.crash
**How/when does this happen**: enderpearling outside of world border (vanilla thing)

**Comment by jiangdashao** [comment]
Refuse to fix, Matrix prohibits this
