### ISSUE TITLE
[FP] Random Velocity Pattern 5 Flags

### ISSUE THREAD

**Issue by Wentoxic** [jiangdashao/Matrix-Issues#1849]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8
**Verbose messages**: visible in the video
**How/when does this happen**: randomly when you fight with 6 - 8 CPS
**Video of false positive**: https://youtu.be/NM7zt7dsIZg
**Other information**: and no it's not just because my second account played with Velocity

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
Just disable pattern 5, I can't fix velocity check right now, maybe future

**Comment by Wentoxic** [comment]
ok, but why did you close the issue? The other Future Velocity Issue has remained open.
