### ISSUE TITLE
[FP] Spectator mode phase

### ISSUE THREAD

**Issue by D230Daniel** [jiangdashao/Matrix-Issues#185]
## Basic Information
**Verbose message(s)**: Failed phase check | phased in to block
**How/when does this happen**: When flying through walls in spectator mode. (Vanilla)
**Video of false positive**: https://www.youtube.com/watch?v=DSMJtE_FJmQ

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/w9Gqjv1q
**Link to config.yml file**: https://pastebin.com/fNVuUKmH

# Server Infomation
**Server Version**: 1.13.2
**Matrix Version**: Latest as of today
**ProtocolLib Version**: Latest as of today
(Sorry, couldn't find version anywhere)

What should happen: Spectator mode allows no-clip, can fly freely through walls. (This works without Matrix)
What actually happens: Matrix triggers and teleports the player back, kicking after a few times.

**Comment by jiangdashao** [comment]
Fixed
