### ISSUE TITLE
[FP] Running on slab cause (jesus.out)

### ISSUE THREAD

**Issue by MrEDok** [jiangdashao/Matrix-Issues#1850]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Purpur-651 (MC: 1.16.1)
**Verbose messages**: https://pastebin.com/KLL533er
**How/when does this happen**: walk/run on slab
**Video of false positive**: https://streamable.com/uzq1xt
**Other information**:

## Configuration Files
**Link to checks.yml file**:

**Comment by MrEDok** [comment]
Also just tested with Matrix 5.0.1 doesn't cause any false positive but with 5.0.2 it does cause false positive.

**Comment by JasonHorkles** [comment]
Looks like the water can even be fairly far away since it's happening with this creeper farm
![image](https://user-images.githubusercontent.com/51760372/87235085-56adde00-c395-11ea-87c5-3a88954e4502.png)

**Comment by ZyphenVisuals** [comment]
The water doesn't seem to need to be bellow, or maybe not even related. In this picture, walking on the slabs around the farm triggers the Jesus check.
![Screenshot_20200712-015016](https://user-images.githubusercontent.com/55757807/87235245-cac2a300-c3e2-11ea-893b-6ed21d3b2dbc.jpg)

**Comment by MrEDok** [comment]
Look like this problem is solved on the 5.0.2-hotfix
