### ISSUE TITLE
[REQUEST] Improve the check for EntitySpeed 

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1852]
**What features/checks do you need?:**
I would really like Matrix’s EntitySpeed to be improved as it is a big problem on my server. I don’t know if this is an issue with just boats or if it affects other entities too (I cannot test this due to my CPU fan being broken, I can test it once the new CPU fan arrives if needed).

Related to issue #1832

Video of me using EntitySpeed with Matrix installed: https://streamable.com/1o4kdo

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
Matrix has a vehicle check

**Comment by AMDBartek** [comment]
@YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE Thanks for the info, changed the request to improve the check instead of to add it.

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
@AMDBartek its pretty obvious you havent tested the entityspeed check, find a bypass/false positive along with video and post it here instead of saying something as useless as "improve it"

**Comment by AMDBartek** [comment]
@YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE I said it’s related to #1832 and that issue got closed (I tested it and thought it was a bypass but it wasn’t), so I made a suggestion to improve the EntitySpeed check. I have linked the video from issue #1832 now.

**Comment by YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE** [comment]
boats go ultra fast on ice, matrix accounts for that. This is why entityspeed in boats works on ice

**Comment by AMDBartek** [comment]
EntitySpeed also seems to work on land, (and possibly water).
