### ISSUE TITLE
Sigma 5.0 AntiKnockBack Bypass

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#1854]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper 1.16 Build 89
**Hacked client**:  Sigma 5.0
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**:  AntiKnockBack
**Video of bypass**:  http://www.mediafire.com/file/jntvnrj62amw5r5/Mein_Film.mp4/file
**Other information**: -

## Configuration Files
**Link to checks.yml file**:  Default
**Link to config.yml file**:  Default

**Comment by Wentoxic** [comment]
Matrix's current velocity check is bad. Hopefully a new one will come sometime.

**Comment by Maximillus** [comment]
Then sending no look/position packets, lag no?
