### ISSUE TITLE
[REQUEST] [FUTURE] asynchronous movement checks

### ISSUE THREAD

**Issue by ghost** [jiangdashao/Matrix-Issues#1856]
**What features/checks do you need?:**
Matrix's biggest con is the playerMoveevent that takes up 5-15% of server tick time depending on player count. This can be fixed by having the option for matrix to check players off the main thread to save performance, this is tagged as future as a lot of stability testing will need to be done to ensure something like this is thread-safe and working optimally, since the last time re tried implementing this there were unexpected behaviors and crashes.

**Comment by jiangdashao** [comment]
Some operations require operating entities, I don’t think it’s feasible to implement asynchronous
