### ISSUE TITLE
[INCOMPATIBILITY] Custom Jumppads

### ISSUE THREAD

**Issue by JoseLu1200** [jiangdashao/Matrix-Issues#1857]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Incompatible plugin**: Custom Jumppads (https://www.spigotmc.org/resources/custom-jumppads-1-8-1-16.44876/)
**Verbose messages (or) console errors**: 
- JoseLu1200 tried to not take knockback | Velocity | 1/3
- JoseLu1200 tried to not take knockback | Velocity | 2/3
- User JoseLu1200 has disconnected, reason: ?AntiCheat?>> Velocity/Anti-Knockback

**How/when does this happen**: When you use one jumppad, i have tested it with an golden pressure plate, POWER: 15 and ANGLE: 45
**Video of incompatibility**: https://imgur.com/3mntlXy
**Other information**: You have to be jumping in the jumppad approximately 1 minute and it kicks you

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/zndzHVh3

**Comment by jiangdashao** [comment]
Do you know what is the "verbose message"? You didn't provide the verbose messages

**Comment by JoseLu1200** [comment]
Yes, they are enumerated:
- JoseLu1200 tried to not take knockback | Velocity | 1/3
- JoseLu1200 tried to not take knockback | Velocity | 2/3
- User JoseLu1200 has disconnected, reason: ?AntiCheat?>> Velocity/Anti-Knockback

**Comment by jiangdashao** [comment]
damn, "/matrix verbose"

**Comment by JoseLu1200** [comment]
Ok, sorry, here are:
https://imgur.com/a/Ds8u0Fy

**Comment by jiangdashao** [comment]
I only get velocity false positive
