### ISSUE TITLE
[FP] Fly with pearls

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1859]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(17:59:16) assasin541 Fly | suspicious movement:0.412 predict:-0.483/-0.155 air_t:12 s:false tag:m1 (+15) | vl:15 ping:0 tps:19.97 component: fly.main
(17:59:16) assasin541 Fly | suspicious movement:0.0 predict:0.326 vel:-0.304 air_t:12 tag:m4 (+10) | vl:25 ping:0 tps:19.97 component: fly.main
(17:59:19) assasin541 Fly | suspicious movement:0.412 predict:-0.483/-0.155 air_t:12 s:false tag:m1 (+15) | vl:40 ping:0 tps:19.98 component: fly.main
(17:59:21) assasin541 Fly | suspicious movement:0.412 predict:-0.078/-0.231 air_t:12 s:false tag:m1 (+15) | vl:55 ping:0 tps:20.0 component: fly.main
(17:59:21) assasin541 Fly | suspicious movement:0.0 predict:0.326 vel:-0.377 air_t:12 tag:m4 (+10) | vl:65 ping:0 tps:20.0 component: fly.main
(17:59:25) assasin541 Fly | suspicious movement:-0.024 predict:-0.228 lm:-0.152 hard_pred:-0.228 sev_pred:0.083 air_t:8 fall_t:3 g:-- tag:gn (+5) | vl:70 ping:51 tps:19.98 component: fly.main
(17:59:36) assasin541 Fly | suspicious movement:0.412 predict:-0.483 vel:-0.155 air_t:12 tag:m4 (+10) | vl:80 ping:52 tps:19.99 component: fly.main
(17:59:36) assasin541 Fly | suspicious movement:0.0 predict:0.326 vel:-0.304 air_t:12 tag:m4 (+10) | vl:90 ping:52 tps:19.99 component: fly.main
(17:59:49) assasin541 Fly | suspicious movement:0.412 predict:-0.078/-0.231 air_t:12 s:false tag:m1 (+15) | vl:65 ping:50 tps:20.0 component: fly.main
(17:59:54) assasin541 Fly | suspicious movement:0.412 predict:-0.483/-0.155 air_t:12 s:false tag:m1 (+15) | vl:80 ping:50 tps:19.97 component: fly.main
(17:59:54) assasin541 Fly | suspicious movement:0.0 predict:0.326 vel:-0.304 air_t:12 tag:m4 (+10) | vl:90 ping:50 tps:19.97 component: fly.main
(17:59:59) assasin541 Fly | suspicious movement:0.0 predict:-0.228 vel:-0.155 air_t:12 tag:m4 (+10) | vl:100 ping:51 tps:20.0 component: fly.main

**How/when does this happen**: when you have plugin that allow riding ender pearls (you sit on thrown enderpearl) it will detect fly which leads to kicks
**Other information**: -

## Configuration Files
**Link to checks.yml file**: -

**Comment by Wentoxic** [comment]
This is more of an incompatibility problem. Create an issue with the "INCOMPATIBILITY" tag and fill out the template there.

**Comment by assasin541** [comment]
@Wentoxic I think this issue is enough, but we will see. :)

**Comment by jiangdashao** [comment]
After testing, no false positives were found.

**Comment by assasin541** [comment]
@jiangdashao 1.8 + viaversion and 1.15 client's version for example?
