### ISSUE TITLE
Matrix Disabler (NO JOKE) [BYPASS] 

### ISSUE THREAD

**Issue by True-cc** [jiangdashao/Matrix-Issues#186]
## Basic Information
**Hacked client**: LiquidBounce, I used a script.
**Cheat that bypassed**: All of them. :/
**Screenshot of cheat settings**: vid?
**Video of bypass**: https://youtu.be/F8a7VLhUR4Q

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**: 

# Server Infomation
**Server Version**: Running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
You are 1403 version(s) behind
**Matrix Version**: 1.8.7 model 5 (?)
**ProtocolLib Version**: 4.4.0

**Comment by True-cc** [comment]
https://pastebin.com/cekyifrY checks.yml
https://pastebin.com/D4eTiGjh config.yml

**Comment by ignPerformance** [comment]
Any errors in console? Also how exactly did you disable it?
To me it looks like it just randomly happened.

**Comment by True-cc** [comment]
Same here. No errors in console. I'll give u code in discord.
