### ISSUE TITLE
[FP] Fly in block

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1866]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(04:06:35) assasin541 Fly | suspicious movement:-0.024 predict:-0.228 lm:-0.152 hard_pred:-0.228 sev_pred:-0.155 air_t:8 fall_t:3 g:-- tag:gn (+5) | vl:5 ping:54 tps:20.0 component: fly.main
(04:07:10) assasin541 Fly | suspicious movement:-0.386 predict:-0.231 lm:-0.155 hard_pred:-0.231 sev_pred:-0.231 air_t:2 fall_t:1 g:-- tag:gn (+5) | vl:5 ping:48 tps:20.0 component: fly.main
(04:07:10) assasin541 Fly | suspicious movement:0.386 predict:0.17 vel:-0.304 air_t:3 tag:vt (+5) | vl:10 ping:48 tps:20.0 component: fly.main
(04:07:10) assasin541 Fly | suspicious movement:-0.234 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-0.517 air_t:6 fall_t:1 g:-- tag:gn (+5) | vl:15 ping:48 tps:20.0 component: fly.main
(04:07:10) assasin541 Fly | suspicious movement:-0.231 predict:-0.307 lm:-0.234 hard_pred:-0.307 sev_pred:-0.585 air_t:7 fall_t:2 g:-- tag:gn (+5) | vl:20 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.905 air_t:12 tag:m4 (+10) | vl:30 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.155 air_t:12 tag:m4 (+10) | vl:40 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.231 air_t:12 tag:m4 (+10) | vl:50 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.155 vel:-0.377 air_t:12 tag:m4 (+10) | vl:60 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.447 air_t:12 tag:m4 (+10) | vl:70 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.155 vel:-0.652 air_t:12 tag:m4 (+10) | vl:80 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.717 air_t:12 tag:m4 (+10) | vl:90 ping:48 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.155 vel:-0.844 air_t:12 tag:m4 (+10) | vl:100 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.905 air_t:12 tag:m4 (+10) | vl:110 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.966 air_t:12 tag:m4 (+10) | vl:120 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.155 vel:-0.155 air_t:12 tag:m4 (+10) | vl:130 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.231 air_t:12 tag:m4 (+10) | vl:140 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.304 air_t:12 tag:m4 (+10) | vl:150 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.155 vel:-0.447 air_t:12 tag:m4 (+10) | vl:160 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.517 air_t:12 tag:m4 (+10) | vl:170 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.078 vel:-0.585 air_t:12 tag:m4 (+10) | vl:180 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.078 predict:-0.155 vel:-0.717 air_t:12 tag:m4 (+10) | vl:190 ping:47 tps:20.0 component: fly.main
(04:07:11) assasin541 Fly | suspicious movement:0.0 predict:-0.002 vel:-0.781 air_t:12 tag:m4 (+10) | vl:200 ping:47 tps:20.0 component: fly.main

**How/when does this happen**: when you get knocked and in the air someone will place a block in you it will bug you in this block which leads to unwanted kicks, it's hard to jump in block that someone placed it's easier to get knocked in it
**Other information**: viaversion, any client's version

## Configuration Files
**Link to checks.yml file**: default checks.yml

**Comment by jiangdashao** [comment]
Please record a video

**Comment by assasin541** [comment]
@jiangdashao test it by yourself, even with a video you say that you can't reproduce so

**Comment by assasin541** [comment]
@jiangdashao is it fixed?

**Comment by jiangdashao** [comment]
no

**Comment by assasin541** [comment]
@jiangdashao why not? That's a big bug.
