### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by PlesCZ** [jiangdashao/Matrix-Issues#1867]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Paper
**Error(s) found in console**:  https://pastebin.com/tEdmmsnQ
**How/when does this happen**: It just kick me out
**Other information**: Nothing

## Configuration Files
**Link to checks.yml file**:  https://git.disroot.org/lampenit/MatrixConfig/raw/commit/edbc420a3e47209b3bd3d3f32a5999097ba8ecea/checks-free.yml
**Link to config.yml file**: Its default

**Comment by PlesCZ** [comment]
`[INFO] PLESOP lost connection: §7[§bMatrix§7]§r KillAura

[INFO] [Matrix] [AsyncPool] Find a error when run a async task, exception type: java.lang.IllegalArgumentException

[WARNING] java.lang.IllegalArgumentException: cannot send packets to a closed channel

[WARNING] at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)

[WARNING] at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651)

[WARNING] at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640)

[WARNING] at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403)

[WARNING] at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786)

[WARNING] at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740)

[WARNING] at me.rerere.matrix.fa.t(Unknown Source)

[WARNING] at me.rerere.matrix.ca.j(Unknown Source)

[WARNING] at me.rerere.matrix.ca.e(Unknown Source)

[WARNING] at me.rerere.matrix.ca.t(Unknown Source)

[WARNING] at me.rerere.matrix.ca.e(Unknown Source)

[WARNING] at me.rerere.matrix.iA$KC.run(Unknown Source)

[WARNING] at me.rerere.matrix.P.run(Unknown Source)

[WARNING] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)

[WARNING] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

[WARNING] at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)

[INFO] PLESOP left the game.

[INFO] [Matrix] player PLESOP was kicked because of cheating!

[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[WARNING] at java.lang.Thread.run(Thread.java:813)

[WARNING] handleDisconnection() called twice `

**Comment by jiangdashao** [comment]
you are wrong, not error kicks you, the truth is, you got kicked, then cause the error
