### ISSUE TITLE
[BYPASS] Interact attack

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#1868]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.1 paper-89
**Hacked client**: Aristois, probably irrelevant in this case, though
**Link to hacked client**: https://aristois.net/
**Cheat that bypassed**: Attack through blocks
**Video of bypass**: https://www.youtube.com/watch?v=D8oRgcAF6mE
**Other information**: Inconsistent, seems to only work from some positions/angles, perhaps a bug

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
This is because you are not aiming at the villagers. The interaction check is based on the player’s line of sight to raytrace the block. If you do not aim at the villagers, then the interaction check will not work, and if it deviates a little bit, the hitbox check will not be triggered.
