### ISSUE TITLE
PaperSpigot 1.8.8 Phase [FP] 

### ISSUE THREAD

**Issue by DarkoGNU** [jiangdashao/Matrix-Issues#187]
Yeah, the "plugin incompatibility" I was going to report. It appears to be a general issue, however.
## Basic Information
**Verbose message(s)**: [click](https://hastebin.com/ohofahixav.sql)
**How/when does this happen**: When stepping on slabs. Possibly other blocks, but this was tested with a few players on a server and only this block got reported.
**Video of false positive**: [YouTube](https://www.youtube.com/watch?v=Xizh-6vARjw)

## Configuration Files
**Link to checks.yml file**: [click](https://hastebin.com/rugocarehi.coffeescript)
**Link to config.yml file**: [click](https://hastebin.com/ohozihawaz.coffeescript)

# Server Infomation
**Server Version**: Latest PaperSpigot 1.8.8, optimized using [this guide.](https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/)
**Matrix Version**: 1.8.8
**ProtocolLib Version**: 4.4.0
**Server log**: [here](https://hastebin.com/afovisuses.md)

**Comment by jiangdashao** [comment]
I can't reproduce the false positive
You can add "Step" to exclude list

**Comment by DarkoGNU** [comment]
Don't give up so fast, lol 
I swear, it happens on latest PaperSpigot 1.8.8, without ANY changes in config and only 3 plugins - latest Matrix and latest ProtocolLib from SpigotMC, Java 8u202. Install WorldEdit and import this schematic: [click](https://drive.google.com/open?id=1elBCB8bLByRaLeEOr2CtTTrvpsE3xD3d)
