### ISSUE TITLE
[FP] KillAura (direction)

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#1873]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: https://pastebin.com/mQ2Wc6m0
**How/when does this happen**: during a combat
**Video of false positive**: https://youtu.be/jAhrLkCMDPk
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default

**Comment by Crowraw** [comment]
Why is down left in the cornor "Killaura" written? Are you cheating?

**Comment by jiangdashao** [comment]
some client's movement is different

**Comment by BestMark** [comment]
@Crowraw, this is autosprint :D

**Comment by MrEDok** [comment]
I doubt it "autosprint" it litterly say [Killaura] toggled
Recommend to use a mojang vanilla client to test it
