### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by mkwwmka5** [jiangdashao/Matrix-Issues#1874]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper-1.15.2
**Verbose messages**: 玩家使用附魔了激流的三叉戟时，会误报Fly检测
**How/when does this happen**: 玩家使用附魔了激流的三叉戟时，会误报Fly检测
**Video of false positive**: no
**Other information**: 
![image](https://user-images.githubusercontent.com/59493751/88480950-91199c80-cf8b-11ea-8478-12ece3a0dfb9.png)

## Configuration Files
**Link to checks.yml file**: https://github.com/Encode42/MatrixConfig

**Comment by jiangdashao** [comment]
录个视频

**Comment by mkwwmka5** [comment]
> 录个视频

稍等

**Comment by mkwwmka5** [comment]
> 录个视频

Bandicam坏了
大概触发的时候就是使用附魔了激流三的三叉戟
向天或者其他地方使用时会触发fly.main项检测

**Comment by mkwwmka5** [comment]
> 录个视频

还有一点，是按住w键与ctrl时触发
