### ISSUE TITLE
[BYPASS] Velo LiquidBounce AAC

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1875]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**liquid**: 
**Link to hacked client**: 
**Velocity**: 
**https://streamable.com/6xv106**: 
**It starts flagging when hitting fast, but still just sometimes. Maybe you can fix that :D**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
the velocity check need several ticks to collect data, if you hit fast -> matrix can't collect data
