### ISSUE TITLE
[BYPASS] Velocity Bypass

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1876]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**LB**: 
**Link to hacked client**: 
**Velo**: 
**https://streamable.com/788rn3**: 
**0 Velocity**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
If you stand under a block, or stand near a block that can block your movement, the velocity check will not work

**Comment by Crowraw** [comment]
Well Im not under a block.
![image](https://user-images.githubusercontent.com/65922503/88486756-45adc100-cf80-11ea-9de8-6fd739e04850.png)

**Comment by Crowraw** [comment]
![image](https://user-images.githubusercontent.com/65922503/88486765-53634680-cf80-11ea-902a-66c449992aa2.png)

**Comment by Hyronymos1337** [comment]
„or stand near a block“
