### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by JasonHorkles** [jiangdashao/Matrix-Issues#1877]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper-115 (MC: 1.16.1)
**Verbose messages**: in video
**How/when does this happen**: clicking a shulker box while standing on it with no room to move up will cause the player to drop into it. Exiting the shulker box will trigger a fly false positive
**Video of false positive**: https://youtu.be/HYPF_NmaV_Q
**Other information**: n/a

## Configuration Files
**Link to checks.yml file**:
https://hasteb.in/wiwagofu.yaml

**Comment by LaserSlimeHD** [comment]
I don't think that this is gonna get fixed. It's a vanilla bug.

**Comment by JasonHorkles** [comment]
> I don't think that this is gonna get fixed. It's a vanilla bug.

I don't recall it having the false positive before tho
