### ISSUE TITLE
[BYPASS] 0 Velo

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1878]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**Lb**: 
**Link to hacked client**: 
**0 Velo**: 
https://streamable.com/ashh64
**Just tell me if you need an other Vid. Ik its not 0/0 Velo, but almost.**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
did you test it in a clean server? Are you sure it’s not the problem with your configuration file or your server has been modified the knockback?

**Comment by Crowraw** [comment]
No, we use the premium standard config as I know.

**Comment by Crowraw** [comment]
We dont modify the server kb

**Comment by jiangdashao** [comment]
Because you continuously received the knockback, but the response check takes a certain time to wait for the player to respond to the knockback

**Comment by Crowraw** [comment]
I will test it today.

**Comment by Crowraw** [comment]
Alright doesnt work when hitting slowly. Still it should also work when fast hitting one.
