### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#1879]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  PaperSpigot 1.8.8
**Verbose messages**: https://pastebin.com/raw/3rxYDiA8
**How/when does this happen**: When jumping on the edge of the block.
**Video of false positive**: https://www.youtube.com/watch?v=xWwt5vlhshE

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/raw/RXXuudvP

**Comment by LaserSlimeHD** [comment]
This is a ViaVersion compatibility issue. They changed the player sneaking hitbox in 1.14 to make the player able to sneak under slabs. This doesn't happen if the server is on 1.14+. The anticheat doesn't check for the client version.

**Comment by jiangdashao** [comment]
it can't be fixed, it's a cross-version bug, The 1.8 server-side prevents players with higher versions from moving like this because 1.8 has a higher collision box
