### ISSUE TITLE
Impact 4.6 various cheats [BYPASS] 

### ISSUE THREAD

**Issue by DarkoGNU** [jiangdashao/Matrix-Issues#188]
## Basic Information
**Hacked client**: [Impact 4.6 for MC 1.12.2](https://impactdevelopment.github.io)
**Screenshot of cheat settings**: [screens](https://imgur.com/a/ypXhHah)

## Configuration Files
**Link to checks.yml file**: [hastebin](https://hastebin.com/sewijijugi.coffeescript)
**Link to config.yml file**: [hastebin](https://hastebin.com/uwiyurutok.coffeescript)

# Server Infomation
**Server Version**: git-Paper-1612 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (default configs), these cheats (at least most of them) also worked on TacoSpigot 1.8.8
**Matrix Version**: 1.8.8
**ProtocolLib Version**: 4.4.0

## Working pretty nice:
**Cheat that bypassed**: Spider (2 blocks), Riding (no saddle, astonishing Entity Step, no violations when trying to swim), New Chunks (shows new chunks - not sure if it is possible to fix), HitBox, Aimbot (only when avoiding fast sweeps - usually good when fighting one mob/player), Speedhack (Strafe and Boost)
**Video of bypass**: [YouTube](https://www.youtube.com/watch?v=eYIut7gcvTk&feature=youtu.be)
**Matrix log**: [hastebin](https://hastebin.com/uripomugig.sql)
**Server log**: [hastebin](https://hastebin.com/koyeyupeno.md)

## Mostly working:
**Cheat that bypassed**: Timer (a lot of violations, but a good speedhack, slight rubberbanding after a while), AntiHunger (effective, violations when jumping)
**Video of bypass**: [YouTube](https://www.youtube.com/watch?v=e36ZqYaXgtM&feature=youtu.be), AntiHunger - [YouTube](https://www.youtube.com/watch?v=4XmawYHkdsw&feature=youtu.be)
**Matrix log**: [hastebin](https://hastebin.com/cilehequhu.sql)
**Server log**: [hastebin](https://hastebin.com/gelilamuzu.md)
**Antihunger**: [server](https://hastebin.com/voxepecovi.md), [Matrix](https://hastebin.com/xexetutihu.sql)

**Comment by jiangdashao** [comment]
1. Speed strafe won't make you faster
2. Speed(Boost) bypassed
3. Entity Step bypassed
4. Spider doesn't bypass, it just hasn't setback you
5. You should use AimBot cheat with movement, not walk straightly
6. HitBox check not strict enough, but it not important

**Comment by DarkoGNU** [comment]
The point with Strafe was that it allows to walk with running speed (no hunger loss). Minor cheat, but still a little, unfair advantage. Effective AntiHunger is similar, but a lot worse - you can't jump. Spider - climbing two blocks is still a little advantage. And with Riding you can ride a horse without saddle. And New Chunks makes finding player bases easier.
Yeah, mostly little, not very important cheats, but fixing them could still improve the anticheat.
I don't know why I reported timer (it could be blocked faster btw, like other speed hacks) and Aimbot :P

**Comment by jiangdashao** [comment]
1. Speed/Spider/EntityStep bypass is fixed
2. You haven't bypass AimBot check, because you just walk straightly, It doesn't need "Aim". Please try it with left/right movement
