### ISSUE TITLE
[BYPASS] Step (2 block)

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#1886]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-0509002-7c03d25 (MC: 1.16.1)
**Hacked client**: Sigma
**Link to hacked client**: https://sigmaclient.info
**Cheat that bypassed**: Step
**Video of bypass**: https://youtu.be/uCGSUvMEWgE
**Other information**: Also works with 1.5 blocks and 2.5 blocks. Works better with only one flying block. 

Sorry for spamming issues. I've tested this anticheat for 3 days now and now i'm reporting every bypass I found.

**Comment by jiangdashao** [comment]
it can be detected, just need some time
