### ISSUE TITLE
[FP] Placing falling block false positive

### ISSUE THREAD

**Issue by MrEDok** [jiangdashao/Matrix-Issues#1887]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.1
**Verbose messages**: https://pastebin.com/dB7W2Ze0
**How/when does this happen**: spam place sand/gravel and let it fall
**Video of false positive**: check discord
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by LaserSlimeHD** [comment]
Can confirm. You have to do it for a very long time. Then it will flag you for noswing.
