### ISSUE TITLE
[REQUEST] Calculate velocity and do not deactivate the speed / fly check

### ISSUE THREAD

**Issue by Wentoxic** [jiangdashao/Matrix-Issues#1889]
**What features/checks do you need?:**
Please calculate the velocity and do not simply deactivate the fly / speed check, because the SmoothReverse Velocity from LiquidBounce bypasses and there are Hurttime Longjumps.

**Comment by jiangdashao** [comment]
I didn't deactivate the movement check, It's just that the movement detection becomes weaker when the player gets knockback

**Comment by jiangdashao** [comment]
if you find any bypass, report it.

**Comment by Wentoxic** [comment]
one of many that work through it
https://www.youtube.com/watch?v=cgGKYYmRKIo
