### ISSUE TITLE
Bot detection [REQUEST] 

### ISSUE THREAD

**Issue by DarkoGNU** [jiangdashao/Matrix-Issues#189]
It's a thing that I have never seen. Impact has Baritone. It allows walking automatically, and it is very effective. Similarly, mining - I think that Baritone is better than any player, both with x-ray and in legit mode (when one target ore is enough). It looks like Baritone can now [build](https://github.com/cabaletta/baritone/blob/master/USAGE.md) from schematics.
Is it possible to detect bots and stop/kick them, or just alert admins?

**Comment by jiangdashao** [comment]
I won't add this check
