### ISSUE TITLE
[BYPASS] AirJump sometimes works for 2 Blocks

### ISSUE THREAD

**Issue by Wentoxic** [jiangdashao/Matrix-Issues#1890]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.7 - 1.16
**Hacked client**: LiquidBounce
**Link to hacked client**: 
**Cheat that bypassed**: AirJump
**Video of bypass**: https://www.youtube.com/watch?v=DIUNyUkoCeY
**Other information**: only works sometimes

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
not important

**Comment by Wentoxic** [comment]
so a 2 block step bypass is not important for you? It shouldn't be too difficult to detect whether a player is jumping in midair

**Comment by MrEDok** [comment]
It detect if u look at the video it show notification at the end

**Comment by Wentoxic** [comment]
it is clearly detected, but as long as you are not setbacked directly to the floor, it is a bypass for me

**Comment by MrEDok** [comment]
Are you running in ghostmode?
High setback violation?

**Comment by Wentoxic** [comment]
This is the Loyisa Test Server which should have the default config without ghost mode. If you do the setback violation under 5 you get a lot of legit flags just to fix an AirJump which is not that difficult to fix in matrix directly
