### ISSUE TITLE
[BYPASS] AAC  Velo Bypass

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1893]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**Lb**: 
**liquidbounce.net**: 
**Velo**: 
** https://streamable.com/ucpc9m **: 
** Im sorry for the random video issues, but idk why it is so**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
it can't bypass

**Comment by Crowraw** [comment]
lol I just showed you, that it works xd
