### ISSUE TITLE
[BYPASS] FastPlace/FastBeak bypass

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1894]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst 6.32.1 (MC version 1.12.2)
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: FastBreak [Instant] and FastPlace
**Video of bypass**: https://streamable.com/thdz6e
**Other information**: FastBreak only works on some blocks like sand, dirt and gravel.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Some legit players can place with this speed

**Comment by AMDBartek** [comment]
What about the FastBreak?

**Comment by jiangdashao** [comment]
You didn't bypass the fast break check

**Comment by AMDBartek** [comment]
Ok, I just realized that sand, dirt and gravel break at the same speed even with FastBreak [Instant] enabled.
