### ISSUE TITLE
[INCOMPATIBILITY] BUG BLOCK

### ISSUE THREAD

**Issue by pigeonmal** [jiangdashao/Matrix-Issues#1897]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper Spigot 1.8
**Incompatible plugin**: Spigot or my Plugin
**Verbose messages (or) console errors**: no
**How/when does this happen**: Place block in my body, with graphical bug
**Video of incompatibility**: https://youtu.be/XZH6qzneIhg
**Other information**: I didn't Have this bug before, matrix.

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
There's no evidence that it's related to matrix
