### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1898]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Sigma 5
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: Fly (Spartan with GroundSpoof)
**Video of bypass**: https://streamable.com/li15gr
**Other information**: Matrix will damage the player if they fly more than 2 blocks above the ground but they can still fly while taking damage with no problem

## Configuration Files
**Link to checks.yml file**: Default (The only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by enderboydiscord** [comment]
Its not important its like if ur jumping but u dont get down its maybe faster but REALY blatant
