### ISSUE TITLE
Inv move and velocity [FP] 

### ISSUE THREAD

**Issue by True-cc** [jiangdashao/Matrix-Issues#190]
## Basic Information
**Verbose message(s)**: idk it was on test server
**How/when does this happen**: when bouncing on slimeblock. In a test server. It happens on my server too,
**Video of false positive**: https://youtu.be/oAxY0idZQeA

## Configuration Files
**Link to checks.yml file**: idk
**Link to config.yml file**: idk

# Server Infomation
**Server Version**: idk ask tree
**Matrix Version**: 1.8.8
**ProtocolLib Version**: idk ask tree

**Comment by jiangdashao** [comment]
I only detect the anti-knockback with very small knockback distance

But the InventoryMove&Speed check has false positive

**Comment by True-cc** [comment]
then pls make the velocity check better pls pls pls pls pls pls pls

**Comment by True-cc** [comment]
like aac's but idk better. pls pls pls pls pls pls pls pls pls I would like an anticheat with a decent velocity check.

**Comment by jiangdashao** [comment]
I will fix the InventoryMove check FP in the next update
Velocity check improvement is hard, I will try to do it, but not now
