### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by DayViper** [jiangdashao/Matrix-Issues#1903]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version*1.8*: 
**Hacked client*LB*: 
**Link to hacked client*https://liquidbounce.net/*: 
**Cheat that bypassed*Fly*: 
**Video of bypass*https://www.youtube.com/watch?v=kiUfyvKBRF0*: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
I can't access the file

**Comment by DayViper** [comment]
That's what you can access. https://drive.google.com/file/d/16DHPSvnogyd3ypZgfAUySfjQhD6qANL1/view

**Comment by jiangdashao** [comment]
server version?

**Comment by DayViper** [comment]
Yes

**Comment by jiangdashao** [comment]
default hack setting?

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/89312533-f49d7b80-d6a9-11ea-9406-06b6aec09117.png)
?

**Comment by DayViper** [comment]
Probably yes

**Comment by jiangdashao** [comment]
can't bypass...

**Comment by DayViper** [comment]
To use this fly you need to turn on the safewalk and sprint, go to the edge of the block to pinch w and simultaneously with the jump to turn on the fly.

**Comment by jiangdashao** [comment]
Still can't: https://streamable.com/6gxdqy

**Comment by ItsDmitriy2018** [comment]
> Still can't: https://streamable.com/6gxdqy

Try place some blocks and then fly

**Comment by jiangdashao** [comment]
> > Still can't: https://streamable.com/6gxdqy
> 
> Try place some blocks and then fly

same
