### ISSUE TITLE
[BYPASS] Boatfly

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#1905]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)
**Hacked client**: Inertia
**Link to hacked client**: https://inertiaclient.com
**Cheat that bypassed**: BoatFly
**Video of bypass**: https://youtu.be/HQpxkMb0eaA
**Other information**: This doesn't work 100% at a time, if it doesn't work, try spoofing your on ground state with NoFall or AntiHunger. Or try spamming spacebar instead of holding it down.

**Comment by jiangdashao** [comment]
can't reproduce
