### ISSUE TITLE
[BYPASS] Boat Phase

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#1906]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)
**Hacked client**: Inertia
**Link to hacked client**: https://inertiaclient.com
**Cheat that bypassed**: Boat Phase
**Video of bypass**: https://youtu.be/y5gvauD6IqU
**Other information**: Not working 100% at a time, but it works almost everytime, if you go through smaller walls or non solid blocks like glass or slabs.

**Comment by jiangdashao** [comment]
can't fix

**Comment by LaserSlimeHD** [comment]
> 
> 
> can't fix
Why not?
