### ISSUE TITLE
[BYPASS] Scaffold

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1907]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: Scaffold (called "ScaffoldWalk")
**Video of bypass**: https://streamable.com/h6t410
**Other information**: Only bypasses the scaffold check when sneaking or walking, when you sprint it gets detected

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
it's pretty legit, I think it can't be detected

**Comment by AMDBartek** [comment]
Ah, I see, but there would be no harm in trying to implement/improve a check to detect it though.

**Comment by jiangdashao** [comment]
It’s not that I don’t want to check it, it hardly has any "features"

**Comment by AMDBartek** [comment]
Ah ok, I understand

**Comment by jiangdashao** [comment]
nvm, I found a feature~
