### ISSUE TITLE
[BYPASS] KillAura

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1908]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: KillAuraLegit
**Video of bypass**: https://streamable.com/elbgaw
**Other information**: Default KillAuraLegit settings fully bypass the KillAura check, sometimes Matrix will spawn an NPC but it doesn't get hit and the VL never gets too high.

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/89529812-ed987980-d81f-11ea-9af2-c3a5ce034ce8.png)

**Comment by AMDBartek** [comment]
Should I post verbose message output?

**Comment by jiangdashao** [comment]
do it in survival mode, can't bypass

**Comment by AMDBartek** [comment]
@jiangdashao It does bypass the KillAura check if you turn off the `Use Attack Cooldown As Speed` option In the KillAuraLegit settings. No matter what gamemode, you might have to lower reach, but it still bypasses the check.

**Comment by Hyronymos1337** [comment]
With those settings legit players are better as you

**Comment by AMDBartek** [comment]
Not on a server with 1.8 combat.
