### ISSUE TITLE
[BYPASS]  Aristois ElytraFlight let's users boost/glide super fast and no fireworks get consumed

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#191]
## Basic Information
**Hacked client**:  Aristois
**Cheat that bypassed**:  ElytraFlight
**Screenshot of cheat settings**:  (not available)
**Video of bypass**:  https://clips.twitch.tv/GlutenFreeFlaccidWaspPastaThat

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

# Server Information
**Server Version**:  Spigot 1.13.2 
**Matrix Version**:  1.8.8
**ProtocolLib Version**: 4.4.0

User can boost themselves with no Fireworks and Glide super fast with ElytraFlight

**Comment by jiangdashao** [comment]
Fixed
