### ISSUE TITLE
[ERROR] /matrix reload doesn't get config from the cloud

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1912]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: x
**Error(s) found in console**: x
**How/when does this happen**: 

Reload:
[Matrix] Reloading Matrix...
[Matrix] Enabled 19 checks, Disabled 1 checks
[Matrix] (Phase#Debug) Exclude: CARPET
[Matrix] Loaded all configuration files
[Matrix] Matrix reloaded.

Start:
[0;36;1m[Matrix] [0;37;22mFetching checks.yml from cloud...[m
[0;37;22mSucceed load checks.yml from: https://x.net/checks.yml[m
[0;36;1m[Matrix] [0;37;22mEnabled 19 checks, Disabled 1 checks[m
[0;36;1m[Matrix] [0;37;22m(Phase#Debug) Exclude: CARPET[m
[0;36;1m[Matrix] [0;37;22mLoaded all configuration files[m
[0;36;1m[Matrix] [0;37;22mLoaded 96 ML models[m
[0;36;1m[Matrix] [0;37;22mScanning outdated log files....[m
[0;36;1m[Matrix] [0;37;22mDeleted 1 outdated log files![m
**Other information**: x

## Configuration Files
**Link to checks.yml file**: x
**Link to config.yml file**:x

**Comment by assasin541** [comment]
@jiangdashao why did you close this?

**Comment by jiangdashao** [comment]
it's not a bug, cloud-config is designed for a larger network, like minigame server. Imagine you will enter a certain minigame server and reload it?

**Comment by assasin541** [comment]
@jiangdashao So if you have checks from the cloud and then do /matrix reload, how can you change checks.yml? It should reload from the cloud.

**Comment by Hyronymos1337** [comment]
The MiniGame Server downloads at the startup the cloud config

**Comment by assasin541** [comment]
How to reload config during uhc game for example if you have to change 1 thing quickly?

**Comment by assasin541** [comment]
@jiangdashao @Hyronymos1337 How to reload config during uhc game for example if you have to change 1 thing quickly?

**Comment by assasin541** [comment]
@Green-Sickness @jiangdashao @Hyronymos1337 /matrix reload doesn't reload config from the cloud.

**Comment by Green-Sickness** [comment]
@assasin541 Have you tried to use plugman to reload Matrix?

**Comment by assasin541** [comment]
@Green-Sickness I don't think this is a good idea.

**Comment by jiangdashao** [comment]
Matrix obtain cloud configuration in the main thread because some checks need to load in the main thread, but if I make `/matrix reload` obtain cloud configuration too, it will freeze server

**Comment by assasin541** [comment]
@jiangdashao test new versions better and don't share bugged versions containing many false positives
