### ISSUE TITLE
[BYPASS] WaterFly/Jesus

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1913]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: Fish
**Video of bypass**: https://streamable.com/mzm042
**Other information**: Sometimes it will flag you for Jesus but it never kicks you

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by Maximillus** [comment]
This makes you any faster in the water? I dont think so..

**Comment by jiangdashao** [comment]
It just makes the user more freedom to control the movement up and down, I will not fix it
