### ISSUE TITLE
[FP] Horses jump false positive

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1916]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: its in video
**How/when does this happen**: jumping with a horse 90% charge for some reason flag entity fly, very strange.
**Video of false positive**: https://streamable.com/cso5cs
**Other information**: 

## Configuration Files
**Link to checks.yml file**: matrix default

**Comment by jiangdashao** [comment]
I can't fix it, keep jumping in the same place will cause the horse not to fall to the ground sometimes, and the matrix cannot reset the horse’s air time
