### ISSUE TITLE
[BYPASS] KillAura

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1919]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: KillAuraLegit
**Video of bypass**: https://streamable.com/elbgaw
**Other information**: Really sorry for the double issue but #1908 was closed saying that KillAuraLegit does not bypass Matrix but KillAuraLegit does indeed bypass Matrix's KillAura check. So I am making this issue to describe what settings you need for KillAuraLegit to bypass Matrix. **The server runs on 1.12.2 but has 1.8 combat mechanics (this is important because of the** `Use Attack Cooldown as Speed` **setting (this setting needs to be off)! You also need to be using a good weapon, if you are using your bare hands you will need to lower the speed.**
**KillAuraLegit settings that bypass Matrix**: https://i.imgur.com/8gKni7d.png, https://i.imgur.com/ZwFCGK4.png (If those still don't bypass lower the speed even more)

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Because the 1.9+ battle is too slow, anti-cheating cannot collect enough information to detect this cheating. And I think the 1.9+ battle does not have any difficult skills, KillAuraLegit cannot bring any unfairness
