### ISSUE TITLE
[FP] [1.8.8] FastUse while eating Chorus Fruit

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#192]
## Basic Information
**Verbose message(s)**:  FastUse
**How/when does this happen**:  Eat Chorus Fruit
**Video of false positive**:  https://clips.twitch.tv/IcyLachrymoseDiamondHoneyBadger

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

# Server Information
**Server Version**: 1.13.2 Spigot 
**Matrix Version**:  1.8.8
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
This also happens when eating other food, just not consistently.

**Comment by jiangdashao** [comment]
I think it's caused by your high latency, because it's a packet base check
