### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1920]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Sigma 5
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: Fly (Spartan with GroundSpoof)
**Video of bypass**: https://streamable.com/34ihwp
**Other information**: This issue is similar to #1898, the fly is mostly patched although it still works if the player is on blocks like carpet, slabs, etc.

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
not important
