### ISSUE TITLE
[FP] velo

### ISSUE THREAD

**Issue by Crowraw** [jiangdashao/Matrix-Issues#1922]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ x] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**https://youtu.be/W72qDWS8JME**: 
**https://youtu.be/W72qDWS8JME**: 
**https://youtu.be/W72qDWS8JME**: 
****: 

## Configuration Files
**Link to checks.yml file**:

**Comment by Crowraw** [comment]
![image](https://user-images.githubusercontent.com/65922503/89666504-c5ba1c00-d8da-11ea-9b32-45cced10c550.png)

**Comment by jiangdashao** [comment]
Can YOU reproduce it?

**Comment by Crowraw** [comment]
Lol its just a screenshot from the video if you mean that. Yeah im getting also sometimes these flags

**Comment by jiangdashao** [comment]
Did you modify the velocity?

**Comment by Crowraw** [comment]
Nope. Its kind if a vannila server
