### ISSUE TITLE
Anti-Knockback / v-clip [BYPASS] 

### ISSUE THREAD

**Issue by ExceptedPrism3** [jiangdashao/Matrix-Issues#1926]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: WURST / WWE
**Link to hacked client**: 
**Cheat that bypassed**: Anti-Knockback / v-clip
**Video of bypass**: 
**Other information**: The Anti-Knockback doesn't detect it at all but the v-clip detects it but not always 

## Configuration Files
**Link to checks.yml file**: checks_minigame
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
1. You still didn't follow the issue template
2. You should report it in discord server first to make sure it's a real bug
