### ISSUE TITLE
[FP] Hitbox

### ISSUE THREAD

**Issue by EazyHacker** [jiangdashao/Matrix-Issues#1932]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Video of false positive**: https://youtu.be/9CV2z1bUOaA

**Comment by jiangdashao** [comment]
not important, you can increase the trace_back_length to prevent this
