### ISSUE TITLE
[BUG] matrix ping bug

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1933]
**What features/checks do you need?:**
in matrix ping calculation it using the transaction packet, but matrix make no effort to see whether the tranaction packet client is sending back is in reply to the one matrix sent or just an inventory click, this mean that if you are clicking in your inventory when matrix measures ping, it will give a player with 200 ping 4 ping which is not accurate. Matrix should check if the id/type etc of response is same as matrix sent.

**Comment by jiangdashao** [comment]
Transaction packet is very rare, clicking on the inventory will not send this packet
