### ISSUE TITLE
[FP] timer 

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1936]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
Maximilus failed BadPackets check | (timer) send 38 moving packets in 1033ms | tag: limit (+0) | vl:0 ping:45 tps:13.4 lp:19 component: net.timer
Maximilus failed BadPackets check | (timer) send 47 moving packets in 1042ms | tag: limit (+10) | vl:10 ping:36 tps:20.0 lp:37 component: net.timer

**How/when does this happen**: When the server has lag spike (from chunk add)
**Other information**: packet limit should be checked on netty threads so they not affected by lag. When player flags this even if they get 0 violation they get lagged (frozen) for some time.

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
already
