### ISSUE TITLE
[REQUEST] criticals

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1941]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
critical hit without correct jumping | tag: mini-jump | d:8.053157106076014E-4 (+5) - p:18 tps:20.0 lp:4 vl:5 - ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.0625 (+5) - ping:43 tps:20.0 lp:7 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.0625 (+5) - ping:29 tps:20.0 lp:2 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.20000004768371582 (+5) - ping:34 tps:20.0 lp:11 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.0625 (+5) - ping:34 tps:20.0 lp:2 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.034999999105934876 (+5) - ping:47 tps:20.0 lp:6 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.034999999105934876 (+5) - ping:96 tps:20.0 lp:1 vl:5 component: ka.critical.hop
critical hit without correct jumping | tag: mini-jump | d:0.0625 (+5) - ping:99 tps:20.0 lp:5 vl:5 component: ka.critical.hop
**How/when does this happen**: when a player is fighting (not sure what causing, lag maybe)
**Other information**: This cause matrix to not register hit, even when server has matrix on ghost mode. Make matrix ghost mode not cancel hit. and/or make first violation register but subsequent ones not.

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
I am not sure how it happens, so I will it don't cancel hits
