### ISSUE TITLE
[FP] aimassist T2

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1942]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: it is in video
**How/when does this happen**: If using optifine cinematic camera
**Video of false positive**: https://streamable.com/905406
**Other information**: Aimassist T2 does not seem to support optifine cinematic move delta, Aim t1 seems to. You may ask why this important but my suggestion on using aim check for bow aimbot, player will optifine zoom in with bow likely.

## Configuration Files
**Link to checks.yml file**: default matrix config

**Comment by jiangdashao** [comment]
can't fix

**Comment by Green-Sickness** [comment]
Its legit one line of code ask other devs if you dont know how to fix it
