### ISSUE TITLE
[BYPASS] Timer

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1943]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: Interta
**Cheat that bypassed**: Timer
**Video of bypass**: https://streamable.com/wf73wr
**Other information**: Toggle it on and off. Gives player +50% speed advantage

## Configuration Files
**Link to checks.yml file**: default matrix
**Link to config.yml file**:default matrix

**Comment by jiangdashao** [comment]
can't fix
