### ISSUE TITLE
[BYPASS] inventorymove/Extracarry

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1944]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: intertia
**Cheat that bypassed**: Inventory move and extra carry
**Video of bypass**: https://streamable.com/o0tgus
**Other information**: It flag when player sprint but player can just walk 

## Configuration Files
**Link to checks.yml file**: its default matrix config
**Link to config.yml file**: default matrix config

**Comment by jiangdashao** [comment]
not important
