### ISSUE TITLE
[REQUEST] add block.delay

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1945]
**What features/checks do you need?:**
Intertia has a hack called nobreakdelay, which allows players to break blocks faster: https://streamable.com/9c1hfg by remove minecraft block break delay. It gives 25% speed advantage, as much as some fastbreak but isn't detected, I think if there is easy way to detect then you should add the check yes.

**Comment by jiangdashao** [comment]
Matrix has this check before, but it's too unstable
