### ISSUE TITLE
[BYPASS] vape v4 

### ISSUE THREAD

**Issue by enderboydiscord** [jiangdashao/Matrix-Issues#1947]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  newest
**Hacked client**: Vape v4
**Link to hacked client**: vape.gg
**Cheat that bypassed**: everything in the screenshot 
**Video of bypass**: I dont have vape myself but a friend showed it
**Other information**: my friend can hack for 1 hour and then get banned

![](https://images-ext-2.discordapp.net/external/ul49z4NT2VKNqASLaOltMtRTjxZacJMPpEUFAOMD8OI/http/i.benny475.me/jycajhe8.png)
The screenshit couldnt download it and the config and check should be basic

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by enderboydiscord** [comment]
Killaura settings 

![](https://images-ext-1.discordapp.net/external/fuw2t08Vpyv_1QOUd4ickgwa5VV4dBO8a5uKo03NsZc/http/i.benny475.me/lh9zzkgw.png)

**Comment by Green-Sickness** [comment]
@enderboydiscord you should try godseye or kauri anticheat

**Comment by enderboydiscord** [comment]
@Green-Sickness stfu im talking abt matrix rn

**Comment by jiangdashao** [comment]
Legit Aura Enabled?
![image](https://user-images.githubusercontent.com/21152113/90308892-efe08f00-df15-11ea-94ca-3adaeb75d298.png)

**Comment by enderboydiscord** [comment]
Yes

**Comment by enderboydiscord** [comment]
If u want we can actually take this to dms on discord

**Comment by jiangdashao** [comment]
I will make hitbox check cancel player hits
