### ISSUE TITLE
[BYPASS] NoslowDown

### ISSUE THREAD

**Issue by ChineseCookie** [jiangdashao/Matrix-Issues#1948]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Liquidbounce
**Link to hacked client**:[https://forums.ccbluex.net/](https://forums.ccbluex.net/)
**Cheat that bypassed:NoslowDown**: 
**Video of bypass：nope**: 
**Other information**: 
Liquidbounce JS Code:
`            if (
                (packetMode.get() == "AAC" && timer.hasTimePassed(80)) ||
            ) {
                switch (event.getEventState().getStateName()) {
                    case "PRE":
                        mc.thePlayer.sendQueue.addToSendQueue(new C07PacketPlayerDigging(C07PacketPlayerDigging.Action.RELEASE_USE_ITEM, new BlockPos(-1, -1, -1), EnumFacing.DOWN))
                        break;
                    case "POST":
                        timer.reset()
                        mc.thePlayer.sendQueue.addToSendQueue(new C08PacketPlayerBlockPlacement(mc.thePlayer.inventory.getCurrentItem()))
                        break;
                }
            }
`

**Comment by jiangdashao** [comment]
这个玩意咋和NCP的NoSlow这么像呢，真能绕？直接发js行吗

**Comment by ChineseCookie** [comment]
> 这个玩意咋和ncp的noSlow这么像呢，真能绕？直接发js行吗

[这个](https://forums.ccbluex.net/assets/uploads/files/1595930169704-noslowtest.zip)   AAC模式可以绕

**Comment by jiangdashao** [comment]
和NCP模式如出一辙，只是加了个timer来防止发包过快
