### ISSUE TITLE
[FP] Block - break block too fast (carpet)

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#1949]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: video
**How/when does this happen**: when player breaks carpet and jumps
**Video of false positive**: https://youtu.be/wJTNHei7THA
**Other information**: 

## Configuration Files
**Link to checks.yml file**: premium config without any changes

**Comment by jiangdashao** [comment]
private video

**Comment by BestMark** [comment]
@jiangdashao I fixed access to video

**Comment by Maximillus** [comment]
This is same with any block that break fast in worldguard region I have found from testing.
