### ISSUE TITLE
[BYPASS] Impact 4.6 No Fall

### ISSUE THREAD

**Issue by LegendsOfMedieval** [jiangdashao/Matrix-Issues#195]
## Basic Information
**Hacked client**: Impact 4.6
**Cheat that bypassed**: No Fall
**Screenshot of cheat settings**: https://i.imgur.com/wCxhUCf.png
**Video of bypass**: https://youtu.be/N3KlqhStA0g

## Configuration Files
**Link to checks.yml file**: https://textuploader.com/15e9r
**Link to config.yml file**: https://textuploader.com/15e99

# Server Infomation
**Server Version**: git-Paper-612
**Matrix Version**: 1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Related #159

**Comment by jiangdashao** [comment]
Can't bypass

**Comment by jiangdashao** [comment]
![Q(CC%92QYBT%8%HEYY_PLVQ](https://user-images.githubusercontent.com/21152113/56086872-4b1def80-5e92-11e9-91f8-b08e64d0cc8c.png)
