### ISSUE TITLE
[BYPASS] Velocity

### ISSUE THREAD

**Issue by DayViper** [jiangdashao/Matrix-Issues#1951]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Skid 
**Link to hacked client**: https://www.mediafire.com/file/fh8c4pq6i90u1pa/Skid.zip/file
**Cheat that bypassed**: Velocity
**Video of bypass**: https://www.youtube.com/watch?v=9nvocNFc6H4&feature=youtu.be
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
not blatant
