### ISSUE TITLE
[FP] When you swim on the surface of the water using 1.13+ on a 1.12.2 server with ViaVersion triggers Jesus 100%

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1952]
## Troubleshooting Information
https://github.com/PirateCraft/dev/issues/15

When you use matrix on 1.12.2 paper with ViaVersion and swim using a 1.13+ client on the surface of water it triggers jesus.

`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: For some reason /matrix verbose is not creating its own logs and only sending to the client! Massive bug there. absolutely stunning. So I have had to copy these from my client logs: https://gist.github.com/FrozenBeard/0f83a665fdb4bc331b8db80c79179bd3
**How/when does this happen**:  100% of the time.

**Comment by jiangdashao** [comment]
You just need to take a screenshot, or copy from matrix log (/Matrix/logs)
