### ISSUE TITLE
[REQUEST] /matrix verbose automatically pastes the log into a gist to copy/paste into issue reporting. 

### ISSUE THREAD

**Issue by FrozenBeard** [jiangdashao/Matrix-Issues#1953]
**What features/checks do you need?:**
Matrix Verbose should work the same as LuckPerms https://github.com/lucko/LuckPerms/wiki/Verbose

`/matrix verbose upload` to turn it on.

You do your false positive. 

`/matrix verbose` to turn it off.
It automatically uploads to a gist, which is then sent to you in-game chat.

You can then copy/paste that verbose to the issue on github.

bonus points.
Include the server/matrix version and config options, this way you dont need the checkboxes on you report, you will automatically gather everything you need from the verbose log.

**Comment by jiangdashao** [comment]
no

**Comment by TomLewis** [comment]
> 
> 
> no

lol
