### ISSUE TITLE
[BYPASS] BedFucker

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1955]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: LiquidBounce b2
**Link to hacked client**: https://liquidbounce.net/
**Cheat that bypassed**: Fucker (more specifically BedFucker)
**Video of bypass**: https://streamable.com/19qr0f
**Other information**: BedFucker will only work through sand for some reason. (There may also be other blocks with the same behaviour.)

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick and custom message for IP ban)
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
sand will cause false positive in some situations, so Matrix ignore it
