### ISSUE TITLE
[BYPASS] Tower

### ISSUE THREAD

**Issue by ChineseCookie** [jiangdashao/Matrix-Issues#1956]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Liquidbounce
**Link to hacked client**: https://forums.ccbluex.net/
**Cheat that bypassed**: MotionTP Tower
**Video of bypass**: Nope
**Other information**: 
The MotionTP mode of Tower in Liquidbounce can Bypass

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by AMDBartek** [comment]
You need to follow the issue template.

**Comment by AMDBartek** [comment]
However, I can confirm that Tower on MotionTP mode does bypass Matrix.

**Comment by jiangdashao** [comment]
感知不强，确实比legit快一点
