### ISSUE TITLE
[FP] Fly and speed

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1957]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: When change from creative to survival mode, player flags many fly/speed then get kicked (after login very often)
**Other information**: This didnt happen before but in recent week it has

## Configuration Files
**Link to checks.yml file**: default matrix config

**Comment by jiangdashao** [comment]
can't reproduce
