### ISSUE TITLE
[BYPASS] Tower

### ISSUE THREAD

**Issue by DayViper** [jiangdashao/Matrix-Issues#1958]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Amera
**Link to hacked client**: http://www.mediafire.com/file/66qxv7xo6g2zztn/amera-1.8.9.rar/file
**Cheat that bypassed**: Tower
**Video of bypass**: https://youtu.be/LqvxmDQg45w
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
How can I detect a "Legit" cheat?
