### ISSUE TITLE
[BYPASS] Killaura

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1961]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: Aristois
**Cheat that bypassed**: killaura (some)
**Video of bypass**: https://streamable.com/9jm9gc
**Other information**: Matrix takes long time to detect very blatant players hitting 180 degrees behind them, the violation added if they slightly miss or if they missing by a large amount is same. If matrix use ray trace for this check it should be checked whether it collides with 3 hitboxes instead of 1 now. 
Hitbox 1 - player hitbox that it uses now, 
Hitbox 2 - player hitbox expanded by +1 block 
Hitbox 3 - player hitbox expanded by +2 blocks.
 If Ray doesn't collide with box #2 but is colliding with box #3 then give the cheater *more VL* because they are missing by a large angle, if the ray is missing box #3 (player box expanded by 2 blocks!!) then give cheater *even more* VL. 
This is similar to dynamic reach vl that matrix has. PS: hb.mis no work if target is creative?
# Configuration Files
**Link to checks.yml file**: its default matrix
**Link to config.yml file**: default matrix

**Comment by jiangdashao** [comment]
Matrix will add a cancel hit system for hitbox check
