### ISSUE TITLE
[FP] aimassist T2

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1962]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

**Server version**: 1.15.2
**Verbose messages**: it is in video
**How/when does this happen**: If using optifine cinematic camera
**Video of false positive**: https://streamable.com/905406
**Fix it with this**: https://github.com/funkemunky/Fiona-Anticheat/blob/ad4a3f87989eb74265e6e69cc924ddf7b2a78fc5/Fiona/src/cc/funkemunky/fiona/data/MovementParser.java#L99

**Comment by jiangdashao** [comment]
can't fix, already checked optfine
