### ISSUE TITLE
[BYPASS] Sigma - AntiKnock AAC / LongJump

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1963]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: Sigma 
**Link to hacked client**: Sigma 
**Cheat that bypassed**: LongJump/AntiKnock AAC
**Video of bypass**: -
**Other information**: please take a look at antiknock for aac on sigma, it bypasses matrix

## Configuration Files
**Link to checks.yml file**: -
**Link to config.yml file**:-

**Comment by jiangdashao** [comment]
I guess you want to get banned again

**Comment by assasin541** [comment]
@jiangdashao sorry, but what do you mean? I'm reporting that Sigma has AntiKnock bypass for AAC that works with Matrix too.

**Comment by Maximillus** [comment]
post video @assasin541

**Comment by assasin541** [comment]
@Maximillus install Sigma and test it

**Comment by Maximillus** [comment]
@assasin541 you must post video for issue to be accepted, dont just say stupid things like this

**Comment by Maximillus** [comment]
long jump doesnt bypass, but I no idea which mode using you were because you didnt post video

**Comment by assasin541** [comment]
@Maximillus test AntiKnock with mode for AAC. It will be the best to test it by yourself, to see exactly how it works.

**Comment by assasin541** [comment]
@Maximillus @jiangdashao any news with this?
