### ISSUE TITLE
[FP] fly

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1964]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: Moving through the kelp
**Video of false positive**: https://streamable.com/g276n8
**Other information**: occur for both minecraft:kelp and minecraft:kelp_plant. this I think may work with other flooded block.

## Configuration Files
**Link to checks.yml file**: its default matrix config

**Comment by jiangdashao** [comment]
can you reproduce this false positive in a real sea?
