### ISSUE TITLE
[REQUEST] Asyncronous mode for matrix

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1967]
**What features/checks do you need?:**
Matrix consumes quite performance on server with 150 player, even with skip tick on. AAC etc have asynchronous mode, matrix should add this.

**Comment by assasin541** [comment]
That would be good, there were some tries some time ago, but @jiangdashao gave up.

**Comment by jiangdashao** [comment]
Results optimization and testing, I think Matrix does not need an asynchronous check, asynchronous check will bring many problems, especially for higher versions of Minecraft

**Comment by assasin541** [comment]
@jiangdashao you want to create lags on your users' servers? With only 60 players online Matrix causes 50% more increased usage and many ticks are increased in time. I found more than 50 bugs just to end history with Matrix when you say you will cause lags and increased tick times?

**Comment by assasin541** [comment]
@jiangdashao also what problems can bring async? Remove PLib dependency, make async, and if problems appears on some version just add plib and remove async. Or bring back it to the config. Matrix causes huge lags and tick times increations.

**Comment by SkyLicks** [comment]
I love Matrix's unmatched combat checks and utility features like the cps test or npc. But Matrix is behind other anticheats in terms of performance. I was hoping to see this fixed in the future :/.

**Comment by assasin541** [comment]
@SkyLicks look at that issue and how @jiangdashao is respecting us. He doesn't care about respecting people and same it is about performance and lagless servers.

**Comment by jiangdashao** [comment]
Matrix only consumes about 8ms per tick on a 200 players server

**Comment by assasin541** [comment]
@jiangdashao that's not true. On 1.8 it can consume 50% tick times with only 60 players. When switching world (even with bypasses on) it creates huge lags. With 60 players every couple tick takes 60-90ms. 

16% increased tick time is HUGE lag. This is lack of smoothness, you don't want to fight with 16% longer ticks.

**Comment by jiangdashao** [comment]
Then please use other anti-cheat ^^matrix is not welcome you

**Comment by assasin541** [comment]
@jiangdashao I will have to look for another anticheat or code some more check to my own. I'm a perfectionist, if you lag my server I won't accept it. Learn to respect people and other people's work too.

**Comment by jiangdashao** [comment]
Good, Please hurry up and use other anti-cheats, I've already felt that you are disgusting
