### ISSUE TITLE
[FP] Scaffold false positive

### ISSUE THREAD

**Issue by MBDEV13** [jiangdashao/Matrix-Issues#1971]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8 Latest
**Verbose messages**: 
https://pastebin.com/1mQqUQEB
https://pastebin.com/wGdTXc7E
**How/when does this happen**: See the vid:
**Video of false positive**: https://vk.com/video_ext.php?oid=484716107&id=456239303&hash=b1ee356257c01241&hd=2
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Premium matrix config

**Comment by jiangdashao** [comment]
you can custom the min_delay in checks.yml

default value is 6

path: `checks.yml/scaffold.modules.delay.min_delay`
