### ISSUE TITLE
[REQUEST] Use Floodgate API instead of prefix to detect Geyser players

### ISSUE THREAD

**Issue by HandyHat** [jiangdashao/Matrix-Issues#1974]
**What features/checks do you need?:**

As detailed [here](https://discordapp.com/channels/392904793758367745/574079643292794915/727490280076476430) by a Geyser dev, it would be good if Matrix used the Floodgate API to detect if a player is playing on Bedrock because that would add support for using linked accounts (where a Bedrock player is playing as if they are on their Java account).

**Comment by Maximillus** [comment]
link not work

**Comment by HandyHat** [comment]
![2020-08-24](https://user-images.githubusercontent.com/58530748/91072503-86593280-e631-11ea-9630-5d96fe8e25f1.png)
Here is a screenshot

**Comment by Tim203** [comment]
If you're planning on actually doing this (what is recommended btw), you should probably wait until the 2.0 is out since it contains breaking Api changes.
