### ISSUE TITLE
[INCOMPATIBILITY] ViaBackwards and ViaRewind cause FastBreak false positive

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1975]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Incompatible plugin**: ViaBackwards and ViaRewind
**Verbose messages (or) console errors**: 
```
(14:34:55) YouAreAYeet failed Block check | break block too fast (digs: 0/2, block: grass) (+4) | vl:4 ping:24 tps:19.93 lp:22 component: block.fastbreak.expect
(14:34:55) YouAreAYeet failed Block check | break block too fast (digs: 0/2, block: grass) (+4) | vl:8 ping:24 tps:19.93 lp:21 component: block.fastbreak.expect
(14:34:56) YouAreAYeet failed Block check | break block too fast (digs: 0/2, block: grass) (+4) | vl:12 ping:24 tps:19.55 lp:20 component: block.fastbreak.expect
(14:34:56) Execute command: coc YouAreAYeet if -tps->18&-lp-<33 do matrix notify YouAreAYeet tried to place/break a block too quickly | Block | 1/3
(14:34:57) YouAreAYeet failed Block check | break block too fast (digs: 0/2, block: grass) (+4) | vl:16 ping:24 tps:19.55 lp:20 component: block.fastbreak.expect
(14:34:57) Execute command: matrix notify YouAreAYeet tried to place/break a block too quickly | Block | 2/3
(14:34:57) YouAreAYeet failed Block check | break block too fast (digs: 0/2, block: grass) (+4) | vl:20 ping:24 tps:19.55 lp:18 component: block.fastbreak.expect
```
**How/when does this happen**: When breaking most blocks.
**Video of incompatibility**: https://streamable.com/8r7esg
**Other information**: I have made an issue on the ViaRewind and ViaBackwards GitHub page, **I cannot use ProtocolSupport due to it being incompatible with Multiverse.** I think that it would be really good to fix compatibility with ViaBackwards and ViaRewind because many servers use these plugins.

ViaBackwards issue: https://github.com/ViaVersion/ViaRewind/issues/201
ViaRewind issue: https://github.com/ViaVersion/ViaBackwards/issues/253

## Configuration Files
**Link to checks.yml file**: Default (Only change is IP ban instead of kick)

**Comment by jiangdashao** [comment]
can't fix that
