### ISSUE TITLE
[BYPASS] jesus

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1978]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: Interta
**Cheat that bypassed**: jesus/waterspeed
**Video of bypass**: https://streamable.com/wgqse6
**Other information**: jesus.out predict wrong

## Configuration Files
**Link to checks.yml file**: default matrix
**Link to config.yml file**:default matrix

**Comment by jiangdashao** [comment]
Because Matrix, in order to prevent desync bugs, all players with 1.13+ think they are swimming even if they are not
You can disable it in checks.yml

### Solve
`jesus.ignore_swim_pose`, set it to false
