### ISSUE TITLE
[FP] Elytra Fly

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#198]
## Basic Information
**Verbose message(s)**:  https://imgur.com/a/Pkegj7N
**How/when does this happen**: When you fly legitimately with an elytra for a long time 
**Video of false positive**: https://youtu.be/3mLiZ947InM

## Configuration Files
**Link to checks.yml file**:  https://pastebin.com/Qr1eAzJT
**Link to config.yml file**:  https://pastebin.com/EjnVuvE6

# Server Infomation
**Server Version**:  1.13
**Matrix Version**:  1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by Kyrobi** [comment]
It would also be nice if there's a way to turn off the elytra check but still allow the fly check

**Comment by jiangdashao** [comment]
It will be add
