### ISSUE TITLE
[BYPASS] KillAura (MultiAura)

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#1982]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst
**Link to hacked client**: https://www.wurstclient.net/
**Cheat that bypassed**: MultiAura
**Video of bypass**: https://streamable.com/gczo88
**Other information**: You have to stand still for it to bypass.

## Configuration Files
**Link to checks.yml file**: Default (Only changes are only_command_trigger: false and IP ban instead of kick)
**Link to config.yml file**: Default

**Comment by AMDBartek** [comment]
Forgot to add video, will add when uploaded

**Comment by jiangdashao** [comment]
not important
