### ISSUE TITLE
[REQUEST] Dummy project for build automation tools

### ISSUE THREAD

**Issue by PikaMug** [jiangdashao/Matrix-Issues#1985]
**What features/checks do you need?:**

Provide a way for Maven/Gradle users to use Matrix as a dependency. This could be accomplished with a dummy API similar to https://github.com/konsolas/AAC-Issues#aac-api

If you aren't able/willing to acquire a repository, just upload the API to Github, then developers can merely use [JitPack](https://jitpack.io/).

Thanks!

**Comment by jiangdashao** [comment]
No, This will make it troublesome for me to update the API
