### ISSUE TITLE
[FP] Phase with 1.16 client

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1986]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(18:06:51) assasin541 Phase | moved into block (block: stained_clay, move: 0.0,0.42,0.0, at: -69.397,50.42,-44.636, dist: 0.0, loop: false) (+2) | vl:15 ping:53 tps:20.0 component: phase.main
(18:06:52) assasin541 Phase | moved into block (block: stained_clay, move: 0.0,0.422,0.0, at: -69.397,50.422,-44.636, dist: 0.0, loop: false) (+2) | vl:17 ping:53 tps:20.0 component: phase.main
(18:06:52) assasin541 Phase | moved into block (block: stained_clay, move: 0.0,0.42,0.0, at: -69.397,50.42,-44.636, dist: 0.0, loop: false) (+2) | vl:19 ping:53 tps:20.0 component: phase.main
(18:06:52) assasin541 Phase | moved into block (block: stained_clay, move: 0.0,0.422,0.0, at: -69.397,50.422,-44.636, dist: 0.0, loop: false) (+2) | vl:21 ping:53 tps:20.0 component: phase.main

**How/when does this happen**: When you sneak under a block and jump you will get flagged for fly.
**Other information**: 1.16 client + viaversion, changing options on viaversion for that doesn't work.

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
don't install ViaVersion in BungeeCord, you should install it in the spigot side
