### ISSUE TITLE
[FP] floating down the water trigger Fly

### ISSUE THREAD

**Issue by MrEDok** [jiangdashao/Matrix-Issues#1987]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.2
**Verbose messages**: check discord
**How/when does this happen**: place wtaer high in the sky and remove source and jump in it
**Video of false positive**: check discord
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
can't fix that

**Comment by jiangdashao** [comment]
1. I can't fix it, it is hard to fix
2. it seems that you modified the water flow speed, I can't reproduce the false positive in my test
