### ISSUE TITLE
[BYPASS]  Users can bypass Spam Chat check by using /me command

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#199]
## Basic Information
**Hacked client**:  any
**Cheat that bypassed**:  Chat
**Screenshot of cheat settings**:  default
**Video of bypass**:  
![image](https://user-images.githubusercontent.com/21042824/56086754-30a43180-5e12-11e9-8609-b5cad612cb75.png)

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

# Server Information
**Server Version**:  Spigot 1.13.2
**Matrix Version**:  1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
It's not spam chat
It is spam command
Please use some command delay plugin or disable the /me command
