### ISSUE TITLE
[REQUEST] Velocity (proxy) support for GeyserMC

### ISSUE THREAD

**Issue by muzak23** [jiangdashao/Matrix-Issues#1990]
**What features/checks do you need?:**
Support for adding Matrix to Velocity (https://www.velocitypowered.com/ a Bungeecord alternative) in regards to the new Bungeecord support for checking GeyserMC Bedrock users.

**Comment by jiangdashao** [comment]
floodgate does not support the latest version of "Velocity"

**Comment by muzak23** [comment]
I'm not sure what you mean by this, as it *does* support it. I'm using it on my proxy right now.

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/91649122-f2f58680-eaa2-11ea-8339-215f2138fb1b.png)

**Comment by muzak23** [comment]
You need to use Velocity 1.1.0, found at https://ci.velocitypowered.com/job/velocity-1.1.0/

**Comment by jiangdashao** [comment]
done
