### ISSUE TITLE
[REQUEST] Clickable commands in notify

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#1991]
**What features/checks do you need?:**
It would be useful if I was able to somehow make usernames in the `notify` clickable, so I can run commands on it. In this case, I want clicking the usernames to issue `/tp` so that I am being teleported to that player.

**Comment by jiangdashao** [comment]
No

**Comment by jiangdashao** [comment]
The notify command is not tied to the player

### Usage
/matrix notify <message>
