### ISSUE TITLE
[FP] Inventory bug

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1992]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(13:51:01) assasin541 Inventory | inventory move | pattern: b | s:32 (+7) | vl:71 ping:51 tps:19.98 component: inv.move
(13:51:01) assasin541 Inventory | inventory move | pattern: b | s:32 (+7) | vl:78 ping:51 tps:19.98 component: inv.move
(13:51:02) assasin541 Inventory | inventory move | pattern: b | s:23 (+7) | vl:85 ping:51 tps:19.98 component: inv.move
(13:51:02) assasin541 Inventory | inventory move | pattern: b | s:32 (+7) | vl:92 ping:51 tps:20.0 component: inv.move

**How/when does this happen**: sometimes inventory bugs and you can't switch slots of the items, drop them, you can only drop/use items from your toolbar. when this has happened, i was clicking in the inventory and i got kicked. I have opened issue in ViaVersion github and we are looking for the source of this bug. Maybe it comes from Matrix?
**Other information**: what is "inventory move | pattern: b"? various client versions 1.13/1.14/1.15/1.16 or other

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
you click the inventory without open it

**Comment by assasin541** [comment]
@jiangdashao I didn't get video, because i got kicked. when it will happen i will try to record, it happens very often.

**Comment by assasin541** [comment]
@jiangdashao why do you need the video for it? You won't see very much, just that I can't edit inventory and i get kicked.

**Comment by assasin541** [comment]
@jiangdashao you know what can cause this? When you open enderchest items and in their place, but you still can't move them.

**Comment by assasin541** [comment]
@jiangdashao I disabled inventory checks and this problem disappeared, so Matrix is blocking opening inventory and blocks this?

**Comment by Maximillus** [comment]
@jiangdashao @assasin541 1.9+ client doesnt send open window packet

**Comment by assasin541** [comment]
@Maximillus @jiangdashao it doesn't happen all the time, it can happen after some time. It happened on 1.8 clients too.
