### ISSUE TITLE
[BYPASS] 2 block step

### ISSUE THREAD

**Issue by kimpiegamesYT** [jiangdashao/Matrix-Issues#1993]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**1.15**: 
**Sigma 5 jello**: 
**https://sigmaclient.info/**: 
**Step**: 
**Step 2 block high NCP mode**:

**Comment by AMDBartek** [comment]
You need to follow the issue template.
