### ISSUE TITLE
[FP] hb.reach hb.mis

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#1994]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: missed player hitbox (raytrace: 1/11 positions, lag: 8, prep: false) (+3) 
**How/when does this happen**: faction plugin for weapon call player.attack(entity)
**Other information**: Matrix should use protocol lib not the bukkit event, using bukkit event is for baby anticheat

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
No, Rewriting requires a lot of work

You can add `IGNORE_ATTACK` meta to the attacker

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/91699159-73e97680-eba6-11ea-8001-18f391cc8b3b.png)

**Comment by Maximillus** [comment]
@jiangdashao instead of entitydamagebyentityevent, listen for attack packet.

**Comment by jiangdashao** [comment]
I said "Rewriting requires a lot of work"
