### ISSUE TITLE
[INCOMPATIBILITY] StreamingDrops

### ISSUE THREAD

**Issue by morelaid** [jiangdashao/Matrix-Issues#1995]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15 and 1.16
**Incompatible plugin**: StreamingDrops
**Verbose messages (or) console errors**:
Not from Matrix. The error message comes from StreamingDrops, but Matrix seems to cause this:
„java.io.IOException: Server returned HTTP response code: 400 for URL“
**How/when does this happen**: 
After a certain time or a amount of HTTP requests, the specified error is displayed. A restart of the server solves the problem temporarily. Removing Matrix solves the problem completely and permanently.
**Video of incompatibility**:
No video
**Other information**:

(Paid version of Matrix)

I am the developer of StreamingDrops, so we can certainly find a solution here.

The main problem seems to be:
My plugin uses web requests to check various information. After a certain time or a number of requests, here the HTTP request is returned with the error "400 - Bad Request". If you restart the server, StreamingDrops will run with the HTTP requests for a while and then not anymore. If Matrix is removed, the problem does not occur anymore.

It is estimated that this will happen with the default configurations as well, but unfortunately I can't say this to 100%, because these problems have been reported by different users of StreamingDrops. All of them using BungeeCord networks.

**Comment by jiangdashao** [comment]
is there any error in console?

**Comment by morelaid** [comment]
Like i said in the topic „ Verbose messages (or) console errors:“

**Error:** java.io.IOException: Server returned HTTP response code: 400 for URL.

This does not come directly from Matrix, but is only caused by it. Matrix itself does not throw an error, but simply blocks the HTTP request, which leads to the above mentioned error.

**Comment by jiangdashao** [comment]
what? I did not block any http requests

**Comment by morelaid** [comment]
Here at least something seems to be blocked, because when Matrix is installed, it only works for about 10-30 minutes... After that no HTTP requests are possible.

If Matrix is uninstalled / not started, then the HTTP requests are still possible after the 10-30 minutes...

Can there be anything else (for example processes or other things) that is blocked or aborted by Matrix?

**Comment by jiangdashao** [comment]
can you try this version: https://file.matrix.rip/matrix_jar/Matrix_5.2.0_http_test_release.jar

**Comment by morelaid** [comment]
Unfortunately this version seems to have made no difference...

![89E7BD51-CBCF-4D5F-8430-946767D64599](https://user-images.githubusercontent.com/37469978/91650424-bb291780-ea7f-11ea-9766-557aec88d62b.png)

**Comment by jiangdashao** [comment]
Then I can’t solve it, or it’s not Matrix’s problem

**Comment by jiangdashao** [comment]
can you show me your http request code?

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/91650860-9fd9fe80-eab7-11ea-9922-2ea233510eb8.png)
Your HTTP code is very simple, can you use a professional HTTP library? like `corn-httpclient`?

If Matrix is blocking the Http request, why is bStats still working? Why is this problem only with your plugin?

**Comment by morelaid** [comment]
To the first question:

Why is my code simple? It makes sense to keep the code as simple as possible...

To the second question:
At this point it seems to be Matrix or the interaction between Matrix and StreamingDrops. If the server is running with Matrix, the problems occur. If you restart the server, it works and after 10-30 minutes it does not work anymore (until the next restart). If you delete Matrix from the server, StreamingDrops will run for several hours without this error (no errors).

So the conclusion is, the combination StreamingDrops & Matrix do not like each other for some reason. And to find exactly this reason, I am here....

**Comment by jiangdashao** [comment]
The simple code is built on the basis of high availability. If you don’t want to change your code, then I have nothing to do, and it does nothing to me.

And, Your API recommends that you use https to access.

`HTTP requests are supported, but HTTPS (TLS 1.x) is encouraged.`

My Http Request Util:
```Java
import me.rerere.matrix.Matrix;
import net.sf.corn.httpclient.HttpClient;
import net.sf.corn.httpclient.HttpResponse;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class HttpUtil {
    public static String connect(String s) {
        try {
            HttpClient httpClient = new HttpClient(new URI(s));
            httpClient.setUserAgent(HttpClient.USER_AGENT_CHROME_28_0_1468_0);
            httpClient.setCharset("UTF-8");
            httpClient.setReadTimeout(5000);
            HttpResponse response = httpClient.sendData(HttpClient.HTTP_METHOD.GET);
            if (response != null) {
                if (!response.hasError()) {
                    if (response.getData() != null) {
                        return response.getData();
                    }
                }
            }
            return "";
        } catch (URISyntaxException e) {
            e.printStackTrace();
            Matrix.log("Wrong URL: " + s);
        } catch (IOException e) {
            e.printStackTrace();
            Matrix.log("Error when connecting internet: " + e.getClass().getName());
        }
        return "";
    }
}
```

**Comment by morelaid** [comment]
You seem to have misunderstood me at this point:

I have already tried other client calls (before contacting you), because I only saw the problem in my case.

I'm not a fan of saying "Plugin XY" is to blame, so it's not about saying "You did something stupid here and there" or anything like that.

I'm sorry if you understood it that way, that I wouldn't be willing to do anything for it, so that the two plugins can stay together. On the contrary... I would be very happy about it, since excluded plugins are always bad.

Gladly I can also try this again on your way. I'm not sure if I used this HTTP client, because I tried different HTTP clients as well as methods in the past. Since these had the same effect, I went back to the "simple" variant.

**Comment by morelaid** [comment]
Even if you did not tell me the right place with the screenshot, I tried it with your HttpClient (in two places).

This now seems to run a bit longer than before. The test will now take a little longer and if it works completely, I will rebuild it accordingly cleanly.
