### ISSUE TITLE
[BYPASS] Boat fly

### ISSUE THREAD

**Issue by Mrjinsop** [jiangdashao/Matrix-Issues#1998]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.2
**Hacked client**: Wurst
**Cheat that bypassed**: boat fly
**Video of bypass**: [https://streamable.com/t30pe](https://bit.ly/3jzARtl)
**Other information**: place boat on soul sand, and ride it. You can bypass it

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
没妈的孩子真可怜
