### ISSUE TITLE
[ERROR] Matrix performance

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#1999]
**What features/checks do you need?:** I would like to see async and better performance, example profiles from spark: https://share.getcloudapp.com/lluY7Rko

**Comment by jiangdashao** [comment]
4% is not a problem

**Comment by assasin541** [comment]
@jiangdashao there's doesn't have to be a problem, if there is a space for improvement we should to that. :)

**Comment by assasin541** [comment]
@jiangdashao also depends on the same it can be more.

**Comment by assasin541** [comment]
@jiangdashao on the newest version it's around 8% + other checks it's even more.
