### ISSUE TITLE
Inventory FP

### ISSUE THREAD

**Issue by DmitryRendov** [jiangdashao/Matrix-Issues#20]
## How you trigger the false positive?
Move chest content to inventory using shift+dblclick (vanilla behaviour)

## Verbose Message:
(10:14:18) Player failed Inventory check | t: chest steal (+3) | vl:75 ping:32 tps:20.0

## Videos:
-

## Server Infomation
Matrix AntiCheat (1.1.9)
git-Spigot-f56e2e7-b634e05 (MC: 1.13.2)
ProtocolLib v4.4.0

**Comment by jiangdashao** [comment]
chest steal check should be recode
