### ISSUE TITLE
[BYPASS] Relogging disables detection for a few seconds

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#200]
## Basic Information
**Hacked client**: Nexus b12.2
**Cheat that bypassed**: Fly
**Screenshot of cheat settings**: https://i.imgur.com/iVEP9wM.png
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxHVisJbxoFqgqtIg

## Configuration Files
**Link to checks.yml file**: I'm on tree.ac, it's default
**Link to config.yml file**: I'm on tree.ac, it's default

# Server Infomation
**Server Version**: I'm on tree.ac, I don't know
**Matrix Version**: I'm on tree.ac, it's default
**ProtocolLib Version**: I'm on tree.ac, I don't know

**Comment by jiangdashao** [comment]
I think it's a tree.ac server's bug
