### ISSUE TITLE
Spelling error in /about

### ISSUE THREAD

**Issue by TrueReassembly** [jiangdashao/Matrix-Issues#2001]
The /about for matrix says "A advanced anticheat" when it should be "An advanced anticheat"

I couldn't find any topic for this

Version is 5.0.0 (#BlameMinehut)

**Comment by AMDBartek** [comment]
It's Minehuts fault not Matrix's, use proper hosting.

**Comment by TrueReassembly** [comment]
Uh no? The /about page is written by the author in the plugin.yml file

Unless there is a minehut matrix fork that I am unaware of, then this is not minehut's fault

**Comment by jiangdashao** [comment]
fixed
