### ISSUE TITLE
Confusion between a plugin[FP] 

### ISSUE THREAD

**Issue by ExceptedPrism3** [jiangdashao/Matrix-Issues#2002]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: "Player" failed Block check | no swing ....
**How/when does this happen**: I have a plugin called WildTools, what this plugin allows you to do is to build up walls with 5 length with 1 hit, this Anti-Hack blocks it and kicks afterwards even all was legit, and in order to make the plugin work I need to disable the whole Block Check.
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by AMDBartek** [comment]
You need to follow the issue template.
