### ISSUE TITLE
[FP] make all combat checks when packet is recieve

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2004]
**What features/checks do you need?:**
Don't use entityDamageByEntityEvent in an anticheat. it cause much of incompatibility with plugins and is a bad practice. Even hitbox original didn't use this event https://github.com/HawkAnticheat/Hawk/blob/master/src/me/islandscout/hawk/check/combat/FightHitbox.java 
if matrix depends protocollib then use protocollib for its purpose (listening packets).

**Comment by ventolotl** [comment]
There's no difference in this case if you use the Bukkit event pipeline or listening to ProtocolLib's events

**Comment by jiangdashao** [comment]
not rn
