### ISSUE TITLE
[FP] hb.mis and hb.reach

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2005]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: when you riding tall vehicle and hit the player it could flag reach/hitbox sometimes.
**Other information**: fix for this is: https://github.com/HawkAnticheat/Hawk/commit/f8b1d8148218bd38b2bd720341c19c8cb010ca9e

## Configuration Files
**Link to checks.yml file**: its default matrix file

**Comment by jiangdashao** [comment]
verbose message? video?
