### ISSUE TITLE
[BYPASS] Inertia Client - Reach & Attack through blocks & Free Cam block placement

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#2009]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server (I'm running 1.16.2)
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.2 
**Hacked client**:  Inertia
**Link to hacked client**:  https://inertiaclient.com
**Cheat that bypassed**:  Reach, Hitting through walls, Free Cam Block Placement
**Video of bypass**:  https://clips.twitch.tv/TacitDarlingPangolinKeyboardCat
**Other information**:  If you observe the video, you can see the Player hitting Mobs through blocks, with far reach. The blocks surrounding him can be placed with Free Cam block placement.  

## Configuration Files
**Link to checks.yml file**:  Using default
**Link to config.yml file**:  Using Default

**Comment by jiangdashao** [comment]
This situation is a bit difficult to fix, it looks like this:
1. Interact check requires the player to face the entity to check. If the player does not look at the entity, then Interact check will not work
2. If the player does not look at the entity, the HitBox check should be detected, but for some reasons, the HitBox check is not strict, it is very loose, so it is bypassed

I think it is not very important
