### ISSUE TITLE
[BYPASS] Scaffold/Tower + ItemSpoof

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#2010]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: BlockFly
**Video of bypass**: https://youtu.be/QQQPcHeayOo
**Other information**: This isn't a 100% working bypass! Make sure to not directly select a block! The only thing I want to demonstrate is that ItemSpoof seems to bypass a lot of checks. Notice how as soon as I manually switch to the dirt block I instantly get kicked? That's what I mean. You can also freely sprint while using this.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
There are some checks to detect it, but it only works for premium user
