### ISSUE TITLE
[BYPASS] NoFall (again)

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#2011]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: NoFall
**Video of bypass**: https://youtu.be/Q4zYaZ81c1w
**Other information**: For some reason the old bypass that was patched a month ago works again.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
not important
