### ISSUE TITLE
[BYPASS]  Jesus + Fly in water

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#2013]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.2 
**Hacked client**:  Inertia
**Link to hacked client**:  https://inertiaclient.com/
**Cheat that bypassed**:  Jesus 
**Video of bypass**:  https://clips.twitch.tv/TemperedPrettyChowderKAPOW
**Other information**:  They seem to be using packet fly + Jesus in water?

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

**Comment by jiangdashao** [comment]
try set "jesus.ignore_pose" to false in checks.yml

**Comment by Kruize1** [comment]
I see this for checks? I guess it's "ignore_swim_pose:" ? I'll try it out.

## Jesus
# Check prevents the player from moving too too quickly in liquids, or walking on liquid.
jesus:
  # Enable this check?
  enable: true

  # Violations needed to cancel illegal movements (-1 = never cancel)
  cancel_vl: 15

  # Should Matrix ignore whether player is in swimming?
  # This feature can prevent swimming status desync
  ignore_swim_pose: true

  # Violation Thresholds
  # number_of_violations: '<command>'
  commands:
    20: 'matrix notify %player% tried to move illegally in liquid (Jesus)'
    40: 'matrix notify %player% tried to move illegally in liquid (Jesus) #2'
    50: 'matrix kick %player% Jesus/WaterSpeed/WaterFly Hacks'

**Comment by jiangdashao** [comment]
yes, set "ignore_swim_pose" to false

**Comment by Kruize1** [comment]
Issue persists as described. True of False, still happens.

**Comment by Kruize1** [comment]
![image](https://user-images.githubusercontent.com/21042824/92673194-68e1c500-f2cf-11ea-8ad5-1248399599c9.png)

**Comment by Maximillus** [comment]
@jiangdashao this is issue #1978

**Comment by jiangdashao** [comment]
> @jiangdashao this is issue #1978

not same

**Comment by jiangdashao** [comment]
client setting?

**Comment by jiangdashao** [comment]
@Kruize1

**Comment by Kruize1** [comment]
I'll ask
