### ISSUE TITLE
[ERROR] 1.16.2 StackOverflowError Error

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#2014]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Latest 1.16.2 Tuinity
**Error(s) found in console**: 
https://pastebin.com/Vcebqk94
**How/when does this happen**: No idea

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
NaN
