### ISSUE TITLE
[REQUEST] add boat phase check

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2015]
**What features/checks do you need?:**
Boat phase from inertia client let player fly through walls + entity ride fast speed. Matrix had boat phase check but it gone now

**Comment by jiangdashao** [comment]
Matrix only detect it when you use the hack under the deep ground, if you just fly through a "wall", it can‘t be detected

**Comment by Maximillus** [comment]
I was flying through deep ground at very fast speed, the check doesn't seem work

**Comment by LaserSlimeHD** [comment]
Vehicle checks as a whole are kind of broken, I was sometimes even able to fly with boats. It only rarely happens tho.

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/93761948-48a3f580-fc41-11ea-87d0-1132185bf273.png)
