### ISSUE TITLE
[BYPASS] Sigma Antibot bypass Matrix NPC

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2018]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Sigma 5
**Link to hacked client**: https://sigmaclient.info/#download
**Cheat that bypassed**: Antibot + Kill Aura
**Video of bypass**: Not needed
**Other information**: The Sigma Antibot in its "Advanced Mode" is bypassing the Matrix NPC.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/BkFxyF6g (only shows KillAura NPC related)

**Comment by jiangdashao** [comment]
it can't bypass, even it bypassed NPC, other checks can detect it too
