### ISSUE TITLE
[FP] Phase while sneaking on 1.16 client

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#2020]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: 
(19:26:22) assasin541 Phase | moved into block (block: stained_clay, move: -0.07,0.42,0.053, at: -83.073,51.42,5.511, dist: 0.087, loop: false) (+2) | vl:12 ping:40 tps:20.0 component: phase.main
(19:26:22) assasin541 Phase | moved into block (block: stained_clay, move: -0.05,0.42,-0.004, at: -83.06,51.42,5.452, dist: 0.051, loop: false) (+2) | vl:2 ping:40 tps:20.0 component: phase.main
(19:26:22) assasin541 Phase | moved into block (block: stained_clay, move: -0.021,0.42,-0.001, at: -83.036,51.42,5.455, dist: 0.021, loop: false) (+2) | vl:4 ping:40 tps:20.0 component: phase.main
**How/when does this happen**: when you sneak under a block and get hit or jump, while being on 1.16 client it will block you and detect phase
**Other information**: 1.16 client

## Configuration Files
**Link to checks.yml file**: -

**Comment by jiangdashao** [comment]
don't install viaversion on bungee side

**Comment by assasin541** [comment]
@jiangdashao i have it only on bukkit side.

**Comment by jiangdashao** [comment]
record a vid?

**Comment by assasin541** [comment]
@jiangdashao 
(20:44:51) assasin541 Phase | moved into block (block: cobblestone, move: -0.051,0.42,0.012, at: 8.513,60.42,2.446, dist: 0.052, loop: false) (+2) | vl:8 ping:47 tps:19.97 component: phase.main
(20:44:51) assasin541 Phase | moved into block (block: cobblestone, move: 0.0,0.42,0.0, at: 8.564,60.42,2.434, dist: 0.0, loop: false) (+2) | vl:10 ping:47 tps:19.97 component: phase.main
(20:44:51) assasin541 Fly | suspicious movement:0.42 predict:-0.078 pmv:0.42 tag:ground (+5) | vl:5 ping:47 tps:19.97 component: fly.main
(20:44:51) assasin541 Phase | moved into block (block: cobblestone, move: 0.0,0.42,0.0, at: 8.564,60.42,2.434, dist: 0.0, loop: false) (+2) | vl:12 ping:47 tps:19.97 component: phase.main
(20:44:51) assasin541 Phase | moved into block (block: cobblestone, move: 0.0,0.422,0.0, at: 8.564,60.422,2.434, dist: 0.0, loop: false) (+2) | vl:14 ping:47 tps:19.97 component: phase.main
(20:44:51) assasin541 Phase | moved into block (block: cobblestone, move: 0.069,0.42,-0.001, at: 8.701,60.42,2.398, dist: 0.069, loop: false) (+2) | vl:16 ping:47 tps:20.0 component: phase.main
(20:44:52) assasin541 Phase | moved into block (block: cobblestone, move: 0.018,0.42,0.02, at: 8.654,60.42,2.425, dist: 0.027, loop: false) (+2) | vl:18 ping:47 tps:20.0 component: phase.main
(20:44:52) assasin541 Phase | moved into block (block: cobblestone, move: 0.018,0.422,0.02, at: 8.654,60.422,2.425, dist: 0.027, loop: false) (+2) | vl:20 ping:47 tps:20.0 component: phase.main

**Comment by jiangdashao** [comment]
then fk off

**Comment by assasin541** [comment]
@jiangdashao i'm trying to help don't be disrespectful. I will try to record the video today.

**Comment by assasin541** [comment]
@jiangdashao (21:45:21) assasin541 Phase | moved into block (block: barrier, move: -0.294,0.336,0.0, at: -33.622,68.294,-13.7, dist: 0.294, loop: false) (+2) | vl:114 ping:28 tps:20.0 component: phase.main
(21:45:22) assasin541 Phase | moved into block (block: barrier, move: -0.593,0.203,-0.008, at: -36.543,68.324,-13.712, dist: 0.593, loop: false) (+4) | vl:118 ping:28 tps:20.0 component: phase.main
(21:45:22) assasin541 Phase | moved into block (block: barrier, move: -1.395,0.385,-0.055, at: -37.321,68.272,-13.781, dist: 1.396, loop: false) (+4) | vl:122 ping:28 tps:20.0 component: phase.main
(21:45:23) assasin541 Phase | moved into block (block: barrier, move: -0.597,0.203,0.053, at: -38.271,68.324,-13.483, dist: 0.599, loop: false) (+4) | vl:126 ping:28 tps:20.0 component: phase.main

it's happening on 1.8 client too. You still want the video?

**Comment by assasin541** [comment]
@jiangdashao any news with this bug?

**Comment by assasin541** [comment]
@jiangdashao here's the video. Please fix this bug, thank you. 👍 
https://share.getcloudapp.com/7Ku81g9X

(19:15:28) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.42,0.0, at: -131.67,47.42,32.431, dist: 0.0, loop: false) (+2) | vl:151 ping:59 tps:19.91 component: phase.main
(19:15:28) assasin541 Fly | suspicious movement:0.42 predict:-0.078 pmv:0.42 tag:ground (+5) | vl:10 ping:59 tps:19.91 component: fly.main
(19:15:28) assasin541 Fly | suspicious movement:0.42 predict:0.42 air_t:0 tag:sam (+5) | vl:15 ping:59 tps:19.91 component: fly.main
(19:15:28) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.42,0.0, at: -131.67,47.42,32.431, dist: 0.0, loop: false) (+2) | vl:153 ping:59 tps:19.91 component: phase.main
(19:15:29) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.42,0.0, at: -131.67,47.42,32.431, dist: 0.0, loop: false) (+2) | vl:155 ping:59 tps:19.91 component: phase.main
(19:15:29) assasin541 Fly | suspicious movement:0.42 predict:-0.078 pmv:0.42 tag:ground (+5) | vl:20 ping:59 tps:19.91 component: fly.main
(19:15:29) assasin541 Fly | suspicious movement:0.42 predict:0.42 air_t:0 tag:sam (+5) | vl:25 ping:59 tps:19.91 component: fly.main
(19:15:29) assasin541 Fly | suspicious movement:0.42 predict:-0.078 pmv:0.42 tag:ground (+5) | vl:30 ping:59 tps:19.91 component: fly.main
(19:15:29) assasin541 Fly | suspicious movement:0.42 predict:0.42 air_t:0 tag:sam (+5) | vl:35 ping:59 tps:19.91 component: fly.main
(19:15:29) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.42,0.0, at: -131.67,47.42,32.431, dist: 0.0, loop: false) (+2) | vl:157 ping:59 tps:19.91 component: phase.main
(19:15:30) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.422,0.0, at: -131.67,47.422,32.431, dist: 0.0, loop: false) (+2) | vl:159 ping:59 tps:20.0 component: phase.main
(19:15:30) assasin541 Fly | suspicious movement:0.42 predict:-0.078 pmv:0.422 tag:ground (+5) | vl:40 ping:59 tps:20.0 component: fly.main
(19:15:30) assasin541 Phase | moved into block (block: red_sandstone, move: 0.0,0.42,0.0, at: -131.67,47.42,32.431, dist: 0.0, loop: false) (+2) | vl:161 ping:59 tps:20.0 component: phase.main

**Comment by assasin541** [comment]
@jiangdashao will it be fixed in the next version?
