### ISSUE TITLE
[FP] killaura direction

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2022]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: 
(13:47:36) wrong head rotation direction (mot: -0.236,-0.193, pre: -0.108,-0.18, sd: 0.305, sp: false, val: 2, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:1
(13:47:37) wrong head rotation direction (mot: -0.27,0.021, pre: -0.155,0.002, sd: 0.271, sp: false, val: 2, ctk: 29, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:2
(13:47:37) wrong head rotation direction (mot: -0.275,0.067, pre: -0.117,0.024, sd: 0.283, sp: true, val: 3, ctk: 24, att: 0.182) (+1) - ping:89 tps:20.0 lp:1 vl:3
(13:47:41) wrong head rotation direction (mot: -0.211,-0.192, pre: -0.128,-0.124, sd: 0.285, sp: false, val: 2, ctk: 23, att: 0.14) (+1) - ping:89 tps:20.0 lp:7 vl:4
(13:47:41) wrong head rotation direction (mot: -0.223,-0.182, pre: -0.138,-0.119, sd: 0.288, sp: false, val: 3, ctk: 21, att: 0.14) (+1) - ping:89 tps:20.0 lp:7 vl:5
(13:47:42) wrong head rotation direction (mot: -0.227,-0.177, pre: -0.144,-0.114, sd: 0.288, sp: false, val: 4, ctk: 30, att: 0.14) (+1) - ping:89 tps:20.0 lp:7 vl:6
(13:47:42) wrong head rotation direction (mot: -0.227,-0.178, pre: -0.145,-0.113, sd: 0.288, sp: false, val: 5, ctk: 28, att: 0.14) (+1) - ping:89 tps:20.0 lp:7 vl:7
(13:47:46) wrong head rotation direction (mot: 0.263,-0.08, pre: 0.15,-0.039, sd: 0.275, sp: false, val: 2, ctk: 29, att: 0.14) (+1) - ping:88 tps:20.0 lp:2 vl:1
(13:47:47) wrong head rotation direction (mot: 0.085,-0.285, pre: 0.056,-0.184, sd: 0.298, sp: false, val: 2, ctk: 28, att: 0.14) (+1) - ping:90 tps:20.0 lp:1 vl:2
(13:47:48) wrong head rotation direction (mot: 0.069,-0.287, pre: 0.051,-0.181, sd: 0.295, sp: false, val: 3, ctk: 26, att: 0.14) (+1) - ping:90 tps:20.0 lp:1 vl:3
(13:47:49) wrong head rotation direction (mot: 0.126,-0.265, pre: 0.069,-0.173, sd: 0.293, sp: false, val: 2, ctk: 28, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:4
(13:47:50) wrong head rotation direction (mot: 0.285,0.011, pre: 0.172,0.025, sd: 0.285, sp: false, val: 3, ctk: 24, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:5
(13:47:50) wrong head rotation direction (mot: 0.288,-0.046, pre: 0.184,-0.009, sd: 0.291, sp: false, val: 4, ctk: 22, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:6
(13:47:55) wrong head rotation direction (mot: -0.263,0.16, pre: -0.188,0.096, sd: 0.308, sp: false, val: 2, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:7
(13:47:56) wrong head rotation direction (mot: -0.227,0.168, pre: -0.144,0.087, sd: 0.282, sp: false, val: 3, ctk: 29, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:8
(13:47:56) wrong head rotation direction (mot: -0.197,0.19, pre: -0.124,0.092, sd: 0.273, sp: false, val: 4, ctk: 28, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:9
(13:47:56) wrong head rotation direction (mot: -0.153,0.271, pre: -0.104,0.188, sd: 0.311, sp: false, val: 5, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:10
(13:47:56) wrong head rotation direction (mot: -0.137,0.264, pre: -0.095,0.167, sd: 0.297, sp: false, val: 6, ctk: 30, att: 0.14) (+1) - ping:90 tps:20.0 lp:1 vl:11
(13:47:58) wrong head rotation direction (mot: 0.266,-0.071, pre: 0.156,-0.02, sd: 0.275, sp: false, val: 2, ctk: 29, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:12
(13:48:00) wrong head rotation direction (mot: 0.039,-0.281, pre: 0.013,-0.169, sd: 0.283, sp: true, val: 2, ctk: 24, att: 0.182) (+1) - ping:90 tps:20.0 lp:1 vl:13
(13:48:00) wrong head rotation direction (mot: -0.044,-0.277, pre: -0.037,-0.16, sd: 0.28, sp: true, val: 3, ctk: 28, att: 0.182) (+1) - ping:88 tps:20.0 lp:1 vl:14
(13:48:00) wrong head rotation direction (mot: 0.026,-0.305, pre: 0.008,-0.207, sd: 0.306, sp: true, val: 4, ctk: 24, att: 0.182) (+1) - ping:88 tps:20.0 lp:1 vl:15
(13:48:00) wrong head rotation direction (mot: 0.029,-0.295, pre: 0.019,-0.19, sd: 0.296, sp: true, val: 5, ctk: 22, att: 0.182) (+1) - ping:88 tps:20.0 lp:1 vl:16
(13:48:00) wrong head rotation direction (mot: 0.066,-0.286, pre: 0.021,-0.187, sd: 0.293, sp: false, val: 6, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:17
(13:48:02) wrong head rotation direction (mot: 0.237,0.155, pre: 0.148,0.084, sd: 0.284, sp: false, val: 2, ctk: 29, att: 0.14) (+1) - ping:88 tps:20.0 lp:1 vl:18
(13:48:03) wrong head rotation direction (mot: -0.266,0.081, pre: -0.158,0.03, sd: 0.278, sp: true, val: 3, ctk: 21, att: 0.182) (+1) - ping:89 tps:20.0 lp:1 vl:19
(13:48:03) wrong head rotation direction (mot: -0.201,0.215, pre: -0.162,0.11, sd: 0.295, sp: false, val: 4, ctk: 30, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:20
(13:48:03) wrong head rotation direction (mot: -0.095,0.296, pre: -0.058,0.207, sd: 0.311, sp: false, val: 5, ctk: 30, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:21
(13:48:03) wrong head rotation direction (mot: -0.095,0.267, pre: -0.052,0.162, sd: 0.284, sp: false, val: 6, ctk: 30, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:22
(13:48:04) wrong head rotation direction (mot: -0.092,0.277, pre: -0.063,0.173, sd: 0.292, sp: false, val: 7, ctk: 30, att: 0.14) (+1) - ping:89 tps:20.0 lp:1 vl:23
(13:48:04) wrong head rotation direction (mot: -0.017,0.285, pre: 0.019,0.176, sd: 0.286, sp: false, val: 2, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:3 vl:24
(13:48:05) wrong head rotation direction (mot: 0.243,0.154, pre: 0.209,0.034, sd: 0.288, sp: false, val: 3, ctk: 30, att: 0.14) (+1) - ping:88 tps:20.0 lp:3 vl:25
**How/when does this happen**: when you run at player while clicking fast
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
direction check is a bad check, I might remove it

**Comment by Maximillus** [comment]
@jiangdashao it a good check to detect killaura like sigma, it just need this false fixed.
