### ISSUE TITLE
[FP] hb.mis

### ISSUE THREAD

**Issue by Hyronymos1337** [jiangdashao/Matrix-Issues#2024]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Verbose messages**: https://paste.twerion.net/ileresumeg.sm
**Video of false positive**: https://www.youtube.com/watch?v=5e7yv3u8L5E

## Configuration Files
**Link to checks.yml file**: premium config example

**Comment by jiangdashao** [comment]
False positives triggered deliberately will not be fixed
