### ISSUE TITLE
[BYPASS] Trident Boost

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#2026]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-2740d5a-da9bb3e (MC: 1.16.3)
**Hacked client**: Inertia
**Link to hacked client**: inertiaclient.com
**Cheat that bypassed**: Trident Boost
**Video of bypass**: https://youtu.be/HPKDVxxTZ5E
**Other information**: Toggle it on and then toggle it off immediatly and it will yeet you up into the air. Yes there is verbose messages, but it's not doing anything else.

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
I accidentally damaged the riptide check in an update
