### ISSUE TITLE
[BYPASS] Horse Jump

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#2027]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-2740d5a-da9bb3e (MC: 1.16.3)
**Hacked client**: Inertia
**Link to hacked client**: inertiaclient.com
**Cheat that bypassed**: Entity Ride
**Video of bypass**: https://youtu.be/j6XpkF1qN4c
**Other information**: Everything up to 1.5 should work 100% at a time.

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Horse check can't be strict due to some Minecraft bugs
