### ISSUE TITLE
[BYPASS] Jesus

### ISSUE THREAD

**Issue by LaserSlimeHD** [jiangdashao/Matrix-Issues#2029]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-2740d5a-da9bb3e (MC: 1.16.3)
**Hacked client**: Inertia
**Link to hacked client**: inertiaclient.com
**Cheat that bypassed**: Jesus
**Video of bypass**: https://youtu.be/rwqP6yNhwC0
**Other information**: It automatically jumps, but it works even better if you manually sprint jump.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Maximillus** [comment]
You flagging, how is it bypass?

**Comment by LaserSlimeHD** [comment]
> 
> 
> You flagging, how is it bypass?

It's only showing verbose messages, but it's not doing anything to really PREVENT me from cheating, which is what anticheats should do, right?

**Comment by jiangdashao** [comment]
it can be prevent, just slow

https://streamable.com/trqaiu

**Comment by LaserSlimeHD** [comment]
Still. A good anticheat shouldn't be slow, or "take a while to detect" Just saying...
