### ISSUE TITLE
[BYPASS] TerrainSpeed - Slime Blocks

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#203]
## Basic Information
**Hacked client**: Nexus b12.2
**Cheat that bypassed**: TerrainSpeed - Slime
**Screenshot of cheat settings**: https://i.imgur.com/Ade5mrU.png
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxQ-PU4h86PZyvcSA

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
It's hard to detect slime speed because the slime block is weird
