### ISSUE TITLE
[FP] move.xz

### ISSUE THREAD

**Issue by DamonOnYT** [jiangdashao/Matrix-Issues#2032]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server

- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config
Somewhat, the Only thing I have changed is what VL you are banned at.

## Issue Information
**Server version**: PaperSpigot 1.16.3
**Verbose messages**:  Available in video. Can provide the log if needed
**How/when does this happen**: When up against a block breaking them, After breaking it with togglespring on it seems to trigger on speed.
**Video of false positive**: https://youtu.be/Jk0QPZf_D5M
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/AB6crP8n

**Comment by jiangdashao** [comment]
The speed of the player walking on flat ground is about 0.28, but you hit 0.8~1, please check if there is a problem with your client

**Comment by Green-Sickness** [comment]
@jiangdashao its badlion

**Comment by Maximillus** [comment]
@Green-Sickness badlion client very buggy sir i have many players on facton 1.13 get banned because of it
