### ISSUE TITLE
[ERROR] Player reports that "relog_time" message on the user side will often say "Please wait 0 seconds"

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#2033]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.16.3

**Error(s) found in console**: 
21.09 15:38:51 [Server] INFO player Bob was kicked because of cheating!
21.09 15:38:58 [Server] INFO UUID of player Bob is 
21.09 15:38:58 [Server] INFO Disconnecting com.mojang.authlib.GameProfile@555555[id=,name=Bob,properties={textures=[com.mojang.authlib.properties.Property@1111]},legacy=false] (/192.168.x.x): Please wait 0 seconds before logging back in! 

**How/when does this happen**:
Player seems to possibly reconnect exactly at 7 seconds, but is told to wait 0 seconds. Ideally we shouldn't show 0 seconds, possibly just alter the logic to always show 1 second(s) instead of 0 seconds.

**Other information**: 

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default but change "relog_time" to 7

![image](https://user-images.githubusercontent.com/21042824/93792339-419dc880-fbea-11ea-9276-879eaa1c4962.png)

**Comment by jiangdashao** [comment]
Number accuracy issues
