### ISSUE TITLE
[FP] fly or speed with high latency

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2035]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: fly.els, speed.main, fly.main
**How/when does this happen**: when player is using elytra toggling on and off in the jumping and they have high latency
**Video of false positive**: 
**Other information**: matrix removed vl reduction on speed/fly check for high latency players which is good but it cause false flags when they using the elytra

## Configuration Files
**Link to checks.yml file**: its matrix defaul

**Comment by jiangdashao** [comment]
can't solve
