### ISSUE TITLE
Fly False Report[FP] 

### ISSUE THREAD

**Issue by ExceptedPrism3** [jiangdashao/Matrix-Issues#2036]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: https://pastebin.com/2MRjePTW
**How/when does this happen**: Flying around with elytra at high speed
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/aAtjCCiU

**Comment by jiangdashao** [comment]
1. No video
2. high speed? `move: 0.0,0.0,0.0`??

**Comment by ExceptedPrism3** [comment]
That's what I get, and I do get it a lot. I'm not around them when it happen + it happens randomly
