### ISSUE TITLE
[BYPASS] autoclicker

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#2041]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 paper 
**Hacked client**:  enertia client
**Link to hacked client**: https://inertiaclient.com/
**Cheat that bypassed**: 
**Video of bypass**: https://www.youtube.com/watch?v=yJQ5MAGOK0o&feature=youtu.be
**Other information**: as you can see the cheater, maybe with the included shield

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
1.9+ autoclicker is useless

**Comment by SkyLicks** [comment]
Many 1.12.2 servers including my own programatically modified 1.12.2 to bring 1.8 pvp which being able to keep 1.12 features. So not true! Plz plz fix!

**Comment by jiangdashao** [comment]
it just wait the cooldown and click, it's useless, you can do it with your hand @SkyLicks
