### ISSUE TITLE
[FP] speed.spin / ka.one.6

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2042]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: 
(19:57:43) Kwon failed KillAura check | [(onehit) attack in an abnormal state (pattern: #06)] (+4) | [VL: 150] [Component: ka.one.6] | [Ping: 143] [LP: 14] [TPS: 19.92]
(19:57:43) Kwon failed KillAura check | [(onehit) attack in an abnormal state (pattern: #06)] (+4) | [VL: 154] [Component: ka.one.6] | [Ping: 143] [LP: 14] [TPS: 19.92]
(19:57:43) Kwon failed KillAura check | [(onehit) attack in an abnormal state (pattern: #06)] (+4) | [VL: 158] [Component: ka.one.6] | [Ping: 143] [LP: 14] [TPS: 19.92]

**How/when does this happen**: This happens when you tap the screen on a touch screen monitor.
**Video of false positive**: Sorry, this was reported to me by a staff member on my server. I don't personally have a touch screen device :/

## Configuration Files
**Link to checks.yml file**: Default

**Comment by Maximillus** [comment]
this also happen when you crawling in 1.15 and spin mouse

**Comment by LaserSlimeHD** [comment]
I don't think touchscreens will be supported.

**Comment by jiangdashao** [comment]
Sorry, the principle of these checks is to check whether the mouse movement speed is an integer. I cannot fix this problem unless I remove this check. You can try to disable this check in the configuration file
