### ISSUE TITLE
[BYPASS] speed

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#2045]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: salhack
**Link to hacked client**: https://salhack.com/#section1
**Cheat that bypassed**: 
**Video of bypass**: https://youtu.be/1nhV77Lv73U
**Other information**: speeds work when they damage the cheater

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
stop posting the duplicate video, if you do it again, you will get banned

**Comment by tiktonik114** [comment]
Sorry, I dropped the wrong link, I will soon throw off the bypass link

**Comment by tiktonik114** [comment]
https://youtu.be/N7oeFReCU98 - yes, agree anti-cheat detects. but when the blow goes through it is very strafe
