### ISSUE TITLE
[BYPASS] packet fly

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#2046]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: inertialclient
**Link to hacked client**: https://inertiaclient.com/Download.php
**Cheat that bypassed**: 
**Video of bypass**: https://www.youtube.com/watch?v=NzrxKbwn_r4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
?
duplicate video?

**Comment by tiktonik114** [comment]
no
