### ISSUE TITLE
[REQUEST] matrix improvement

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2047]
**What features/checks do you need?:**
make matrix use protocollib for killaura/hitbox check, instead of bukkit event because it interfere with many plugin, is inaccurate and unprofessional.

**Comment by jiangdashao** [comment]
there are many killaura checks, I can't make all of them use protocollib

**Comment by jiangdashao** [comment]
I

**Comment by WaterTheMelon** [comment]
Maybe some could be made using ProtocolLib with the option to turn on the bukkit event ones?

**Comment by jiangdashao** [comment]
can you provide the verbose messages? I will improve the incompatible check
