### ISSUE TITLE
[FP] Fly on slimeblock

### ISSUE THREAD

**Issue by assasin541** [jiangdashao/Matrix-Issues#2048]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.,8
**Verbose messages**: 
(23:36:32) assasin541 Fly | suspicious movement:0.0 predict:-1.023/-0.966 air_t:12 s:false tag:m1 (+15) | vl:183 ping:46 tps:20.0 component: fly.main
(23:36:32) assasin541 Fly | suspicious movement:0.0 predict:-1.023 air_t:12 e_t:5 tag:tk (+4) | vl:187 ping:46 tps:20.0 component: fly.main
(23:36:32) assasin541 Fly | suspicious movement:-1.023 predict:-0.078 lm:0.0 hard_pred:-0.078 sev_pred:-1.025 air_t:12 fall_t:1 g:-- tag:gn (+5) | vl:192 ping:46 tps:20.0 component: fly.main
(23:35:40) assasin541 Fly | step | p: 1 | m:1.93 ev:1.897 lm:0.99 (+8) | vl:144 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.813 ev:1.781 lm:0.99 (+8) | vl:152 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.699 ev:1.667 lm:0.99 (+8) | vl:160 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.586 ev:1.555 lm:0.99 (+8) | vl:168 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.476 ev:1.446 lm:0.99 (+8) | vl:176 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541  Fly | step | p: 1 | m:1.368 ev:1.338 lm:0.99 (+8) | vl:184 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.262 ev:1.233 lm:0.99 (+8) | vl:192 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.159 ev:1.13 lm:0.99 (+8) | vl:200 ping:54 tps:20.0 component: speed.step
(23:35:40) assasin541 Fly | step | p: 1 | m:1.057 ev:1.029 lm:0.99 (+8) | vl:208 ping:54 tps:20.0 component: speed.step

**How/when does this happen**: it's simple just jump from some blocks up like 40/50 on 1.16.3 on the slimeblock
**Video of false positive**: i don't think if its needed, if yes i will try to record
**Other information**: 1.16.3 client

## Configuration Files
**Link to checks.yml file**: default, skip rate 3

**Comment by jiangdashao** [comment]
if you want to get banned again, you can try again without posting the video

**Comment by assasin541** [comment]
@jiangdashao you really need the video of me jumpin on slime block? Give me couple minutes...

**Comment by assasin541** [comment]
@jiangdashao (17:08:07) assasin541 Fly | step-1/1 | slime | m:2.620121189210405 b:-2.063689118167052 l:0.99 (+9) | vl:9 ping:52 tps:20.0 component: speed.step
(17:08:07) assasin541 Fly | step | p: 1 | m:2.489 ev:0.42 lm:0.99 (+8) | vl:17 ping:52 tps:20.0 component: speed.step
(17:08:07) assasin541 Fly | step | p: 1 | m:2.361 ev:0.333 lm:0.99 (+8) | vl:25 ping:52 tps:20.0 component: speed.step
(17:08:07) assasin541 Fly | step | p: 1 | m:2.236 ev:0.248 lm:0.99 (+8) | vl:33 ping:52 tps:20.0 component: speed.step
(17:08:07) assasin541 Fly | step | p: 1 | m:2.112 ev:0.165 lm:0.99 (+8) | vl:41 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.992 ev:0.083 lm:0.99 (+8) | vl:49 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.874 ev:0.003 lm:0.99 (+8) | vl:57 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.758 ev:-0.078 lm:0.99 (+8) | vl:65 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.644 ev:-0.155 lm:0.99 (+8) | vl:73 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.533 ev:-0.231 lm:0.99 (+8) | vl:81 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.424 ev:-0.304 lm:0.99 (+8) | vl:89 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.317 ev:-0.377 lm:0.99 (+8) | vl:97 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | step | p: 1 | m:1.212 ev:-0.447 lm:0.99 (+8) | vl:105 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | suspicious movement:1.212 predict:1.212/-0.447 air_t:12 s:true tag:m1 (+15) | vl:120 ping:52 tps:20.0 component: fly.main
(17:08:08) assasin541 Fly | step | p: 1 | m:1.11 ev:-0.517 lm:0.99 (+8) | vl:128 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | suspicious movement:1.11 predict:1.109/-0.517 air_t:12 s:true tag:m1 (+15) | vl:143 ping:52 tps:20.0 component: fly.main
(17:08:08) assasin541 Fly | step | p: 1 | m:1.009 ev:-0.585 lm:0.99 (+8) | vl:151 ping:52 tps:20.0 component: speed.step
(17:08:08) assasin541 Fly | suspicious movement:1.009 predict:1.009/-0.585 air_t:12 s:true tag:m1 (+15) | vl:166 ping:52 tps:20.0 component: fly.main
(17:08:08) assasin541 Fly | suspicious movement:0.719 predict:0.719/-0.781 air_t:12 s:false tag:m1 (+15) | vl:181 ping:52 tps:19.98 component: fly.main
(17:08:08) assasin541 Fly | suspicious movement:0.626 predict:0.626/-0.844 air_t:12 s:false tag:m1 (+15) | vl:196 ping:52 tps:19.98 component: fly.main
(17:08:08) assasin541 Fly | suspicious movement:0.535 predict:0.535/-0.905 air_t:12 s:false tag:m1 (+15) | vl:211 ping:52 tps:19.98 component: fly.main
(17:08:08) assasin541 Fly | suspicious movement:0.446 predict:0.446/-0.966 air_t:12 s:false tag:m1 (+15) | vl:226 ping:52 tps:19.98 component: fly.main
