### ISSUE TITLE
[FP] velocity

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2049]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
(respond) ignore server velocity: -0.323,0.42,0.535 (+5) - ping: 120 tps:20.0 lp:15 vl:5 vel.expect
(respond) ignore server velocity: 0.616,0.161,0.104 (+5) - ping: 576 tps:20.0 lp:21 vl:10 vel.expect
(vertical) reduce vertical velocity: 0.16075 (+1) - ping: 576 tps:20.0 lp:21 vl:11 vel.vet
(respond) ignore server velocity: 0.518,0.161,0.349 (+5) - ping: 576 tps:20.0 lp:21 vl:16 vel.expect
(vertical) reduce vertical velocity: 0.16075 (+1) - ping: 576 tps:20.0 lp:21 vl:17 vel.vet
**How/when does this happen**: when player lag out and stop responding to the velocity
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its default matrix

**Comment by jiangdashao** [comment]
you can increase the `wait_time`
