### ISSUE TITLE
[BYPASS] Ghost Hand

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#205]
## Basic Information
**Hacked client**: Nexus b12.2
**Cheat that bypassed**: GhostHand
**Screenshot of cheat settings**: https://i.imgur.com/cITPEs6.png
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxUcc-o1b0KTkiohw

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
![B@D3RQ2PQYR_Z67P2KDV(Q6](https://user-images.githubusercontent.com/21152113/56404600-1b0f8b80-629a-11e9-8ea1-7d3722da086c.png)

**Comment by jiangdashao** [comment]
It looks like a tree.cc's bug
But Matrix works well in my test server
