### ISSUE TITLE
[FP] 1.16 Auto drop feature false positive

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2052]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 (but client version is 1.16.3)
**Verbose messages**: In the below linked video...
**How/when does this happen**: When you go on client version 1.16+, and hold Q to drop items, the 1.16 auto drop feature will appear to Matrix as an autoclicker.
**Video of false positive**: https://youtu.be/GDXARbZm9ic
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I can't reproduce it
