### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2053]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Many different autoclickers
**Link to hacked client**: 
- https://sourceforge.net/projects/orphamielautoclicker/
- https://tapclient.weebly.com/
**Cheat that bypassed**: Autoclicker
**Video of bypass**: https://youtu.be/A3UJNzDWoaA
**Other information**: Some of the clickers are basic and blatant autoclicker but Matrix was only able to detect is slowly and only because I didn't stop clicking. Yes, others are more discrete like the TapClient autoclicker but I think the autoclicker check needs an upgrade! Even though this is a 1.12.2 server, many servers including mine have plugins to make it appear to be 1.8 PvP! 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by SkyLicks** [comment]
Even the Tap Client autoclicker is not impossible to detect. Even though it has random click delays, if you look at the big picture, the average click speed over a longer period of time still is the same. Real peoples CPS varies more. Real peoples fingers get tired after a long time and their CPS goes down.

**Comment by jiangdashao** [comment]
AAC/Reflex can't detect it too, I suggest you code an anti-auto clicker by yourself
