### ISSUE TITLE
[FP] Groundspoof with boating

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2056]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
ground spoof (expect: --, move: 0.083,0.0,-0.053, at: 948.08,63.086,-2771.485, type: air, pkt: false)
ground spoof (expect: --, move: 0.046,0.0,-0.029, at: 948.125,63.086,-2771.514, type: air, pkt: false)
 ground spoof (expect: --, move: 0.038,0.0,-0.024, at: 948.164,63.086,-2771.538, type: air, pkt: false)
**How/when does this happen**: when a laggy player exits the boat
**Video of false positive**: 
**Other information**: when they leave boat, on player screen they are standing on the boat (y coord of false flag always end with .08576534715491 because it is height of boat) but on server the boat moved away. You can check for the false positive like this:
if (data.lastboatexit was <10 seconds ago && isBoatGlitched(player.getlocation)){dont flag}

private boolean isBoatGlitched(Location l) {
        Material at = l.clone().add(0, -0.084, 0).getBlock().getType();
        Material under = l.clone().add(0, -0.086, 0).getBlock().getType();
        return at.isAir() && under == Material.WATER;
    }

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
I can't understand, video please?

**Comment by Maximillus** [comment]
@jiangdashao https://github.com/jiangdashao/Matrix-Issues/issues/1869 this is the same issue

**Comment by jiangdashao** [comment]
1. I cannot reproduce this bug
2. I have checked if the player is standing on the boat
