### ISSUE TITLE
[BYPASS] FastBreak

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#206]
## Basic Information
**Hacked client**: Nexus b12.2
**Cheat that bypassed**: FastBreak
**Screenshot of cheat settings**: https://i.imgur.com/xT7Z0UD.png
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxWK23FlSg6OMLdQQ

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
It's hard to detect
