### ISSUE TITLE
[BYPASS] WaterSpeed

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2061]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-17d78db-2577f9b (MC: 1.16.3)
**Hacked client**: Wurst
**Link to hacked client**: wurstclient.net
**Cheat that bypassed**: NoWaterPush
**Video of bypass**: https://youtu.be/DZXcvINaTmk
**Other information**: Allows you to move freely in water. Sprinting will cause weird glitches and flags, but it works fine without sprinting. (I know wurst sux but still)

**Comment by jiangdashao** [comment]
won't fix it
