### ISSUE TITLE
[BYPASS] Jesus

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2063]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-17d78db-2577f9b (MC: 1.16.3)
**Hacked client**: Inertia
**Link to hacked client**: inertiaclient.com
**Cheat that bypassed**: Boat Phase
**Video of bypass**: https://youtu.be/XvhOMJIOPGo
**Other information**: I have no idea why this is working, but it works...

**Comment by jiangdashao** [comment]
set ignore swim pose to `false`
