### ISSUE TITLE
[FP] Fly & Speed

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2066]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-229 (MC: 1.16.3)
**Verbose messages**: 
(07:16:08) Player failed Speed check | sprint with weird direction (dist: 0.235, angle:110.001) (+5) | vl:5 ping:0 tps:19.99 lp:0 component: speed.sprint
(07:18:22) Player failed Fly check | step | p:2 | val: 0.4375 (+7) | vl:7 ping:0 tps:20.0 lp:7 component: speed.step
(07:18:22) Player failed Fly check | suspicious movement:0.438 predict:0.338 vel:0.333 air_t:1 tag:vt (+5) | vl:12 ping:0 tps:20.0 lp:7 component: fly.main
(07:18:22) Player failed Fly check | step | p:3 (+4) | vl:16 ping:0 tps:20.0 lp:7 component: speed.step
(07:19:25) Player failed Fly check | suspicious movement:0.387 predict:0.301 air_t:1 tag:sam (+5) | vl:5 ping:14 tps:19.99 lp:14 component: fly.main
(07:19:25) Player failed Fly check | suspicious movement:0.387 predict:0.338 vel:0.333 air_t:1 tag:vt (+5) | vl:10 ping:14 tps:19.99 lp:14 component: fly.main
(07:19:27) Player failed Fly check | suspicious movement:0.387 predict:0.301 air_t:1 tag:sam (+5) | vl:15 ping:14 tps:19.87 lp:9 component: fly.main
(07:19:27) Player failed Fly check | suspicious movement:0.387 predict:0.338 vel:0.333 air_t:1 tag:vt (+5) | vl:20 ping:14 tps:19.87 lp:9 component: fly.main
(07:19:31) Player failed Fly check | suspicious movement:0.387 predict:0.338 vel:0.42 air_t:1 tag:vt (+5) | vl:25 ping:19 tps:19.77 lp:5 component: fly.main
(07:24:12) Player failed Speed check | change direction in mid-air (dist: 0.281, angle:99.935, pre:0.261) (+5) | vl:5 ping:29 tps:20.0 lp:3 component: speed.strafe
(07:25:09) Player failed Elytra check | (elytra) reserve energy: 0.56 dif: 0.08 motion: 0.128 t: 1046 (+2) | vl:2 ping:18 tps:18.61 lp:3 component: ely.re
(07:30:24) Player failed Speed check | suspicious movement (move: 0.47, vet: 0.389, tag: d) (+8) | vl:8 ping:16 tps:20.0 lp:10 component: speed.main
(07:30:24) Player failed Fly check | suspicious movement:0.389 predict:0.303 air_t:1 tag:sam (+5) | vl:5 ping:16 tps:20.0 lp:10 component: fly.main
(07:30:24) Player failed Fly check | suspicious movement:0.389 predict:0.338 vel:0.333 air_t:1 tag:vt (+5) | vl:10 ping:16 tps:20.0 lp:10 component: fly.main
(07:30:42) Player failed Speed check | suspicious movement (0.308, air_t: 12, lm:0.279 acc: 0.029066482365730006, tag: ed) (+15) | vl:15 ping:18 tps:20.0 lp:20 component: speed.main
(07:30:42) Player failed Speed check | suspicious movement (move: 0.503, vet: 0.391, tag: d) (+8) | vl:23 ping:18 tps:20.0 lp:20 component: speed.main
(07:30:42) Player failed Speed check | suspicious movement (move: 0.51, expect: 0.3665, tag: ea) (+5) | vl:28 ping:18 tps:20.0 lp:20 component: speed.main
(07:30:42) Player failed Speed check | suspicious movement (move: 0.51, predict: 0.301, friction: 0.6, ground:false, motY: 0.391, increase:0.026, preMove:0.275, motion: -0.473,0.391,-0.19, attribute: 0.13, tag: pred) (+5) | vl:33 ping:18 tps:20.0 lp:20 component: move.xz
(07:30:42) Player failed Fly check | suspicious movement:0.391 predict:0.304 air_t:1 tag:sam (+5) | vl:5 ping:18 tps:20.0 lp:20 component: fly.main
(07:30:42) Player failed Fly check | suspicious movement:0.391 predict:0.338 vel:0.333 air_t:1 tag:vt (+5) | vl:10 ping:18 tps:20.0 lp:20 component: fly.main
**How/when does this happen**: 
When jumping and sprinting with elytra.

**Comment by WaterTheMelon** [comment]
Elytra Fly is REALLY buggy with high ping players turn off the check "force_setback" under ElytraFly
I would suggest to the owner of this plugin to suggest this in the check.yml config

**Comment by jiangdashao** [comment]
it's a desync, I can't fix that
