### ISSUE TITLE
[REQUEST] Cloud language.yml

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2069]
**What features/checks do you need?:**
Like with the cloud checks feature, large networks may change the language file and need to sync it across servers. Especially now that custom global placeholders were added, and the checks file needs the language file to access them.

Currently, that is not possible, only `checks.yml` can be synced from a repo.
If implemented, this would work the same as the current cloud system, but with the language file.

**Comment by jiangdashao** [comment]
language.yml is usually not updated frequently, I don’t think it needs to be loaded from the cloud
