### ISSUE TITLE
[BYPASS] jesushacken

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2072]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: WWE
**Link to hacked client**: 
**Cheat that bypassed**: jesus
**Other information**: Walk on lava with the jesus hack you don't damage and matrix doesn't detect.

## Configuration Files
**Link to checks.yml file**: matrix default
**Link to config.yml file**: matrix default

**Comment by jiangdashao** [comment]
set  `jesus.ignore_swim_pose` to `false`

**Comment by Maximillus** [comment]
@jiangdashao https://streamable.com/b6gsyc default matrix config

**Comment by jiangdashao** [comment]
one block deep lava?

**Comment by Maximillus** [comment]
any depth
