### ISSUE TITLE
[FP] fly.nc

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2074]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: fly tag nc
**How/when does this happen**: when you jump in the cobwebs 
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
video please

**Comment by Maximillus** [comment]
@jiangdashao the video here https://streamable.com/0e3ky2
