### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Valeriy54** [jiangdashao/Matrix-Issues#2075]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: KillAura OneHit Pattern #2
**How/when does this happen**: When you click on player after closing or opening shield
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
desync
