### ISSUE TITLE
[BYPASS] jesus

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2076]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.1
**Hacked client**: Inertia (WWE)
**Link to hacked client**: 
**Cheat that bypassed**: Jesus
**Video of bypass**: https://streamable.com/dgaksg
**Other information**: re, you saying "set ignore swim pose true" but swimming give 3.9BPS (block travel per second) while bypass give 12BPS without matrix flag

## Configuration Files
**Link to checks.yml file**: **default matrix check yml**
**Link to config.yml file**: **default matrix config**

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/97951642-dc86e680-1dd5-11eb-8376-1421233d9737.png)

**Comment by jiangdashao** [comment]
ignore_swim_pose will cause matrix always think the player is swiming
