### ISSUE TITLE
🕑 [BYPASS] Phase

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#208]
## Basic Information
**Hacked client**: Nexus b12.2
**Cheat that bypassed**: Phase (All modes except NoClip)
**Video of bypass**: https://1drv.ms/f/s!ApY4tKsF8vPUgoxccaICEu_seJ3ftg

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by ignPerformance** [comment]
Noclip phase bypass as well: #209

**Comment by jiangdashao** [comment]
Not a bug
Phase check won't check some special blocks, because of it's buggy hitbox

**Comment by ignPerformance** [comment]
Blocks that SHOULD be blocked with Phase are doors and fence gates. Those are essential to a phase check, otherwise, you might not even need one. Here's one of hundreds of videos of people RUINING THE GAME for other players by phasing into doors and fence gates. https://youtu.be/bpHKVkmSKHA

Your Phase check is great at blocking full-block phase, sure, but nobody uses full-block. You *need* to block Phase for fence gates and doors. It is 100% necessary.

**Comment by jiangdashao** [comment]
I won't check the door/fence gates phase
