### ISSUE TITLE
[ERROR] matrix ping bug

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2081]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**How/when does this happen**: when a player is play
**Other information**: **#1933 was not fixed** matrix still sometimes says player with 120 ping has 3 ping

## Configuration Files
**Link to checks.yml file**: default matrix config
**Link to config.yml file**: default matrix config

**Comment by jiangdashao** [comment]
because I can't reproduce the transaction packet

**Comment by Maximillus** [comment]
@jiangdashao it is sent when opening/clicking inventory maybe, look at source code minecraft
