### ISSUE TITLE
[BYPASS] Fly with Punch 5 bow

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2083]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8+
**Hacked client**: Sigma (Jello)
**Cheat that bypassed**: Fly
**Video of bypass**: https://streamable.com/o75xgv
**Other information**: Bow has Punch 5. "`you can basically fly a huge distance with a punch 5 bow`"

**Comment by Maximillus** [comment]
@jiangdashao fix for this is give matrix 1.8 slow timer check since move packet in 1.8 every 50ms
