### ISSUE TITLE
[FP] speed.noslow.toggle

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2087]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.1
**Verbose messages**: 
(toggle) send release use item packet frequently (+2) - p:113 t:20.0 lp:5 vl:4
(toggle) send release use item packet frequently (+2) - p:118 t:20.0 lp:5 vl:6
(toggle) send release use item packet frequently (+2) - p:117 t:20.0 lp:6 vl:8
(toggle) send release use item packet frequently (+2) - p:116 t:20.0 lp:6 vl:2
(toggle) send release use item packet frequently (+2) - p:118 t:20.0 lp:6 vl:4
**How/when does this happen**: when you block then unblock fast (5+ cps) it also set you back
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
that's how it works, I can't fix it

**Comment by Maximillus** [comment]
@jiangdashao you need measure rolling average, not just time between 2 block packets. You dont measure autoclicker based on 2 sample because lag. Do same for this.
