### ISSUE TITLE
[BYPASS] Jesus

### ISSUE THREAD

**Issue by hswhsw610** [jiangdashao/Matrix-Issues#2088]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity 1.16.3
**Hacked client**: Sigma 5.0
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: Jesus
**Video of bypass**: https://streamable.com/tm0g84
**Other information**: well... jesus is bypassed by fly... matrix sometimes setback me.. but it took so long..

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
it's packet fly, not jesus

**Comment by hswhsw610** [comment]
Anyway it's working... :(
