### ISSUE TITLE
[REQUEST] matrix platforms

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2089]
**What features/checks do you need?:**
Matrix should be sold on spigotMC, it will make it more users. Also i know matrix remove from spigot because obfuscation, but why not just use normal instead of heavy obfuscate

**Comment by jiangdashao** [comment]
This may cause Matrix to be easily cracked, but I will try

**Comment by jiangdashao** [comment]
oops, spigot rules do not allow the license system
