### ISSUE TITLE
[ERROR] Server stops after 10-15 seconds after logging player

### ISSUE THREAD

**Issue by PerchunPak** [jiangdashao/Matrix-Issues#2090]
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version: Paper 1.12.2 build 1618**: 
**Error in console:
[10:36:55 INFO]: [AuthMe] Player logged in 127.0.0.1 (if not localhost - too work)
[10:37:21 INFO]: Stopping the server**: 
**When issue hapends? When player loging to server + 10-15 seconds**: 
**Matrix last version, and if player dont join it doesn't stop (tested)**: 

## Configuration Files
**Link to checks.yml file - default** 
**Link to config.yml file - default**

**Comment by PerchunPak** [comment]
also matrix updater
![image](https://user-images.githubusercontent.com/68118654/97964591-b0616a80-1dc1-11eb-96c8-2511af1fde36.png)

**Comment by jiangdashao** [comment]
can you send me your matrix log file? in `/Matrix/logs`

**Comment by PerchunPak** [comment]
[matrix_log_2020-11-03.txt](https://github.com/jiangdashao/Matrix-Issues/files/5480356/matrix_log_2020-11-03.txt)

**Comment by jiangdashao** [comment]
Where did you download Matrix from?

**Comment by jiangdashao** [comment]
Did you modify the Matrix Jar?

**Comment by PerchunPak** [comment]
i downoloading from discord. no, i did not modify anything

**Comment by jiangdashao** [comment]
dm me in discord
