### ISSUE TITLE
[INCOMPATIBILITY] Craftbook signs (pipes and ICs)

### ISSUE THREAD

**Issue by xenoflot** [jiangdashao/Matrix-Issues#2092]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] The incompatible plugin is up-to-date
- [ X] Matrix and ProtocolLib are up-to-date (PL v4.6.0-SNAPSHOT-b482 Matrix Free 5.3.1)
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [ X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.3 Paper 246
**Incompatible plugin**:  CraftBook v3.10.2;21180b0
**Verbose messages (or) console errors**: n/a
**How/when does this happen**: Consistently
**Video of incompatibility**: not supplied
**Other information**: 

I have Craftbook and when my players try to create a [pipe], they get a cryptic error "area.use-permission" and the sign drops on the ground.  The same error is given when trying to create a Craftbook IC.
As an op, I do not have this problem.  
With Matrixfree removed, they do not have this problem.  
Searching the error in question leads me to this issue with another anti-cheat that, from a quick scan, suggests that https://github.com/NoCheatPlus/Issues/issues/201
Not saying that's the problem, but it's all I've got so far!

## Configuration Files
Config files have not been edited. We simply installed the matrix jar file and fired up the server.

**Comment by jiangdashao** [comment]
Please provide the verbose messages! (/matrix verbose), and, record a video

**Comment by xenoflot** [comment]
Unbelievable. I can't reproduce it now. Only difference that I can think of is having rebooted the server a couple of times. Oh well. I'll lodge again if the problem returns.
