### ISSUE TITLE
[ERROR] Matrix hangs server with unloaded chunks

### ISSUE THREAD

**Issue by KaxonDev** [jiangdashao/Matrix-Issues#2093]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.3 Tuinity
**Error(s) found in console**: [https://pastebin.com/bTKZ92gw](https://pastebin.com/bTKZ92gw)
**How/when does this happen**: Randomly occurs on world generation or deletion
**Other information**: The plugin needs to check if the chunk is loaded before doing things.

## Configuration Files
**Link to checks.yml file**: premium checks
**Link to config.yml file**: default config

**Comment by AoElite** [comment]
Matrix should make sure to check if the chunk is loaded before performing a action on it. So these hangs cannot occur.
