### ISSUE TITLE
SPeed Hacks [BYPASS] 

### ISSUE THREAD

**Issue by MarcusVosper** [jiangdashao/Matrix-Issues#2095]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.3
**Hacked client**: Aristois
**Link to hacked client**: https://aristois.net/
**Cheat that bypassed**: Speed Hacks
**Video of bypass**: https://www.youtube.com/watch?v=3DognLTaaHY
**Other information**: This has also been the case for Entity Riding. One of our players managed to travel to over a million in 40 minutes. I also have a video of one player riding a horse very fast - https://www.youtube.com/watch?v=GPHLHk9ygn0

## Configuration Files
**Link to checks.yml file**: https://pastebin.pl/view/6fab7d45
**Link to config.yml file**: https://pastebin.pl/view/534ab1eb

**Comment by Maximillus** [comment]
matrix clear not enabled in this video. check console maybe

**Comment by MarcusVosper** [comment]
I had reset the config file for myself however a player is still being able to bypass this --> https://www.youtube.com/watch?v=iraUi81Q92E


This is also being shown in the console: https://pastebin.com/gAvN0CU2

**Comment by jiangdashao** [comment]
Matrix does not have the vehicle speed check for LLAMA
