### ISSUE TITLE
[BYPASS] speed.sprint

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2097]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: WWE
**Cheat that bypassed**: sprint
**Video of bypass**: 
**Other information**: You can sprint sidewards, 90 degree angle, not backward however

## Configuration Files
**Link to checks.yml file**: its default matrix
**Link to config.yml file**: its default matrix

**Comment by jiangdashao** [comment]
I can't improve it
