### ISSUE TITLE
Jesus FP

### ISSUE THREAD

**Issue by DmitryRendov** [jiangdashao/Matrix-Issues#21]
## How you trigger the false positive?
Just swim and keep your head above the water. That's enough.

## Verbose Message:
(16:40:50) WaterDemon failed Jesus check | t:jesus-6  a:0.0 (+7) | vl:21 ping:105 tps:20.0
(16:40:52) WaterDemon failed Jesus check | t:jesus-6  a:0.0 (+7) | vl:28 ping:105 tps:20.0
(16:40:55) WaterDemon failed Jesus check | t:jesus-6  a:0.0 (+7) | vl:35 ping:105 tps:20.0

## Videos:
https://youtu.be/SfXjXqIqbyc

## Server Infomation
Matrix AntiCheat (1.1.9)
git-Spigot-f56e2e7-b634e05 (MC: 1.13.2)
ProtocolLib v4.4.0

**Comment by jiangdashao** [comment]
Fixed
