### ISSUE TITLE
[BYPASS] make matrix vehicle check for every ridable entity and future ridable entities

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2101]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Hacked client**: any 
**Cheat that bypassed**: entity speed
**Video of bypass**: 
**Other information**: check if player.getVehicle() instanceof Vehicle && !(player.getVehicle() instanceof Minecart)(https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Vehicle.html) for vehicle check it all you need, no entity type and updating because spigot doing it automatically. It prevent the mistake with llama speed in future

## Configuration Files
**Link to checks.yml file**: its default matrix
**Link to config.yml file**: its default matrix

**Comment by jiangdashao** [comment]
the different entity has a different speed

**Comment by Maximillus** [comment]
Just store the expected speeds in a hashmap, (entitytype,float), if vehicle is not in hashmap then just set max speed high so they can speed a little bit but not gamebreaking
