### ISSUE TITLE
[FP] Matrix error SkyWars capsule start

### ISSUE THREAD

**Issue by alexeses** [jiangdashao/Matrix-Issues#2105]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12
**Verbose messages**: 
**How/when does this happen**: I have a bungeemode SkyWars with more than 200 players online, the problem happens when a game is about to start, the player's capsule disappears and the player sometimes dies directly or is automatically teleported to the ground with damage caused. This is caused by the antihacack because in the same logs it is shown: https://prnt.sc/vi64pk. I have tried it with the normal configuration and the premium configuration (I am a buyer of the matrix). The problem keeps happening, I get a lot of continuous complaints.
**Video of false positive**: https://prnt.sc/vi64pk 
**Other information**: It happens sometimes, you can try it playing on my server mc.minebox.es (Hispanic community, SkyGames mode)

## Configuration Files
**Link to checks.yml file**: https://paste.ubuntu.com/p/Qvg4GbXmkn/

**Comment by alexeses** [comment]
Without a doubt, it is a fly check error

> Log matrix: https://paste.ubuntu.com/p/vDGfDHM5g8/

**Comment by jiangdashao** [comment]
use matrix API to register a client block
