### ISSUE TITLE
[FP] ground spoof

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2106]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.394,0.0,-0.114, at: -3954.779,64.0,-2599.271, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:5 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.386,0.0,-0.115, at: -3954.394,64.0,-2599.386, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:10 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.38,0.0,-0.119, at: -3954.014,64.0,-2599.505, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:15 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.376,0.0,-0.124, at: -3953.638,64.0,-2599.629, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:20 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.338,0.0,-0.127, at: -3953.3,64.0,-2599.756, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:25 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.0,0.0,-0.118, at: -3953.3,64.0,-2599.874, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:30 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.0,0.0,-0.122, at: -3953.3,64.0,-2599.996, type: air, pkt: false) (+5) - ping:94 tps:20.0 lp:10 vl:35 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.0,0.0,-0.126, at: -3953.3,64.0,-2600.122, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:40 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.0,0.0,-0.129, at: -3953.3,64.0,-2600.251, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:45 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.048,0.0,-0.202, at: -3953.252,64.0,-2600.453, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:50 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.083,0.0,-0.238, at: -3953.17,64.0,-2600.691, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:55 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.129,0.0,-0.242, at: -3953.041,64.0,-2600.934, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:60 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.07,0.0,-0.132, at: -3952.97,64.0,-2601.066, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:65 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.038,0.0,-0.072, at: -3952.932,64.0,-2601.138, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:70 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.157,0.0,-0.019, at: -3952.775,64.0,-2601.157, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:10 vl:75 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.216,0.0,0.031, at: -3952.559,64.0,-2601.125, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:80 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.118,0.0,0.017, at: -3952.441,64.0,-2601.108, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:85 - fly.gf
(16:16:52) player: Fly - ground spoof (expect: --, move: 0.064,0.0,0.009, at: -3952.377,64.0,-2601.099, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:90 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.205,0.0,0.059, at: -3952.171,64.0,-2601.04, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:95 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.282,0.0,0.086, at: -3951.89,64.0,-2600.953, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:100 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.324,0.0,0.101, at: -3951.566,64.0,-2600.852, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:105 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.347,0.0,0.109, at: -3951.219,64.0,-2600.743, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:110 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.359,0.0,0.114, at: -3950.859,64.0,-2600.629, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:115 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.366,0.0,0.116, at: -3950.493,64.0,-2600.513, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:120 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.371,0.0,0.113, at: -3950.122,64.0,-2600.4, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:125 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.375,0.0,0.1, at: -3949.747,64.0,-2600.3, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:130 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.339,0.0,0.0, at: -3949.408,64.0,-2600.3, type: air, pkt: false) (+5) - ping:77 tps:20.0 lp:9 vl:135 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.321,0.0,0.0, at: -3949.087,64.0,-2600.3, type: air, pkt: false) (+5) - ping:82 tps:20.0 lp:9 vl:140 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.312,0.0,0.0, at: -3948.775,64.0,-2600.3, type: air, pkt: false) (+5) - ping:82 tps:20.0 lp:9 vl:145 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.308,0.0,0.0, at: -3948.467,64.0,-2600.3, type: air, pkt: false) (+5) - ping:82 tps:20.0 lp:9 vl:150 - fly.gf
(16:16:53) player: Fly - ground spoof (expect: --, move: 0.304,0.0,-0.014, at: -3948.163,64.0,-2600.314, type: air, pkt: false) (+5) - ping:82 tps:20.0 lp:9 vl:155 - fly.gf
**How/when does this happen**: player who are on the ground randomly flag ground spoof
**Video of false positive**: https://imgur.com/DbbIqDz red box represent player move while flagging (they on ground and touch villager house)
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
record a video
