### ISSUE TITLE
[FP] Placing blocks under you

### ISSUE THREAD

**Issue by NgLoader** [jiangdashao/Matrix-Issues#2107]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:
1.16.4-R0.1

**Verbose messages**: 
- **** failed Fly check | suspicious movement:0.165 predict:0.165 vel:-0.152 air_t:12 tag:m4 (+0) | vl:0 ping:30 tps:9.07 lp:6 component: fly.main
- **** failed Fly check | suspicious movement:0.083 predict:-0.078 vel:-0.152 air_t:12 tag:m4 (+0) | vl:0 ping:30 tps:9.07 lp:6 component: fly.main
- **** failed Fly check | suspicious movement:0.165 predict:0.165 vel:-0.302 air_t:12 tag:m4 (+0) | vl:0 ping:30 tps:9.54 lp:15 component: fly.main

**How/when does this happen**:
When you place blocks under you

**Video of false positive**:
https://youtu.be/K3HtcqbKbK8 (0:56)

**Other information**:
 tested this with a normal 1.16.4 client

**Comment by jiangdashao** [comment]
TPS 9

**Comment by NgLoader** [comment]
The TPS are usually 19.8-20 * and are on 9 (very rare) for about 1 second witch reproduce this. Is it able to set a tps limit for fly checks?

**Comment by jiangdashao** [comment]
can't fix
