### ISSUE TITLE
[FP] sfd.place.o

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2110]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
scaffold-like placement | type O +7vl ping: 228
scaffold-like placement | type C +7vl ping: 227
scaffold-like placement | type O +7vl ping: 228
**How/when does this happen**: when the player is speedbridging they flagging sfd.place.o
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
video

**Comment by jiangdashao** [comment]
what's your discord name? okdude? @Maximillus

**Comment by WaterTheMelon** [comment]
@jiangdashao @Maximillus  I've noticed this too though you can just fix it by turning down the "min_delay:"
