### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by Maciek2136** [jiangdashao/Matrix-Issues#2111]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 paper
**Hacked client**: Flux B21
**Link to hacked client**: flux.today
**Cheat that bypassed**: Speed AACSlowHop
**Video of bypass**: https://youtu.be/412GMamFZdQ
**Other information**:

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I don't have client
