### ISSUE TITLE
[BYPASS] Speedmine/Nuker

### ISSUE THREAD

**Issue by radek203** [jiangdashao/Matrix-Issues#2112]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 [GuardSpigot]
**Hacked client**: Huzuni 1.8 [3.5]
**Link to hacked client**: https://megawrzuta.pl/download/96ca7b98261814af9b366790a4a51768.html
**Cheat that bypassed**: speedmine/nuker
**Video of bypass**: https://youtu.be/KFAOS6hVEKQ?t=30
**Other information**: after a short time you can dig under the speedmine and the nuker works without any problems

## Configuration Files
**Link to checks.yml file**: default...
**Link to config.yml file**: default... with my premium...

**Comment by jiangdashao** [comment]
useless cheat

**Comment by radek203** [comment]
> useless cheat

don't you see that you can then dig the speedmine normally with the nuker?

**Comment by jiangdashao** [comment]
the nuker is legit, it just digs blocks around you

**Comment by radek203** [comment]
But I say that when I have a nuker, SPEEDMINE works here too

**Comment by jiangdashao** [comment]
no, it was blocked, and you got kicked

**Comment by radek203** [comment]
see 1:50 and later
