### ISSUE TITLE
[FP] ground spoof

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2113]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
ground spoof (expect: --, move: 0.0,0.0,0.0, at: -243.7,74.5,-462.8, type: air, pkt: false) (+5)
ground spoof (expect: --, move: 0.0,0.0,0.0, at: -243.7,74.5,-462.8, type: air, pkt: false) (+5)
ground spoof (expect: --, move: 0.0,0.0,0.0, at: -243.7,74.5,-462.8, type: air, pkt: false) (+5)
**How/when does this happen**: when player does an enderpearl teleport into the wall where their head is in stairs
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its default matrix

**Comment by jiangdashao** [comment]
can't reproduce
