### ISSUE TITLE
[BYPASS] Avoiding Matrix Rubber Bands

### ISSUE THREAD

**Issue by WaterTheMelon** [jiangdashao/Matrix-Issues#2114]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [  ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Impact
**Link to hacked client**: 
**Cheat that bypassed**: Most Movement hacks
**Video of bypass**: 
**Other information**:
From what I've seen with this Matrix's checks are not at fault its entirely how the back system works. To break the back point you need to get far enough from your previous back point without setting new back points, I have discovered this can be done in various ways (I'm assuming their a many other ways you could do this.) using anti hunger and hopping away, using anti hazard and walking on pressure plates, and you can just grab some boats and hop away on those. Once you do this you never need to worry about rubber banding until you reconnect to the server, you bypass every fly that isn't too fast and a lot of the speed checks hardly even rubber band you properly,

Anyways other than this Matrix is a pretty damn good anti cheat ignoring this issue and I can see how this was overlooked I hope my report helps make Matrix better. :)

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
thank you, I never realized this
