### ISSUE TITLE
[ERROR] Matrix 5.3.1 not working with Velocity Proxy

### ISSUE THREAD

**Issue by 3xpl0itz** [jiangdashao/Matrix-Issues#2117]
## Troubleshooting Information
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Velocity v1.1.0
**Error(s) found in console**:   

`[01:58:59` ERROR]: Unable to load plugin plugins/Matrix_5.3.1_hotfix_2_release.jar
     at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoa
der.java:47) ~[velocity_proxy.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:76)
 ~[velocity_proxy.jar:1.1.0]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:268) ~[velocity_proxy.ja
r:1.1.0]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:210) ~[velocity_proxy.jar:1.1.
0]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:55) ~[velocity_proxy.jar:1.1.0]
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.`

**How/when does this happen**: On startup, no matter which version you install. This happens on 5.3.0 as well.
![Capture](https://user-images.githubusercontent.com/37809476/99887860-d463df00-2bfc-11eb-9642-9b759baa1c2a.PNG)

**Comment by flumf** [comment]
Alright so the bug itself is kind of weird, not sure why this happened but if you look at the jarfile (I'm working with Matrix_5.3.1_hotfix_2_release.jar (SHA256: 3babbfde2d676e213d71073860c5ce86c7ee5b42d94a612f3dcb746bbed4ce6e)) you'll notice that at the top of it there's 41 extra bytes before the PK header: match: 5.3.1_HOTFIX_2 <==> 5.3.1_HOTFIX_2.

Removing this allows velocity to properly detect the velocity-plugin.json. Not sure what it's doing there or if it's important but hey, if it works it works.

**Comment by 3xpl0itz** [comment]
@flumf 's method worked perfectly. Thanks legend
