### ISSUE TITLE
[REQUEST] Override config

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2121]
**What features/checks do you need?:**
An "override config" which changes certain values of an existing config.
This will allow users to auto-update a cloud config and have certain values changed in the parsed config.
It will also allow for networks to have a base config and change certain values for minigames, skyblock, anarchy, etc.

This could be achieved by loading the base config, loading the override config, then merging the override config over the base config.

**Example:**
checks.yml:
```
...
killaura:
    enabled: true
    modules:
        ...
```

checks.override.yml
```
killaura:
    enabled: false
```

parsed result:
```
...
killaura:
    enabled: false
    modules:
        ...
```

**Comment by jiangdashao** [comment]
Now that there is a cloud configuration file, the server can use a different link to load the configuration file
