### ISSUE TITLE
[ERROR] NullPointerException

### ISSUE THREAD

**Issue by AoElite** [jiangdashao/Matrix-Issues#2123]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Latest 1.16.4 Tuinity
**Error(s) found in console**: https://pastebin.com/HvFvd3xh
**How/when does this happen**: I don't know, my guess is it has something to do with the killaura bot.
**Other information**: None

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by Etheride** [comment]
Give full logs and all your server plugins list please.

**Comment by jiangdashao** [comment]
how does it happen? when players switching world?
