### ISSUE TITLE
[ERROR] Unhandled exception occured in onPacketSending(PacketEvent) Unable to find getSound

### ISSUE THREAD

**Issue by SmallSansSerif** [jiangdashao/Matrix-Issues#2128]
## Troubleshooting Information

- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information

https://pastebin.com/hZw1wEU8

[11:02:14] [Server thread/ERROR]: [Matrix] Unhandled exception occured in onPacketSending(PacketEvent) for Matrix
java.lang.IllegalArgumentException: Unable to find getSound in org.bukkit.craftbukkit.v1_16_R3.CraftSound

Tuinity version git-Tuinity-"571b4b2" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Matrix version 5.4.0
ProtocolLib version 4.6.0-SNAPSHOT-b483

<img width="379" alt="Screen Shot 2020-11-26 at 11 13 48 AM" src="https://user-images.githubusercontent.com/4984139/100374363-25e3e380-2fda-11eb-91e2-191499d0212a.png">

**Comment by SlinkyAbyss4249** [comment]
I have exactly the same error

**Comment by Maximillus** [comment]
Why is matrix listening for sound?

**Comment by Kenaestic** [comment]
Yup. Started happening to me after [this](https://github.com/PaperMC/Paper/commit/43e2f13b21aa6f7890cfd14dfb7793538c8a925e) Paper (or rather Bukkit) update.

**Comment by Pemigrade** [comment]
Me too. Happened after updating from an older build of 1.16.4 to the latest build.

**Comment by NikV2** [comment]
This is a known error, it'll be fixed as soon as RE gets out of the hospital
