### ISSUE TITLE
[FP] timer

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2130]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
(Maximilus logs in at 16:24:33)
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:0 t:20.0 lp:43 vl:10 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:0 t:20.0 lp:43 vl:20 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+10) : ping:0 t:20.0 lp:43 vl:30 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 17.241, t:58, buffer:20, tag:timer) (+5) : ping:943 t:20.0 lp:48 vl:35 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+5) : ping:943 t:20.0 lp:48 vl:40 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+5) : ping:943 t:20.0 lp:48 vl:45 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+5) : ping:943 t:20.0 lp:48 vl:50 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 10.309, t:97, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:60 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:70 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:80 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:90 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:100 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:110 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:41 t:20.0 lp:49 vl:120 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 17.241, t:58, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:130 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:140 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:150 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:160 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:170 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 111.111, t:9, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:180 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:190 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:200 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:210 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 111.111, t:9, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:220 module: net.timer
(16:25:07) Maximilus flagged KillAura : (clickaimbot) click aim bot (d:0.0, 74.882) (+5) : ping:121 t:20.0 lp:49 vl:5 : ka.ckm
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 1000.0, t:1, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:230 module: net.timer
(16:25:07) Maximilus flagged BadPackets : (timer) moved too many times (timer: 9.223372036854776E15, t:0, buffer:20, tag:timer) (+10) : ping:121 t:20.0 lp:49 vl:240 module: net.timer
**How/when does this happen**: after player logs in and loading world with bad internet
**Video of false positive**: 
**Other information**: matrix exempt new logged in players from flag timer but the exempt should start when they send the first position packet. also  9.223372036854776E15 t:0 timer should give less vl because no hacks do this, it get caught by minecraft packet limiter if they spam packet

## Configuration Files
**Link to checks.yml file**: matrix default

**Comment by jiangdashao** [comment]
video,please
