### ISSUE TITLE
[BYPASS] loose detection for guyser players?

### ISSUE THREAD

**Issue by ghost** [jiangdashao/Matrix-Issues#2132]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:1.15.2 
**Hacked client**: bedrock minecraft has as many hacks as java
**Link to hacked client**: 
**Cheat that bypassed**: everything
**Video of bypass**: 
**Other information**: Instead of disable all checks for guyser players, move around/build with guyser player and see all the false positives it produce then fix the false positives, guyser players can speedhack and fly/ killaura 6 block because matrix ignores them. https://www.spigotmc.org/resources/spartan-advanced-anti-cheat-hack-blocker.25638/update?update=373421 spartan just added detection for guyser cheater. It ok if matrix loose with guyser but if they fly it should detect

## Configuration Files
**Link to checks.yml file**: matrix default
**Link to config.yml file**: matrix default

**Comment by prefislt** [comment]
**Yes!** Absence of this feature prevents me from using GeyserMC right now. Easiest implementation would be just create and load two different checks files - one for Java players and another for Bedrock players. Matrix would use one or another depending on platform.
_This idea with different checks on different groups can be used with permissions too. If for some reason server owner want to disable some checks or use different checks values for certain group of players and etc._

**Comment by NikV2** [comment]
Bedrock's protocol differ a lot more than you think than java's. Even if RE ends up making checks for bedrock players only, It will be very hard to maintain them afterwards. especially if bedrock's hacks get better over time.

Honestly, personal opinion. don't use Geyser. It's a heavy protocol hack and the security issues it can possibly create aren't worth the cost.

**Comment by prefislt** [comment]
> 
> 
> Bedrock's protocol differ a lot more than you think than java's. Even if RE ends up making checks for bedrock players only, It will be very hard to maintain them afterwards. especially if bedrock's hacks get better over time.
> 
> Honestly, personal opinion. don't use Geyser. It's a heavy protocol hack and the security issues it can possibly create aren't worth the cost.

We talking about "loose" detection so Bedrock players doesn't fly around and speed hack all over the place. I tested Spartan's implementation and it works fine. Just give us an option and community itself can maintain Bedrock checks. It's better than nothing.

**Comment by NikV2** [comment]
Fair enough.

**Comment by Maximillus** [comment]
surprisingly current geyser works near perfectly with matrix with the checks enabled, only problem is scaffolding forwards flag scaffold and clicking a player too fast can flag noswing

**Comment by OskarZyg** [comment]
> Bedrock's protocol differ a lot more than you think than java's. Even if RE ends up making checks for bedrock players only, It will be very hard to maintain them afterwards. especially if bedrock's hacks get better over time.
> 
> Honestly, personal opinion. don't use Geyser. It's a heavy protocol hack and the security issues it can possibly create aren't worth the cost.

Which security issues?
