### ISSUE TITLE
[FP] vehicle fly

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2134]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.448, entity:skeleton_horse, t:21, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:2 - veh.fly
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.354, entity:skeleton_horse, t:22, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:4 - veh.fly
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.263, entity:skeleton_horse, t:23, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:6 - veh.fly
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.176, entity:skeleton_horse, t:24, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:8 - veh.fly
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.092, entity:skeleton_horse, t:25, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:10 - veh.fly
(21:07:53) Maximilus: flagged vehicle: vehicle flight (mot: 0.011, entity:skeleton_horse, t:26, js:0.756) (+2) - ping:90 t:20.0 lp:4 vl:12 - veh.fly
**How/when does this happen**: jumping with a skeleton horse, maybe other types of horse
**Video of false positive**: 
**Other information**: if you jump normally with a skeleton horse it sometime flag veh.fly?

## Configuration Files
**Link to checks.yml file**: default matrix

**Comment by jiangdashao** [comment]
I said many times, it's likely a desync bug, I can't fix it
