### ISSUE TITLE
[FP] Void Teleport Fly

### ISSUE THREAD

**Issue by kacperleague9** [jiangdashao/Matrix-Issues#2136]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.12.2
**Verbose messages**: https://hastebin.com/ovoxoniruh.sql
**How/when does this happen**: Player jumps in void with void teleport plugin installed 
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: It's default one

**Comment by jiangdashao** [comment]
record a video

**Comment by kacperleague9** [comment]
https://gyazo.com/1fadb5d8302002ba14dce7dd001df1f4
and this shows up after 1 second more
![obraz](https://user-images.githubusercontent.com/34658474/102242843-cc951300-3efa-11eb-8bdc-52aade97ca82.png)

**Comment by kacperleague9** [comment]
Is this fixed?

**Comment by kacperleague9** [comment]
oh verbose, sure but will be hard for me

**Comment by kacperleague9** [comment]
https://hastebin.com/vinoroxove.sql

**Comment by jiangdashao** [comment]
> https://hastebin.com/vinoroxove.sql

it's empty

**Comment by kacperleague9** [comment]
weird, but

`(15:24:00) Execute command: matrix notify twin_dagger tried to fly (Fly) #1
(15:24:00) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.41 air_t:12 fall_t:10 g:-- tag:gn (+5) | vl:55 ping:57 tps:20.0 lp:4 component: fly.main
(15:24:01) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.503 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:60 ping:57 tps:20.0 lp:8 component: fly.main
(15:24:01) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.573 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:65 ping:57 tps:20.0 lp:11 component: fly.main
(15:24:02) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.636 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:70 ping:57 tps:20.0 lp:11 component: fly.main
(15:24:02) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.693 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:75 ping:57 tps:19.98 lp:14 component: fly.main
(15:24:03) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.731 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:80 ping:57 tps:19.98 lp:14 component: fly.main
(15:24:03) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.762 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:85 ping:57 tps:19.98 lp:15 component: fly.main
(15:24:04) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.791 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:90 ping:57 tps:19.98 lp:15 component: fly.main
(15:24:04) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.812 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:95 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:05) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.83 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:100 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:05) Execute command: matrix notify twin_dagger tried to fly (Fly) #2
(15:24:05) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.847 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:105 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:06) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.859 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:110 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:06) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.869 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:115 ping:57 tps:20.0 lp:18 component: fly.main
(15:24:07) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.878 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:120 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:07) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.885 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:125 ping:57 tps:20.0 lp:17 component: fly.main
(15:24:07) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.89 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:130 ping:60 tps:20.0 lp:18 component: fly.main
(15:24:08) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.896 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:135 ping:60 tps:19.98 lp:17 component: fly.main
(15:24:08) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.9 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:140 ping:60 tps:19.98 lp:17 component: fly.main
(15:24:09) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.904 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:145 ping:60 tps:19.98 lp:18 component: fly.main
(19:53:52) twin_dagger failed Fly check | suspicious movement: 0.0/0.127 vel: -0.078 tag:nc (+2) | vl:2 ping:0 tps:19.99 lp:1 component: fly.main
(19:53:52) twin_dagger failed Fly check | suspicious movement: 0.0/0.127 vel: -0.078 tag:nc (+2) | vl:4 ping:0 tps:20.0 lp:1 component: fly.main
(19:55:26) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.885 air_t:3 fall_t:3 g:-- tag:gn (+5) | vl:5 ping:52 tps:20.0 lp:2 component: fly.main
(19:55:26) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.887 air_t:4 fall_t:4 g:-- tag:gn (+5) | vl:10 ping:52 tps:20.0 lp:2 component: fly.main
(19:55:26) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.889 air_t:5 fall_t:5 g:-- tag:gn (+5) | vl:15 ping:52 tps:20.0 lp:2 component: fly.main
(19:55:27) twin_dagger failed Fly check | suspicious movement:0.0 predict:-0.155/-3.895 air_t:12 s:false tag:m1 (+15) | vl:30 ping:52 tps:20.0 lp:6 component: fly.main
(19:55:27) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.899 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:35 ping:52 tps:20.0 lp:6 component: fly.main
(19:55:27) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.9 air_t:12 fall_t:4 g:-- tag:gn (+5) | vl:40 ping:52 tps:20.0 lp:6 component: fly.main
(19:55:27) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.901 air_t:12 fall_t:5 g:-- tag:gn (+5) | vl:45 ping:52 tps:20.0 lp:6 component: fly.main
(19:55:28) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.902 air_t:12 fall_t:6 g:-- tag:gn (+5) | vl:50 ping:52 tps:20.0 lp:8 component: fly.main
(19:55:28) Execute command: matrix notify twin_dagger tried to fly (Fly) #1
(19:55:28) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.903 air_t:12 fall_t:7 g:-- tag:gn (+5) | vl:55 ping:52 tps:20.0 lp:8 component: fly.main
(19:55:28) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.906 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:60 ping:52 tps:20.0 lp:8 component: fly.main
(19:55:29) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.908 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:65 ping:52 tps:20.0 lp:11 component: fly.main
(19:55:29) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.91 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:70 ping:52 tps:20.0 lp:14 component: fly.main
(19:55:30) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.912 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:75 ping:52 tps:20.0 lp:15 component: fly.main
(19:55:30) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.913 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:80 ping:52 tps:19.99 lp:15 component: fly.main
(19:55:30) twin_dagger failed Fly check | suspicious movement:0.0 predict:-0.155/-3.914 air_t:12 s:false tag:m1 (+15) | vl:95 ping:52 tps:19.99 lp:16 component: fly.main
(19:55:30) twin_dagger failed Fly check | suspicious movement:0.0 predict:-0.078/-3.914 air_t:12 s:false tag:m1 (+15) | vl:110 ping:52 tps:19.99 lp:16 component: fly.main
(19:55:30) Execute command: matrix notify twin_dagger tried to fly (Fly) #2
(19:55:31) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.915 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:115 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:31) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.916 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:120 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:32) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.917 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:125 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:32) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.917 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:130 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:33) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.918 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:135 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:33) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.918 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:140 ping:52 tps:19.99 lp:18 component: fly.main
(19:55:34) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.918 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:145 ping:52 tps:19.99 lp:19 component: fly.main
(19:55:34) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:150 ping:52 tps:20.0 lp:18 component: fly.main
(19:55:35) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:155 ping:52 tps:20.0 lp:18 component: fly.main
(19:55:35) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:160 ping:52 tps:20.0 lp:17 component: fly.main
(19:55:35) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:165 ping:52 tps:20.0 lp:18 component: fly.main
(19:55:36) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:170 ping:52 tps:20.0 lp:18 component: fly.main
(19:55:36) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.919 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:175 ping:52 tps:20.0 lp:18 component: fly.main
(19:55:37) twin_dagger failed Fly check | suspicious movement:-0.078 predict:-0.155 lm:-0.078 hard_pred:-0.155 sev_pred:-3.92 air_t:12 fall_t:3 g:-- tag:gn (+5) | vl:180 ping:53 tps:20.0 lp:18 component: fly.main
(19:55:37) Execute command: matrix kick twin_dagger Fly Related Hacks`

**Comment by kacperleague9** [comment]
https://pastebin.com/Lu6ivvjk

**Comment by kacperleague9** [comment]
hey

**Comment by jiangdashao** [comment]
Try Matrix 6

**Comment by kacperleague9** [comment]
wdym? i see only matrix 5 on mcmarket

**Comment by jiangdashao** [comment]
soon, it's still in test
