### ISSUE TITLE
[FP] slime block jump

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2142]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
**How/when does this happen**: when jumping on slime block from high place
**Video of false positive**: https://streamable.com/qk1ezw and https://streamable.com/s4ywp0
**Other information**: matrix still struggle with slime block, this happen about 50% of time when jump slime

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
Unable to solve, I think this may need to rewrite the move check to solve
