### ISSUE TITLE
[REQUEST] Better anti spam

### ISSUE THREAD

**Issue by WaterTheMelon** [jiangdashao/Matrix-Issues#2143]
A chat check that checks if the a message sent by the player could be possible from the last movement or maybe even last message or first join. For example if a message is like 50 characters long and the player just joined a second ago that would be impossible for a player to do that regularly and would most likely be a bot spamming some junk into the chat thats just going to leave the next moment.
Could be nice for bots who are spamming copy and pasted messages in the chat rapidly a lot better with probably not that advanced code either.

**Comment by jiangdashao** [comment]
no
