### ISSUE TITLE
[REQUEST] disable matrix lagpoints on >1.9 version

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2145]
**What features/checks do you need?:**
Matrix lag point doesn't work on 1.9+ because flying packet send every 1 second when standing so it not consistant. Matrix think the player is lag when they not.

**Comment by Encode42** [comment]
Alternatively, the LP could be calculated differently to take the packet into account since LP is a better metric than ping in terms of security.

**Comment by jiangdashao** [comment]
I have considered the version 1.9+, please prove that it does not work properly
