### ISSUE TITLE
[REQUEST] Additions to MatrixAPI

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2147]
**What features/checks do you need?:**

I am requesting that the **tempBypass()** method prevent Matrix from running the checks altogether. For example, when a player has the MATRIX.BYPASS permission, the check methods are not run at all for that player (**saving server performance**). I want to be able to take advantage of **MatrixAPI#tempBypass()** to reduce the **impact speed/fly checks** have on my server (especially when 100+ players are on) by giving **tempBypass()** to players that are **unlikely** to use a blatant cheat **like flight** (but still continue to check them for less blatant cheats like kill aura). After all, at this time, movement checks like fly/speed are the most expensive.

**Comment by Maximillus** [comment]
yes, tempbypass should disable check altogether and so should disable it in config yml

**Comment by jiangdashao** [comment]
Checks are continuous, switching to check whether they are running may cause many problems
