### ISSUE TITLE
[BYPASS] Auto Armor

### ISSUE THREAD

**Issue by DebuffPvP** [jiangdashao/Matrix-Issues#2148]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.8.8
**Hacked client**: 
sigma but also works for wurst and others
**Link to hacked client**: 
**Cheat that bypassed**: 
- auto armor
- auto pot
- chest stealer
**Video of bypass**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
i use your guys's
**Link to config.yml file**:
i use your guys's

**Comment by jiangdashao** [comment]
1. There is no auto armor check, so it's not a "bypass"
2. Matrix only can detect "instant" auto potion, if it's not instant, then it's legit
3. For chest stealer, Matrix only detect when clicking multiple times in 100ms
