### ISSUE TITLE
[FP] Kill Aura - Aimbot

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#215]
## Basic Information
**Verbose message(s)**: https://i.imgur.com/8Pwp5LI.png
**How/when does this happen**: Watch the video. I'm not cheating.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxqhoMVltGgCt8zBA

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
The normal player won't combat like you

**Comment by jiangdashao** [comment]
AimBot(Math) check will be temporarily removed until I recode it
