### ISSUE TITLE
[REQUEST] Hex color support

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2151]
**What features/checks do you need?:**
The Adventure API provides features such as hex and markdown support, as well as a few other helpful features.
When players running an older version than 1.16, the formatting gets downgraded to support those versions.
There are other ways to achieve this feature, but experimenting with the Adventure API is the best way to go IMO.

**Comment by jiangdashao** [comment]
why an anticheat need hex color
