### ISSUE TITLE
[FP] speed.main

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2153]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
Maximilus flagged speed : suspicious movement (move: 0.479, vet: 0.563, tag: d) (+8) - p:103 t:20.0 lp:6 vl:32: module: speed.main
Maximilus flagged speed : suspicious movement (move: 0.468, vet: 0.563, tag: d) (+8) - p:100 t:20.0 lp:7 vl:40: module: speed.main
Maximilus flagged speed : suspicious movement (move: 0.465, vet: 0.563, tag: d) (+8) - p:103 t:19.98 lp:6 vl:8: module: speed.main
Maximilus flagged speed : suspicious movement (move: 0.48, vet: 0.563, tag: d) (+8) - p:96 t:20.0 lp:5 vl:16: module: speed.main
Maximilus flagged speed : suspicious movement (move: 0.476, vet: 0.563, tag: d) (+8) - p:92 t:20.0 lp:5 vl:24: module: speed.main
**How/when does this happen**: pressing the spacebar right before go over a lantern
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
video pls
