### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by Suqatri** [jiangdashao/Matrix-Issues#2154]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: video
**How/when does this happen**: video 
**Video of false positive**: https://youtu.be/JpqCXHGCe30
**Other information**: nothing

## Configuration Files
**Link to checks.yml file**:
https://hasteb.in/voyozaji.yaml

**Comment by jiangdashao** [comment]
There is currently no good solution, you can solve it by calling MatrixAPI#registerClientBlock
