### ISSUE TITLE
[FP] Kill Aura - Snap

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#216]
## Basic Information
**Verbose message(s)**: 
**How/when does this happen**: Watch the video. I'm not cheating.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxsoCduUzMiyFef5Q

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
The normal player won't combat like you
