### ISSUE TITLE
[REQUEST] Improve Matrix CPS

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2161]
**What features/checks do you need?:**
Due to limitations in Minecraft, it is not possible to accurately monitor a player's CPS when they are clicking air. I suggest that when running the /Matrix CPS command, Matrix should check if the player is clicking the air and if yes, spawn an invisible NPC in front of the player to more accurately monitor their CPS.

**Comment by jiangdashao** [comment]
no
