### ISSUE TITLE
[REQUEST] Matrix NPC API Additions

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2162]
**What features/checks do you need?:**

Hello, again Re. Could you please kindly add an API interface for the Matrix NPC? Some suggested methods are:
- MatrixAPI#spawnNPC(Location loc) [Returns instance of NPC]
- NPC#setInvisible(boolean b)
- NPC#teleport(Location loc)

I wanted to experiment with some custom NPC based kill aura checks. If I could utilize the MatrixAPI for that since Matrix already has an NPC that would be very helpful! Thanks!

**Comment by jiangdashao** [comment]
Unfortunately, I cannot provide APIs for other developers to operate NPCs. This will cause some security issues.
