### ISSUE TITLE
[ERROR] InvalidPluginException

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2164]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Error(s) found in console**: https://pastebin.com/GtvL9pvq
**How/when does this happen**: When I'm starting server

**Comment by jiangdashao** [comment]
did you installed ProtocolLib? did you try redownloading matrix?

**Comment by DrakMC** [comment]
I'm using latest version of ProtocolLib. I tried it also with Matrix version 5.6.1 and it doesn't work.

**Comment by jiangdashao** [comment]
can you send me your server log?

**Comment by DrakMC** [comment]
Log: https://pastebin.com/pBuedeAU

**Comment by jiangdashao** [comment]
can you try using 1.8 spigot?

**Comment by DrakMC** [comment]
Same on Spigot 1.8.8: https://pastebin.com/raw/2GGpVJBh

**Comment by jiangdashao** [comment]
I have no idea why it happens

**Comment by DrakMC** [comment]
I found that the last version that worked was 5.3.1_HOTFIX_2. Version 5.4.0 no longer worked.
