### ISSUE TITLE
[BYPASS] matrix 5.6.1 speed bypass

### ISSUE THREAD

**Issue by stovan12** [jiangdashao/Matrix-Issues#2166]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.4
**Hacked client**: Hydra 
**Link to hacked client**: https://hydra-utility-mod.yolasite.com 
**Cheat that bypassed**: speed
**Video of bypass**: https://streamable.com/c03jas
**Other information**: matrix flags the speed but only sometimes, is about 3x normal speed

## Configuration Files
**Link to checks.yml file**: no changes from default
**Link to config.yml file**: no changes from default

**Comment by jiangdashao** [comment]
https://streamable.com/176ibs
