### ISSUE TITLE
[REQUEST] default "setback_to_void" to "false" instead of "true" 

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#2168]
**What features/checks do you need?:**

setback_to_void "true" causes Matrix to murder players on legitimate Survival Servers. 

Please set this to "false" by default.

![image](https://user-images.githubusercontent.com/21042824/102733409-195d5d00-42f2-11eb-962e-a42c3a12ffef.png)

**Comment by jiangdashao** [comment]
It's important for Skywars/Bedwars server, if you set it to false, then they can use BugUp to avoid falling into void

**Comment by Kruize1** [comment]
Ya, but they can just enable it themselves. Is the majority of servers all bedwars servers?
