### ISSUE TITLE
[BYPASS] airjump

### ISSUE THREAD

**Issue by stovan12** [jiangdashao/Matrix-Issues#2169]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.4
**Hacked client**: hydra
**Link to hacked client**: https://hydra-utility-mod.yolasite.com/ 
**Cheat that bypassed**: fly (air jump)
**Video of bypass**: https://streamable.com/qdyhgb 0.1.3
**Other information**: matrix sometimes flags it as ground spoof, but even when it is flagged as that you can travel 100+ blocks before being kicked.

## Configuration Files
**Link to checks.yml file**: default with no-fall damage disabled (matrix was killing laggy players on my server)
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
it can't bypass in my testing

**Comment by stovan12** [comment]
@jiangdashao what did it do in your testing?

**Comment by jiangdashao** [comment]
enable AirJump and use it
