### ISSUE TITLE
[BYPASS] killaura

### ISSUE THREAD

**Issue by stovan12** [jiangdashao/Matrix-Issues#2170]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.4
**Hacked client**: hydra
**Cheat that bypassed**: killaura mode: bypassv2 
**Video of bypass**: https://streamable.com/uv7sdm
**Other information**: Bypasses matrix for mobs and players

## Configuration Files
**Link to checks.yml file**: the default matrix config
**Link to config.yml file**: the default matrix config

**Comment by jiangdashao** [comment]
can't bypass in my testing
