### ISSUE TITLE
[REQUEST] click to teleport for matrix notifications?

### ISSUE THREAD

**Issue by stovan12** [jiangdashao/Matrix-Issues#2171]
**What features/checks do you need?:**
the teleportation command could be specified in config. Moving from AAC to matrix and miss this feature

**Comment by jiangdashao** [comment]
1. Matrix is not AAC
2. The `/matrix notify <message>` command obviously does not contain any `player parameters`. You can put any message in it. How do I implement the click teleport function? 
3. "/matrix notify <message>" command support tellraw parameters. You can add "-h" parameters to add hover information, add "-c" parameters to add clickable action. For example: `/matrix notify I like eating -c say Food is great`, this command will display "I like eating" in the chat, and when you clicked it will execute the "say Food is great" command
