### ISSUE TITLE
[FP] Delay check Inventory FP ;-;

### ISSUE THREAD

**Issue by SadGhostYT** [jiangdashao/Matrix-Issues#2173]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity 1.16.1
**Verbose messages**: 
Taurus is verbosing SheDontWantMe failed Delay check | perform actions faster than expected // inventory (type D, d: 18) (VL +1) | vl: 55 ping: 9 tps: 20.0 lp: 6 component: delay.inv | ver: 1.16.x
Taurus is verbosing SheDontWantMe failed Delay check | perform actions faster than expected // inventory (type D, d: 6) (VL +1) | vl: 56 ping: 9 tps: 20.0 lp: 4 component: delay.inv | ver: 1.16.x
**How/when does this happen**: Spam Click open/close inventory and pick item on inventory/click on slots
**Video of false positive**: https://youtu.be/gba5otM4YI8
**Other information**: If this is clicking inventory while inventory is closed, then its due to the fact server receives the click inside the inventory before the inventory open. Also happens when spamming the number of slot with items other than clicking

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/WACDv6LV

**Comment by jiangdashao** [comment]
I will release a hotfix
