### ISSUE TITLE
[FP] Delay Check Inventory Again ;-;

### ISSUE THREAD

**Issue by SadGhostYT** [jiangdashao/Matrix-Issues#2174]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity 1.16.1
**Verbose messages**:
Taurus is verbosing SheDontWantMe failed Delay check | perform actions faster than expected // inventory (type E, d: 28) (VL +1) | vl: 159 ping: 12 tps: 20.0 lp: 2 component: delay.inv | ver: 1.16.x
Taurus is verbosing SheDontWantMe failed Delay check | perform actions faster than expected // inventory (type E, d: 23) (VL +1) | vl: 160 ping: 12 tps: 20.0 lp: 2 component: delay.inv | ver: 1.16.x
**How/when does this happen**: Opening a GUI through npc's and closing it too quick (any menu other than inventory
**Video of false positive**: https://youtu.be/xqyC04hBjYQ
**Other information**: Flags sometimes D when i open my own inventory while opening the other gui (not sure) and the E flags on all kind of inventory except the player's inventory (for example flags on chests & Crafting Tables) Also was with really low ping

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/WACDv6LV

**Comment by Tacosheel** [comment]
Is that a minehut server?

If so, it could be something to do with Skript's delay

**Comment by stovan12** [comment]
minehut doesn't allow jar files such as matrix so I doubt it

**Comment by SadGhostYT** [comment]
minehut contains Matrix but outdates most of the times, tho its not a minehut server

**Comment by jiangdashao** [comment]
I see it as a false positive that was triggered deliberately, and I am considering whether to remove this check

**Comment by Tacosheel** [comment]
> minehut doesn't allow jar files such as matrix so I doubt it

they have matrix though lol, and usually I get it updated
