### ISSUE TITLE
[FP] Very old fly FP

### ISSUE THREAD

**Issue by SadGhostYT** [jiangdashao/Matrix-Issues#2175]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity 1.16.1
**Verbose messages**: 
=-=-=-=-=-=-=-=-=
Fly Speed 10 Verbose:
=-=-=-=-=-=-=-=-=
Taurus is verbosing SheDontWantMe failed Fly check | creative fly (move: 10.936, exp: 10.92) (VL +10) | vl: 100 ping: 15 tps: 19.91 lp: 6 component: fly.cre | ver: 1.16.x
Taurus is verbosing SheDontWantMe failed Fly check | creative fly (move: 10.937, exp: 10.92) (VL +10) | vl: 40 ping: 10 tps: 20.0 lp: 6 component: fly.cre | ver: 1.16.x

=-=-=-=-=-=-=-=-=
Fly Speed 1 Verbose:
=-=-=-=-=-=-=-=-=
Taurus is verbosing SheDontWantMe failed Fly check | creative fly (move: 1.11, exp: 1.11) (VL +10) | vl: 40 ping: 10 tps: 20.0 lp: 2 component: fly.cre | ver: 1.16.x
Taurus is verbosing SheDontWantMe failed Fly check | creative fly (move: 1.11, exp: 1.11) (VL +10) | vl: 50 ping: 10 tps: 20.0 lp: 1 component: fly.cre | ver: 1.16.x
**How/when does this happen**: When Flying in creative while holding W+D or W+A, flying while holding it will flag every few seconds.
**Video of false positive**: https://youtu.be/kMRqxvAt0vk
**Other information**: This is a really old False Positive, Have forgotten about this false positive soo could not report it ;-;

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/WACDv6LV

**Comment by jiangdashao** [comment]
Seems to be a calculation accuracy problem

**Comment by SadGhostYT** [comment]
This check was never really useful, you should maybe make it disabled on default. and if any server owner wants to use it they will turn it on

**Comment by SadGhostYT** [comment]
Only use for this check is fly on Plots/Creative servers

**Comment by stovan12** [comment]
make it more leniant, it falses when i fly diagonal sometimes
