### ISSUE TITLE
[FP] Cinematic Camera/Zoom View Killaura False Positive

### ISSUE THREAD

**Issue by SadGhostYT** [jiangdashao/Matrix-Issues#2176]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Verbose messages**: 
Taurus is verbosing SheDontWantMe failed KillAura check | exhibiting an aiming pattern similar to aimbot // sensitivity (VL +0) | vl: 0 ping: 0 tps: 20.0 lp: 0 component: ka.abt.ses | ver: 1.8.x
Taurus is verbosing SheDontWantMe failed KillAura check | exhibiting an aiming pattern similar to aimbot // sensitivity (VL +0) | vl: 0 ping: 0 tps: 20.0 lp: 0 component: ka.abt.ses | ver: 1.8.x
**How/when does this happen**: When you attack enemies with cinematic/zoom aim you false flag sensitivity check :/
**Video of false positive**: https://youtu.be/s7WeApijsmE
**Other information**: Should make it detect cinematic aim usage.

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/WACDv6LV

**Comment by jiangdashao** [comment]
No one will use zoom in combat, unless you deliberately
