### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by 0xBit-MC** [jiangdashao/Matrix-Issues#2177]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, or 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.16.4 (git-Purpur-926, fork of paper)
**Error(s) found in console**: https://pastebin.com/upr6zDuK
**How/when does this happen**: Randomly on BlockPlaceEvent

**Comment by jiangdashao** [comment]
delete your outdated checks.yml
