### ISSUE TITLE
[FP] fly: tag:dmj

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2178]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
(23:16:48) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:76 t:20.0 lp:39 vl:12 module: fly.main
(23:16:49) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:63 t:19.99 lp:39 vl:24 module: fly.main
(23:16:51) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:69 t:20.0 lp:43 vl:36 module: fly.main
(23:16:52) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:81 t:20.0 lp:43 vl:48 module: fly.main
(23:16:55) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:68 t:20.0 lp:39 vl:60 module: fly.main
(23:16:58) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:78 t:20.0 lp:40 vl:72 module: fly.main
(23:16:59) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:60 t:20.0 lp:43 vl:84 module: fly.main
(23:17:00) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:76 t:20.0 lp:43 vl:96 module: fly.main
(23:17:01) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:67 t:19.99 lp:37 vl:108 module: fly.main
(23:17:05) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:77 t:20.0 lp:45 vl:80 module: fly.main
(23:17:07) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:58 t:20.0 lp:40 vl:92 module: fly.main
(23:17:08) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:68 t:20.0 lp:41 vl:104 module: fly.main
(23:17:09) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:86 t:20.0 lp:45 vl:116 module: fly.main
(23:17:10) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:61 t:20.0 lp:45 vl:128 module: fly.main
(23:17:15) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:70 t:20.0 lp:30 vl:140 module: fly.main
(23:17:16) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:72 t:20.0 lp:30 vl:152 module: fly.main
(23:17:18) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:64 t:20.0 lp:35 vl:164 module: fly.main
(23:17:21) Maximilus flagged Fly - suspicious movement:1.333 predict:1.69 air:1 tag:dmj (+12) - p:64 t:20.0 lp:37 vl:176 module: fly.main
**How/when does this happen**: when damaged and velocity apply
**Video of false positive**: 
**Other information**: reduce tag:dmj vl because it not stable

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
can you record a video? Every time you don’t record a video
