### ISSUE TITLE
[REQUEST] Optimizing matrix

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2180]
**What features/checks do you need?:**
Matrix grown to become very good anticheat but one problem persist for a while, the performance. Matrix performs not as well as other anticheats, it use 5% of tick when there are many player, not because it isn't async but because it needs to optimize more. for example reducing getType() and getNearbyEntity() call as much as possible, only call getType/getNearbyEntity once if needed and then use that data in other methods. Also return early as much as possible, i.e if check is disabled then dont do calculation first then return, check the easy booleans first. Cache everything. Also there is no point checking if player is on ice or near boat if they are moving slowly. try to leave expensive calls as late as possible, remove unnecessary try catch block and reduce call of System.currentTimeMillis() . I think optimize should be main focus of 5.7 update :) have nice day.

**Comment by jiangdashao** [comment]
I have tried the optimization you mentioned, but obviously, Java is not so fast

**Comment by Maximillus** [comment]
There is always something that can be improved :)

**Comment by Maximillus** [comment]
Another technique would be if you had a boolean whether to flag a player and it reaches true, other if statements that also flag it as true shouldn't be run. Basically use if else as much as possible instead of if if if. Also if you have a large if else branch turn it to a switch statement. Im sure there is probably lots of old code that needs optimized from early 2019 when you were not as good at java.

**Comment by Maximillus** [comment]
If after all optimization is complete, if matrix still underperforms I think you should move movement checks to netty threads

**Comment by Hyronymos1337** [comment]
@Maximillus you could try Matrix6 (avaible on discord)
