### ISSUE TITLE
[Bypass] Not rubber banding properly

### ISSUE THREAD

**Issue by WaterTheMelon** [jiangdashao/Matrix-Issues#2185]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 
**Hacked client**:  Impact
**Cheat that bypassed**: Fly & Anti Hunger
**Other information**:  If the player dies while fly or anti hunger is on the anti cheat pulls you to the ground rather than rubber banding when they respawn. ignoring fall damage and lets the player go faster than normal.

**Comment by jiangdashao** [comment]
Record a video, please
