### ISSUE TITLE
[FP] Kill Aura - Yaw Pattern

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#219]
## Basic Information
**Verbose message(s)**: https://i.imgur.com/CPflHSF.png
**How/when does this happen**: Watch the video. I'm not cheating. Basically, just look at a villager and move your mouse in weird ways while hitting him.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgoxwGt_wG5jCE6NZng

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
The normal player won't combat like you
