### ISSUE TITLE
[FP] Delay triggering when taking out items quickly from chest

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#2191]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://gist.github.com/Brottweiler/61f00398ccde160cb1773ea7339ce4fd
**How/when does this happen**: spam shift clicking items from a chest
**Video of false positive**: https://streamable.com/sx4reu
**Other information**: client version 1.16.4

## Configuration Files
**Link to checks.yml file**: **PREMIUM** config, but the video and verbose messages are on a local server which uses the _free_ version

**Comment by jiangdashao** [comment]
That's how it works, you can disable it if you want.
