### ISSUE TITLE
[FP] fastplace/fly triggers when spamming blocks fast under yourself

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#2192]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://gist.github.com/Brottweiler/b10051f4f18982bfdb432fbd2130f31f
**How/when does this happen**: spamming blocks fast under yourself while sprint jumping
**Video of false positive**: https://streamable.com/502wh9
**Other information**: 

## Configuration Files
**Link to checks.yml file**: **PREMIUM** config, but the video and verbose messages are on a local server which uses the _free_ version

**Comment by jiangdashao** [comment]
you can adjust the fastplace limit in checks.yml
