### ISSUE TITLE
[FP] Bridging without sneaking falsely triggers Scaffold

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#2194]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: 
```
(16:31:24) teagod failed Scaffold check | (delay) bridge too fast: 4,5 (+5) | vl:5 ping:108 tps:20.0 lp:1 component: sfd.dly ver: unknown
(16:31:24) teagod failed Scaffold check | (delay) bridge too fast: 5,5 (+5) | vl:10 ping:108 tps:20.0 lp:1 component: sfd.dly ver: unknown
(16:31:24) teagod failed Scaffold check | (delay) bridge too fast: 5,5 (+5) | vl:15 ping:108 tps:20.0 lp:4 component: sfd.dly ver: unknown
(16:31:24) Execute command: matrix notify &bteagod &7trigger &2Scaffold &7(sfd.dly&7) (&e15VL&7) (108ms)
(16:31:25) teagod failed Scaffold check | (delay) bridge too fast: 5,5 (+5) | vl:20 ping:108 tps:20.0 lp:4 component: sfd.dly ver: unknown
```
**How/when does this happen**: The player in question bridged while not crouching/sneaking. he was moving slightly diagonally and timing his clicks to place a block under himself to continue the bridge. Matrix false reports this as scaffold cheating.
**Video of false positive**: https://youtu.be/easMEAmkkqw
**Other information**: 

## Configuration Files
**Link to checks.yml file**: premium config

**Comment by jiangdashao** [comment]
You can custom the delay limit in checks.yml

**Comment by jiangdashao** [comment]
Plus: Before reporting a false positive, please publish the false positive on the discord server.
