### ISSUE TITLE
[FP] Honey blocks trigger illegal fly

### ISSUE THREAD

**Issue by Folas1337** [jiangdashao/Matrix-Issues#2195]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] Matrix is running on a 1.16.4 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:
git-Paper-351 (MC: 1.16.4)
**Verbose messages**:
Folas1337 failed Fly check | suspicious movement:-0.127 predict:-0.203 lm:-0.127 hard_pred:-0.203 sev_pred:-0.05 air_t:12 fall_t:45 g:-- tag:gn (+5) | vl:5 ping:2 tps:20.0 lp:4 component: fly.main ver: 1.16.x
**How/when does this happen**:
When hanging on to a honey block with no blocks beneath it. A contraption like this triggers it easily: https://imgur.com/a/QofJpR4 You'll be reset to where you jumped from just as you approach the bottom end of the pillar.
**Video of false positive**:
I don't happen to have one but I hope the image and my words are enough to explain it well. I can submit a video if necessary 😄 
**Other information**:
It's not happening when I'm crouching while jumping onto the side of the pillar.

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/Y9cTwfKv

**Comment by jiangdashao** [comment]
record a video?

**Comment by Folas1337** [comment]
https://youtu.be/zDPKpFUAo-U
Here you go, sorry for the annoying static noise in the background.

First attempt is while falling normally, second is me sneaking while falling.
