### ISSUE TITLE
[FP] jumping in sweet berry bush flags fly nc

### ISSUE THREAD

**Issue by stovan12** [jiangdashao/Matrix-Issues#2196]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: 
 suspicious movement: -0.118/0.041 vel: 0.0 tag:nc (+8) - p:273 t:20.0 lp:5 vl:24 module: fly.main
 suspicious movement: -0.118/0.041 vel: 0.0 tag:nc (+8) - ping:30 tps:20.0 lp:5 vl:32 module: fly.main
 suspicious movement: -0.118/0.031 vel: 0.0 tag:nc (+8) - ping:29 tps:20.0 lp:11 vl:8 module: fly.main
 suspicious movement: -0.118/0.031 vel: 0.0 tag:nc (+8) - ping:23 tps:20.0 lp:9 vl:16 module: fly.main
 suspicious movement: -0.118/0.031 vel: 0.0 tag:nc (+8) - ping:29 tps:20.0 lp:8 vl:24 module: fly.main
 suspicious movement: -0.118/0.032 vel: 0.0 tag:nc (+8) - ping:29 tps:20.0 lp:8 vl:32 module: fly.main
**How/when does this happen**: when jumping into a sweet berry bush
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default matrix config

**Comment by DontNeedAName** [comment]
Can confirm. You have to jump at the edge and then walk back.
