### ISSUE TITLE
[FP] Scaffold Check while non-shift bridging 

### ISSUE THREAD

**Issue by dkim19375** [jiangdashao/Matrix-Issues#2201]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.4
**Verbose messages**: https://paste.helpch.at/avoqifudat.sql
**How/when does this happen**: When breezily (less common), moonwalking (common), or godbridging (very common)
**Video of false positive**: https://streamable.com/r2ywzv
**Other information**: Client: Sigma 1.16.4

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
You can custom the min_delay in checks.yml

**Comment by dkim19375** [comment]
uhhh what do I set it to?
Also then change the default config also

**Comment by jiangdashao** [comment]
4

**Comment by jiangdashao** [comment]
default is strict

**Comment by dkim19375** [comment]
> default config is strict

the default config shouldn't have false positives though..

**Comment by jiangdashao** [comment]
However, most players don’t build bridges like this

**Comment by dkim19375** [comment]
> However, most players don’t build bridges like this

Aren't there more checks for scaffold? MCPlayHD has FastBridge and doesn't ban legit players godbridging, tellybridging, and other fast bridging types, yet they ban safewalkers and scaffolders.

**Comment by jiangdashao** [comment]
Yes, there are many other scaffold checks, but "delay" check prevent the player bridge too fast
