### ISSUE TITLE
[BYPASS] Velocity/AntiKnockback

### ISSUE THREAD

**Issue by dkim19375** [jiangdashao/Matrix-Issues#2202]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.4
**Hacked client**: Sigma 1.16.4 - AntiKnockback - All types
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: AntiKnockback
**Video of bypass**: https://streamable.com/8i8dmf
**Other information**: in the video, I took 0 knockback even with a punch 2 bow. I also proved at the end that verbose was on.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Tacosheel** [comment]
Are you using the latest version? Because that doesn't bypass for me.

**Comment by jiangdashao** [comment]
It can be detected
