### ISSUE TITLE
[REQUEST] OR [BYPASS] W-Tap

### ISSUE THREAD

**Issue by dkim19375** [jiangdashao/Matrix-Issues#2203]
Not exactly sure if this is part of Velocity or not, so I just filled both in

**What features/checks do you need?:** 
Ability to detect if the player is using a hack called W-tap.
This is because in pvp gamemodes, dealing more knockback and taking less knockback is important (one of the reasons why people click fast and strafe).

----

## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.4
**Hacked client**: Sigma 5.0
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: W-tap
**Video of bypass**: https://streamable.com/pyk0jj
**Other information**: Enabling W-tap allows me to deal more knockback to the other player, a big advantage in pvp, especially sumo

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I am curious if there are other anti-cheat detection w-tap, I guess it is undetectable

**Comment by DontNeedAName** [comment]
You could try to detect if the player is toggling sprint without moving, because that's only possible with WTab, but it might cause issues with lag.
