### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by radek203** [jiangdashao/Matrix-Issues#2204]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [PROBABLY] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: GuardSpigot 1.8.8
Error: https://drive.google.com/file/d/1KqWrUglk4Jt0-VKHQFAjge_RUEctwwBd/view?usp=sharing

## Configuration Files
**Link to checks.yml file**: https://drive.google.com/file/d/1KqWrUglk4Jt0-VKHQFAjge_RUEctwwBd/view?usp=sharing
**Link to config.yml file**: https://drive.google.com/file/d/1KqWrUglk4Jt0-VKHQFAjge_RUEctwwBd/view?usp=sharing

**Comment by jiangdashao** [comment]
not matrix error
