### ISSUE TITLE
[FP] Hitting players into cobwebs

### ISSUE THREAD

**Issue by RoccoDev** [jiangdashao/Matrix-Issues#2205]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date (5.6.3)
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: This server is running CraftBukkit version git-PaperSpigot-"1987fefb0" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT). The custom fork is ProjectKig/KigPaper.  
**Verbose messages**: 
```
[Matrix] Player failed Fly check | suspicious movement:0.016 predict:-0.092 air:9 tag:dmf (+10) | vl:10 ping:1 tps:19.99 lp:0 component: fly.main ver: 1.8.x
[Matrix] Player failed Fly check | suspicious movement:0.014 predict:-0.109 air:11 tag:dmf (+10) | vl:20 ping:1 tps:19.99 lp:0 component: fly.main ver: 1.8.x
[Matrix] Player failed Fly check | suspicious movement:0.014 predict:-0.109 air:12 tag:dmf (+10) | vl:30 ping:1 tps:19.99 lp:0 component: fly.main ver: 1.8.x
[Matrix] Player failed Velocity check | (vertical) reduce vertical velocity: 0.36075 (+1) | vl:1 ping:1 tps:20.0 lp:0 component: vel.vet ver: 1.8.x
```
Each ~3 fly flags you get a velocity flag.

**How/when does this happen**: When you make a 3x2 cobweb wall and knock someone into it, and optionally keep hitting them.  
**Video of false positive**: https://www.youtube.com/watch?v=TLgONCrB96k  
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: Matrix default, [uploaded anyway](https://gist.github.com/RoccoDev/2bd3a8824243435d211ef98ecb09629c).

**Comment by Tacosheel** [comment]
+1, I remember this during matrix 5.2.0

**Comment by jiangdashao** [comment]
not accept old matrix version bugs currently, please wait matrix 6
