### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2207]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Liquid Bounce
**Link to hacked client**: https://dl.ccbluex.net/download/N34KneSHmN
**Cheat that bypassed**: MoreCarry
**Video of bypass**: Not needed
**Other information**: The more carry hack that allows a player to carry items in their inventory crafting is completely bypassed

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
I won't add any inventory checks anymore, it's stupid
