### ISSUE TITLE
[FP] FastHeal

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2208]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12
**Verbose messages**: https://m.cft.li/p/le5.png / https://m.cft.li/p/go3.png
**How/when does this happen**: Unknown.
**Video of false positive**: x
**Other information**: It happens to most online players no matter their network latency. Many players connect with versions higher than 1.12, others stick with the native version. Players could be standing still and just healing or running, the falses still appear.

## Configuration Files
**Link to checks.yml file**: Happens on default and [MatrixChecks](https://github.com/Encode42/MatrixChecks)

**Comment by Maximillus** [comment]
@jiangdashao fastheal check in >1.9 is useless because fastheal doesn't work past 1.8

**Comment by DontNeedAName** [comment]
> 
> 
> @jiangdashao fastheal check in >1.9 is useless because fastheal doesn't work past 1.8

Yeah same goes for fasteat and fastbow. They should be disabled by default in 1.9+

**Comment by jiangdashao** [comment]
> @jiangdashao fastheal check in >1.9 is useless because fastheal doesn't work past 1.8

why? healing calculated on server-side?

**Comment by jiangdashao** [comment]
> > @jiangdashao fastheal check in >1.9 is useless because fastheal doesn't work past 1.8
> 
> Yeah same goes for fasteat and fastbow. They should be disabled by default in 1.9+

There is FastEat cheat on 1.9+

**Comment by DontNeedAName** [comment]
> 
> 
> > > @jiangdashao fastheal check in >1.9 is useless because fastheal doesn't work past 1.8
> > 
> > 
> > Yeah same goes for fasteat and fastbow. They should be disabled by default in 1.9+
> 
> There is FastEat cheat on 1.9+

No there isn't. The clients just interrupts the eating animation for a second, which causes the illusion of eating faster, but it actually isn't faster at all.
Try with sigma on a 1.8 and 1.16 server for a comparison.

**Comment by Maximillus** [comment]
in <1.9 eating/healing/bow ticks were based on how many flying packets client would send, so client could spam flying packets to tick it faster, in >1.9 the ticks are server-side, which means they cannot be spoofed by client

**Comment by jiangdashao** [comment]
> in <1.9 eating/healing/bow ticks were based on how many flying packets client would send, so client could spam flying packets to tick it faster, in >1.9 the ticks are server-side, which means they cannot be spoofed by client

cool, that's good
