### ISSUE TITLE
[FP] Falling onto Slime block

### ISSUE THREAD

**Issue by slvlr** [jiangdashao/Matrix-Issues#2210]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.4 build 386
**Verbose messages**:
![image](https://user-images.githubusercontent.com/8680731/103889821-f4812c00-50de-11eb-8d08-d5e35d64ec80.png)

**How/when does this happen**: When a use falls from a high block, with fly mode enabled (essentials fly) and lands on a slime block, it teleports the user back to the top. If the user does not have /fly enabled, it bounces as normal.
**Video of false positive**:  https://youtu.be/M8gnwtk8A0c
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/xDufpeK9

**Comment by jiangdashao** [comment]
not accept matrix 5 false positive report currently
