### ISSUE TITLE
[FP] 跳到粘液块上误报飞行

### ISSUE THREAD

**Issue by DreamVoid** [jiangdashao/Matrix-Issues#2212]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: https://lanzous.com/ivm43k5erqh
**How/when does this happen**: 玩家从很高的地方跳到粘液块上弹到空中就会报飞行
**Video of false positive**: https://lanzous.com/iMrjDk5erbc
**Other information**: 视频里我把自己的权限全部删掉了，只有一个verbose权限（因为没人帮我演示）

## Configuration Files
**Link to checks.yml file**: 默认（和刚装matrix没调配置一样）

**Comment by jiangdashao** [comment]
请等待matrix 6, 移动检测被重写了
