### ISSUE TITLE
[BYPASS] NoFall/Fly

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2217]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094
**Hacked client**: meteor
**Link to hacked client**: meteorclient.com
**Cheat that bypassed**: NoFall
**Video of bypass**: https://youtu.be/qyU8iL2fhuc https://youtu.be/oRbLidPKEnQ https://youtu.be/Sju7RPn8kL8
**Other information**: Use Settings Airplace and BeforeDamage as shown in the last video. You have to look down and manually swing your hand to make it work. Yes it sometimes flags for scaffold if used really blatantly, but placing blocks in mid air shouldn't be possible.

**Comment by jiangdashao** [comment]
stupid Minecraft, you even can place a block in the air

**Comment by supakeks** [comment]
Meteor strong

**Comment by seasnail8169** [comment]
Meteor strong

**Comment by seasnail8169** [comment]
@DontNeedAName meteor client is not a hacked client, it's a utility mod. Nothing meteor does is related to "hacking", please don't misuse the term.

**Comment by asdffdsdaf** [comment]
popbob sex dupe moment

**Comment by Wide-Cat** [comment]
Meteor on crack!

**Comment by DontNeedAName** [comment]
> 
> 
> @DontNeedAName meteor client is not a hacked client, it's a utility mod. Nothing meteor does is related to "hacking", please don't misuse the term.

The issue template isn't written by me.
