### ISSUE TITLE
[BYPASS] EntityControl

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2218]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094
**Hacked client**: meteor
**Link to hacked client**: meteorclient.com
**Cheat that bypassed**: EntityControl
**Video of bypass**: https://youtu.be/qWkJJJlscrw
**Other information**: For some reason turning on entity speed bypasses entity control at speed 6.

**Comment by jiangdashao** [comment]
useless

**Comment by asdffdsdaf** [comment]
bro stop its not a hacked client

**Comment by seasnail8169** [comment]
Meteor Strong

**Comment by asdffdsdaf** [comment]
> 
> 
> Meteor Strong

meteor strong

**Comment by DontNeedAName** [comment]
> 
> 
> > Meteor Strong
> 
> meteor strong

No it's not it literally messes up the players velocity even if it's disabled, causing instant kicks when you get hit.

**Comment by seasnail8169** [comment]
> > > Meteor Strong
> > 
> > 
> > meteor strong
> 
> No it's not it literally messes up the players velocity even if it's disabled, causing instant kicks when you get hit.

that was fixed lmao
