### ISSUE TITLE
[FP] Holding Space up 2 stairs

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#222]
## Basic Information
**Verbose message(s)**: https://i.imgur.com/s0yFFtD.png
**How/when does this happen**: When you hold space when running up 2 stairs. Watch the video.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgox-J0oh1V0skvkLCQ

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by Kyrobi** [comment]
Ah yes! Finally, this issue with https://github.com/jiangdashao/Matrix-Issues/issues/60 can also be fixed.

**Comment by ignPerformance** [comment]
Still not fully fixed.

**Comment by jiangdashao** [comment]
Reduced false flags
