### ISSUE TITLE
[ERROR] [Matrix 5.6.3] [Viaversion] Incorrect Version Detection

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2220]
My setup:
- Using Matrix 5.6.3
- Paper 1.12.2
- Over BungeeCord

It appeals that a player's version is not always detected properly? I think this might actually be an issue with Viaversion maybe? But after checking my server logs (because my custom plugin prints user login version to console as well) and I am noticing something very wierd:

`[10:52:11] [Server thread/INFO]: [Core-Join-DEBUG] Handling player join event for MuzoTAT
[10:52:11] [Server thread/INFO]: [Core] [NMSVersion][Resolve] Player MuzoTAT has version id=340
[10:52:11] [Server thread/INFO]: [Matrix] (Via) Player MuzoTAT joined with (1.12.x) client
[10:52:12] [Server thread/INFO]: [Core] [NMSVersion][Resolve] Player MuzoTAT has version id=754
[10:52:12] [Server thread/INFO]: [Core] [Join] Texture pack code #4 (1.13.x AND ABOVE) due to NMS protocol version=MC_1_16_4
[10:52:12] [Server thread/INFO]: [Core] [NMSVersion][Resolve] Player MuzoTAT has version id=754
[10:52:12] [Server thread/INFO]: MuzoTAT Logged in. (Version: MC_1_16_4) [607ms]`

I've looked at the code for my plugin and it looks like when the server got the player's version using Viaversion API initially, the player's protocol version was 1.12.2 (340). Matrix also captured this version ID. However, a second later, when the get version methods were called in my plugin after our server loaded their User data, via version was now returning a protocol version of 754 (1.16.4/5). I found this after that player was swimming and triggering Jesus (because 1.16 swim mechanics are different). Not sure why this is happening but maybe Matrix get try to get the player's login version a little bit later?

**Comment by SkyLicks** [comment]
To clarify this issue does on occasion cause false positives ^.

**Comment by jiangdashao** [comment]
that's weird

**Comment by jiangdashao** [comment]
can you try the latest version of the beta build?

**Comment by SkyLicks** [comment]
Sorry just seeing this. I was very busy the past few days. I will test this ASAP.

**Comment by Aseeef** [comment]
Sorry but will not be able to test until Saturday (because I also need to update my Matrix integrations plugin which I use to make matrix compatible with some custom plugins and server specific issues).

**Comment by SkyLicks** [comment]
This is a rare issue so I can't replicate it outside the production server. I can confirm if it is really fixed once the update is on my production server but before that I've reported a few falses which I am hoping you could fix first.
