### ISSUE TITLE
[BYPASS] Movements Checks Super Slow / Broken??

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2226]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: Wurst
**Link to hacked client**: 
**Cheat that bypassed**: Fly and Speed Hack
**Video of bypass**: https://youtu.be/6-ZtMLJrnJc & https://youtu.be/NqfcAE3keOU
**Other information**: P.S. **I noticed that even with "ghost mode" set to true in the config, it was still warping me back**. I think the new move check broke ghost mode.

## Configuration Files
**Link to checks.yml file**:  Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
ghost mode has been removed

**Comment by jiangdashao** [comment]
can't reproduce
