### ISSUE TITLE
[FP] Ladder false positive

### ISSUE THREAD

**Issue by WcaleNieWolny** [jiangdashao/Matrix-Issues#2227]
## Troubleshooting Information
I chcecked on test.matrix.rip
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
i don't know i was on 1.16
**Verbose messages**: 
**How/when does this happen**:
always 
**Video of false positive**:
https://www.youtube.com/watch?v=v9ecVFzuXmg&feature=youtu.be 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
don't report beta version bug on github

**Comment by WcaleNieWolny** [comment]
> don't report beta version bug on github

Sorry i didn't know that on test.matrix.rip is on beta
