### ISSUE TITLE
[FP] Levitation False

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2229]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In video
**How/when does this happen**: When ever a player gets a high amount of levitation, it can false move
**Video of false positive**: https://youtu.be/NxwjmK1pPxo
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.pl/view/0b2a8531

**Comment by jiangdashao** [comment]
can't fix
