### ISSUE TITLE
[FP] Hitting inside of a player

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2232]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In video
**How/when does this happen**: Seems to happen when you are hitting from very close or from inside another player while moving your head. Very annoying false positive in server spawns where often a lot of players are close together.
**Video of false positive**: https://youtu.be/tFGAJGdIzyE
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
not important

**Comment by DontNeedAName** [comment]
The Killaura checks should only work if the player is at least one block away from the other player.
