### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by EvanBurnett** [jiangdashao/Matrix-Issues#2236]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [Yes ] Matrix and ProtocolLib are up-to-date
- [ 1.8] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ Bypass] The issue happens on default config.yml and checks.yml
- [YEs on defualt config ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.8.9
**Hacked client**:  Liquid Bounce
**Link to hacked client**:  https://liquidbounce.net/
**Cheat that bypassed**: I only tested fly
**Video of bypass**: https://youtu.be/WzFh2_C7CBI

**Other information**: 

## Configuration Files
**Link to checks.yml file**: Literally fresh installation
**Link to config.yml file**: Literally fresh installation

**Comment by DontNeedAName** [comment]
Are you sure you didn't have bypass permission?

**Comment by EvanBurnett** [comment]
In the beginning of the clip you can see that I flagged it!

> Are you sure you didn't have bypass permission?

**Comment by jiangdashao** [comment]
Enable `/matrix verbose` when testing, and set disable_bypass_permission to true in config.yml
