### ISSUE TITLE
[FP] Liquid Interact - Fences (Possibly Other Blocks)

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#224]
## Basic Information
**Verbose message(s)**: https://i.imgur.com/vzvWHSF.png
**How/when does this happen**: Watch the video.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgo0Jv63SQ7KsklUTZA

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
It's compatibility bug to some protection plugins
not important
