### ISSUE TITLE
[BYPASS] ChestStealer

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2240]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: ChestStealer
**Video of bypass**: https://youtu.be/Zzjn0bk3ar8
**Other information**: Inventory checks became kinda useless in the last update.

**Comment by jiangdashao** [comment]
I will not add this check temporarily
