### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2241]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: Fly
**Video of bypass**: https://youtu.be/Sq52oZrULc8
**Other information**: Make sure you don't have blocks in your inventory. If you get flagged for no swing you have to manually swing your arm by punching in the air.

**Comment by jiangdashao** [comment]
it can setback in my testing

**Comment by DontNeedAName** [comment]
Yes it can, but the setback comes way to late. You can fly around 30 blocks without setback.

**Comment by contionability** [comment]
复活了（With ViaVersion1.17 on 1.8.X
