### ISSUE TITLE
[BYPASS] Anti Knockback

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2242]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: Anti Knockback
**Video of bypass**: https://youtu.be/3TMsUTjHmNk
**Other information**: I'm not sure if this can be detected, but this is especially noticeable during combos when the player is in the air.

**Comment by jiangdashao** [comment]
Are you reporting a flight or antiknockback

**Comment by DontNeedAName** [comment]
I accidentally used the wrong link... Now I fixed it.
