### ISSUE TITLE
[REQUEST] Seperate Inventory Check

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2244]
**What features/checks do you need?:**
I don't think that it makes much sense to have a delay check for both timer cheats like fastheal, fasteat and fastbow and inventory cheats like cheststealer and autototem. They are fundamentally different and should be split into their own checks, allowing for more customizability. The Inventory check should be seperate from the delay check.

**Comment by jiangdashao** [comment]
nope
