### ISSUE TITLE
[INCOMPATIBILITY] GPFlags

### ISSUE THREAD

**Issue by DrBot7** [jiangdashao/Matrix-Issues#2247]
## Troubleshooting Information
- [x] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Purpur 966 (1.16.5)
**Incompatible plugin**: [GriefPreventionFlags](https://github.com/ShaneBeee/GriefPreventionFlags)
**Verbose messages (or) console errors**: none
**How/when does this happen**: Someone flies or falls in a claim with ownerfly/ownermemberfly or nofall flags.
**Video of incompatibility**:
**Other information**:

**Comment by jiangdashao** [comment]
Record a video with the verbose message on

**Comment by jiangdashao** [comment]
still no video
