### ISSUE TITLE
[FP] move.ver

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2253]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: See video
**How/when does this happen**: When you break the block you stand on and the block breaking gets cancelled by a plugin.
**Video of false positive**: https://youtu.be/JKpGsWAwfC0
**Other information**:

**Comment by jiangdashao** [comment]
can't fix

**Comment by DontNeedAName** [comment]
But this didn't happen before...

**Comment by Maximillus** [comment]
you can easily detect cancelled block break event and account for it. Why does move check even flag here? what hack moves you down into a block?

**Comment by NikV2** [comment]
YPort e.t.c.

Most anticheats have the same issue w ghost blocks.

**Comment by Maximillus** [comment]
> YPort e.t.c.
> 
> Most anticheats have the same issue w ghost blocks.

y port doesn't move you into blocks it moves up and down above blocks, no hack except phase would be moving down into a solid block, its useless, only flag is a false flag from chunks not being sent to player
