### ISSUE TITLE
[FP] Bukkit Survival Fly Compatibility Issues

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#2257]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In video
**How/when does this happen**: When initiating flight in survival whenever bukkit's flight is enabled.
**Video of false positive**: https://youtu.be/D3gE6aWpxyE
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default with setback vl set to -1

**Comment by jiangdashao** [comment]
Please use vanilla client

**Comment by SkyLicks** [comment]
> Please use vanilla client

Im just using 5 zig. Also happens on vanilla client.
