### ISSUE TITLE
[FP] ka.clk.swg - Clicking at entity 10+ cps

### ISSUE THREAD

**Issue by dkim19375** [jiangdashao/Matrix-Issues#2259]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.4
**Verbose messages**: https://streamable.com/2xhq3z
**How/when does this happen**: Clicking at an entity (only tested with a villager though) with about 12+ cps
**Video of false positive**: https://streamable.com/2xhq3z
**Other information**: Client: 1.8.9, Feel free to close this issue if you cannot reproduce using a 1.16.4 client. (Make sure you have at least 12 cps though)

## Configuration Files
**Link to checks.yml file**:

**Comment by DontNeedAName** [comment]
Can confirm this.

**Comment by jiangdashao** [comment]
This check is mainly used to check whether the player’s click interval is constant.
