### ISSUE TITLE
[FP] Moving while having Charged bow on hands

### ISSUE THREAD

**Issue by emanondev** [jiangdashao/Matrix-Issues#2260]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Verbose messages**: (just look for Salvo2112 reports)
https://pastebin.com/8D9Bpet7
**How/when does this happen**: Move with charged bow
**Video of false positive**: 
https://i.imgur.com/YoaqhAe.mp4
**Other information**: 
On the last 15 seconds of the video 0:35+ the player seems like not moving but it is actually teleported back when trying to move

## Configuration Files
**Link to checks.yml file**: Default, just notify message/kick has been changed but it's on same violation level as default

**Comment by jiangdashao** [comment]
can't reproduce

**Comment by jiangdashao** [comment]
can't reproduce

**Comment by emanondev** [comment]
You need to move while shooting and also you need to move on diagonals like pressing both W and A or W and D

moving on just a single direction get no reports

https://i.imgur.com/2zbd4dy.mp4

**Comment by jiangdashao** [comment]
try it on 6.0.3
