### ISSUE TITLE
[REQUEST] Detailed CPS info

### ISSUE THREAD

**Issue by emanondev** [jiangdashao/Matrix-Issues#2262]
**What features/checks do you need?:**
Matrix status offers the averange cps of a Player and the current cps, those values alone are not very useless

A player may do 2, 2, 2, 18, 18, 18, 10 and it would give 10 as AVG and 10 as Current cps which is not much informative

i suggest to add a command which should print the cps value of each of the last 10 seconds (print may be delayed by 10 seconds to collect data) of a choosen player and optionaly AVG value as well

the command should be something like
/matrix cps <player> [monitor duration]
where [monitor duration] is how many seconds the player should be monitored, if omitted takes by default a fixed value like 10

else
/matrix cps <player>
should be enough

**Comment by jiangdashao** [comment]
No, Matrix only counts APS, not CPS

**Comment by emanondev** [comment]
How abouth /matrix aps ?
