### ISSUE TITLE
[FP] Phase walking on floor of mixed full blocks and chests (phase.main)

### ISSUE THREAD

**Issue by emanondev** [jiangdashao/Matrix-Issues#2263]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Verbose messages**: 
(22:23:19) Sheld0nC00per failed Phase check | moved into block (block: spruce_planks, move: -0.013,0.078,-0.041, at: -2825.713,4.0,728.301, dist: 0.044, loop: false) (+2) | vl:131 ping:46 tps:20.0 lp:24 component: phase.main ver: 1.16.x
https://pastebin.com/2fvmwVS7
**How/when does this happen**: 
walk over a floor of mixed chest and full blocks, do not jump do not sneak, works with sprint and speed too
**Video of false positive**: 
https://i.imgur.com/BQO0uUO.mp4
https://i.imgur.com/dei7iQ5.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default, just commands has been changed to chat notify commands

**Comment by jiangdashao** [comment]
can't reproduce, make sure he is using vanilla client

**Comment by emanondev** [comment]
Tested with both Vanilla Client and Lunar Client

**Comment by jiangdashao** [comment]
But I can't reproduce it

**Comment by emanondev** [comment]
do you have a public test server?

**Comment by jiangdashao** [comment]
test.matrix.rip

**Comment by emanondev** [comment]
i didn't found a path of mixed chests and full blocks but i found this:

https://i.imgur.com/ZKVgaMs.mp4
