### ISSUE TITLE
[FP] Move false while sprinting with key assignment

### ISSUE THREAD

**Issue by SmallSansSerif** [jiangdashao/Matrix-Issues#2264]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
Tuinity version git-Tuinity-"4d52574" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Verbose messages**: 
Unable to get verbose as it was after reviewing logs but see multiple users getting move:

tried to move abnormally (Move) #1
tried to move abnormally (Move) #2

**How/when does this happen**: 
The user that reported it was getting stuck when trying to use a key assignment for sprint. So moving while sprinting. Not the best test because I don't know all the specifics of their setup.

**Comment by SmallSansSerif** [comment]
Was able to capture video of this finally: https://streamable.com/teg4vk

**Comment by batuhan121** [comment]
I have this problem, please solve it
