### ISSUE TITLE
High CPU use as of Version 6 for "PacketPlayInFlying$PacketPlayInPositionLook.a()"

### ISSUE THREAD

**Issue by TomLewis** [jiangdashao/Matrix-Issues#2267]
I've been having many performance issues with high playercounts and Matrix 6.0.3 installed on Paper 1.12.2. 
I got a Spark report during one of the laggiest times of the day, hopefully it can help.
https://spark.lucko.me/#6K5wnQUvJe

Its under `SystemUtils.a()` using 21.87%.

![Screenshot 2021-02-09 13 39 37](https://user-images.githubusercontent.com/144046/107371609-5d900100-6adc-11eb-9f3d-eb95bbc2cbbb.png)

**Comment by jiangdashao** [comment]
It seems that Matrix only consumes 8% of the tick
