### ISSUE TITLE
[BYPASS] Velocity

### ISSUE THREAD

**Issue by K-o-d-y** [jiangdashao/Matrix-Issues#2268]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: My Client
**Link to hacked client**: no link
**Cheat that bypassed**: Velocity
**Video of bypass**:  https://youtu.be/TwglL0MN-Jk
**Other information**: reverse velocity x z

## Configuration Files
**Link to checks.yml file**: default 
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
暂时没必要修
