### ISSUE TITLE
[BYPASS] Speed while flying

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2269]
(Relayed from Shozem)

## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Any
**Hacked client**: Pretty much any
**Link to hacked client**: 
**Cheat that bypassed**: Move
**Video of bypass**: 
**Other information**: When players have the ability to fly, they can fly at any speed without detections. I would assume Matrix checks if a player can fly then exempts them from the check, but this allows for players with the ability to fly at insane speeds.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by AMDBartek** [comment]
I agree with this, it should be the server owners choice whether or not a player can use things like "fly boosts".

**Comment by DontNeedAName** [comment]
Yeah there should just be an option to disable this check if you want "PvP" clients to use their creative fly.
