### ISSUE TITLE
Cobblestone generator[FP] 

### ISSUE THREAD

**Issue by MarcusVosper** [jiangdashao/Matrix-Issues#2270]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 
**Verbose messages**: MaxxLite failed Block check | break block without delay (+4) | vl:4 ping 86 tps: 20.0 lp:4 component blk.fb.dly ver:1.16.x 
**How/when does this happen**: Everytime
**Video of false positive**: https://www.youtube.com/watch?v=Gp9M4bEsXfk&feature=youtu.be
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
https://pastebin.pl/view/e890879c

**Comment by jiangdashao** [comment]
outdated
