### ISSUE TITLE
[FP] Piston push me up

### ISSUE THREAD

**Issue by K-o-d-y** [jiangdashao/Matrix-Issues#2272]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: unexpected vertical movement
**How/when does this happen**: Piston push me up
**Video of false positive**: https://www.youtube.com/watch?v=pYYOXZK-8pc
**Other information**: None

## Configuration Files
**Link to checks.yml file**: default

**Comment by K-o-d-y** [comment]
and https://youtu.be/FxLPA-Q6zgg unexpected horizontal movement

**Comment by DontNeedAName** [comment]
Can confirm this. Same goes for vertical piston pushing. Basically any type of piston pushing will cause this.

**Comment by jiangdashao** [comment]
单活塞方块没有被正确注册
