### ISSUE TITLE
[FP] Jumping with Elytra

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2275]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Yatopia 1.16.5
**Verbose messages**: https://pastebin.com/raw/AmeidReu
**How/when does this happen**: Often when running and jumping with Elytra

**Comment by jiangdashao** [comment]
video？

**Comment by DrakMC** [comment]
Video: https://youtu.be/TljNjP7bIx0

**Comment by jiangdashao** [comment]
elytra status desync, hard to fix
