### ISSUE TITLE
[FP] Move abnormally

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2276]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Verbose messages**: https://pastebin.com/raw/1PpiuVDm
**How/when does this happen**: When jumping and crouching under the block.
**Video of false positive**: https://youtu.be/wHyIWgCFfCU

**Comment by jiangdashao** [comment]
client version?

**Comment by DrakMC** [comment]
1.16.5

**Comment by jiangdashao** [comment]
I guess it was canceled by the server
