### ISSUE TITLE
[FP] Jumping on Lily Pad

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2277]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Verbose messages**: https://pastebin.com/raw/796UFXm0
**How/when does this happen**: When jumping on Lily Pad.
**Video of false positive**: https://youtu.be/sMZllXJt9Fo

**Comment by jiangdashao** [comment]
are u using the latest hotfix version?

**Comment by DrakMC** [comment]
Yes, I'm using it.

**Comment by jiangdashao** [comment]
hotfix 13?

**Comment by DrakMC** [comment]
I'm using: Matrix_6.0.3_hotfix9_release

**Comment by jiangdashao** [comment]
try the latest version

**Comment by DrakMC** [comment]
Where can I download it? There is only hotfix9 on your Discord server.

**Comment by jiangdashao** [comment]
there is now

**Comment by DrakMC** [comment]
The problem still persists.

**Comment by jiangdashao** [comment]
I guess you are using the 1.16 client, right?

**Comment by jiangdashao** [comment]
the collision box height of the lily pad was changed
