### ISSUE TITLE
[FP] Move with Plugin teleports

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2279]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: video
**How/when does this happen**: If the player gets teleported by a plugin while moving.
**Video of false positive**: https://youtu.be/ju6BrwKs-XI
**Other information**: This can also happen if the player was teleported by matrix, which can cause vl buildup: https://youtu.be/mtlRkDNZXho (I'm trying to demonstrate that if the player gets flagged and keeps doing the same thing, he will continue to get flagged forever.)

**Comment by jiangdashao** [comment]
can't reproduce

**Comment by DontNeedAName** [comment]
> 
> 
> can't reproduce

I think the biggest problem is in the second video.

**Comment by jiangdashao** [comment]
Nope, anticheat **should** flag player when they build up like this

**Comment by DontNeedAName** [comment]
> 
> 
> Nope, anticheat **should** flag player when they build up like this

I mean flags in general. Let's say that this was a false flag, the player continues to get lagged back for no reason.
