### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2283]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: Speed
**Video of bypass**: https://youtu.be/GtU06HccXLY
**Other information**: You have to be at 0 vl for this to work.

**Comment by jiangdashao** [comment]
I don’t know the meaning of speeding up on the honey block

**Comment by DontNeedAName** [comment]
> 
> 
> I don’t know the meaning of speeding up on the honey block

You mean it's useless? Yes it is, but it's still a bypass, like noslowdown...

**Comment by DontNeedAName** [comment]
I think there's a problem with the noslow check, especially on 1.8. I can run around while sneaking and on soul sand. Also I get flagged when eating while walking normally.
