### ISSUE TITLE
[BYPASS] Criticals

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2284]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5)
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: Criticals
**Video of bypass**: https://youtu.be/EQdh7Qhyvtg
**Other information**: You will get random movement flags while having this enabled, however the criticals themselves don't get detected.

**Comment by jiangdashao** [comment]
useless, you even can't move when using this cheat

**Comment by LaserSlimeHD** [comment]
> 
> 
> useless, you even can't move when using this cheat

But if you don't sprint or jump you can still move.
