### ISSUE TITLE
[ERROR] An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2286]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Yatopia 1.16.5
**Error(s) found in console**: https://pastebin.com/raw/HxyfBdhK
**How/when does this happen**: When enabling the plugin

**Comment by jiangdashao** [comment]
ignore it
