### ISSUE TITLE
[ERROR] Invincible players from ALL damage types.

### ISSUE THREAD

**Issue by slvlr** [jiangdashao/Matrix-Issues#2288]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.5
**Error(s) found in console**: 
>.... [13:09:45 INFO]: + [Duke] AsimoNewbie
>.... [13:09:52 INFO]: [Matrix] AsimoNewbie tried to reach entity outside max reach distance (HitBox)
>.... [13:09:52 INFO]: Spawned KillAura Npc for AsimoNewbie (120 ticks)
>.... [13:09:52 INFO]: [Matrix] AsimoNewbie tried to reach entity outside max reach distance (HitBox) #2
>.... [13:10:00 INFO]: ItzZen issued server command: /r done already

AsimoNewbie was spam hitting ItzZen, and within 15 seconds it flagged him for max reach, and then made ItzZen invincible.

**How/when does this happen**: 
When you are on a wilderness (pvp) area, and a non-pvp border (tested with both Towny and Worldguard regions), and quickly walking in and out of the safe-zone. You have someone standing in the wilderness chunk spam hitting you with their fists, and then you will suddenly stop taking all damage until you reconnect to the server. It seems to be easier to reproduce when the person that is doing the hitting is lagging, in the video that I will send, he has high ping.

**Other information**: 
https://youtu.be/HbuepKqCVG4
When matrix is not loaded on the server players cannot reproduce this bug, thus I believe Matrix is the cause of this.

## Configuration Files
**Link to checks.yml file**:  https://pastebin.com/KqLbPg2X
**Link to config.yml file**: https://pastebin.com/bZK4LArX

**Comment by slvlr** [comment]
![image](https://user-images.githubusercontent.com/8680731/107896232-99d4be80-6f2d-11eb-9ced-e4463b548f5a.png)

**Comment by jiangdashao** [comment]
Does he is creative mode?

**Comment by slvlr** [comment]
No, neither users have access to creative mode, or god mode.
They are both in normal survival mode, and do nothing except punch the target, and the target walking in and out of a protected zone, (Towny or worldguard).

**Comment by jiangdashao** [comment]
then they are cheating

**Comment by slvlr** [comment]
They are lagging at high ping, but even if the person doing the hitting is cheating, it shouldn't make everyone else invincible?! 
Even if they do it to me, it makes me invisible. It is an error in your plugin, please fix it.

**Comment by slvlr** [comment]
https://youtu.be/pJQJZM5Lnlg

**Comment by slvlr** [comment]
This should help, shows the bug as well as verbose: 
https://youtu.be/STvjXOeQ42k
