### ISSUE TITLE
[FP] Scaffolding Bug

### ISSUE THREAD

**Issue by crafter23456** [jiangdashao/Matrix-Issues#2294]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 Paper
**Verbose messages**: 
![image](https://user-images.githubusercontent.com/64259198/108545725-7375a100-72e8-11eb-8123-ae4bcb13e67c.png)

**How/when does this happen**: if I jump in gamemode 1 its normaly, but in gm 0 it is very buggy you can see in that video. I tested it without Matrix and it was normal.
**Video of false positive**: https://drive.google.com/file/d/10BYnaFs-riT5haaWVE-S3Q2DWiW9d3Y_/view?usp=sharing
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
https://just-paste.it/fpQx2s2Tfn

**Comment by jiangdashao** [comment]
video deleted
