### ISSUE TITLE
[REQUEST] MovePos memory leak

### ISSUE THREAD

**Issue by RoccoDev** [jiangdashao/Matrix-Issues#2298]
There is a slight memory leak in the movement handler (`me.rerere.matrix.lIIIllllllIIIII` in 6.0.4 - the listener for PlayerMoveEvent).
There are two issues here:

- `PlayerMoveEvent` isn't called when the player changes worlds/dimensions (except when it's teleported in the air, which causes downwards moves);
- The `MovePos`s aren't removed from the queue when the player changes worlds/dimensions.

This is able to create a pretty important memory leak when a player is AFK, since it could carry `Location`s (and therefore `World`s) from multiple worlds (as if I've understood it correctly, it stores the 15 most recent locations according to `PlayerMoveEvent`).

My suggestion would be to run the same logic on `PlayerTeleportEvent` for the first issue, and to **clear the queue** on `PlayerChangedWorldEvent` (I'm assuming you use the location queue to get the most recent "safe" location or to perform distance checks, thus it wouldn't make sense to store locations from different worlds).

**Comment by jiangdashao** [comment]
I clear it on other places
