### ISSUE TITLE
[FP] Fly, Strict Glide - Jumping on the Side of Blocks

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#230]
## Basic Information
**Verbose message(s)**: https://i.imgur.com/Vragwtz.png
**How/when does this happen**: Watch the video.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgo0xMQu8Mr0fLDvAew

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
I think it caused by your `BlockWalk` cheat
and it also not important
I can't reproduce it
