### ISSUE TITLE
[FP] Knockback + Edgesneaking

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2303]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Verbose messages**: https://pasteboard.co/JQa4s66.png
**How/when does this happen**: When a player gets hit with a knockback item and this player is sneaking on an edge
**Video of false positive**: https://youtu.be/4JfYsqnbhDg
**Other information**: This could have something to do with this MC Bug: https://bugs.mojang.com/browse/MC-200282

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
can't fix
