### ISSUE TITLE
[BYPASS] + [FP] Honey Blocks

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2306]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Hacked client**: Sigma
**Link to hacked client**: sigmaclient.info
**Cheat that bypassed**: Highjump
**Video of bypass**: https://youtu.be/JKoLDnC50s8
**Video of false positive**: https://youtu.be/L8HQ5PYyluk
**Other information**: Honey Block check really needs some rework. The honey "tag" for honey blocks rarily pop up in verbose messages.

**Comment by DontNeedAName** [comment]
Similar to liquidbounce aac 3.3.13 fly bypass, this also works on vines, ladders and water.

**Comment by jiangdashao** [comment]
crap
