### ISSUE TITLE
[FP] Killaura Mouse Speed

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2308]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: video
**How/when does this happen**: When strafing around while hitting a target.
**Video of false positive**: https://youtu.be/OPycaxB92jI
**Other information**:  Try hitting slower to reduce mouse shaking at it will sometimes randomly start flagging.

**Comment by jiangdashao** [comment]
then disable it

**Comment by jiangdashao** [comment]
nvm
