### ISSUE TITLE
[BYPASS] NoSlow

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2311]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce
**Link to hacked client**: liquidbounce.net
**Cheat that bypassed**: NoSlow
**Video of bypass**: https://youtu.be/-WSPTDKb3jk
**Other information**: This doesn't always work and I'm not sure why. Make sure to have 0 vl. NoSlow check is generally weird. NCP is much better at this.

**Comment by jiangdashao** [comment]
It does not bypass, if the player uses Noslow hacking with ~100% speed, Matrix will directly clean the using item status of the player

**Comment by DontNeedAName** [comment]
> 
> 
> It does not bypass, if the player uses Noslow hacking with ~100% speed, Matrix will directly clean the using item status of the player

But what about soul sand?

**Comment by DontNeedAName** [comment]
That sometimes doesn't lag back correctly.

**Comment by jiangdashao** [comment]
not important

**Comment by DontNeedAName** [comment]
Also the sword not getting cancelled correctly is still a bug that should be fixed.

**Comment by jiangdashao** [comment]
Tell me how to cancel correctly?

**Comment by DontNeedAName** [comment]
As suggested in #1769 ((CraftPlayer)p).getHandle().clearActiveItem() or ((CraftPlayer)p).getHandle().releaseActiveItem() (I don't know whats the difference)

**Comment by jiangdashao** [comment]
Already did that

**Comment by jiangdashao** [comment]
But this state will not be synchronized to the client, this is unsolvable

**Comment by DontNeedAName** [comment]
But for me it's working. (I'm on 1.16.5)
