### ISSUE TITLE
[REQUEST] Pitch Check

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2312]
**What features/checks do you need?:**
I really don't know why this got removed, but there is currently no check for having a pitch above 90 or below -90. This should instantly result in a kick by default, because the vanilla client never sends something like this. This can also patch some shitty scaffolds.

**Comment by DontNeedAName** [comment]
The entire derp check seems to be nonexistent. You can sprintjump around while using derp.

**Comment by jiangdashao** [comment]
it does exist in the move check, but not working correctly

**Comment by DontNeedAName** [comment]
> 
> 
> it does exist in the move check, but not working correctly

Same with the noslow soul sand check. It sometimes randomly stops working. Please also fix that.

**Comment by jiangdashao** [comment]
already fixed
