### ISSUE TITLE
[BYPASS] Interact/HandNoClip/GhostHand

### ISSUE THREAD

**Issue by AMDBartek** [jiangdashao/Matrix-Issues#2314]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
**Hacked client**: Wurst 1.8.9
**Link to hacked client**: https://www.wurstclient.net/download/minecraft-1-8/
**Cheat that bypassed**: Interact/HandNoClip/GhostHand
**Video of bypass**: https://streamable.com/3gp2y3
**Other information**: LiquidBounce's GhostHand bypasses too. Wurst's HandNoClip only works for 1 block in between, however, LiquidBounce's GhostHand worked up to 3 blocks.

This is quite bad because, for example, you could open a chest that is inside someone's house and take their items.

## Configuration Files
**Link to checks.yml file**: Happens on default checks
**Link to config.yml file**: Happens on default config

**Comment by jiangdashao** [comment]
Interact check got removed now, I am still working on recoding it

**Comment by AMDBartek** [comment]
@jiangdashao Will this check be added back?

**Comment by jiangdashao** [comment]
> @jiangdashao Will this check be added back?
> 
> Will it make it into 6.1.0?

soon™
