### ISSUE TITLE
[BYPASS] add speed.tp for vertical movements

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2316]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Other information**: Move check force setback falses too much to have enabled, but without it enabled players can highjump 100+ blocks. Add hard limit to Y movement to prevent.

**Comment by DontNeedAName** [comment]
Yeah, even with the check enabled, players can sometimes teleport up vertically using liquidbounce old rewinside teleport.

**Comment by AMDBartek** [comment]
Yeah, something should be added to prevent players from teleporting vertically.

**Comment by jiangdashao** [comment]
no, if u find false positive, report it
