### ISSUE TITLE
Killaura snap head  & vanilla protocol #05 [FP] 

### ISSUE THREAD

**Issue by smertnix55551** [jiangdashao/Matrix-Issues#2317]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: matrix.rip, client version: 1.12.2
**Verbose messages**: Killaura snap head, Killaura combat not following vanilla protocol #05
**How/when does this happen**: i get fp for legit aiming
**Video of false positive**: https://youtu.be/wcL4AT9U08g
**Other information**: server - matrix.rip, client version: 1.12.2

**Comment by jiangdashao** [comment]
useless reporting

**Comment by jiangdashao** [comment]
I do not accept false positive feedback triggered deliberately
