### ISSUE TITLE
[FP] Jumping under neath a lantern block

### ISSUE THREAD

**Issue by Maximillus** [jiangdashao/Matrix-Issues#2318]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.4
**Verbose messages**: 
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.072/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:5 ping:2226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.087/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:10 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.101/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:15 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.115/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:20 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.13/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:25 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.144/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:30 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.159/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:35 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.173/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:40 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.188/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:45 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.202/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:50 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.217/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:55 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.231/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:60 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.245/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:65 ping:226 tps:20.0 lp:0 component: move.vert ver: 1.16.x
(23:34:12) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.26/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:70 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.014/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:75 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.029/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:80 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.043/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:85 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.058/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:90 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.072/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:95 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.087/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:100 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.101/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:105 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.115/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:110 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.13/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:115 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:13) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.144/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:120 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.159/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:125 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.173/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:130 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.188/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:135 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.202/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:140 ping:229 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.217/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:145 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.231/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:150 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.245/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:155 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:14) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.26/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:160 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.014/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:165 ping:226 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.029/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:170 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.043/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:175 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.058/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:180 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.072/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:185 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.087/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:190 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.101/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:195 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.115/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:200 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.13/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:205 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.144/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:210 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.159/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:215 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.173/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:220 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.188/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:225 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.202/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:230 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.217/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:235 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.231/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:240 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:15) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.245/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:245 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
(23:34:16) Maximillus failed Move check | unexpected vertical movement (motion: 0.0/-0.029, hor: 0.0, buffer: 0.26/true, ground: +-, setback: -, vel: none, from: 67.029, past: 0.0, tags: collision) (+5) | vl:250 ping:231 tps:20.0 lp:1 component: move.vert ver: 1.16.x
**How/when does this happen**: when you jump under of a lantern block, even once, you begin to alert move.vert
**Other information**: 

## Configuration Files
**Link to checks.yml file**: its matrix default

**Comment by jiangdashao** [comment]
can't be fix
