### ISSUE TITLE
[BYPASS] Omnisprint

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#232]
## Basic Information
**Hacked client**: Saturn b21
**Link to hacked client**: https://1drv.ms/u/s!ApY4tKsF8vPUgo0-_7tWudThimDKgA
**Cheat that bypassed**: Sprint
**Screenshot of cheat settings**: https://i.imgur.com/QE4fNq4.png
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgo04Se_mCx4WgCPRGQ

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by True-cc** [comment]
Doesn't look like it can be blocked because I think what's happening is that the player is looking at where you're running server side, but not client side.

**Comment by ignPerformance** [comment]
It's the same speed, so it should be blocked.

**Comment by jiangdashao** [comment]
I can't use that client
Anyway, as True-CC's said, it's unimportant
And the sprint direction is made to detect sprint scaffold

**Comment by ignPerformance** [comment]
You have to add -noverify to the JVM arguments.

**Comment by ignPerformance** [comment]
I'll re-open this until you close it again.
