### ISSUE TITLE
[FP] Fp

### ISSUE THREAD

**Issue by kacperleague9** [jiangdashao/Matrix-Issues#2321]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 
**Verbose messages**:  (23:10:34) KapceRBLX Move check | send invalid ability packets (simple flight hacking) (+20) | vl:40 ping:156 tps:20.0 lp:3 komponent: move.ability wersja: 1.16.x
(23:10:34) KapceRBLX Velocity check | (analyser) fast fall after when getting knockback: -0.42,0.333 (+3) | vl:3 ping:156 tps:20.0 lp:3 komponent: vel.ana wersja: 1.16.x
**How/when does this happen**: If you spam double jump and shift with this plugin https://www.spigotmc.org/resources/treys-double-jump-api.19630/ you will get a fp
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Its fresh generated only translated**:

**Comment by me-rgb** [comment]
Don't use double jump plugins.

**Comment by kacperleague9** [comment]
@me-rgb what? i need one on my hub so players can travel faster

**Comment by jiangdashao** [comment]
why you use anticheat on a hub server? @kacperleague9

**Comment by jiangdashao** [comment]
it works good in my test

**Comment by kacperleague9** [comment]
@jiangdashao i use it because players can earn rewards on hub too by doing tasks, i dont want them to cheat

try default configuration and spam shift when jumping
