### ISSUE TITLE
[ERROR] An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by crafter23456** [jiangdashao/Matrix-Issues#2322]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ dont know] The issue happens on default config.yml and checks.yml
- [ dont know] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.16.5
**Error(s) found in console**:  https://just-paste.it/69fa3E0Of3
**How/when does this happen**: dont know
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://just-paste.it/cz1565vfE0
**Link to config.yml file**: https://just-paste.it/v2mAA8O35W (I removed premium password and database access)

**Comment by jiangdashao** [comment]
ignore it
