### ISSUE TITLE
Scaffold bridge too fast FP

### ISSUE THREAD

**Issue by smertnix55551** [jiangdashao/Matrix-Issues#2323]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16
**Verbose messages**: scaffold fast bridge (delay)
**How/when does this happen**: 
**Video of false positive**: https://www.youtube.com/watch?v=Q6Vd1znzDJA&ab_channel=GujaratGamerMeet
**Other information**: scaffold fp

## Configuration Files
**Link to checks.yml file**:

**Comment by DontNeedAName** [comment]
You can change the min-delay in config.yml. The velocity false positive is pretty weird tho...

**Comment by jiangdashao** [comment]
set min delay lower

**Comment by DontNeedAName** [comment]
> 
> 
> set min delay lower

What about the velocity false positive at the end?
