### ISSUE TITLE
Speed bypass

### ISSUE THREAD

**Issue by me-rgb** [jiangdashao/Matrix-Issues#2326]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8 
**Hacked client**: Exhibition 
**Link to hacked client**: Paid, minesense.pub
**Cheat that bypassed**: Speed mode: hypixel
**Video of bypass**: n/a
**Other information**: 0 flag, can't use whilst killauraing

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
It's a private client, do you have that? @me-rgb
