### ISSUE TITLE
DiscordSRV and Matrix [INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by Nononitas** [jiangdashao/Matrix-Issues#2327]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] The incompatible plugin is up-to-date
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Incompatible plugin**: DiscordSRV
**Verbose messages (or) console errors**:  none
**How/when does this happen**:  
If you add these listeners to DiscordSRV and load chunks for a little while (flying in createive) your server will start to lag.
https://pastebin.com/eZ5bKVPK

## Configuration Files
**Link to checks.yml file**: default

I report it here because other plugin using DiscordSRV doesn't create any lag. Only if I add listeners from Matrix.

**Comment by jiangdashao** [comment]
Not my problem

**Comment by Nononitas** [comment]
Ok thought you may be able to fix the problems caused by your plugin
