### ISSUE TITLE
[FP] Water flow Move 

### ISSUE THREAD

**Issue by crafter23456** [jiangdashao/Matrix-Issues#2329]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 Paper
**Verbose messages**: have a look at the video
**How/when does this happen**: have a look at the video
**Video of false positive**: 
https://drive.google.com/file/d/14s7tKZLGAI7-zu9YL_etE2qyA2an-ex8/view?usp=sharing
https://drive.google.com/file/d/1DOOP1c3kgvNi5r21wFRgNs0gd_ckYJ3z/view?usp=sharing

## Configuration Files
**Link to checks.yml file**: https://just-paste.it/xhfvG938zo

**Comment by jiangdashao** [comment]
same as #2324
