### ISSUE TITLE
[ERROR] Potential error for users running Java 16

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2331]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Any
**Error(s) found in console**:
```
(Matrix) | <MV> Modified the rotation delta value check
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.rerere.matrix.IlIIllllIIIIIII$IIIIllllllIllII (file:/plugins/Matrix_6.0.4_release.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of me.rerere.matrix.IlIIllllIIIIIII$IIIIllllllIllII
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
(Matrix) | Injected server connection handler
```
**How/when does this happen**: Server startup
**Other information**:
Reflections are blocked and turned into errors in Java 16 and above. This illegal reflection will most likely cause issues for users running Java 16.

I have not personally tested if this happens, but from other user's experiences this will be blocked.

**Comment by AMDBartek** [comment]
This can be really bad for people using new versions of Java as the illegal access operation will be blocked.

**Comment by DontNeedAName** [comment]
If reflections are blocked in 1.16, will that be the death of nms operations? Because almost all nms stuff requires reflections... That would be really bad. How on earth will people do Protocol Hacks or Anticheats then?

**Comment by Encode42** [comment]
@DontNeedAName Not *all* reflections are blocked, just the ones that Java does not allow as seen above.

**Comment by DontNeedAName** [comment]
> 
> 
> @DontNeedAName Not _all_ reflections are blocked, just the ones that Java does not allow as seen above.

I'm sure there will be bypasses tho. Modifiers field was patched in java 12, but it's still possible with other utility classes. (I think it's called varlookup)

**Comment by DontNeedAName** [comment]
Still tho. Many plugins are causing this warning. Will they all break?

**Comment by Encode42** [comment]
Yes

**Comment by ZakShearman** [comment]
Personally I believe this to be an important issue as there are much more compelling additions in moving from java 11 -> 17 vs from 8 -> 11. I can see quite a few developers utilising java 17 once it's been out for a while (and I already use 15/16 for all my personal projects because of the new features).

**Comment by jiangdashao** [comment]
Java has updated multiple versions, and there is still a huge gap with Kotlin, lol

**Comment by jiangdashao** [comment]
Ignore it
