### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by kacperleague9** [jiangdashao/Matrix-Issues#2332]
**What features/checks do you need?:**
Compability with ProCosmetics
https://www.spigotmc.org/resources/procosmetics-300-cosmetics-treasurechests-eula-compliant-1-8-1-16-support.49106/
some gadgets cause FPS

**Comment by jiangdashao** [comment]
why you use gadgets with an anticheat? it should install in the lobby server only

**Comment by kacperleague9** [comment]
Players can use cosmetics on other gamemodes too but only on spawn

pt., 26 mar 2021, 09:45 użytkownik RERERE ***@***.***>
napisał:

**Comment by jiangdashao** [comment]
can't support cosmetics
