### ISSUE TITLE
[INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by boss-space** [jiangdashao/Matrix-Issues#2333]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**1.16.5**: 
**discordSRV**: 
**none**: 
**How can I put matrix messages in discord?**: 
**none**: 
**none**: 

## Configuration Files
**default**:

**Comment by jiangdashao** [comment]
ask it in discord server or see discordsrv plugin wiki
