### ISSUE TITLE
Lots of bypasses :D

### ISSUE THREAD

**Issue by me-rgb** [jiangdashao/Matrix-Issues#2334]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: DeepwaterHorizon
**Link to hacked client**: no srry i payed 250$ for it if u rlly need it dm []me24345#0728
**Cheat that bypassed**: lots
**Video of bypass**: Shit vid but here's a link to download: https://www.mediafire.com/file/3urs0o0p4mysih4/2021-03-25_19-32-44.mkv/file
**Other information**: idk

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**:default

**Comment by kacperleague9** [comment]
it clearly detected something

**Comment by jiangdashao** [comment]
use streamable.com, don't use mediafire :(

**Comment by jiangdashao** [comment]
report it on discord server first
