### ISSUE TITLE
[BYPASS] Jumping on water with Jesus

### ISSUE THREAD

**Issue by JasonHorkles** [jiangdashao/Matrix-Issues#2340]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper version git-Paper-571 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Hacked client**: Aristois 1.16.5
**Link to hacked client**: https://aristois.net/download
**Cheat that bypassed**: Jesus
**Video of bypass**: https://youtu.be/_wGyVKAchis
**Other information**: Only happens when jumping on the water; standing will be detected

## Configuration Files
**Link to checks.yml file**: https://paste.gg/p/JasonHorkles/4115e3bc7066443daa8edd0251cad6ac
**Link to config.yml file**: https://paste.gg/p/JasonHorkles/0683fe6c19c345a680664bd2163487a1

**Comment by jiangdashao** [comment]
It can't work
