### ISSUE TITLE
[FP] Move Setback On Snow Layer

### ISSUE THREAD

**Issue by realriccio** [jiangdashao/Matrix-Issues#2343]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Verbose messages**: failed Move check | unexpected vertical movement, failed Move check | unexpected horizontal movement
**How/when does this happen**: When walking on a single layer of snow the player gets continuously set back.
**Video of false positive**: Not needed.
**Other information**: Can be tested on test.matrix.rip coords 198 63 155.

**Comment by jiangdashao** [comment]
One layer of snow doesn't have a hitbox, so the player shouldn't be able to walking on it
And, there is no one layer of snow **in the air** in production server, it only can made by worldedit
