### ISSUE TITLE
[FP] Right Click Message on Towering

### ISSUE THREAD

**Issue by crafter23456** [jiangdashao/Matrix-Issues#2344]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper 1.8.9
**Verbose messages**: /
**How/when does this happen**: 
**Video of false positive**: 
**Other information**: 
I have scaffold.right_cps.enable: false but in my database I see "right click too fast (cps: 45 length: 1000)" where 2VL get added, 2VL is only tower, but why right click on tower? 
I don't have a video, but they arent hacking. Only mouse abuse, it's MLG Rush

## Configuration Files
**Link to checks.yml file**:
https://just-paste.it/3YNvbvDBI0

**Comment by jiangdashao** [comment]
It's a bug, right-click check didn't read the config
