### ISSUE TITLE
[FP] Slow falling Elytra FP

### ISSUE THREAD

**Issue by Ryoyo2** [jiangdashao/Matrix-Issues#2345]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Airplane-"87d4a17" (MC: 1.16.5)
**Verbose messages**: https://pastebin.com/uvYcmiwW
**How/when does this happen**: See video
**Video of false positive**: https://youtu.be/143iKAd3tT8
**Other information**: 

## Configuration Files
**Link to checks.yml file**:https://github.com/Encode42/MatrixChecks/releases/tag/1.10

**Comment by jiangdashao** [comment]
can't reproduce
