### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by meerpaluten** [jiangdashao/Matrix-Issues#2347]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:  https://paste.timo.cloud/yihamakezo.sql

**How/when does this happen**: When a Player knock me with a Knockback I Stick 
**Video of false positive**:  https://youtu.be/OaLZYXbYrdg
**Other information**: MLGRush Modi

## Configuration Files
**Link to checks.yml file**: https://paste.timo.cloud/fikeheveqi.bash

**Comment by jiangdashao** [comment]
Are you using any knockback modify plugin?

**Comment by meerpaluten** [comment]
no, we don`t use any plugin witch modify the knockback

**Comment by jiangdashao** [comment]
try reproduce it on a clean server(matrix+protocollib+spigot)

**Comment by DontNeedAName** [comment]
I think it's the plugin teleportation. Teleporting while moving causes false positives. I reported that a few months ago. This is just another example.
