### ISSUE TITLE
[FP] Move FP on snow layer

### ISSUE THREAD

**Issue by Brottweiler** [jiangdashao/Matrix-Issues#2348]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: https://gist.github.com/Brottweiler/ffe03fc7cfcdaa67107e3d1abc3a84ec
**How/when does this happen**: 1.16 client walking on snow layer
**Video of false positive**: https://streamable.com/x6quol
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
premium

**Comment by realriccio** [comment]
This is the same bug i reported here https://github.com/jiangdashao/Matrix-Issues/issues/2343

**Comment by Brottweiler** [comment]
> This is the same bug i reported here #2343

I see that it is marked **wontfix**. The issue here is that, yes, 1 layer snow doesn't have a hitbox. But if you are 1.16 on a 1.8 server, the 1 layer snow will become a 2 layer snow to the client, which does have a hitbox. 

But matrix thinks you are like... flying ontop of it, since you are too high up I assume.

**Comment by jiangdashao** [comment]
I can't reproduce it on my server...

**Comment by jiangdashao** [comment]
https://streamable.com/iwp9qd

**Comment by Brottweiler** [comment]
I think this is causing it https://github.com/ViaVersion/ViaVersion/blob/00b4c9b1f8220ae41363e7b5aae3dd0d6b1f2e12/common/src/main/resources/assets/viaversion/config.yml#L120

**Comment by jiangdashao** [comment]
Same as 1.8 client, turn off it
