### ISSUE TITLE
[ERROR] Managing hotfixes

### ISSUE THREAD

**Issue by x1p** [jiangdashao/Matrix-Issues#2350]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Error(s) found in console**: https://pastebin.com/raw/ePPmvVT3
**How/when does this happen**: delete the running jar
**Other information**: Hotfixes appear regularly and that is super. Normally you would stop the server, change files, start the server. That doesn't work on production servers, since they always run. I delete jar files at night, place the new jar and wait for the restart. This works with almost all plugins.
Matrix somehow needs it's jar from time to time according to the warning.
A workaround could be to unload/load Matrix with plugman. This is not recommended of course, but helps against this warning spam. I rather have the ability to silently switch jar files.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
not a bug
