### ISSUE TITLE
[FP] Piston Slimebounce

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2351]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16
**Verbose messages**: https://pasteboard.co/JWXZUdX.png
**How/when does this happen**: When using a bouncy castle
**Video of false positive**: https://youtu.be/rgo2GeHf_nA
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
Will players make this kind of thing in a production environment?

**Comment by Pascalpex** [comment]
Only if they want to have fun and bounce around
