### ISSUE TITLE
[FP] LabyMod Emotes Incompatibility

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2352]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: https://pasteboard.co/JWZqWjE.png
**How/when does this happen**: Using emotes from LabyMod
**Video of false positive**: https://youtu.be/8wyg7TOVwEo
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

Is it possible to make this compatible?

**Comment by jiangdashao** [comment]
not a false

**Comment by jiangdashao** [comment]
Matrix is only compatible with vanilla clients
