### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by FlexaLOL** [jiangdashao/Matrix-Issues#2353]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9 (Matrix server)
**How/when does this happen**: I go inside a villager, then start hitting it with high mouse sensibility
**Video of false positive**: https://www.youtube.com/watch?v=wRA3KuB8Hmg
**Other information**:  my discord is JustAnAnnonymousPizza#0409 (The pizza man), and this was tested on matrix test server
**Server**: Matrix test server

**Comment by jiangdashao** [comment]
Only receive false positive feedback in the production environment, and deliberately triggered false positives will not be accepted
