### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by itsWarHammer** [jiangdashao/Matrix-Issues#2354]
**What features/checks do you need?:**
Chest Stealer -- And possibly NoKeepSprint if that is non existent

**Comment by itsWarHammer** [comment]
If Keep sprint is already a feature then here is my "bypass" report

**Comment by jiangdashao** [comment]
I won't add the chest stealer check, it will bring many false positives
and there is already a keep sprint check, it's only for enterprise users
