### ISSUE TITLE
[FP] walk backward with speed 1 or 2

### ISSUE THREAD

**Issue by MrEDok** [jiangdashao/Matrix-Issues#2355]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**Verbose messages**: check discord
**Video of false positive**: check discord

## Configuration Files
Default config

**Comment by jiangdashao** [comment]
don't use outdated version
