### ISSUE TITLE
[FP] Scaffold (Tower)

### ISSUE THREAD

**Issue by Suqatri** [jiangdashao/Matrix-Issues#2359]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
    -> Note: I disable some checks (phase, chat) and change the max CPS to 50
- [X] I've tested if the issue happens on default config
    -> Note: I disable the bypass permission...

## Issue Information
**Server version**: paper 1.8
**Verbose messages**: (video)
**How/when does this happen**: (video) 
**Video of false positive**:  https://www.youtube.com/watch?v=2U9gEf9vdLE
**Other information**: matrix premium version, not the free version

## Configuration Files
**Link to checks.yml file**: https://hastebin.de/vuficixupo.yaml

**Comment by DontNeedAName** [comment]
Can confirm. This needs to be fixed.
