### ISSUE TITLE
[FP] Move on Snow layer

### ISSUE THREAD

**Issue by Encode42** [jiangdashao/Matrix-Issues#2360]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8?
**Verbose messages**: https://cdn.discordapp.com/attachments/365455566329348097/836628228973920266/2021-04-27_11.41.45.png
**How/when does this happen**: Walking onto a snow layer
**Video of false positive**:
1.16.5: https://cdn.discordapp.com/attachments/365455566329348097/836628525737443409/2021-04-27_11.37.08.mp4
1.8.9: https://cdn.discordapp.com/attachments/365455566329348097/836628540883075152/2021-04-27_11.39.13.mp4
**Other information**:
Happens on vanilla 1.8.9 and 1.16.5. Tested on `test.matrix.rip`. Could this be an issue with ViaVersion?

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
I guess it was caused by the server's built-in ac? I can't reproduce it
