### ISSUE TITLE
[INCOMPATIBILITY] Server performance with piston flying machine

### ISSUE THREAD

**Issue by MrEDok** [jiangdashao/Matrix-Issues#2367]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5
**How/when does this happen**: piston flying machine test with latest matrix when piston machine is working mspt is around 50 (when tested) when machine stop mspt went back to 20mspt
**Video of incompatibility**: 
**Other information**: 
![bild](https://user-images.githubusercontent.com/57065626/117333480-41acb900-ae99-11eb-90a6-42267c3063db.png)
![bild](https://user-images.githubusercontent.com/57065626/117333510-4b362100-ae99-11eb-8ac1-c2086adf4d05.png)

**Comment by jiangdashao** [comment]
did you tried the latest hotfix version? @MrEDok
