### ISSUE TITLE
[INCOMPATIBILITY] Matrix doesn't detect players as Bedrock

### ISSUE THREAD

**Issue by EkonC** [jiangdashao/Matrix-Issues#2368]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Waterfall #415
**Incompatible plugin**: GeyserMC
**Verbose messages (or) console errors**: `[MatrixBungee]: [Debug] .EkonC301 is not a bedrock player! (f:false)`
**How/when does this happen**: Every time a bedrock player joins the server, it doesn't detect them as bedrock (even though they are joining from bedrock.
**Other information:** Relevant plugins - Geyser 2.0, Floodgate 2.0, JPremium

## Configuration Files
**Link to checks.yml file**: matrix default

**Comment by jiangdashao** [comment]
does not support jpremium

**Comment by EkonC** [comment]
Thank you very much, it works now ♥
