### ISSUE TITLE
[ERROR] com.mysql.cj.exceptions.CJException: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by RalphORama** [jiangdashao/Matrix-Issues#2371]
## Troubleshooting Information

`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
   - Issue with database config which is disabled by default. I've checked with all other settings at their default values.
- [x] I've tested if the issue happens on default config

## Issue Information

**Server version**: `Tuinity version git-Tuinity-"b12d0cc" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
**Matrix version**: 6.1.1 (premium)
**Error(s) found in console**: [https://pastebin.com/RFwMbhfr](https://pastebin.com/RFwMbhfr)
**How/when does this happen**: When using Matrix SQL logging with MySQL (or equivalent) > 8.0

## Other information

I have had this issue occur with other plugins when setting up SQL integration. Matrix is missing this option, but my solution was to modify the connection string to include `allowPublicKeyRetrieval=true`. 

For example, in my LiteBans config:
```yaml
sql:
  # <snipping other config options>
  options: 'allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
```

And for DiscordSRV:
```yaml
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://<ip>:3306/<database>?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
```

This issue can easily be resolved by adding an option in the config to include SQL options like this, which are then passed to the JDBC driver.

## Configuration Files

**Link to checks.yml file**: I am using the default checks.yml file
**Link to config.yml file**: I am using the default config.yml file

**Comment by DontNeedAName** [comment]
I recommend doing this instead: https://qiita.com/shaching/items/5fe3d5df691b4ec53084

**Comment by RalphORama** [comment]
I do not have shell access to the server or the ability to ALTER USER.
