### ISSUE TITLE
[FP] Delay

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2373]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 3056-Spigot-4225eac-6f55b5b (MC: 1.16.5)
**Verbose messages**: in video
**How/when does this happen**: When putting on armor quickly.
**Video of false positive**: https://youtu.be/PLrWNyiDI1w
**Other information**: Only affects shifting armor, not shifting items in chests etc.

**Comment by That1G** [comment]
Wrong video uploaded. New link - https://streamable.com/ltonb4

**Comment by jiangdashao** [comment]
that's how it works, if u don't like it, disable it

**Comment by DontNeedAName** [comment]
Can you at least add an option to disable the inventory checks seperately? Because currently there is only one component called delay.inv and the false positive is in type C. I can only disable an entire component, meaning the entire inventory check.
