### ISSUE TITLE
[FP] Move check

### ISSUE THREAD

**Issue by That1G** [jiangdashao/Matrix-Issues#2376]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Tuinity-"7d36676" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Verbose messages**: 2 different types of messages, both related to move.

failed Move check | unexpected horizontal movement (motion: 0.262/0.25, buffer: 0.15/true, vet: 0.0, vec: 0.042, ground: ++, add: 0.019, past: 0.0,0.078, fr: 0.6, setback: -, vel: none, from: 4.0, rv: empty, ptags: collision, tags: collision) (+5) | vl:15 ping:82 tps:20.0 lp:2 component: move.hor

failed Move check | unexpected vertical movement (motion: 0.42/25.52, hor: 0.14, buffer: 10.0/true, ground: +-, setback: -, vel: none, from: 4.0, past: 0.0, tags: jump,attr_end) (+5) | vl:25 ping:82 tps:20.0 lp:6 component: move.vert

**How/when does this happen**: Sprint jumping / jumping while spamming with a customized gun plugin.
**Video of false positive**:  https://streamable.com/ltonb4
**Other information**: I use a mostly default config. Only thing I have edited is the time it takes to actually trigger a kick so I checked "It happens on default config & I tested it on default config"

**Comment by Tacosheel** [comment]
tuinity and yatopia does false flag/allow bypasses, idk why, but try it on paper.

**Comment by jiangdashao** [comment]
gun plugin link?

**Comment by jiangdashao** [comment]
no response
