### ISSUE TITLE
[ERROR] Disconnect

### ISSUE THREAD

**Issue by masterhacka** [jiangdashao/Matrix-Issues#2377]
Bedrock users on Xbox have the following issue: https://i.imgur.com/hEbw5j7.png

**Comment by jiangdashao** [comment]
Can't fix

**Comment by masterhacka** [comment]
Bedrock users get the matrix.bypass permission, but the error still happens

**Comment by jiangdashao** [comment]
It's not a check, it's a security module of matrix to prevent player send illegal move packets to crash matrix/server

**Comment by masterhacka** [comment]
Is it possible to disable this module with own risks in the config?

**Comment by masterhacka** [comment]
Or not?

**Comment by jiangdashao** [comment]
you can't
