### ISSUE TITLE
[REQUEST] Dispatch multiple kick/ban commands when exceeding VL

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2379]
**What features/checks do you need?:**
If a player reaches a certain number of VL, the kick/ban command is executed more than once. This is because the command that is executed is first sent to the BungeeCord using PluginMessagingChannel, and the BungeeCord executes a command to ban the player. I tried to give tempbypass before the command, but it didn't work.

**Comment by jiangdashao** [comment]
What do you mean? If you want to execute multiple commands, see the faq channel in the discord server

**Comment by DrakMC** [comment]
I would somehow like to execute only 1 command when reaching the VL of a player. Multiple ban commands are executed instead of one. For example, I would need some command to reset the VL of the player.

**Comment by jiangdashao** [comment]
Isn’t it only executed once?
