### ISSUE TITLE
[BYPASS] Jesus/WaterJump

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2381]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Aristois
**Link to hacked client**: aristois.net
**Cheat that bypassed**: WaterJump
**Video of bypass**: https://youtu.be/jy__aS0RQs4
**Other information**: This only works on 1.8.

**Comment by jiangdashao** [comment]
Can't reproduce it on local server
