### ISSUE TITLE
[BYPASS] NoSlow/Safewalk

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2382]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.16.5
**Hacked client**: Aristois
**Link to hacked client**: aristois.net
**Cheat that bypassed**: NoSlow
**Video of bypass**: https://youtu.be/Uao71VPMd8A
**Other information**: This needs to be fixed because it's basically like safewalk. Just make sure to cancel the sneaking if detected or add an option to disable it, because sneaking can sometimes desync.

**Comment by DontNeedAName** [comment]
Still barely flagging in latest hotfix...

**Comment by jiangdashao** [comment]
I make the player not sneaking to prevent desync

**Comment by DontNeedAName** [comment]
Well, then it's still a desync.
