### ISSUE TITLE
[ERROR] PacketEvent

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2384]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Error(s) found in console**: https://pastebin.com/raw/QsU3hJAs
**How/when does this happen**: I noticed this for the first time.

**Comment by jiangdashao** [comment]
ignore it
