### ISSUE TITLE
[FP] Move Check (Carpets)

### ISSUE THREAD

**Issue by AtditC** [jiangdashao/Matrix-Issues#2386]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 Paper
**Verbose messages**:

[ANTICHEAT] xIDDoS failed Move (move.vert) | unexpected vertical movement (motion: 0.063/0.42, hor: 0.265, buffer: 0.179/true, ground: ++, setback: -, vel: , from: 33.0, past: 0.0, tags: jump) | vl:5+5 client:1.16.x ping:93 lp:2 tps:20.0

[ANTICHEAT] xIDDoS failed Move (move.vert) | unexpected vertical movement (motion: 0.063/0.0, hor: 0.098, buffer: 0.135/true, ground: --, setback: -, vel: , from: 33.0, past: 0.0, tags: collision) | vl:100+5 client:1.16.x ping:107 lp:4 tps:20.0

[ANTICHEAT] xIDDoS failed Move (move.vert) | unexpected vertical movement (motion: 0.063/0.0, hor: 0.097, buffer: 0.031/true, ground: -+, setback: -, vel: , from: 33.0, past: 0.0, tags: collision) | vl:240+5 client:1.16.x ping:95 lp:6 tps:20.0

**How/when does this happen**: As you can see, it takes a few attempts until it happens. But once it "started", it will happen whenever you try to walk/jump on a carpet.
**Video of false positive**: https://www.youtube.com/watch?v=WpxiAzx865Q
**Other information**: It only happens for players using 1.8 clients. **EDIT:** It happens for 1.16 clients as well, and I'm assuming any versions between 1.8 and 1.16 as well. The server uses ProtocolSupport build 599, ProtocolLib 4.6.1, and Matrix 6.1.1 (currently the newest version).

## Configuration Files
**Link to checks.yml file**: It happens with the default config/checks, but the video shown was recorded with this configuration active: https://github.com/Encode42/MatrixChecks

**Comment by jiangdashao** [comment]
I can't reproduce: https://streamable.com/fm9s95
