### ISSUE TITLE
[REQUEST] Anti-InvMove

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2387]
**What features/checks do you need?:** I want Matrix to prevent players from walking arround while they have an inventory opened. This hack is called InvMove in Sigma 5

**Comment by DontNeedAName** [comment]
Opening your own inventory is sadly client side. You can only detect inventory move if they are clicking items while moving.

**Comment by Pascalpex** [comment]
what does `player.getOpenInventory();` do then

**Comment by DontNeedAName** [comment]
It returns chest inventories if the player has opened a chest for example. But it can't see a difference between the player opening and closing his own inventory.

**Comment by Pascalpex** [comment]
ok then

**Comment by DontNeedAName** [comment]
I mean like I said it IS possible to detect inventory move, but only if the player actually moves items or is opening a container like a chest. There's also the problem with false positives like sliding on ice, getting knockback or pushed etc.
But it is possible.

**Comment by Pascalpex** [comment]
So I guess I should wait and see what RE has to say on this request before closing it

**Comment by jiangdashao** [comment]
This check only can be implemented for 1.8 server/client, there is no such API for 1.9+ client/server, so I don't want to add invmove check
