### ISSUE TITLE
[INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by goosBanny** [jiangdashao/Matrix-Issues#2388]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] The incompatible plugin is up-to-date
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Purpur-1.16.5-1051
**Incompatible plugin**: VeinMiner https://www.spigotmc.org/resources/veinminer.12038/
**Verbose messages (or) console errors**: https://bin.birdflop.com/utiditutun.properties
**How/when does this happen**: When someone tries to Vein Mine
**Video of incompatibility**: Unable to add. Sorry!
**Other information**: Nothing!

## Configuration Files
**Link to checks.yml file**: https://raw.githubusercontent.com/Encode42/MatrixChecks/main/checks.yml

**Comment by Encode42** [comment]
Talk to Choco about this, there's nothing Matrix can do about the issue. If he needs any help with the new Matrix API, I can help.

**Comment by jiangdashao** [comment]
Matrix has added veinminer compatibility internally, why does he do it again?

**Comment by JasonHorkles** [comment]
> Matrix has added veinminer compatibility internally, why does he do it again?

matrix seems to still cancel the block breaking and flags the player for cheating, or at least it used to when he added the check

**Comment by 2008Choco** [comment]
Will have a release available tomorrow with the aforementioned pull request merged. Thank you @JasonHorkles :)
