### ISSUE TITLE
[FP] Move check when teleported while falling into void

### ISSUE THREAD

**Issue by Jitsuzai** [jiangdashao/Matrix-Issues#2389]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Spigot connected to a 1.16 waterfall
**Verbose messages**: https://pastebin.com/u9hFFg73
**How/when does this happen**: When you are falling into the void walking forward and then you get teleported you get a flag
**Video of false positive**: https://youtu.be/vFy_6WXLFkw
**Other information**: We are using the trial version of Matrix for now

**Comment by DontNeedAName** [comment]
This is just another example of matrix flagging with plugin teleports. This has been reported around 4 times already. RE doesn't seem to care.

**Comment by Jitsuzai** [comment]
> This is just another example of matrix flagging with plugin teleports. This has been reported around 4 times already. RE doesn't seem to care.

Oh ok, do you have any idea how to fix it?

**Comment by DontNeedAName** [comment]
> 
> 
> > This is just another example of matrix flagging with plugin teleports. This has been reported around 4 times already. RE doesn't seem to care.
> 
> Oh ok, do you have any idea how to fix it?

There is now way to fix this yourself. RE has to fix it. But like I said he keeps denying the issue.

**Comment by Jitsuzai** [comment]
> > > This is just another example of matrix flagging with plugin teleports. This has been reported around 4 times already. RE doesn't seem to care.
> > 
> > 
> > Oh ok, do you have any idea how to fix it?
> 
> There is now way to fix this yourself. RE has to fix it. But like I said he keeps denying the issue.

I see I thought you could disable something in the config, well thanks for your time I'm gonna close the issue then.

**Comment by DontNeedAName** [comment]
> 
> 
> > > > This is just another example of matrix flagging with plugin teleports. This has been reported around 4 times already. RE doesn't seem to care.
> > > 
> > > 
> > > Oh ok, do you have any idea how to fix it?
> > 
> > 
> > There is now way to fix this yourself. RE has to fix it. But like I said he keeps denying the issue.
> 
> I see I thought you could disable something in the config, well thanks for your time I'm gonna close the issue then.

That's actually my second problem with matrix currently: There are not that many config options to disable smaller parts of the checks. All you could do is disable the entire movement check. (Some servers actually did this and matrix got mocked for it)
In versions before 6.0 there was much more customization.
