### ISSUE TITLE
[ERROR] Server crash with Matrix installed

### ISSUE THREAD

**Issue by stillerek** [jiangdashao/Matrix-Issues#2394]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16 Purpur
**Error(s) found in console**: 
**How/when does this happen**: In some clients (for ex. BlazeClient) there is a command such as `.crash PlayerLook` that crashes the server only when Matrix is ​​installed
**Other information**: Recently I bought a Matrix, but I was a little disappointed with it because it can be used to kick the server, you will probably ask how?

Forgive me for choosing incompatibility when creating the application, but I didn't know what to choose

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Crash log? Client download link?

**Comment by jiangdashao** [comment]
No response
