### ISSUE TITLE
[FP] Scaffold/Tower

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2395]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.8.8
**Verbose messages**: https://pastebin.com/raw/4qYBTu5M
**How/when does this happen**: When placing blocks
**Video of false positive**: https://zombieapocalypse.eu/files/fake_detect_scaffold.mp4

**Comment by jiangdashao** [comment]
Don't install ViaVersion on bungee side
