### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by yooniks** [jiangdashao/Matrix-Issues#2396]
## Troubleshooting Information
- [ X] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ x] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tuinity 1.16.5
**Error(s) found in console**: https://pastebin.com/NsLUXUGP
**How/when does this happen**: This happens when the player joins, it's incompatibility with the newest viaversion, 4.x.x
**Other information**: It's happening since i updated viaversion for 1.17 support.

**Comment by jiangdashao** [comment]
what's your matrix version?

**Comment by yooniks** [comment]
> 
> 
> what's your matrix version?

6.1.1

**Comment by jiangdashao** [comment]
which hotfix version?

**Comment by yooniks** [comment]
Oh, I'm really sorry for wasting your time, I just updated and it seems to be fixed, I thought I'm running the newest version because of my (second) owner told me it's the newest version, but it wasn't HOTFIX, only RELEASE.

Thanks for answering.
