### ISSUE TITLE
[FP] 1.17 bug

### ISSUE THREAD

**Issue by crafter23456** [jiangdashao/Matrix-Issues#2397]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8

1.17 sends a position packet immediatelly when you right click into the air (interact), which causes matrix to false flag.
I know no 1.17 server plugin support, but most server run viaversion that also 1.17 player can go in. But would be great if Matrix 1.8 supports latest client behavior and not the latest software if you understand what I mean.

**Comment by DontNeedAName** [comment]
This is exactly what I already reported. This needs to be fixed.

**Comment by Encode42** [comment]
As stated above, related to #2393
