### ISSUE TITLE
[ERROR] Matrix can't pass activation.

### ISSUE THREAD

**Issue by NyashMyash99** [jiangdashao/Matrix-Issues#2408]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper git-Paper-10fa0c2d (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Error(s) found in console**: https://pastebin.com/11V5Hr4n
**How/when does this happen**: When loading Matrix.
**Other information**: On dedicated server running many servers that occupy ports.  As I understand, Matrix is trying to run something for activation, but can't do it because port is buzy.
## Configuration Files
**Link to checks.yml file**: https://pastebin.com/0dp0VZCN
**Link to config.yml file**: https://pastebin.com/vq19BgZz

**Comment by jiangdashao** [comment]
I can't solve it

**Comment by NyashMyash99** [comment]
Maybe output port to configuration so that users can choose it themselves?
