### ISSUE TITLE
[FP] punch in water

### ISSUE THREAD

**Issue by Incluuu** [jiangdashao/Matrix-Issues#2410]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**How/when does this happen**: punch bow in water
**Video of false positive**: https://www.youtube.com/watch?v=LdbI09RqoVo

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
hard to reproduce
