### ISSUE TITLE
[FP] Ender Pearl

### ISSUE THREAD

**Issue by Thin-Troll** [jiangdashao/Matrix-Issues#2411]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 Paper 1618
**Verbose messages**: 
**How/when does this happen**: This happens often in pvp moments, but even so it can be repeated simply by jumping from a height and throwing the Ender's eye several times (someday, yes, it will bring you back to the height) even if you threw the eye in the wrong place.
**Video of false positive**: https://drive.google.com/drive/folders/1bpzjCmhhZHIH3VYg2Wos_jUDiMNnh4rd?usp=sharing
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://github.com/QuantumSuite/MatrixChecks

**Comment by jiangdashao** [comment]
what? What's wrong in the video? IDK

**Comment by Thin-Troll** [comment]
players teleports in general not to where the Ender pearls are thrown.
Can't you see it in the video? do not make me laugh

**Comment by jiangdashao** [comment]
try 6.2.2_hotfix
