### ISSUE TITLE
[REQUEST] Multi-line GUI descriptions

### ISSUE THREAD

**Issue by TechnicallyCoded** [jiangdashao/Matrix-Issues#2417]
**What features/checks do you need?:**
When using the Matrix GUI, please make the descriptions multi-lined. At the moment, half of the text just goes off screen :/

![image](https://user-images.githubusercontent.com/29813490/124380753-bdbb5580-dcbe-11eb-95ae-3fa80e7d373c.png)

**Comment by jiangdashao** [comment]
Change your GUI scale

**Comment by TechnicallyCoded** [comment]
Thanks, you just detered me from paying for the plugin.

**Comment by jiangdashao** [comment]
If you think it’s my fault just because your client’s settings are wrong, then I beg you not to buy this plugin, I don’t need a client like you

**Comment by TechnicallyCoded** [comment]
If your plugin doesn't work because of a GUI scale set to 3, then that's your problem

**Comment by jiangdashao** [comment]
YOU ARE RIGHT!!!

**Comment by TechnicallyCoded** [comment]
oh and this is GUI scale 2 btw since you asked so nicely
![image](https://user-images.githubusercontent.com/29813490/124381694-2c4ee200-dcc4-11eb-8204-fc4e844c529f.png)

**Comment by TechnicallyCoded** [comment]
And no, I am not playing minecraft on gui scale 1 lmao
![image](https://user-images.githubusercontent.com/29813490/124381775-8e0f4c00-dcc4-11eb-87fd-28fce0f600b0.png)

**Comment by TechnicallyCoded** [comment]
Hopefully this can actually be taken care of. If it is, I will take that as a sign of realization that I am not a complete idiot and I will consider the plugin again. (and yes, gui readability is not the #1 priority of an anticheat but now this is just a game of principles for the way a future customer would be treated)

**Comment by jiangdashao** [comment]
I will fix it in next version
