### ISSUE TITLE
[FP] ender pearl error

### ISSUE THREAD

**Issue by Incluuu** [jiangdashao/Matrix-Issues#2418]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: spigot 1.8.8
**Verbose messages**: https://pastebin.com/qmb7rY7P
**How/when does this happen**: throw a ender pearl at the ceiling
**Video of false positive**: https://www.youtube.com/watch?v=2xuJdizIQxg
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default

**Comment by ojoeth** [comment]
Disabling phase checks seemed to fix this for me, since by throwing the Pearl you are phasing through the bedrock.

**Comment by Incluuu** [comment]
> Disabling phase checks seemed to fix this for me, since by throwing the Pearl you are phasing through the bedrock.

I've had this checking disable for a long time, and I'm still getting this error.
This bug appeared in version 6.0 matrix in 5.0 it is not there. The problem is with the move.

**Comment by jiangdashao** [comment]
I can't reproduce

**Comment by Incluuu** [comment]
> I can't reproduce

New Verbose messages: https://pastebin.com/Us3ZdkJN

Move check -> component: move.vert + move.gf

How to reproduce:

1. First find ceiling with above hight +20.
2. You must have at least 32 pearls.
3. Throw 2 pearls at the ceiling, when you are downstairs again, throw 2 pearls again and keep doing this.
4. Watch the movie again, I posted additional new verbose.
