### ISSUE TITLE
[FP] MOVE False Positives

### ISSUE THREAD

**Issue by LucaDoller** [jiangdashao/Matrix-Issues#2420]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9 (ViaVersion up to 1.17)
**Verbose messages**:  https://paste.mykns.net/aluriqubag.sql
**How/when does this happen**:  In different Gamemodes from our Server are Special Items and they produce the Flags
**Video of false positive**: It isn't a "Vanilla" Flag so the Video can't say anything
**Other information**: It is possible to make it able to disable following checks: unexoected horizontal movement, unexoected vertical movement, ground spoof

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
no video
