### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by WaterTheMelon** [jiangdashao/Matrix-Issues#2427]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [  ] The issue happens on default config.yml and checks.yml
- [  ] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.16.5
**Verbose messages**: N/A
**How/when does this happen**:  When a hackers attacks get canceled (And not set to 0) it cancels the attacked hits aswell
**Video of false positive**: 
**Other information**:

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
?
