### ISSUE TITLE
[BYPASS] Blink

### ISSUE THREAD

**Issue by MoonVN571** [jiangdashao/Matrix-Issues#2428]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2 
**Hacked client**: Wurst 3
**Link to hacked client**: https://github.com/WurstPlus/wurst-plus-three
**Cheat that bypassed**: Blink
**Video of bypass**: https://cdn.discordapp.com/attachments/625715711481741324/869461845776412742/Wurst3___v0.7.0_2021-07-27_13-09-26.mp4 (download it)
**Other information**: 

## Configuration Files
**Link to checks.yml & config.yml file**: 
+ https://cdn.discordapp.com/attachments/867428599372185660/869462685765484554/Config__Checks.rar

**Comment by jiangdashao** [comment]
useless, low distance blink
