### ISSUE TITLE
[BYPASS] Step

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#243]
## Basic Information
**Hacked client**: Medusa 0.5.0
**Link to hacked client**: http://www.mediafire.com/file/f5en50qdk98pm9m/Medusa-0.5.0.rar
**Cheat that bypassed**: Step
**Screenshot of cheat settings**: Watch the video.
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgo4ykLN49iMgkm9rJg
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

# Server Infomation
**Server Version**: Tree.ac
**Matrix Version**: Tree.ac
**ProtocolLib Version**: Tree.ac

**Comment by jiangdashao** [comment]
one block step
I won't fix it
