### ISSUE TITLE
[FP] levitation effect and half brick

### ISSUE THREAD

**Issue by Dmitri233** [jiangdashao/Matrix-Issues#2432]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Verbose messages**: https://z3.ax1x.com/2021/07/29/WHMCVJ.png
**How/when does this happen**: When there is a levitation effect, it may happen in the vicinity of half a brick
**Video of false positive**: https://youtu.be/OSya7U7QYDM
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
什么版本

**Comment by Dmitri233** [comment]
1.17.1 matrix6.2.3 ,在潜影贝打开时攻击还经常会有hitbox误报

**Comment by jiangdashao** [comment]
试试6.3.0_beta

**Comment by Dmitri233** [comment]
我是白嫖版😥

**Comment by jiangdashao** [comment]
那在qq群吗？叫啥

**Comment by Dmitri233** [comment]
不在 我都不知道有群

**Comment by jiangdashao** [comment]
809411919

**Comment by Dmitri233** [comment]
我测试了一会 没出现这样的问题了
