### ISSUE TITLE
[FP] Teleport false positive

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#2433]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: video
**How/when does this happen**: always
**Video of false positive**: https://youtu.be/UTYvMOF8wUE

## Configuration Files
**Link to checks.yml file**: default

**Comment by jiangdashao** [comment]
fixed
