### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Tranzitron** [jiangdashao/Matrix-Issues#2434]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.8.8
**Verbose messages**:  [Matrix] Tranzitron failed Move check | unexpected vertical movement (motion: -0.078/0.003, hor: 0.106, buffer: 0.244/true, ground: --, setback: -, vel: none, from: 101.249, past: 0.083, tags: empty) (+5) | vl:5 ping:102 tps:19.98 lp:3 component: move.vert ver: 1.8.x
**How/when does this happen**: Forward/Backward + Left/Right + Jump + Sword Blocking/Bow Shooting/Eating
**Video of false positive**: https://youtu.be/6uqbvclNv2c
**Other information**: It probably work with more items

## Configuration Files
**Link to checks.yml file**: Tree.ac Anticheat test server (/ac to select the anticheat)

**Comment by jiangdashao** [comment]
can't reproduce, and I guess no one in the production server would do this
