### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Tranzitron** [jiangdashao/Matrix-Issues#2435]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: [Matrix] Tranzitron failed Move check | unexpected vertical movement (motion: -0.005/0.037, hor: 0.097, buffer: 0.021/true, ground: --, setback: -, vel: none, from: 111.06, past: 0.118, tags: empty) (+5) | vl:5 ping:110 tps:19.97 lp:2 component: move.vert ver: 1.8.x
**How/when does this happen**: Forward +Jump on slime blocks with ladders (see video with keystrokes)
**Video of false positive**: https://youtu.be/pZqr3CaL5ZY
**Other information**: Edit: works with any blocks

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
not important
