### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Outlander87** [jiangdashao/Matrix-Issues#2437]
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

**Server version**: Paper 1.17.1 - latest build 
**Verbose messages**:  https://pastebin.com/N9Jujqky
**How/when does this happen**:  when a player jumps and rotate at 360 degrees and then clicks on the floor with right click
**Video of false positive**: https://streamable.com/axx7ao

**Link to checks.yml file** : default matrix config and default matrix checks yml
https://github.com/QuantumSuite/MatrixChecks/blob/main/checks.yml

**Comment by jiangdashao** [comment]
not important

**Comment by Outlander87** [comment]
> 
> 
> not important

excuse me?
