### ISSUE TITLE
[BYPASS] WintWare, Akrien

### ISSUE THREAD

**Issue by TheKlimoT** [jiangdashao/Matrix-Issues#2438]
- [x] Matrix 6.3.0 - ProtocolLib 4.6.0-SNAPSHOT-b490
- [x] Matrix is running 1.16.5
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
Version: Purpur 1.16.5
Client wintware: 1.12.2 
Client url:  https://github.com/xWhitey/WintWare-Client-SourceCode
Bypass: Timer/KillAura
Video: https://youtu.be/3xFcNg15Txk

## Configuration Files
Checks: default 
Config: default

**Comment by jiangdashao** [comment]
open a ticket on the discord server so that we can discuss some details here
