### ISSUE TITLE
[FP] Soulsand + Ice

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2439]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Verbose messages**: https://pasteboard.co/KgXFN3I.png
**How/when does this happen**: Sprinting + jumping fast in a two block space with soulsand and ice below
**Video of false positive**: https://youtu.be/DfNQuR499WQ
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default

**Comment by jiangdashao** [comment]
fixed
