### ISSUE TITLE
[FP] Shulker hitbox

### ISSUE THREAD

**Issue by Dmitri233** [jiangdashao/Matrix-Issues#2440]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  `git-Paper-202 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2406634)`  
**Verbose messages**: 
**How/when does this happen**: 玩家移动时攻击潜影贝的打开部分
**Video of false positive**: https://youtu.be/pd7jgLAFhhQ
**Other information**:  测试过 `Matrix6.3.0_beta` 和 `Matrix6.2.3` 上有这样的情况

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
fixed
