### ISSUE TITLE
[ERROR] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DrakMC** [jiangdashao/Matrix-Issues#2441]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: FlamePaper 1.8.8
**Error(s) found in console**: https://pastebin.com/raw/cB5T7A5d
**How/when does this happen**: When enabing plugin

**Comment by DrakMC** [comment]
On Paper 1.8.8 it's worked without any problem. WIth FlamePaper 1.8.8 it doesn't work. Last version worked fine.

**Comment by jiangdashao** [comment]
I will release a patch
