### ISSUE TITLE
[INCOMPATIBILITY] Matrix detecting but not ignoring GeyserMC clients

### ISSUE THREAD

**Issue by ramsom11** [jiangdashao/Matrix-Issues#2445]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.17.1
**Incompatible plugin**: 
GeyserMC
**Verbose messages (or) console errors**: 
None
**How/when does this happen**: 
When a player on Bedrock connects, this displays on the BungeeCord console:
![geyser](https://user-images.githubusercontent.com/60997764/131647476-a4371b72-0756-4110-8abe-c344353ab84e.PNG)
However, Matrix on the server still treats it like a standard java player and causes false positives.
Here's what server status says. Under Server Information, Geyser and BungeeGeyser say false.
![matrix](https://user-images.githubusercontent.com/60997764/131648159-7f35961b-4af2-4cab-a996-906d51a34b84.PNG)

**Video of incompatibility**: 
**Other information**: 
Latest GeyserMC installed on Bungee
Latest Matrix installed on server and Bungee

## Configuration Files
**Link to checks.yml file**:
Default configs used

**Comment by jiangdashao** [comment]
https://github.com/jiangdashao/Matrix-Issues/wiki/GeyserMC-Support

**Comment by jiangdashao** [comment]
follow the guide

**Comment by ramsom11** [comment]
All sorted! Thanks!
