### ISSUE TITLE
[BYPASS] Jesus

### ISSUE THREAD

**Issue by Pascalpex** [jiangdashao/Matrix-Issues#2453]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Hacked client**: LiquidBounce b72
**Link to hacked client**: https://liquidbounce.net/
**Cheat that bypassed**: LiquidWalk (Jesus) Mode: AACFly
**Video of bypass**: https://youtu.be/hqr19JPrGJU
**Other information**: AACFlyMotion has to be around 0.4 for a good result

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
fixed in  6.4.0
