### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by DontNeedAName** [jiangdashao/Matrix-Issues#2454]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 3096-Spigot-9fb885e-296df56 (MC: 1.16.5)
**Hacked client**: Hedes
**Link to hacked client**: 1337quip.win
**Cheat that bypassed**: Speed
**Video of bypass**: https://youtu.be/K56o6sQrKok
**Other information**: aac bhop 1 is a little faster than redesky ground but it flags more. They both bypass pretty well though.

**Comment by jamesgames69** [comment]
How much faster? Test on eu.loyisa.cn

**Comment by jiangdashao** [comment]
+1
