### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by Not-LagsAlot** [jiangdashao/Matrix-Issues#2455]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ Y ] Matrix and ProtocolLib are up-to-date
- [ Y ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ Y ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Azura
**Link to hacked client**: intent.store
**Cheat that bypassed**: Scaffold
**Video of bypass**: https://streamable.com/yffj53
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: N/A (tested it on eu.loyisa.cn so checks.yml access)
**Link to config.yml file**:N/A (tested it on eu.loyisa.cn so config.yml access)

**Comment by jiangdashao** [comment]
too slow
