### ISSUE TITLE
[BYPASS] Scaffold

### ISSUE THREAD

**Issue by Not-LagsAlot** [jiangdashao/Matrix-Issues#2456]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ Y ] Matrix and ProtocolLib are up-to-date
- [ Y ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [  ] The issue happens on default config.yml and checks.yml
- [  ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: Azura
**Link to hacked client**: intent.store
**Cheat that bypassed**: Scaffold
**Video of bypass**: https://streamable.com/2oplui
**Other information**: Bypass/Bug that you can scaffold if there are some blocks next to you. I was using a CubeCraft config during the scaffold

## Configuration Files
**Link to checks.yml file**: Idk I was on the eu.loyisa.cn server 
**Link to config.yml file**: Idk I was on the eu.loyisa.cn server

**Comment by jiangdashao** [comment]
it's not important, If there are squares near you, then you can directly click on them to place the squares
