### ISSUE TITLE
[FP] Flowing Water False Positive

### ISSUE THREAD

**Issue by LegendsOfMedieval** [jiangdashao/Matrix-Issues#247]
## Basic Information
**Verbose message(s)**: 
(09:19:40) My_English_Suck failed BadPackets check | slow timer(percent: 0.5, d:2,a: 100) (+19) | vl:38 ping:162 tps:19.89
(09:19:45) My_English_Suck failed BadPackets check | slow timer(percent: 0.5, d:2,a: 100) (+19) | vl:19 ping:159 tps:19.59
(09:19:48) My_English_Suck failed BadPackets check | slow timer(percent: 0.5, d:3,a: 100) (+19) | vl:38 ping:159 tps:19.92
(09:19:51) My_English_Suck failed BadPackets check | slow timer(percent: 0.505, d:9,a: 99) (+19) | vl:57 ping:159 tps:19.73
**How/when does this happen**: When you swim backward in flowing water.
**Video of false positive**: https://youtu.be/UaSwukIBZhU

## Configuration Files
**Link to checks.yml file**: https://textuploader.com/158mm
**Link to config.yml file**: https://textuploader.com/158mc

# Server Infomation
**Server Version**: git-Paper-616
**Matrix Version**: 1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
What are your plugins?

**Comment by jiangdashao** [comment]
SlowTimer check will be removed
