### ISSUE TITLE
[FP] Step into fences

### ISSUE THREAD

**Issue by masterstreamer** [jiangdashao/Matrix-Issues#248]
## Basic Information
**Verbose message(s)**: is phase into block (Phase)
**How/when does this happen**: 
By jumping onto a triangle of fences you get a false positive and get kicked
**Screenshot**: https://imgur.com/a/asG6gWE

# Server Infomation
**Server Version**: 1.13.2

**Comment by jiangdashao** [comment]
Please provide video evidence

**Comment by masterstreamer** [comment]
@jiangdashao Alright, see here: https://drive.google.com/file/d/1z0LxFV5zL041nku7fI2Q0VVqdOAFcTSF/view?usp=sharing

**Comment by ignPerformance** [comment]
Duplicate of #169.

**Comment by masterstreamer** [comment]
@ignPerformance No, it isn't duplicate. walking on side of a fence works fine, only as shown in my video there is a false positive. btw, walls are not causing this.

**Comment by ignPerformance** [comment]
Walking in between an intersect of 3 fences, I know. Same with cobblestone walls.
