### ISSUE TITLE
[FP] Fast PlACE

### ISSUE THREAD

**Issue by OverBrave** [jiangdashao/Matrix-Issues#249]
## Basic Information
**Verbose message(s)**: https://cdn.discordapp.com/attachments/392906483735592962/568096651252727808/unknown.png
https://cdn.discordapp.com/attachments/392906483735592962/568097387818778644/unknown.png
**How/when does this happen**: If you put the block sneaking the matrix because of the fast block kick the game.

# Server Infomation
**Server Version**:  1.13.2
**Matrix Version**:  1.8.9
**ProtocolLib Version**: Last

**Comment by ignPerformance** [comment]
Why do you purposely not provide video evidence? We need it.
