### ISSUE TITLE
Bypassing Jesus checks with Bhop

### ISSUE THREAD

**Issue by Rattle189** [jiangdashao/Matrix-Issues#25]
## Bypass Infomation
**Hack Client**: Aristois Build 232
**Bypassed Hacking Type**: Jesus
**Matrix Version**: 1.2.1
**Server Version**: 1.13.2

## Videos
https://www.youtube.com/watch?v=E-u-hez7aag

**Comment by jiangdashao** [comment]
I can't reproduce the bypass
