### ISSUE TITLE
[FP] Matrix Speed

### ISSUE THREAD

**Issue by coolpvpv** [jiangdashao/Matrix-Issues#251]
Verbose messages: watch the video
How/when does this happen: put stairs at the first block then a stone block infront of it and keep doing that to show you it watch the video sense its hard to explain
Video of false positive: https://streamable.com/5ymjo

Link to checks.yml file: its the default config the only thing i changed was the op bypass permission so i could test the anticheat
Link to config.yml file: its the default config the only thing i changed was the op bypass permission so i could test the anticheat

Server Version: 1.8.8
Matrix Version: 1.8.9 or whatever the newest version is
ProtocolLib Version: 4.4.0 or whatever the newest version is

**Comment by jiangdashao** [comment]
Please don't remove our template format, you issue is hard to read....

**Comment by ignPerformance** [comment]
@coolpvpv Reopen this with our format.

**Comment by ignPerformance** [comment]
Also, this is a duplicate issue.
