### ISSUE TITLE
[FP] Horse

### ISSUE THREAD

**Issue by LegendsOfMedieval** [jiangdashao/Matrix-Issues#254]
## Basic Information
**Verbose message(s)**: 
(04:13:56) My_English_Suck failed Speed check | entity speed | type: horse | distance: 0.6024546578660195 (+4) | vl:65 ping:167 tps:19.74
(04:13:56) My_English_Suck failed Fly check | t:e m=0.0 tk=10 et=5 vy=-0.0784000015258789 (+3) | vl:27 ping:167 tps:19.74
(04:13:59) My_English_Suck failed Speed check | entity speed | type: horse | distance: 0.6041042146803207 (+4) | vl:69 ping:162 tps:19.85
(04:13:59) My_English_Suck failed Fly check | t:e m=0.0 tk=10 et=5 vy=-0.0784000015258789 (+3) | vl:30 ping:162 tps:19.85
(04:13:59) My_English_Suck failed Speed check | faster than expected | t-e | 3.668 > 0.46499999999999997 | tag: a (+4) | vl:73 ping:162 tps:19.85
(04:13:59) My_English_Suck failed Speed check | faster than expected | t-e | 3.668 > 0.41500000000000004 | tag: c (+9) | vl:82 ping:162 tps:19.85
**How/when does this happen**: When you riding horse
**Video of false positive**: https://youtu.be/SZjZGHtGkUI

## Configuration Files
**Link to checks.yml file**: https://textuploader.com/158mm
**Link to config.yml file**: https://textuploader.com/158mc

# Server Infomation
**Server Version**: git-Paper-616
**Matrix Version**: 1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
This only happens when riding a very fast horse.
