### ISSUE TITLE
[INCOMPATIBILITY] Crackshot False hitbox (reach) posivities (explosives weapons)

### ISSUE THREAD

**Issue by artemati1** [jiangdashao/Matrix-Issues#256]
## Basic Information
**Incompatible plugin: CrackShot (Guns) 0.98.9**: 
**Verbose message(s): When one player damage other player by a grenade or RPG, Matrix gives false positives (hitbox check (reach)) .**: 
**Console error(s): null**:  
**Video of incompatibility: screenshots**: 

## Configuration Files
**checks.yml file **:

hitbox:
  enable: true
  angle:
    max: 90
    min_dist: 1.5
  reach:
    max_reach: 3.5
    enable_analyser: true
  cancel_vl: 8
  commands:
    20: 'matrix notify %player% tried to reach entity outside max reach distance (HitBox)'
    40: 'matrix notify %player% tried to reach entity outside max reach distance (HitBox) #2'
    60: 'matrix kick %player% Reach/HitBox Hacks'

# Server Infomation
**Server version: Spigot 1.12.2**: 
**Matrix version: 1.8.9**: 
**ProtocolLib version: 4.4.0**:
![image](https://user-images.githubusercontent.com/49755854/56364573-8a806f00-61f7-11e9-9300-d2a74632bbfa.png)
![image](https://user-images.githubusercontent.com/49755854/56364603-9b30e500-61f7-11e9-8dbb-54f6aa86e429.png)
![image](https://user-images.githubusercontent.com/49755854/56364625-a71ca700-61f7-11e9-9556-9da77a52cec3.png)
![image](https://user-images.githubusercontent.com/49755854/56364636-ad128800-61f7-11e9-9aa1-d308598d1811.png)

**Comment by jiangdashao** [comment]
Please provide the verbose message
/matrix verbose

**Comment by artemati1** [comment]
![2019-04-18_17 29 19](https://user-images.githubusercontent.com/49755854/56368174-8fe1b780-61ff-11e9-88b0-df2c281ae210.png)
![2019-04-18_17 29 25](https://user-images.githubusercontent.com/49755854/56368175-907a4e00-61ff-11e9-88d0-aa7e758acaa4.png)
![2019-04-18_17 29 31](https://user-images.githubusercontent.com/49755854/56368176-907a4e00-61ff-11e9-9207-e94c7db27ce7.png)

**Comment by artemati1** [comment]
Assistent: Edyardo

**Comment by artemati1** [comment]
Well, can you fix it?

**Comment by jiangdashao** [comment]
How can I get a gender/RPG

**Comment by artemati1** [comment]
* grenade

**Comment by artemati1** [comment]
Well, can you fix it?

**Comment by jiangdashao** [comment]
I can't reproduce the false positive

**Comment by artemati1** [comment]
It's very simple.
Steps:
1. Download spigot 1.12.2
2. Download plugin: https://www.spigotmc.org/resources/crackshot-guns.48301/
3. Restart your server
4. Join server using 2 accounts
4. Use command "/shot get Grenade" or "shot get Bazooka" to get weapon

**Comment by artemati1** [comment]
It does not work with mobs. False positives occur on the attacker.

**Comment by artemati1** [comment]
How is it going?

**Comment by jiangdashao** [comment]
CrackShot's author didn't provide any useful API
I won't add that support
