### ISSUE TITLE
[REQUEST] MCMMO

### ISSUE THREAD

**Issue by Bisdakikobe** [jiangdashao/Matrix-Issues#257]
# What features/checks do you need?

I really hope you can add MCMMO support in future because its a really nice plugin :)

**Comment by jiangdashao** [comment]
It's useless to tell me to add the `xxx` plugin support
You should use that plugin, and tell me how they are not compatible with Matrix(provide video and verbose message)

**Comment by Bisdakikobe** [comment]
oh sorry about that then I will try to do it in the following days !
