### ISSUE TITLE
[FP] Speed Killaura Velocity while normal 1vs1

### ISSUE THREAD

**Issue by DieserFab** [jiangdashao/Matrix-Issues#260]
## Basic Information
**Verbose message(s)**: All inluded in the Video
**How/when does this happen**: Included in the Video
**Video of false positive**: https://www.youtube.com/watch?v=BJKhT-rYxJU&feature=youtu.be

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

# Server Infomation
**Server Version**: Spigot 1.8.8 R.01
**Matrix Version**: 1.9.0
**ProtocolLib Version**:4.4.0

**Comment by jiangdashao** [comment]
It's ok that there are some false flags. 
If you are getting setback or get kicked, then you can report it
But you are not in the video, you just get some false flags, and you haven't been teleport back or kicked.
