### ISSUE TITLE
[ERROR] Console error found on SpigotMC

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#268]
## Basic Information
**Error(s) found in console**: https://pastebin.com/raw/paB6MsrB
**How/when does this happen**: Unknown.
**Other information**: His SpigotMC username is AntoLuMeju99.

## Configuration Files
**Link to checks.yml file**: Unknown.
**Link to config.yml file**: Unknown.

# Server Infomation
**Server Version**: PaperSpigot "4c7641d" - MC Version 1.8.8
**Matrix Version**: 1.8.9
**ProtocolLib Version**: Unknown

**Comment by jiangdashao** [comment]
PlayerJoinEvent + NullPointerException = Outdated Config
Please delete the old config files
