### ISSUE TITLE
FP Killaura

### ISSUE THREAD

**Issue by Acenox** [jiangdashao/Matrix-Issues#27]
## How you trigger the false positive?
I just did a PvP moving my head.

## Verbose Message:
https://pastebin.com/ZumvvQkH

## Videos:
https://youtu.be/smfkw07t2nI

## Server Infomation
**Matrix Version**: 1.2.2 (latest)
**Server Version**: Spigot 1.8.8 (latest)
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Normal players don't swing their heads up and down like this, it's unimportant
