### ISSUE TITLE
[FP] A few errors regarding speed and fly

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#270]
## Basic Information If a player moves from a 9/10 height block to a 10/10 height block if says they are speed hacking and they get stuck. E.g If they run from a grass path block to a grass block
**Verbose message(s)**: Don't know as it says I dont have permission to view verbose messages even though I am OP
**How/when does this happen**: In the basic information
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:  Default config
**Link to config.yml file**: 

# Server Infomation
**Server Version**: 1.13.2
**Matrix Version**: Latest
**ProtocolLib Version**: Latest

2 More issues:
If a player flys with elytra (it could just be when players have high speed effects), it says they are flying and telelports them back to where they took off. All information same as above

And

A player with high speed effects cant run and jump without it saying its a speed or fly hack

**Comment by jiangdashao** [comment]
1. Please use our issue template format, don't edit it
2. Please provide enough video evidence

**Comment by jiangdashao** [comment]
3. Please provide the verbose message
