### ISSUE TITLE
[ERROR] [Matrix] Task #38 for Matrix v1.9.2 generated an exception

### ISSUE THREAD

**Issue by xAphex** [jiangdashao/Matrix-Issues#275]
## Before Reporting
- [x] Matrix is up-to-date
- [x] Matrix is running on a 1.8, 1.12, or 1.13 server
- [x] Config.yml and checks.yml have been reset to default

## Issue Information
**Error(s) found in console**:
`[Matrix] Task #38 for Matrix v1.9.2 generated an exception`
**How/when does this happen**:
when a player joins the server it spams this message.
**Other information**:
https://pastebin.com/r0Ubah5m

## Configuration Files
**Link to checks.yml file**:
https://pastebin.com/SGnbcE98
**Link to config.yml file**:
https://pastebin.com/NbS19xS8

# Server Infomation
**Server Version**: `Paper 1.13.2 #621`
**Matrix Version**: `1.9.2`
**ProtocolLib Version**: `4.4.0`

**Comment by ignPerformance** [comment]
The error shows that a class of ProtocolLib can't initialize correctly. Please try redownloading ProtocolLib. If any further troubleshooting issues fail, I'll reopen this on request.
