### ISSUE TITLE
[FP] Killaura Aimbot Check

### ISSUE THREAD

**Issue by DieserFab** [jiangdashao/Matrix-Issues#277]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, or 1.13 server
- [ ] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: Test Server 
**Verbose messages**: See Video
**How/when does this happen**: See Video
**Video of false positive**: https://www.youtube.com/watch?v=UINxXNATI0o&feature=youtu.be
**Other information**: ---

## Configuration Files
**Link to checks.yml file**: Test Server
**Link to config.yml file**: Test Server

**Comment by jiangdashao** [comment]
The test server's plugin is outdated
