### ISSUE TITLE
GUI Feature [REQUEST] 

### ISSUE THREAD

**Issue by freak-dk** [jiangdashao/Matrix-Issues#278]
Hoping you will consider adding the following, 

Currently I can't seem to operate the GUI in GM 3 which is fairly annoying. Not sure if intentional or bug, but I feel like you should be able to.

In AAC you were able to click the head of a player within the violation menu, to be teleported to said player and put in GM 3. I thought that was really usefull and I miss that feature.

Thanks for putting a lot of effort into the project, I am finding the AC to be very effective for combat checks :-)!

**Comment by jiangdashao** [comment]
Added
