### ISSUE TITLE
[INCOMPATIBILITY] Wilderness-TP

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#283]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: Spigot 1.13.2
**Incompatible plugin**: Wilderness-TP (https://www.spigotmc.org/resources/wilderness-tp.18431/)
**Verbose messages (or) console errors**: <name> failed Fly check / glide / strict / (-0.86 < -1.948) -> 1.088 / 15 (+2) / vl:18 ping:166 tps:19.54 
**How/when does this happen**: When players use /wild, the plugin teleports them about 6 blocks above the surface. This is where it glitches the player for flying
**Video of incompatibility**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/syeahsuf
**Link to config.yml file**: https://pastebin.com/qnmpQ2NB
⠀

**Comment by jiangdashao** [comment]
It's a chunk loading compatible issue
