### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by pabloalba16** [jiangdashao/Matrix-Issues#284]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, or 1.13 server
- [ ] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce
**Link to hacked client**: liquidbounce.net *Cheat that bypassed**: AutoClicker
**Video of bypass**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:⠀
**Link to config.yml file**:⠀

**Comment by ignPerformance** [comment]
Please use the proper format.
