### ISSUE TITLE
[REQUEST] Remove the Chat check

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#286]
**What features/checks do you need?:**
Remove the Chat check. It's useless and is annoying, and doesn't support as many features as fully-fledged chat plugins, like ChatControl. Most people have it disabled in the Metrics.

**Comment by jiangdashao** [comment]
Yes, it's useless, but I won't remove it

**Comment by ignPerformance** [comment]
Disable it in default config?

**Comment by jiangdashao** [comment]
Users can disable it by themself
