### ISSUE TITLE
🕑 [REQUEST] Improve the autoclicker checks

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#289]
**What features/checks do you need?:**
They need improvement. Please, please look into [these professionally coded autoclicker checks](https://github.com/SimonVoorman/Foxtrot/tree/master/src/main/java/me/ygore/anticheat/check/type/autoclicker) for guidance.

**Comment by jiangdashao** [comment]
AutoClicker check is enough now, I don't want to use any trick to detect some client's autoclicker
