### ISSUE TITLE
Fp Speed

### ISSUE THREAD

**Issue by Acenox** [jiangdashao/Matrix-Issues#29]
## How you trigger the false positive?
Just sprint and then turn very fast.

## Verbose Message:
https://pastebin.com/dJNCzQWw

## Videos:
https://youtu.be/_r9SEUpyybo

## Server Infomation
**Matrix Version**: 1.2.2 (latest)
**Server Version**: 1.8.8 (latest)
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Can't reproduce in vanilla client
