### ISSUE TITLE
[BYPASS] AutoClicker 

### ISSUE THREAD

**Issue by pabloalba16** [jiangdashao/Matrix-Issues#290]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, or 1.13 server
- [x] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce
**Link to hacked client**: www.liquidbounce.net
**Cheat that bypassed**: AutoClicker (default settings)
**Video of bypass**: I dont have a video but i have this picture: https://i.imgur.com/CwQi2ou.png/attachments/533032463296102403/570417727827869719/unknown.png
**Other information**: The autoclicker setting are between 9 and 12 cps and with verbose activated it doesnt say more than 1 vl normally.

## Configuration Files
**Link to checks.yml file**:⠀https://pastebin.com/aphswuJA
**Link to config.yml file**:⠀https://pastebin.com/y49mGYVN

**Comment by ignPerformance** [comment]
The auto-clicker detection will be improved in the next version (hopefully.) Not sure if this will fix your issue, but this is so minor and unimportant.
