### ISSUE TITLE
[REQUEST] API - PlayerViolationEvent Cancellation Compatibility

### ISSUE THREAD

**Issue by Delfofthebla** [jiangdashao/Matrix-Issues#298]
**What features/checks do you need?:**
Matrix does not appear to have full compatibility with event cancellation. If another plugin cancels the "PlayerViolationEvent", Matrix still affects the player.

For instance, if another plugin manually creates an "EntityDamageEvent" with DamageCause.ENTITY_ATTACK, matrix will cancel that event and throw a violation. If I cancel that violation however, the original EntityDamageEvent is still cancelled.

This makes it impossible to properly integrate with the Matrix plugin and write our own compatibility layer.

**Comment by jiangdashao** [comment]
You can use "MatrixAPI.setBypass(player,true);" before you create EntityDamageEvent
and then MatrixAPI.setBypass(player,false);

**Comment by Delfofthebla** [comment]
> 
> 
> You can use "MatrixAPI.setBypass(player,true);" before you create EntityDamageEvent
> and then MatrixAPI.setBypass(player,false);

Except if I do it this way I will have to queue up a runnable for the next tick, won't I? I suppose I have not tested this yet but I am assuming that the event has to completely resolve before Matrix is satisfied.

What's more is that I don't want to let them bypass cheats globally. If they are in the middle of speed hacking when they trigger one of these serverside attack events, I do not wish for that server action to suddenly "clear their plate" in terms of any logic matrix is executing against them.
