### ISSUE TITLE
Kill Aura False Positive

### ISSUE THREAD

**Issue by gc2023** [jiangdashao/Matrix-Issues#30]
## How you trigger the false positive?

Jump and spam attack a player.
## Verbose Message:
<! -- Provide the verbose message here -->
player is using kill aura (#1)
player failed KillAura check : attack out of sight ag=349.63384...
player failed KillAura check : hit too far away disatnce = 54.530586204...
player failed Interact check : attack entity through walls : vl:2 ping:0 tps:19.93
even though we were in open area
## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version*1.2.2*:
**Server Version*1.8.8*:
**ProtocolLib Version*Latest? 4.4.0 i think is latest*:

**Comment by jiangdashao** [comment]
Please provide a complete verbose message. You can find them in the log file and copy them.
