### ISSUE TITLE
[FP] Shooting Yourself with a Bow

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#302]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: Tree.ac
**Verbose messages**: https://i.imgur.com/IGxloOQ.png
**How/when does this happen**: Shooting yourself with a bow while running.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgpIPLBXUZLVZ6gzWUQ
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

**Comment by jiangdashao** [comment]
I won't fix it, it will cause BowFly hack
