### ISSUE TITLE
[BYPASS] 2 Block Spider

### ISSUE THREAD

**Issue by Crystalware** [jiangdashao/Matrix-Issues#306]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: tree.ac
**Hacked client**: Crystalware V2 (Winterware)
**Link to hacked client**: DM me on Discord @ WinterwareDev#2687
**Cheat that bypassed**: Spider (DEV Mode, Speed 0.01)
**Video of bypass**: https://1drv.ms/v/s!ApY4tKsF8vPUgpIXn60L0Zt0YxvEbg
**Other information**: 

## Configuration Files
**Link to checks.yml file**: tree.ac
**Link to config.yml file**: tree.ac

**Comment by Crystalware** [comment]
https://1drv.ms/v/s!ApY4tKsF8vPUgo073Aq8N-6UyaPHew Forgot to add the video

**Comment by jiangdashao** [comment]
Please provide client download link

**Comment by ignPerformance** [comment]
Message him on Discord for it @jiangdashao  WinterwareDev#2687
