### ISSUE TITLE
[FP] Velocity false positive

### ISSUE THREAD

**Issue by pabloalba16** [jiangdashao/Matrix-Issues#307]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [ ] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://pastebin.com/ErynfcgV
**How/when does this happen**: This happen when you are next to an enemie like a zombie (i didnt test with another player) you go straight on in the same direction, they hit you and it detects you Velocity until Matrix kicks you like in the screen.
**Video of false positive**: I have this picture i cant rec a video with my pc https://imgur.com/uYQtMsD
**Other information**: Im using minecraft 1.8.8 with optifine no hack client is used.         

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/n9XghhtA
**Link to config.yml file**: https://pastebin.com/hXtweYuh

**Comment by jiangdashao** [comment]
Please provide the video evidence

**Comment by ignPerformance** [comment]
Also test on default config.
