### ISSUE TITLE
[REQUEST] PlaceholderApi placeholders

### ISSUE THREAD

**Issue by True-cc** [jiangdashao/Matrix-Issues#309]
**What features/checks do you need?:**
I think you should add placeholders for placeholderapi for stuff like vl, or check type. idk, but I think that would be cool. I know there are already placeholders in checks.yml, but I think you should have placeholders for outside of checks.yml idk I think it would be cool

**Comment by jiangdashao** [comment]
It's enough to support PlaceholderAPI in checks.yml
