### ISSUE TITLE
Jesus False Positive

### ISSUE THREAD

**Issue by gc2023** [jiangdashao/Matrix-Issues#31]
## How you trigger the false positive?

Have one player go in water and keep head out of water and have another player use fishing pole on them.
## Verbose Message:
<! -- Provide the verbose message here -->
player was kicked for chesting
no verbose
## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version*1.2.2*:
**Server Version*1.8.8*:
**ProtocolLib Version*latest 4.4.0*:

**Comment by jiangdashao** [comment]
Please provide verbose message
