### ISSUE TITLE
[ERROR]  Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#310]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, or 1.13 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.14
**Error(s) found in console**: 
https://pastebin.com/5U8BVbtJ 
**How/when does this happen**: This seems to be happening when players are loading new chunks. This could maybe be an issue with 1.14 Spigot. Maybe Spigot is not optimized enough yet. 
**Other information**: 

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

**Comment by jiangdashao** [comment]
It's a Matrix Bug, not spigot, I will fix it in next update
