### ISSUE TITLE
Fp Killaura

### ISSUE THREAD

**Issue by Acenox** [jiangdashao/Matrix-Issues#32]
How you trigger the false positive?
Hello,
I reopen the ticket, because your answer is not appropriate, this kind of fight happens very EASILY during a PvP for for example a Faction, if it's enough to do that to be kick, then your detection of Killaura is completely broken. 
So no it's not "unimportant" and I would really like you to make a fix.
Verbose Message:
https://pastebin.com/ZumvvQkH

Videos:
https://youtu.be/smfkw07t2nI

Server Infomation
Matrix Version: 1.2.2 (not latest, because 1.3 has no improvement for killaura check)
Server Version: Spigot 1.8.8 (latest)
ProtocolLib Version: 4.4.0

**Comment by jiangdashao** [comment]
t: c(0) -> not false positive, please check your client and internet connection
t: b -> It's a important check for checking some type of KillAura, I won't remove it
