### ISSUE TITLE
[FP] Fly/Speed from Pistons

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#328]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [x] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version:** This server is running Paper version git-Paper-c66f02b1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages/errors:**
1) https://hastebin.com/hahitipago
2) https://hastebin.com/gacujohido
**Video:**
1) https://streamable.com/b1wot
2) https://streamable.com/iwz2e

## Configuration Files
**checks.yml**: default
**config.yml**: default

**Comment by jiangdashao** [comment]
Pistons are weird, I don't have any way to check it
