### ISSUE TITLE
[INCOMPATIBILITY] Vein Miner

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#329]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2 PaperSpigot
**Incompatible plugin**: Vein Miner
**Verbose messages (or) console errors**: Watch the video.
**How/when does this happen**: Hold shift when Vein Miner is toggled on and mine a chunk of ore. It will mine all of it instantly and kick you for cheating.
**Video of incompatibility**: https://1drv.ms/v/s!ApY4tKsF8vPUgpNBlQX15Z-mjluaJw
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
https://github.com/2008Choco/VeinMiner/tree/master/src/main/java/wtf/choco/veinminer/anticheat
You should tell the author to let him add compatibility
