### ISSUE TITLE
[REQUEST] Ideas from another anticheat

### ISSUE THREAD

**Issue by True-cc** [jiangdashao/Matrix-Issues#332]
**What features/checks do you need?:**
*cough cough*

I just copy and pasted this from another anticheat. The name of the anticheat is Spartan and it has some REALLY nice features/ideas, but the checks are pretty bad. 

**False Positive Detection** - The plugin will automatically identify most redundant false positives and prevent them for legitimate players.

**Better Chat Protection** - Block specific words, commands, and set chat cooldowns.

**MySQL Support** - Save structured logs into your SQL database and review them at any time.

**Punishment Waves** - Control and punish massive amounts of players in an instant.

**Staff Chat** - Secretly contact the staff team by starting your message with a certain character. (@)

**Dynamic Names** - Rename each check to the name you personally prefer.

**Conditional Commands** - Individually interact with the TPS, player latencies, and many more with a conditional command. [This is the plugin.](https://www.spigotmc.org/resources/conditionalcommands.14295/)

**Per World Checks** - Configure in which worlds a "certain" check will not run without doubts.

**Configuration Recommendations** - Get live in-game recommendations regarding your configuration. 

**Configuration Diagnostics** - Run the diagnostics via an inventory-menu, and in seconds, your false positives will be gone.

**Comment by ignPerformance** [comment]
Edited by me.
