### ISSUE TITLE
[INCOMPATIBILITY] FastFoodPlus

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#337]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Tree.ac
**Incompatible plugin**: FastFoodPlus
**Verbose messages (or) console errors**: Watch the video.
**How/when does this happen**: Spamming and eating food with a lot of health (the plugin acts like old food mechanics, so just give yourself a lot of health for this.)
**Video of incompatibility**: https://mega.nz/#!78UWQKaR!zmTzpEWqj95Bs0VvVNVrA0VjxJ10qGQvg68uduf4eAs
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Tree.ac
**Link to config.yml file**: Tree.ac

**Comment by jiangdashao** [comment]
Downloads < 3000
Reviews < 50
