### ISSUE TITLE
[INCOMPATIBILITY] KitBattle Advanced - Kangaroo Rocket

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#341]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Incompatible plugin**: KitBattle Advanced
**Verbose messages (or) console errors**: Watch the video. 
**How/when does this happen**: When a player uses KitBattle Advanced's kangaroo rocket.
**Video of incompatibility**: https://mega.nz/#!y8cGUaxI!GXPIldffFJkZ64GyY2BwhhG3xQJn9Lg9EgDqvKYkSGo
**Other information**: Join my server kitpvp.io to test this out.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Related to #338

**Comment by ignPerformance** [comment]
It isn't related, or it might be. Either way this isn't fixed or #338: https://mega.nz/#!fhd10QwZ!KU1_7mV-pY0ASzCH-sZMDnQORxDXqIs9hIhH1TugC_M

**Comment by ignPerformance** [comment]
https://mega.nz/#!H9tjBCSY!MQPIHRvKihfU6hahHwUb86_-XtCniR_ehfMrRe1f_1U
