### ISSUE TITLE
[FP] Boat on Ice

### ISSUE THREAD

**Issue by LegendsOfMedieval** [jiangdashao/Matrix-Issues#343]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14
**Verbose messages**: 
(12:18:03) My_English_Suck failed Speed check | entity speed | type: boat | tag: ice | distance: 1.6026352590364468 (+4) | vl:4 ping:173 tps:11.64
(12:18:03) My_English_Suck failed Fly check | flight | t:e | m=0.0 tk=12 et=5 vy=-0.0784000015258789 (+3) | vl:3 ping:173 tps:11.64
**How/when does this happen**: 
**Video of false positive**: https://youtu.be/_dHZQ3-pUzo
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Fixed
