### ISSUE TITLE
FP KillAura

### ISSUE THREAD

**Issue by KoTEHoChek** [jiangdashao/Matrix-Issues#35]
## Verbose Message:
<! -- https://youtu.be/1Zb_hAbOK1Y -->

## Videos:
<! -- https://youtu.be/1Zb_hAbOK1Y --> 

## Server Infomation
**Matrix Version**: 1.4.0
**Server Version**: 1.12.2
**ProtocolLib Version**: 4.4.0

**Comment by KoTEHoChek** [comment]
I'm downloading a video.

**Comment by KoTEHoChek** [comment]
That's all

**Comment by KoTEHoChek** [comment]
1.4.1 not fixing fp.

**Comment by jiangdashao** [comment]
I will release a hotfix for it
