### ISSUE TITLE
[REQUEST]  Expose "Anti Fall Damage" in checks.yml for fly 

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#350]
**What features/checks do you need?:** Would like "Anti Fall Damage" exposed in the checks.yml , would like something to prevent it from occurring, if the player has touched a water block recently, within X seconds.

Trying to prevent some odd , and very rare and hard to reproduce issue, where the player flies into water with elytra, goes under water, then comes out and touches land and dies instantly like "Player died."

![image](https://user-images.githubusercontent.com/21042824/57095524-fbc82380-6cc7-11e9-9cf1-f0573d505bfa.png)

**Comment by jiangdashao** [comment]
What？

**Comment by jiangdashao** [comment]
If it's a false positive, please report it

**Comment by Kruize1** [comment]
It's extremely hard to reproduce this or even see this in action.

I feel that having this option enabled might help prevent it. 

The screenshot isn't from the actual issue happening. 

I just want "Anti Fall Damage" to not trigger if the player has recently touched a water block.

I "think" this is what's happening. I'm not 100% sure.

If you can even just adjust the Anti Cheat to not trigger "Anti Fall Damage" if the player has touched a water block recently, then that's perfect! :)
