### ISSUE TITLE
[FP] Sweeping edge doesnt work

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#351]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: failed KillAura check / no swing (+1) / vl:688 ping:45 tps:19.96
**How/when does this happen**: Using a sweeping edge sword
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/wvA0tDFL
**Link to config.yml file**: https://pastebin.com/An6Jxq2k

**Comment by jiangdashao** [comment]
Do you using the latest version of Matrix?
