### ISSUE TITLE
[FP] Bad Packets flagging when standing still.

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#356]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://zak.pink/19-05-16-37-42_807.png / https://zak.pink/19-05-16-40-17_808.png
**How/when does this happen**: I was standing still doing nothing
**Video of false positive**: None, just screenshots.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Completely Original
**Link to config.yml file**: Completely Original

**Comment by ZakShearman** [comment]
Added the configs because why not: https://www.zak.pink/matrix/checks.yml / https://www.zak.pink/matrix/config.yml.

**Comment by ignPerformance** [comment]
Change `verbose_useless: true` to `verbose_useless: false`.
