### ISSUE TITLE
[FP] Velocity and Hitbox False Flags

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#357]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: When fighting the bot - I showed that I only have ESP enabled.
**Video of false positive**: https://zak.pink/matrix/issue-1.mp4 / Go to a bit after 00:40
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default - https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**: Default - https://www.zak.pink/matrix/config.yml

**Comment by ZakShearman** [comment]
I also am getting flagged for killaura. It's uploading at the moment and can be seen here when it is finished: https://www.zak.pink/matrix/issue-2.mp4

**Comment by artemati1** [comment]
This is normal. There are always small errors.

**Comment by ZakShearman** [comment]
So it's normal to get falsely kicked?

**Comment by BitesizedLion** [comment]
> This is normal. There are always small errors.

I personally would not call it normal, in an actual server, it is not good that players get falsely kicked for such thing and yes, nothing is perfect.

**Comment by BitesizedLion** [comment]
> So it's normal to get falsely kicked?

Unrelated to this but, did discord just die?
