### ISSUE TITLE
[REQUEST] Better Check GUI

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#363]
**What features/checks do you need?:** Make it so that you are able to enable/disable cancellation and command execution of different cheats through the GUI. Maybe make it as followed:
  - Left Click = Toggle the whole check on/off
  - Right Click = Toggle cheat cancellation on/off.
  - Shift + Right Click = Toggle command execution on/off.

**Comment by jiangdashao** [comment]
Check GUI is JUST designed for toggle checks temporary
