### ISSUE TITLE
[FP] Speed False Flag

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#364]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://zak.pink/19-05-19-32-36_820.png, https://zak.pink/19-05-19-32-49_821.png
**How/when does this happen**: This happens when you are being hit by a player and are running away. It thinks that you are going fast than you are able to.
**Video of false positive**: https://zak.pink/matrix/issue-5.mp4

## Configuration Files
**Link to checks.yml file:** https://www.zak.pink/matrix/checks.yml
**Link to config.yml file:** https://www.zak.pink/matrix/config.yml

**Comment by jiangdashao** [comment]
It looks like you have an abnormal knockback

**Comment by ZakShearman** [comment]
Re-testing with server knockback modification disabled.

**Comment by ZakShearman** [comment]
The issue still occurs:

https://www.zak.pink/matrix/issue-5-2.mp4

https://zak.pink/19-05-08-26-05_843.png
https://zak.pink/19-05-08-26-12_844.png
https://zak.pink/19-05-08-26-18_845.png
