### ISSUE TITLE
[FP] False positive with Flint and Steel (FastPlace/FastBreak hacks)

### ISSUE THREAD

**Issue by artemati1** [jiangdashao/Matrix-Issues#366]
## Troubleshooting Information

- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: spigot 1.8.8 
**Verbose messages**: video
**How/when does this happen**: when player use flint and steel 
**Video of false positive**: https://yadi.sk/i/rZuAdUEdPAg7ug
**Other information**: my nick is artemati

## Configuration Files
**checks.yml file**: default
**config.yml file**: default

**Comment by ZakShearman** [comment]
Yep, also getting this: https://www.zak.pink/matrix/issue-7.mp4
