### ISSUE TITLE
Fp Killaura

### ISSUE THREAD

**Issue by Acenox** [jiangdashao/Matrix-Issues#37]
## How you trigger the false positive?
Just PvP in a closed corner.

## Verbose message

https://pastebin.com/mYdNDiLp

## Videos:

https://youtu.be/L4riQPBKS28 

## Server Infomation : 
**Matrix Version:** 1.4.3 (latest)
**Server Version:** 1.8.8
**ProtocolLib Version:** 4.4.0

**Comment by jiangdashao** [comment]
This is unlikely to happen in real PVP

**Comment by AlikSondor** [comment]
In checks.yml, set the max_cps value to 15.1.
The problem will disappear.

**Comment by jiangdashao** [comment]
> In checks.yml, set the max_cps value to 15.1.
> The problem will disappear.

don't set double value, please use integer
