### ISSUE TITLE
[FP] Killaura/Interact False Positive

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#371]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: In Video 
**Video of false positive**: https://www.zak.pink/matrix/random-1.mp4

## Configuration Files
**Link to checks.yml file**: https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**:https://www.zak.pink/matrix/config.yml

**Comment by jiangdashao** [comment]
There are some false flags that are normal, and I will not fix the false positives caused by deliberate trigger detection.
