### ISSUE TITLE
[BYPASS/CHECK IMPROVEMENT] Timer manages to bypass for quite a while. 

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#372]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Vape
**Link to hacked client**: Vape.gg - Most will be the same.
**Cheat that bypassed**: Timer
**Video of bypass**: https://www.zak.pink/matrix/timer-1.mp4
**Other information**: 40 seconds to kick and 12 seconds to first notification.

## Configuration Files
**Link to checks.yml file**: https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**:https://www.zak.pink/matrix/config.yml

Note: The cheat does not fully bypass, but it is just that it is taking a long time for it to be detected.

**Comment by ZakShearman** [comment]
Could fix this by having a more specific check that is more sensitive or modifying the default config file so that it will alert staff/kick the player faster.

**Comment by jiangdashao** [comment]
Improve the TickRate check setback
