### ISSUE TITLE
[FP] Phase - Breaking Block False Flag

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#373]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: When you break a block below you, in front of you and walk into it, etc. you false flag.
**Video of false positive**: https://www.zak.pink/matrix/phase-1.mp4, https://www.zak.pink/matrix/phase-2.mp4

## Configuration Files
**Link to checks.yml file**: https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**: https://www.zak.pink/matrix/config.yml

**Comment by jiangdashao** [comment]
It looks like a block protection plugin imcompatibility

**Comment by ZakShearman** [comment]
It's simply just cancelling when a block is broken, what can I do about that?
