### ISSUE TITLE
[FP] Run on slabs with speed potion 2 

### ISSUE THREAD

**Issue by variationtime** [jiangdashao/Matrix-Issues#374]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper 1.12.2
**Video of false positive**: https://media.discordapp.net/attachments/574628734640848897/574630162835046435/unknown.png

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**: default

**Comment by ZakShearman** [comment]
Video?

**Comment by variationtime** [comment]
same as here
https://github.com/jiangdashao/Matrix-Issues/issues/342

**Comment by jiangdashao** [comment]
I can't reproduce
