### ISSUE TITLE
[FP] [1.9.7] Bad Packets check | tick rate

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#377]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper 1.13.2
**Verbose messages**:  Bad Packets check | tick rate
**How/when does this happen**:  Some legitimate players will randomly trigger this while they play. Their ping is around 100 , which isn't that bad. When they start to experience this, they then trigger other false flags for fly, and speed, etc. 
**Video of false positive**:  No video, but here is a screenshot 
![image](https://user-images.githubusercontent.com/21042824/57201759-347b2d80-6f52-11e9-87b2-1d33e9196c59.png)

**Other information**: 

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
He may be using the Timer hack. lol

**Comment by Kruize1** [comment]
He's not though. He's a legit vanilla player

**Comment by jiangdashao** [comment]
set tickrate.cache_size higher
