### ISSUE TITLE
Swimming + Depth Strider 3 + Dolphin's grace and Boat + ice/blue-ice/packed-ice false positive

### ISSUE THREAD

**Issue by k9lego** [jiangdashao/Matrix-Issues#381]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [ 1.14] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ n/a] I've tested if the issue happens on default config

## Issue Information
Dolphin's grace + Depth strider 3 swimming false positive
Boat on ice/blue-ice/packed-ice, make a long path and go really fast. False positive there.

Would include a video but these are easy to describe. I have some more false positives I know of, but I want to document them properly. Thanks!! :)
## Configuration Files
Default

**Comment by jiangdashao** [comment]
Please provide the verbose message
