### ISSUE TITLE
Anti cheat

### ISSUE THREAD

**Issue by Naskosa** [jiangdashao/Matrix-Issues#394]
Good day!
You do not tell me how to put one plugin in the list of exceptions in the Anti-cheat Matrix?
I have a plugin on the server that interacts with the flight and so on.
I want this plug-in to be on the "list of exceptions" of this anti-cheat.
(Antichit fine)

**Comment by jiangdashao** [comment]
If you are a developer, you can listen to the "PlayerViolationEvent" and cancel it
