### ISSUE TITLE
[REQUEST] %id%

### ISSUE THREAD

**Issue by k9lego** [jiangdashao/Matrix-Issues#395]
Quick request for Matrix. I'm planning on using Matrix to trigger replay recordings, so here are two features I wouldn't mind seeing someday in the future:
Either official support for triggering recordings of players who are suspected to be cheating.
Or
A %id% to generate a unique number or name. This would be useful for the replay file, maybe other stuff as well. Also a way to execute a command 30 seconds after a check has been triggered might be useful for delaying bans, etc:
`50: 'matrix notify %player% is using fly hacks' 
30 seconds: 'matrix ban %player% fly hacks'` Obviously not actual yaml but I think you get the idea.
If you don't plan on adding either of the two, I can find a way to make this work. It'd just be cool to have this functionality built into Matrix :)
https://www.spigotmc.org/resources/advancedreplay-1-9-1-13.52849/

**Comment by jiangdashao** [comment]
I will add %id% placeholder
