### ISSUE TITLE
Bypasses

### ISSUE THREAD

**Issue by CraftG** [jiangdashao/Matrix-Issues#4]
### Core information
** Matrix Version **: 1.0.4
** Server Version **: 1.8.8
** ProtocolLib Version **: 4.4.0-b424
** Plugin List: **: Matrix, ProtocolLib

### Other infomation
** ViaVersion Version: ** no
** ProtocolSupport Version: ** no
**BungeeCord plugins**: no

1.LiquidBounce WallClimb-Clip
2.LiquidBounce Step-Rewinside

Fix pls :)

**Comment by jiangdashao** [comment]
It will be fixed in next update
