### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by AlikSondor** [jiangdashao/Matrix-Issues#40]
## Bypass Infomation
**Hack Client**:
Flux b13
**Bypassed Hacking Type**:
Jesus in solid mode - partly (Detects with delayed and only in reservoirs with a depth of 4 blocks.
Warnings does not, just blocks.)
FastPlace.
Speed in slowhop, slowhop2 and aacslowhop modes.
Velocity.
No slow.
ChestCtealer.
BetterSword.
AutoArmor.
**Matrix Version**:
1.5.1
**Server Version**:
Spigot 1.12.2
## Videos
https://youtu.be/soyYUTwdbQg

**Comment by jiangdashao** [comment]
Speed: after testing, no bypass
NoSlow: no bypass
BetterSword: It's a render hack, it's undetectable
AutoArmor/InvCleaner: There is no such check, and i won't add it too

**Comment by AlikSondor** [comment]
What about Jesus, FastPlace, Velocity and ChestCtealer?
+ AutoArmor - InventoryHack.
Speed: bypasses on my server
checks.yml: https://pastebin.com/xWa3jyAm
Hack client: https://yadi.sk/d/oGfhdXHuj43ccA

**Comment by jiangdashao** [comment]
Please remove the OP permission

**Comment by AlikSondor** [comment]
In the video, I showed that there is no op prescribing / gm 1

**Comment by AlikSondor** [comment]
Op disabled, killaura blocks

**Comment by AlikSondor** [comment]
Op disabled.
The confirmation: https://youtu.be/RCK6MulaIWk

**Comment by jiangdashao** [comment]
You need to rejoin server to refresh permission cache

**Comment by AlikSondor** [comment]
At the end of the video use NCPHope, which was discovered
