### ISSUE TITLE
FLY [BYPASS] 

### ISSUE THREAD

**Issue by TheSkiddy** [jiangdashao/Matrix-Issues#401]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**1.8.8**: 
**LiquidBounceB62**: 
**LiquidBounce.net**: 
**FLY Rewinside**: 
**https://youtu.be/qTcGzuylY0U**: 
**Other information**: 

## Configuration Files
**DEFAULT**: 
**DEFAULT**:

**Comment by jiangdashao** [comment]
See you VL
3000+
