### ISSUE TITLE
[FP] Jump + Water Bubbles = Setback

### ISSUE THREAD

**Issue by NyannyWu** [jiangdashao/Matrix-Issues#402]
## Basic Information
**Verbose message(s)**:  https://hastebin.com/raw/fovojahowi
**How/when does this happen**:  Jump from somewhere high and land on water bubbles

## Configuration Files
**Link to checks.yml file**:  https://hastebin.com/raw/okufizecoh
**Link to config.yml file**:  https://hastebin.com/raw/rumivuruki

# Server Infomation
**Server Version**:  1.13.2
**Matrix Version**:  1.9.9
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Please provide video evidence

**Comment by NyannyWu** [comment]
https://streamable.com/2v9j6
