### ISSUE TITLE
[FP]  ping players out of the server

### ISSUE THREAD

**Issue by CraftElis** [jiangdashao/Matrix-Issues#408]
## Issue Information
**Server version**: spigot 1.8.8

## Configuration Files
**Link to checks.yml file**: 
https://hastebin.com/furugahuxe.coffeescript
**Link to config.yml file**:
https://hastebin.com/sutuqipere.shell

**Comment by ZakShearman** [comment]
So what's the actual issue? You have provided no information here.

Please could you add:
  - Description of the issue or false positive.
  - Video of the issue or false positive.

**Comment by CraftElis** [comment]
i am turkish. this is doing google translate i don't know how well it does. 
my problem is
players raw materials they dig time not even cheating ping beats from the server

**Comment by jiangdashao** [comment]
Please provide the verbose message when they get kicked
