### ISSUE TITLE
Error Spam In Console Plus Kicks!

### ISSUE THREAD

**Issue by Zacky26** [jiangdashao/Matrix-Issues#41]
## Console Error
https://pastebin.com/cgfYtxCk

## When the error happens?
When player moves. It will lag a little (Matrix's fault) and kick the player.

# Server Infomation
1.13
Latest Matrix
Latest ProtocolLib
Yes I'm using the newest config

**Comment by jiangdashao** [comment]
Please use official spigot (1.13_R2)

**Comment by Zacky26** [comment]
I am using that version

**Comment by Zacky26** [comment]
```
> [10:27:30 INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
> [10:27:30 INFO]: Checking version, please wait...
> [10:27:30 INFO]: You are 273 version(s) behind
```

**Comment by jiangdashao** [comment]
Please use paper or spigot, don't use Bukkit

**Comment by Zacky26** [comment]
That is spigot though.

**Comment by jiangdashao** [comment]
redownload spigot: https://getbukkit.org/
or download paper: https://papermc.io/downloads

It was not Matrix's problem

**Comment by Zacky26** [comment]
Hey for the last time I am using the latest 1.13 build and yes I redownloaded the jar file

**Comment by jiangdashao** [comment]
This is definitely a problem with your server jar, which lacks an API

**Comment by Zacky26** [comment]
Well can you send me a 1.13 version of paper thanks :3

**Comment by jiangdashao** [comment]
https://drive.google.com/file/d/12ZAtS-F-JttA5DZDrIrwcSSmuXi_9lKk/view?usp=sharing
