### ISSUE TITLE
[1.10.3 / MC 1.14.1] Matrix kicks for fastheal if regenerating health when the server is lagging [FP] 

### ISSUE THREAD

**Issue by RalphORama** [jiangdashao/Matrix-Issues#411]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: `Paper version git-Paper-26 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)`
**Verbose messages**: `[Matrix] RalphORama failed FastHeal check regen health too fast I b=133 c=14 d=SATIATED (+2) | vl:2 ping:43 tps:4.89`
**How/when does this happen**: If a player is regenerating health/eating when the server lags.
**Video of false positive**:  https://www.youtube.com/watch?v=aTlD5ZYQsa4
**Other information**: Might be related to #174 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/THgeAgZv
**Link to config.yml file**: https://pastebin.com/k9qAacQV

**Comment by jiangdashao** [comment]
You can disable FastHeal check if you think it's buggy.
And BadPackets check can detect it, including FastUse/FastBow/FastHeal
