### ISSUE TITLE
Bypass on the server without plugins.

### ISSUE THREAD

**Issue by AlikSondor** [jiangdashao/Matrix-Issues#42]
## Bypass Infomation
Test without plugins.
Only Matrix, ViaVersion, ViaRewind, ViaBackwards are installed.
**Hack Client**:
Flux b13 1.8.8
**Bypassed Hacking Type**:

**Speed:** SlowHop2 mode, AACSlowHop mode.

**ChestStealer**

**Spider** (Two blocks, with damage)

**Jesus** (In shallow reservoirs)

**FastPlace** (Partly)

**Velocity.**

**Matrix Version**:
1.5.1
**Server Version**:
1.12.2
## Videos
https://youtu.be/TRYsIfJgFu8

**Comment by jiangdashao** [comment]
FastPlace: the legit player can do this by jitter click, so it's not bypass
Spider: unimportant
ChestStealer: not bypass, chest stealer only check player click different items, it won't detect you click same type items fast
Speed: yes, it's a bypass
Jesus/Velocity: unimportant

**Comment by jiangdashao** [comment]
After the speed test, These speed types are slower than normal player, so it's not bypass

**Comment by AlikSondor** [comment]
Antiknowback it is unimportant?

**Comment by jiangdashao** [comment]
I think so

**Comment by AlikSondor** [comment]
> Jesus/Velocity: unimportant
> Spider: unimportant

![image](https://user-images.githubusercontent.com/48272470/54520562-b4563400-49b4-11e9-8c59-09355c41df98.png)

**Comment by AlikSondor** [comment]
> FastPlace: the legit player can do this by jitter click, so it's not bypass

What then is protection against FastPlace?

**Comment by jiangdashao** [comment]
place per second
