### ISSUE TITLE
[FP] Jesus When Going Down Water

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#421]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Spigot
**Verbose messages**: https://zak.pink/19-05-17-30-49_969.png or in video.
**How/when does this happen**: When going down water - not holding space.
**Video of false positive**: https://zak.pink/matrix/jesus-1.mp4
**Other information**: Feel free to test at ac.zakshearman.com

## Configuration Files
**Link to checks.yml file**: https://zak.pink/matrix/checks.yml
**Link to config.yml file**: https://zak.pink/matrix/config.yml

**Comment by jiangdashao** [comment]
You create unnatural liquid blocks, which don't happen in games.

**Comment by ZakShearman** [comment]
https://zak.pink/matrix/jesus-2.mp4

Can replicate with normal blocks as well.

**Comment by ZakShearman** [comment]
Can you re open this or fix it?
