### ISSUE TITLE
posY bypass

### ISSUE THREAD

**Issue by akuankka128** [jiangdashao/Matrix-Issues#422]
**Server version: Spigot 1.8.8
Matrix version: not provided**

Works as of 20/05/2019

By setting the player position (_client-side_ (using mc.thePlayer.setPosition() )) to a high value (currently tested only with 2147483647, every tick), the anticheat doesn't flag you.

**Comment by jiangdashao** [comment]
1. Please use our issue template
2. Please provide video evidence
3. It may be client-side, please provide evidence that it can be seen on the server side
