### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#426]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Impact 4.6
**Cheat that bypassed**: Step (NCP)
**Video of bypass**: https://www.zak.pink/matrix/step-bypass-1.mp4
**Other information**: ac.zakshearman.com

## Configuration Files
**Link to checks.yml file**: https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**: https://www.zak.pink/matrix/config.yml

**Comment by jiangdashao** [comment]
It's a timer step, it can be flagged
