### ISSUE TITLE
[FP] Velocity

### ISSUE THREAD

**Issue by variationtime** [jiangdashao/Matrix-Issues#433]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8 spigot
**Video of false positive**: https://streamable.com/5wcg8
**Other information**: 

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I think it won't cause false kick in real game, if yes, I will reopen it

**Comment by variationtime** [comment]
It will cause, I have punishment on my own server as 12 VL. In video i already have 13

**Comment by yorik100** [comment]
It does false kick

**Comment by jiangdashao** [comment]
I mean, you deliberately triggered this detection, normal players don't walk like this.

**Comment by variationtime** [comment]
yea, dont walk, buy most of the players use 180% turn and get 1-3 vl from it
