### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Mejos** [jiangdashao/Matrix-Issues#434]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.1
**Verbose messages**: Player was kicked for floating too long!
**How/when does this happen**: Sleeping in a floating Bed
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Please could you provide the verbose messages so we know what check is causing this.
