### ISSUE TITLE
[ERROR] in console and fly related issues

### ISSUE THREAD

**Issue by grzegorz2047** [jiangdashao/Matrix-Issues#435]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
This server is running CraftBukkit version git-Spigot-03bd4b0-c45c0a9 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
**Error(s) found in console**: 
https://pastebin.com/aaT3P1fs
https://pastebin.com/2sAMeHRm
**How/when does this happen**: 
Hard to say
**Other information**: 
I have also fly related issues when players jump off high places like 240 y coordinate that's why I had to increase fly checks levels and  spigot.yml value moved-too-quickly-multiplier: 16.0

## Configuration Files
**Link to checks.yml file**: 
https://pastebin.com/GWpr5ZbV
**Link to config.yml file**:
https://pastebin.com/8Bx7nGAF

**Comment by ZakShearman** [comment]
Can you try this with the default configuration.

**Comment by grzegorz2047** [comment]
If error shows up again Ill switch to default config and reopen this issue
