### ISSUE TITLE
[INCOMPATIBILITY] Essentials /afk

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#439]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Incompatible plugin**: EssentialsX 
**Verbose messages (or) console errors**: In Video
**How/when does this happen**: Type /afk and move
**Video of incompatibility**: https://www.zak.pink/matrix/essentials-incompatibility.mp4
**Other information**: ac.zakshearman.com

## Configuration Files
**Link to checks.yml file**: https://www.zak.pink/matrix/checks.yml
**Link to config.yml file**:https://www.zak.pink/matrix/config.yml

**Comment by ZakShearman** [comment]
If you want to reproduce, come on ac.zakshearman.com, type /afk and you're good to go. Just tested and it still happens.

**Comment by jiangdashao** [comment]
Are you using EssentialsX? or other AFK plugin?

**Comment by ZakShearman** [comment]
EssentialsX

Just checked and this also happens with 1.8.9.
