### ISSUE TITLE
[ERROR] [Console Spam] Matrix v1.10.6 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#443]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.14.2 Paper (with ProtocolLib 4.5.0)
**Error(s) found in console**:  https://pastebin.com/xHs2kxbs
**How/when does this happen**:  Seems to happen when bad packets check triggers and kicks the player.
**Other information**:  1.14.2 is new. The Paper version was just released recently.

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:   default

**Comment by jiangdashao** [comment]
weird
