### ISSUE TITLE
[FP]  Speed check makes inventory items to change automatically.

### ISSUE THREAD

**Issue by NyannyWu** [jiangdashao/Matrix-Issues#447]
## Basic Information
**Verbose message(s)**:  https://hastebin.com/raw/ijurexisiy
**How/when does this happen**:  Walk in circles pressing left and forward and with mouse to the other direction
**Video of false positive**:  https://streamable.com/cmbbs

## Configuration Files
**Link to checks.yml file**:  https://hastebin.com/raw/okufizecoh
**Link to config.yml file**:  https://hastebin.com/raw/rumivuruki

# Server Infomation
**Server Version**:  1.13.2
**Matrix Version**:  1.10.7
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
