### ISSUE TITLE
Fly and speed

### ISSUE THREAD

**Issue by JakubEG0** [jiangdashao/Matrix-Issues#45]
After the last update it does not block flying and speed (1.13.2)
ver. 1.5.4

**Comment by jiangdashao** [comment]
plugin list

**Comment by JakubEG0** [comment]
ActionBarAPI, AdvancedBan*, AntiAFKPro*, AntiCurse, antiRedstoneClock, AuthMe, ChangeSkin, ChatControl, ChatReaction*, ChestCommands, ChestShop, CombatLogX, ConsoleSpamFix, CustomEnderChest, DeathSpectating, EditableSign*, Emoji*, EnderPearlWorld*, Essentials, EssentialsChat, EssentialsExtras*, EssentialsSpawn, GraviTree, HealthBar, HolographicDisplays, IllegalStack, ItemJoin, KarenProtect*, KenerlRTP, LagAssist, Matrix, MobFarmManager, Multiverse-Core, MyCommand, NametagEdit*, NoChorus*, NoFireworkDamage*, NoPlugins, NoSpawnerChange, NoUnicode*, PermissionsEx*, PlaceholderAPI, PlugMan, ProtocolLib*, RFChairs, ServerlistMOTD*, SimpleCommandBlocker*, TimeIsMoney*, TitleManager*, TradePlus, TreasureChestReloaded, Vault, Voting*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, ZavMessage*

**Comment by jiangdashao** [comment]
Fixed

**Comment by JakubEG0** [comment]
Hey, go on the same!

**Comment by JakubEG0** [comment]
I had to restart 2 times .. strange
