### ISSUE TITLE
[ERROR] Console Error

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#451]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [Unsure ] The issue happens on default config.yml and checks.yml
- [Unsure ] I've tested if the issue happens on default config

It happens randomly, so I can't easily reproduce it with default settings or not. 

## Issue Information
**Server version**: 1.13.2
**Error(s) found in console**: https://pastebin.com/UNmNUut1
**How/when does this happen**: Unknown
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/ZdigtFD6
**Link to config.yml file**: https://pastebin.com/uygntezH

**Comment by jiangdashao** [comment]
Fixed
