### ISSUE TITLE
[FP] Low TPS causes False Positives and eventual kicks

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#454]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.2 Paper 
**Verbose messages**:  Many verbose messages . Kill Aura, Speed, Jesus, etc. 
**How/when does this happen**:  When the server TPS gets low Matrix begins to cause False Positives. This occurs even when the TPS prevention in the Config is set to 19.
**Video of false positive**:  https://clips.twitch.tv/ThankfulSmokyAirGuitarAMPEnergy
**Other information**:  In the video you can clearly see the TPS going super low, and you can also see the Verbose Messages reporting 10 TPS. With the TPS protection setting in place, it's expected that verbose messages should be disabled.

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default (although setting TPS protection to 19 still resulted in false flags.

**Comment by jiangdashao** [comment]
Why not try to resolve the lag issue?

**Comment by Kruize1** [comment]
Because you offer TPS protection in the config file. We kind of expect it to work.

**Comment by jiangdashao** [comment]
The TPS protection disable some useless checks when TPS is low

**Comment by Kruize1** [comment]
# Server Lag Protection
# Description: Automatically disables some checks when your
# server is lagging. This prevents most, but not all, false
# positives from occuring.
tps_protection:
  # Enable this feature?
  enable: true

  # Minimum TPS needed to trigger protection
  min_tps: 19.0

**Comment by Kruize1** [comment]
Can you make it disable all?
