### ISSUE TITLE
[ERROR] Could not pass event BlockBreakEvent to Matrix v1.10.9

### ISSUE THREAD

**Issue by maxlehot1234** [jiangdashao/Matrix-Issues#457]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [] The issue happens on default config.yml and checks.yml
- [] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2 Paperspigot build 626
**Error(s) found in console**:  https://gist.github.com/maxlehot1234/bd588ab83cd23c76c9c78dd2e46223f6
**How/when does this happen**: Seems to occured when someone break a block.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://gist.github.com/maxlehot1234/9dce4081b5bf0567f4e801d6f618d495
**Link to config.yml file**: https://gist.github.com/maxlehot1234/8a3e797295b586c5a469d3bbd8a37576

**Comment by jiangdashao** [comment]
Break what block?and where?
