### ISSUE TITLE
Velocity false positive

### ISSUE THREAD

**Issue by CrazyWords1** [jiangdashao/Matrix-Issues#46]
## How you trigger the false positive?
I'm running to player, this player shoot me, and i'm not stop running 

## Verbose Message:
Matrix kick me (reason >> AKB)

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version**: 1.5.1
**Server Version**: 1.12.2
**ProtocolLib Version**: 4.29-dev

**Comment by jiangdashao** [comment]
Velocity check will be recoded in next version
