### ISSUE TITLE
[FP] A list of false-positives

### ISSUE THREAD

**Issue by AutismGaming228** [jiangdashao/Matrix-Issues#461]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.2
**Verbose messages**: https://pastebin.com/M3pB7Dfr
**How/when does this happen**: There are 3 issues:
- Flagged for Speed while eating a chorus fruit or bread when sprint jumping, it switches your inventory slot to a random one
- Flagged when spamming sprint and jump to boost with an elytra
- Flagged when you swim and sprint on a boat

**Video of false positive**: https://youtu.be/UjiPOzV8MUs 1st - 0:00 2nd - 0:37 3rd - 1:11
**Other information**: Will send more issues from my friends if I'll confirm that they exist.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/YbfzZQw7
**Link to config.yml file**: https://pastebin.com/mD884C3B

*Edited by Performance.*

**Comment by jiangdashao** [comment]
I can't play the video

**Comment by ignPerformance** [comment]
The video is unavailable.

**Comment by AutismGaming228** [comment]
Whoops, should be working now
