### ISSUE TITLE
[FP] Grenade(TNT) explosion

### ISSUE THREAD

**Issue by sumsar1812** [jiangdashao/Matrix-Issues#463]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper spigot 1.8
**Verbose messages**: 
**How/when does this happen**: When using the plugin crackshot with grenades(it spawns invisible TNT as far as i know) our players sometimes gets kicked for using killaura/reach cause it is hitting people behind walls, multiple people at the same time or from a long distance.
**Video of false positive**: https://youtu.be/YQCK455Lx1w?t=118 and https://www.youtube.com/watch?v=zGUqoIcDXwo
**Other information**: 

## Configuration Files
https://pastebin.com/i0VA78ba
https://pastebin.com/TcUxHcKe

**Comment by jiangdashao** [comment]
It does not support CrackShot
