### ISSUE TITLE
[ERROR] Won't start with new Paper update

### ISSUE THREAD

**Issue by x04** [jiangdashao/Matrix-Issues#464]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-83
**Error(s) found in console**: https://hasteb.in/zujowoco.md
**How/when does this happen**: Upon updating from 82 to 83
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Don't use PlugMan to load the plugin
