### ISSUE TITLE
[ERROR] GUI not opening

### ISSUE THREAD

**Issue by PurpleCOCK** [jiangdashao/Matrix-Issues#466]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Error(s) found in console**: none
**How/when does this happen**: Always
**Other information**: Opens but doesn't change sections when I click on one

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Please complete the form properly.

Add your check and config file, give the error you are having, fill out the sufficient check boxes.
