### ISSUE TITLE
[FP] Jump Boosting with Slime Block triggers false fly

### ISSUE THREAD

**Issue by NoManaSendHelp** [jiangdashao/Matrix-Issues#472]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.2 Paper 94
**Verbose messages**: https://gyazo.com/f19c2293dee1a6a4dbd036ef1d68cf30
**How/when does this happen**:  When a player uses a slime block and piston to boost them up to their 2nd floor, it triggers that message and sends them back down to the ground, as if they flew.
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/MmbsgAEG
**Link to config.yml file**: https://pastebin.com/JSPhi6tv

**Comment by jiangdashao** [comment]
Please provide the video

**Comment by NoManaSendHelp** [comment]
https://www.youtube.com/watch?v=EuyrFRBx3HA&feature=youtu.be

Screenshots of the verbose:
(First message that showed up with the elytra)
https://gyazo.com/72e7abc4ced3ba648113b84af06463ad

(Second message that showed up without elytra)
https://gyazo.com/c0ad01898a7dc561887d30e0f0861628

**Comment by jiangdashao** [comment]
It was caused by Piston
