### ISSUE TITLE
[FP] players with /fly are kicked for "Jesus" when flying above water

### ISSUE THREAD

**Issue by rmellis** [jiangdashao/Matrix-Issues#476]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Paper**: git-paper-626 (MC: 1.13.2)
**Verbose messages**: Tried to move illegally in liquid (Jesus)
**How/when does this happen**: most of the time when players fly low above water
**Video of false positive**: n/a
**Other information**: n/a

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/efbkg5h8
**Link to config.yml file**:  https://pastebin.com/bHGa8D0D

**Comment by jiangdashao** [comment]
Can you provide a video of it?
I can't reproduce it
