### ISSUE TITLE
[FP] "failed Interact" when a sign is close to the line of sight

### ISSUE THREAD

**Issue by marcbal** [jiangdashao/Matrix-Issues#478]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: `This server is running CraftBukkit version git-Spigot-5340a52-27b8bf9 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`
**Verbose messages**: `failed Interact check | interact block through walls ,o=WALL_SIGN b=CHEST (+1) | vl:15 ping:27 tps:20.0 component: interact.through`
**How/when does this happen**: When the player try to open a chest or break block, when a wall sign is close to the line of sight of the player
**Video of false positive**: https://www.youtube.com/watch?v=LfqxgzoMXcE
**Other information**: Since we use a plugin to protect chests with signs, this false positive occurs frequently and annoy the players.

## Configuration Files
**Link to checks.yml file**: default one
**Link to config.yml file**: default one

**Comment by jiangdashao** [comment]
I can't reproduce it

**Comment by marcbal** [comment]
Well, I wanted to try to disable some plugin to see if there is some conflict, but it seams that I can’t reproduce the bug again, even with the same conditions as in my video.

If the bug occurs again and if I have new infos, I will send a message here.
