### ISSUE TITLE
Guardian

### ISSUE THREAD

**Issue by JakubEG0** [jiangdashao/Matrix-Issues#48]
## How you trigger the false positive?
When he fights with Guardian, he often throws the AntiKnockback off the server.

## Verbose Message:
<! -- Provide the verbose message here -->

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version**: 1.5.4
**Server Version**: 1.13.2
**ProtocolLib Version**: newest

**Comment by jiangdashao** [comment]
Related #46

**Comment by JakubEG0** [comment]
And so it is much better than with WatchCat (there were more and more errors from version to version)
