### ISSUE TITLE
[REQUEST] Add check using Vanilla Generic Attributes

### ISSUE THREAD

**Issue by Spookit** [jiangdashao/Matrix-Issues#481]
**What features/checks do you need?:**
I installed 1 plugin (custom coded plugin), that modify player attributes, but unfortunately matrix seems doesnt support it. After player upgraded their Movement Speed Skill (generic.movementSpeed attribute), when they walk, they got pushed back/teleported back like when they lag. This issue was missunderstood by my players as server lag, but its not happened when i disable Matrix checks. The plugin also modify other vanilla attributes.

**Comment by ZakShearman** [comment]
Should be labelled and submitted as an incompatibility: Could you provide a tiny bit of verbose messages that it triggers just to make any fixing a little bit faster.

**Comment by Spookit** [comment]
Septogeddon failed Speed check | faster than expected | t-a | 0.348 > 0.2873 | val: true (+3) | vl: 30 ping:328 tps:20.0 component: speed.main
