### ISSUE TITLE
Penalize when interacting with an NPC (HitBox) [FP] 

### ISSUE THREAD

**Issue by GabrielHD150** [jiangdashao/Matrix-Issues#482]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.8.8
**Verbose messages**: https://pastebin.com/skhF2niK
**How/when does this happen**: This happens when interacting with an NPC
**Video of false positive**: 
**Other information**: Server SkyWars

## Configuration Files
Checks.yml: https://pastebin.com/k8mFVKrV
config.yml: https://pastebin.com/zdmx8Bwe

**Comment by ZakShearman** [comment]
Please fill the false positive report out correctly.

Add:
  - Verbose Messages
  - Video of the false positive
  - Make sure that Matrix and ProtocolLib are up to date.

**Comment by jiangdashao** [comment]
Please provide the video evidence
