### ISSUE TITLE
[FP] swimming on boat and walking/jumping on boat

### ISSUE THREAD

**Issue by grzegorz2047** [jiangdashao/Matrix-Issues#485]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  git-Spigot-df0eb25-da071ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
**Verbose messages**: 
**How/when does this happen**: on boat
**Video of false positive**:  https://youtu.be/WsCd3SmA8wk
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**:  default

**Comment by jiangdashao** [comment]
Please provide the verbose message
