### ISSUE TITLE
[FP] New FastPlace Check

### ISSUE THREAD

**Issue by henrik9999** [jiangdashao/Matrix-Issues#486]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**1.14.2 Paper-105**: 
**Blocks placed fast (still happens but no so often anymore)**:

**Comment by NoManaSendHelp** [comment]
I'm also still recieving this after updating to the hotfix, running paper 105 on mc1.14.2

https://gyazo.com/def7bc894bcd29eca05e3d2556394edd

**Comment by jiangdashao** [comment]
set vl weight to 1
