### ISSUE TITLE
[FP] Hitboxes/Reach

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#488]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Paper Spigot
**Verbose messages**: https://zak.pink/19-06-22-36-59_1178.png & https://zak.pink/19-06-22-37-05_1179.png & https://zak.pink/19-06-22-37-15_1180.png
**How/when does this happen**: PvP.
**Video of false positive**: www.zak.pink/matrix/reach-1.mp4
**Other information**: Happy to provide anything within reason.

## Configuration Files
**Link to checks.yml file**: Default - Just uploaded
**Link to config.yml file**: Default - Just uploaded

**Comment by ZakShearman** [comment]
To be clear, I know I leaked my IP and IDC.

**Comment by jiangdashao** [comment]
This is combo fly mode?
no hit delay?

**Comment by ZakShearman** [comment]
Well, 3 ticks. I can see if I can replicate it in non modified hit delay if you would like.
