### ISSUE TITLE
[REQUEST] Auto Updater

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#489]
**What features/checks do you need?:** Hi there, it would be great if we have the option or a way of being able to auto update the plugin instead of having to download, upload, restart, etc. every time.

There are two main options:
  - Have the plugin use a config option and then it will download the update when there is one and then either with a set time, restart or upon user request.
  - Have a system similar to FAWE so that it will send a message on join if a player has a certain permission and they can run /fawe update, which will download the latest update and also restart the server when it is executed.

This would drastically reduce the updating time of the plugin for everyone.

Thanks.

**Comment by jiangdashao** [comment]
I know it's a good idea, but Matrix changes the config files frequently, I can't auto update the config files...
