### ISSUE TITLE
Slime block

### ISSUE THREAD

**Issue by JakubEG0** [jiangdashao/Matrix-Issues#49]
## How you trigger the false positive?
When jumping from Slime Block to Slime Block (parkour), he moves back.

## Verbose Message:
<! -- Provide the verbose message here -->

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 

## Server Infomation
**Matrix Version**: 1.5.4
**Server Version**: 1.13.2
**ProtocolLib Version**: newest

**Comment by jiangdashao** [comment]
No video, and no verbose message provided

**Comment by JakubEG0** [comment]
I'll copy in a moment.

**Comment by JakubEG0** [comment]
Video:
https://youtu.be/_9y0bPH5xOk

**Comment by JakubEG0** [comment]
The issue still exists! (the newest version)
