### ISSUE TITLE
[REQUEST] Auto totem check

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#490]
**What features/checks do you need?:**
Auto totem check pls

**Comment by jiangdashao** [comment]
what is this?

**Comment by wulfwuud** [comment]
https://streamable.com/czpjg

**Comment by Nikita11790** [comment]
auto totem basically is when a totem is used another one is auto moved into 2nd hand slot

**Comment by ZakShearman** [comment]
I can imagine this being extremely hard to detect because as I see it, it's pretty similar to AutoSoup.

**Comment by ignPerformance** [comment]
This is potentially detectable.
https://github.com/Photon-GitHub/AACAdditionPro/blob/master/src/main/java/de/photon/AACAdditionPro/modules/checks/AutoPotion.java

**Comment by ZakShearman** [comment]
That looks all related to Auto Potion, and that's different to Auto Soup by a long way. Auto Soup does not require any change in looking direction or movement.
