### ISSUE TITLE
[INCOMPATIBILITY] Fast Break with TokenEnchant

### ISSUE THREAD

**Issue by Disorbs** [jiangdashao/Matrix-Issues#494]
## Troubleshooting Information
- [x] The incompatible plugin is up-to-date
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3 paper
**Incompatible plugin**: TokenEnchant
**Verbose messages (or) console errors**: 
**How/when does this happen**: only when mining up or down since strip mining is fine
**Video of incompatibility**: https://youtu.be/cKvqFEWMaVw
**Other information**: default settings when mining upwards you get triggers with a vanilla eff 5 pickaxe as well with another eff 5 + haste 2 from the video you can see the messages trigger and for the second its already denying the block break

## Configuration Files
**Link to checks.yml file**:  https://pastebin.com/raw/AtdKMBUG
**Link to config.yml file**: https://pastebin.com/raw/Q0Vk3hWV

**Comment by jiangdashao** [comment]
1. it's a paid plugin (TokenEnchant)
2. you didn't provide the verbose message
