### ISSUE TITLE
[FP] WorldGuard protected Blocks

### ISSUE THREAD

**Issue by Disorbs** [jiangdashao/Matrix-Issues#495]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3
**Verbose messages**: 
**How/when does this happen**: trying to break protected crops at spawn with axe by worldguard
**Video of false positive**: https://i.gyazo.com/26bd0336287e97d96cf1d5c1c5672af8.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Please provide the verbose message
