### ISSUE TITLE
[FP] Killaura False Positive

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#498]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Spigot
**Verbose messages**: In Video
**How/when does this happen**: Attacking an NPC.
**Video of false positive**: http://zak.pink/matrix/killaura-1.mp4
**Other**: Running latest experimental version.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by ignPerformance** [comment]
Heuristics flagged my players as well.
Turned it off.
