### ISSUE TITLE
[LAGGY] In Player Join the server drop tps

### ISSUE THREAD

**Issue by JavituRec** [jiangdashao/Matrix-Issues#499]
Hi,

this is not  a bug or plugin incompatibility, when player join to server drop tps
timings : https://timings.aikar.co/?id=c00594bc46e34e6b8dd89022aaad7545

/Version
![verss](https://user-images.githubusercontent.com/10663192/60732280-e8e10200-9f49-11e9-90f5-c0aa78329dbc.png)

There is not much loss of tps in this report that only a player join if this multiplies I suppose that it will increase the loss of tps.

Sincerely.

**Comment by JavituRec** [comment]
Other timings more clear:
https://timings.aikar.co/?id=9d3697c001384ec8b77cbb9989cfd163

**Comment by jiangdashao** [comment]
I will fix it
