### ISSUE TITLE
[ERROR] Latest version of matrix crashes when server boots

### ISSUE THREAD

**Issue by Nikita11790** [jiangdashao/Matrix-Issues#500]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 124
**Error(s) found in console**: https://paste.gg/p/anonymous/210172e9d5f34bb4a68fa800d9d05f09
**How/when does this happen**: on server boot
**Other information**: 

## Configuration Files
**Link to checks.yml file**:   https://paste.gg/p/anonymous/77c43906183f4fe897719535f4dadfdb
**Link to config.yml file**:
https://paste.gg/p/anonymous/e5a514b8022c441c9bb473c59f86ccf4

**Comment by Nikita11790** [comment]
I deleted config.yml but I have same issue

**Comment by jiangdashao** [comment]
delete all config file"s"

checks.yml
language.yml
config.yml

**Comment by Nikita11790** [comment]
Oh ok
