### ISSUE TITLE
[BYPASS] Phase

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#502]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Liquid Bounce
**Cheat that bypassed**: Phase - Mineplex
**Video of bypass**: https://www.zak.pink/matrix/phase-3.mp4
**Other information**: ac.zakshearman.com

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
It doesn't detect some blocks like fence

**Comment by jiangdashao** [comment]
Because it's weird collision box

**Comment by ZakShearman** [comment]
What about at 35 seconds where I full block phased?
