### ISSUE TITLE
[INCOMPATIBILITY] AdvancedDevUtils-Spigot (Fake PlayerNPCs)

### ISSUE THREAD

**Issue by Sprax2013** [jiangdashao/Matrix-Issues#503]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**Incompatible plugin**: AdvancedDevUtils-Spigot version 0.7.6-DEV
**Verbose messages (or) console errors**: Kirschbroetchen lost connection: Internal Exception: java.io.IOException: Error while write(...): Datenübergabe unterbrochen (broken pipe)
**How/when does this happen**: When Matrix is install. It stops happening as soon as the server starts without Matrix
**Video of incompatibility**: https://youtu.be/eQeFYNQupDA (btw. i know my IP is in the clip)
**Other information**: AdvancedDevUtils-Spigot (or ADU-Spigot for short) spawns a fake PlayerNPCs - Interacting with it causes the client to disconnect from the server (in my case falling back to the hub-server)
ADU-Spigot source: https://gitlab.sprax2013.de/Sprax2013/advanceddevutils-spigot/tree/master/src/de/sprax2013/advanced_dev_utils/spigot/npc
ADU-Spigot.jar: [ADU-Spigot-0.7.6-DEV.zip](https://github.com/jiangdashao/Matrix-Issues/files/3365878/ADU-Spigot-0.7.6-DEV.zip)

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/mNS2qiBE
**Link to config.yml file**: https://pastebin.com/jkWF7KU8

**Comment by ZakShearman** [comment]
Can you do /matrix verbose and then record the video again so that we can get the verbose message. The message that you supplied as the one for verbose above is incorrect.

A screenshot would be fine as well.

**Comment by Sprax2013** [comment]
I'm already enabling verbose around second 10 in the video.

**Comment by ZakShearman** [comment]
Well, it looks like there were no verbose messages, which means that it is not to do with Matrix as no matrix detections are being flagged.

**Comment by Sprax2013** [comment]
Yeah, that's what I'm confused about. As soon as I disable/delete Matrix from the server and restart it, I don't get kicked. So I thought it's happening because Matrix does not expect an interaction with an 'invalid' Entity-ID. It is somehow related to Matrix.

I spawn them using an Entity-Spawn packet (+PlayerInfoPacket). The server doesn't know about them as he does with the normal players. The interaction is tracked using ProtocolLib and cancelled, so bukkit/spigot should not process them.

**Comment by jiangdashao** [comment]
What's your ProtocolLib version?

**Comment by jiangdashao** [comment]
Is there any error in your BungeeCord's console?

**Comment by Sprax2013** [comment]
Didn't think of that. Exception from BungeeCord: https://pastebin.com/Frr9zKC5

ProtocolLib version: 4.4.0

**Comment by jiangdashao** [comment]
Did you sent a packet or related things when you handle the interact packet?

**Comment by Sprax2013** [comment]
I use ProtocolLib to listen for interact packages. If the EntityID is the one from the NPC it gets cancelled and I use the Bukkit-API to open an Inventory.

I sadly didn't have any time for testing. But what I saw: This does not happen with every NPC but they should be the same... They both just stand there and open an inventory on interact... My Hub-Server doesn't have any problems. But my Gameserver (from the video) does

**Comment by jiangdashao** [comment]
How do you open an inventory? Did you open it in main thread?

**Comment by Sprax2013** [comment]
Ahhh I'm stupid. My link to the source is down xDD

Now that say so... I thought so but ProtocolLib is propably not running all this in the main thread... I'll check that

Okay I'm done checking. I've tested opening it in the Main Thread (because I was not >.<) and using Matrix v2.0.7 there are no problems anymore
