### ISSUE TITLE
[FP] Mining fastplace/fastbreak, & phase

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#504]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://pastebin.com/09YBG5MT
**How/when does this happen**: Just mine, the better the pickaxe the easier it triggers I guess (like the one in the video). Everyone on my server triggers this.
**Video of false positive**: https://youtu.be/7Hk0R9Hck_I
**Other information**: It may be a coincidence, but in the video you can see someone else on the server getting kicked for fast place apparently.
The user I was recording also got kicked for phase (because a mined block respawned for some reason, so it was considered phase).
A chatcontrol error also occurs at the same time, it may also be a coincidence.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Please provide the verbose message

**Comment by MithrandirCraft** [comment]
Do you mean this by any chance? Or do you require further indepth debugging?
![imagen](https://user-images.githubusercontent.com/6623704/60825552-38266d00-a1ac-11e9-8534-d19ee382813a.png)

**Comment by MithrandirCraft** [comment]
Provided.

**Comment by ZakShearman** [comment]
Please provide all of the verbose messages, that one alone does not actually help, as it is not contributing anything to the kick.

**Comment by MithrandirCraft** [comment]
Pastebinned full relevant matrix logs.

**Comment by MithrandirCraft** [comment]
Still encountering issues. I'd suggest this ticket to be reopened.

![imagen](https://user-images.githubusercontent.com/6623704/61244474-99b97f00-a74a-11e9-8cd9-e2132e293efb.png) (2.0.5-hotfix)
Spigot 1.13.2

Matrix logs: https://pastebin.com/Xhwc3QgB
Pickaxe used for triggering:
![imagen](https://user-images.githubusercontent.com/6623704/61244532-bbb30180-a74a-11e9-966e-496000e02ca0.png)

**Comment by MithrandirCraft** [comment]
Matrix 2.0.6
Spigot 1.13.2
Player still getting kicked for mining with this pickaxe:
![imagen](https://user-images.githubusercontent.com/6623704/61668774-0c43d500-acde-11e9-9ab8-adfd15660e68.png)
Logs:
https://gist.github.com/MithrandirCraft/723ced5939d4ff0c0f65d02d25ea09ad
