### ISSUE TITLE
[FP] Speed/Fly FP - Headhitting against a block

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#506]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper-123 1.14.3
**Verbose messages**: In the video
**How/when does this happen**: Jumping while part of your hitbox is under a non-full block(Trapdoor, slab)
**Video of false positive**: https://www.youtube.com/watch?v=Hd3EfMeFZ8c
**Other information**: Ice is not required, only happens when your head is not directly under the block you are headhitting(as shown in the video)

## Configuration Files
**Link to checks.yml file**: default for 2.0.4 https://pastebin.com/vmt2L8WK
**Link to config.yml file**: default for 2.0.4 https://pastebin.com/4623Sucz

**Comment by jiangdashao** [comment]
I don't think that will lead to any problems.
