### ISSUE TITLE
[FP] Fly FP caused by levitation effect

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#508]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper-123 1.14.3
**Verbose messages**: In the video
**How/when does this happen**: After levitation effect ends
**Video of false positive**: https://www.youtube.com/watch?v=gMFrQzsHYzk
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default for 2.0.4 https://pastebin.com/vmt2L8WK
**Link to config.yml file**: default for 2.0.4 https://pastebin.com/4623Sucz

**Comment by ZakShearman** [comment]
Can you show a video of this being able to get to a level where they are rubber banded back, or does it only flag the verbose once?

**Comment by Kuraky** [comment]
It's quite inconsistent - usually it flags once(rarely twice) and sometimes it doesn't flag at all. For some reason shulker's levitation doesn't cause the false positive at all or atleast I was unable to make it flag me. However, giving myself through /effect the exact same levitation duration and amplifier as the one shulker gives flagged me. It causes some heavy rubber banding at really high amplifiers. https://www.youtube.com/watch?v=nWZ4-9Ra9zo

**Comment by ZakShearman** [comment]
Because of how little this flags, it would not cause any issues. This is only a verbose message and not an actual cheating notification.

**Comment by jiangdashao** [comment]
It won't cause drag back or kick
