### ISSUE TITLE
[BYPASS]  Indefinite Packet Fly

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#509]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3 Paper 
**Hacked client**:  WWE
**Link to hacked client**:  https://www.wizardhax.com/2019/06/01/minecraft-1-14-x-wwe-hacked-cheat-client-download/
**Cheat that bypassed**:  Packet Fly
**Video of bypass**:  https://clips.twitch.tv/EsteemedLachrymoseDonutArgieB8
**Other information**:  
Mode: Fast
Y Distance 999.0
Y Mode: Y+
Wait: Yes
Wait Time: 2.5
Wait Offset: 5.0
Speed: 1.0

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I can't launch WWE client :(

**Comment by jiangdashao** [comment]
Fixed
