### ISSUE TITLE
[BYPASS] Jesus

### ISSUE THREAD

**Issue by coco0325** [jiangdashao/Matrix-Issues#511]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.14.3
**Hacked client**: 
aristois
**Link to hacked client**: 
https://aristois.net/
**Cheat that bypassed**: 
Jesus

**Comment by jiangdashao** [comment]
Please provide the video evidence

**Comment by coco0325** [comment]
Video [https://www.youtube.com/watch?v=tZC-GamrSgY&feature=youtu.be](url)

**Comment by jiangdashao** [comment]
try deeper water, one block water maybe can't detect jesus
