### ISSUE TITLE
[ERROR] Nothing showing in Violations GUI when player caught

### ISSUE THREAD

**Issue by hamcoremusic** [jiangdashao/Matrix-Issues#518]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3
**Error(s) found in console**: None
**How/when does this happen**: When clicking "Show Violations" in the GUI
**Other information**: Nothing shows in the violations GUI. I cannot check and see who is violating the rules and triggering anti cheat

**Comment by jiangdashao** [comment]
because no one has violations

**Comment by jiangdashao** [comment]
the violations can auto decrease itself
