### ISSUE TITLE
[FP] Jesus

### ISSUE THREAD

**Issue by Nikita11790** [jiangdashao/Matrix-Issues#521]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3 paper 127
**Verbose messages**:  inside of video
**How/when does this happen**: when a certen player is swimming
**Video of false positive**: https://streamable.com/uu2e8
**Other information**: it only happens with this person

## Configuration Files
**Link to checks.yml file**: latest default
**Link to config.yml file**: latest default

**Comment by Nikita11790** [comment]
Happend to someone else

**Comment by henrik9999** [comment]
yeah happens for players on my serve too i disabled the check because of that

**Comment by S-B99** [comment]
Why was this closed without a solution?

**Comment by Nikita11790** [comment]
it was fixed in update 2.0.5

**Comment by S-B99** [comment]
I mean making it more obvious with a close message would be helpful for people in the future.

**Comment by ZakShearman** [comment]
It was added to the milestone, and then closed inside the milestone when it was fixed.
