### ISSUE TITLE
[ERROR] matrix disabled

### ISSUE THREAD

**Issue by henrik9999** [jiangdashao/Matrix-Issues#522]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version: 1.14.3 Paper-129**: 
**https://pastebin.com/xCfhtAmh**: 

Matrix wont work after that and is red in /pl

**Comment by jiangdashao** [comment]
delete your old config files
