### ISSUE TITLE
When join a player to server [ERROR]

### ISSUE THREAD

**Issue by Zekcero** [jiangdashao/Matrix-Issues#523]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
**Error(s) found in console**: https://pastebin.com/9WRR3zBq
**How/when does this happen**: When a player joins the server it automatically kicks it (I use bungeecord, the error that happens comes out in the bungeecord).
**Other information**: nothing more.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/DpVqrwhd
**Link to config.yml file**: https://pastebin.com/Sfbm0Hzt

**Comment by Zekcero** [comment]
Video explaining what happens.
https://youtu.be/9B-YWPyDRtg

**Comment by jiangdashao** [comment]
What's your ProtocolLib version?
And did you install other anticheats?
Can you provide your plugin list?

**Comment by Zekcero** [comment]
1) last version. 
2) kauri anticheat. 
3) is in the video.

**Comment by jiangdashao** [comment]
Remove Kauri and PacketListenerAPI, and try again

**Comment by Zekcero** [comment]
Ok, I remove kauri and working but I need use that anticheat.

**Comment by jiangdashao** [comment]
So remvove Matrix

**Comment by Zekcero** [comment]
But I want use matrix, too

**Comment by jiangdashao** [comment]
I can't help it. You should contact with Kauri's author, it's his problem, because Matrix works well with other anticheats, like AAC/Spartan/NCP

**Comment by Zekcero** [comment]
Ok thx

**Comment by ZakShearman** [comment]
BTW, not much point as Funke will just say "why are you using another anti cheat" and dismiss it xD. Can always try tho.

**Comment by Zekcero** [comment]
Shit You're right.
