### ISSUE TITLE
Boat on Ice issue

### ISSUE THREAD

**Issue by RainbowTea** [jiangdashao/Matrix-Issues#53]
## How you trigger the false positive?
My members were using boats on  ice and trying to move forward it instantly kicks them out. 
If i disable speed checking the issue is stopped. I watched them reproduce this false positive.
https://pastebin.com/kmGA9YFZ
This is my config.

## Verbose Message:
If this means the messages like ' [Maxtrix] Warnings, there was none when the boat was used. it just boots them out

## Videos:
no video. 

## Server Infomation
**Matrix Version**: Matrix v1.6.0 is the version i am using, and it also had this issue in the previous version.
**Server Version**: Paper version git-Paper-564 (MC: 1.13.2)  is what i am running
**ProtocolLib Version**: 4.40

**Comment by jiangdashao** [comment]
It was caused by BoatSpeed check

**Comment by RainbowTea** [comment]
> It was caused by BoatSpeed check

Okay, and how is this fixed? or how do i fix it then? or is it fixed?

**Comment by jiangdashao** [comment]
Already fixed
