### ISSUE TITLE
[FP] when players break blocks = kick interact/fastplace

### ISSUE THREAD

**Issue by OverBrave** [jiangdashao/Matrix-Issues#530]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.14.3
**Verbose messages**:  ![image](https://user-images.githubusercontent.com/47111280/61210553-81734100-a705-11e9-819d-c8c03ede9a78.png)
**Video of false positive**: 
[dene.zip](https://github.com/jiangdashao/Matrix-Issues/files/3391871/dene.zip)

**Comment by jiangdashao** [comment]
Please upload video via https://streamable.com/

**Comment by OverBrave** [comment]
https://streamable.com/uf5bt
