### ISSUE TITLE
[BYPASS] Killaura

### ISSUE THREAD

**Issue by TheDarkSword** [jiangdashao/Matrix-Issues#532]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Hacked client**: Aristois
**Link to hacked client**: https://aristois.net/
**Cheat that bypassed**: Killaura
**Video of bypass**: I can't register video
**Other information**: The Killaura is detected when used with critical cheats otherwise not

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Aristois is shit, it can't bypass
If you want to proof, please provide video
