### ISSUE TITLE
Keep get kick because fastbreak in Skyblock ~~"

### ISSUE THREAD

**Issue by CaoTrongThang** [jiangdashao/Matrix-Issues#533]
My player just keep get kick when mining with effective 13 pickaxe because FastBreak in my Skyblock server ~~"
![image](https://user-images.githubusercontent.com/51023235/61235318-75b46880-a75f-11e9-96e9-5b9b76acdf77.png)

**Comment by jiangdashao** [comment]
Please use our issue template
