### ISSUE TITLE
[FP] Breaking/Placing Blocks while event is cancelled

### ISSUE THREAD

**Issue by Pas02** [jiangdashao/Matrix-Issues#534]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Spigot
**Verbose messages**: [Server thread/INFO]: [Matrix] Daisukee tried to place/break a block too quickly (FastPlace)
**How/when does this happen**: Breaking or Placing a Block when the BlockBreakEvent or BlockPlaceEvent is cancelled
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/gVnjXK8T
**Link to config.yml file**: https://pastebin.com/LZh01Tnn

**Comment by Kuraky** [comment]
Can confirm, note the video was recorded on 1.14.3

https://www.youtube.com/watch?v=XcHz0XhVTnA
