### ISSUE TITLE
Too many false positives

### ISSUE THREAD

**Issue by FendiTony777** [jiangdashao/Matrix-Issues#535]
Minecraft server
Spigot jar 1.12.2
Matrix version 2.0.5 [Model 6]
Protocol Lib 4.4.0
70 minutes timings with anticheat ON Average TPS: 19.63 - Server Load:  11.80%

Players with both high ping and occasionally normal ping get kicked or flagged by Matrix's anticheat system. I've attached a video as I'm sure the players are not cheating.
Also there are way TOO MANY reports from the verbose, it's basically flooding the chat, and that is with only 5 players on...

https://youtu.be/7YRjKMGozjg   (video of a player randomly getting kicked)

**Comment by ZakShearman** [comment]
Please fill out the issue report correctly.
