### ISSUE TITLE
Killaura & Velocity [FP] 

### ISSUE THREAD

**Issue by Zekcero** [jiangdashao/Matrix-Issues#537]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**Verbose messages**: https://gyazo.com/55d07afdb86abb2fa96d1cfe7658d707
**How/when does this happen**: In pvp
**Video of false positive**: https://youtu.be/DtP15F5SmGk  &(With lag) https://youtu.be/TUnSo_BdRsQ
**Other information**: Also when the player goes to a ping something high (200+ms) he kicks it and the player is vanilla.

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/DpVqrwhd
**Link to config.yml file**: https://pastebin.com/Sfbm0Hzt

**Comment by jiangdashao** [comment]
1. It's very normal that you get some flags when you fighting
2. If you are running Matrix on a PvP server, I suggest you disable Velocity.Expect check
