### ISSUE TITLE
[REQUEST] bot checking

### ISSUE THREAD

**Issue by ThePhoenix96** [jiangdashao/Matrix-Issues#538]
**What features/checks do you need?:**
i want to block auto mining (youtube link below how it works). would be nice to have antixray too based on how much resources player breaking and how fast,
https://www.youtube.com/watch?v=StquF69-_wI

**Comment by ThePhoenix96** [comment]
i mean if player find 64 diamond in 5 mins he is ofc cheater.

**Comment by jiangdashao** [comment]
You should use an AntiXray plugin, or use Spigot/PaperSpigot's built-in anti-xray system
