### ISSUE TITLE
[BYPASS] Killaura

### ISSUE THREAD

**Issue by TheDarkSword** [jiangdashao/Matrix-Issues#539]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.3.2
**Hacked client**: Aristois
**Link to hacked client**: https://streamable.com/yjuqe
**Cheat that bypassed**: Killaura
**Video of bypass**: https://streamable.com/yjuqe
**Other information**: If I use Killaura with Criticals cheats, Matrix detects it and kicks the player otherwise it does nothing

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by coolpvpv** [comment]
aristoiss aura doesn't aim it only aims at where your aiming so it should of falsed the hitbox check
