### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by FendiTony777** [jiangdashao/Matrix-Issues#540]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.11.2 (latest build)
**Verbose messages**: [playername] failed Killaura/Speed/Velocity/otherhacks check
**How/when does this happen**: everytime
**Video of false positive**: https://youtu.be/eeqCqFZVhGI and https://youtu.be/7YRjKMGozjg
**Other information**: I've excluded the fact that is the server's fault since I've even removed 1.12.2 version which is known for keepalive packets making the ping bad.

## Configuration Files
**Link to checks.yml file**: DEFAULT
**Link to config.yml file**: DEFAULT

**Comment by ZakShearman** [comment]
In the first video, I believe the player is cheating. It looks like they hit two endermen at the same time near the end of the video. They are also banned by anti cheats on at least one other major server.

**Comment by FendiTony777** [comment]
Ok thank you, The next player that get falsely kicked , I'm going to check him manually via AnyDesk to be sure. By the way how I find out if a player is already banned on other major servers (HyPixel, Mineplex etc..)?

**Comment by ZakShearman** [comment]
Some servers offer methods to do so such as websites and some I know people.
