### ISSUE TITLE
[FP] Killaura

### ISSUE THREAD

**Issue by FendiTony777** [jiangdashao/Matrix-Issues#544]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8
**Verbose messages**: [Matrix] _MsZelda_ failed Killaura check : heuristic check : pattern: #2 : val: 44.47292470932007/44.47292184829712 (+2) : vl:16 ping :95 tps:20.0 component: ka.heuristic 
**How/when does this happen**: Player attacking mobs/bots/entities
**Video of false positive**: https://youtu.be/uuZdmTLsNEo
**Other information**: Running latest Matrix version on a VPN,
IP: 51.77.231.129:25577

## Configuration Files
**Link to checks.yml file**: not needed as it's default.
**Link to config.yml file**:  not needed as it's default.

**Comment by jiangdashao** [comment]
It's very normal that you get some flags when you are fighting

**Comment by FendiTony777** [comment]
> 
> 
> It's very normal that you get some flags when you are fighting

Yeah but it false flags to the point that it kicked me.

**Comment by jiangdashao** [comment]
It won't kick you in real server

**Comment by FendiTony777** [comment]
I am running it on a private test server, if you want video i'll provide it.

**Comment by jiangdashao** [comment]
I mean, it won't kick you in the production environment server, if you find false positives in production environment server, the report it

**Comment by FendiTony777** [comment]
but why it kicks in a normal server? I am running spigot 1.8.8

**Comment by jiangdashao** [comment]
ok, provide a video here

**Comment by FendiTony777** [comment]
Sure, here is the video, you have to wait a little for Youtube to upgrade quality to 1080p
https://youtu.be/SlVerldSKhM

**Comment by FendiTony777** [comment]
I think that the yaw/pitch control is too sensitive

**Comment by jiangdashao** [comment]
You are deliberately triggering false positives, I can't help this

**Comment by FendiTony777** [comment]
I don't get this false positives with other anticheats but ok.
