### ISSUE TITLE
[FP] Speed

### ISSUE THREAD

**Issue by FendiTony777** [jiangdashao/Matrix-Issues#545]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8 lastest build
**Verbose messages**: https://imgur.com/d476dbb7-5821-485e-82ad-440716a80a68
**How/when does this happen**: When climbing stairs and pressing space (legit)
**Video of false positive**:  https://youtu.be/78w7ExhJl-Q
**Other information**: Matrix running on latest version and default configs. Server 51.77.231.129:25577

## Configuration Files
**Link to checks.yml file**: not needed since it's default ones
**Link to config.yml file**: not needed since it's default ones

**Comment by jiangdashao** [comment]
It won't cause kick
