### ISSUE TITLE
[FP] Fly when towering

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#548]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 paper-135
**Verbose messages**: In the video
**How/when does this happen**: Towering up when server's TPS is fluctuating
**Video of false positive**: https://www.youtube.com/watch?v=k_XP_Iy4IUE
**Other information**: The video was recorded on 2.0.5 although the issue still exists in 2.0.6, also note it was very hard to simulate just the right amount of lag for me to reproduce it and record it. On my server I've noticed this happening to afew people much faster than on the video.(https://www.youtube.com/watch?v=N5Z7ht7NyZ8)

## Configuration Files
**Link to checks.yml file**: default for 2.0.6
**Link to config.yml file**: default for 2.0.6

**Comment by jiangdashao** [comment]
It was caused by server lag
look at your TPS, it dropped to 13

**Comment by jiangdashao** [comment]
And Matrix reduced the VL to zero

**Comment by Kuraky** [comment]
It does however teleport you back, even though I have TPS protection enabled in the config and set to 17. The only way for me to prevent it is to entirely disable fly.main.
