### ISSUE TITLE
[FP] FastPlace False Reports

### ISSUE THREAD

**Issue by RageYT** [jiangdashao/Matrix-Issues#549]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: PLAYER tried to place/break a block too quickly (FastPlace)
![image](https://user-images.githubusercontent.com/17907584/61594458-22587500-abba-11e9-8845-7ba762278992.png)

**How/when does this happen**: When the player is using abilities from mcMMO, like Super Breaker
**Video of false positive**: N/A, can't seem to get it reproduced
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: https://github.com/jiangdashao/Matrix-Issues/blob/master/checks.yml
**Link to config.yml file**: https://github.com/jiangdashao/Matrix-Issues/blob/master/config.yml

**Comment by ZakShearman** [comment]
I can try to make this occur, but it's going to be quite hard without a video or being able to reproduce it.

**Comment by ZakShearman** [comment]
Could you add the verbose messages that are output by /matrix verbose please.

**Comment by RageYT** [comment]
Yeah sorry I couldn't seem to get a video and yeah sure thing I will get a log of it. Also, I think the issue actually occurs with mcMMO and the super breaker ability.

**Comment by RageYT** [comment]
![image](https://user-images.githubusercontent.com/17907584/61594454-15d41c80-abba-11e9-8e16-e4f47efabd77.png)

**Comment by RageYT** [comment]
So will mcMMO compatibility not be a thing? I noticed you said before something about mcMMO compatibility and not implementing it.
