### ISSUE TITLE
Bad Scaffold(Block) check

### ISSUE THREAD

**Issue by KoTEHoChek** [jiangdashao/Matrix-Issues#55]
## Bypass Infomation
**Hack Client**: Akrien
**Bypassed Hacking Type**: Scaffold
**Matrix Version**: 1.6.1
**Server Version**: 1.8.8

**Comment by jiangdashao** [comment]
Provide video, pls

**Comment by jiangdashao** [comment]
tested, no bypass

**Comment by KoTEHoChek** [comment]
https://youtu.be/BKM2kdveUxc

**Comment by jiangdashao** [comment]
You are flagged...
But you are so lag, try to disable latency protection in config.yml
