### ISSUE TITLE
[FP] Some KillAura false positives and fatal FP for Velocity

### ISSUE THREAD

**Issue by mlegok** [jiangdashao/Matrix-Issues#550]
Last version PLib
Last version matrix
Last version paper spigot 1.13.2
https://www.youtube.com/watch?v=KMGpyMZYXGc&feature=youtu.be
https://www.youtube.com/watch?v=tZ4aYZ8emmY&feature=youtu.be

**Comment by ZakShearman** [comment]
In the first video, they do not actually flag once, only verbose messages which are only meant as a debugging tool. Checking the other video now.

**Comment by ZakShearman** [comment]
Please can you give the other information that is in the template for a false positive, it is there for a reason (are you using the default configuration files or modified).

**Comment by mlegok** [comment]
I am ising the default config.
