### ISSUE TITLE
Slime block Fly false positive

### ISSUE THREAD

**Issue by Performancee** [jiangdashao/Matrix-Issues#56]
## How you trigger the false positive?

Go in creative mode, fly up 50~ blocks and land on a slime block.

## Verbose Message:
<! -- Provide the verbose message here -->
Player123 failed Fly check | t:step-1 a=1.69811652262527 b=1.6372380987397417 (+8) | vl:8 ping:79 tps:19.98

## Videos:
<! -- If you recorded a video for it, write the video link at here --> 
https://youtu.be/u0_w6_yP95k

## Server Infomation
**Matrix Version**: 1.6.1
**Server Version**: Paper version git-Paper-571 (MC: 1.13.2)
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
the bug still works in 1.6.1?

**Comment by Performancee** [comment]
Yes it does.

**Comment by JakubEG0** [comment]
Yes.
