### ISSUE TITLE
[INCOMPATIBILITY] CustomBlocks

### ISSUE THREAD

**Issue by coolpvpv** [jiangdashao/Matrix-Issues#572]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Incompatible plugin: CustomBlocks link https://www.spigotmc.org/resources/customblocks.64002/
Verbose messages (or) console errors: Watch the video
How/when does this happen: when you get on a sponge and get launched it will flag you for either fly speed or velocity
Video of incompatibility: https://streamable.com/1x055
Other information: 

Configuration Files
Link to checks.yml file: Default Config
Link to config.yml file: Default Config

**Comment by jiangdashao** [comment]
I won't add compatibility support for very few people use plugins
