### ISSUE TITLE
[FP] 1.14 Scaffolding fastplace/scaffold flag

### ISSUE THREAD

**Issue by Yottazoid** [jiangdashao/Matrix-Issues#574]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:
`git-Paper-137 (MC: 1.14.4)`
`Matrix AntiCheat v2.0.6`
`ProtocolLib v4.5.0-SNAPSHOT`
**Verbose messages**: 
![image](https://user-images.githubusercontent.com/23495508/61606595-73d23400-ac8e-11e9-9f86-54cdbc4bb81b.png)
**How/when does this happen**:
When placing scaffolding blocks by clicking on other scaffolding blocks.
**Video of false positive**: [2019-07-22 2014-29-02.mp4](https://www.dropbox.com/s/7re17t55a4mex84/2019-07-22%2014-29-02.mp4)
**Other information**:
Vanilla client, no other plugins present.

## Configuration Files
**Link to checks.yml file**: (Default for 2.0.6) https://pastebin.com/gxeD6uA4
**Link to config.yml file**: (Default for 2.0.6) https://pastebin.com/TC15Cj0G

**Comment by DaLeberkasPepi** [comment]
in the newest version (v2.2.2) i again get a lot of false positive kicks when using scaffoulding
