### ISSUE TITLE
[FP] Velocity, while interacting with mobs and spider webs

### ISSUE THREAD

**Issue by mlegok** [jiangdashao/Matrix-Issues#578]
All last version :)
So, you fixed some bags with this interacts, but anticheat is also kicking players for velocity, when they got damaged from mobs (It can be a spider, skeleton, phantom and another mobs) in spider, or maybe in air, please pay more attention for this interact with mobs
https://www.youtube.com/watch?v=hBGCNMpAdo8

**Comment by coolpvpv** [comment]
> All last version :)
> So, you fixed some bags with this interacts, but anticheat is also kicking players for velocity, when they got damaged from mobs (It can be a spider, skeleton, phantom and another mobs) in spider, or maybe in air, please pay more attention for this interact with mobs
> https://www.youtube.com/watch?v=hBGCNMpAdo8

why did you completely remove its default issue page and just used your own
