### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by ezzerland** [jiangdashao/Matrix-Issues#579]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 BeerSpigot (Premium)
**Error(s) found in console**: https://hastebin.com/buxohatiri.pl
**How/when does this happen**: Just freshly loaded it, joined and moved my mouse. Didn't even move my player yet.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: It was default, freshly loaded
**Link to config.yml file**: It was default, freshly loaded

**Comment by jiangdashao** [comment]
Did you try Spigot?

**Comment by ezzerland** [comment]
Yes. Spigot, TacoSpigot and Paper. All 3 of those versions work fine. Seems to be an error unique to BeerSpigot. Unfortunate, really, since BeerSpigot is a must.

**Comment by jiangdashao** [comment]
So I can't help that, because I don't have BeerSpigot

**Comment by ezzerland** [comment]
Can you dm me on disc and I can send it to you?

**Comment by jiangdashao** [comment]
PM me on Discord

**Comment by ezzerland** [comment]
Closing as unresolvable. Thanks for trying :)
