### ISSUE TITLE
[REQUEST] More commands execute and notify player

### ISSUE THREAD

**Issue by Rigagit** [jiangdashao/Matrix-Issues#580]
1. No notification is sent to the mod chat (perm matrix.notify) if the player has been kicked (I don’t want to display a kick message in the general chat). Make notify into the mod chat (perm matrix.notify) if player kicked. (This can be replaced by the third point, then it will be possible to execute a player's kick notification and execute kick)

2. Also, the player himself does not know why he was kicked, maybe do commands "say"?

3. Make a few executable commands that will allow to notify the player, mod chat and another function.

Example:

  ```
commands:
    70: 
        1: 'matrix notify %player% Fly #1'
        2: 'matrix say %player% You are suspected of Fly #1'
    120: 
        1: 'matrix notify %player% Fly #2'
        2: 'matrix say %player% You are suspected of Fly #2'
    190: 
        1: 'matrix notify %player% kicked for Fly'
        2: 'matrix say %player% You are kicked for Fly'
        3: 'matrix kick %player% Fly'
```

**Comment by jiangdashao** [comment]
1. You can custom the commands, Matrix support multi commands.
2. "/matrix msg <player> <message>" can send message to player
