### ISSUE TITLE
[REQUEST] How to do multi commands?

### ISSUE THREAD

**Issue by Rigagit** [jiangdashao/Matrix-Issues#582]
Back to the past issues https://github.com/jiangdashao/Matrix-Issues/issues/580

Can you show an example of multi commands?
I need several commands for one VL, but not several VL (see the example in the link above)

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/61695001-40aea400-ad65-11e9-92e8-d03617d5b0b9.png)

**Comment by Rigagit** [comment]
Thanks. add in an example somewhere so less disturbed :D
