### ISSUE TITLE
[BYPASS] Velocity

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#584]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**:  1.12.2
**Hacked client**: Impact 4.6
**Link to hacked client**: https://impactdevelopment.github.io/
**Cheat that bypassed**: Velocity 
**Video of bypass**: https://youtu.be/MFj20laO-4g
**Other information**: ???

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
You are moving when you get damaged
