### ISSUE TITLE
[REQUEST] Sounds support, auto-config update support and Anti-Xray based on fake ores

### ISSUE THREAD

**Issue by Germanode** [jiangdashao/Matrix-Issues#588]
**What features/checks do you need?:**

It would be good to allow:

1. **Sound** to be played to admins when a player gets kicked or is detected for cheating. Optional setting of course.

2. Auto-**Config updates**. When Matrix is updated, the config often changes and it's up to the server owner to manually edit the config every time. Is it somehow possible to add auto-update feature which updates the new values in the config, without touching the already-changed values? This would really be lovely.

3. New **Xray check** (Completely different from all anti-xray plugins):
Special 'fake' ores, placed by the plugin in impossible directions around someone who is suspected of Xray (mines too many ores or uses a weird pattern). 

Let's say someone is mining in a weird pattern with possibly no light level. Ahead of him, fake diamonds appear, 3 blocks down and 3 blocks to the left, so a normal miner would have never noticed them. The Xrayer will likely go for the fake ore and try to mine it. This would ofc trigger matrix.

When the special ore is mined, it drops a normal stone block and notifies the admins of suspected Xray. The fake ores can be told apart from the normal ores only by admins which should see particles around them.

If you could implement any of these, that would be amazing!

**Comment by jiangdashao** [comment]
1: It's a useless feature, I won't add it
2. I can't auto-update the config files without removing their comment lines
3. Please use Spigot/PaperSpigot's built-in Anti-Xray system

**Comment by Germanode** [comment]
2. For people like me, having a config without comments is totally acceptable. You should make it optional if possible. It's annoying as hell to reconfig everytime. Hope you can at least implement that.

**Comment by jiangdashao** [comment]
I didn't change config frequently, and you needn't reconfigure it, you just need to see the file changelog, and modify your old config files

**Comment by Germanode** [comment]
Exactly. Auto-updates would eliminate this step which would be great.
