### ISSUE TITLE
Riptide + Elytra FP

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#59]
## How you trigger the false positive?
Equip elytra and use trident with riptide. While in water, try to shoot out of the water using trident. Occasionally, you'll get slammed into the ground.

## Verbose Message:
https://pastebin.com/00ALiY45

## Videos:
https://youtu.be/o1ZHpmtlJCE

## Server Infomation
**Matrix Version**: 1.6.3
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
