### ISSUE TITLE
[REQUEST]  Prevent WWE "Off Hand Crash"

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#590]
**What features/checks do you need?:**

Check to prevent WWE's "Off Hand Crash"

It causes severe lag and crashes other people's Minecraft Client.

**Comment by jiangdashao** [comment]
What is that?
I didn't see any lag or crash in my test

**Comment by Kruize1** [comment]
You might need to repro it like this:

Get 2 players:

1. Player A , uses WWE Client "Off hand crash" near Player B
2. Observe the result on the normal client for Player B

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/62285769-df838080-b488-11e9-9b25-ae8f461bf3ca.png)
Spigot can block it

**Comment by Kruize1** [comment]
Can you test this with Paper? 

It still occurs for me on 1.14.4 Paper
