### ISSUE TITLE
[FP] Riptide + Rain

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#593]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/4ce8f9f91a4c8480631a63eb633d2f01
**How/when does this happen**: If it's raining, and a player right clicks and releases after 3 seconds a trident with these enchantments, preferably looking upwards:
![imagen](https://user-images.githubusercontent.com/6623704/61998488-2f410100-b0b1-11e9-9dbc-fed6796a358a.png)

**Video of false positive**: https://youtu.be/2a-e2Q2eaOk
**Other information**: Enough is priovided

## Configuration Files
**Link to checks.yml file**: default.
**Link to config.yml file**: default.

**Comment by jiangdashao** [comment]
I can't reproduce it

**Comment by MithrandirCraft** [comment]
What? xD Seriously, it's so easy to reproduce.

Sigh* I'll do it myself again...

**Comment by MithrandirCraft** [comment]
The trident used for reproducing this:
![imagen](https://user-images.githubusercontent.com/6623704/62320860-9be94080-b4a1-11e9-9d41-aaf79e8605e1.png)
Tip: It's easy to reproduce if you continuously attempt at taking off as though you where about to fly from the ground.
Here's a video of me doing this: https://youtu.be/OzAx_lH-bFo

**Comment by jiangdashao** [comment]
The Riptide enchantment can't exist with loyalty enchantment at the same time.

**Comment by MithrandirCraft** [comment]
Item attributes can't exist either, but they're still vanilla.
You want me to do this again without the loyalty enchant? I'm guessing it will be pointless though, it's going to happen anyway.

I can't figure how you can't reproduce something so simple. Can you show me how you do it?

**Comment by jiangdashao** [comment]
I use the /enchant command.
 if you enchanted Riptide III, then I can't enchant the Loyalty III, these enchantments can't exist at the same time.
If I use Anvil, they still can't exist at the same time too.

**Comment by MithrandirCraft** [comment]
*note to self*: Could not reproduce this issue on a clean minecraft server. Will have to do further investigating in main server.
