### ISSUE TITLE
[FP] Dolphin's grace and other casualties

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#594]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/38dca5cc0883bd0b9c2cf3a31784941e
**How/when does this happen**: You need to gain Dolphin's Grace status effect, and swim around water. Players usually get this efect by getting near dolphins in sea water.
![imagen](https://user-images.githubusercontent.com/6623704/61998767-74ffc880-b0b5-11e9-9c4a-9f10581c6996.png)
**Video of false positive**: https://youtu.be/qiIgvDln4kQ
**Other information**: You can trigger false positives like speed, jesus, and even fly by using this. It could get worse if you combine it with conditions such as other status effects like slow fall and item attributes. A cluster of these mentioned conditions being present together which would make this much more triggerable.

## Configuration Files
**Link to checks.yml file**: default.
**Link to config.yml file**: default.

**Comment by jiangdashao** [comment]
I think he is hacking, why he can stand on water?

**Comment by MithrandirCraft** [comment]
@jiangdashao Bare in mind, all my recordings will always be of someone who is playing legally, since it's always a friend of mine.

The reason why he can float on top of water is due to the slowfall potion effect. As mentioned, if you combine multiple elements such as more potion effects, and even item attributes which may modify speed, you can achieve worse effects (like the ones in the video which indeed look like hacking, but are 100% legit vanilla movements) that will obviously trigger your plugin's checks if you do not account for them.

You can actually probably reproduce this even without slowfall, since the speed is so high you can spend a while above seawater from the impulse you get from the dolphin.

So as I say, this is just legit player behaviour, and in the video I can clearly see he isn't even combining it with item attributes, so maybe he didn't even use additional potion effects, just dolphin's grace.

Did you attempt to reproduce this yourself? Else this ticket shouldn't be marked as invalid. I only send you real issues.

**Comment by jiangdashao** [comment]
I saw a "tag: a" information in the verbose message, he sent a moving packet with ground=true in the liquid, why? I just say he is cheating, can you produce this false positive by yourself?

**Comment by MithrandirCraft** [comment]
Well, I can't guarantee 100% he isn't cheating, but I certainly wouldn't say so hahaha.
I'll do it myself, yes.

**Comment by MithrandirCraft** [comment]
This is the trident:
![imagen](https://user-images.githubusercontent.com/6623704/62320674-19608100-b4a1-11e9-9859-8b1cea7c177e.png)
And here's me doing the same exact thing I already showed you on the other video:
https://youtu.be/OzAx_lH-bFo

As a tip, remember it has to be raining, and it's easyer to reproduce if you angle it as though you where about to take off in flight diagonally, as shown on the video.

**Comment by MithrandirCraft** [comment]
Matrix 2.1.0
These are the results of my own research:
All I did was apply the command and then play around in water (I applied the effect directly since I'm bad at getting the dolphins to apply it to me)
`/effect give GiegueGiygas minecraft:dolphins_grace 99999`

Recorded a false positive applying Dolphin's grace, and then moving along the water surface: https://youtu.be/s0Bq-VGYnmk
Here's the logs: https://gist.github.com/MithrandirCraft/9a8680fe697539aef171be321ee9fad4

**Comment by MithrandirCraft** [comment]
Found an extension of this FP. Can you try it out?
Conditions: 
![imagen](https://user-images.githubusercontent.com/6623704/62823525-01b88500-bb92-11e9-8d7c-e8f1b346a56c.png)
![imagen](https://user-images.githubusercontent.com/6623704/62823529-07ae6600-bb92-11e9-8082-4289c6a13a46.png)
![imagen](https://user-images.githubusercontent.com/6623704/62823537-214fad80-bb92-11e9-82d0-ca1f9e3b4570.png)

Video: https://youtu.be/x9DCIule6pw

Logs: (Incomplete sorry)
https://gist.github.com/MithrandirCraft/09c018a325bbb56ba36931d9ea95168b

**Comment by jiangdashao** [comment]
Please open a new issue
