### ISSUE TITLE
[FP / Vanilla incompatibility] Item attributes (Speed modifications)

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#595]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/ff656cb380b02f85479aabf84dcee487
**How/when does this happen**: Using items with item attributes which modify speed, such as following examples:
![imagen](https://user-images.githubusercontent.com/6623704/61998978-6070ff80-b0b8-11e9-977d-a2fb4e767d6b.png)
![imagen](https://user-images.githubusercontent.com/6623704/61998980-67980d80-b0b8-11e9-8057-a90fa7364ea2.png)
**Video of false positive**: https://youtu.be/xjcKEj5byis
**Other information**: Other items with vanilla item attributes may exist which conflict with Matrix checks, I'll attempt at documenting them if detected.

## Configuration Files
**Link to checks.yml file**: default.
**Link to config.yml file**: default.

**Comment by jiangdashao** [comment]
I can't reproduce it....

**Comment by MithrandirCraft** [comment]
Ah yes, sorry for not mentioning this, but the issue probably happens by combining both items.
Ideally you should check for the items the player is holding, or has equipped, and be less lenient with movement speeds in such cases.

**Comment by jiangdashao** [comment]
Yes, I tried a used an item with 2000% speed

**Comment by MithrandirCraft** [comment]
I'll look into it more indepth then.

**Comment by MithrandirCraft** [comment]
Hey. So my moderator commented that you actually need to combine the item attribute with a speed enhancing BEACON, in this case.

That would solve the mistery as to why you can't reproduce it just with item attributes alone.

**Comment by MithrandirCraft** [comment]
?
