### ISSUE TITLE
[FP] Killaura on regular combat

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#596]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/fe562635310caf5e89c9c868bc20e0da
**How/when does this happen**: Not entirely sure, but I think the killaura check is pretty bad right now, since it's detecting just regular pvp's in just a few hits (Even got a report of someone being kicked with just one hit), and also players fighting mobs in a regular fashion.
**Video of false positive**: https://youtu.be/qe5gIX-cgqg
**Other information**: Regular pvp and pve triggers this.

## Configuration Files
**Link to checks.yml file**: default.
**Link to config.yml file**: default.

**Comment by jiangdashao** [comment]
Is it flag on sweep attack?

**Comment by MithrandirCraft** [comment]
It looks like the sweep may have something to do.

**Comment by MithrandirCraft** [comment]
With this sword, which is probably irrelevant because regular pvp is a cluster of false positives whatever you are equiped with (allthough killaura stands out):
![imagen](https://user-images.githubusercontent.com/6623704/62738630-0ca8d380-ba33-11e9-8d81-b545d172a628.png)

During a crowd pvp (video): https://youtu.be/f1WwrgVpRXU

Matrix logs: https://gist.github.com/MithrandirCraft/161154ca3bb1bbf1f04dfc39edf29bf7
(killaura are relevant checks)
