### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by ConnorPed** [jiangdashao/Matrix-Issues#599]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
-[X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.13.2
**Verbose messages**:
Block 
**How/when does this happen**:
Breaking grass triggers the "Block"(FastBreak) check
**Video of false positive**: 
**Other information**: 
I get spammed by this check when someone starts breaking (TALL_GRASS) & (GRASS)

## Configuration Files
https://pastebin.com/416XcmvM (Config)  (I have not changed anything)**: 
https://pastebin.com/13nSVTK9 (Checks)    (I have not changed anything)**:

**Comment by jiangdashao** [comment]
Please provide the verbose message
