### ISSUE TITLE
Problems when flying on the elytra with fireworks or building pillars.

### ISSUE THREAD

**Issue by bloodyearth** [jiangdashao/Matrix-Issues#6]
Hey. I downloaded the latest version of the plugin, but I have some problems with it.

For example, if I use fireworks when flying on the elytra, then after some time I teleport back to the place where I started the flight.

The second problem is that if I build a pillar, then it starts pushing me from it.

However, I do not observe any messages in the chat or console.

**Comment by jiangdashao** [comment]
1.  You should use "/matrix verbose" command to enable the output message
2. Please record a video with the verbose message output enabled to report the false positives, because I can't reproduce the bugs

**Comment by bloodyearth** [comment]
> 1. You should use "/matrix verbose" command to enable the output message
> 2. Please record a video with the verbose message output enabled to report the false positives, because I can't reproduce the bugs

This is when flying on elytra: 
https://ibb.co/2cG2YnK

And this is after teleporting back when flying:
https://ibb.co/Tc18YCg

I'll record the video later, now there is no possibility.

**Comment by bloodyearth** [comment]
This is when building pillars:
https://ibb.co/KLqFnF6

**Comment by jiangdashao** [comment]
The "step-r" and "step-1" false positive should be fixed in the next update.
But the "BadPackets" false positives when flying on elytra was caused by server lagging, you TPS was dropped to 18.x

**Comment by bloodyearth** [comment]
And this can not be fixed?

**Comment by jiangdashao** [comment]
I need some time to improve this check, but not now, because doing a good BadPackets check is very troublesome.

**Comment by bloodyearth** [comment]
okay

**Comment by jiangdashao** [comment]
I developed a new BadPackets check that will be more responsive and less false positives.
You can try it in the next update!!

**Comment by bloodyearth** [comment]
Ok, i try it.
