### ISSUE TITLE
Sprinting up stairs FP

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#60]
## How you trigger the false positive?
Sprint up some stairs

## Verbose Message:
https://pastebin.com/aVwvcK5s

## Videos:
N/A

## Server Infomation
**Matrix Version**: 1.6.3
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by Kyrobi** [comment]
Here's a video showing it in action: https://youtu.be/9CEpNHoElaw

Going down the stairs seems to also trigger fly.

**Comment by Performancee** [comment]
I can personally confirm this isn't invalid; I just reproduced the glitch. Same server information.

Verbose: https://pastebin.com/raw/VctVgKdh
Video: https://youtu.be/5fbrzjwz-VM

**Comment by jiangdashao** [comment]
Can't reproduce speed fp

**Comment by Kyrobi** [comment]
I don't understand. I my production server, on my test server, and on the Matrix test server, I get the same "micro stutter" when sprinting up stairs :/

Here's a video of a longer staircase: https://youtu.be/4qgUfYd9s_8

**Comment by Kyrobi** [comment]
> I can personally confirm this isn't invalid; I just reproduced the glitch. Same server information.
> 
> Verbose: https://pastebin.com/raw/VctVgKdh
> Video: https://youtu.be/5fbrzjwz-VM

If there anyway I can join your test server to test this? Just to make sure I'm not going insane :/

**Comment by jiangdashao** [comment]
![@1{54V~}Q GIUA@@J30}T@6](https://user-images.githubusercontent.com/21152113/54996034-3244bb80-5003-11e9-976b-b1e8efb0063f.png)
I tested, but I can't reproduce FP

**Comment by Kyrobi** [comment]
> ![@1{54V~}Q GIUA@@J30}T@6](https://user-images.githubusercontent.com/21152113/54996034-3244bb80-5003-11e9-976b-b1e8efb0063f.png)
> I tested, but I can't reproduce FP

Huh.. this is so weird. Could I test this on your test server?
