### ISSUE TITLE
[FP] I keep getting false positives for mcmmo.

### ISSUE THREAD

**Issue by FunkyJamma** [jiangdashao/Matrix-Issues#600]
This plugin doesnt seem to be compatible with mcmmo or maybe im misconfiguring it. I also have mcmmo horses in stalled. Things as simple as eating causes the player to get kicked for healing too fast. People get kicked for mining and riding horses as well as placing blocks too fast. 

## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**1.14.4**: 
**Verbose messages**: 
**anytime essentially**: 
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Please provide a video to spoof it, and provide the verbose message so that I can know how it flags you.
