### ISSUE TITLE
[ERROR] Matrix stopped starting

### ISSUE THREAD

**Issue by CeIebrimbor** [jiangdashao/Matrix-Issues#603]
The plugin stopped starting some time ago. Given the nature of the error message, I highly doubt it's config related.

## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [No Config Error] The issue happens on default config.yml and checks.yml
- [No Config Error] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-151 (MC: 1.14.4)
**Error(s) found in console**: https://pastebin.com/LthYabvh
**How/when does this happen**: Server Startup
**Other information**: ProtocolLib v4.5.0-SNAPSHOT

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/imaGGFdG
**Link to config.yml file**: https://pastebin.com/xbteA6gk

**Comment by ZakShearman** [comment]
Did this happen after updating the plugin, or just started happening 'randomly' as such after use.

**Comment by CeIebrimbor** [comment]
I'll be honest, the plugin stopped starting about 2 weeks ago around about the time 1.14.4 was being released. I haven't looked into the error until today as it was just a testing environment at the time.

I do not know if the same issue occurred on 2.0.7 or 1.14.3. The plugin definitely functioned as intended weeks ago.

**Comment by SugarD-x** [comment]
I'm having the same issue on Spigot 1.14.4 with the same version of ProtocolLib. I can also confirm the 1.14.4 update is when it stopped working for me too. Spigot reports the following error for it:
"[Server] Server thread/ERROR Error occurred while enabling Matrix v2.0.8 (Is it up to date?)"

It looks like a 1.14.4 incompatibility issue to me.

**Comment by jiangdashao** [comment]
Most NullPointerException errors at starting were caused by outdated config files, did you try to start with default config files?

**Comment by CeIebrimbor** [comment]
I update the config based on the revisions link. If you see an error in my config, please advise.

If it were a config error, it would print a YamlConfiguration error with a string position.

**Comment by jiangdashao** [comment]
If you miss a config section, you will not get a YamlConfiguration error, but a NullPointerException, I did some test in 1.14 yesterday, it works fine with the default configuration.

According to the error, an error occurred while reading your **checks.yml**. You can try backing it up and then use the default configuration file.

**Comment by CeIebrimbor** [comment]
Will do. At some point xD

**Comment by jiangdashao** [comment]
I saw the mistake
"hitbox.commands", you used "[]", it's wrong

**Comment by jiangdashao** [comment]
You can change it to "{}"

**Comment by CeIebrimbor** [comment]
Oh you rock!

*_slides into shadows_
