### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by salikaaa** [jiangdashao/Matrix-Issues#604]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.14.4
**Error(s) found in console**: [16:43:15] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Matrix v2.0.8
**How/when does this happen**: player join and random time.
**Other information**: nothing

## Configuration Files
**Link to checks.yml file**: https://shrib.com/#2Dpi4X5teiYcGX-H17LO
**Link to config.yml file**: https://shrib.com/#5YP4q5o-R-.k1xOFqlBi

**Comment by jiangdashao** [comment]
Did you try to use the default config files?

**Comment by ignPerformance** [comment]
He did test it @jiangdashao - it doesn't happen. His config is the issue it seems.
