### ISSUE TITLE
[REQUEST] Add MythicMobs compatibility

### ISSUE THREAD

**Issue by Zaino60** [jiangdashao/Matrix-Issues#606]
**What features/checks do you need?:**
Add MythicMobs compatibility so mobs/items skills don't falsely trigger the anti cheat. https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
55k downloads + API available

**Comment by jiangdashao** [comment]
There is no anti-cheat compatible with this plugin, and please provide more incompatible information, like which skills cause some false flags, also, you need to record a video for it

**Comment by Zaino60** [comment]
From what I noticed, happens with skills related to movement. This one specifically: 
  - pull{velocity=6} @PIR{r=60}
Example vid reproducing the false positive: https://gyazo.com/280657fecb04bac57760c6a22ed23a5f (the lackback happens when the mob uses the pull skill)

**Comment by jiangdashao** [comment]
Please provide the verbose message
