### ISSUE TITLE
[FP] Fly

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#608]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: Stand on the edge of a slime block pushed by a piston
**Video of false positive**: https://zak.pink/matrix-fly-1.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by ZakShearman** [comment]
This issue has not been fixed in the 2.1.0 version. Please re open this.

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/62408393-14afe000-b5fb-11e9-9cf8-96ee73841c32.png)
weird

**Comment by ZakShearman** [comment]
Try 1.8.8 client and 1.8.8 server and see if you can do it then. I'll try again in a moment as well as reset all Matrix files on the test server.

**Comment by jiangdashao** [comment]
Yes, I tried 1.8.8

**Comment by ZakShearman** [comment]
Ok, resetting Matrix on the test server now.

**Comment by ZakShearman** [comment]
Yep, still happens and you will be able to see at http://zak.pink/matrix/more-fly.mp4 in around 2 minutes from now. Feel free to try it on the test server if you wish.

PLs: https://zak.pink/19-08-11-54-47_1538.png
Specific Server Version: https://zak.pink/19-08-11-54-59_1539.png
Client Version: 1.8.9
