### ISSUE TITLE
[BYPASS] Vanila Fly

### ISSUE THREAD

**Issue by NikeSchuh** [jiangdashao/Matrix-Issues#609]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config
- [X] I've checked that my Server is running on 1.8 1.12 1.13 or 1.14

## Issue Information
**Server version**: 1.13.2
**Hacked client**: Aristois
**Link to hacked client**: https://aristois.net/
**Cheat that bypassed**:  Fly
**Video of bypass**: https://youtu.be/kVt_W5tWCOI
**Other information**: If you get Damaged somehow you can Bypass mostly everything

## Configuration Files
**Link to checks.yml file**https://pastebin.com/i7yNGwae 
**Link to config.yml file**: https://pastebin.com/jdL8cF5V
Note that i have updated Matrix after putting the config on pastebin. But the Bypass is still the same as before.

**Comment by jiangdashao** [comment]
I guess you removed the kick command to produce this bypass, I won't fix this bypass currently, because it's not important and hard to fix.

**Comment by NikeSchuh** [comment]
Yeah, cause when i put the kick command in there it just spits a error in the console from the kick plugin
