### ISSUE TITLE
Gamemode Change Fly False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#61]
## How you trigger the false positive?
Go into creative mode, fly fast and quickly switch to survival mode.

## Verbose Message:
https://pastebin.com/raw/abZypma0

## Videos:
https://youtu.be/P3WIyv4H-Hw

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Paper version git-Paper-605, 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed

**Comment by ignPerformance** [comment]
Reopened, still working.

**Comment by jiangdashao** [comment]
hard to reproduce, won't fix it
