### ISSUE TITLE
Fause possitive illegal interaction with block hoppers.

### ISSUE THREAD

**Issue by Smartjer123** [jiangdashao/Matrix-Issues#611]
Someone tried to use a hopper and it detected them

**Comment by jiangdashao** [comment]
Please use our issue template, and provide information about this issue, like video and verbose message

**Comment by Smartjer123** [comment]
Sorry i didnt see it because i used an app. The guy that got banned said that he just holded his mouse button and it did it. When i get the time i will try to reproduce it
