### ISSUE TITLE
[BYPASS] NoWeb

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#614]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**:  1.12.2
**Hacked client**: LB b2 (1.12.2)
**Link to hacked client**: https://liquidbounce.net/
**Cheat that bypassed**: NoWeb
**Video of bypass**: https://youtu.be/G8HUhYQF_fY
**Other information**: ???

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/62419539-f7d7e300-b6b4-11e9-8813-775ac849dc28.png)
