### ISSUE TITLE
[FP] Glitching doors

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#617]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: You can manage to spam and glitch doors, which therefore means you will get flagged and kicked.
**Video of false positive**: https://zak.pink/matrix/2019-08-04-15-34-21.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Is there any "move wrongly" in the console?

**Comment by ZakShearman** [comment]
Yes. Presuming this is more of a MC issue then.

**Comment by jiangdashao** [comment]
¯\_(ツ)_/¯
So I can't help that
