### ISSUE TITLE
False Positives Jesus and timings

### ISSUE THREAD

**Issue by Retrumek** [jiangdashao/Matrix-Issues#62]
## Server Infomation
**Matrix Version**: latest
**Server Version**: 1.8.8
**ProtocolLib Version**: 4.2.0

![jesus](https://user-images.githubusercontent.com/28825502/54982172-748dde80-4faa-11e9-8a22-73b8cf6fa8ca.png)
![matrix](https://user-images.githubusercontent.com/28825502/54982173-748dde80-4faa-11e9-9fad-6e5c8fad0aea.png)

**Comment by jiangdashao** [comment]
Can you give me the class names with performance problems in plain text?

**Comment by jiangdashao** [comment]
And you should provide a video that how you trigger the false positives
