### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by Waterman1001** [jiangdashao/Matrix-Issues#621]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.14
**Verbose messages**: 
(02:10:42) JellepelleFast failed Jesus check | liquid speed | 0.217 >- 0.21 | d: false (+3) | vl:3 ping:53 tps:20.0 component: jesus.speed.in
(02:10:42) JellepelleFast failed Jesus check | liquid speed | 0.194 >- 0.12 | d: false (+3) | vl:6 ping:53 tps:20.0 component: jesus.speed.in
(02:10:42) JellepelleFast failed Jesus check | liquid speed | 0.172 >- 0.12 | d: false (+3) | vl:9 ping:53 tps:20.0 component: jesus.speed.in
(02:10:42) JellepelleFast failed Jesus check | liquid speed | 0.151 >- 0.12 | d: false (+3) | vl:12 ping:53 tps:20.0 component: jesus.speed.in
(02:10:42) JellepelleFast failed Jesus check | liquid speed | 0.13 >- 0.12 | d: false (+3) | vl:15 ping:53 tps:20.0 component: jesus.speed.in
(02:10:43) JellepelleFast failed Jesus check | liquid speed | 0.123 >- 0.12 | d: false (+3) | vl:18 ping:53 tps:20.0 component: jesus.speed.in
(02:10:43) JellepelleFast failed Jesus check | liquid speed | 0.13 >- 0.12 | d: false (+3) | vl:21 ping:53 tps:20.0 component: jesus.speed.in
(02:10:43) JellepelleFast failed Jesus check | liquid speed | 0.136 >- 0.12 | d: false (+3) | vl:24 ping:53 tps:20.0 component: jesus.speed.in
(02:10:43) JellepelleFast failed Jesus check | liquid speed | 0.142 >- 0.12 | d: false (+3) | vl:27 ping:53 tps:20.0 component: jesus.speed.in
**How/when does this happen**: It happends when sprinting under water / killing a mob under water.
**Other information**: You get kicked for jesus check, while you're not even on the water, but litteraly inside it / under the water.

**Comment by jiangdashao** [comment]
You should provide a video to show how to reproduce it

**Comment by Waterman1001** [comment]
Okay, Thanks for you reply.
I will do this soon.

**Comment by ZakShearman** [comment]
Any update on the video?
