### ISSUE TITLE
[FP] Elytra stutter

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#623]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/a4a969c6ac7f0cf72204c945545d05e7
**How/when does this happen**: Flying fast with elytra's + rockets for extra speed
**Video of false positive**: https://youtu.be/SqyJ6x5SQQM
**Other information**: You can appreciate stuttering twice in the video. The flight momentum stops completely, and errors show up close to the moment the movement is halted.

## Configuration Files
**Link to checks.yml file**: default.
**Link to config.yml file**: default.

**Comment by jiangdashao** [comment]
I'm sorry, but I can't improve the Elytra check at the moment because the work of the elytra is strange and hard to predict.

**Comment by MithrandirCraft** [comment]
I guess you can't simply be less lenient when elitras are equiped? Or make it configurable?
