### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by leshacoplays** [jiangdashao/Matrix-Issues#626]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.14.4
**Verbose messages**: 
![image](https://user-images.githubusercontent.com/34228146/62791095-0c760a00-baff-11e9-8c90-0d6b7ba61a72.png)

**How/when does this happen**: I gave a group a permission to change gamemode to spectate only but matrix detects it as a cheat.
**Video of false positive**:  https://youtu.be/LCjFqYgx22g
**Other information**: Players can't use Spectate properly the keep changing into survival after nocliping in the under ground and takes damage.

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
1: Please provide a video
2: We need verbose messages, not just flags. Use /matrix verbose.

**Comment by leshacoplays** [comment]
> 1: Please provide a video
> 2: We need verbose messages, not just flags. Use /matrix verbose.
i'm sorry im done editing my ticket, Thanks!
