### ISSUE TITLE
[BYPASS] Killaura and AntiKnockBack

### ISSUE THREAD

**Issue by Davidmayr** [jiangdashao/Matrix-Issues#628]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [yes] Matrix and ProtocolLib are up-to-date
- [yes] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [yes] The issue happens on default config.yml and checks.yml
- [yes] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.3
**Hacked client**: Aristois
**Link to hacked client**: https://aristois.net/download
**Cheat that bypassed**: Killaura and AntiKnockBack
**Video of bypass**: https://www.youtube.com/watch?v=N7GtT22QGJM&feature=youtu.be
**Other information**: Changed no configs just defaults(In the anticheat and in the hacked client)

## Configuration Files
**Link to checks.yml file**: IS DEFAULT
**Link to config.yml file**: IS DEFAULT

**Comment by ZakShearman** [comment]
Can you make sure that you do not have any bypass permission (matrix.bypass or op). Let me know if you don't.

**Comment by Davidmayr** [comment]
no the player doesnt have permissions! Other hacks get flaged and the hacker gets kicked! @ZakShearman
