### ISSUE TITLE
[ERROR] Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#629]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Error(s) found in console**: https://gist.github.com/MithrandirCraft/8769fbb44ec8fa391fe00f8d047a15d0
**How/when does this happen**: Random
**Other information**: I just found it on console, thought it may be relevant to you. It's not causing any performance or gameplay issues for what I can gather.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
I don't know why this error happens, and I don't know which code causes this error, because I lost the obfuscation log....
Maybe you should wait for the next version to know why the error happens
