### ISSUE TITLE
Boat Issue (and not on ice this time)

### ISSUE THREAD

**Issue by RainbowTea** [jiangdashao/Matrix-Issues#63]
## How you trigger the false positive?
Player using boat on  ground /slabs with a villager as the passenger, and when they move it keeps booting them. And not on just ice this time. They are moving very slowly aswell. 

## Verbose Message:
No messsage, just boots them from the boat

## Videos:
no video

## Server Infomation
**Matrix Version**:  (1.6.5)
**Server Version**: This server is running Paper version git-Paper-572 (MC: 1.13.2)
**ProtocolLib Version**: 4.4.0
config:
https://pastebin.com/sBRNs8tx

**Comment by Performancee** [comment]
I am unable to reproduce this.
Same server information.
Video: https://1drv.ms/u/s!ApY4tKsF8vPUge8MiJixgyaHFF2mNQ

**Comment by RainbowTea** [comment]
I'll try and record it, but it definitely happens only when i have this plugin installed. 
When i disable the speedcheck, boat issue is gone.

**Comment by jiangdashao** [comment]
Fixed
