### ISSUE TITLE
[ERROR] Hitbox error on player hit

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#634]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Error(s) found in console**: https://pastebin.com/WEDSh4KF
**How/when does this happen**: https://www.zak.pink/matrix/console-error-hitbox-spam_new.mp4
**Other information**: On the test server, all files were reset after the update (https://zak.pink/19-08-14-41-22_1656.png)

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Caused by Citizens compatibility, I will release a hotfix soon

**Comment by ZakShearman** [comment]
Ok, thanks.
