### ISSUE TITLE
Matrix "Internal error" Task 74

### ISSUE THREAD

**Issue by Challenger8168** [jiangdashao/Matrix-Issues#643]
`Server thread/WARN [Matrix] Task #74 for Matrix v2.2.0 generated an exception
12.08 05:47:30 [Server] INFO java.lang.NullPointerException: null
12.08 05:47:30 [Server] INFO at me.rerere.matrix.iiIiiIIIiI.run(vd) ~[?:?]
12.08 05:47:30 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:30 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:30 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:30 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:30 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:31 [Multicraft] Skipped 170 lines due to rate limit (30/s)
12.08 05:47:31 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 05:47:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191-1-ojdkbuild]`

I have Matrix and Horizon installed, because Matrix seems to, whatever I do, not stop or punish cheaters, but Horizon does, but Horizon has bad killaura checks, so I got matrix. But now, Matrix broke, and Horizon with it

**Comment by jiangdashao** [comment]
You can try to use Matrix without Horizon

**Comment by Challenger8168** [comment]
But could you please tell me how I can make matrix use the punishments I set in the config?
(I had to make it a txt file because yml isnt supported by github

[checks.txt](https://github.com/jiangdashao/Matrix-Issues/files/3491782/checks.txt)

**Comment by Challenger8168** [comment]
And matrix without horizon works

**Comment by jiangdashao** [comment]
What?

**Comment by Challenger8168** [comment]
What do you mean with what?

**Comment by Challenger8168** [comment]
`12.08 06:00:08 [Server] Server thread/WARN [Matrix] Task #72 for Matrix v2.2.0 generated an exception
12.08 06:00:08 [Server] INFO java.lang.NullPointerException: null
12.08 06:00:08 [Server] INFO at me.rerere.matrix.iiIiiIIIiI.run(vd) ~[?:?]
12.08 06:00:08 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
12.08 06:00:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191-1-ojdkbuild]`

I am now getting spammed by it

**Comment by jiangdashao** [comment]
Do you run  it with Horizon?

**Comment by Challenger8168** [comment]
I also get an internal error if I use /matrix verbose

But I cant show you the error since multicraft has a rate limit

**Comment by Challenger8168** [comment]
yes, I have now removed Horizon and launched the server with Matrix only

**Comment by jiangdashao** [comment]
What's your ProtocolLib version?

**Comment by Challenger8168** [comment]
![image](https://user-images.githubusercontent.com/30499120/62857970-54f91780-bcf9-11e9-8158-d196cfae028d.png)

**Comment by jiangdashao** [comment]
Try update it to 4.5.0

**Comment by Challenger8168** [comment]
I do not see 4.5.0 on the spigot, and the dev build doesnt show a version. Im installing the latest dev build right now...

**Comment by Challenger8168** [comment]
Okay, I installed 4.5.0 Snapshot, but i didnt help.
Now, even the base command /matrix gives an internal error

**Comment by jiangdashao** [comment]
What spigot are you using?
/ver

**Comment by Challenger8168** [comment]
![image](https://user-images.githubusercontent.com/30499120/62866975-787c8c00-bd12-11e9-9fdf-4bc01a868aa2.png)
I am now using Nocheatplus fork for 1.14.3
