### ISSUE TITLE
[FP] Phase False Flag

### ISSUE THREAD

**Issue by coolpvpv** [jiangdashao/Matrix-Issues#646]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: CraftBukkit version git-Spigot-e5b1b5d-e5e8eec (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Verbose messages: Watch the video
How/when does this happen: When you Try to pearl through fences or fence gates
Video of false positive: https://streamable.com/5jllb
Other information: idk

Configuration Files
Link to checks.yml file: its the default config but i removed the bypass permissions so i could see alerts
Link to config.yml file: its the default config but i removed the bypass permissions so i could see alerts

**Comment by jiangdashao** [comment]
It's not false positive, I think it should be blocked
