### ISSUE TITLE
[FP] Players can see KillAura bot

### ISSUE THREAD

**Issue by hs-rendov** [jiangdashao/Matrix-Issues#649]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-166 (MC: 1.14.4) 
**Verbose messages**: -
**How/when does this happen**: -
**Video of false positive**: https://cdn.discordapp.com/attachments/331379605728657408/610770644166115329/7013-7088.mp4
**Other information**: Matrix AntiCheat (2.2.2) Model: (6)

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Firstly: The video shows nothing
Secondly: We need verbose messages if there is a false positive.

**Comment by ZakShearman** [comment]
Oh wait, I see now. It's coz u put this under false positive 🤦‍♂.

**Comment by ZakShearman** [comment]
If you want, you can disable the NPC killaura checks in the checks.yml file. You could also make it so that it is only spawned by a command.

**Comment by jiangdashao** [comment]
I will add an option to make bot invisible in next update ^^
