### ISSUE TITLE
[FP] Autoclicker confused with Killaura

### ISSUE THREAD

**Issue by ZandercraftGames** [jiangdashao/Matrix-Issues#652]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper version git-Paper-166 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Verbose messages**: `ZandercraftGames failed KillAura check | auto clicker | cps | cps: 53 | var: 3 (+4) | vl:12 ping: 6 tps:20.0 component: ka.autoclicker.cps`
**How/when does this happen**: When using an autoclicker at an interval of 4ms.
**Other information**: The system kicks the user for Killaura and posts a message warning of the user using KillAura (`[Matrix] ZandercraftGames might be using combat hacks (KillAura)
[Matrix] ZandercraftGames is using combat hacks (KillAura) #2
ZandercraftGames lost connection: [Matrix] KillAura`) when the user is using an autoclicker.

**Comment by jiangdashao** [comment]
AutoClicker is a part of KillAura check ^^
