### ISSUE TITLE
[FP] AntiKnockback is undetected

### ISSUE THREAD

**Issue by mlegok** [jiangdashao/Matrix-Issues#653]
Paper last version 1.14.4
Matrix Last version!
Hi! I get no verbose from the anticheat on antiknockback issue. It doesn't detect and kick player.
https://www.youtube.com/watch?v=b3UyFVmQjOc&feature=youtu.be

**Comment by ZakShearman** [comment]
Please submit this again under the correct category (bypass) and then give the rest of the information.

**Comment by jiangdashao** [comment]
Because the player is standing on the Snow, Matrix only detect when the player not in a block
