### ISSUE TITLE
Recode the Hitbox/Reach check | Constant false flags, has been for ages

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#654]
Hi there,

I'm requesting this because there have for a long time been constant issues with being kicked that have not been fixed for ages, and they were not fixed in the last version when I re reported them all.

I have done some testing again, and the below 3 videos show how fast I can get kicked when not using any illegal modifications.

Combo: https://www.zak.pink/matrix/hitbox-false-flag-combo.mp4
GApple: https://www.zak.pink/matrix/hitbox-false-flag-gapple.mp4
NoDebuff: https://www.zak.pink/matrix/hitbox-false-flag-nodebuff.mp4

All default configs, no KB modification or anything like that, latest versions of plugins. Thanks to the people that have helped me test combat in the past as well.

**Comment by ZakShearman** [comment]
Adding my videos from the previous version:

https://www.zak.pink/matrix/ka-false-1-compressed.mp4
https://www.zak.pink/matrix/ka-false-2-compressed.mp4
https://www.zak.pink/matrix/ka-false-3-compressed.mp4
https://www.zak.pink/matrix/ka-false-4-compressed.mp4

**Comment by coolpvpv1** [comment]
> Adding my videos from the previous version:
> 
> https://www.zak.pink/matrix/ka-false-1-compressed.mp4
> https://www.zak.pink/matrix/ka-false-2-compressed.mp4
> https://www.zak.pink/matrix/ka-false-3-compressed.mp4
> https://www.zak.pink/matrix/ka-false-4-compressed.mp4
> 
> (I've throttles back my compression since these videos, so the ones that are in the submission above are of higher quality.)

server ip?

**Comment by ZakShearman** [comment]
It's a test server.

**Comment by coolpvpv1** [comment]
> It's a test server.

oh ok
