### ISSUE TITLE
[REQUEST] Add PaperSpigot Support

### ISSUE THREAD

**Issue by pabloalba16** [jiangdashao/Matrix-Issues#656]
**What features/checks do you need?:**
Professional servers are running paperspigot because of the optimization and the stability. My server is PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar and i cant run Matrix seems that is working but it doesnt check anything. I hope you can make it running without problems in Paper to put it again on my server :D

**Comment by jiangdashao** [comment]
Matrix support PaperSpigot
Did you install ProtocolLib?
