### ISSUE TITLE
[FP]  Anticheat doesn't detect AntiKnockback

### ISSUE THREAD

**Issue by mlegok** [jiangdashao/Matrix-Issues#657]
Paper 1.14.4 last version
Matrix last version
https://www.youtube.com/watch?v=TTxfFdufheM

**Comment by jiangdashao** [comment]
Please tell me what hack client are he using?

**Comment by mlegok** [comment]
Aristoris

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/63238603-cdbc1e80-c279-11e9-93f2-2e2c812ae7a6.png)
It was detected, you can set velocity.modules.delay's vl weight higher
