### ISSUE TITLE
NPC'S are visible to non-cheaters.

### ISSUE THREAD

**Issue by Nikita11790** [jiangdashao/Matrix-Issues#658]
After the new update **all** of my players are complaining that they see random flying players after they kill animals. here is a video 

https://streamable.com/1cnm9

please fix. for the time being we need to switch to a older version

**Comment by ZakShearman** [comment]
Please check previous issues. There will be an invisible option added, but do note, they are supposed to be visible to non cheaters by default.

PS, you can just disable the NPC check in the checks file for now
