### ISSUE TITLE
Jumping on ladders is "flying"[FP] 

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#659]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X ] The issue happens on default config.yml and checks.yml
- [ X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper spigot 1.13.2
**Verbose messages**: <name> failed Fly check / suspicious movement:-0.005 predict:0.037 air_t:12 tag:ff1 (+10) / vl:10 ping:22 tps: 19.15 component: fly.fastfall
**How/when does this happen**: If you try to jump to a block that has a ladder on it (during parkour when you have to jump and hold shift on the ladder block), it will TP you back and the false positive will occur
**Video of false positive**: 
**Other information**: You can see the setup of what I mean here https://gyazo.com/2dbaed2ea49bfe4a48c24d35ce1d9c13

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/vwBSLpqy
**Link to config.yml file**: https://pastebin.com/sx9gCjsc

**Comment by jiangdashao** [comment]
Please the newest version, the fly.fastfall has been removed
