### ISSUE TITLE
Players take damage when i have this plugin installed

### ISSUE THREAD

**Issue by RainbowTea** [jiangdashao/Matrix-Issues#66]
I know this isn't a false positive but i honestly dont know how else to report this.

I'm really diligent on any issue on my server, and i noticed ever since the last few updates of matrix, when my players walk, or even just jump they take damage.  My players are also very diligent on reporting any issues too, and it ONLY happens when i have this plugin enabled, i disable it, the  damage taken is gone, i add it back its back.

What players will report: "pawh3/26/2019, 7:12:18 PM
Just leaving this here so someone knows but i was playing and every time i would jump i took half a heart of dmg. I could move around and break things but if i jumped i lost half a heart. relogging fixed it but not sure if it was a bug or something so just thought i leave a message about it"

Username - StarLily16
Time Stamp - 2:50 AM PST
Issue - Glitching into blocks and taking damage every few seconds. Cant jump up onto a block without taking damage. Died once due to said issues, but was able to retrieve all of my items.
What were you doing? - Building at my base and walking by blocks

At first i thought it was a paper issue, so  i updated paper, issue persisted, then i disabled  this plugin completely, and the issue stopped.

Matrix Version: (1.6.5)
Server Version: This server is running Paper version git-Paper-572 (MC: 1.13.2)
ProtocolLib Version: 4.4.0
config:
https://pastebin.com/sBRNs8tx

**Comment by Performancee** [comment]
Enable verbose.

**Comment by RainbowTea** [comment]
> Enable verbose and put your verbose messages in pastebin. Find this in Matrix logs.

Where do i enable verbose?

**Comment by RainbowTea** [comment]
Why was this closed? the issue isn't resolved at all yet, this should be left open till i can provide a video or more information.
