### ISSUE TITLE
[REQUEST] Check version command

### ISSUE THREAD

**Issue by xtomyserrax** [jiangdashao/Matrix-Issues#660]
It would be really useful to have a /matrix info or /matrix version command so we can check the plugin's version.

In networks this is handy as sometimes plugins get outdated in some servers and staff can use this command in order to check and help preventing this.

This is a really small feature request but it would be amazing. Thanks!

**Comment by jiangdashao** [comment]
1. You can see the current plugin version by using the command: /matrix or /ver Matrix
2. The plugin will auto-check update when the server starting
