### ISSUE TITLE
[FP] Killaura False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#661]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: CraftBukkit version git-Spigot-e5b1b5d-e5e8eec (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Verbose messages: Watch the video
How/when does this happen: i was just pvping and moving my head up and down and it falses killaura
Video of false positive: https://streamable.com/2wl7c
Other information: idk

Configuration Files
Link to checks.yml file: its the default config but with the bypass permission off so i can see alerts
Link to config.yml file: its the default config but with the bypass permission off so i can see alerts

**Comment by jiangdashao** [comment]
Did you see the reporting rule?
![image](https://user-images.githubusercontent.com/21152113/63219659-0b04ab80-c1a9-11e9-802f-a44a12439475.png)
ka.pitch check player's head up and down when they fighting, it can help detect some "random aim center" killaura, and do you think the legit player will move their head up and down when fighting? I think not...

**Comment by jiangdashao** [comment]
If you don't want this check, you can disable it in checks.yml
set "killaura.modules.pitch.enable" to false
