### ISSUE TITLE
[FP] Levitation

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#666]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.14 paper-162
**Verbose messages**: In the video
**How/when does this happen**: Fly into a slab after being hit by a shulker
**Video of false positive**: https://www.youtube.com/watch?v=JI7jC69zjXU
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by nicknitewolf** [comment]
Can confirm. Happens on upside-down stairs as well
