### ISSUE TITLE
[FP] Killaura And Velocity False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#667]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: craftbukkit 1.8.8
Verbose messages: Watch the video
How/when does this happen: i was just pvping with like 11-15 cps normally NOT trying to false it i think i was falsing velocity cause i had high cps sense you get kinda less kb when you get high cps
Video of false positive: https://streamable.com/tswsw
Other information: this was on the ac.zakshearman.com test server

Configuration Files
Link to checks.yml file: idk 
Link to config.yml file: idk

**Comment by ZakShearman** [comment]
To add - (haven't watched the video), config files are all default on the test server :D.

**Comment by jiangdashao** [comment]
I think I have said it **many times**, and some false flags are normal, especially the KillAura check.
KillAura detection works fine on many servers, including my server.
^^
