### ISSUE TITLE
False Speed and Fly Positives with Riptide 3 Trident 

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#67]
## How you trigger the false positive?
1. Enable /matrix verbose
2. Ensure it's raining
3. Ensure you have a Trident with Riptide 3 enchant
4. Hold Right Click and release
5. Repeat step #3 multiple times, horizontally across the the ground
6. Observe Verbose Logs

## Verbose Message:
https://media.discordapp.net/attachments/392906483735592962/560185519108259860/unknown.png?width=400&height=229

https://media.discordapp.net/attachments/392906483735592962/560185809823858689/unknown.png?width=400&height=27

## Videos:
https://clips.twitch.tv/FragileFlaccidMooseAMPEnergy

## Server Information
**Matrix Version**: 1.7.0
**Server Version**:  Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Can not reproduce those exact verbose flags. However, I did flag Fly t:step-2 multiple times while Riptiding horizontally.

**Comment by jiangdashao** [comment]
Can't reproduce

**Comment by Kruize1** [comment]
Please re-open. I attached a video.
