### ISSUE TITLE
[FP] Bunch of random Fly, Speed, BadPackets

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#672]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12 , 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**:  This server is running Paper version git-Paper-c66f02b1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Verbose messages**: Look at vids

**Video of false positive**: 
https://streamable.com/nj201
https://streamable.com/bf841
https://streamable.com/9pki2
https://streamable.com/sfr3i
https://streamable.com/ouhbh
https://streamable.com/mzvtu
https://streamable.com/4vuc9
https://streamable.com/fg00y
https://streamable.com/ogpj0
https://streamable.com/s4qxi
https://streamable.com/rbml5
https://streamable.com/y2jgw
https://streamable.com/kndlw
https://streamable.com/zxapj

**Other information**: 
~ 120 players was on this server

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
it looks like most false flags caused by “timer patterm”

**Comment by jiangdashao** [comment]
the timer pattern will be removed
