### ISSUE TITLE
[FP] Matrix Killaura 检测误报

### ISSUE THREAD

**Issue by bow9500** [jiangdashao/Matrix-Issues#675]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot-1.8.8
**Verbose messages**: ![image](https://user-images.githubusercontent.com/49287036/63452000-daa66100-c477-11e9-98dc-86a155885970.png)
**How/when does this happen**: In the StrikePractice robot training mode, there are a lot of false positives. When you comb the robots, killaura will generate a lot of false positives, htibox also has a small number of false positives. Below I give the Matrix logs. （Player KamioMisuzu Sdetection is false positive）
**Video of false positive**: 无
**Other information**: 
[matrix_log_2019-08-22.txt](https://github.com/jiangdashao/Matrix-Issues/files/3526444/matrix_log_2019-08-22.txt)

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
1. 你需要录制视频说明
2. 请在真实环境下测试，而不是打Bot，并且不能刻意去触发误判
