### ISSUE TITLE
Stop the NPCS spawning for killaura[REQUEST] 

### ISSUE THREAD

**Issue by JHarris12345** [jiangdashao/Matrix-Issues#676]
**What features/checks do you need?:**
The new check for killaura making that ghost NPC behind you is VERY annoying and horrible for PvP servers. How do we disable that all together and what is the point of it?

**Comment by ZakShearman** [comment]
Take a read of the checks configuration file and search for 'NPC'. There is an option to disable it.

**Comment by jiangdashao** [comment]
set "killaura.modules.npc.enable" to false
