### ISSUE TITLE
False Positives for Elytra flying with fireworks

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#68]
## How you trigger the false positive?
1. Ensure /matrix verbose is enabled
2. Ensure you have Elytra and 64 Firework Rockets
3. Fly with Elytra
4. Use Fireworks to boost you upwards
5. At the highest point of ascension, point 45 degrees upwards, and use a Firework to boost yourself
6. Observe Verbose logs

## Verbose Message:
https://media.discordapp.net/attachments/392906483735592962/560189058492399651/unknown.png?width=400&height=224

## Videos:
https://clips.twitch.tv/TsundereEvilParrotPrimeMe

## Server Infomation
**Matrix Version**: 1.7.0
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Can't reproduce, please provide an video

**Comment by Kruize1** [comment]
Video has been attached. Please re-open issue for investigation.
