### ISSUE TITLE
[FP] Jesus

### ISSUE THREAD

**Issue by FendiTony777** [jiangdashao/Matrix-Issues#682]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  PaperMC-1.12.2
**Verbose messages**:  See image.
**How/when does this happen**: When swimming in water.
**Video of false positive**: ![image](https://i.imgur.com/QbemGEf.png)
**Other information**: Jesus false kicks,

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Can you provide a video to show how to reproduce it?
