### ISSUE TITLE
[FP] Velocity False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#686]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.8.8 i think idk
Verbose messages: Watch the video
How/when does this happen: just normal pvp with 11-15 cps
Video of false positive: https://streamable.com/8007g
Other information: this was on the official test server ac.zakshearman.com

Configuration Files
Link to checks.yml file: default
Link to config.yml file: default

**Comment by ZakShearman** [comment]
#683 happens in lots of scenarios.

**Comment by coolpvpv1** [comment]
> #683 happens in lots of scenarios.

ye

**Comment by ZakShearman** [comment]
This is a different module to what was removed because of mine, so let's see.
