### ISSUE TITLE
[BYPASS] KillAura

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#692]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 paper-175
**Hacked client**: WWE
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: KillAura
**Video of bypass**: https://www.youtube.com/watch?v=0VCUGG7KC-Y
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by OstojaTheGamer** [comment]
Is `disable_bypass_permission` set to true? Because anti cheat ignores opped players.

**Comment by Kuraky** [comment]
Well, the answer is in the video 
![obraz](https://user-images.githubusercontent.com/38810662/63862221-884fcd80-c9ac-11e9-8813-076f53073c1c.png)

**Comment by OstojaTheGamer** [comment]
> Well, the answer is in the video
> ![obraz](https://user-images.githubusercontent.com/38810662/63862221-884fcd80-c9ac-11e9-8813-076f53073c1c.png)

Yes it still gives an output in verbose even if you are opped but can you try deopping yourself and running KillAura test again?

**Comment by Kuraky** [comment]
It gives no verbose message if you have the matrix.bypass permission.

**Comment by ZakShearman** [comment]
@OstojaTheGamer they are right, you are ignored from checks completely if you have the bypass permission. There will be no verbose at all if you bypass.

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/64113871-0d2c5400-cdbe-11e9-9000-213d24e9677c.png)
Not an important bypass
