### ISSUE TITLE
[FP] Report False Positives with Coral

### ISSUE THREAD

**Issue by Cyanoure** [jiangdashao/Matrix-Issues#693]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date (Matrix 2.2.4 and ProtocolLib 4.5.0-SNAPSHOT)
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server (1.14.4)
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 (git-Paper-167)
**Verbose messages**: [Matrix] _PLAYERNAME_ is phase into block (Phase)
**How/when does this happen**: When a player is going into any type of coral
**Video of false positive**: 
**Other information**: Sorry for my English. :P

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/vA8PUw3k
**Link to config.yml file**: https://pastebin.com/D9MG5qMC

**Comment by ZakShearman** [comment]
Most likely not needed, but it's best to provide verbose messages (/matrix verbose).

**Comment by Cyanoure** [comment]
![image](https://user-images.githubusercontent.com/30216303/63639607-af995880-c695-11e9-9409-2f0a2ecae8ee.png)
When I'm added the coral into 'exclude_types', requires restart, or reload is enough?

**Comment by Cyanoure** [comment]
![image](https://user-images.githubusercontent.com/30216303/63639636-099a1e00-c696-11e9-9efc-3b8adb1d3548.png)
sorry :'D

**Comment by Cyanoure** [comment]
But I don't know what is this fly message...

**Comment by Cyanoure** [comment]
I think the fly message is the WorldGuard's entry deny flag.
