### ISSUE TITLE
[REQUEST] [Bug?] Matrix.Bypass update delay

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#694]
**What features/checks do you need?:**

Alright so when one is given the Matrix.Bypass permission, it generally takes a solid 15 seconds before Matrix stops flagging the user. And if you are removing the node it also takes a solid 15 seconds before matrix starts flagging the user again.

This is a small issue, but still. Not sure if I should report but reported just in case.

**Comment by ZakShearman** [comment]
This is with all permission nodes BTW, I presume that RE just has it scheduled to only update every period of time.

**Comment by jiangdashao** [comment]
You can use MatrixAPI.reloadPermissionCache(); to refresh permission immediately

**Comment by ZakShearman** [comment]
*creates a runnable to run every 10 ticks and destroys server performance*
