### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by lukeeexd** [jiangdashao/Matrix-Issues#698]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: https://streamable.com/1lvrf
**How/when does this happen**: running in a tunnel
**Video of false positive**: https://streamable.com/1lvrf
**Other information**: 

## Configuration Files
**Link to checks.yml file**: Premium checks
**Link to config.yml file**: https://hastebin.com/kovuboxaza.shell

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [ ]  The issue happens on default config.yml and checks.yml
> * [ ]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: 1.14.4
> **Verbose messages**: https://streamable.com/1lvrf
> **How/when does this happen**: running in a tunnel
> **Video of false positive**: https://streamable.com/1lvrf
> **Other information**:
> 
> ## Configuration Files
> **Link to checks.yml file**: Premium checks
> **Link to config.yml file**: https://hastebin.com/kovuboxaza.shell

??? that dude looks like hes sneaking while running and half of the check boxes aren't filled so its either a hacker the anticheats fault or your config

**Comment by jiangdashao** [comment]
The guy is using noslow hack, closed this issue
