### ISSUE TITLE
Attacked by Mobs False Positive [Velocity]

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#70]
## How you trigger the false positive?
Get attacked by mobs (Zombies, Phantoms, etc.) without attacking first.

## Videos:
https://clips.twitch.tv/ThirstyOpenWrenPrimeMe
https://1drv.ms/v/s!ApY4tKsF8vPUgohXnv-XYgsQinIDpg

## Server Infomation
**Matrix Version**: 1.8.2
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Check the bug in next update, if it still works, set air to false

**Comment by ignPerformance** [comment]
I can personally reproduce this. Uploading video sometime tomorrow.

**Comment by ignPerformance** [comment]
Still able to reproduce.

**Comment by ignPerformance** [comment]
Video: https://1drv.ms/v/s!ApY4tKsF8vPUgohXnv-XYgsQinIDpg

**Comment by jiangdashao** [comment]
It seems to have happened only at 1.13.
