### ISSUE TITLE
[BYPASS] Interact attack

### ISSUE THREAD

**Issue by Kuraky** [jiangdashao/Matrix-Issues#707]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 paper-175
**Hacked client**: WWE
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: Hitbox/Attacking entity through a block
**Video of bypass**: https://www.youtube.com/watch?v=z9EBF_rrQHI
**Other information**: none

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by OstojaTheGamer** [comment]
Just like your last post. Is `disable_bypass_permission` set to true in the config? Anti cheat ignores opped players and by default `disable_bypass_permission` is set to false.

**Comment by Kuraky** [comment]
Just like in my last post, the answer is in the video. I've got flagged 3 or 4 times.

**Comment by jiangdashao** [comment]
At present, Matrix can only detect people who are really behind the wall, not this situation. And, I don't have a better algorithm to detect WallHit, ignore it for now.
