### ISSUE TITLE
[BYPASS] Entity speed with skeleton horse still possible

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#709]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
1.14.4
aristosis
**Link to hacked client**: 
entityspeed
https://www.youtube.com/watch?v=2el8cF3ru3w&feature=youtu.be
You patched _zombie horse_ speed which is great but you forgot about _skeleton horses!_ 
thanks. :)

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by OstojaTheGamer** [comment]
Can you provide link to checks.yml and config.yml if you modified them or you haven't modified them at all? Another thing if `disable_bypass_permission` is set to false in config.yml which is by default and you are opped on server then Anti cheat will ignore opped players.

**Comment by ZakShearman** [comment]
No need to provide the checks file as they listed as default. However, RE already indicated they'll patch this 💜.
