### ISSUE TITLE
False detection when a player gets on a horse

### ISSUE THREAD

**Issue by snake0053** [jiangdashao/Matrix-Issues#71]
## How you trigger the false positive?
Matrix detects Speed ​​when the player gets on the horse.
And let the player off the horse.

## Verbose Message:
failed Speed check | entity speed | type: horse | distance: 0.5033620946474692 (+1) | vl:1 ping:769 tps:20.0
failed Fly check | t:e m=0.0 tk=11 et=5 vy=-0.0784000015258789 (+1) | vl:1 ping:769 tps:20.0

## Videos:
No Video

## Server Infomation
**Matrix Version**:1.7.1
**Server Version**:git-Paper-561
**ProtocolLib Version**:4.4.0

**Comment by jiangdashao** [comment]
How he get detected?

**Comment by snake0053** [comment]
Matrix detected Speed ​​when the player moved on a horse.
The player was kicked when trying to ride continuously.

**Comment by jiangdashao** [comment]
So, I need to know how player trigger the false positive
Please provide an video
