### ISSUE TITLE
[FP] jesus

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#713]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Verbose messages**:  
**How/when does this happen**: 
**Video of false positive**: https://www.youtube.com/watch?v=aMGB27quJ7U
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Default configuration?

**Comment by tiktonik114** [comment]
**Link to checks.yml file**:  https://pastebin.com/rEFegkqM
**Link to config.yml file**: https://pastebin.com/MbS2iTHd
