### ISSUE TITLE
[BYPASS] fly #2

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#715]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: wwe
**Link to hacked client**: I can not find the official site
**Cheat that bypassed**:  http://prntscr.com/oz31jo
**Video of bypass**:   https://youtu.be/15sNcsjgECU
**Other information**: matrix no detect (straight at all), but the kernel itself detects (http://prntscr.com/oz362b), but I turned it off, because there are false positives

## Configuration Files
**Link to checks.yml file**:  https://pastebin.com/rEFegkqM
**Link to config.yml file**: https://pastebin.com/MbS2iTHd

**Comment by jiangdashao** [comment]
The BadPackets doesn't detect it?

**Comment by tiktonik114** [comment]
no
