### ISSUE TITLE
[INCOMPATIBILITY] Doublejump

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#718]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.8.8
Verbose messages: Watch the video
How/when does this happen: when i was double jumping around i was falsing fly
Video of false positive: https://streamable.com/bpxd3
Other information: link to plugin https://www.spigotmc.org/resources/doublejump.70272/ so if this was on a popular server with alot of people the alerts and logs file would be spammed with false flags

Configuration Files
Link to checks.yml file: default
Link to config.yml file: deault

**Comment by jiangdashao** [comment]
Can't add support this plugin, it's dangerous for matrix, the player can fly when they have blocks under their foot, so they can bypass the fly&speed check when they on the ground, it would cause many bypasses.

Also, a lobby server shouldn't install Matrix or an anticheat

![image](https://user-images.githubusercontent.com/21152113/64062754-880a3900-cc1d-11e9-9bbf-46cac1323268.png)
