### ISSUE TITLE
[FALSE POSITIVES] Command blocks

### ISSUE THREAD

**Issue by VirxEC** [jiangdashao/Matrix-Issues#719]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.14.4
**Verbose messages**: Fly hacks with tp, it depends
**How/when does this happen**: When an admin places command blocks to tp players high up, or at least that's what I got the error with

## Configuration Files
**Link to checks.yml file**: It's the default config
**Link to config.yml file**:  It's the default config

**Comment by ZakShearman** [comment]
We need verbose messages or at least a video please (/matrix verbose).

**Comment by VirxEC** [comment]
btw I was messing with a friend on the same server and we got false positives from just vanilla. Like about break and noslow warnings. Here's a link to the log: https://mclo.gs/QrnEp9t Hope that's what u need!

**Comment by ZakShearman** [comment]
We need the output of /matrix verbose.

**Comment by VirxEC** [comment]
They're in there. I turned it on. Just look

**Comment by ZakShearman** [comment]
Alerts and verbose are not the same. We need the verbose output specifically.

You could send a screenshot from in game, a recording from in game or just your matrix logs file for that session.

**Comment by VirxEC** [comment]
Ok sorry about that. Here: https://pastebin.com/6Cn3Lqyt VirxEC is me testing command block tp with a non-op survival player, and Microlax is my friend just playing in vanilla.

**Comment by jiangdashao** [comment]
Minecraft only support 4096 blocks height
