### ISSUE TITLE
[FP] Hello! My friend recently installed this plugin on his server, and minutes later I got on a horse and the plugin accused me of being "flying", I got a ban on that. Thanks!

### ISSUE THREAD

**Issue by SirFlankBoring** [jiangdashao/Matrix-Issues#720]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
You didn't provide any evidence
such as video/verbose messages
