### ISSUE TITLE
[FALSE POSITIVE] Anti-Knockback

### ISSUE THREAD

**Issue by Unsalt** [jiangdashao/Matrix-Issues#724]
Here's the video showing a player taking knockback but still getting flagged by the anticheat.
https://youtu.be/51keRhOOF_w

**Comment by SkylixMC** [comment]
You did not follow the false positive format and include needed information making it very hard for the dev to exactly pin down this issue :/

(PS, some hacks hack a knock back resistance and don't 100% negate knockback but reduce it)

Just saying.
