### ISSUE TITLE
[BYPASS] [REQUEST] Timer, FastBreak, Inventory++

### ISSUE THREAD

**Issue by NgLoader** [jiangdashao/Matrix-Issues#725]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.14.4-R0.1
**Hacked client**: Arisois
**Link to hacked client**: https://aristois.net
**Cheat that bypassed**: Inventory++, Timer, FastBreak, AntiSlowDown
**Video of bypass**: https://www.youtube.com/watch?v=oNP5-MPaiuA&t=1s
**information** AntiSlowDown will not get blocked on blocks like soulsand (even with a ice block below)

## Configuration Files
**Link to checks.yml file**: DEFAULT
**Link to config.yml file**: DEFAULT

**Comment by jiangdashao** [comment]
There is no Inventory++ check, it also won't add
