### ISSUE TITLE
[BYPASS] Speed/Jesus on Impact 1.14.4 works with leaping/speed potions/effects active.

### ISSUE THREAD

**Issue by SlickJava** [jiangdashao/Matrix-Issues#726]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.14.4 build 176
**Hacked client**: Impact 1.14.4
**Link to hacked client**: https://impactclient.net/
**Cheat that bypassed**: Speed, Jesus, Speed in water
**Video of bypass**: Don't have currently.
**Other information**: Pretty self-explanatory, thanks for your hard work on matrix btw it's really such a good ac.

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
You should provide verbose spoof

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/64075412-8a869480-ccea-11e9-8c85-5e349261b570.png)
