### ISSUE TITLE
Tnt pryamid 

### ISSUE THREAD

**Issue by mirko0** [jiangdashao/Matrix-Issues#73]
##Triggering
Player is placed at top of a pyramid of tnt then when you light it up it explodes and launches him in sky. Then matrix sends player name and telling us he is using fly hacks, also you can spam /nuke and launch player using that it will also tell that player is using fly hacks. Fireball cmd will also launch players sometimes and send fly hack notification, but with tnt its sending it every time.

## Verbose Message:
![image](https://user-images.githubusercontent.com/45130689/55281960-85887800-533b-11e9-8beb-ac9096e355d7.png)

## Videos:
https://i.imgur.com/4uX6dgK.gifv

## Server Infomation
**Matrix Version**: 1.7.3
**Server Version**: 1.12.2 paperspigot
**ProtocolLib Version**:  4.4.0

**Comment by jiangdashao** [comment]
It just flag, not very important
