### ISSUE TITLE
[FP] Scaffolding FP when placing trapdoors

### ISSUE THREAD

**Issue by northerncarrots** [jiangdashao/Matrix-Issues#730]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**:
```
>.... [16:12:45 INFO]: [Matrix] Rice_Trap tried to bridge blocks quickly (Scaffold)
>.... [16:12:45 INFO]: [Carrot Guardian] Rice_Trap tried to bridge blocks quickly (Scaffold) #2
```
**How/when does this happen**: Place down trap doors
**Video of false positive**: [Video of a player](https://streamable.com/bs296)
**Other information**: Scaffolding check was disabled in this video

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by ZakShearman** [comment]
Don't think we'll need it here - but for future the Verbose messages are what is outputted with `/matrix verbose`.

**Comment by jiangdashao** [comment]
provide  verbose message pls

**Comment by northerncarrots** [comment]
```(16:04:10) Rice_Trap failed Scaffold check | direction: 3.606 (+4) | vl:4 ping:64 tps:20.0 component: block.scaffold.dir
(16:04:10) Rice_Trap failed Scaffold check | direction: 3.606 (+4) | vl:8 ping:64 tps:20.0 component: block.scaffold.dir
(16:04:10) Rice_Trap failed Scaffold check | direction: 3.606 (+4) | vl:12 ping:64 tps:20.0 component: block.scaffold.dir
(16:04:10) Rice_Trap failed Scaffold check | direction: 3.606 (+4) | vl:16 ping:64 tps:20.0 component: block.scaffold.dir
(16:04:11) Rice_Trap failed Scaffold check | direction: 3.606 (+4) | vl:20 ping:64 tps:20.0 component: block.scaffold.dir
(16:04:13) Rice_Trap failed Scaffold check | direction: 4.472 (+4) | vl:24 ping:64 tps:20.0 component: block.scaffold.dir```
