### ISSUE TITLE
[FP] Blue ice boat highway flags vehicle cheat. 

### ISSUE THREAD

**Issue by SlickJava** [jiangdashao/Matrix-Issues#732]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper build 180 1.14.4
**Verbose messages**: https://imgur.com/a/yu2sEex
**How/when does this happen**: 1/09/2019 i'm kidding, read below
**Video of false positive**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
@SlickJava please fill out the report properly. We need to know how to reproduce this, and a video would be extremely useful.

**Comment by SlickJava** [comment]
I'll try add a video later, but i'll explain the reproduction in words for now.

Place blue ice in a row in a 3 wide area like in the screenshot, one block apart from each other. Place slabs around the ice.
Place a boat and row it onto the ice, then try rowing around. You get teleported off the boat.
This is a well known vanilla form of transport.

It doesn't take long before it starts flagging and kicking you off the boat.
example:
https://imgur.com/a/hBaQ2ks

**Comment by coolpvpv1** [comment]
> @SlickJava please fill out the report properly. We need to know how to reproduce this, and a video would be extremely useful.

its basically a copy of my old issue with the blue ice boat thing

**Comment by SlickJava** [comment]
> > @SlickJava please fill out the report properly. We need to know how to reproduce this, and a video would be extremely useful.
> 
> its basically a copy of my old issue with the blue ice boat thing

i'm sure they'll get to fixing it
