### ISSUE TITLE
[FP] Eat berries on low health while climbing a vine

### ISSUE THREAD

**Issue by VirxEC** [jiangdashao/Matrix-Issues#737]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.144
**Verbose messages**: VirxEC failed FastHeal check | regen health too fast | difficulty: 3 delay: 278 protocol_ver: 14 (+2) | vl:2 ping:117 tps:20.0 component: heal
**How/when does this happen**: It happend to me when I was eating berries on low health while climbing a vine
**Video of false positive**: None...
**Other information**: None...

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
not a false positive

**Comment by VirxEC** [comment]
How? I was in vanilla mc!

**Comment by VirxEC** [comment]
That IS a false positive!

**Comment by jiangdashao** [comment]
it's just a flag, it's normal.

**Comment by VirxEC** [comment]
but it stops u from gaining health, which can be really bad in pvp

**Comment by jiangdashao** [comment]
it's rare, ignore it
