### ISSUE TITLE
KillAura and hitbox coming up when hiting players bottom hitbox

### ISSUE THREAD

**Issue by mirko0** [jiangdashao/Matrix-Issues#74]
## How you trigger the false positive?
The issue is triggered when you hit "the feet", the bottom of hitbox, in video i placed the player on 3 blocks higher then me, and when i hit him it sent an killaura and hitbox notification.

## Verbose Message:
![image](https://user-images.githubusercontent.com/45130689/55282085-4fe48e80-533d-11e9-9785-619e45fff056.png)

## Videos:
https://i.imgur.com/ENQfT8v.gifv

## Server Infomation
**Matrix Version**: 1.7.3
**Server Version**: 1.12.2 PAPERSPIGOT
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
