### ISSUE TITLE
[ERROR] Cloud Error Thrown on Startup

### ISSUE THREAD

**Issue by zachrocks22** [jiangdashao/Matrix-Issues#741]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Error(s) found in console**: https://pastebin.com/raw/dB4gZWtf
**How/when does this happen**: It happens a few minutes after the initial server startup.
**Other information**: Using Latest Paper Spigot. All configuration options/settings are still default. I also tried restarting the server to see if it would fix it, but to no avail.

## Configuration Files
**All files were left as default.**

**Comment by jiangdashao** [comment]
You can disable cloud service in config.yml
