### ISSUE TITLE
[BYPASS] NoSlow

### ISSUE THREAD

**Issue by Unsalt** [jiangdashao/Matrix-Issues#742]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.8.8
**Hacked client**: Jigsaw 1.8.8
**Link to hacked client**: 
**Cheat that bypassed**: NoSlow
**Video of bypass**: https://youtu.be/AgU-fFsa1wI
**Other information**: NoSlow blocks running while pulling back bow, but not blocking of swords. Player does not have bypass permission.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
Are you sure player is actually blocking? Can you open another client to see if it's a real blocking?

**Comment by Unsalt** [comment]
Just checked, it's actually blocking.

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/64262961-7a2c1f00-cf61-11e9-865d-2feaacab3b62.png)

detected, not bypass
