### ISSUE TITLE
flux b13 is OP than speed control of Matrix

### ISSUE THREAD

**Issue by leoncp9** [jiangdashao/Matrix-Issues#743]
flux b13
can bypass speed check with slowhop2 hack
server version paper 1.14.4

**Comment by leoncp9** [comment]
just try the hack and you will see the bypass, so i don't need to give more proof

**Comment by SkylixMC** [comment]
Follow the proper format and you will save the dev a lot of work <3

**Comment by leoncp9** [comment]
what? is not my problem, i can continue bypass matrix with speed, not problem for me, bye

**Comment by ZakShearman** [comment]
Have fun then. No need to be so derogatory... it's literally a free plugin lol.

**Comment by jiangdashao** [comment]
OP?
LOL, please go to some anticheat test servers to test it
it is slower than legit
