### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#749]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
[close] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: https://gist.github.com/MithrandirCraft/23c08d1ca261515484b6ff4a6a620f29
**How/when does this happen**: Often when building for those with the item.
**Video of false positive**: https://youtu.be/qNv_HtGPxNo
**Other information**: 
- You must have these attributes applied (speed only I'd say)
![imagen](https://user-images.githubusercontent.com/6623704/64269547-573a4480-cf3a-11e9-864c-3a2d3fdb4b40.png)
- You must crouch to appreciate the damage effect
- You can do this by pillaring upwards while crowching, or just building sideways.
- I know I must update the plugin. But I fear the newer updates xD
I think this is probably still going to be reproducable in the two newest versions.
## Configuration Files
**Link to checks.yml file**: https://gist.github.com/MithrandirCraft/a1ee0a11437c97a5c2153e14215cdfcf
**Link to config.yml file**: https://gist.github.com/MithrandirCraft/d12324f5241582014009d42a0a2942cc

**Comment by jiangdashao** [comment]
1. Don't use outdated version to report bugs
2. Please enable verbose message out when you recording the video
