### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by ImKingEz** [jiangdashao/Matrix-Issues#750]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Spigot 1.8.8
**Verbose messages**: watch the video
**How/when does this happen**: watch the video
**Video of false positive**: https://youtu.be/W2voyXIP9xo
**Other information**: 1st FP is caused by bow enchanted by punch; 2nd FP is caused when a player use STap in PvP (sorry for bad english).

## Configuration Files
**Link to checks.yml file**: https://www.mediafire.com/file/enoc97bkcrxq5r7/checks.yml/file
**Link to config.yml file**: https://www.mediafire.com/file/1g2w9n98gp46td5/config.yml/file

**Comment by jiangdashao** [comment]
1. It's not important enough to get fix
2. I will try to fix that
