### ISSUE TITLE
[Request] Better TPS Protection

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#751]
**What features/checks do you need?:**
I am requesting an upgrade to the TPS protection systems. Currently, if "tps_protection" is set to true, and the server tps drops below the configured amount, some checks are disabled. I am requesting the ability to disable ALL checks when the server TPS drops below the configured amount to:
1) Help lighten the server load by disabling Matrix temporarily
2) Completely eliminate false positives and save legit players a lot of trouble

The reason I am requesting this is because I think in laggy situations, not only this could reduce the load on the server but also eliminate false positives. False positives especially for server owners who chose to use matrix to autoban people can be dangerous!

In a situation where the server TPS is really suffering, as someone who helps run a server myself, in laggy situations where the TPS is low, people cheating is second priority to making sure the server performance is restored. After all, a laggy server effects EVERYONE where a hacker may only effect certain players.

**Comment by jiangdashao** [comment]
1. Matrix won't eat too much resource, even when the server is lag. Disable Matrix won't help anything
2. If disable Matrix entirely, hackers will able to teleport/crash server/fly/speed/etc
