### ISSUE TITLE
[FP] HitBox FP

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#752]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: (In the video below)
**How/when does this happen**: Whenever a player is moving side by side (yaw) to quickly during PvP, it causes a hitbox false positive for "hitting targets not in view". It appears matrix doesn't update where the player is looking quick enough.
**Video of false positive**: https://youtu.be/YjIzSxU7I98
**Other information**: PvP situations like that have caused the hitbox check to false flag a lot of my players for hitting targets not in view.
## Configuration Files
**Link to checks.yml file**: https://pastebin.com/xFMB9GeZ
**Link to config.yml file**: https://pastebin.com/K3eBpbnK

**Comment by jiangdashao** [comment]
can't fix that
