### ISSUE TITLE
[FP] Small Block Fly FP

### ISSUE THREAD

**Issue by northerncarrots** [jiangdashao/Matrix-Issues#755]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: Not retrievable at this time
**How/when does this happen**: Hold W against a block and jump while still holding W. Make sure there is a cake (or any block with a similar wideness) and another block three spots above the initial block.
**Video of false positive**: https://streamable.com/i7vif
**Other information**: Not too important. Friend flagged this while watching a video on the side. Tested successfully with cake, turtle eggs, chest, trapped chest, ender chest.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
aha?
I don't think it's a false positive. Ignore it
