### ISSUE TITLE
[ERROR] matrix is deadlocking the server

### ISSUE THREAD

**Issue by Lusteroth** [jiangdashao/Matrix-Issues#756]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 (Paper 186)
**Error(s) found in console**: https://pastebin.com/92AvZ1zY
**How/when does this happen**: Often after teleporting to a position (/p h ; PlotSquared)
**Other information**: https://github.com/PaperMC/Paper/issues/2537

## Configuration Files
**Link to checks.yml file**: -
**Link to config.yml file**: -

**Comment by jiangdashao** [comment]
Did you 2.3.5? Please try it

**Comment by Lusteroth** [comment]
Did you fix the cause of the error in 2.3.5? Because my server crashed eight times yesterday and I don't want that again...

**Comment by jiangdashao** [comment]
Not sure if this is caused by Matrix, because there is no other people report this bug

**Comment by Lusteroth** [comment]
Me: "Is there a way to help the developer of matrix? Maybe tell him what he needs to change?"

Answer: "They need to read the API spec and stop accessing stuff async"

My server just crashed using version 2.3.5...

**Comment by SkylixMC** [comment]
Try 2.2.8 to see if your performance issues still exist. Ive actually also been having performace related issues when 60+ players are on.

**Comment by Lusteroth** [comment]
Thanks for your suggestion @SkylixMC. Unfortunately the server crahes with version 2.2.8 too.
