### ISSUE TITLE
[Question] ProtocolLib 4.5.0?

### ISSUE THREAD

**Issue by VirxEC** [jiangdashao/Matrix-Issues#757]
I can't find ProtocolLib 4.5.0. The spigot and bukkit posts are only on 4.4.0. The github page has only release 4.4.0. How can you have 4.5.0?

**Comment by Kuraky** [comment]
The link is on ProtocolLib's Spigot page. Although it's described as "latest dev build" and not actually "version 4.5.0" which is probably why you were unable to find it.
![obraz](https://user-images.githubusercontent.com/38810662/64370649-2d0e8280-d01f-11e9-8bdb-5ba886bdd0a6.png)

**Comment by VirxEC** [comment]
Thanks!
