### ISSUE TITLE
[FP] Cobweb Fast Break w/ Sword 2.3.5

### ISSUE THREAD

**Issue by Busted11290** [jiangdashao/Matrix-Issues#758]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.14.4
**Verbose messages**:  
![firefox_FKxpdlbBj9](https://user-images.githubusercontent.com/14338718/64404158-0107f700-d049-11e9-92fe-6fd96f1f86f3.png)

**How/when does this happen**:  Player breaks cobwebs with sword.  Tested with an enchanted diamond sword and it was fine.  Tested with normal iron sword and it was the above messages.  Had a player get kicked multiple times also using an iron sword on them.
**Video of false positive**:  No video but can repeat this and get one for you if you really need it.
**Other information**:   The verbose screenshot doesn't show me getting kicked because I stopped before it kicked.  But it will kick you.  Tested on my live server and on localhost.

## Configuration Files
**Link to checks.yml file**:  DEFAULT fresh install
**Link to config.yml file**:  DEFAULT fresh install

**Comment by ZakShearman** [comment]
Did you update to the latest version of the Anti Cheat (#753).

**Comment by Busted11290** [comment]
Yes, I updated to the latest build, 2.3.5.  Which is why I thought it odd when a player was suddenly getting kicked for it.  Then I tested it myself and had the same happen.  I will get a video of it to show, give me a few minutes.

**Comment by Busted11290** [comment]
Live server - https://youtu.be/NZzII_0mgDQ
Test Server - https://youtu.be/06p-wuNvt9M

**Comment by northerncarrots** [comment]
Can confirm this is still present in 2.3.5.
