### ISSUE TITLE
[FP] Pillar Fly PF

### ISSUE THREAD

**Issue by northerncarrots** [jiangdashao/Matrix-Issues#759]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: [Various messages](https://hastebin.com/edaveqomun.sql)
**How/when does this happen**: Build up using 1x1 tower. Break down once out of blocks.
**Video of false positive**: https://streamable.com/vwdn6
**Other information**: Player will receive tons of fall damage building upwards (can be around 5 hearts of higher even with Protection IV armor on) and downwards (player dies as shown in the video)

Player will gather more fall damage as they build higher. Once they stop and hit the ground, they will receive fall damage. The player will earn more damaged based on how high they built up without stopping.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Busted11290** [comment]
Just tested this on my server, confirming it here as well.  1.14.4 Paper 186, updated Matrix and Protocol, default configs.
