### ISSUE TITLE
False Positive when moving forward on a Horse with Saddle

### ISSUE THREAD

**Issue by Kruize1** [jiangdashao/Matrix-Issues#76]
## How you trigger the false positive?
1. Ensure you have a Saddle and tame a wild hose (Not a Horse from Creative Mode Spawn Egg)
2. After taming the Horse, place the Saddle on the Horse
3. Enable Matrix Verbose
4. Ride Horse, and attempt to walk forward (W key) (Please note: A, S, D, walking backwards or to the side with a Horse will not trigger false positives, only walking forward.)  

## Verbose Message:
![image](https://user-images.githubusercontent.com/21042824/55286349-6eec1c00-534f-11e9-828c-83c5ec72a9b4.png)

## Videos:
https://clips.twitch.tv/DeadInnocentStarTebowing

## Server Information
**Matrix Version**: 1.7.4
**Server Version**: Spigot 1.13.2
**ProtocolLib Version**:  4.4.0

**Comment by jiangdashao** [comment]
Fixed
