### ISSUE TITLE
[FP] Velocity False Flag And Some Killaura Falses (again lmao)

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#762]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: idk
Verbose messages: Watch the video
How/when does this happen: click 11-15 cps and fight a player with it and you will false killaura and velocity (nvm you can false velocity with 5-6 cps to lmao)
Video of false positive: https://streamable.com/r1wjl
Other information: please fix the velocity and killaura checks instead of being like oh not important and how is it normal for your aura check to false? its expose to get only aura hackers and your saying it normally falses like wtf?? and this was on the official test server and im clearly being forced by someone to make bad reviews on spigotmc lmao if your anticheat didn't false litterally just by normally pvping i would put a normal good review but thats not the case is it

Configuration Files
Link to checks.yml file: default
Link to config.yml file: default

**Comment by jiangdashao** [comment]
1. Most people's cps can't higher than 15, so the default max_cps configuration is 15, you can modify it in checks.yml
2. Ye, the velocity.horizon check is bad now, I will fix it in next update
