### ISSUE TITLE
[REQUEST] OldCombatMechanics

### ISSUE THREAD

**Issue by NikV2** [jiangdashao/Matrix-Issues#763]
**What features/checks do you need?:**
I would love to see an option in the config that hooks into OldCombatMechanics
Most servers already run OldCombatMechanics nowdays
And since this is one IF NOT the best free Anti-Cheating plugin out there
I'd love to see availability for this plugin. I believe it'd help a lot of users out there including myself !
OldCombatMechanics basically reduces the time needed for each Hit to be casted. Meaning most anti cheats Have issues with a few KillAura checks.
Here's the plugin:
https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/

**Comment by jiangdashao** [comment]
I didnt get any false positive when I test, it is compatible
