### ISSUE TITLE
[FP] PvP Tests - Velocity

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#766]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: Normal PvP fights
**Video of false positive**: https://zak.pink/matrix/matrix%20velocity%20false%20flag.mp4
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: default (just reset)
**Link to config.yml file**: default (just reset)

**Comment by jiangdashao** [comment]
Do you have speed potion effect when you testing?

**Comment by ZakShearman** [comment]
Yes, speed 2

**Comment by ZakShearman** [comment]
I believe that you sent me a message on Discord, but I am currently unable to repond. I will be able to when I am home.
