### ISSUE TITLE
[FP] PvP Tests - Killaura

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#767]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: Normal PvP fights
**Video of false positive**: http://zak.pink/matrix/matrix%20killaura%20false%20flag.mp4
**Other information**: N/A

## Configuration Files
**Link to checks.yml file**: default (just reset)
**Link to config.yml file**: default (just reset)

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [x]  The issue happens on default config.yml and checks.yml
> * [x]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: 1.8.8
> **Verbose messages**: In Video
> **How/when does this happen**: Normal PvP fights
> **Video of false positive**: http://zak.pink/matrix/matrix%20killaura%20false%20flag.mp4
> **Other information**: N/A
> 
> ## Configuration Files
> **Link to checks.yml file**: default (just reset)
> **Link to config.yml file**: default (just reset)

whats the ip to that practice server

**Comment by ZakShearman** [comment]
This is a different test server that I use to test this kind of thing once in a while.

**Comment by ZakShearman** [comment]
I may be adding a practice pvp to the test server in the future, but that would be once I've finished my practice core.

**Comment by jiangdashao** [comment]
it looks like ka.ab check causes this issue
