### ISSUE TITLE
[BUG] Incorrect TPS?

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#768]
BUG DESCRIPTION:

Frequently, the TPS number in verbose shows up as wrong number (often saying a TPS like 20). Im not sure if this is a delay in updating (but our server usually only stays at a TPS of around 19.92 and doesn't really hit 20 TPS unless like no one is on).

I THINK this might be a bug. Im reporting it to be safe. Here is a screenshot.

![2019-08-31_14 45 04](https://user-images.githubusercontent.com/34877092/64567956-7a446a00-d327-11e9-946b-29476f53b8d7.png)

**Comment by ZakShearman** [comment]
_Joke: If your server runs at 20TPS you will never have this issue :D_

**Comment by jiangdashao** [comment]
it is normal, Matrix calculate TPS by itself, it didn't use servers' TPS data
