### ISSUE TITLE
False positive speed

### ISSUE THREAD

**Issue by kawa196** [jiangdashao/Matrix-Issues#77]
## Verbose Message:
videos

## Videos:
https://www.youtube.com/watch?v=TSzLpzAa19U&feature=youtu.be
https://www.youtube.com/watch?v=0Q_W_k6CpNA&feature=youtu.be

## Server Infomation
**Matrix Version**: 1.7.4
**Server Version**: 1.8.8 + viaversion support 1.12.2
**ProtocolLib Version**: 4.4.0

**Comment by TerriblePanda** [comment]
Matrix的作者难逃一劫
