### ISSUE TITLE
[REQUEST] GhostHand / Interact

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#770]
**What features/checks do you need?:**

Allow us to not block interaction through blocks. Why?

Well, currently, the check is only good for blocking hacks. Not detecting hacks. Im suggesting allowing us a configurable option to disable the canceling. This way, if someone does manage to access a chest through blocks they will build up a higher violation and get punished.

For example, look at the video below. I am not able to build up any VL to become questionable. And as a hacker, I will stop trying after seeing it doesn't work the first few times. As a moderator, when staff can see from their eyes someone is using ghost hand, they are much more easily to catch and ban.

https://youtu.be/Fftbb6sTcyo

Currently, we can't punish those with low VLs because there are occasional falses with this check (especially when someone quickly turns a corner and accesses a chest).

**Comment by jiangdashao** [comment]
No, the Interact check is mainly designed for canceling cheats, as you said, Interact checks occasionally cause false flags. Also, the interact SHOULD block cheat, because it's easy to detect/block.
