### ISSUE TITLE
[ERROR] Spigot 1.14.4 Error

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#778]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.14.4 
Error(s) found in console: 
How/when does this happen: i actually dont know i was just testing matrix anticheat for like 1 hour then i decided to randomly look in the console and i just saw matrix completely spamming me with errors in the console heres the logs https://pastebin.com/pbdQ4mqR
Other information: idk how this happened just randomly looked at console and saw it spamming errors

Configuration Files
Link to checks.yml file: default
Link to config.yml file:  default

**Comment by jiangdashao** [comment]
Update your ProtocolLib to 4.5.0
