### ISSUE TITLE
[Incompatibility] GadgetsMenu (found more falses)

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#779]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.14.4
Incompatible plugin: GadgetsMenu link is https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-14-4.10885/
Verbose messages (or) console errors: watch the video
How/when does this happen: when you use the diving board gadget and trampoline gadget you will false fly when you use it and sometimes on the diving board you will false velocity but not that much
Video of incompatibility: https://streamable.com/plnx8 (found another false) https://streamable.com/a03x1
Other information: idk

Configuration Files
Link to checks.yml file: default
Link to config.yml file: default

**Comment by jiangdashao** [comment]
It's not a compatibility issue, Matrix can't predict y-axis movement when the player starts to fall down if they have high-velocity.

**Comment by jiangdashao** [comment]
I will fix it if I find a way to predict it correctly.
Anyway, I suggest you don't use GMenu and Matrix at the same time

**Comment by jiangdashao** [comment]
LOL, found a special way to fix it
