### ISSUE TITLE
[FP] Switching gamemode FP

### ISSUE THREAD

**Issue by SkylixMC** [jiangdashao/Matrix-Issues#784]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In the video below
**How/when does this happen**: Occasionally when switching from spectator mode to survival / adventure, a flight.main event is triggered. In my example video, I am aware the violation is still very low, but occasionally, multiple violations are triggered at once enough to raise the VL significantly. This false positive is significant because moderators switching gamemodes after watching a rule breaker can falsely be flagged.
**Video of false positive**: https://youtu.be/ntlLWhBjlGM
**Other information**: None

## Configuration Files
Link to checks.yml file: https://pastebin.com/24HhXPBU
Link to config.yml file: https://pastebin.com/cGbN72Us

**Comment by jiangdashao** [comment]
false-positive = you get drag back or kicked
