### ISSUE TITLE
[REQUEST] KillAura NPC Invisibility

### ISSUE THREAD

**Issue by NikV2** [jiangdashao/Matrix-Issues#788]
**What features/checks do you need?:**
The current option of Visible = False
in the config doesn't seem to work
The player is still able to see the NPC behind him
I'd like to see an option where you could maybe add the Invisibility effect to the NPC

**Comment by jiangdashao** [comment]
Server Version?

**Comment by NikV2** [comment]
1.13.2

**Comment by JaroSound** [comment]
same problem on 1.12.2

**Comment by NikV2** [comment]
^^
