### ISSUE TITLE
[ERROR] Console spam

### ISSUE THREAD

**Issue by Nikita11790** [jiangdashao/Matrix-Issues#789]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: latest paper 1.14.4
**Error(s) found in console**: https://paste.gg/p/anonymous/45363b408da84a9aad748b581f7edb14
**How/when does this happen**: always, it spams so fast my screen blurs
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**:default

**Comment by NikV2** [comment]
Are u using the 4.5.0 version of ProtocolLib?

**Comment by NikV2** [comment]
If yes, Reset your config files

**Comment by Nikita11790** [comment]
Ok

**Comment by Nikita11790** [comment]
I still have spam, I deleted matrix folder

**Comment by Nikita11790** [comment]
and rebooted server

**Comment by Nikita11790** [comment]
OH IT DOESNT SPAM ANYMORE THANK YOU

**Comment by Nikita11790** [comment]
it started agen once a player joined

**Comment by NikV2** [comment]
What is your server version
I'm sure this is an issue with ProtocolLib
If u're using minecraft version 1.13.2 Download this ProtocolLib: https://www.spigotmc.org/resources/protocollib.1997/download?version=241216

If 1.14.+ Download this: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by Nikita11790** [comment]
ok

**Comment by Nikita11790** [comment]
thank u so much
