### ISSUE TITLE
[FP] Phase on creeper explosion

### ISSUE THREAD

**Issue by Bartek200219** [jiangdashao/Matrix-Issues#794]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper Spigot 1.14-R.01-SNAPSHOT
**Verbose messages**: [Matrix] Player is phase into block (Phase)
**How/when does this happen**: When player is in creeper explosion
**Video of false positive**: 
![image](https://user-images.githubusercontent.com/37016424/65179685-951b8a80-da5b-11e9-9a08-3068e70abec4.png)

**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
[checks.yml.txt](https://github.com/jiangdashao/Matrix-Issues/files/3628042/checks.yml.txt)

**Link to config.yml file**: 
[config.yml.txt](https://github.com/jiangdashao/Matrix-Issues/files/3628043/config.yml.txt)

**Comment by jiangdashao** [comment]
Please provide the verbose message
/matrix verbose
