### ISSUE TITLE
[FP] jesus

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#796]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**:  https://www.youtube.com/watch?v=MAbg_J8p7Wc&feature=youtu.be
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
It looks like a compatibility issue, did you install any plugin that influence fishrod?

**Comment by tiktonik114** [comment]
http://prntscr.com/p8mf2u

**Comment by jiangdashao** [comment]
I can't reproduce this false positive

**Comment by tiktonik114** [comment]
so check with paper 1.12.2
https://papermc.io/ci/job/Paper/
