### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by TerriblePanda** [jiangdashao/Matrix-Issues#8]
### Issue description
http://prntscr.com/mkdtcg
对一只玩家实体进行较大幅度的抖动点击，将会出现这种情况。

### Core information
** Matrix Version **:1.0.11
** Server Version **:1.8.8 PaperSpigot
** ProtocolLib Version **:4.4.0-b425
** Plugin List: **:MultiWorld LiteBans PEX FastAsyncWE WE ProtocolLib Matrix

### Other infomation
** ViaVersion Version: **None
** ProtocolSupport Version: **None
**BungeeCord plugins**:None

**Comment by jiangdashao** [comment]
HitBox检查任然需要改进
