### ISSUE TITLE
[BYPASS] Phase (Two Phases)

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#801]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.8.8
Verbose messages: Watch the video
How/when does this happen: if you use phase mode aac3.5.0 or mineplex on liquidbounce on fence gates it works aac3.5.0 does flag speed only 1 time but it still works so
Video of false positive: oof messed up the video of false positive it should be bypass but heres the link https://streamable.com/tiakj
Other information: idk

Configuration Files
Link to checks.yml file: default
Link to config.yml file: default

**Comment by jiangdashao** [comment]
that's normal, Matrix ignores most special blocks that have an incorrect hitbox.
see #323
