### ISSUE TITLE
[FP] Killaura False Flag (wtf is this)

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#808]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot idk
Verbose messages: Watch the video
How/when does this happen: i was legit just aiming at his body not even moving my head at all and i was spamming killaura falses wtf
Video of false positive: https://streamable.com/frpqq
Other information: idk

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
same as #805
