### ISSUE TITLE
[FP] Fly When Jumping

### ISSUE THREAD

**Issue by DevYorma** [jiangdashao/Matrix-Issues#81]
## How you trigger the false positive?
I tried to jump in survival mode without any permission.

## Verbose Message:
(18:43:27) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:8 ping:15 tps:20.0
(18:43:27) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:16 ping:15 tps:20.0

## Server Infomation
**Matrix Version**:  v1.7.4
**Server Version**:  git-Spigot-cf694d8-8d8475f (MC: 1.13.2)
**ProtocolLib Version**:  v4.4.0 (MC: 1.13.2)

**Comment by jiangdashao** [comment]
No evidence, no video

**Comment by DevYorma** [comment]
(09:31:16) Yorma failed Speed check | faster than expected | t-d | move: 0.463 mv: 1.42 (+7) | vl:7 ping:17 tps:20.0
(09:31:16) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:8 ping:17 tps:20.0
(09:31:28) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:8 ping:17 tps:20.0
(09:31:29) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:16 ping:17 tps:20.0
(09:31:33) Yorma failed Speed check | faster than expected | t-d | move: 0.481 mv: 1.42 (+7) | vl:7 ping:17 tps:20.0
(09:31:33) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:24 ping:17 tps:20.0
(09:31:33) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:32 ping:17 tps:20.0
(09:31:35) Yorma failed Fly check | t:step-1  a=1.4199999868869781 b=0.41999998688697815 (+8) | vl:40 ping:17 tps:20.0

<blockquote class="imgur-embed-pub" lang="en" data-id="a/vQRCjqo"><a href="//imgur.com/vQRCjqo"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by jiangdashao** [comment]
Please provide enough information, such as your client information

**Comment by DevYorma** [comment]
## Clientinformation:
Minecraft 1.13.2 Vanilla (no mods at all)
Java 8 Update 211
RAM: 2048MB

**Comment by jiangdashao** [comment]
Please provide debug files: /matrix debug
Is there any potion effect when you jump? or any plugins modified your movement？

**Comment by DevYorma** [comment]
There are no plugins doing stuff like that.
[debug.txt](https://github.com/jiangdashao/Matrix-Issues/files/3099858/debug.txt)

**Comment by DevYorma** [comment]
And no potion effects

**Comment by ignPerformance** [comment]
Record a video @DevYorma and link it here. Otherwise, this is staying closed.

**Comment by DevYorma** [comment]
I still recorded this video: https://imgur.com/a/vQRCjqo

**Comment by ignPerformance** [comment]
What are your Skript files?

**Comment by DevYorma** [comment]
What do you mean?
The files we coded?

**Comment by ignPerformance** [comment]
Anything that would modify movement at all?

**Comment by DevYorma** [comment]
There is nothing which should do something like that.
But I try to run Matrix on a clean server and I'll tell you the results.

**Comment by ignPerformance** [comment]
After that, take out all your .sk files and see if the error persists.
If it still does, start slowly unloading plugins with PlugMan or something.

**Comment by DevYorma** [comment]
I figured out what the problem is:
skMorkaz is not compatible with Matrix

**Comment by DevYorma** [comment]
A solution would be to disable the jump event in the config of MorkazSk.
