### ISSUE TITLE
[FP] Fast Place False Positive

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#810]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: Jitter clicking / placing blocks as well as bridging fast whilst jitter clicking.
**Video of false positive**: https://zak.pink/matrix/matrix-fastplace-fp.mp4 and https://zak.pink/matrix/matrix-fastplace-fp-2.mp4
**Other information**: Using premium config, second video has impact of the issue even though no VL is added.

## Configuration Files
**Link to checks.yml file**: Defaut
**Link to config.yml file**: Default + premium info.

**Comment by jiangdashao** [comment]
There is no good way to prevent false flags... 😭

**Comment by ZakShearman** [comment]
oof
