### ISSUE TITLE
[FP] BadPackets False Positive

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#813]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: https://pastebin.com/ktP4uZbt
**How/when does this happen**: when player was staying in AFK for 2 minutes (he minimized Minecraft client), he was kicked for using BadPackets.
**Video of false positive**: -
**Other information**: Client 1.8.8 (via ProtocolSupport)

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [x]  The issue happens on default config.yml and checks.yml
> * [x]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: 1.12.2
> **Verbose messages**: https://pastebin.com/ktP4uZbt
> **How/when does this happen**: when player was staying in AFK for 2 minutes (he minimized Minecraft client), he was kicked for using BadPackets.
> **Video of false positive**: -
> **Other information**: Client 1.8.8 (via ProtocolSupport)
> 
> ## Configuration Files
> **Link to checks.yml file**: default
> **Link to config.yml file**: default

yeah this has happened to me alot when i tab out of mc it kicks me for badpackets and its the most annoying thing ever

**Comment by jiangdashao** [comment]
can't help with anything about BadPackets check
You can try set cache_size larger
