### ISSUE TITLE
[BYPASS] Baritone demonstrates ability to bypass Anti-Bot

### ISSUE THREAD

**Issue by VirxEC** [jiangdashao/Matrix-Issues#814]
I just saw this YouTube video by the dev of Baritone, so I don't know much. All I know is that Baritone now bypasses Matrix's Anti-Bot checks. I don't think that this is released to the public yet, but here's the proof: https://www.youtube.com/watch?v=o8HMbKAG87U At the end, he does /plugins and shows that Matrix and ProtocolLib are installed.

**Comment by jiangdashao** [comment]
waiting for Baritone official release

**Comment by aUniqueUser** [comment]
@VirxEC You literally made the original issue on the baritone repository 🤡

**Comment by VirxEC** [comment]
¯\_(ツ)_/¯

**Comment by aUniqueUser** [comment]
¯\_(ツ)_/¯

**Comment by jiangdashao** [comment]
wow, bad guy

**Comment by leijurv** [comment]
LMAO you be playing both sides huh

**Comment by 0-x-2-2** [comment]
BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT BYPASS ALERT

**Comment by babbaj** [comment]
oy vey da bypass

**Comment by VirxEC** [comment]
@jiangdashao @leijurv xD I was just wondering how long I could do this for but clearly not very long at all xDDD

**Comment by SkyLicks** [comment]
Ban! Ban! Ban!

**Comment by VirxEC** [comment]
You can't ban people on GitHub...

**Comment by leijurv** [comment]
yes you can lol

**Comment by leijurv** [comment]
<img width="1012" alt="Screen Shot 2019-10-06 at 2 20 22 PM" src="https://user-images.githubusercontent.com/3837873/66276107-76cbd200-e844-11e9-80a5-7c58863ec542.png">
just to prove it to you i banned u from baritone for 1 day

**Comment by VirxEC** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOI love Baritone I discovered this bc I wanted to get an AntiCheat for my mc server and then I tried to use Baritone on it bc Baritone is so nice WHYYYYYYY


am i overreacting it's for 1 day...

**Comment by burturt** [comment]
You can always disable the anti bot check on Matrix...
