### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by ManuGooX** [jiangdashao/Matrix-Issues#817]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
Server Version: PaperSpigot 1.8.8
Error(s) found in console:

BungeeCord Console:
DownstreamBridge <-> [SkyWars1] - bad packet ID, are mods in use!? Empty minecraft packet!

Spigot/Bukkit Console:
Internal Exception: java.io.IOException: Error while write(...): Broken pipe
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException

How/when does this happen: 
  It happens when a player in a version up to 1.8 tries to enter the server.
Other information:
  I use only viaversion for connect 1.8.8 with 1.9 and up players and protocolib and matrix anticheat are updated to the last version.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
What's your BungeeCord version and type?

**Comment by ZakShearman** [comment]
I've been getting this using the latest Waterfall. I made it allow empty packets and now I get this on the Spigot server: https://pastebin.com/1Ff0eSLT

**Comment by ManuGooX** [comment]
I use Travertine #108

**Comment by jiangdashao** [comment]
IDK, try BungeeCord

**Comment by ManuGooX** [comment]
Travertine is bungeecord but modified for more compatibility, but I don't think it's bungeecord compatibility it from the server in my opinnion.

**Comment by jiangdashao** [comment]
I don't know why this error occurred, I followed the Protocol to send the packet.
