### ISSUE TITLE
[BYPASS] Fly Bypass Bug

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#820]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: idk (its official test server)
Hacked client: any works (doesn't need to be 1.12.2 anything like 1.8.8 version whatever)
Link to hacked client: any works (doesn't need to be 1.12.2 anything like 1.8.8 version whatever)
Cheat that bypassed: fly
Video of bypass: https://streamable.com/ajfgc
Other information: no u

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
cant patch, because I cant calculate velocity accurately
