### ISSUE TITLE
[BYPASS] Step Bypass Bug Idk

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#821]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: idk (official test server)
Hacked client: (any client with vanilla step works)
Link to hacked client: (any client with vanilla step works)
Cheat that bypassed: Step
Video of bypass: https://streamable.com/0vwgu
Other information: no u

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
not a bypass
