### ISSUE TITLE
[FP] Reach/Hitbox Falses

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#822]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot idk
Verbose messages: Watch the video
How/when does this happen: when you just normally attack the fighter3 bot on the official test server you false reach/hitbox alot
Video of false positive: https://streamable.com/f1k7n
Other information: idk

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by ZakShearman** [comment]
Adding on to this: http://zak.pink/matrix/player-matrix-hitbox-fp.mp4

1.8.8 server, 1.7.10 client, premium.
