### ISSUE TITLE
[BYPASS] Step Bypass

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#824]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: spigot 1.8.8
Hacked client: Flux b13
Link to hacked client: https://anonfile.com/IfF0zf65n4/Flux_b13_insane_2_year_old_client_matrix_bypasser_XD_zip
Cheat that bypassed: Step
Video of bypass: https://streamable.com/syt5v
Other information: no u

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
it's timer step + 1 block step, I can't patch it
