### ISSUE TITLE
[REQUEST] Customize kick command in config.yml

### ISSUE THREAD

**Issue by Technoguyfication** [jiangdashao/Matrix-Issues#829]
**What features/checks do you need?:**

I want to use the normal kick command instead of `matrix kick` when a player is kicked for cheating. Right now I am accomplishing this by going into the checks.yml file and replacing every `matrix kick` with `kick`. This works fine, but I have to redo it every single time I update my checks.yml due to a plugin update. It would be nice to have a config option such as `kick-command: 'matrix kick %s'` that can be used to define a global kick command so users who customize their kick command don't have to update it every time.

**Comment by jiangdashao** [comment]
nope，you can use NotePad++ to replace commands quickly (ctrl+F)
