### ISSUE TITLE
[FP] FastBreak Mushroom Block

### ISSUE THREAD

**Issue by Busted11290** [jiangdashao/Matrix-Issues#831]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Paper-196  1.14.4
**Verbose messages**:  Can be seen in video around 1:54
**How/when does this happen**:  Breaking a mushroom block by hand, in the rain.
**Video of false positive**: https://youtu.be/vOPZb2Yf93s
**Other information**:   Not sure if it is because of the rain, but it feels like it.  Doesn't seem to happen as often during the non-rain weather.

## Configuration Files
**Link to checks.yml file**:  default with ChestStealer(_Inventory management mods trigger it_) and Elytra(_issues with flying w/ fireworks_) Off
**Link to config.yml file**:  default

**Comment by jiangdashao** [comment]
Can you provide verbose message?
/matrix verbose

**Comment by Busted11290** [comment]
![firefox_pawX4RtL35](https://user-images.githubusercontent.com/14338718/65698761-06a29c80-e04b-11e9-975e-58220ea91791.png)
![firefox_3aYcfF03nx](https://user-images.githubusercontent.com/14338718/65698762-073b3300-e04b-11e9-8d4d-0d29c6fc3ca7.png)
This is the verbose in the video linked.

Just updated to 2.5.0, will test later to see if this is still an issue.
