### ISSUE TITLE
[BYPASS] criticals

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#834]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: impact 4.6 and lb
**Link to hacked client**: you have
**Cheat that bypassed**: criticals
**Video of bypass**: https://youtu.be/9wVsYdOHZCg
**Other information**: I saw the update done, but you didn’t fix it with criticals. criticals pass, but they should just as before simply not give a hit and kick for this

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [x]  The issue happens on default config.yml and checks.yml
> * [x]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: paper 1.12.2
> **Hacked client**: impact 4.6 and lb
> **Link to hacked client**: you have
> **Cheat that bypassed**: criticals
> **Video of bypass**: https://youtu.be/9wVsYdOHZCg
> **Other information**: I saw the update done, but you didn’t fix it with criticals. criticals pass, but they should just as before simply not give a hit and kick for this
> 
> ## Configuration Files
> **Link to checks.yml file**: default
> **Link to config.yml file**: default

what criticals mode and you aren't showing the other persons screen lol

**Comment by jiangdashao** [comment]
forget to add criticals check since killaura check get recode
