### ISSUE TITLE
[FP] New Hitbox False Flag

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#836]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8, 1.7.10 Forge client.
**Verbose messages**: In Video
**How/when does this happen**: General PvP
**Video of false positive**: https://www.zak.pink/matrix/2-5-hitbox-false-flags.mp4
**Other information**: Just installed, non premium version. Disabled killaura check VIA the GUI to prevent getting kicked from that module.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by jiangdashao** [comment]
seems like a Combo hit compatibility issue
