### ISSUE TITLE
[BYPASS] BoatFly / HorseFly

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#841]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.14.4
Hacked client: Aristois
Link to hacked client: https://aristois.net/zips/1.14.4-Aristois-Latest.zip
Cheat that bypassed: BoatFly / HorseFly
Video of bypass: https://streamable.com/qw31d
Other information: idk?

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
not a bypass
Matrix only check you move UP, and I won't add vehicle glide check

**Comment by coolpvpv1** [comment]
> not a bypass
> Matrix only check you move UP, and I won't add vehicle glide check

ok
