### ISSUE TITLE
[REQUEST] Hide the fake player creepily floating behind the target

### ISSUE THREAD

**Issue by pgmann** [jiangdashao/Matrix-Issues#849]
**What features/checks do you need?:**
This has gave some of our testers a scare when they enabled reverse F5 mode. Could the fake player be made invisible or something to hide this?

![image](https://user-images.githubusercontent.com/5852501/65815799-e78f4080-e1eb-11e9-9ec0-82cb8cb22fdc.png)

**Comment by jiangdashao** [comment]
you can set it in checks.yml
path: killaura.settings.npc.visible
