### ISSUE TITLE
[FP] Killaura Delay False Positive

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#851]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: General PvP, most likely only whilst jitter clicking or clicking fast.
**Video of false positive**: https://www.zak.pink/matrix/killaura-delay-false-flag-2-5-1.mp4
**Other information**: Using the premium version.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
see next version
