### ISSUE TITLE
[BYPASS] Aristois Jesus

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#852]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Aristois
**Link to hacked client**: https://aristois.net/download
**Cheat that bypassed**: Jesus
**Video of bypass**: https://www.zak.pink/matrix/jesus-bypass-2-5-1.mp4 & https://www.zak.pink/matrix/jesus-bypass-2-5-1-2.mp4
**Other information**: On the test server, premium version, apparently only works on 1 block high water.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [x]  The issue happens on default config.yml and checks.yml
> * [x]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: 1.8.8
> **Hacked client**: Aristois
> **Link to hacked client**: https://aristois.net/download
> **Cheat that bypassed**: Jesus
> **Video of bypass**: https://www.zak.pink/matrix/jesus-bypass-2-5-1.mp4 & https://www.zak.pink/matrix/jesus-bypass-2-5-1-2.mp4
> **Other information**: On the test server, premium version, apparently only works on 1 block high water.
> 
> ## Configuration Files
> **Link to checks.yml file**: Default
> **Link to config.yml file**: Default

any jesus works on that its just that its not 2 blocks deep jesus doesn't flag matrixs jesus checks if the waters only 1 block down lol so its not a bypass
