### ISSUE TITLE
[BYPASS] PacketFly (infinitly go up or forward)

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#854]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: Spigot 1.13.2
Hacked client: WWE
Link to hacked client: https://wweclient.com/AdDownload.php?MinecraftVersion=1.13.2%20client
Cheat that bypassed: PacketFly (you can go infinitly up and forward no flags)
Video of bypass: https://streamable.com/01dhf
Other information: if you want to go forward make sure packetfly is on mode normal and speed is 0.22 and if you want to up just change the speed to anything and put it on fast mode normal mode works to but fast mode is faster xd btw dont move your head at all when flying

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
caused by an NMS bug, sometime PlayerMoveEvent didn't call because of the move distance too small
