### ISSUE TITLE
[FP] Minecraft Vivecraft client is 100% incompatible with Matrix

### ISSUE THREAD

**Issue by GGothicRide** [jiangdashao/Matrix-Issues#859]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14
**Verbose messages**: 
http://prntscr.com/pc981i
http://prntscr.com/pc98j9
http://prntscr.com/pc99fy
http://prntscr.com/pc99zj
**How/when does this happen**: 
almost immeaditly
player cannot do anything with Vivecraft without the anti-cheat being set aflame with alerts
**Video of false positive**: 
https://youtu.be/PsWZYkNdV-Q
**Other information**: 
this is the wierdest bug i have ever seen out of Matrix and its probably the first of its kind
## Configuration Files
Log file: https://pastebin.com/pafi7FtC
**Link to checks.yml file**: 
https://pastebin.com/FtE41p2j
**Link to config.yml file**: 
https://pastebin.com/KzNHyVJC

**Comment by ZakShearman** [comment]
From what I can see, it does look like step at the end.

**Comment by jiangdashao** [comment]
Can you show me your plugin list?

**Comment by wesleytech** [comment]
hi, this is the plugin list of the server:
![image](https://user-images.githubusercontent.com/44944379/65829642-c68c2580-e2a7-11e9-8420-94c709826fef.png)

**Comment by jiangdashao** [comment]
so only the vivecraft client get false positives?

**Comment by jiangdashao** [comment]
> hi, this is the plugin list of the server:
> ![image](https://user-images.githubusercontent.com/44944379/65829642-c68c2580-e2a7-11e9-8420-94c709826fef.png)

so only the vivecraft client get false positives?

**Comment by GGothicRide** [comment]
yes only the vivecraft client gets loads of false positives

**Comment by GGothicRide** [comment]
wesleytech is part of our staff team, i was asleep when he commented on this issue

**Comment by jiangdashao** [comment]
did you install any mods on the vivecraft client? or does vivecraft client has autojump feature?

**Comment by GGothicRide** [comment]
i have the original staff member with the Vivecraft client who will be able to further elaborate on what it has coming to comment on this and give you more of an idea

**Comment by LemonyIsCool** [comment]
I did not install any mods on the client. I just downloaded it and started playing.

**Comment by GGothicRide** [comment]
Slimefun does generate false positives but theres not much that can be done about that as some of the items allow flight and advanced mechanics

**Comment by jiangdashao** [comment]
Can't add support for it, because the client modify the Minecraft movement mechanism
