### ISSUE TITLE
[BYPASS] 0 knockback liquidbounce bypass?

### ISSUE THREAD

**Issue by isGamerik** [jiangdashao/Matrix-Issues#860]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce 1.8.9b64
**Link to hacked client**: Liquidbounce.net/
**Cheat that bypassed**: Velocity (simple 0.0 0.0)
**Video of bypass**: https://youtu.be/b-vMznZ6fos
**Other information**: all checks enabled, Verbose doesn't show any flags

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/11J7hU7T
**Link to config.yml file**: https://pastebin.com/rFyjikTC

**Comment by jiangdashao** [comment]
Do you standing beside some blocks? Do you have bypass permission?

**Comment by isGamerik** [comment]
neither of that, i really dont know what happened

**Comment by isGamerik** [comment]
btw i was using a knockback 1 sword

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/65829772-6f07ad00-e2db-11e9-90ee-148a9b16965f.png)
It can be detected
