### ISSUE TITLE
[FP] HitBox False Positive

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#861]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: https://pastebin.com/fsZbk0ZD
**How/when does this happen**: When I was hitting blocks under myself while sneaking, I was kicked by Matrix
**Video of false positive**: no
**Other information**: Minecraft 1.8.9 without mods

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Please provide video evidence
