### ISSUE TITLE
[BYPASS] packetfly

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#863]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**:  wwe
**Link to hacked client**: https://yadi.sk/d/lhRYfHKMoe5whA
**Cheat that bypassed**: http://prntscr.com/pcip05
**Video of bypass**: https://youtu.be/ZG-x3esWokk
**Other information**: -

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default - premium

**Comment by jiangdashao** [comment]
you should tell me the client setting
