### ISSUE TITLE
[FP] elytra

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#865]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**: https://youtu.be/l7lhYh0Sh2E
**Other information**: I think this is due to the fact that when you go up and down without fireworks, the anti-cheat starts to swear

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by tiktonik114** [comment]
https://youtu.be/M07YckJqH44

**Comment by jiangdashao** [comment]
Can't reproduce it
