### ISSUE TITLE
[INCOMPATIBILITY] KICKING PLAYER FROM SERVER

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#868]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] The incompatible plugin is up-to-date
- [ x] Matrix and ProtocolLib are up-to-date
- [ x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Incompatible plugin**: npclib
**Verbose messages (or) console errors**: Internal Exception: java.io.IOException: Error while write(...): Broken pipe https://pastebin.com/raw/aTKfWFgB
**How/when does this happen**: click on npc, then it kicks you
**Video of incompatibility**: just click on npc
**Other information**: npclib

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
It was not caused by Matrix, please don't send a packet while reading a packet

**Comment by DanielAlves123** [comment]
@jiangdashao what??? When I add Matrix it happens, without it not.

**Comment by jiangdashao** [comment]
check your self code
As I said, don't send any packets while reading a packet, you should send it in next tick

**Comment by DanielAlves123** [comment]
@jiangdashao it happesn when I add Matrix to the server, so its Matrix's issue.

**Comment by jiangdashao** [comment]
Someone had the same issue as you before^^
Anyway, try the next version, I will release it soon

**Comment by DanielAlves123** [comment]
@jiangdashao it doesn't kick with head bug but it still kicks when clicking on npc.

**Comment by jiangdashao** [comment]
I already said it's not caused by matrix...
see #503

**Comment by DanielAlves123** [comment]
@jiangdashao why does it happen with Matrix and without not?

**Comment by jiangdashao** [comment]
I don't know, please check your code, are you sending a packet while receiving a packet

**Comment by DanielAlves123** [comment]
@jiangdashao why you kick player for that? You should check Matrix's code if its incompatible with ncplib...

**Comment by jiangdashao** [comment]
Matrix didn't kick player...
Please, it's your fault, I said many times, don't SEND PACKET while reading a packet

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/65967717-abcad400-e494-11e9-9f06-4549adb3faf7.png)
Did you saw it? The errror caused by your plugin

**Comment by DanielAlves123** [comment]
@jiangdashao why does it happen with Matrix and without it doesn't???

**Comment by jiangdashao** [comment]
Can we talk on Discord server?

**Comment by jiangdashao** [comment]
You should execute the "openPublicMenu" method in another thread, just like this:
`Bukkit.getScheduler().runTask(plugin, ()->{
           MenuUtil.openPublicMenu();
        });`

**Comment by DanielAlves123** [comment]
@jiangdashao why it doesn't happen without Matrix? There's definetely something wrong with this.

**Comment by jiangdashao** [comment]
just do it, or delete Matrix.

**Comment by BitesizedLion** [comment]
> @jiangdashao why it doesn't happen without Matrix? There's definetely something wrong with this.

He gave you a fix, delete matrix or use the fix.

**Comment by jiangdashao** [comment]
This is obviously an error, you can't send a packet in the method of listening to the packet or call the method that will send the packet. If you are a BungeeCord server, you will get kicked too (without Matrix)

**Comment by jiangdashao** [comment]
Your approach will only lead to netty errors, do not believe you can ask some senior developers. This is definitely your own mistake.
