### ISSUE TITLE
[BYPASS] flux

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#869]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: flux
**Link to hacked client**: flux
**Cheat that bypassed**: bunnyhop
**Video of bypass**: -
**Other information**: - 

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
it's slower than legit
