### ISSUE TITLE
[INCOMPATIBILITY] NPCLib, ViaVersion

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#870]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] The incompatible plugin is up-to-date
- [x ] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Incompatible plugin**: NPCLib, ViaVersion
**Verbose messages (or) console errors**: when i join the server viaversion kicks me and says that received head packet but theres no head. also when i try to click on npc it kicks me Internal Exception: java.io.IOException: Error while write(...): Broken pipe https://pastebin.com/raw/aTKfWFgB
**How/when does this happen**: /\
**Video of incompatibility**: /\
**Other information**: /\ It doesn't happen when i remove matrix.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
ViaVersion compatibility bug will be fixed
