### ISSUE TITLE
[INCOMPATIBILITY] boots plugin

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#871]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] The incompatible plugin is up-to-date
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Incompatible plugin**: changing blocks under you
**Verbose messages (or) console errors**: fly ground spoof fake air packet component fly.fg.air
**How/when does this happen**: when i have plugin to change blocks under you when moving
**Video of incompatibility**: /\
**Other information**: /\

## Configuration Files
**Link to checks.yml file**: /\
**Link to config.yml file**: /\

**Comment by jiangdashao** [comment]
Listening the PlayerViolationEvent and cancel it when you change the blocks, it's your private plugin, I wont add compatibility support

**Comment by DanielAlves123** [comment]
@jiangdashao shouldn't you just avoid fly check when this happens? I'm not moving just blocks are changing. I don't think it was happening in the previous version.

**Comment by DanielAlves123** [comment]
@jiangdashao please fix that should not happen.

**Comment by jiangdashao** [comment]
I told you solution ^^ or just disable fly.fg.air check

**Comment by DanielAlves123** [comment]
@jiangdashao ye you want to edit every plugin but not fix bugs on the matrix's side. Also when i sprint and run into a repeater it shows speed and sometimes shows that i send too many moving packets.

**Comment by jiangdashao** [comment]
This is a problem caused by your plugin. Other people don't have this problem at all. Why should I add compatibility to you alone?

**Comment by DanielAlves123** [comment]
@jiangdashao you should protect people from such bugs. You know a minigame where blocks change colors under you and then disappear and you fall to lava? Same thing.

**Comment by DanielAlves123** [comment]
@jiangdashao can we talk on discord?

**Comment by DanielAlves123** [comment]
@jiangdashao I think it wasn't happening on previous versions.

**Comment by DanielAlves123** [comment]
@jiangdashao it's confirmed, on previous versions it wasn't happening. I think it's like 2 versions before the newest.

**Comment by SkyLicks** [comment]
Couldn't you make an extension using the Matrix API to cancel certain violations under certain conditions to better work with Matrix?
