### ISSUE TITLE
[REQUEST] Afk kick

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#872]
an afk detector that uses packets instead of playermoveevent, rendering anti afk waterstreams useless.

**Comment by jiangdashao** [comment]
AFK is not cheat

**Comment by isGamerik** [comment]
I mean its not a bad Idea ¯\_(ツ)_/¯

**Comment by ZakShearman** [comment]
But also not a cheat.

**Comment by isGamerik** [comment]
I guess....
