### ISSUE TITLE
[BYPASS] Wurst KA

### ISSUE THREAD

**Issue by wulfwuud** [jiangdashao/Matrix-Issues#873]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server

## Issue Information
**Server version**: Paper 1.12.2
**Hacked client**: Wurst latest 1.12.2
**Link to hacked client**: dunno
**Cheat that bypassed**: KillauraLegit
**Video of bypass**: https://streamable.com/8k1oe
**Other information**: no

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Wurst = L
