### ISSUE TITLE
[FP] nofall bug

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#875]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Verbose messages**: x
**How/when does this happen**: when you disable fly and fall it can kill you even from 3 blocks maybe it saves wrong last location or something
**Video of false positive**: x
**Other information**: x

## Configuration Files
**Link to checks.yml file**: x
**Link to config.yml file**: x

**Comment by ZakShearman** [comment]
Please provide verbose messages.

**Comment by DanielAlves123** [comment]
@ZakShearman nothing is showing.

**Comment by ZakShearman** [comment]
Then it's not matrix. Make sure you're using /matrix verbose.

**Comment by DanielAlves123** [comment]
@ZakShearman i get damage when EntityDamageEvent is cancelled so something is wrong.

**Comment by jiangdashao** [comment]
no verbose message, close

**Comment by DanielAlves123** [comment]
@jiangdashao fly ground spoof normal val1 69.9215 +5 vl 10 ping 0 component fly.fg.simple
fly send illegal packet to anti fall damage val1 0.0 val2 0.2580 val3 true +10 vl 20 component nofall.packet

**Comment by jiangdashao** [comment]
When you get this false flags, can you record a video?

**Comment by DanielAlves123** [comment]
@jiangdashao when i'm on block in the air and it disappears.

**Comment by DanielAlves123** [comment]
@jiangdashao also when you fight and get knocked (with normal sword without knockback for example) it can drag you back.

**Comment by DanielAlves123** [comment]
@jiangdashao also this plugin kills players and bypasses my plugin that heals player when they die.

**Comment by ZakShearman** [comment]
> @jiangdashao also when you fight and get knocked (with normal sword without knockback for example) it can drag you back.

Do you have a knockback modification plugin? Please send verbose messages and record videos as well.

**Comment by DanielAlves123** [comment]
@jiangdashao i don't have such plugin. please check by yourself if you hit player and when he is in air and get hit again it can drag him back. 
and this bug and nofall bug 'also this plugin kills players and bypasses my plugin that heals player when they die.'

**Comment by DanielAlves123** [comment]
@ZakShearman @jiangdashao
