### ISSUE TITLE
Jesus bug

### ISSUE THREAD

**Issue by leothawne** [jiangdashao/Matrix-Issues#88]
## How you trigger the false positive?
Can be triggered by walking thru half of a water block.

## Verbose Message:
<Player> tried to move illegally in liquid (Jesus).

## Videos:
No video, sorry :(

## Server Infomation
**Matrix Version**: 1.7.4
**Server Version**: 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
No evidence
