### ISSUE TITLE
[FP] Auto Clicker 

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#880]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8, 1.8.9 client version (Forge).
**Verbose messages**: In Video
**How/when does this happen**: General fighting someone.
**Video of false positive**: https://www.zak.pink/matrix/matrix-autoclicker-ff-new.mp4
**Other information**: Using premium version, velocity check disabled.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default - premium info added

**Comment by jiangdashao** [comment]
I will make a setting for ka.ac.delay check
