### ISSUE TITLE
[FP] Scaffold

### ISSUE THREAD

**Issue by ntruong2** [jiangdashao/Matrix-Issues#884]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: failed Scaffold check | equal rotation: 75.34417, 90.0 (+5) | vl:25 ping:9 tps:20.0 component: block.scaffold.er
**How/when does this happen**: 
**Video of false positive**: https://jxjjxy-my.sharepoint.com/:v:/g/personal/yt1zk4fy7_t_odmail_cn/EUI_heEILwVAimdE13HukpoBke7JjplLmN6onq9zjgKaPA?e=YztapW
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
You should use vanilla client

**Comment by ntruong2** [comment]
Using Forge was found to be false positive
Do not turn on the Scaffold
