### ISSUE TITLE
[FP] FastBreak Concrete

### ISSUE THREAD

**Issue by Bartek200219** [jiangdashao/Matrix-Issues#885]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Newest Spigot
**Verbose messages**: 
![image](https://user-images.githubusercontent.com/37016424/66273635-e1493600-e875-11e9-809b-772389c9f33f.png)

**How/when does this happen**:  When mining falling concrete powder that becomes nomal concrete
**Video of false positive**:  
![image](https://user-images.githubusercontent.com/37016424/66273648-076ed600-e876-11e9-90dd-537be8008b82.png)

**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
[checks.yml.txt](https://github.com/jiangdashao/Matrix-Issues/files/3694713/checks.yml.txt)

**Link to config.yml file**: 
[config.yml.txt](https://github.com/jiangdashao/Matrix-Issues/files/3694711/config.yml.txt)

**Comment by jiangdashao** [comment]
Record video pls
