### ISSUE TITLE
[INCOMPATIBILITY] FastPlace/FastBreak

### ISSUE THREAD

**Issue by ntruong2** [jiangdashao/Matrix-Issues#887]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Incompatible plugin**: Viaversion up 1.8
**Verbose messages (or) console errors**: failed Block check | no swing after place block | STONE (+2) | vl:10 ping:0 tps:19.99 component: block.noswing
**How/when does this happen**: 
**Video of incompatibility**: https://jxjjxy-my.sharepoint.com/:v:/g/personal/yt1zk4fy7_t_odmail_cn/EcFe5a2sSTpIjlQJxanPO6YBjGl1DTcnHnMKQyq4xXIOOA?e=yvxGQ7
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
I tried many times, can't reproduce

**Comment by ntruong2** [comment]
please try
Server 1.8.8
Client 1.11.2
