### ISSUE TITLE
[REQUEST] Add an @a argument for /matrix npc

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#888]
**What features/checks do you need?:**
It would be alot easier for me to check aurahacks with the ability to spawn npcs for all online players. for example instead of doing /matrix npc <player> 100 for everyone online, add a /matrix npcall or /matrix npc @a 100. Thanks :)

**Comment by isGamerik** [comment]
sounds pretty nice tbh :)

**Comment by jiangdashao** [comment]
it will cause lag if you enable npc check for all players at the same time
