### ISSUE TITLE
[INCOMPATIBILITY] MineableSpawners duplication

### ISSUE THREAD

**Issue by prefislt** [jiangdashao/Matrix-Issues#889]
## Troubleshooting Information
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 paper-209
**Incompatible plugin**: MineableSpawners
**Verbose messages (or) console errors**: tried to place/break a block too quickly (FastPlace/FastBreak)
**How/when does this happen**: When player breaks spawner with Silk Touch pickaxe.
**Video of incompatibility**: [Video link](https://streamable.com/c91ax)
**Other information**: 
When i disable Matrix everything works great. 
Plugin URL: [MineableSpawners](https://www.spigotmc.org/resources/mineablespawners-1-13-1-14-silkspawners-with-extras.59921/)

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Please provide the verbose message
/matrix verbose

**Comment by jiangdashao** [comment]
it's not a compatibility issue, it's a false positive.
Fixed
