### ISSUE TITLE
Fence & Half-Slab Fly False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#89]
## How you trigger the false positive?
Put a fence gate on the top of a block and place a fence on it. Just watch the video.

## Verbose Message:
Player failed Fly check | t:fgf (+1+ | vl:2 ping:340 tps:20.0

## Videos:
https://www.dropbox.com/s/dtcrfwqnvmm5t7l/2019-04-02_00-38-36.mp4?dl=0

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment]
Update: https://1drv.ms/v/s!ApY4tKsF8vPUgogH-KEtwD832ToTxQ

**Comment by jiangdashao** [comment]
Fixed
