### ISSUE TITLE
[BYPASS] no slow

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#890]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: lb
**Link to hacked client**: -
**Cheat that bypassed**: http://prntscr.com/phgbli
**Video of bypass**:  https://youtu.be/g1nNjG--qyw
**Other information**: as you see, when he runs the anti-cheat weakly throws back. That is, he can be used and released for 2 seconds and then again used for 2 minutes and again released

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by ZakShearman** [comment]
You say it can be used for 2 minutes again, but the video you show demonstrates it can only be used again for around 2 seconds. Was this a mistake?

**Comment by tiktonik114** [comment]
yes wrong, 2 seconds
