### ISSUE TITLE
[FP] Speed false positive with slabs

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#895]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
test server
**Verbose messages**: 
see video
**How/when does this happen**: 
whenm you walk under a slab while crouching?
**Video of false positive**: 
https://youtu.be/whemvIhd-Co
**Other information**: 
was messing around on test server and found this, i have a client but only tracerhacks on
## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Not a false positive
1.14 changed player eye height, but the test server is 1.8, so the server setback you, not Matrix.
