### ISSUE TITLE
[BYPASS] killaura

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#896]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**: jessica 0.6
**Link to hacked client**: https://chity-majnkraft.ru/chity-na-majnkraft-1-12-2/chit-jessica-0-6-dlja-majnkraft-1-12-2
**Cheat that bypassed**: http://prntscr.com/pi8by2  - http://prntscr.com/pi8c0f
**Video of bypass**: https://youtu.be/EHlYBXyR3Q0
**Other information**: if the cheater cuts functions hardcombat, aac, ncp and spartan - then it is noticeable that the anti-cheat starts not detecting cheats

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/4HxLaSkj
**Link to config.yml file**: default - premium

**Comment by jiangdashao** [comment]
1. the setting is useless for fighting (low CPS + low Range)
2. ka.pitch.T1 can detect it some time, and after set cps higher, it can be detected easily

**Comment by wulfwuud** [comment]
This is 1.12.2 server pvp so cps will never be high
