### ISSUE TITLE
[REQUEST] Improve killaura npc

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#897]
**Killaura NPC improvement requests.**
- The Kill aura NPC is too close to the ground, produces visible walking particles for the player. _The height of the NPC should be configurable._
- There should be a kill aura NPC command for all players, _even if it has to cycle through each one to reduce lag. The reason I would like a command to spawn the NPC for all players is because the only way to catch hackers is by using a visible NPC, but it is very distracting (see suggestion below)_
-The kill aura NPC is very visible for players when they turn around quickly, alot of killaura modules on hacked clients do not attack invisible mobs/players _perhaps make the NPC invisible when the player is turning their head._

**Comment by jiangdashao** [comment]
If you make npc float in air, some AntiBot can easily detect the bot

**Comment by jiangdashao** [comment]
option "move_up_after_attack" will add
