### ISSUE TITLE
[FP] Velocity/Speed

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#898]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
 Speed: suspicious movement: 0.787 expect: 0.672500001 predict: 0.82999904 fr:0.6 tag:ec 
Velocity:  ignore server velocity: 0.348 pattern #5
**How/when does this happen**: fighting
**Video of false positive**: easy to reproduce
**Other information**: 
A lot of false positives with latest Matrix.

## Configuration Files
**Link to checks.yml file**:  latest
**Link to config.yml file**:  latest

**Comment by ZakShearman** [comment]
I don't get issues with velocity. Please can you list your plugins.

**Comment by DanielAlves123** [comment]
@ZakShearman I have issues and a lot of spam with false warnings. It happens on 1.8 server but people have less nodamagerticks.

**Comment by ZakShearman** [comment]
What do you mean? Also, please list your plugins.

**Comment by DanielAlves123** [comment]
What do I mean with what?
WorldEdit, WorldGuard, ViaVersion, ViaRewind, ViaRewind-Legacy-Support, ProtocolLib, NoCheatPlus, Matrix, HolographicDisplays

**Comment by ZakShearman** [comment]
Can you provide a video of the issue as well please.

**Comment by DanielAlves123** [comment]
@ZakShearman not really at the moment, but it's easy to reproduce, I get a lot of false messages.

**Comment by ZakShearman** [comment]
Well, thing is, on my 1.8 server I don't get these falses.

**Comment by ZakShearman** [comment]
Can you provide the matrix log file instead?

**Comment by DanielAlves123** [comment]
(15:19:52) p1 Speed | suspicious movement:1.393 expect:0.365 predict:0.0255 fr:0.6 tag:ea (+20) | vl:20 ping:0 tps:20.0 component: speed.main
(15:19:52) p2  Fly | suspicious movement:-0.304 predict:-0.078 lm:0.0 hard_pred:-0.078 sev_pred:-0.231 air_t:1 g:-- tag:gn (+5) | vl:5 ping:0 tps:20.0 component: fly.main
(15:19:52) p3 Speed | suspicious movement:0.651 expect:0.6235 predict:0.115 fr:0.6 tag:c (+10) | vl:10 ping:36 tps:20.0 component: speed.main
(15:19:52) p3 Speed | suspicious movement:0.512 expect:0.365 predict:0.6177251506320736 fr:0.6 tag:ea (+5) | vl:15 ping:36 tps:20.0 component: speed.main
(15:19:52) p3 Fly | suspicious movement:-0.078 predict:0.333 lm:0.42 hard_pred:0.333 sev_pred:0.42 air_t:1 g:-- tag:gn (+5) | vl:5 ping:36 tps:20.0 component: fly.main
(15:19:53) p3 Speed | suspicious movement:0.484 expect:0.365 predict:0.4910548608736863 fr:0.6 tag:ea (+5) | vl:20 ping:36 tps:20.0 component: speed.main
(15:19:53) p3 Speed | suspicious movement:0.465 expect:0.365 predict:0.4661409172734017 fr:0.6 tag:ea (+5) | vl:25 ping:36 tps:20.0 component: speed.main
(15:19:53) p3 Speed | suspicious movement:0.547 expect:0.419 predict:0.3940102320110441 gt:1 fr:0.6 tag:b (+8) | vl:33 ping:36 tps:20.0 component: speed.main
(15:19:53) p3 Speed | suspicious movement:0.424 expect:0.419 predict:0.44292157900001244 gt:2 fr:0.6 tag:b (+8) | vl:41 ping:36 tps:20.0 component: speed.main
(15:19:53) p3 Velocity | ignore server velocity: 0.604 pattern: #5 (+4) | vl:4 ping:36 tps:20.0 component: vel.expect
(15:19:57) p4 Fly | ground spoof | t: fgw.2 a=63.01555509510107 b=-0.0784000015258789 c=0.40444489178590715 (+10) | vl:10 ping:48 tps:19.99 component: fly.fg.w2
(15:19:58) p5 Fly | suspicious movement:-0.374 predict:-0.078 lm:0.0 hard_pred:-0.078 sev_pred:-0.377 air_t:11 g:-- tag:gn (+5) | vl:5 ping:7 tps:19.99 component: fly.main
(15:20:00) p1 Speed | suspicious movement:0.326 expect:0.315 predict:0.32416451313371836 fr:0.6 tag:ec (+10) | vl:10 ping:45 tps:19.99 component: speed.main
(15:20:00) p1 Speed | suspicious movement:0.345 expect:0.342 predict:0.341300851033193 fr:0.6 tag:eb (+6) | vl:16 ping:45 tps:19.99 component: speed.main
(15:20:00) p1 Speed | suspicious movement:0.332 expect:0.315 predict:0.3295696483278372 fr:0.6 tag:ec (+10) | vl:26 ping:45 tps:19.99 component: speed.main
(15:20:01) p1 Speed | suspicious movement:0.348 expect:0.342 predict:0.34395293362007556 fr:0.6 tag:eb (+6) | vl:32 ping:45 tps:19.99 component: speed.main
(15:20:01) p1  Speed | suspicious movement:0.335 expect:0.315 predict:0.33212321275583445 fr:0.6 tag:ec (+10) | vl:42 ping:45 tps:19.99 component: speed.main
(15:20:01) p2 Velocity | ignore server velocity: 0.569 pattern: #5 (+4) | vl:4 ping:4 tps:19.99 component: vel.expect
(15:20:03) p5 Velocity | ignore server velocity: 0.328 pattern: #5 (+4) | vl:4 ping:64 tps:20.0 component: vel.expect
(15:20:04) p6 Velocity | ignore server velocity: 0.231 pattern: #5 (+4) | vl:4 ping:37 tps:19.97 component: vel.expect
(15:20:06) p2 Velocity | ignore server velocity: 0.315 pattern: #5 (+4) | vl:8 ping:64 tps:20.0 component: vel.expect
(15:20:07) p5 Velocity | ignore server velocity: 0.328 pattern: #5 (+4) | vl:4 ping:7 tps:20.0 component: vel.expect
(15:20:08) p2 Velocity | ignore server velocity: 0.289 pattern: #5 (+4) | vl:12 ping:64 tps:19.97 component: vel.expect

all false positives

**Comment by jiangdashao** [comment]
record a video to show it

**Comment by jiangdashao** [comment]
I only get Velocity false positive
it will be fixed in next update

**Comment by DanielAlves123** [comment]
@jiangdashao sometimes it can drag you back when you get hit in the air when fighting.
