### ISSUE TITLE
[INCOMPATIBILITY] EnchantsPlus "excavation" enchant.

### ISSUE THREAD

**Issue by prefislt** [jiangdashao/Matrix-Issues#899]
## Troubleshooting Information
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 paper-210 
**Incompatible plugin**: [EnchantsPlus](https://www.spigotmc.org/resources/enchantsplus.3396/)
**Verbose messages (or) console errors**: https://imgur.com/t9UpVou
**How/when does this happen**: Using axe with "Excavation" enchant on any tree.
**Video of incompatibility**: ---
**Other information**: ---

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Tell the author to use his own "BlockBreakEvent" class.
such as:
`public class EnchantPlusBlockBreakEvent extends BlockBreakEvent { ...}`
I can't do anything about it
