### ISSUE TITLE
2 High Ceiling to Slab False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#90]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
Player failed Speed check | type E: a=(anywhere from 0.31 to 0.43) b=(anywhere from 0.31 to 0.43) t:(b, c, or 1)

## Videos:
https://www.dropbox.com/s/0r5pmykvf4lm94u/2019-04-02_00-48-44.mp4?dl=0

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
