### ISSUE TITLE
[FP] TrackPoint on Laptop flags Killaura Spin

### ISSUE THREAD

**Issue by BitesizedLion** [jiangdashao/Matrix-Issues#900]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: PaperSpigot 1.8.8
**Verbose messages**: https://pastebin.com/HnJGBam1
**How/when does this happen**: When using the TrackPoint "mouse" on my Dell Latitude E5540
**Video of false-positive**: https://caspers.app/matrix_pointer.mp4
**Other Information**: 

## Configuration Files
**Link to checks.yml file**: Zak's AC Server (Default w/ premium)
**Link to config.yml file**:  Zak's AC Server (Default w/ premium)

**Comment by jiangdashao** [comment]
That's how "spin" check works, detect player move head with the SAME speed
If you don't like it, you can disable it in checks.yml
