### ISSUE TITLE
[FP] Speed on item use

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#901]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: In Video
**How/when does this happen**: Using an item and moving whilst or right after.
**Video of false positive**: https://matrix.zakshearman.com/matrix-speed-false-flag-2-6-2-again.mp4 / https://matrix.zakshearman.com/matrix-speed-false-flag-2-6-2.mp4
**Other information**: Using the premium version.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default - with prem information

**Comment by jiangdashao** [comment]
The first video is a Minecraft bug, I can't solve it ^^
Second will be fixed
