### ISSUE TITLE
[REQUEST] Adding a document to edit which commands it executes when a player is kicked for one of the checks

### ISSUE THREAD

**Issue by RoblokazPlays** [jiangdashao/Matrix-Issues#902]
**What features/checks do you need?:**
So basically, I want a new document in the Matrix folder where you can configure the different command executions if a player toggles a check. This would make you able to ban/tempban players instead of only kicking them because they can just come back on and continue hacking.

**Comment by ZakShearman** [comment]
I don't get what you mean. You can already set all punishment commands for different violation levels in the checks.yml file.

Could you please explain in better detail and make it a bit clearer what you mean?

**Comment by RoblokazPlays** [comment]
oof i said the wrong thing

**Comment by RoblokazPlays** [comment]
i like write suggestions in notepad for different plugins and i messed up
would it be possible to make cheat announce

**Comment by RoblokazPlays** [comment]
yeah i messed up again
