### ISSUE TITLE
[FP] NoFall

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#903]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x] The issue happens on default config.yml and checks.yml
- [x ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Verbose messages**: x
**How/when does this happen**: nofall drags and kill
**Video of false positive**: x
**Other information**: matrix bypasses plugin that heals player before they die killing them

## Configuration Files
**Link to checks.yml file**: x
**Link to config.yml file**: x

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [ x] Matrix and ProtocolLib are up-to-date
> * [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [ x] The issue happens on default config.yml and checks.yml
> * [x ] I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**:
> **Verbose messages**: x
> **How/when does this happen**: nofall drags and kill
> **Video of false positive**: x
> **Other information**: matrix bypasses plugin that heals player before they die killing them
> 
> ## Configuration Files
> **Link to checks.yml file**: x
> **Link to config.yml file**: x

verbose messages the server version video of the false are the config and checks default?? you LEGIT GAVE NO INFO AT ALL JUST SAYING NOFALL DRAGS AND KILL DOESN'T EXPLAIN HOW IT HAPPENS

**Comment by jiangdashao** [comment]
No verbose

**Comment by DanielAlves123** [comment]
@jiangdashao @coolpvpv1 nofall bypasses plugin that heals when they are near death and kills them anyway, what is the need of other informations? 1.8 server

**Comment by DanielAlves123** [comment]
@jiangdashao

**Comment by ZakShearman** [comment]
You are still yet to actually provide information! @DanielAlves123, if this is still an issue, please make a new issue report and **fill it in correctly**. Don't just put `x`, it doesn't help.

**Comment by DanielAlves123** [comment]
@ZakShearman like what informations do you need? When dragging player back it kills player when i heal them in entitydamageevent. @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled=true)

**Comment by ZakShearman** [comment]
Just make a new issue report, and fill in all of the information there.

Do not `x` any of it.
Do not remove any of it.
Simple.
