### ISSUE TITLE
[FP] BadPackets

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#904]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x ] Matrix and ProtocolLib are up-to-date
- [x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x ] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: x
**How/when does this happen**: afk
**Video of false positive**: x
**Other information**: when player is afk he is kicked for badpackets

## Configuration Files
**Link to checks.yml file**: x
**Link to config.yml file**: x

**Comment by ZakShearman** [comment]
We need verbose messages. This is utterly useless.

**Comment by jiangdashao** [comment]
No verbose
