### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by JanisPlayer** [jiangdashao/Matrix-Issues#905]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**1.14.4**: 
**WEE**: 
**https://wweclient.com/Download.php**: 
**Fly and No Fall bypassed**: 
**https://youtu.be/uifk6FSLGOQ (Fly)
https://youtu.be/9mI20SeGE9I (Jump + Fly)
https://youtu.be/kgKRKqWTgaY (No Fall Damage)
https://youtu.be/WU3HIKYBUw8 (Speed) https://www.directupload.net/file/d/5605/6akcy4q9_png.htm (Hitbox)
https://youtu.be/UYlzH7PjiCI (No Fall)**: 
**https://youtu.be/s44lj5BeXSY (Old Bypass and Bug Video)**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
1. Fly-Hypixel is GroundSpoof, it can't detect when near ground and near-ground fly is useless, you still can't walk faster
2. You can set "cancel_vl" lower in Fly check
3. NoFall can't bypass in my test
4. I will improve timer check for 1.12+ , see #907 
5. HitBox check only works for real player
6.  WTF?

**Comment by JanisPlayer** [comment]
"Fly-Hypixel is GroundSpoof, it can't detect when near ground and near-ground fly is useless, you still can't walk faster"
As a cheater, I would use it to move my hitbox fast up and down.  ;)
Does not run on the server of you the latest version of Matrix NoFallDamage supposedly be fixed? https://youtu.be/kgKRKqWTgaY

So high jump works up to 3 blocks without problems.
If I keep freezing in the air for 3 seconds I have a huge advantage.

Why does not the moment check in some places in the game?
This bug is damned weird.
https://youtu.be/s44lj5BeXSY?t=1m3s

The hitbox sizes cheat also worked on real players without a flag.
A Killaura bypass could actually be very easy for this anti cheat.
The client was unfortunately programmed so poorly that the view angle is not even corrected, but there were surprisingly few flags.
But that's not bad for me, because we only have one build server.
Still a great idea with machine learning.

The tip with the timer and fly I'll change with me Thank you.

Still, so far the best anti cheat I have tested.
Good work.
