### ISSUE TITLE
[INCOMPATIBILITY] Custom Kb Plugin

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#906]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: 1.8.8 Spigot
Incompatible plugin: custom
Verbose messages (or) console errors: Watch The Video
How/when does this happen: i installed matrix on the server then when i hit people i saw that for some reason it was falsing velocity idk if its the plugin issue or matrixs velocity check
Video of incompatibility: https://streamable.com/0u2ma
Other information: idk?

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
You should be compatbile with Matrix, not Matrix compatible with you.
Matrix listen the velocity packet in HIGH priority, you should modify the packet before Matrix listened it
