### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by JanisPlayer** [jiangdashao/Matrix-Issues#909]
**What features/checks do you need?:**
hey i just wanted to ask if the anti cheat detects when i'm swimming on land?
![7ff8ydgz](https://user-images.githubusercontent.com/54918417/66791248-a38e8200-eef3-11e9-921c-f1d13702bd03.png)

I could not test it yet because I know more about memory hacking than java hooks like fabric.

I also wanted to ask if a visibility check is planned?(Anti ESP)

**Comment by jiangdashao** [comment]
1. Made a hack, if it works, then report it. I think it might check in the server side
2. I won't add AntiESP, it will waste too much CPU

**Comment by JanisPlayer** [comment]
1. Thanks that only interested me and I thought you know the info.
2. Okay thanks, that's probably the reason why these plugins are not updated anymore. (NoMoreESP and TracerBlocker)
Unfortunately, there are only these plugins left.
(AntiWallhack and Watchcat)
