### ISSUE TITLE
Fence Gate Next to Water Fly False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#91]
## How you trigger the false positive?
Place a fence that is submerged under one block of water (as seen in the video.) Jump on the wall and run into it, all while looking in random directions and movements.

## Verbose Message:
https://pastebin.com/raw/hL55Rr6y

## Videos:
https://www.dropbox.com/s/n8uxip38c85zocf/2019-04-02_00-53-49.mp4?dl=0

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
