### ISSUE TITLE
[BYPASS] bhop

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#911]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2 
**Hacked client**: wwe 2.7.2
**Link to hacked client**: https://wweclient.com/
**Cheat that bypassed**: http://prntscr.com/pjg5bp
**Video of bypass**: https://youtu.be/fti6i8H8BJY
**Other information**: Be sure to beat so that bhop will work for the cheater

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default - premium

**Comment by jiangdashao** [comment]
it's timer, not bhop
