### ISSUE TITLE
[FP] Killaura Pitch

### ISSUE THREAD

**Issue by coolpvpv1** [jiangdashao/Matrix-Issues#915]
Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

Issue Information
Server version: spigot something idk it was the official test server
Verbose messages: Watch The Video
How/when does this happen: if you use optifine will attacking going up it will false killaura pitch
Video of false positive: https://streamable.com/43pbi
Other information: cant wait for this to be marked as not important yet the other person reported the old killaura pitch falses and they got fixed lmao

Configuration Files
Link to checks.yml file: Default
Link to config.yml file: Default

**Comment by jiangdashao** [comment]
lol.
Don't ever let me see you again
