### ISSUE TITLE
[FP] Jumppads from Custom Jumppads plugin always kick my players

### ISSUE THREAD

**Issue by FerriW** [jiangdashao/Matrix-Issues#916]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
**Verbose messages**: 
**How/when does this happen**: Players gets launched with jumpads
**Video of false positive**: 
**Other information**: 
## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
No verbose message
