### ISSUE TITLE
[REQUEST] Building bug

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#917]
**What features/checks do you need?:** When building is blocked and block is showed for split second to a player you can jump on it and when you build near wall you can jump to the top without being blocked or dragged back.

**Comment by jiangdashao** [comment]
If I check this, someone will report that it's "false positive"

**Comment by DanielAlves123** [comment]
@jiangdashao you could add option to the checks.yml if it should be blocked :) In my opinion it's cheating when you can't build and still can build up

**Comment by DanielAlves123** [comment]
@jiangdashao it causes players to have fly detected.
