### ISSUE TITLE
[FP] Killaura.Post Random Issue

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#918]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 - 1.7.10 client version
**Verbose messages**: In Video
**How/when does this happen**: See video
**Video of false positive**: https://matrix.zakshearman.com/matrix-ka-post-false-flag-2-6-3.mp4
**Other information**: Using the premium configuration - disabled velocity as I use custom knockback.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default + premium information

**Comment by coolpvpv1** [comment]
> ## Troubleshooting Information
> `Change - [ ] to - [X] to check the checkboxes below.`
> 
> * [x]  Matrix and ProtocolLib are up-to-date
> * [x]  Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
> * [x]  The issue happens on default config.yml and checks.yml
> * [x]  I've tested if the issue happens on default config
> 
> ## Issue Information
> **Server version**: 1.8.8 - 1.7.10 client version
> **Verbose messages**: In Video
> **How/when does this happen**: See video
> **Video of false positive**: https://matrix.zakshearman.com/matrix-ka-post-false-flag-2-6-3.mp4
> **Other information**: Using the premium configuration - disabled velocity as I use custom knockback.
> 
> ## Configuration Files
> **Link to checks.yml file**: Default
> **Link to config.yml file**: Default + premium information

the velocity false cause of a custom knockback plugin has happened to me to and its really annoying lol

**Comment by jiangdashao** [comment]
Hmm, that's how ka.post works, calculate delays between flying packet and attack packet, it might cause false flags when you lagging. My advice is to disable it if you want, it's not an important check.
