### ISSUE TITLE
Minecart Interact False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#92]
## How you trigger the false positive?
Ride around on a minecart and try and break some tracks (as seen in the video.)

## Verbose Message:
![image](https://user-images.githubusercontent.com/43710301/55385617-5c561c00-54e2-11e9-9bbc-741886ae1c96.png)
The blocks change but you get the idea.

## Videos:
https://www.dropbox.com/s/i2gboh771nu1w7w/2019-03-28_00-58-28.mp4?dl=0

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Already fixed
