### ISSUE TITLE
[FP] NoFall kills players

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#920]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: -
**How/when does this happen**: something drags player back and kills them
**Video of false positive**: -
**Other information**: matrix bypasses plugin that heals player before they die killing them. When dragging player back it kills player when i heal them in entitydamageevent. @eventhandler(priority = EventPriority.MONITOR, ignoreCancelled=true)

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by ZakShearman** [comment]
I literally said not to leave anything out. How hard is that to understand?

Provide a video and verbose messages please.

**Comment by DanielAlves123** [comment]
@ZakShearman it's simple to reproduce

**Comment by ZakShearman** [comment]
If this gets closed like the other issue report because you didn't provide the information, then just leave it :). Fine by me.

**Comment by DanielAlves123** [comment]
@jiangdashao @ZakShearman what informations? It drags you back dealing damage, then it bypasses plugin that heals you when you have low health. Simple.

**Comment by ZakShearman** [comment]
I'm simply going to ignore you/your issues here now. You're simply incapable of reading, I have told you many times through various different methods, done as much as I can, and I now just simply give up.

**Comment by DanielAlves123** [comment]
@ZakShearman good because i see that you have mental issues. If you will want to help people and fix Matrix let me know.

**Comment by ZakShearman** [comment]
Ok thanks. Blocked.

**Comment by True-cc** [comment]
@DanielAlves123 , you are being a huge jerk and asshole. You're not responding to information that one MUST have. If you don't know how to get/give the verbose, and don't know how to make a video, please, say it. If you do know how, but are unwilling to do so, then fuck off.

**Comment by DanielAlves123** [comment]
@True-cc i report simple and easy to fix bug. Don't tell me to fuck off because in real life you would suck my dick to stay alive after saying me that

**Comment by DanielAlves123** [comment]
@jiangdashao it bypasses cancelled entitydamageevent.

**Comment by BitesizedLion** [comment]
> @ZakShearman good because i see that you have mental issues. If you will want to help people and fix Matrix let me know.

Piss off, dumb cunt.

**Comment by True-cc** [comment]
> @True-cc i report simple and easy to fix bug. Don't tell me to fuck off because in real life you would suck my dick to stay alive after saying me that

1: I'm not homosexual.
2: The fact that you said that probably means you're homo.
3: Fairly certain everyone's making fun of you now. XD

**Comment by BitesizedLion** [comment]
> @True-cc i report simple and easy to fix bug. Don't tell me to fuck off because in real life you would suck my dick to stay alive after saying me that
> 
> 1: I'm not homosexual.
> 2: The fact that you said that probably means you're homo.
> 3: Fairly certain everyone's making fun of you now. XD

How has he not deleted his account yet, kappa

**Comment by jiangdashao** [comment]
NoFall check just detect ground spoof, it does not listen or influence the entity damage eveent

**Comment by DanielAlves123** [comment]
@jiangdashao maybe it's different check that deals damage? Without Matrix people can't reach playerdeathevent, with Matrix I just see 'player died' info and it bypasses cancelled entitydamage. Can you check it? Thanks. :)

**Comment by jiangdashao** [comment]
What? Matrix only makes the player get damage when they get Fly.NoFall check flags.
I said, record a video, also provide the verbose message (/matrix verbose)

**Comment by DanielAlves123** [comment]
@jiangdashao that's probably the cause. It's hard to record a video, but I will try to match logs with death events.

**Comment by DanielAlves123** [comment]
@jiangdashao (08:07:46) player Fly | suspicious movement:-0.186 predict:-0.781 lm:-0.717 hard_pred:-0.781 sev_pred:-1.139 air_t:12 g:-- tag:gn (+5) | vl:5 ping:62 tps:20.0 component: fly.main
(08:07:46) player Fly | ground spoof | send ground packets when falling | a: 4.249187095921471 (+5) | vl:10 ping:62 tps:20.0 component: fly.fg.nofall
(08:07:46) player Fly | t: af (+5) | vl:15 ping:62 tps:20.0 component: nofall.air

[08:07:46] [Server thread/INFO]: PlayerDeathEvent should not be called!
[08:07:46] [Server thread/INFO]: player died

**Comment by jiangdashao** [comment]
? So how does this happens?

**Comment by DanielAlves123** [comment]
@jiangdashao I don't really know it probably drags players and deal damage when bypassing cancelled entitydamage event.

**Comment by jiangdashao** [comment]
I use `Player#damage()` method to force damage player when they using nofall

**Comment by DanielAlves123** [comment]
@jiangdashao     @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled=true)
    public void on(EntityDamageEvent event) {
        final Entity entity = event.getEntity();
        if (entity instanceof Player == false) {
            return;
        }
        final Player victim = (Player) entity;
        if (victim.getHealth() - event.getFinalDamage() > 0) {
            return;
        }
        event.setCancelled(true);

So how to fix this?

**Comment by DanielAlves123** [comment]
@jiangdashao people are being damaged even in lobbies, where damage can't be dealt.

**Comment by DanielAlves123** [comment]
@jiangdashao false positives:
(16:05:19) player Speed | suspicious movement:0.456 expect:0.45099999999999996 predict:0.31513319502014164 gt:1 fr:0.6 tag:b (+8) | vl:8 ping:59 tps:19.99 component: speed.main
(16:09:42) player Fly | suspicious movement:-0.156 predict:-0.844 lm:-0.781 hard_pred:-0.844 sev_pred:-0.844 air_t:11 g:-- tag:gn (+5) | vl:5 ping:38 tps:20.0 component: fly.main
(16:09:42) player Fly | ground spoof | send ground packets when falling | a: 5.078400001525878 (+5) | vl:10 ping:38 tps:20.0 component: fly.fg.nofall
(16:09:42) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 5.078400001525878 val3: true (+10) | vl:20 ping:38 tps:20.0 component: nofall.packet

**Comment by DanielAlves123** [comment]
@jiangdashao

**Comment by DanielAlves123** [comment]
@jiangdashao maybe you should look on nocheatplus source? https://github.com/NoCheatPlus/NoCheatPlus/blob/62df128efdb475a8c8adc9ab3ab96386fb426387/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/moving/player/NoFall.java#L186

**Comment by DanielAlves123** [comment]
@jiangdashao
