### ISSUE TITLE
[REQUEST] Violation Weight

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#921]
**What features/checks do you need?:**

I would like to see violation weight being introduced to the speed check, flight check, elytra check, and any other checks that doesn't have an overall weight system. It's hard to configure the punishment thresholds if you don't know when it'll trigger.

**Comment by jiangdashao** [comment]
I can't add custom VL Weight for these checks, because there are many different modules in Movement check. "Many"
