### ISSUE TITLE
[FP] Elytra false positive

### ISSUE THREAD

**Issue by fireboyev** [jiangdashao/Matrix-Issues#924]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14
**Verbose messages**: (20:46:44) fireboyev failed Elytra check | move unexpected: 0.068 -> -0.167 / pb / t:877 (+2) | vl:4 ping:53 tps:20.0 component: elytra.y
**How/when does this happen**:  When you glide with a firework rocket and the boost ends while facing upwards
**Other information**: It only shoots out one message each time you are facing upwards when the firework boost ends.

## Configuration Files
**Link to checks.yml file**:  default
**Link to config.yml file**:  default

**Comment by jiangdashao** [comment]
not important
