### ISSUE TITLE
Fence, Slab, & Block Fly False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#93]
## How you trigger the false positive?
Attempt what is seen in the video.

## Verbose Message:
https://pastebin.com/raw/RgfeXPZK

## Videos:
https://www.dropbox.com/s/t3zntvzttftc6be/2019-04-02_00-59-20.mp4?dl=0

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
I won't fix this
