### ISSUE TITLE
[REQUEST] False positives

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#931]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:
(20:08:03) player Fly | suspicious movement:-0.228 predict:-0.078 lm:0.0 hard_pred:-0.078 sev_pred:-0.231 air_t:9 g:-+ tag:gn (+5) | vl:5 ping:46 tps:20.0 component: fly.main
 (20:08:45) player FastHeal | regen health too fast | difficulty: 1 delay: 3604 protocol_ver: 8 (+2) | vl:2 ping:44 tps:19.99 component: heal
(20:09:24) player Velocity | ignore server velocity: 0.465, 0.185 pattern: #6 (+2) | vl:2 ping:53 tps:19.98 component: vel.expect
(20:09:24) player Velocity | ignore server velocity: 0.533,0.772 pattern:#5 (+4) | vl:6 ping:53 tps:19.98 component: vel.expect
(20:09:25) player KillAura | (style) non-human like combat style | confidence: 21.21212121212121 (+10) | vl:10 ping:53 tps:20.0 component: ka.style
(20:09:30) player Velocity | ignore server velocity: 0.203, 0.086 pattern: #6 (+2) | vl:8 ping:53 tps:20.0 component: vel.expect
(20:09:41) player KillAura | (npc) force field (+5) | vl:5 ping:53 tps:20.0 component: ka.ff
(20:09:44) player Speed | sprint direction: 0.326 angle:475.585 (+5) | vl:5 ping:53 tps:20.0 component: speed.sprint
(20:10:06) player Speed | suspicious movement:0.923 expect:0.615 predict:0.2858854411544493 fr:0.6 tag:ea (+5) | vl:10 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.863 expect:0.615 predict:0.8653699687723099 fr:0.6 tag:ea (+5) | vl:15 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.809 expect:0.615 predict:0.8111912511913674 fr:0.6 tag:ea (+5) | vl:20 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.76 expect:0.615 predict:0.7619254040236414 fr:0.6 tag:ea (+5) | vl:25 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.76 expect:0.542 predict:0.7619254040236414 fr:0.6 tag:eb (+6) | vl:31 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.716 expect:0.615 predict:0.7173273394009659 fr:0.6 tag:ea (+5) | vl:36 ping:44 tps:20.0 component: speed.main
(20:10:06) player Speed | suspicious movement:0.675 expect:0.615 predict:0.6769015833933031 fr:0.6 tag:ea (+5) | vl:41 ping:44 tps:20.0 component: speed.main
(20:10:11) player KillAura | (angle) suspicious angle:[105.81246, 166.65341] (+8) | vl:8 ping:44 tps:20.0 component: ka.angle
(20:10:11) player HitBox | direction: player d:[0.0, 0.0, 0.0, 0.0] t:4 (cache) (+4) | vl:4 ping:44 tps:20.0 component: hb.dir
(20:10:14) player Speed | suspicious movement:0.285 expect:0.264 predict:0.305003044040984 fr:0.6 tag:ea (+5) | vl:5 ping:44 tps:20.0 component: speed.main
(20:10:14) player Speed | suspicious movement:0.277 expect:0.264 predict:0.2976608554894041 fr:0.6 tag:ea (+5) | vl:10 ping:44 tps:20.0 component: speed.main

**How/when does this happen**: most problematic is dragging back when fighting/running and getting knocked in running way
**Video of false positive**: -
**Other information**: 1.14 client version for example

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Olly32** [comment]
you're supposed to supply a video that shows exactly what causes these checks to be set off, also speed false positives all the time so dont worry about it

**Comment by DanielAlves123** [comment]
@Olly32 it happens in normal fight. The most problematic is dragging back player when he get knocked, it's really annoying.

**Comment by jiangdashao** [comment]
video please
