### ISSUE TITLE
[CRASH] Server crasher still works

### ISSUE THREAD

**Issue by ZakShearman** [jiangdashao/Matrix-Issues#934]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Information**: This is the same crash as before, and I get this in console `[Matrix] Received invalid look packet!` It no longer crashes the server, but the server is basically pinned at 100% CPU usage (1 core fully utilised) https://zak.pink/19-10-20-47-14_2955.png.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default - Premium version

**Comment by ZakShearman** [comment]
This quantifies with how many people crash it:

https://zak.pink/19-10-20-58-19_2958.png
https://zak.pink/19-10-20-59-08_2959.png

**Comment by BitesizedLion** [comment]
> This quantifies with how many people crash it:
> 
> https://zak.pink/19-10-20-58-19_2958.png
> https://zak.pink/19-10-20-59-08_2959.png

100% per client

**Comment by BitesizedLion** [comment]
This has not been fixed.

**Comment by ZakShearman** [comment]
Yep. Re open please:

https://zak.pink/Spiteful-Nematode-3434.png
https://zak.pink/Harmless-Raptors-3433.png
