### ISSUE TITLE
Jesus/Liquids False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#94]
## How you trigger the false positive?
Watch the video.

## Verbose Message:
![image](https://user-images.githubusercontent.com/43710301/55386352-2ca81380-54e4-11e9-805e-4c0c91b9a85b.png)

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogO2BKLYWbVEQ1fOw

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
