### ISSUE TITLE
[REQUEST] Make entityspeed speed limit consider mob type

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#940]
**What features/checks do you need?:**
You can use entityspeed on pigs to match the speed of horses without being detected, because there is only 1 speed limit (15.7~ blocks per second) between all mob types. I am suggesting that each mobtype should have a speed limit (for example, pigs can only go 5.2 blocks per second when using the carrot on a stick boost)

**Comment by jiangdashao** [comment]
Actually it already works like that. I set the limit speed for pig higher to avoid false flags in some situations
