### ISSUE TITLE
[INCOMPATIBILITY] KnockbackMaster Incompatibility

### ISSUE THREAD

**Issue by jiangdashao** [jiangdashao/Matrix-Issues#943]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] The incompatible plugin is up-to-date
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Incompatible plugin**: 
**Verbose messages (or) console errors**: 
**How/when does this happen**: 
**Video of incompatibility**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Would be really nice if you could add KnockbackMaster support. _Additionally nice if you added Strike Practice's knockback support. I can get the dev to add API stuff if you need._
