### ISSUE TITLE
[FP] boat

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#944]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**:  https://youtu.be/PiMVMU4GQv8
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default premium

**Comment by Kyrobi** [comment]
There's nothing to worry about since it's between  1 and 2 VL. It's not important

**Comment by tiktonik114** [comment]
but not what the player throws back? this is normal? I could finally pissed me off

**Comment by jiangdashao** [comment]
It looks like some bug in Bukkit/Spigot API, I can't fix it.
Just set setback_vl higher
