### ISSUE TITLE
[BYPASS] crystalaura

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#945]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**:  impact 4.6
**Link to hacked client**: -
**Cheat that bypassed**: http://prntscr.com/pplwa7
**Video of bypass**: https://youtu.be/WJkh9KA_GPk
**Other information**: maybe the anti-cheat sees that the cheater hits for 6 blocks, but he just swears at it but does not block anything. I want to block the damage from the first hit

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default premium

**Comment by jiangdashao** [comment]
it works and blocks in my test

**Comment by tiktonik114** [comment]
.....
