### ISSUE TITLE
[FP] velocity ignore kick trigger by elder gardian and some other nice stuff <3

### ISSUE THREAD

**Issue by pluttotv** [jiangdashao/Matrix-Issues#946]
## Troubleshooting Information
- [ x ] Matrix and ProtocolLib are up-to-date 
- [ x ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ x ] The issue happens on default config.yml and checks.yml
- [ x ] I've tested if the issue happens on default config

## Issue Information
paper 121 1.14.4
vid: https://www.youtube.com/watch?v=-C8AkWfY7VY
32:50 - 33:04
every time on this round players are getting kicked by the matrix cuz of the elder guardian making a skill that trigger the velocity ignore.

## Configuration Files
**Link to checks.yml ** :
https://pastebin.com/xLivFAZL

**Link to config.yml file**: 
https://pastebin.com/UGdMLbhB

i must say this plugin is amazing, its so good agents cheaters,
also i know how hard it is to keep it uptodate so respect man!
u deserve it alll!

but beside that - here are 2 sidenotes (not related to the false positives):
1. alot of the members playing in my server keep geting bother by the matrix kill aura (im pretty sure its the kill aura)
its seems to really annoy people cuz they see this player always flying next to them always checking if they cheat. its happen often on the zombie mini game (which u can see in the vid - thro i never see him cuz im op). is there any chance to add to the config an option to not check it that often - or like set "check every x time" cuz otherwise i have to turn off the kill aura.

2. i have a mod that his mission is to keep trying to hack down the server.
most of the public hacks are bypassed by matrix, but one which bypass almost all ur protection
is this hack:
https://aristois.net/
im posting the link here so you can check it ur self.
the spam msg from that hack works 2 good, and matrix doesn't blook it, as well other handful of hacks.

thanks!
keep up the amazing work!
Plutto.

**Comment by jiangdashao** [comment]
1. Please provide verbose message of the false positive. Use /matrix verbose to turn on it
2. You can set killaura.vl_weights.npc to -1 to disable npc check. It is just a part of KillAura check.
3. If you found any bypass, please make a new issue, not telling me which client can bypass.

**Comment by pluttotv** [comment]
no problem it will take me a day or 2 cuz i didn't had the matrix verbose on on that time.
i will turn it on and replicate the false positive. 

about the hack that work - i will check creating new issue about it - but beside that site and the download link i dont know alot -> my guy did checked alot of hacks from it and it worked him.
the most clearly i notice is the spam chat hack he used.

**Comment by jiangdashao** [comment]
Matrix only prevent basic spam chat hack, you should use other advanced AntiSpam plugin

**Comment by pluttotv** [comment]
i see thanks!
also where i can find 
killaura.vl_weights.npc ?
on the yml i cant find it and i cant trigger it with any command ingame.

**Comment by jiangdashao** [comment]
Please provide the verbose messages of the velocity false positive

**Comment by pluttotv** [comment]
atm i cant replicated the false positive - so if you want to close the topic i understand, onces it happen again i will ues /matrix verbose send all the full info.... thanks.
btw - still cant find killaura.vl_weights.npc thing, can you point up where is it?
Cheers

**Comment by jiangdashao** [comment]
at checks.yml
