### ISSUE TITLE
Matrix False Positives

### ISSUE THREAD

**Issue by Jakaboii** [jiangdashao/Matrix-Issues#948]
## Troubleshooting Information
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 Paper
**Verbose messages**: (all shown in the vid)
**How/when does this happen**: When using LaunchPads, PvP'ing, Bow Spamming & Building
**Video of false positive**: https://www.youtube.com/watch?v=QTpEcl6H7iM
**Other information**: What I did in the video would not only send Verbose messages, but sometimes flag the player for Fly, KillAura, Anti-Knockback ect, ect

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/uLmYeGc2
**Link to config.yml file**: https://pastebin.com/g26GcCyD

**Comment by ZakShearman** [comment]
Launch Pads - Plugin incompatibility, what plugin are you using?

The building one you showed - Never actually flagged, and you were 40 violations off being cancelled. Not anything I would consider broken there.

Bow Spamming - Yh, that one's annoying / p sure it needs to be fixed.

PvP False Flags - Seems pretty insignificant apart from velocity, as they're nowhere near being a problem.

With velocity, are you using any knockback modifications with Strike Practice or another plugin?

**Comment by ZakShearman** [comment]
Don't think support for LaunchPadPlus could be added. Probably best to remove it from Practice.

**Comment by Jakaboii** [comment]
Ok, I'll remove the LaunchPads from Practice

And for the Knockback, I have it set to false & haven't changed it's settings

**Comment by ZakShearman** [comment]
Hmm. Ok. I'll leave this all to RE now :).

**Comment by Jakaboii** [comment]
Ok, ty
