### ISSUE TITLE
[BYPASS] nuker

### ISSUE THREAD

**Issue by tiktonik114** [jiangdashao/Matrix-Issues#949]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: paper 1.12.2
**Hacked client**:  impact 4.6
**Link to hacked client**: 
**Cheat that bypassed**: 
**Video of bypass**: https://youtu.be/vmkhs1zUde8
**Other information**: lighthouse detour

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Because you are using an unsafe enchantment: Efficiency level > 5
