### ISSUE TITLE
Spamming Space on Slabs Speed False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#95]
## How you trigger the false positive?
Watch the video. Basically, spam space once you reach the middle-ish slab.

## Verbose Message:
https://pastebin.com/raw/ucBkyarN

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogQdDXLQtenOXVR5g

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
