### ISSUE TITLE
[FP] Scaffold (tower)

### ISSUE THREAD

**Issue by ntruong2** [jiangdashao/Matrix-Issues#954]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Verbose messages**: https://hastebin.com/ayufanocih.sql
**How/when does this happen**: When using minecraft version higher than 1.8
**Video of false positive**: https://streamable.com/14khg
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Black List User
