### ISSUE TITLE
[FP] Flying with elytra aborted & Riding on blue ice abord

### ISSUE THREAD

**Issue by jackhistoria** [jiangdashao/Matrix-Issues#959]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server (1.14 paper server)
- [x] The issue happens on default config.yml and checks.yml 
- [x] I've tested if the issue happens on default config //Default config of what? Matrix? (yes)

## Issue Information
**Server version**: 
papermc 1.14.4
**Verbose messages**: 
![Screenshot_20191103_102916](https://user-images.githubusercontent.com/47753801/68086509-2f3d6380-fe4d-11e9-8e47-466c3a0cebc7.png)

**How/when does this happen**: 
1. Flying with elytra (dropping), new fireworks rocked needed to not drop on the ground
2. Riding with boat on blue ice anc ctrl pressed (getting kicked out of the boat)
(getting kicked of the boat riding a 10.000 blocks ice lane makes it nasty and the 
plugin unusable)

**Video of false positive**: 
http://ul.to/9x5ktu69 (high quality1.5gb)
http://ul.to/edtydbpa (low quality 130mb)
https://streamable.com/3jmd0 (low quality 130mb)
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
[checks.txt](https://github.com/jiangdashao/Matrix-Issues/files/3801648/checks.txt)
(renamed to txt to get it uploaded)
**Link to config.yml file**: 
[config.txt](https://github.com/jiangdashao/Matrix-Issues/files/3801649/config.txt)
(renamed to txt to get it uploaded)

**Comment by Olly32** [comment]
upload the video on youtube unlisted dude, fucking uploaded.net??? lmao.

**Comment by jackhistoria** [comment]
Already Uploading it in low quality to streamable. Just wait a few seconds and you can download it from uploaded.

**Comment by Olly32** [comment]
Could you do this with /matrix verbose on? Otherwise dev won't know the cause of the false positive.

**Comment by jackhistoria** [comment]
There is nothing as an option to turn verbose on since the last update. I put on the last log file with all information the plugin is possible is able to produce.
[matrix_log_2019-11-03.txt](https://github.com/jiangdashao/Matrix-Issues/files/3801945/matrix_log_2019-11-03.txt)

**Comment by jackhistoria** [comment]
![Screenshot_20191103_193112](https://user-images.githubusercontent.com/47753801/68090134-8ef93600-fe70-11e9-9550-9e634fa35861.png)

**Comment by Kyrobi** [comment]
Here's a video of the boat on blue ice: https://youtu.be/bSjp9DjGBS4 Welcome

**Comment by jackhistoria** [comment]
Thanks bud
