### ISSUE TITLE
[FP] Velocity false positive, "Knockback" enchantment incompatibility

### ISSUE THREAD

**Issue by BestMark** [jiangdashao/Matrix-Issues#961]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: https://pastebin.com/mTsQu0tZ
**How/when does this happen**: when the player was hit with a stick with the knockback enchantment, anti-cheat kicked him.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by Olly32** [comment]
please provide a youtuve video of this
