### ISSUE TITLE
[FP] Speed flag jumping into nether portal

### ISSUE THREAD

**Issue by iBrady** [jiangdashao/Matrix-Issues#962]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.12.2

**Verbose messages**: 
![image](https://user-images.githubusercontent.com/14994117/68108301-b7704700-fee7-11e9-8030-04e51673443d.png)

**How/when does this happen**: 
Whenever a player jumps into a nether portal, they get stuck into the nether portal by the AC

## Configuration Files
**Link to checks.yml file**: 
https://pastebin.com/d6CFkbZF

**Link to config.yml file**: 
https://pastebin.com/EJMWqV7e

**Comment by jiangdashao** [comment]
Please provide your plugin list, it shouldn't happen in the normal server

**Comment by iBrady** [comment]
We're using FabledSkyblock. Instead of going to the actual nether, when entering the nether portal you get teleported to a different world.

This is probably the isuse. [This is the Portal class](https://gitlab.com/Songoda/fabledskyblock/blob/development/src/main/java/com/songoda/skyblock/listeners/Portal.java) used by FabledSkyblock

**Comment by Olly32** [comment]
kinda offtopic but that playermoveevent listener makes me cringe, like why are they getting so many objects before even seeing if it isn't mouse movement :/

**Comment by iBrady** [comment]
Trust me, I have no idea.. They bought the source code and were thinking about a recode, but yet they are still working on it

**Comment by jiangdashao** [comment]
Please use `teleport()` method, not using `event.setTo()`
