### ISSUE TITLE
[BYPASS] No-slow bypass with non-meat items

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#963]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4
WWE Client
video: https://youtu.be/d0Nvxma8ew4
Only meat food items are taken into consideration, that means food items, even ones that are the same value as meat (pumpkin pie) are ignored.
*I also tested these food-types, none of the below are stopped:*
salmon,cod,apple,mushroomstew,rabbit,potato,stew,pufferfish,betrootsoup,cookedcod,tropicalfish,beetroot,bakedpotato,driedkelp,melonslice,cookie,cookedsalmon,rabbitstew,sweetberry,spumpkinpie,rottenflesh,goldencarrot
## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
I will add some of them, but I won't add them all. Cross-version compatibility with these materials is very cumbersome.

**Comment by Olly32** [comment]
Not sure if eating packets are sent from client to server or visa versa but couldnt you just listen for general eating packets?

**Comment by jiangdashao** [comment]
There is no eating packet

**Comment by Olly32** [comment]
Ah, so how does eating work? Surely the player would have to tell the server when they are eating.
