### ISSUE TITLE
[BYPASS] When you can't build it doesn't drag you down [HIGH PRIORITY]

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#965]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: vanilla client
**Link to hacked client**: vanilla client
**Cheat that bypassed**: placing blocks
**Video of bypass**: -
**Other information**: when you can't build and place block you can stand on them and jump near wall or something 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
But someone thinks it should be, they think it's false positive ^^

**Comment by DanielAlves123** [comment]
@jiangdashao it should't be allowed. People can get up where they shouldn't be able to. NoCheatPlus detected it as survivalfly. Can you do the same and maybe add option to checks to toggle it? Thank you, Matrix will be very close to perfect after fixing this bug.

**Comment by DanielAlves123** [comment]
@jiangdashao please fix this is crucial bug

**Comment by BitesizedLion** [comment]
This issue is closed, stop responding.

**Comment by DanielAlves123** [comment]
@BitesizedLion issue closed, but bug not fixed. @jiangdashao please fix...

**Comment by DanielAlves123** [comment]
@jiangdashao still not fixed, please fix this is the worst bug of Matrix!

**Comment by Olly32** [comment]
bruh, make your spawn area adventure mode lol

**Comment by CowzMooMoo** [comment]
ikr, this isn't a cheat, therefore it is not a bypass. Matrix is an Anti**Cheat**

**Comment by DanielAlves123** [comment]
@CowzMooMoo when players fly near wall it isn't cheating?

**Comment by BitesizedLion** [comment]
> 
> 
> @CowzMooMoo when players fly near wall it isn't cheating?

It's block glitching, make your spawn area adventure mode just like @Rasputing said.

Case closed, stop responding to a closed issue.

**Comment by ZakShearman** [comment]
"Hacked client: vanilla client"

JEEZ, just shut up already. If you call the vanilla client a hacked client, I guess no one should listen to your false positives right because you're using a hacked client. Vanilla :).

**Comment by SkyLicks** [comment]
Just ban everyone using the vanilla Hacked Client. Hacks are bad. Problem solved.
