### ISSUE TITLE
Task #53 for Matrix v2.6.10 generated an exception

### ISSUE THREAD

**Issue by SimmsRyan97** [jiangdashao/Matrix-Issues#968]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14
**Error(s) found in console**: Task #53 for Matrix v2.6.10 generated an exception
**How/when does this happen**: When I join the game and several times throughout the time I'm on the server, practically flooding the console.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/X8bZwwHe
**Link to config.yml file**: https://pastebin.com/cqnQWs03

**Comment by SimmsRyan97** [comment]
I'm also getting "Plugin Matrix v2.6.10 generated an exception while executing task 48" in the console with other players connected

**Comment by ZakShearman** [comment]
Did you update from a previous version?

**Comment by ZakShearman** [comment]
And also, could you possibly provide the latest.log file?

**Comment by jiangdashao** [comment]
Update ProtocolLib to 4.5.0
