### ISSUE TITLE
Running into Fences Velocity False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#97]
## How you trigger the false positive?
Jump and run into a fence.

## Verbose Message:
https://pastebin.com/raw/gGNY90c0

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogNxxUHCBC92yN4QA

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
Fixed
