### ISSUE TITLE
[REQUEST] Sneak Glitch

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#970]
**What features/checks do you need?:**
There is a glitch in Minecraft, spigot, paperspigot, or something. I don't know exactly what causes this, but sometimes, players get stuck sneaked. It's a visual glitch, and I remember it used to happen in Hypixel too.

I found a thread about it too: https://hypixel.net/threads/what-kinda-glitch-is-this.559479/

So when players get stuck in this bug, they throw off massive amounts of speed.main. In older versions of Matrix this check was with speed.noslow.limit. But in recent versions. this sneak running check seems to be combined with speed.main.

I just wanted to request separating the two checks again because I want to disable people from throwing alerts when stuck in this glitch.

**Comment by SkyLicks** [comment]
BTW, if more information is needed, let me know.

**Comment by jiangdashao** [comment]
As I know, the sneak glitch only happens in 1.14 version, sometimes when you go through the nether portal. Matrix fixed that bug. If you think you find a new one, please provide the evidence
