### ISSUE TITLE
[FP] Jesus false positive

### ISSUE THREAD

**Issue by MajorLOLGaming** [jiangdashao/Matrix-Issues#974]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config (I think we're using the default config. I'm pretty sure.)

## Issue Information
**Server version**: 1.14.2, paper 105
**Verbose messages**: unsure what this means, because English is not my first language. Please explain, and I will get it
**How/when does this happen**: this happens when players stand on griefprevention claim indicators in water
**Video of false positive**: https://youtu.be/8PobC36Our4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/gwdmm1MA
**Link to config.yml file**: https://pastebin.com/ReLX6zB8

**Comment by jiangdashao** [comment]
Please provide the verbose message and your plugin list

**Comment by MajorLOLGaming** [comment]
> Please provide the verbose message and your plugin list

As I said, I have no idea what a verbose message is. Is it just the message I get when it happens?

**Comment by jiangdashao** [comment]
Yes
And I think it's a compatibility issue, maybe some plugins created a fake block

**Comment by MajorLOLGaming** [comment]
Verbose is just 

> [Matrix] "playername" tried to move illegally in liquid (Jesus)

Pluginlist is:

> BungeeTabListPlus, BuycraftX, cbook-patch, CoreProtect, DiscordSRV, dynmap, Elevator, Essentials, EssentialsChat, EssentialsSpawn, FastFarmStopper, GriefPrevention, GriefPreventionDynmap, IllegalStack, LibsDisguises, LiteBans, LuckPerms, Matrix, mcMMO, MineableSpawners, Minepacks, NametagEdit, OpenInv, PAPISign, PhantomSpawnControl, PingFix, PlaceholderAPI, PlugMan, ProtocolLib, SellChest, ServerListPlus, ServerRestart, SignEdit, Skript, StaffChat, SuperVanish, Vault, Wild, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by MajorLOLGaming** [comment]
> And I think it's a compatibility issue, maybe some plugins created a fake block

That's what griefprevention does to indicate claims.

**Comment by jiangdashao** [comment]
# The verbose message is :
1. use command "/matrix verbose" to turn on the verbose messages output
2. Reproduce the false positive, and you will get the verbose messages

# This is a compatibility issue
Does grief prevention give you an option to disable the fake block?

**Comment by MajorLOLGaming** [comment]
Verbose: 
> [Matrix] "playername" failed Jesus check | jesus | pattern: #7 (+3) | vl:3 ping:4 tps:20.0 component: jesus.7

i dont know if it can be disabled yet. I am trying to get in contact with gp dev
