### ISSUE TITLE
[11:54:43] [WebSocketConnectReadThread-129/INFO]: [Matrix] [Cloud] Error: java.net.ConnectException - Connection timed out (Connection timed out) [11:54:43] [WebSocketConnectReadThread-129/INFO]: [Matrix] [Cloud] Connection closed: -1 reason: Connection timed out (Connection timed out)[ERROR] 

### ISSUE THREAD

**Issue by swerck** [jiangdashao/Matrix-Issues#975]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [y] Matrix and ProtocolLib are up-to-date
- [y] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [idk] The issue happens on default config.yml and checks.yml
- [idk] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.4 spigot
**Error(s) found in console**:  [11:54:43] [WebSocketConnectReadThread-129/INFO]: [Matrix] [Cloud] Error: java.net.ConnectException - Connection timed out (Connection timed out)
[11:54:43] [WebSocketConnectReadThread-129/INFO]: [Matrix] [Cloud] Connection closed: -1 reason: Connection timed out (Connection timed out)
**How/when does this happen**: after server restart
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment]
Ignore it, you just can't connect our cloud service, you can disable it in config.yml
