### ISSUE TITLE
[REQUEST] Add a freecam check.

### ISSUE THREAD

**Issue by Olly32** [jiangdashao/Matrix-Issues#977]
**What features/checks do you need?:**
If you could add a way to detect freecam (players in freecam take no knockback) and cancel it that would be great.
ps. Horizon anticheat has this check and I believe they cancel it by teleporting the player a microscopic amount every few seconds.

**Comment by jiangdashao** [comment]
I said, no, I won't add the freecam check

**Comment by Olly32** [comment]
Why not?
