### ISSUE TITLE
[FP] Pillar building/mining fly detection

### ISSUE THREAD

**Issue by MithrandirCraft** [jiangdashao/Matrix-Issues#978]
## Troubleshooting Information
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.13.2
**Verbose messages**: (From video 1) https://gist.github.com/MithrandirCraft/3f0687b883b4aef0444b11340687c532
**How/when does this happen**: 
Method 1:
Mine blocks as shown in Video 1. For example, make a high pillar of blocks and mine straight down.
You will eventually get suddenly bugged and teleported to the base of the tower, with full fall damage applied.
On video 1, the player had:
- Efficiency 5 on diamond pickaxe.
- Mining speed level 2 from a beacon.

It's very easy to reproduce with these conditions, however...
The issue can occur even with a regular pickaxe with no advantageous enchantments and/or effects applied. This means **you don't really need to do it the same way** in order to reproduce, and the speed at which you do this probably doesn't even matter.

Method 2:
Just build a pillar of blocks upward. 
You will eventually get suddenly bugged and teleported to the base of the tower, with full fall damage applied. As shown in video 2.

**Video of false positive**: 
Video 1: https://youtu.be/b5mTsMsckrI
Video 2: https://www.youtube.com/watch?v=-80Ab96-1do&feature=youtu.be
Video 3: https://www.youtube.com/watch?v=ANY_aa6pWvA&feature=youtu.be

**Other information**: 
Both ways of reproducing seem very similar. I'm treating them as the same bug, but they may be diferent, or slightly diferent.

It's important to note that in method 2, you don't need any equipment in order to reproduce the issue. So it's basically just building a regular tower, which everyone does in minecraft.

Important to note that in video 3 you can notice this happens to the recorder, someone who isn't even mining downward, but descending on the same pillar due to the blocks disappearing underneath him. The miner is unaffected in this singular case.

There's a problem here, **don't fucking close my ticket without saying anything**.

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by jiangdashao** [comment]
Are you using Matrix 2.7.0?

**Comment by MithrandirCraft** [comment]
Yes, you'll never see me marking these for no reason:
![imagen](https://user-images.githubusercontent.com/6623704/69063676-3784c980-0a1d-11ea-88e7-a09c4243e424.png)

**Comment by MithrandirCraft** [comment]
Hello. I've had reports of this issue still being present (at least when building towers upward)

We'll do some testing tomorrow, when the latest version 2.7.2 kicks in after the automatic restart, and if there happens to be a new way of reproducing this fp, I'll let you know.
