### ISSUE TITLE
[BYPASS] Velocity

### ISSUE THREAD

**Issue by PassiAPI** [jiangdashao/Matrix-Issues#984]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
Paper 1.8.8
**Hacked client**: 
LiquidBounce
**Link to hacked client**: 
https://liquidbounce.net/
**Cheat that bypassed**: 
Velocity
**Video of bypass**: 
**Other information**: 
A Simple null knockback cheat doesn't get detected by the Anticheat. In the verbose message you can see some little detection but with no impact.

## Configuration Files
**Link to checks.yml file**: 
Default
**Link to config.yml file**:
Default (ghostmode activated)

**Comment by PassiAPI** [comment]
I happend since the 2.7.0 update

**Comment by jiangdashao** [comment]
![image](https://user-images.githubusercontent.com/21152113/69340431-75deea80-0ca2-11ea-9064-53bd6b40952d.png)
get kicked fast
