### ISSUE TITLE
[FP] Lagging Players causing massive elytra falses

### ISSUE THREAD

**Issue by SkyLicks** [jiangdashao/Matrix-Issues#985]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Verbose messages**: In the video
**How/when does this happen**: When a player is lagging, and they use the elytra (especially when they use fireworks rocket), there are MASSIVE false positives.
**Video of false-positive**: https://youtu.be/GvCkUhpuAig (the main part of the video starts at 0:30)
**Other Information**: Yes, I did use a hacked client to make myself lag, but note this hack I used in the video is different from the packet "fake lag". This hack simulates actual latency lag.

## Configuration Files
Link to checks.yml file: https://pastebin.com/b8GnLWkN
Link to config.yml file: https://pastebin.com/4NNkPqvM

**Comment by Kyrobi** [comment]
An easier solution would be to use a plugin like ConditionalCommands to check if the player is lagging when executing a command.

Example: 
![image](https://user-images.githubusercontent.com/20980266/69202222-92deb680-0b06-11ea-9b7e-9b6e21f0c0ae.png)

If the threshold is reached, it also sees if the following conditions are true: ping <140 and tps > 19.2.

If the conditions don't match, the commands won't be executed.

**Comment by SkyLicks** [comment]
Yes. I know about those but it still spams the absolute poop out of verbose. More over, the conditional commands practically fisable the check for lagging players. I don't want that. I simply want the check to account for and be more lenient towards slightly lagging players so it is still able to catch cheaters who are lagging.

**Comment by SkyLicks** [comment]
Oops did not want to close this. Sorry!

**Comment by jiangdashao** [comment]
Did you try clumsy? It's a network emulator
https://jagt.github.io/clumsy/download.html

**Comment by SkyLicks** [comment]
No, I can try it tomorrow though and get back to you.

**Comment by jiangdashao** [comment]
Will add more lenient
