### ISSUE TITLE
[FP] Elytra

### ISSUE THREAD

**Issue by Kyrobi** [jiangdashao/Matrix-Issues#989]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.14.1
**Verbose messages**: https://pastebin.com/JdMD1nAq
**How/when does this happen**: The server will flag the person for using elytra when they are stuck in this glitch.

**Video of false positive**: N/A

**Other information**: I understand that this is a **vanilla bug** and has nothing to do with the anti-cheat. However, when players experience this glitch, they will set off the fly / speed check.

Here is the link to the bug: https://bugs.mojang.com/browse/MC-90026

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by Kyrobi** [comment]
Edit:  In the report, there are different ways to trigger it. For example, if you try to elytra hop, it'll sometimes trigger it.

**Comment by jiangdashao** [comment]
Please record a video for it

**Comment by Kyrobi** [comment]
I'll reopen this when I get a video of it
