### ISSUE TITLE
Inventory Move False Positive

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#99]
## How you trigger the false positive?
Watch the video. Basically, spam E, W, and left-click.

## Verbose Message:
https://pastebin.com/raw/TCM6Cnei

## Videos:
https://1drv.ms/v/s!ApY4tKsF8vPUgogKOy-DDlOszqyCHw

## Server Infomation
**Matrix Version**: 1.7.5
**Server Version**: Latest PaperSpigot for 1.13.2
**ProtocolLib Version**: 4.4.0

**Comment by jiangdashao** [comment]
I think it's unimportant...

**Comment by ignPerformance** [comment]
I think you should remove the check entirely as it's so easy to flag legitimately, and InventoryMove isn't that important. Most of the time it gets in the way.

**Comment by jiangdashao** [comment]
I will add a custom option for Inventory Move check
