### ISSUE TITLE
[FP] Jesus

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#995]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: (15:55:45) player Jesus | move vertically too fast: 0.197 expect: 0.19 (+5) | vl:5 ping:43 tps:20.0 component: jesus.ver
(15:55:45) player Jesus | move vertically too fast: 0.21 expect: 0.19 (+5) | vl:10 ping:43 tps:20.0 component: jesus.ver
(15:55:45) player Jesus | move vertically too fast: 0.22 expect: 0.19 (+5) | vl:15 ping:43 tps:20.0 component: jesus.ver
(15:55:45) player Jesus | move vertically too fast: 0.221 expect: 0.19 (+5) | vl:20 ping:43 tps:20.0 component: jesus.ver
(15:55:46) player Jesus | move vertically too fast: 0.222 expect: 0.19 (+5) | vl:25 ping:43 tps:20.0 component: jesus.ver
(15:55:46) player Jesus | move vertically too fast: 0.444 expect: 0.19 (+5) | vl:30 ping:43 tps:20.0 component: jesus.ver

**How/when does this happen**: 1.14 client vesion, tried to swim
**Video of false positive**: -
**Other information**: -

## Configuration Files
**Link to checks.yml file**: -
**Link to config.yml file**: -

**Comment by jiangdashao** [comment]
video, pls

**Comment by DanielAlves123** [comment]
@jiangdashao It happened when you try to go above the water level or go out of the water.

**Comment by Olly32** [comment]
Please post a video of this happening.

**Comment by DanielAlves123** [comment]
@Olly32 go ahead and test if yourself, try using my description as advice.

**Comment by DanielAlves123** [comment]
@jiangdashao no video here but this you fix but this https://github.com/jiangdashao/Matrix-Issues/issues/996 not?

**Comment by SkyLicks** [comment]
I know this issue @jiangdashao.

This issue is caused by swimming vertically (up or down) on a 1.12 server while using 1.14 (Viaversion / Protocol support). It is caused by the new jesus.ver check. Here is a video:

https://youtu.be/4gY2oGOc4K0
