### ISSUE TITLE
[FP] Fly/Speed

### ISSUE THREAD

**Issue by DanielAlves123** [jiangdashao/Matrix-Issues#996]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**: (15:02:07) player Fly | ground spoof | t: fgw.2 a=67.16610926093821 b=-0.0784000015258789 c=0.08307781780646906 (+10) | vl:10 ping:0 tps:20.0 component: fly.fg.w2
(15:02:07) player Fly | t: af (+5) | vl:15 ping:0 tps:20.0 component: nofall.air
(15:02:09) player Speed | suspicious movement:0.507 ar_t:12 lm:0.242 tag:ed (+15) | vl:15 ping:0 tps:20.0 component: speed.main
(15:02:16) player Speed | suspicious movement:0.677 expect:0.615 predict:1.11397563085554 fr:0.6 tag:ea (+5) | vl:20 ping:0 tps:19.94 component: speed.main
(15:02:16) player Speed | suspicious movement:0.64 expect:0.615 predict:0.6415368254595603 fr:0.6 tag:ea (+5) | vl:25 ping:0 tps:19.94 component: speed.main
(15:02:16) player Speed | suspicious movement:0.55 expect:0.542 predict:0.5492070380220349 fr:0.6 tag:eb (+6) | vl:31 ping:0 tps:19.94 component: speed.main
(15:02:19) player Speed | suspicious movement:0.721 expect:0.5795909354025612 predict:0.4857147067165124 gt:1 fr:0.6 tag:b (+8) | vl:39 ping:0 tps:20.0 component: speed.main
(15:02:21) player Block | abort breaking | dig | block at: -2.0,59.0,43.0 type: STAINED_CLAY (+0) | vl:0 ping:0 tps:19.99 component: block.abort
(15:02:50) player Fly | ground spoof | send ground packets when falling | d: 27.649136293380877 (+5) | vl:5 ping:39 tps:20.0 component: fly.fg.nofall
(15:02:50) player Fly | ground spoof | normal | val1: 35.551544693834586 (+5) | vl:10 ping:39 tps:20.0 component: fly.fg.simple
(15:02:50) player Fly | send illegal packet to anti fall damage |  val1: 0.0 val2: 27.649136293380877 val3: true (+10) | vl:20 ping:39 tps:20.0 component: nofall.packet

**How/when does this happen**: when you fight it can drag you back, 1 from these verbose messages happened when i was falling down and i suddenly GOT KILLED IN THE AIR! please fix this
**Video of false positive**: -
**Other information**:  1.14 client version, all of these verbose messages are false positives

## Configuration Files
**Link to checks.yml file**: -
**Link to config.yml file**: -

**Comment by Olly32** [comment]
Please post a video of this happening.

**Comment by DanielAlves123** [comment]
@Olly32 go ahead and test if yourself, try using my description as advice.

**Comment by jiangdashao** [comment]
No video

**Comment by DanielAlves123** [comment]
@jiangdashao why do you need video? Just try fighting, getting knocked while being in air, running in different directions and use for example 2 people, but it happens with 1 too.
