### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by SalvatoreZx** [jiangdashao/Matrix-Issues#998]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ X] The issue happens on default config.yml and checks.yml
- [X ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Error(s) found in console**: https://pastebin.com/CDd6am1m
**How/when does this happen**: After i update the plugin that error spam my console.
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ZakShearman** [comment]
Install ProtocolLib 4.5.0
