### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by kinrokinro** [jiangdashao/Matrix-Issues#999]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X ] Matrix and ProtocolLib are up-to-date
- [ X ] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
Paper-230 1.14.4
**Error(s) found in console**: 
https://pastebin.com/B2kKenc8
**How/when does this happen**: 
Cant say

## Configuration Files
**Link to checks.yml file**: 
https://pastebin.com/TbfAF16x
**Link to config.yml file**:
https://pastebin.com/RnXXxsFM

**Comment by jiangdashao** [comment]
It's a chunk issue, you can disable NPC check temporary
set `killaura.vl_weights.npc` to `-1` (in checks.yml)
